 'use strict';
const {randomUUID}=require('node:crypto'),{id,ref,version,error}=require('../party/policy');
const {digest}=require('../governance/content'),{authorizeOperator}=require('../governance/operator-access'),P=require('./policy');
const one=async(tx,sql,args=[])=>(await tx.execute(sql,args))[0][0];
function checked(r){if(!r)throw error('FINANCE_NOT_FOUND',404);const data=typeof r.data_json==='string'?JSON.parse(r.data_json):r.data_json;if(digest(data)!==r.data_sha256)throw error('STORED_CONTENT_MISMATCH',503);return {...r,data};}
function dto(row){const r=checked(row);return {id:r.id,kind:r.kind,agreement_id:r.agreement_id,owner_party_id:r.owner_party_id,created_by:r.created_by,current_status:r.current_status,object_version:r.object_version,content_sha256:r.data_sha256,data:r.data};}
async function load(tx,key,kind,lock='FOR UPDATE'){const r=dto(await one(tx,'SELECT * FROM finance_records WHERE id=? '+lock,[id(key)]));if(kind&&r.kind!==kind)throw error('FINANCE_NOT_FOUND',404);return r;}
// Public snapshots keep the immutable original hash for exact-version confirmation.
// A participant sees only its own balance; payer and authorized operator see all.
function visibleRecord(r,g,party){if(r.kind!=='SETTLEMENT'||!party||party===g.owner_party_id)return r;return {...r,data:{...r.data,balances:r.data.balances.filter(x=>x.party_id===party)}};}
async function active(tx,key){const p=await one(tx,'SELECT * FROM parties WHERE id=? FOR SHARE',[id(key)]);if(!p||['CLOSED','SUSPENDED'].includes(p.current_status))throw error('FINANCE_PARTY_NOT_ACTIVE',409);return p;}
async function asset(tx,key,owner){const r=await one(tx,"SELECT * FROM supply_assets WHERE id=? AND current_status='READY' FOR SHARE",[id(key)]);if(!r||r.owner_party_id!==owner||!['RIGHTS_EVIDENCE','REVIEW_EVIDENCE','CONSENT_EVIDENCE'].includes(r.purpose))throw error('FINANCE_EVIDENCE_REQUIRED',409);return r;}
function context(db,{resolvePrincipal=async()=>null}={}){
 async function actor(tx,ctx){const principal=await resolvePrincipal(ctx);if(!principal)throw error('AUTHENTICATION_REQUIRED',401);const a=await one(tx,'SELECT * FROM identity_accounts WHERE subject_ref=? FOR SHARE',[ref(principal.subject_ref)]);if(!a||a.current_status!=='ACTIVE')throw error('ACCOUNT_NOT_ACTIVE');return {...a,request_id:ref(principal.request_id||randomUUID())};}
 async function owner(tx,a,party){await active(tx,party);if(!await one(tx,"SELECT id FROM party_memberships WHERE party_id=? AND account_id=? AND current_status='ACTIVE' AND role_code='OWNER' FOR SHARE",[party,a.id]))throw error('FINANCE_PARTY_FORBIDDEN');}
 async function operator(tx,a,g,r,independent=false){if(!await authorizeOperator(tx,{account_id:a.id,action:'FINANCE_REVIEW'}))throw error('FINANCE_REVIEW_FORBIDDEN');if(independent){if(r.created_by===a.id||g.created_by===a.id)throw error('SELF_REVIEW_FORBIDDEN');for(const party of g.data.parties)if(await one(tx,"SELECT id FROM party_memberships WHERE party_id=? AND account_id=? AND current_status='ACTIVE'",[party,a.id]))throw error('SELF_REVIEW_FORBIDDEN');}}
 async function access(tx,a,g,r,party){if(!party)return operator(tx,a,g,r);await owner(tx,a,party);if(!g.data.parties.includes(party))throw error('FINANCE_NOT_FOUND',404);if(['PAYOUT','PAYOUT_EVIDENCE','RECEIPT'].includes(r.kind)&&![g.owner_party_id,r.owner_party_id,r.data.recipient_party_id].includes(party))throw error('FINANCE_NOT_FOUND',404);}
 async function payer(tx,a,g,i){await owner(tx,a,i.party_id);if(g.owner_party_id!==i.party_id)throw error('FINANCE_PAYER_REQUIRED');}
 async function audit(tx,a,r,event){await tx.execute('INSERT INTO finance_audit(id,record_id,actor_account_id,event_code,object_version,data_sha256,request_id) VALUES (?,?,?,?,?,?,?)',[randomUUID(),r.id,a.id,event,r.object_version,r.content_sha256,a.request_id]);}
 async function notify(tx,g,r,event){for(const party of g.data.parties)await tx.execute('INSERT INTO finance_notifications(agreement_id,record_id,party_id,event_code) VALUES (?,?,?,?)',[g.id,r.id,party,event]);}
 async function insert(tx,a,kind,g,party,status,data){const r={id:randomUUID(),kind,agreement_id:g?.id||null,owner_party_id:party,created_by:a.id,current_status:status,object_version:1,content_sha256:digest(data),data};await tx.execute('INSERT INTO finance_records(id,kind,agreement_id,owner_party_id,created_by,current_status,data_json,data_sha256) VALUES (?,?,?,?,?,?,?,?)',[r.id,kind,r.agreement_id,party,a.id,status,JSON.stringify(data),r.content_sha256]);await audit(tx,a,r,kind+'_CREATED');if(g)await notify(tx,g,r,kind+'_CREATED');return r;}
 async function save(tx,a,g,r,status,data,event){const next={...r,current_status:status,object_version:r.object_version+1,content_sha256:digest(data),data};await tx.execute('UPDATE finance_records SET current_status=?,object_version=?,data_json=?,data_sha256=? WHERE id=?',[status,next.object_version,JSON.stringify(data),next.content_sha256,r.id]);await audit(tx,a,next,event);await notify(tx,g,next,event);return next;}
 async function command(tx,a,op,i,fn){const key=digest([a.id,op,ref(i.operation_key)]),hash=digest(i);try{await tx.execute('INSERT INTO finance_commands(id,fingerprint) VALUES (?,?)',[key,hash]);}catch(e){if(e.code!=='ER_DUP_ENTRY')throw e;const r=await one(tx,'SELECT * FROM finance_commands WHERE id=?',[key]);if(r.fingerprint!==hash)throw error('IDEMPOTENCY_CONFLICT',409);if(!r.result_id)throw error('IDEMPOTENCY_IN_PROGRESS',409);return load(tx,r.result_id);}const r=await fn();await tx.execute('UPDATE finance_commands SET result_id=? WHERE id=?',[r.id,key]);return r;}
 async function mutate(ctx,input,op,authorize,fn){const i=P.copy(input);return db.withTransaction(async tx=>{const a=await actor(tx,ctx),hint=await load(tx,i.record_id,null,''),g=await load(tx,hint.agreement_id||hint.id,'AGREEMENT'),r=hint.id===g.id?g:await load(tx,hint.id);await authorize(tx,a,g,r,i);const result=await command(tx,a,op,i,async()=>{if(r.object_version!==version(i.expected_version))throw error('VERSION_CONFLICT',412);return fn(tx,a,g,r,i);});return visibleRecord(result,g,i.party_id);});}
 async function entry(tx,g,source,party,category,value,key,data){P.signed(value);await tx.execute('INSERT INTO finance_entries(agreement_id,party_id,fact_key,category,amount_minor,source_id,data_json,data_sha256) VALUES (?,?,?,?,?,?,?,?)',[g.id,party,digest(key),category,value,source.id,JSON.stringify(data),digest(data)]);}
 async function external(tx,key,r){try{await tx.execute('INSERT INTO finance_external_refs(reference_key,record_id) VALUES (?,?)',[digest(key),r.id]);}catch(e){if(e.code==='ER_DUP_ENTRY')throw error('EXTERNAL_REFERENCE_ALREADY_USED',409);throw e;}}
 return {db,actor,owner,operator,access,payer,audit,notify,insert,save,command,mutate,entry,external};
}
module.exports={context,one,checked,dto,load,active,asset,visibleRecord};
