 'use strict';
const {id,ref,label,shape,error}=require('../party/policy');
const {copy,amount,instant}=require('../trade/policy');
function signed(n){if(!Number.isSafeInteger(n)||Math.abs(n)>900000000000)throw error('INVALID_MONEY',400);return n;}
function shares(rows){if(!Array.isArray(rows)||!rows.length||rows.length>30)throw error('INVALID_SHARES',400);const seen=new Set();let sum=0;for(const x of rows){shape(x,['party_id','bps','role']);id(x.party_id);if(!['SUPPLIER','PLATFORM','MCN','RIGHTSHOLDER','PRODUCER','PARTICIPANT'].includes(x.role)||seen.has(x.party_id)||!Number.isInteger(x.bps)||x.bps<0||x.bps>10000)throw error('INVALID_SHARES',400);seen.add(x.party_id);sum+=x.bps;}if(sum!==10000)throw error('SHARES_NOT_BALANCED',400);return copy(rows);}
// Last explicit recipient takes the integer-minor rounding remainder. Order is part of signed terms.
function split(total,rows){signed(total);shares(rows);let used=0;return rows.map((r,index)=>{const value=index===rows.length-1?total-used:Number(BigInt(total)*BigInt(r.bps)/10000n);used+=value;return {...r,amount_minor:value};});}
function rules(v){shape(v,['version','settlement_at','release_condition','terms','lines']);ref(v.version);instant(v.settlement_at);label(v.terms,8000);if(!['RECEIVED','DELIVERY_ACCEPTED'].includes(v.release_condition)||!Array.isArray(v.lines)||!v.lines.length||v.lines.length>30||new Set(v.lines.map(x=>x.line_id)).size!==v.lines.length)throw error('INVALID_FINANCE_RULE',400);for(const l of v.lines){shape(l,['line_id','shares','deductions']);ref(l.line_id);shares(l.shares);if(!Array.isArray(l.deductions)||l.deductions.length>30)throw error('INVALID_DEDUCTIONS',400);for(const fee of l.deductions){shape(fee,['category','party_id','amount_minor','basis','refund_behavior']);if(!['CHANNEL_FEE','TAX','DISCOUNT','OTHER'].includes(fee.category)||!l.shares.some(s=>s.party_id===fee.party_id))throw error('INVALID_DEDUCTION',400);amount(fee.amount_minor,true);if(!['RETAIN','PROPORTIONAL'].includes(fee.refund_behavior))throw error('INVALID_DEDUCTION',400);label(fee.basis,2000);}}return copy(v);}
function adjustment(v,parties){if(!Array.isArray(v)||v.length<2||v.length>30||new Set(v.map(x=>x.party_id)).size!==v.length)throw error('INVALID_ADJUSTMENT',400);let sum=0;for(const x of v){shape(x,['party_id','amount_minor']);if(!parties.includes(id(x.party_id)))throw error('ADJUSTMENT_PARTY_MISMATCH',409);sum+=signed(x.amount_minor);}if(sum!==0)throw error('ADJUSTMENT_NOT_BALANCED',409);return copy(v);}
module.exports={copy,amount,instant,signed,shares,split,rules,adjustment};
