 'use strict';
const {id,ref,label,shape,error}=require('../party/policy'),{digest}=require('../governance/content'),C=require('./context'),S=require('./source'),P=require('./policy');
const {one,load,dto}=C;
const CHECKS=['parties_verified','contract_verified','amount_verified','evidence_verified'];
function methods(H){const {db,actor,access,operator,payer,mutate,insert,save,entry,external,accrue}=H;return {
 async review(ctx,i){shape(i,['record_id','expected_version','decision','reason','verification','operation_key']);label(i.reason,4000);shape(i.verification,CHECKS);if(CHECKS.some(k=>typeof i.verification[k]!=='boolean'))throw error('INVALID_VERIFICATION',400);if(!['APPROVED','REJECTED'].includes(i.decision))throw error('INVALID_REVIEW',400);return mutate(ctx,i,'REVIEW',(tx,a,g,r)=>operator(tx,a,g,r,true),async(tx,a,g,r)=>{if(!['AGREEMENT','STATEMENT','RECEIPT','SETTLEMENT','ADJUSTMENT','PAYOUT','PAYOUT_EVIDENCE'].includes(r.kind)||!['IN_REVIEW','REQUESTED'].includes(r.current_status))throw error('FINANCE_REVIEW_NOT_PENDING',409);if(i.decision==='APPROVED'&&CHECKS.some(k=>i.verification[k]!==true))throw error('FINANCE_VERIFICATION_REQUIRED',409);
 const data={...r.data,review:{decision:i.decision,reason:i.reason,verification:i.verification,reviewer_account_id:a.id,method:'INDEPENDENT_MANUAL_EVIDENCE_REVIEW'}};
 if(i.decision==='REJECTED')return save(tx,a,g,r,'REJECTED',data,'FINANCE_REJECTED');
 if(r.kind==='AGREEMENT'){const source=await S.source(tx,g.data.source_type,g.data.source_id);if(source.hash!==g.data.source_sha256)throw error('FINANCE_SOURCE_CHANGED',409);await C.asset(tx,g.data.evidence_asset_id,g.owner_party_id);S.validateRules(source,g.data.rules,g.data.source_type);}
 else await S.liveAgreement(tx,g);
 if(r.kind==='STATEMENT'){await C.asset(tx,r.data.evidence_asset_id,g.owner_party_id);if(r.data.direction==='DEBIT'){const old=await load(tx,r.data.original_statement_id,'STATEMENT'),[rows]=await tx.execute("SELECT * FROM finance_records WHERE agreement_id=? AND kind='STATEMENT' AND current_status='APPROVED' FOR SHARE",[g.id]);const used=rows.map(dto).filter(x=>x.data.original_statement_id===old.id).reduce((n,x)=>n-x.data.net_minor,0);if(used-r.data.net_minor>old.data.net_minor)throw error('CORRECTION_EXCEEDS_STATEMENT',409);}await external(tx,['CHANNEL_STATEMENT',g.data.environment,g.owner_party_id,(await S.source(tx,'RELEASE',g.data.source_id)).record.data.channel_id,r.data.external_reference],r);}
 if(r.kind==='RECEIPT'){await C.asset(tx,r.data.evidence_asset_id,g.owner_party_id);const statement=await load(tx,r.data.statement_id,'STATEMENT'),[rows]=await tx.execute("SELECT * FROM finance_records WHERE agreement_id=? AND kind='RECEIPT' AND current_status='APPROVED' FOR SHARE",[g.id]);const used=rows.map(dto).filter(x=>x.data.statement_id===statement.id).reduce((s,x)=>s+x.data.amount_minor,0);if(used+r.data.amount_minor>statement.data.net_minor)throw error('RECEIPT_EXCEEDS_STATEMENT',409);await external(tx,['BANK_EVENT',g.data.environment,g.owner_party_id,r.data.external_reference],r);}
 if(r.kind==='SETTLEMENT'){if(r.data.facts_sha256!==(await S.facts(tx,g)).hash)throw error('SETTLEMENT_SOURCE_CHANGED',409);}
 if(r.kind==='ADJUSTMENT'){await C.asset(tx,r.data.evidence_asset_id,g.owner_party_id);P.adjustment(r.data.entries,g.data.parties);for(const x of r.data.entries)await entry(tx,g,r,x.party_id,'ADJUSTMENT',x.amount_minor,['ADJUSTMENT',r.id],{reason:r.data.reason,evidence_asset_id:r.data.evidence_asset_id});}
 if(r.kind==='PAYOUT'){const available=await S.payable(tx,g,r.data.recipient_party_id,{exclude:r.id});if(r.data.amount_minor>available.available_minor)throw error('PAYOUT_EXCEEDS_AVAILABLE',409);await C.asset(tx,r.data.destination_asset_id,r.data.destination_owner_party_id);}
 if(r.kind==='PAYOUT_EVIDENCE'){await C.asset(tx,r.data.evidence_asset_id,g.owner_party_id);const payout=await load(tx,r.data.payout_id,'PAYOUT'),outcome=r.data.outcome;if(!(payout.current_status==='APPROVED'&&['PAID','FAILED'].includes(outcome)||payout.current_status==='PAID'&&outcome==='RETURNED')||r.data.amount_minor!==payout.data.amount_minor)throw error('PAYOUT_EVIDENCE_STALE',409);await external(tx,['BANK_EVENT',g.data.environment,g.owner_party_id,r.data.external_reference],r);if(outcome!=='FAILED')await entry(tx,g,r,payout.data.recipient_party_id,outcome==='PAID'?'PAYOUT':'PAYOUT_RETURN',outcome==='PAID'?-r.data.amount_minor:r.data.amount_minor,['PAYOUT_RESULT',r.id],{payout_id:payout.id,external_reference:r.data.external_reference,evidence_asset_id:r.data.evidence_asset_id,method:'EXTERNAL_MANUAL_PAYMENT'});await save(tx,a,g,payout,outcome,{...payout.data,last_evidence_id:r.id},'PAYOUT_'+outcome);}
 return save(tx,a,g,r,'APPROVED',data,'FINANCE_APPROVED');});},
 async reconcile(ctx,i){shape(i,['record_id','party_id','expected_version','provider','environment','external_reference','items','evidence_asset_id','operation_key']);ref(i.external_reference);if(!['APPLE','ALIPAY'].includes(i.provider)||!['SANDBOX','PRODUCTION'].includes(i.environment)||!Array.isArray(i.items)||i.items.length>200)throw error('INVALID_RECONCILIATION',400);const keys=new Set();for(const x of i.items){shape(x,['record_id','direction','external_reference','amount_minor']);id(x.record_id);ref(x.external_reference);P.amount(x.amount_minor,true);if(!['RECEIPT','REFUND'].includes(x.direction)||keys.has(x.record_id))throw error('INVALID_RECONCILIATION',400);keys.add(x.record_id);}return mutate(ctx,i,'RECONCILE',(tx,a,g,r)=>payer(tx,a,g,i),async(tx,a,g,r)=>{if(r.kind!=='AGREEMENT'||g.data.source_type!=='ORDER'||g.data.environment!==i.environment)throw error('RECONCILIATION_SCOPE_MISMATCH',409);await C.asset(tx,i.evidence_asset_id,i.party_id);const f=await S.facts(tx,g),actual=f.references.filter(x=>x.provider===i.provider&&x.environment===i.environment),differences=[];for(const row of actual){const v=i.items.find(x=>x.record_id===row.record_id);if(!v)differences.push({record_id:row.record_id,reason:'MISSING_IN_EXTERNAL_STATEMENT'});else if(v.direction!==row.direction||v.amount_minor!==row.amount_minor||v.external_reference!==row.external_reference)differences.push({record_id:row.record_id,reason:'FACT_MISMATCH'});}for(const row of i.items)if(!actual.some(x=>x.record_id===row.record_id))differences.push({record_id:row.record_id,reason:'UNKNOWN_PLATFORM_FACT'});return insert(tx,a,'RECONCILIATION',g,g.owner_party_id,differences.length?'DIFFERENCES':'MATCHED',{provider:i.provider,environment:i.environment,external_reference:i.external_reference,items:i.items,facts_sha256:f.hash,differences,evidence_asset_id:id(i.evidence_asset_id),meaning:'COMPARISON_ONLY_NOT_A_PAYMENT_OR_MANUAL_APPROVAL'});});},
 async confirmations(ctx,{record_id,party_id}){return db.withTransaction(async tx=>{const a=await actor(tx,ctx),r=await load(tx,record_id,null,'FOR SHARE'),g=r.kind==='AGREEMENT'?r:await load(tx,r.agreement_id,'AGREEMENT','FOR SHARE');await access(tx,a,g,r,party_id);const [rows]=await tx.execute('SELECT party_id,decision,content_sha256,reason FROM finance_confirmations WHERE record_id=? ORDER BY party_id',[r.id]);return {items:rows};});},
 async readiness(ctx,{record_id,party_id}){return db.withTransaction(async tx=>{const a=await actor(tx,ctx),g=await load(tx,record_id,'AGREEMENT','FOR SHARE');await access(tx,a,g,g,party_id);return {environment:g.data.environment,automatic_payout:{current_status:'NOT_IMPLEMENTED',reason_code:'PAYOUT_PROVIDER_NOT_VERIFIED'},manual_payment:{current_status:'IMPLEMENTED',meaning:'Requires an actual external payment, private receipt and independent verification; not already paid'}};});},
 };}
module.exports={methods,CHECKS};
