 'use strict';
const {id,error}=require('../party/policy'),{digest}=require('../governance/content'),C=require('./context'),P=require('./policy');
const {one,checked,load,dto}=C;
async function source(tx,type,key){if(type==='ORDER'){const r=checked(await one(tx,"SELECT * FROM trade_records WHERE id=? AND kind='ORDER' FOR SHARE",[id(key)]));return {payer:r.merchant_party_id,parties:[r.buyer_party_id,r.merchant_party_id,...r.data.quote.lines.map(x=>x.provider_party_id),...(r.data.quote.commercial?.relation?[r.data.quote.commercial.relation.mcn_party_id]:[])],hash:digest(r.data.contract),record:r};}if(type==='RELEASE'){const r=checked(await one(tx,"SELECT * FROM project_records WHERE id=? AND kind='RELEASE' FOR SHARE",[id(key)]));if(!['EXTERNAL_PUBLISHED','EXTERNAL_WITHDRAWN'].includes(r.current_status))throw error('RELEASE_NOT_VERIFIED',409);const e=checked(await one(tx,"SELECT * FROM project_records WHERE id=? AND kind='EDITION' FOR SHARE",[r.data.edition_id]));return {payer:r.owner_party_id,parties:[r.owner_party_id,...e.data.confirmers.map(x=>x.party_id)],hash:digest({edition_id:e.id,content_sha256:e.data_sha256,channel_id:r.data.channel_id}),record:r};}throw error('INVALID_FINANCE_SOURCE',400);}
function validateRules(info,rules,type){if(type==='ORDER'){const lines=info.record.data.quote.lines;if(rules.lines.length!==lines.length)throw error('FINANCE_LINES_MISMATCH',409);for(const r of rules.lines){const l=lines.find(x=>x.line_id===r.line_id);if(!l||!r.shares.some(x=>x.party_id===l.provider_party_id))throw error('FINANCE_LINES_MISMATCH',409);if(r.deductions.reduce((s,x)=>s+x.amount_minor,0)>l.total_minor)throw error('DEDUCTIONS_EXCEED_PRICE',409);const c=info.record.data.quote.commercial;if(c){const supplier=r.shares.find(x=>x.party_id===l.provider_party_id),platform=r.shares.filter(x=>x.role==='PLATFORM'),mcn=r.shares.filter(x=>x.role==='MCN');if(['PLATFORM','MCN'].includes(supplier.role)||(!c.relation&&mcn.length)||supplier.bps!==10000-c.commission.platform_bps||platform.length!==1||platform[0].bps!==c.commission.platform_bps-c.commission.mcn_bps||r.shares.length!==(c.relation?3:2)||(c.relation&&(mcn.length!==1||mcn[0].party_id!==c.relation.mcn_party_id||mcn[0].bps!==c.commission.mcn_bps)))throw error('HISTORICAL_COMMISSION_MISMATCH',409);}}}else if(rules.lines.length!==1||rules.lines[0].line_id!=='revenue'||rules.lines[0].deductions.some(x=>['CHANNEL_FEE','TAX'].includes(x.category)))throw error('REVENUE_DEDUCTIONS_ALREADY_IN_STATEMENT',409);}
async function facts(tx,g){const info=await source(tx,g.data.source_type,g.data.source_id);if(info.hash!==g.data.source_sha256)throw error('FINANCE_SOURCE_CHANGED',409);let lines=[],references=[],environment=null,receivable=0,received=0;
 if(g.data.source_type==='ORDER'){
  const order=info.record,totals=new Map(order.data.quote.lines.map(x=>[x.line_id,{line_id:x.line_id,gross_minor:0,refund_minor:0,base_minor:x.total_minor}]));
  const [rows]=await tx.execute('SELECT j.id,j.direction,j.amount_minor,r.id AS record_id,r.data_json,r.data_sha256 FROM trade_journal j JOIN trade_records r ON r.id=j.source_id WHERE j.order_id=? ORDER BY j.id',[order.id]);
  for(const row of rows){const r=checked(row).data;if(environment&&environment!==r.environment)throw error('MIXED_PAYMENT_ENVIRONMENT',409);environment=r.environment;if(!['ALIPAY','APPLE'].includes(r.provider))throw error('UNKNOWN_FINANCE_PROVIDER',409);references.push({id:row.id,record_id:row.record_id,direction:row.direction,provider:r.provider,environment:r.environment,external_reference:row.direction==='RECEIPT'?r.transaction_id:row.record_id,amount_minor:Number(row.amount_minor),sha256:row.data_sha256});for(const a of r.allocations){const t=totals.get(a.line_id);if(!t)throw error('FINANCE_LINE_UNKNOWN',409);t[row.direction==='RECEIPT'?'gross_minor':'refund_minor']+=a.amount_minor;}}
  lines=[...totals.values()].map(x=>({...x,net_minor:x.gross_minor-x.refund_minor}));for(const x of lines)if(x.net_minor<0||x.gross_minor>x.base_minor)throw error('FINANCE_FACTS_INVALID',409);received=lines.reduce((s,x)=>s+x.net_minor,0);receivable=order.data.quote.total_minor-lines.reduce((s,x)=>s+x.gross_minor,0);
 }else{
  const [rows]=await tx.execute("SELECT * FROM finance_records WHERE agreement_id=? AND kind IN ('STATEMENT','RECEIPT') AND current_status='APPROVED' ORDER BY id FOR SHARE",[g.id]);let recognized=0;
  for(const r of rows.map(dto)){if(r.data.environment!==g.data.environment)throw error('MIXED_PAYMENT_ENVIRONMENT',409);if(r.kind==='STATEMENT'){recognized=P.signed(recognized+r.data.net_minor);references.push({id:r.id,direction:'STATEMENT',sha256:r.content_sha256,amount_minor:r.data.net_minor});}else{received=P.signed(received+r.data.amount_minor);references.push({id:r.id,direction:'RECEIPT',sha256:r.content_sha256,amount_minor:r.data.amount_minor});}}
  environment=g.data.environment;receivable=recognized-received;lines=[{line_id:'revenue',gross_minor:recognized,refund_minor:0,net_minor:recognized,base_minor:recognized}];
 }
 if(environment&&environment!==g.data.environment)throw error('PAYMENT_ENVIRONMENT_MISMATCH',409);
 const adjustments=(await tx.execute("SELECT * FROM finance_records WHERE agreement_id=? AND kind='ADJUSTMENT' AND current_status='APPROVED' ORDER BY id FOR SHARE",[g.id]))[0].map(dto);
 const hash=digest({lines,references,adjustments:adjustments.map(x=>({id:x.id,hash:x.content_sha256}))});return {info,lines,references,adjustments,hash,environment:environment||g.data.environment,received_minor:received,receivable_minor:receivable};
}
function targets(g,f){const totals=Object.fromEntries(g.data.parties.map(x=>[x,0]));for(const r of g.data.rules.lines){const l=f.lines.find(x=>x.line_id===r.line_id);let shares=P.split(l.net_minor,r.shares);const c=f.info.record.data.quote?.commercial;if(c){const fee=Number(BigInt(l.net_minor)*BigInt(c.commission.platform_bps)/10000n),mcn=Number(BigInt(l.net_minor)*BigInt(c.commission.mcn_bps)/10000n);shares=r.shares.map(s=>({...s,amount_minor:s.role==='PLATFORM'?fee-mcn:s.role==='MCN'?mcn:l.net_minor-fee}));}for(const s of shares)totals[s.party_id]=P.signed(totals[s.party_id]+s.amount_minor);for(const fee of r.deductions){const value=fee.refund_behavior==='PROPORTIONAL'?(l.base_minor>0?Number(BigInt(fee.amount_minor)*BigInt(l.net_minor)/BigInt(l.base_minor)):0):(l.gross_minor>0?fee.amount_minor:0);totals[fee.party_id]=P.signed(totals[fee.party_id]-value);}}return totals;}
async function confirmed(tx,r,parties){const [rows]=await tx.execute('SELECT party_id,decision,content_sha256 FROM finance_confirmations WHERE record_id=?',[r.id]);if(parties.some(p=>!rows.some(x=>x.party_id===p&&x.decision==='APPROVED'&&x.content_sha256===r.content_sha256)))throw error('FINANCE_CONFIRMATIONS_REQUIRED',409);}
async function liveAgreement(tx,g){if(g.current_status!=='APPROVED')throw error('FINANCE_AGREEMENT_NOT_APPROVED',409);await confirmed(tx,g,g.data.parties);}
async function freeze(tx,g){const [rows]=await tx.execute("SELECT id FROM finance_records WHERE agreement_id=? AND kind='DISPUTE' AND current_status IN ('OPEN','ACTION_REQUIRED') FOR SHARE",[g.id]);if(rows.length)throw error('FINANCE_DISPUTED',409);}
async function totals(tx,g){const [rows]=await tx.execute('SELECT party_id,category,SUM(amount_minor) AS amount_minor FROM finance_entries WHERE agreement_id=? GROUP BY party_id,category',[g.id]);const result=Object.fromEntries(g.data.parties.map(x=>[x,{accrued_minor:0,adjustment_minor:0,paid_minor:0,balance_minor:0}]));for(const row of rows){const n=P.signed(Number(row.amount_minor)),r=result[row.party_id];r.balance_minor=P.signed(r.balance_minor+n);if(row.category==='ACCRUAL')r.accrued_minor=n;else if(row.category==='ADJUSTMENT')r.adjustment_minor=n;else r.paid_minor-=n;}return result;}
async function payable(tx,g,recipient,{exclude=null}={}){await liveAgreement(tx,g);await freeze(tx,g);for(const party of g.data.parties)await C.active(tx,party);if(g.owner_party_id===recipient)throw error('RETAINED_INCOME_NOT_PAYOUT',409);if(g.data.rules.settlement_at>new Date().toISOString())throw error('SETTLEMENT_DATE_NOT_REACHED',409);const f=await facts(tx,g);if(g.data.source_type==='ORDER'&&f.info.record.current_status==='PAYMENT_REVIEW_REQUIRED')throw error('CUSTOMER_PAYMENT_REVIEW_REQUIRED',409);if(g.data.source_type==='RELEASE'&&f.receivable_minor>0)throw error('REVENUE_NOT_RECEIVED',409);if(g.data.rules.release_condition==='DELIVERY_ACCEPTED'&&g.data.source_type==='ORDER'){const order=f.info.record;for(const line of order.data.quote.lines.filter(x=>x.line_kind==='PRODUCTION'))if(!await one(tx,"SELECT p.id FROM production_records p JOIN production_order_lines l ON l.project_id=p.id WHERE p.kind='PROJECT' AND l.order_id=? AND l.line_id=? AND p.current_status='ACCEPTED' FOR SHARE",[order.id,line.line_id]))throw error('FINANCE_DELIVERY_NOT_ACCEPTED',409);}
 const [rows]=await tx.execute("SELECT * FROM finance_records WHERE agreement_id=? AND kind='SETTLEMENT' AND current_status='APPROVED' ORDER BY id FOR SHARE",[g.id]);let found=false;for(const row of rows.map(dto)){if(row.data.facts_sha256!==f.hash)continue;try{await confirmed(tx,row,g.data.parties);found=true;break;}catch(e){if(e.code!=='FINANCE_CONFIRMATIONS_REQUIRED')throw e;}}if(!found)throw error('CURRENT_SETTLEMENT_CONFIRMATION_REQUIRED',409);
 const balances=await totals(tx,g),[pending]=await tx.execute("SELECT * FROM finance_records WHERE agreement_id=? AND kind='PAYOUT' AND current_status IN ('REQUESTED','APPROVED') FOR SHARE",[g.id]);const reserved=pending.map(dto).filter(x=>x.id!==exclude&&x.data.recipient_party_id===recipient).reduce((n,x)=>n+x.data.amount_minor,0);return {available_minor:Math.max(0,(balances[recipient]?.balance_minor||0)-reserved),facts:f};}
module.exports={source,validateRules,facts,targets,confirmed,liveAgreement,freeze,totals,payable};
