import {ApiError,request,requestBytes,type ApiResult} from '../client'
import {validSupplyId,getSupplyAsset,postSupply,type SupplyIdentity,type SupplyAsset,type SupplyWrite} from './supply'
import {iso,parseMoney} from './projects'
import type {TextValue} from './contracts'
export {iso,parseMoney}
export type Environment='SANDBOX'|'PRODUCTION'
export interface Share {party_id:string;bps:number;role:'SUPPLIER'|'PLATFORM'|'MCN'|'RIGHTSHOLDER'|'PRODUCER'|'PARTICIPANT'}
export interface Deduction {category:'CHANNEL_FEE'|'TAX'|'DISCOUNT'|'OTHER';party_id:string;amount_minor:number;basis:string;refund_behavior:'RETAIN'|'PROPORTIONAL'}
export interface Rules {version:string;settlement_at:string;release_condition:'RECEIVED'|'DELIVERY_ACCEPTED';terms:string;lines:{line_id:string;shares:Share[];deductions:Deduction[]}[]}
export const checks={parties_verified:'主体已核实',contract_verified:'合同已核实',amount_verified:'金额已核实',evidence_verified:'凭据已核实'} as const
export interface Review {decision:'APPROVED'|'REJECTED';reason:string;verification:Record<keyof typeof checks,boolean>;reviewer_account_id:string;method:'INDEPENDENT_MANUAL_EVIDENCE_REVIEW'}
export interface Balance {party_id:string;accrued_minor:number;adjustment_minor:number;paid_minor:number;balance_minor:number}
export interface AvailableBalance extends Balance {expected_accrued_minor:number;available_minor:number;recovery_due_minor:number;reason_code:string|null;meaning:'MERCHANT_RETAINED_NOT_TRANSFER'|'PAYABLE_NOT_YET_TRANSFERRED'}
export type SourceReference={id:string;record_id:string;direction:'RECEIPT'|'REFUND';provider:'APPLE'|'ALIPAY';environment:Environment;external_reference:string;amount_minor:number;sha256:string}|{id:string;direction:'STATEMENT'|'RECEIPT';sha256:string;amount_minor:number}
export interface AdjustmentEntry {party_id:string;amount_minor:number}
export interface ExternalLine {record_id:string;direction:'RECEIPT'|'REFUND';external_reference:string;amount_minor:number}
interface Base {id:string;agreement_id:string|null;owner_party_id:string;created_by:string;current_status:string;object_version:number;content_sha256:string}
export type FinanceRecord=Base&(
 {kind:'AGREEMENT';data:{previous_agreement_id:string|null;source_type:'ORDER'|'RELEASE';source_id:string;source_sha256:string;environment:Environment;currency:'CNY';rule_id:string;rule_snapshot:{id:string;terms:Record<string,TextValue>;version:string;rule_key:string;content_sha256:string;format_version:string};rules:Rules;parties:string[];evidence_asset_id:string;review:Review|null}}|
 {kind:'SETTLEMENT';data:{period_reference:string;note:string;facts_sha256:string;source_references:SourceReference[];received_minor:number;receivable_minor:number;balances:Balance[];rule_sha256:string;review:Review|null}}|
 {kind:'PAYOUT';data:{recipient_party_id:string;amount_minor:number;destination_asset_id:string;destination_owner_party_id:string;note:string;method:'EXTERNAL_MANUAL_PAYMENT';review:Review|null;cancel_reason?:string;last_evidence_id?:string}}|
 {kind:'PAYOUT_EVIDENCE';data:{payout_id:string;recipient_party_id:string;outcome:'PAID'|'FAILED'|'RETURNED';amount_minor:number;external_reference:string;occurred_at:string;evidence_asset_id:string;note:string;review:Review|null;method:'EXTERNAL_MANUAL_EVIDENCE'}}|
 {kind:'STATEMENT';data:{external_reference:string;period_start:string;period_end:string;gross_minor:number;refund_minor:number;channel_fee_minor:number;tax_minor:number;net_minor:number;direction:'CREDIT'|'DEBIT';original_statement_id:string|null;evidence_asset_id:string;note:string;environment:Environment;review:Review|null}}|
 {kind:'RECEIPT';data:{statement_id:string;amount_minor:number;external_reference:string;occurred_at:string;evidence_asset_id:string;note:string;environment:Environment;review:Review|null}}|
 {kind:'ADJUSTMENT';data:{entries:AdjustmentEntry[];reason:string;evidence_asset_id:string;review:Review|null}}|
 {kind:'RECONCILIATION';data:{provider:'APPLE'|'ALIPAY';environment:Environment;external_reference:string;items:ExternalLine[];facts_sha256:string;differences:{record_id:string;reason:'MISSING_IN_EXTERNAL_STATEMENT'|'FACT_MISMATCH'|'UNKNOWN_PLATFORM_FACT'}[];evidence_asset_id:string;meaning:'COMPARISON_ONLY_NOT_A_PAYMENT_OR_MANUAL_APPROVAL'}}|
 {kind:'DISPUTE';data:{about_record_id:string;category:'QUALITY'|'REFUND'|'RIGHTS_DEFECT'|'EXCLUSIVITY'|'SETTLEMENT'|'OTHER';reason:string;evidence_asset_ids:string[];decision_history:{decision:'ACTION_REQUIRED'|'RESUME'|'REMEDIED';reason:string;action_record_id:string|null;reviewer_account_id:string}[]}}|
 {kind:'RESPONSE';data:{dispute_id:string;message:string;evidence_asset_ids:string[]}})
export type FinanceKind=FinanceRecord['kind']
export type ChildKind=Exclude<FinanceKind,'AGREEMENT'>
export interface FinancePage {items:FinanceRecord[];next_cursor:string|null}
export interface Confirmation {party_id:string;content_sha256:string;decision:'APPROVED'|'REJECTED';reason:string}
export interface Balances {agreement_id:string;currency:'CNY';environment:Environment;customer_payment_separate:true;received_minor:number;receivable_minor:number;items:AvailableBalance[]}
export interface Readiness {environment:Environment;automatic_payout:{current_status:'NOT_IMPLEMENTED';reason_code:'PAYOUT_PROVIDER_NOT_VERIFIED'};manual_payment:{current_status:'IMPLEMENTED';meaning:string}}
export type Entry={id:string;party_id:string;amount_minor:number;source_id:string}&({category:'ACCRUAL';data:{facts_sha256:string;source_references:SourceReference[];target_minor:number}}|{category:'ADJUSTMENT';data:{reason:string;evidence_asset_id:string}}|{category:'PAYOUT'|'PAYOUT_RETURN';data:{payout_id:string;external_reference:string;evidence_asset_id:string;method:'EXTERNAL_MANUAL_PAYMENT'}})
export interface Notification {id:string;agreement_id:string;record_id:string;event_code:string}
export interface FinanceWrite {path:string;body?:unknown;version?:number;targetId?:string;agreementId?:string;resultKind:FinanceKind|'ASSET';label:string;supply?:SupplyWrite;confirmation?:boolean}
export type FinanceResult=FinanceRecord|SupplyAsset
const obj=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==='object'&&!Array.isArray(v)
const exact=(v:unknown,keys:string[],optional:string[]=[]):v is Record<string,unknown>=>obj(v)&&keys.every(k=>Object.hasOwn(v,k))&&Object.keys(v).every(k=>keys.includes(k)||optional.includes(k))
const str=(v:unknown,max=8000):v is string=>typeof v==='string'&&v.trim().length>0&&v.length<=max
const amount=(v:unknown,min=0,max=900000000000):v is number=>Number.isSafeInteger(v)&&Number(v)>=min&&Number(v)<=max
const signed=(v:unknown)=>amount(v,-900000000000)
const hash=(v:unknown)=>typeof v==='string'&&/^[a-f0-9]{64}$/.test(v)
const nullableId=(v:unknown)=>v===null||validSupplyId(v)
const environment=(v:unknown):v is Environment=>v==='SANDBOX'||v==='PRODUCTION'
const ids=(v:unknown,max=100)=>Array.isArray(v)&&v.length<=max&&v.every(validSupplyId)&&new Set(v).size===v.length
const incremental=(v:unknown)=>typeof v==='string'&&/^[1-9][0-9]*$/.test(v)&&Number.isSafeInteger(Number(v))
export function isRules(v:unknown):v is Rules {
 if(!exact(v,['version','settlement_at','release_condition','terms','lines'])||!str(v.version,128)||!iso(v.settlement_at)||!['RECEIVED','DELIVERY_ACCEPTED'].includes(String(v.release_condition))||!str(v.terms)||!Array.isArray(v.lines)||!v.lines.length||v.lines.length>30||new Set(v.lines.map(l=>obj(l)?l.line_id:null)).size!==v.lines.length)return false
 return v.lines.every(l=>exact(l,['line_id','shares','deductions'])&&str(l.line_id,128)&&Array.isArray(l.shares)&&l.shares.length>0&&l.shares.length<=30&&new Set(l.shares.map(s=>obj(s)?s.party_id:null)).size===l.shares.length&&l.shares.every(s=>exact(s,['party_id','bps','role'])&&validSupplyId(s.party_id)&&amount(s.bps,0,10000)&&['SUPPLIER','PLATFORM','MCN','RIGHTSHOLDER','PRODUCER','PARTICIPANT'].includes(String(s.role)))&&l.shares.reduce((n,s)=>n+Number(s.bps),0)===10000&&Array.isArray(l.deductions)&&l.deductions.length<=30&&l.deductions.every(f=>exact(f,['category','party_id','amount_minor','basis','refund_behavior'])&&['CHANNEL_FEE','TAX','DISCOUNT','OTHER'].includes(String(f.category))&&validSupplyId(f.party_id)&&(l.shares as Share[]).some(s=>s.party_id===f.party_id)&&amount(f.amount_minor)&&str(f.basis,2000)&&['RETAIN','PROPORTIONAL'].includes(String(f.refund_behavior))))
}
function review(v:unknown){return v===null||exact(v,['decision','reason','verification','reviewer_account_id','method'])&&['APPROVED','REJECTED'].includes(String(v.decision))&&str(v.reason,4000)&&validSupplyId(v.reviewer_account_id)&&v.method==='INDEPENDENT_MANUAL_EVIDENCE_REVIEW'&&exact(v.verification,Object.keys(checks))&&Object.values(v.verification).every(x=>typeof x==='boolean')&&(v.decision!=='APPROVED'||Object.values(v.verification).every(x=>x===true))}
const balance=(v:unknown)=>exact(v,['party_id','accrued_minor','adjustment_minor','paid_minor','balance_minor'])&&validSupplyId(v.party_id)&&['accrued_minor','adjustment_minor','paid_minor','balance_minor'].every(k=>signed(v[k]))
const adjustment=(v:unknown)=>Array.isArray(v)&&v.length>=2&&v.length<=30&&new Set(v.map(x=>obj(x)?x.party_id:null)).size===v.length&&v.every(x=>exact(x,['party_id','amount_minor'])&&validSupplyId(x.party_id)&&signed(x.amount_minor))&&v.reduce((n,x)=>n+Number(x.amount_minor),0)===0
const externalLine=(v:unknown)=>exact(v,['record_id','direction','external_reference','amount_minor'])&&validSupplyId(v.record_id)&&['RECEIPT','REFUND'].includes(String(v.direction))&&str(v.external_reference,128)&&amount(v.amount_minor)
const sourceReference=(v:unknown)=>exact(v,['id','record_id','direction','provider','environment','external_reference','amount_minor','sha256'])&&validSupplyId(v.id)&&validSupplyId(v.record_id)&&['RECEIPT','REFUND'].includes(String(v.direction))&&['APPLE','ALIPAY'].includes(String(v.provider))&&environment(v.environment)&&str(v.external_reference,128)&&amount(v.amount_minor)&&hash(v.sha256)||exact(v,['id','direction','sha256','amount_minor'])&&validSupplyId(v.id)&&['STATEMENT','RECEIPT'].includes(String(v.direction))&&signed(v.amount_minor)&&hash(v.sha256)
export function isFinanceRecord(v:unknown):v is FinanceRecord {
 if(!exact(v,['id','kind','agreement_id','owner_party_id','created_by','current_status','object_version','content_sha256','data'])||![v.id,v.owner_party_id,v.created_by].every(validSupplyId)||!amount(v.object_version,1)||!hash(v.content_sha256)||!obj(v.data))return false
 const d=v.data,s=String(v.current_status),child=validSupplyId(v.agreement_id),reviewStatus=['IN_REVIEW','APPROVED','REJECTED'].includes(s)
 switch(v.kind){
 case 'AGREEMENT':return v.agreement_id===null&&['IN_REVIEW','APPROVED','REJECTED','SUPERSEDED'].includes(s)&&exact(d,['previous_agreement_id','source_type','source_id','source_sha256','environment','currency','rule_id','rule_snapshot','rules','parties','evidence_asset_id','review'])&&nullableId(d.previous_agreement_id)&&['ORDER','RELEASE'].includes(String(d.source_type))&&validSupplyId(d.source_id)&&hash(d.source_sha256)&&environment(d.environment)&&d.currency==='CNY'&&validSupplyId(d.rule_id)&&exact(d.rule_snapshot,['id','terms','version','rule_key','content_sha256','format_version'])&&validSupplyId(d.rule_snapshot.id)&&obj(d.rule_snapshot.terms)&&['version','rule_key','format_version'].every(k=>str((d.rule_snapshot as Record<string,unknown>)[k]))&&hash(d.rule_snapshot.content_sha256)&&isRules(d.rules)&&ids(d.parties)&&validSupplyId(d.evidence_asset_id)&&review(d.review)
 case 'SETTLEMENT':return child&&reviewStatus&&exact(d,['period_reference','note','facts_sha256','source_references','received_minor','receivable_minor','balances','rule_sha256','review'])&&str(d.period_reference)&&str(d.note)&&hash(d.facts_sha256)&&Array.isArray(d.source_references)&&d.source_references.every(sourceReference)&&amount(d.received_minor)&&signed(d.receivable_minor)&&Array.isArray(d.balances)&&d.balances.every(balance)&&hash(d.rule_sha256)&&review(d.review)
 case 'PAYOUT':return child&&['REQUESTED','CANCELLED','APPROVED','REJECTED','PAID','FAILED','RETURNED'].includes(s)&&exact(d,['recipient_party_id','amount_minor','destination_asset_id','destination_owner_party_id','note','method','review'],['cancel_reason','last_evidence_id'])&&[d.recipient_party_id,d.destination_asset_id,d.destination_owner_party_id].every(validSupplyId)&&amount(d.amount_minor,1)&&str(d.note)&&d.method==='EXTERNAL_MANUAL_PAYMENT'&&review(d.review)&&(!Object.hasOwn(d,'cancel_reason')||str(d.cancel_reason,2000))&&(!Object.hasOwn(d,'last_evidence_id')||validSupplyId(d.last_evidence_id))
 case 'PAYOUT_EVIDENCE':return child&&reviewStatus&&exact(d,['payout_id','recipient_party_id','outcome','amount_minor','external_reference','occurred_at','evidence_asset_id','note','review','method'])&&[d.payout_id,d.recipient_party_id,d.evidence_asset_id].every(validSupplyId)&&['PAID','FAILED','RETURNED'].includes(String(d.outcome))&&amount(d.amount_minor,1)&&str(d.external_reference)&&iso(d.occurred_at)&&str(d.note)&&review(d.review)&&d.method==='EXTERNAL_MANUAL_EVIDENCE'
 case 'STATEMENT':return child&&reviewStatus&&exact(d,['external_reference','period_start','period_end','gross_minor','refund_minor','channel_fee_minor','tax_minor','net_minor','direction','original_statement_id','evidence_asset_id','note','environment','review'])&&str(d.external_reference,128)&&iso(d.period_start)&&iso(d.period_end)&&d.period_start<d.period_end&&['gross_minor','refund_minor','channel_fee_minor','tax_minor'].every(k=>amount(d[k]))&&signed(d.net_minor)&&['CREDIT','DEBIT'].includes(String(d.direction))&&nullableId(d.original_statement_id)&&validSupplyId(d.evidence_asset_id)&&str(d.note,4000)&&environment(d.environment)&&review(d.review)
 case 'RECEIPT':return child&&reviewStatus&&exact(d,['statement_id','amount_minor','external_reference','occurred_at','evidence_asset_id','note','environment','review'])&&validSupplyId(d.statement_id)&&amount(d.amount_minor,1)&&str(d.external_reference)&&iso(d.occurred_at)&&validSupplyId(d.evidence_asset_id)&&str(d.note)&&environment(d.environment)&&review(d.review)
 case 'ADJUSTMENT':return child&&reviewStatus&&exact(d,['entries','reason','evidence_asset_id','review'])&&adjustment(d.entries)&&str(d.reason)&&validSupplyId(d.evidence_asset_id)&&review(d.review)
 case 'RECONCILIATION':return child&&['MATCHED','DIFFERENCES'].includes(s)&&exact(d,['provider','environment','external_reference','items','facts_sha256','differences','evidence_asset_id','meaning'])&&['APPLE','ALIPAY'].includes(String(d.provider))&&environment(d.environment)&&str(d.external_reference)&&Array.isArray(d.items)&&d.items.length<=200&&d.items.every(externalLine)&&hash(d.facts_sha256)&&Array.isArray(d.differences)&&d.differences.every(x=>exact(x,['record_id','reason'])&&validSupplyId(x.record_id)&&['MISSING_IN_EXTERNAL_STATEMENT','FACT_MISMATCH','UNKNOWN_PLATFORM_FACT'].includes(String(x.reason)))&&validSupplyId(d.evidence_asset_id)&&d.meaning==='COMPARISON_ONLY_NOT_A_PAYMENT_OR_MANUAL_APPROVAL'
 case 'DISPUTE':return child&&['OPEN','ACTION_REQUIRED','RESOLVED'].includes(s)&&exact(d,['about_record_id','category','reason','evidence_asset_ids','decision_history'])&&validSupplyId(d.about_record_id)&&['QUALITY','REFUND','RIGHTS_DEFECT','EXCLUSIVITY','SETTLEMENT','OTHER'].includes(String(d.category))&&str(d.reason)&&ids(d.evidence_asset_ids,30)&&Array.isArray(d.decision_history)&&d.decision_history.every(x=>exact(x,['decision','reason','action_record_id','reviewer_account_id'])&&['ACTION_REQUIRED','RESUME','REMEDIED'].includes(String(x.decision))&&str(x.reason)&&nullableId(x.action_record_id)&&validSupplyId(x.reviewer_account_id))
 case 'RESPONSE':return child&&s==='RECORDED'&&exact(d,['dispute_id','message','evidence_asset_ids'])&&validSupplyId(d.dispute_id)&&str(d.message)&&ids(d.evidence_asset_ids,30)
 default:return false
 }
}
export function visibleRecord(i:SupplyIdentity,v:unknown):v is FinanceRecord {return isFinanceRecord(v)&&!(v.kind==='SETTLEMENT'&&i.partyId&&i.partyId!==v.owner_party_id&&v.data.balances.some(b=>b.party_id!==i.partyId))}
export function isBalances(v:unknown):v is Balances {return exact(v,['agreement_id','currency','environment','customer_payment_separate','received_minor','receivable_minor','items'])&&validSupplyId(v.agreement_id)&&v.currency==='CNY'&&environment(v.environment)&&v.customer_payment_separate===true&&amount(v.received_minor)&&signed(v.receivable_minor)&&Array.isArray(v.items)&&v.items.length<=100&&v.items.every(x=>exact(x,['party_id','accrued_minor','adjustment_minor','paid_minor','balance_minor','expected_accrued_minor','available_minor','recovery_due_minor','reason_code','meaning'])&&validSupplyId(x.party_id)&&['accrued_minor','adjustment_minor','paid_minor','balance_minor','expected_accrued_minor'].every(k=>signed(x[k]))&&amount(x.available_minor)&&amount(x.recovery_due_minor)&&(x.reason_code===null||str(x.reason_code,128))&&['MERCHANT_RETAINED_NOT_TRANSFER','PAYABLE_NOT_YET_TRANSFERRED'].includes(String(x.meaning)))}
export function isReadiness(v:unknown):v is Readiness {return exact(v,['environment','automatic_payout','manual_payment'])&&environment(v.environment)&&exact(v.automatic_payout,['current_status','reason_code'])&&v.automatic_payout.current_status==='NOT_IMPLEMENTED'&&v.automatic_payout.reason_code==='PAYOUT_PROVIDER_NOT_VERIFIED'&&exact(v.manual_payment,['current_status','meaning'])&&v.manual_payment.current_status==='IMPLEMENTED'&&str(v.manual_payment.meaning)}
const options=(i:SupplyIdentity,signal?:AbortSignal)=>({token:i.token,actingParty:i.partyId,cache:'no-store' as const,signal})
function checked<T>(r:ApiResult<unknown>,i:SupplyIdentity,guard:(v:unknown)=>v is T):T {if(!guard(r.data)||!r.meta?.request_id||r.meta.actor?.account_id!==i.accountId||r.meta.acting_party!==i.partyId)throw new ApiError({status:200,code:'UNEXPECTED_RESPONSE_SHAPE',message:'财务回复的身份、私有投影或内容不符合契约，请核对原操作。',requestId:r.requestId});return r.data}
export async function getFinance(i:SupplyIdentity,id:string,kind?:FinanceKind,signal?:AbortSignal){return checked(await request('/finance/records/'+id,options(i,signal)),i,(v):v is FinanceRecord=>visibleRecord(i,v)&&v.id===id&&(!kind||v.kind===kind))}
export async function listFinance(i:SupplyIdentity,agreementId?:string,kind?:ChildKind,cursor:string|null=null,signal?:AbortSignal){const q=new URLSearchParams({limit:'20'});if(kind)q.set('kind',kind);if(cursor)q.set('cursor',cursor);return checked(await request(agreementId?'/finance/agreements/'+agreementId+'/records?'+q:'/finance/agreements?'+q,options(i,signal)),i,(v):v is FinancePage=>exact(v,['items','next_cursor'])&&Array.isArray(v.items)&&v.items.length<=100&&v.items.every(r=>visibleRecord(i,r)&&(agreementId?r.agreement_id===agreementId&&r.kind===kind:r.kind==='AGREEMENT'))&&nullableId(v.next_cursor))}
export async function financeConfirmations(i:SupplyIdentity,id:string,signal?:AbortSignal){return checked(await request('/finance/records/'+id+'/confirmations',options(i,signal)),i,(v):v is {items:Confirmation[]}=>exact(v,['items'])&&Array.isArray(v.items)&&v.items.length<=100&&v.items.every(x=>exact(x,['party_id','decision','content_sha256','reason'])&&validSupplyId(x.party_id)&&['APPROVED','REJECTED'].includes(String(x.decision))&&hash(x.content_sha256)&&str(x.reason,2000)))}
export async function financeBalances(i:SupplyIdentity,id:string,payerId:string,signal?:AbortSignal){return checked(await request('/finance/agreements/'+id+'/balances',options(i,signal)),i,(v):v is Balances=>isBalances(v)&&v.agreement_id===id&&(!i.partyId||i.partyId===payerId||v.items.every(b=>b.party_id===i.partyId)))}
export async function financeReadiness(i:SupplyIdentity,id:string,signal?:AbortSignal){return checked(await request('/finance/agreements/'+id+'/readiness',options(i,signal)),i,isReadiness)}
function isEntry(v:unknown):v is Entry {if(!exact(v,['id','party_id','amount_minor','source_id','category','data'])||!incremental(v.id)||!validSupplyId(v.party_id)||!signed(v.amount_minor)||!validSupplyId(v.source_id)||!obj(v.data))return false;const d=v.data;return v.category==='ACCRUAL'?exact(d,['facts_sha256','source_references','target_minor'])&&hash(d.facts_sha256)&&Array.isArray(d.source_references)&&d.source_references.every(sourceReference)&&signed(d.target_minor):v.category==='ADJUSTMENT'?exact(d,['reason','evidence_asset_id'])&&str(d.reason,4000)&&validSupplyId(d.evidence_asset_id):['PAYOUT','PAYOUT_RETURN'].includes(String(v.category))&&exact(d,['payout_id','external_reference','evidence_asset_id','method'])&&validSupplyId(d.payout_id)&&str(d.external_reference,128)&&validSupplyId(d.evidence_asset_id)&&d.method==='EXTERNAL_MANUAL_PAYMENT'}
export async function financeEntries(i:SupplyIdentity,id:string,payerId:string,cursor:string|null=null,signal?:AbortSignal){const q=new URLSearchParams({limit:'50'});if(cursor)q.set('cursor',cursor);return checked(await request('/finance/agreements/'+id+'/entries?'+q,options(i,signal)),i,(v):v is {items:Entry[];next_cursor:string|null}=>exact(v,['items','next_cursor'])&&Array.isArray(v.items)&&v.items.length<=100&&v.items.every(e=>isEntry(e)&&(!i.partyId||i.partyId===payerId||e.party_id===i.partyId))&&(v.next_cursor===null||incremental(v.next_cursor)))}
export async function financeNotifications(i:SupplyIdentity,cursor:string|null=null,signal?:AbortSignal){const q=new URLSearchParams({limit:'30'});if(cursor)q.set('cursor',cursor);return checked(await request('/finance/notifications?'+q,options(i,signal)),i,(v):v is {items:Notification[];next_cursor:string|null}=>exact(v,['items','next_cursor'])&&Array.isArray(v.items)&&v.items.length<=100&&v.items.every(n=>exact(n,['id','agreement_id','record_id','event_code'])&&incremental(n.id)&&validSupplyId(n.agreement_id)&&validSupplyId(n.record_id)&&str(n.event_code,128))&&(v.next_cursor===null||incremental(v.next_cursor)))}
export async function postFinance(i:SupplyIdentity,c:FinanceWrite,key:string,signal?:AbortSignal):Promise<FinanceResult>{if(c.supply)return postSupply(i,c.supply,key,signal) as Promise<SupplyAsset>;return checked(await request(c.path,{...options(i,signal),method:'POST',body:c.body,idempotencyKey:key,ifMatch:c.version}),i,(v):v is FinanceRecord=>visibleRecord(i,v)&&v.kind===c.resultKind&&(!c.agreementId||v.agreement_id===c.agreementId||v.kind==='AGREEMENT'&&v.id===c.agreementId)&&(!c.targetId||v.id===c.targetId||v.agreement_id===c.targetId||v.kind==='RECEIPT'&&v.data.statement_id===c.targetId||v.kind==='PAYOUT_EVIDENCE'&&v.data.payout_id===c.targetId||v.kind==='DISPUTE'&&v.data.about_record_id===c.targetId||v.kind==='RESPONSE'&&v.data.dispute_id===c.targetId))}
export const getFinanceResult=(i:SupplyIdentity,id:string,kind:FinanceWrite['resultKind'],signal?:AbortSignal):Promise<FinanceResult>=>kind==='ASSET'?getSupplyAsset(i,id,signal):getFinance(i,id,kind,signal)
export const financeEvidence=(i:SupplyIdentity,id:string,asset:string,signal?:AbortSignal)=>requestBytes('/finance/records/'+id+'/evidence/'+asset,options(i,signal))
export const evidenceIds=(r:FinanceRecord)=>r.kind==='PAYOUT'?[r.data.destination_asset_id]:'evidence_asset_id' in r.data?[r.data.evidence_asset_id]:'evidence_asset_ids' in r.data?r.data.evidence_asset_ids:[]
export function confirmationGate(r:FinanceRecord,g:FinanceRecord,party:string,items:Confirmation[]){if(!['AGREEMENT','SETTLEMENT'].includes(r.kind)||g.kind!=='AGREEMENT'||!g.data.parties.includes(party))return {can:false,message:'当前身份不是这份约定的指定确认方。'};if(r.current_status!=='APPROVED')return {can:false,message:'本版尚未通过独立财务复核。'};if(items.some(x=>x.party_id===party))return {can:false,message:'本方已对该记录决定，历史决定不能覆盖。'};return {can:true,message:r.kind==='SETTLEMENT'?'仅确认本方收到的余额与原约定；原指纹绑定不可变全体快照，不表示已经读取他人余额。':'核对准确约定及本方分配后明确决定；确认不代表实际付款。'}}
export function parseSignedMoney(value:string){if(value.startsWith('-')){const n=parseMoney(value.slice(1));return n===null?null:-n}return parseMoney(value)}
export function parsePercent(value:string){if(!/^(0|[1-9][0-9]*)(\.[0-9]{1,2})?$/.test(value))return null;const n=parseMoney(value);return n!==null&&n<=10000?n:null}
export const kindLabels:Record<FinanceKind,string>={AGREEMENT:'结算约定',SETTLEMENT:'期间结算单',PAYOUT:'付款申请',PAYOUT_EVIDENCE:'真实付款结果报告',STATEMENT:'渠道收入账单',RECEIPT:'渠道实际到账报告',ADJUSTMENT:'账务调整',RECONCILIATION:'支付渠道对账',DISPUTE:'业务异议',RESPONSE:'争议补充说明'}
export const statusLabels:Record<string,string>={IN_REVIEW:'待独立复核',REQUESTED:'申请待复核，额度已占用',APPROVED:'已复核，仍需按后续流程办理',REJECTED:'已拒绝，历史保留',SUPERSEDED:'被新约定替代',CANCELLED:'已取消未执行申请',PAID:'实际付款已核实',FAILED:'付款失败已核实，占用已释放',RETURNED:'款项退回已核实，另行申请重付',OPEN:'异议待处理，暂停新付款',ACTION_REQUIRED:'需要补救，暂停新付款',RESOLVED:'本次处理决定已保存',RECORDED:'说明已保存',MATCHED:'与已核实事实匹配，不新增付款',DIFFERENCES:'与已核实事实存在差异'}
export const financeStatus=(r:Pick<FinanceRecord,'kind'|'current_status'>)=>r.kind==='PAYOUT'&&r.current_status==='APPROVED'?'已批准，尚未实际付款':r.kind==='PAYOUT_EVIDENCE'&&r.current_status==='IN_REVIEW'?'外部报告待独立核实，尚未记实付':statusLabels[r.current_status]||r.current_status

export const financeReasons:Record<string,string>={FINANCE_AGREEMENT_NOT_APPROVED:'约定尚未独立复核通过',FINANCE_CONFIRMATIONS_REQUIRED:'约定各方准确版本确认尚未完成',FINANCE_DISPUTED:'存在待处理异议，暂停新付款',RETAINED_INCOME_NOT_PAYOUT:'商家保留金额，不再次转给自己',SETTLEMENT_DATE_NOT_REACHED:'尚未达到约定结算时间',CUSTOMER_PAYMENT_REVIEW_REQUIRED:'客户原付款待核实',REVENUE_NOT_RECEIVED:'渠道应收尚未实际到账',FINANCE_DELIVERY_NOT_ACCEPTED:'原制作交付尚未实际验收',CURRENT_SETTLEMENT_CONFIRMATION_REQUIRED:'当前事实须重新生成结算单、独立复核并完成各方确认'}
