import { ApiError, request, requestBytes, type ApiResult } from '../client'
import { validSupplyId, MAX_ASSET_BYTES, type SupplyIdentity } from './supply'
import { instant } from './licensing'
export const gigKinds=['RULE','RELATION','GIG','OFFER','COMMISSION','RANKING'] as const
export type GigKind=typeof gigKinds[number]
export interface CommissionTerms {platform_bps:number;mcn_bps:number}
export interface RankingRule {window_days:number;newcomer_days:number;minimum_orders:number;order_weight:number;net_minor_weight:number;newcomer_bonus:number}
export interface GigRule {version:string;terms:string;categories:{code:string;allowed:boolean;required_proofs:string[]}[];ranking:RankingRule}
export interface GigScope {purpose:'COMMERCIAL';territory:string;valid_until:string}
export interface RelationSnapshot {id:string;version:number;sha256:string;mcn_party_id:string;terms:string;valid_from:string;valid_until:string}
export const checkLabels={identity_verified:'实名与本人身份已由外部核验',authority_verified:'权属与商业脸声同意已核验',materials_reviewed:'私有证明材料已实际读取核验',content_reviewed:'服务内容与禁品规则已核验',marking_reviewed:'必要标识或水印已实际核验'} as const
export type GigChecks=Record<keyof typeof checkLabels,boolean>
interface Review {decision:'APPROVED'|'REJECTED';reason:string;checks:GigChecks|null;account_id:string;method:'EXTERNAL_MANUAL_REVIEW'}
export interface CommercialSnapshot {ranking_opt_in:boolean;offer_id:string;offer_sha256:string;gig_id:string;scope:GigScope;category:string;terms:string;commission:CommissionTerms;relation:RelationSnapshot|null;avatar_id:string;consent_id:string;rule_id:string}
export interface FinancialFacts {received_minor:number;refunded_minor:number;net_minor:number;environment:'SANDBOX'|'PRODUCTION'|null;first_at:number|null;journal_ids:string[]}
export interface Amounts {net_minor:number;supplier_minor:number;platform_minor:number;mcn_minor:number}
export interface BoardRow {party_id:string;territory:string;orders:number;heat:string;emerging:string}
export interface PublicRanking {id:string;as_of:string;rule_id:string;rule:RankingRule;source:'VERIFIED_PRODUCTION_COMMERCIAL_RECEIPTS';data_status:'AVAILABLE'|'INSUFFICIENT_DATA';boards:Record<'hot'|'emerging'|'regional',BoardRow[]>}
interface Base {id:string;kind:GigKind;owner_party_id:string|null;counterparty_id:string|null;parent_id:string|null;created_by:string;current_status:string;object_version:number;content_sha256:string}
export type GigRecord=Base & (
 {kind:'RULE';data:{rule:GigRule;review:Review|null;retirement?:{reason:string;account_id:string}}}|
 {kind:'RELATION';data:{scope:'COMMERCIAL';valid_from:string;valid_until:string;exclusive:boolean;terms:string;commission:CommissionTerms;evidence_asset_ids:string[];accepted_by:string|null;ended_reason:string|null}}|
 {kind:'GIG';data:{title:string;brief:string;category:string;scope:GigScope;rule_id:string;rule_sha256:string;proofs:{code:string;asset_id:string}[];review:Review|null;suspension:{reason:string;account_id:string}|null}}|
 {kind:'OFFER';data:{ranking_opt_in:boolean;spec_id:string;avatar_id:string;consent_id:string;relation:RelationSnapshot|null;commission:CommissionTerms;terms:string;evidence_asset_ids:string[];review:Review|null;buyer_accepted_by:string|null}}|
 {kind:'COMMISSION';data:{order_id:string;contract_sha256:string;agreement:CommercialSnapshot;relation:RelationSnapshot|null;facts:FinancialFacts;amounts:Amounts;currency:'CNY';paid_out_minor:0;meaning:'ACCRUAL_ONLY_NOT_TRANSFERRED'}}|
 {kind:'RANKING';data:Omit<PublicRanking,'id'|'boards'> & {rule_sha256:string;facts:{order_id:string;party_id:string;territory:string;net_minor:number;environment:string|null;at:number;first_at:number;journal_ids:string[]}[];boards:Record<'hot'|'emerging'|'regional',{party_id:string;territory:string;current:number;previous:number;net:number;first:number;heat:string;emerging:string}[]>}}
)
export interface GigPage {items:GigRecord[];next_cursor:string|null}
export interface Catalogue {rules:{id:string;rule:GigRule}[];items:{id:string;title:string;brief:string;category:string;scope:GigScope;buyer_party_id:string}[]}
export interface CommissionEntry {id:string;object_version:number;data:{delta:Omit<Amounts,'net_minor'>;facts:FinancialFacts;amounts:Amounts}}
export interface GigWrite {path:string;body:unknown;version?:number;targetId?:string;resultKind:GigKind;label:string}
const obj=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==='object'&&!Array.isArray(v)
const text=(v:unknown,max=8000):v is string=>typeof v==='string'&&v.trim().length>0&&v.length<=max
const int=(v:unknown,min=0,max=900000000000)=>Number.isSafeInteger(v)&&Number(v)>=min&&Number(v)<=max
const hash=(v:unknown)=>typeof v==='string'&&/^[a-f0-9]{64}$/.test(v)
const nullableId=(v:unknown)=>v===null||validSupplyId(v)
const array=(v:unknown,g:(x:unknown)=>boolean,min=0,max=100):v is unknown[]=>Array.isArray(v)&&v.length>=min&&v.length<=max&&v.every(g)
const ids=(v:unknown,min=0,max=30):v is string[]=>array(v,validSupplyId,min,max)&&new Set(v).size===v.length
export const isCommissionTerms=(v:unknown):v is CommissionTerms=>obj(v)&&int(v.platform_bps,0,10000)&&int(v.mcn_bps,0,10000)&&Number(v.mcn_bps)<=Number(v.platform_bps)
export const isRankingRule=(v:unknown):v is RankingRule=>obj(v)&&int(v.window_days,1,366)&&int(v.minimum_orders,1,100000)&&['newcomer_days','order_weight','net_minor_weight','newcomer_bonus'].every(k=>int(v[k],0,100000))
export const isGigRule=(v:unknown):v is GigRule=>obj(v)&&text(v.version,128)&&text(v.terms)&&array(v.categories,x=>obj(x)&&text(x.code,128)&&typeof x.allowed==='boolean'&&array(x.required_proofs,y=>text(y,128),0,20)&&new Set(x.required_proofs).size===x.required_proofs.length,1)&&new Set(v.categories.map(x=>(x as {code:string}).code)).size===v.categories.length&&isRankingRule(v.ranking)
const scope=(v:unknown):v is GigScope=>obj(v)&&v.purpose==='COMMERCIAL'&&text(v.territory,128)&&instant(v.valid_until)
const relation=(v:unknown):v is RelationSnapshot|null=>v===null||obj(v)&&validSupplyId(v.id)&&int(v.version,1)&&hash(v.sha256)&&validSupplyId(v.mcn_party_id)&&text(v.terms)&&instant(v.valid_from)&&instant(v.valid_until)&&v.valid_from<v.valid_until
const review=(v:unknown)=>v===null||obj(v)&&['APPROVED','REJECTED'].includes(String(v.decision))&&text(v.reason,2000)&&validSupplyId(v.account_id)&&v.method==='EXTERNAL_MANUAL_REVIEW'&&(v.checks===null||obj(v.checks)&&Object.keys(checkLabels).every(k=>typeof (v.checks as Record<string,unknown>)[k]==='boolean'))
export const isCommercialSnapshot=(v:unknown):v is CommercialSnapshot=>obj(v)&&typeof v.ranking_opt_in==='boolean'&&['offer_id','gig_id','avatar_id','consent_id','rule_id'].every(k=>validSupplyId(v[k]))&&hash(v.offer_sha256)&&scope(v.scope)&&text(v.category,128)&&text(v.terms)&&isCommissionTerms(v.commission)&&relation(v.relation)
const facts=(v:unknown):v is FinancialFacts=>obj(v)&&['received_minor','refunded_minor','net_minor'].every(k=>int(v[k]))&&Number(v.net_minor)===Number(v.received_minor)-Number(v.refunded_minor)&&[null,'SANDBOX','PRODUCTION'].includes(v.environment as string|null)&&(v.first_at===null||int(v.first_at,0,Number.MAX_SAFE_INTEGER))&&ids(v.journal_ids,0,100000)
const amounts=(v:unknown):v is Amounts=>obj(v)&&['net_minor','supplier_minor','platform_minor','mcn_minor'].every(k=>int(v[k]))&&v.net_minor===Number(v.supplier_minor)+Number(v.platform_minor)+Number(v.mcn_minor)
const score=(v:unknown)=>typeof v==='string'&&/^-?\d+$/.test(v)
const board=(v:unknown):v is BoardRow=>obj(v)&&validSupplyId(v.party_id)&&text(v.territory,128)&&int(v.orders)&&score(v.heat)&&score(v.emerging)&&!Object.hasOwn(v,'order_id')&&!Object.hasOwn(v,'journal_ids')
export const isPublicRanking=(v:unknown):v is PublicRanking=>obj(v)&&validSupplyId(v.id)&&validSupplyId(v.rule_id)&&rankingDate(v.as_of)&&isRankingRule(v.rule)&&v.source==='VERIFIED_PRODUCTION_COMMERCIAL_RECEIPTS'&&['AVAILABLE','INSUFFICIENT_DATA'].includes(String(v.data_status))&&obj(v.boards)&&['hot','emerging','regional'].every(k=>array((v.boards as Record<string,unknown>)[k],board,0,10000))&&!Object.hasOwn(v,'facts')
export function isGigRecord(v:unknown):v is GigRecord {
 if(!obj(v)||!validSupplyId(v.id)||!validSupplyId(v.created_by)||![v.owner_party_id,v.counterparty_id,v.parent_id].every(nullableId)||!int(v.object_version,1)||!hash(v.content_sha256)||!obj(v.data))return false
 const d=v.data,s=String(v.current_status),owned=validSupplyId(v.owner_party_id),paired=owned&&validSupplyId(v.counterparty_id)
 switch(v.kind){
 case 'RULE':return v.owner_party_id===null&&v.counterparty_id===null&&v.parent_id===null&&['IN_REVIEW','EFFECTIVE','REJECTED','RETIRED'].includes(s)&&isGigRule(d.rule)&&review(d.review)&&(d.retirement===undefined||obj(d.retirement)&&text(d.retirement.reason,2000)&&validSupplyId(d.retirement.account_id))
 case 'RELATION':return paired&&v.parent_id===null&&['INVITED','ACTIVE','REJECTED','ENDED'].includes(s)&&d.scope==='COMMERCIAL'&&instant(d.valid_from)&&instant(d.valid_until)&&d.valid_from<d.valid_until&&typeof d.exclusive==='boolean'&&text(d.terms)&&isCommissionTerms(d.commission)&&ids(d.evidence_asset_ids,1)&&nullableId(d.accepted_by)&&(d.ended_reason===null||text(d.ended_reason,2000))
 case 'GIG':return owned&&v.counterparty_id===null&&v.parent_id===null&&['IN_REVIEW','PUBLISHED','REJECTED','SUSPENDED'].includes(s)&&text(d.title,200)&&text(d.brief)&&text(d.category,128)&&scope(d.scope)&&validSupplyId(d.rule_id)&&hash(d.rule_sha256)&&array(d.proofs,x=>obj(x)&&text(x.code,128)&&validSupplyId(x.asset_id),0,30)&&review(d.review)&&(d.suspension===null||obj(d.suspension)&&text(d.suspension.reason,2000)&&validSupplyId(d.suspension.account_id))
 case 'OFFER':return paired&&validSupplyId(v.parent_id)&&['IN_REVIEW','APPROVED','REJECTED','ACCEPTED'].includes(s)&&typeof d.ranking_opt_in==='boolean'&&['spec_id','avatar_id','consent_id'].every(k=>validSupplyId(d[k]))&&relation(d.relation)&&isCommissionTerms(d.commission)&&text(d.terms)&&ids(d.evidence_asset_ids,1)&&review(d.review)&&nullableId(d.buyer_accepted_by)
 case 'COMMISSION':return paired&&validSupplyId(v.parent_id)&&s==='CALCULATED'&&validSupplyId(d.order_id)&&hash(d.contract_sha256)&&isCommercialSnapshot(d.agreement)&&relation(d.relation)&&facts(d.facts)&&amounts(d.amounts)&&d.facts.net_minor===d.amounts.net_minor&&d.currency==='CNY'&&d.paid_out_minor===0&&d.meaning==='ACCRUAL_ONLY_NOT_TRANSFERRED'
 case 'RANKING':return v.owner_party_id===null&&v.counterparty_id===null&&validSupplyId(v.parent_id)&&s==='PUBLISHED'&&rankingDate(d.as_of)&&validSupplyId(d.rule_id)&&hash(d.rule_sha256)&&isRankingRule(d.rule)&&d.source==='VERIFIED_PRODUCTION_COMMERCIAL_RECEIPTS'&&['AVAILABLE','INSUFFICIENT_DATA'].includes(String(d.data_status))&&array(d.facts,x=>obj(x)&&validSupplyId(x.order_id)&&validSupplyId(x.party_id)&&text(x.territory,128)&&int(x.net_minor)&&[null,'SANDBOX','PRODUCTION'].includes(x.environment as string|null)&&int(x.at,0,Number.MAX_SAFE_INTEGER)&&int(x.first_at,0,Number.MAX_SAFE_INTEGER)&&ids(x.journal_ids,0,100000),0,100000)&&obj(d.boards)&&['hot','emerging','regional'].every(k=>array((d.boards as Record<string,unknown>)[k],x=>obj(x)&&validSupplyId(x.party_id)&&text(x.territory,128)&&['current','previous','net','first'].every(k=>int(x[k],0,Number.MAX_SAFE_INTEGER))&&score(x.heat)&&score(x.emerging),0,10000))
 default:return false
 }
}
export function rankingDate(v:unknown):v is string{return instant(v)&&v.endsWith('T00:00:00.000Z')&&Date.parse(v)<=Date.now()}
export function basisInput(v:string){return /^\d+$/.test(v)&&int(Number(v),0,10000)?Number(v):null}
/** Integer floors match the server. MCN is carved out of the platform fee. */
export function commissionSplit(net:number,c:CommissionTerms):Amounts {if(!int(net)||!isCommissionTerms(c))throw new Error('INVALID_COMMISSION');const n=BigInt(net),fee=n*BigInt(c.platform_bps)/10000n,mcn=n*BigInt(c.mcn_bps)/10000n;return {net_minor:net,supplier_minor:Number(n-fee),platform_minor:Number(fee-mcn),mcn_minor:Number(mcn)}}
const options=(i:SupplyIdentity,signal?:AbortSignal)=>({token:i.token,actingParty:i.partyId,cache:'no-store' as const,signal})
const visible=(r:GigRecord,i:SupplyIdentity)=>!i.partyId||r.owner_party_id===i.partyId||r.counterparty_id===i.partyId||('relation' in r.data&&r.data.relation?.mcn_party_id===i.partyId)
function checked<T>(r:ApiResult<unknown>,i:SupplyIdentity,g:(v:unknown)=>v is T):T{if(!g(r.data)||!r.meta?.request_id||r.meta.actor?.account_id!==i.accountId||r.meta.acting_party!==i.partyId)throw new ApiError({status:200,code:'UNEXPECTED_RESPONSE_SHAPE',message:'无法确认商业合作记录，请重新读取。',requestId:r.requestId});return r.data}
export const gigTitle=(r:GigRecord)=>r.kind==='GIG'?r.data.title:r.kind==='RULE'?`规则 ${r.data.rule.version}`:r.kind==='RELATION'?'直接 MCN 合作':r.kind==='OFFER'?'商单服务提案':r.kind==='COMMISSION'?'订单佣金计提':'榜单快照'
export const gigStatuses:Record<string,string>={IN_REVIEW:'待独立审核',EFFECTIVE:'规则已生效',RETIRED:'规则已退役',INVITED:'待本人确认',ACTIVE:'直接合作有效',ENDED:'合作已结束',REJECTED:'已拒绝',PUBLISHED:'已发布',SUSPENDED:'商单已暂停',APPROVED:'已审待客户确认',ACCEPTED:'客户已确认',CALCULATED:'已计提，未出款'}
export async function listGigs(i:SupplyIdentity,kind:GigKind,cursor:string|null=null,signal?:AbortSignal){const q=new URLSearchParams({kind,limit:'20'});if(cursor)q.set('cursor',cursor);return checked(await request(`/gigs/records?${q}`,options(i,signal)),i,(v):v is GigPage=>obj(v)&&array(v.items,x=>isGigRecord(x)&&x.kind===kind&&visible(x,i))&&nullableId(v.next_cursor))}
export interface RelationParties {record_id:string;source:'CURRENT_DISPLAY_NAME';parties:{party_id:string;display_name:string|null}[]}
export async function getRelationParties(i:SupplyIdentity,r:GigRecord,signal?:AbortSignal):Promise<RelationParties|null>{
 if(r.kind!=='RELATION'||!i.partyId)throw new ApiError({status:400,code:'INVALID_RELATION',message:'请先选择合作双方的有效身份。'});
 try{return checked(await request(`/gigs/relations/${encodeURIComponent(r.id)}/parties`,options(i,signal)),i,(v):v is RelationParties=>
  obj(v)&&Object.keys(v).length===3&&v.record_id===r.id&&v.source==='CURRENT_DISPLAY_NAME'&&Array.isArray(v.parties)&&v.parties.length===2&&
  v.parties.every(p=>obj(p)&&Object.keys(p).length===2&&[r.owner_party_id,r.counterparty_id].includes(p.party_id as string)&&(p.display_name===null||text(p.display_name,120)))&&
  new Set(v.parties.map(p=>p.party_id)).size===2);
 }catch(e){if(e instanceof ApiError&&e.status===404&&e.code==='NOT_FOUND')return null;throw e}
}
export async function getGig(i:SupplyIdentity,id:string,kind?:GigKind,signal?:AbortSignal){return checked(await request(`/gigs/records/${encodeURIComponent(id)}`,options(i,signal)),i,(v):v is GigRecord=>isGigRecord(v)&&v.id===id&&(!kind||v.kind===kind)&&visible(v,i))}
export async function postGig(i:SupplyIdentity,c:GigWrite,key:string,signal?:AbortSignal){return checked(await request(c.path,{...options(i,signal),method:'POST',body:c.body,idempotencyKey:key,ifMatch:c.version}),i,(v):v is GigRecord=>isGigRecord(v)&&v.kind===c.resultKind&&visible(v,i)&&(!c.targetId||v.id===c.targetId))}
export async function getCatalogue(i:SupplyIdentity,signal?:AbortSignal){const p={...i,partyId:null};return checked(await request('/gigs/catalogue',options(p,signal)),p,(v):v is Catalogue=>obj(v)&&array(v.rules,x=>obj(x)&&validSupplyId(x.id)&&isGigRule(x.rule))&&array(v.items,x=>obj(x)&&validSupplyId(x.id)&&text(x.title,200)&&text(x.brief)&&text(x.category,128)&&scope(x.scope)&&validSupplyId(x.buyer_party_id)))}
export async function getNotifications(i:SupplyIdentity,signal?:AbortSignal){return checked(await request('/gigs/notifications',options(i,signal)),i,(v):v is {items:{id:string;record_id:string;event_code:string}[]}=>obj(v)&&array(v.items,x=>obj(x)&&validSupplyId(x.id)&&validSupplyId(x.record_id)&&text(x.event_code,128)))}
export async function getRanking(i:SupplyIdentity,id:string,signal?:AbortSignal){const p={...i,partyId:null};return checked(await request(`/gigs/rankings/${encodeURIComponent(id)}`,options(p,signal)),p,(v):v is PublicRanking=>isPublicRanking(v)&&v.id===id)}
export async function getEntries(i:SupplyIdentity,id:string,signal?:AbortSignal){return checked(await request(`/gigs/commissions/${encodeURIComponent(id)}/entries`,options(i,signal)),i,(v):v is {items:CommissionEntry[]}=>obj(v)&&array(v.items,x=>obj(x)&&validSupplyId(x.id)&&int(x.object_version,1)&&obj(x.data)&&facts(x.data.facts)&&amounts(x.data.amounts)&&obj(x.data.delta)&&['supplier_minor','platform_minor','mcn_minor'].every(k=>int((x.data as {delta:Record<string,unknown>}).delta[k],-900000000000)),0,100000))}
export async function gigEvidence(i:SupplyIdentity,recordId:string,assetId:string,signal?:AbortSignal){const bytes=await requestBytes(`/gigs/records/${encodeURIComponent(recordId)}/evidence/${encodeURIComponent(assetId)}`,options(i,signal));if(bytes.size>MAX_ASSET_BYTES)throw new ApiError({status:200,code:'PRIVATE_CONTENT_MISMATCH',message:'私有材料大小不符。'});return bytes}
export interface CommercialSupply {id:string;kind:'AVATAR'|'CONSENT';owner_party_id:string;current_status:string;object_version:number;data:{display_name?:string;consent?:{avatar_id:string;subject_party_id:string;features:string[];purposes:string[];territories:string[];valid_from:string;valid_until:string;terms:string;evidence_asset_ids:string[]};review?:unknown;withdrawal?:unknown;signing_method?:string;identity_verification?:string;material_asset_ids?:string[];provider_asset_ref?:string|null}}
export function isCommercialSupply(v:unknown):v is CommercialSupply {if(!obj(v)||!validSupplyId(v.id)||!validSupplyId(v.owner_party_id)||!validSupplyId(v.created_by)||!text(v.stream_ref,128)||!int(v.revision,1)||!int(v.object_version,1)||!obj(v.data))return false;const d=v.data;if(v.kind==='AVATAR')return v.current_status==='RECORDED'&&text(d.display_name,200)&&ids(d.material_asset_ids,1,100)&&(d.provider_asset_ref===null||text(d.provider_asset_ref,200));if(v.kind!=='CONSENT'||!['PENDING_REVIEW','APPROVED','CHANGES_REQUESTED','REJECTED','WITHDRAWN'].includes(String(v.current_status))||!obj(d.consent))return false;const c=d.consent;return validSupplyId(c.avatar_id)&&validSupplyId(c.subject_party_id)&&array(c.features,x=>['FACE','VOICE'].includes(String(x)),1,2)&&array(c.purposes,x=>text(x,128),1)&&array(c.territories,x=>text(x,128),1)&&instant(c.valid_from)&&instant(c.valid_until)&&text(c.terms)&&ids(c.evidence_asset_ids,1,100)&&d.signing_method==='IN_APP_DECLARATION'&&d.identity_verification==='NOT_VERIFIED'}
export async function listCommercialSupply(i:SupplyIdentity,kind:'AVATAR'|'CONSENT',signal?:AbortSignal){const records:CommercialSupply[]=[],seen=new Set<string>();let cursor:string|null=null;do{const q=new URLSearchParams({kind,limit:'100'});if(cursor)q.set('cursor',cursor);const page=checked(await request(`/supply/records?${q}`,options(i,signal)),i,(v):v is {items:CommercialSupply[];next_cursor:string|null}=>obj(v)&&array(v.items,x=>isCommercialSupply(x)&&x.kind===kind&&(x.owner_party_id===i.partyId||x.kind==='CONSENT'&&x.data.consent?.subject_party_id===i.partyId))&&nullableId(v.next_cursor));records.push(...page.items);cursor=page.next_cursor;if(cursor&&seen.has(cursor))throw new ApiError({status:200,code:'UNEXPECTED_RESPONSE_SHAPE',message:'私有资料分页未更新。'});if(cursor)seen.add(cursor)}while(cursor);return records}

/** A saved, currently authorized commission also supplies its original order for MCN recalculation. */
export function commissionOrderAllowed(id:string,orders:{id:string}[],record:GigRecord|null){return validSupplyId(id)&&(orders.some(o=>o.id===id)||record?.kind==='COMMISSION'&&record.data.order_id===id)}
