import { ApiError, request, requestBytes, type ApiResult } from '../client'
import { isSpecification, type Specification } from './trade'
import { validSupplyId, type SupplyIdentity, type SupplyAsset, type SupplyWrite, postSupply, getSupplyAsset } from './supply'
export const stages = { SCRIPT:'剧本', SAMPLE:'样片', ROUGH_CUT:'粗剪', FINAL:'成片' } as const
export type Stage = keyof typeof stages
export const fileMedia = { 'text/plain':'纯文本', 'video/mp4':'MP4 视频', 'audio/mpeg':'MP3 音频', 'image/png':'PNG 图片', 'application/pdf':'PDF 文档' } as const
export type FileMedia = keyof typeof fileMedia
export const MAX_FILE_BYTES = 50 * 1024 * 1024
export const operations = { CREATE_LONG_LIVED:'建立长期数字人资产', RENDER:'生成视频任务', DELETE_LONG_LIVED:'删除长期资产' } as const
export type Verification = { contract_sha256:string; identity_verified:true; signatures_verified:true; rights_verified:true } | { script_reviewed:true; specification_reviewed?:true; audio_reviewed?:true; branding_reviewed?:true }
export interface Review { decision:'APPROVED'|'REJECTED'; reason:string; verification:Verification|null; account_id:string; method:'EXTERNAL_MANUAL_REVIEW' }
export interface ProjectData { line_id:string; buyer_party_id:string; merchant_party_id:string; producer_party_id:string; script_version_id:string; license_project_id:string|null; assignee_account_id:string; purpose:string; territory:string; consent_ids:string[]; evidence_asset_id:string; specification:Specification; quantity:number; contract_sha256:string; current:Partial<Record<Stage,string>>; accepted:Partial<Record<Stage,string>>; revisions:Partial<Record<Stage,number>>; change_requests:number; review:Review|null; assignment_reason?:string }
export interface FileData { object_key:string; media_type:FileMedia; byte_size:number; content_sha256:string }
export interface VersionData { stage:Stage; revision:number; file_id:string; preview_file_id:string; basis_version_id:string|null; note:string; review:Review|null; last_feedback_id?:string }
export interface FeedbackData { version_id:string; stage:Stage; decision:'ACCEPT'|'REQUEST_CHANGES'; note:string; checklist:Verification|null }
export interface GenerationData { operation:keyof typeof operations; avatar_id:string; asset_id:string|null; consent_id:string; provider_code:string; environment:'SANDBOX'|'PRODUCTION'; config_revision:string; script_version_id:string|null; upstream_task_id:string|null; job_id:string|null; result:{asset_id:string;asset_type:'LONG_LIVED_AVATAR'}|{deleted:true}|{result_ref:string;delivery_state:'AWAITING_PRIVATE_IMPORT_AND_REVIEW'}|null }
export interface DigitalAssetData { avatar_id:string; consent_id:string; provider_code:string; environment:'SANDBOX'|'PRODUCTION'; config_revision:string; upstream_asset_ref:string; asset_type:'LONG_LIVED_AVATAR' }
interface Base { id:string; project_id:string|null; order_id:string; created_by:string|null; current_status:string; object_version:number; content_sha256:string }
export type ProductionRecord = Base & ({kind:'PROJECT';data:ProjectData}|{kind:'FILE';data:FileData}|{kind:'VERSION';data:VersionData}|{kind:'FEEDBACK';data:FeedbackData}|{kind:'GENERATION';data:GenerationData}|{kind:'DIGITAL_ASSET';data:DigitalAssetData})
export type ProductionKind = ProductionRecord['kind']
export interface ProductionPage { items:ProductionRecord[]; next_cursor:string|null }
export interface Readiness { provider_code:string; environment:'SANDBOX'|'PRODUCTION'; config_revision:string; current_status:'NOT_ENABLED'|'SERVICE_READY'; reason_code:string|null }
export interface Job { record_id:string;job_id:string;current_status:'PENDING'|'RUNNING'|'RETRY'|'FAILED'|'BLOCKED'|'SUCCEEDED';attempts:number;last_error:string|null }
export interface ProductionWrite { path:string;body?:unknown;blob?:Blob;mediaType?:FileMedia;version?:number;targetId?:string;projectId?:string;resultKind:ProductionKind|'ASSET';label:string; supply?:SupplyWrite }
export type ProductionResult = ProductionRecord | SupplyAsset
const obj=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==='object'&&!Array.isArray(v)
const str=(v:unknown,max=2000):v is string=>typeof v==='string'&&v.trim().length>0&&v.length<=max
const num=(v:unknown,min=0,max=4294967294)=>Number.isSafeInteger(v)&&Number(v)>=min&&Number(v)<=max
const hash=(v:unknown)=>typeof v==='string'&&/^[a-f0-9]{64}$/.test(v)
const nullableId=(v:unknown)=>v===null||validSupplyId(v)
const nullableText=(v:unknown,max=128)=>v===null||str(v,max)
const stage=(v:unknown)=>typeof v==='string'&&Object.hasOwn(stages,v)
const map=(v:unknown,guard:(x:unknown)=>boolean)=>obj(v)&&Object.entries(v).every(([k,x])=>stage(k)&&guard(x))
const ids=(v:unknown)=>Array.isArray(v)&&v.length<=20&&new Set(v).size===v.length&&v.every(validSupplyId)
const checklist=(v:unknown)=>obj(v)&&v.script_reviewed===true&&(Object.keys(v).length===1||v.specification_reviewed===true&&v.audio_reviewed===true&&v.branding_reviewed===true)
const verification=(v:unknown)=>v===null||checklist(v)||obj(v)&&hash(v.contract_sha256)&&v.identity_verified===true&&v.signatures_verified===true&&v.rights_verified===true
const review=(v:unknown)=>v===null||obj(v)&&['APPROVED','REJECTED'].includes(String(v.decision))&&str(v.reason)&&verification(v.verification)&&validSupplyId(v.account_id)&&v.method==='EXTERNAL_MANUAL_REVIEW'
const provider=(v:Record<string,unknown>)=>str(v.provider_code,128)&&['SANDBOX','PRODUCTION'].includes(String(v.environment))&&str(v.config_revision,128)
export function isProductionRecord(v:unknown):v is ProductionRecord {
 if(!obj(v)||!validSupplyId(v.id)||!nullableId(v.project_id)||!validSupplyId(v.order_id)||!nullableId(v.created_by)||!num(v.object_version,1,100000)||!hash(v.content_sha256)||!obj(v.data))return false
 const d=v.data,s=String(v.current_status)
 switch(v.kind){
 case 'PROJECT':return v.project_id===null&&['IN_REVIEW','READY','IN_PROGRESS','ACCEPTED','REJECTED'].includes(s)&&str(d.line_id,128)&&[d.buyer_party_id,d.merchant_party_id,d.producer_party_id,d.script_version_id,d.assignee_account_id,d.evidence_asset_id].every(validSupplyId)&&nullableId(d.license_project_id)&&str(d.purpose,100)&&str(d.territory,100)&&ids(d.consent_ids)&&isSpecification(d.specification)&&num(d.quantity,1,100000)&&hash(d.contract_sha256)&&map(d.current,validSupplyId)&&map(d.accepted,validSupplyId)&&map(d.revisions,x=>num(x))&&num(d.change_requests)&&review(d.review)&&(d.assignment_reason===undefined||str(d.assignment_reason))
 case 'FILE':return validSupplyId(v.project_id)&&['UPLOADING','READY','FAILED'].includes(s)&&str(d.object_key,512)&&Object.hasOwn(fileMedia,String(d.media_type))&&num(d.byte_size,1,MAX_FILE_BYTES)&&hash(d.content_sha256)
 case 'VERSION':return validSupplyId(v.project_id)&&['IN_REVIEW','APPROVED','REJECTED'].includes(s)&&stage(d.stage)&&num(d.revision,1,100000)&&validSupplyId(d.file_id)&&validSupplyId(d.preview_file_id)&&nullableId(d.basis_version_id)&&str(d.note)&&review(d.review)&&(d.last_feedback_id===undefined||validSupplyId(d.last_feedback_id))
 case 'FEEDBACK':return validSupplyId(v.project_id)&&s==='RECORDED'&&validSupplyId(d.version_id)&&stage(d.stage)&&['ACCEPT','REQUEST_CHANGES'].includes(String(d.decision))&&str(d.note,4000)&&(d.checklist===null||checklist(d.checklist))
 case 'GENERATION':return validSupplyId(v.project_id)&&['QUEUED','PENDING','SUCCEEDED'].includes(s)&&Object.hasOwn(operations,String(d.operation))&&validSupplyId(d.avatar_id)&&validSupplyId(d.consent_id)&&nullableId(d.asset_id)&&provider(d)&&nullableId(d.script_version_id)&&nullableId(d.job_id)&&nullableText(d.upstream_task_id)&&(d.result===null||obj(d.result)&&(validSupplyId(d.result.asset_id)&&d.result.asset_type==='LONG_LIVED_AVATAR'||d.result.deleted===true||str(d.result.result_ref,128)&&d.result.delivery_state==='AWAITING_PRIVATE_IMPORT_AND_REVIEW'))
 case 'DIGITAL_ASSET':return validSupplyId(v.project_id)&&['READY','DELETE_REQUIRED','DELETING','DELETED'].includes(s)&&validSupplyId(d.avatar_id)&&validSupplyId(d.consent_id)&&provider(d)&&str(d.upstream_asset_ref,128)&&d.asset_type==='LONG_LIVED_AVATAR'
 default:return false
 }
}
export function isReadiness(v:unknown):v is Readiness{return obj(v)&&provider(v)&&['NOT_ENABLED','SERVICE_READY'].includes(String(v.current_status))&&nullableText(v.reason_code)}
export function isJob(v:unknown):v is Job{return obj(v)&&validSupplyId(v.record_id)&&validSupplyId(v.job_id)&&['PENDING','RUNNING','RETRY','FAILED','BLOCKED','SUCCEEDED'].includes(String(v.current_status))&&num(v.attempts)&&nullableText(v.last_error,80)}
const options=(i:SupplyIdentity,signal?:AbortSignal)=>({token:i.token,actingParty:i.partyId,cache:'no-store' as const,signal})
function checked<T>(r:ApiResult<unknown>,i:SupplyIdentity,guard:(v:unknown)=>v is T):T {if(!guard(r.data)||!r.meta?.request_id||r.meta.actor?.account_id!==i.accountId||r.meta.acting_party!==i.partyId)throw new ApiError({status:200,code:'UNEXPECTED_RESPONSE_SHAPE',message:'制作记录回复未能确认，请重新核对。',requestId:r.requestId});return r.data}
export async function listProduction(i:SupplyIdentity,projectId?:string,kind?:Exclude<ProductionKind,'PROJECT'>,cursor:string|null=null,signal?:AbortSignal){const q=new URLSearchParams({limit:'20'});if(kind)q.set('kind',kind);if(cursor)q.set('cursor',cursor);return checked(await request(projectId?`/production/projects/${projectId}/records?${q}`:`/production/projects?${q}`,options(i,signal)),i,(v):v is ProductionPage=>obj(v)&&Array.isArray(v.items)&&v.items.length<=100&&v.items.every(r=>isProductionRecord(r)&&(projectId?r.project_id===projectId&&r.kind===kind:r.kind==='PROJECT'&&(!i.partyId||[r.data.buyer_party_id,r.data.merchant_party_id,r.data.producer_party_id].includes(i.partyId))))&&nullableId(v.next_cursor))}
export async function getProduction(i:SupplyIdentity,id:string,kind?:ProductionKind,signal?:AbortSignal){return checked(await request(`/production/records/${id}`,options(i,signal)),i,(v):v is ProductionRecord=>isProductionRecord(v)&&v.id===id&&(!kind||v.kind===kind))}
export async function postProduction(i:SupplyIdentity,c:ProductionWrite,key:string,signal?:AbortSignal):Promise<ProductionResult>{if(c.supply)return postSupply(i,c.supply,key,signal) as Promise<SupplyAsset>;return checked(await request(c.path,{...options(i,signal),method:'POST',body:c.body,rawBody:c.blob,idempotencyKey:key,ifMatch:c.version}),i,(v):v is ProductionRecord=>isProductionRecord(v)&&v.kind===c.resultKind&&(!c.projectId||v.project_id===c.projectId)&&(!c.targetId||v.id===c.targetId||v.kind==='VERSION'&&v.project_id===c.targetId||v.kind==='FEEDBACK'&&v.data.version_id===c.targetId||v.kind==='GENERATION'&&v.project_id===c.targetId))}
export const getProductionResult=(i:SupplyIdentity,id:string,kind:ProductionWrite['resultKind'],signal?:AbortSignal):Promise<ProductionResult>=>kind==='ASSET'?getSupplyAsset(i,id,signal):getProduction(i,id,kind,signal)
export async function productionReadiness(i:SupplyIdentity,id:string,signal?:AbortSignal){return checked(await request(`/production/projects/${id}/generation-readiness`,options(i,signal)),i,isReadiness)}
export async function productionJob(i:SupplyIdentity,id:string,signal?:AbortSignal){return checked(await request(`/production/generations/${id}/job`,options(i,signal)),i,(v):v is Job=>isJob(v)&&v.record_id===id)}
export const productionContent=(i:SupplyIdentity,id:string,variant:'preview'|'final',signal?:AbortSignal)=>requestBytes(`/production/versions/${id}/content?variant=${variant}`,options(i,signal))
export const productionEvidence=(i:SupplyIdentity,id:string,signal?:AbortSignal)=>requestBytes(`/production/projects/${id}/evidence`,options(i,signal))
export const labels:Record<string,string>={IN_REVIEW:'待独立核验',READY:'开工依据已核验',IN_PROGRESS:'制作进行中',ACCEPTED:'当前成片已验收',REJECTED:'已拒绝',UPLOADING:'上传结果待核实',FAILED:'已确认失败',APPROVED:'内部审片已通过，待客户决定',RECORDED:'已保存本版反馈',QUEUED:'请求已排队，未完成生成',PENDING:'等待实际服务结果',SUCCEEDED:'已核实服务结果',DELETE_REQUIRED:'需删除，尚未删除',DELETING:'删除处理中',DELETED:'已获实际删除确认'}
export const productionStatus=(r:Pick<ProductionRecord,'kind'|'current_status'>)=>r.kind==='FILE'&&r.current_status==='READY'?'私有文件可引用':r.kind==='DIGITAL_ASSET'&&r.current_status==='READY'?'长期资产已获服务确认':labels[r.current_status]||r.current_status
export function canStage(p:ProductionRecord,stage:Stage){if(p.kind!=='PROJECT'||!['READY','IN_PROGRESS'].includes(p.current_status))return false;const prev=Object.keys(stages)[Object.keys(stages).indexOf(stage)-1] as Stage|undefined;return !prev||!!p.data.current[prev]&&p.data.current[prev]===p.data.accepted[prev]}
export function currentApproved(p:ProductionRecord,v:ProductionRecord){return p.kind==='PROJECT'&&v.kind==='VERSION'&&v.project_id===p.id&&v.current_status==='APPROVED'&&p.data.current[v.data.stage]===v.id}
export function checkedStage(stage:Stage,checks:Record<string,boolean>):Verification|null{if(!checks.script_reviewed)return null;if(stage==='SCRIPT')return {script_reviewed:true};return ['specification_reviewed','audio_reviewed','branding_reviewed'].every(k=>checks[k])?{script_reviewed:true,specification_reviewed:true,audio_reviewed:true,branding_reviewed:true}:null}
/** These are existing private supply lists, not a public account or avatar directory. */
export interface Dependency { id:string;kind:'AVATAR'|'CONSENT';owner_party_id:string;current_status:string;data:{display_name?:string;consent?:{avatar_id:string;subject_party_id:string;features:string[];purposes:string[];territories:string[];valid_until:string}} }
export async function listDependencies(i:SupplyIdentity,kind:'AVATAR'|'CONSENT',signal?:AbortSignal){const all:Dependency[]=[],seen=new Set<string>();let cursor:string|null=null;do{const q=new URLSearchParams({kind,limit:'20'});if(cursor)q.set('cursor',cursor);const page=checked(await request(`/supply/records?${q}`,options(i,signal)),i,(v):v is {items:Dependency[];next_cursor:string|null}=>obj(v)&&Array.isArray(v.items)&&v.items.every(r=>obj(r)&&validSupplyId(r.id)&&r.kind===kind&&validSupplyId(r.owner_party_id)&&str(r.current_status,80)&&obj(r.data)&&(kind==='AVATAR'?str(r.data.display_name,120):obj(r.data.consent)&&validSupplyId(r.data.consent.avatar_id)&&validSupplyId(r.data.consent.subject_party_id)&&Array.isArray(r.data.consent.features)&&Array.isArray(r.data.consent.purposes)&&Array.isArray(r.data.consent.territories)&&str(r.data.consent.valid_until,40)))&&nullableId(v.next_cursor));all.push(...page.items);cursor=page.next_cursor;if(cursor&&seen.has(cursor))throw new ApiError({status:200,code:'UNEXPECTED_RESPONSE_SHAPE',message:'同意记录分页重复，请重新读取。'});if(cursor)seen.add(cursor)}while(cursor);return all}
