import { ApiError, request, requestBytes, type ApiResult } from '../client'
import { validSupplyId, getSupplyAsset, postSupply, type SupplyIdentity, type SupplyAsset, type SupplyWrite } from './supply'
export const layers={FACE_VOICE:'脸声',ORIGINAL:'原始作品',SCRIPT:'剧本',MUSIC:'音乐',ADAPTATION:'改编',FINAL:'最终成片'} as const
export type Layer=keyof typeof layers
export interface Scope {purpose:'PUBLIC_SHARE'|'RELEASE';territory:string;language:string;valid_until:string}
export interface Right {layer:Layer;holder_party_id:string;evidence_asset_id:string;purpose:Scope['purpose'];territory:string;valid_until:string;terms:string}
export interface Confirmer {party_id:string;responsibility:string;after_party_ids:string[]}
export interface Funding {candidate_id:string;order_id:string;line_id:string}
export const reviewFields={PLAN:['identity_verified','signatures_verified','rights_verified','production_verified'],EDITION:['rights_verified','content_verified','credits_verified','materials_verified'],CHANNEL:['channel_verified','requirements_verified'],RELEASE:['rights_verified','materials_verified','channel_verified'],EXTERNAL_EVENT:['source_verified','reference_verified','outcome_verified']} as const
export const verificationLabels:Record<string,string>={identity_verified:'身份已核实',signatures_verified:'真实签署材料已核实',rights_verified:'本次权利已核实',production_verified:'制作与角色资金已核实',content_verified:'成片内容已核实',credits_verified:'署名已核实',materials_verified:'材料已核实',channel_verified:'渠道已核实',requirements_verified:'提交要求已核实',source_verified:'外部凭据来源已核实',reference_verified:'外部参考已核实',outcome_verified:'实际结果已核实'}
export interface Review {decision:'APPROVED'|'CHANGES_REQUESTED'|'REJECTED';reason:string;verification:Record<string,boolean>;reviewer_account_id:string;method:'MANUAL_EVIDENCE_REVIEW'}
interface Base {id:string;project_id:string|null;owner_party_id:string;created_by:string;current_status:string;object_version:number;content_sha256:string}
export type ProjectRecord=Base&(
 {kind:'PROJECT';data:{title:string;scope:Scope;current_plan_id:string|null;current_edition_id:string|null;cancel_reason:string|null}}|
 {kind:'ROLE';data:{title:string;capacity:number;pricing:'FIXED'|'QUOTE';amount_minor:number|null;terms:string}}|
 {kind:'CANDIDATE';data:{role_id:string;avatar_id:string|null;consent_id:string|null;amount_minor:number|null;note:string|null;terms:string;final_confirmed_by:string|null}}|
 {kind:'PLAN';data:{production_project_id:string;rights:Right[];confirmers:Confirmer[];funding:Funding[];terms:string;roster_sha256:string;review:Review|null}}|
 {kind:'EDITION';data:{plan_id:string;final_version_id:string;final_content_sha256:string;material_asset_ids:string[];confirmers:Confirmer[];note:string;review:Review|null}}|
 {kind:'CHANNEL';data:{name:string;channel_reference:string;submission_requirements:string;evidence_asset_id:string;review:Review|null}}|
 {kind:'RELEASE';data:{edition_id:string;channel_id:string;prior_release_id:string|null;material_asset_ids:string[];note:string;review:Review|null;last_external_event_id:string|null}}|
 {kind:'EXTERNAL_EVENT';data:{release_id:string;outcome:'SUBMITTED'|'CHANGES_REQUESTED'|'REJECTED'|'PUBLISHED'|'WITHDRAWN';external_reference:string;occurred_at:string;evidence_asset_id:string;note:string;review:Review|null;provenance:'EXTERNAL_MANUAL_EVIDENCE'}})
export type ProjectKind=ProjectRecord['kind']
export type ChildKind=Exclude<ProjectKind,'PROJECT'|'CHANNEL'>
export interface ProjectPage {items:ProjectRecord[];next_cursor:string|null}
export interface CatalogueRole {id:string;object_version:number;title:string;capacity:number;pricing:'FIXED'|'QUOTE';amount_minor:number|null;terms:string}
export interface CatalogueItem {id:string;kind:'PROJECT'|'CHANNEL';title:string;scope:Scope|null;channel_reference:string|null;roles:CatalogueRole[]}
export interface Confirmation {party_id:string;account_id:string;content_sha256:string;decision:'APPROVED'|'REJECTED';reason:string}
export interface ProjectReadiness {current_status:'AVAILABLE'|'BLOCKED';reason_code:string|null}
export interface ProjectWrite {path:string;body?:unknown;version?:number;targetId?:string;projectId?:string;resultKind:ProjectKind|'ASSET';label:string;supply?:SupplyWrite;confirmation?:boolean;catalogueRecovery?:boolean}
export type ProjectResult=ProjectRecord|SupplyAsset
const obj=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==='object'&&!Array.isArray(v)
const exact=(v:unknown,keys:string[]):v is Record<string,unknown>=>obj(v)&&Object.keys(v).length===keys.length&&keys.every(k=>Object.hasOwn(v,k))
const str=(v:unknown,max=8000):v is string=>typeof v==='string'&&v.trim().length>0&&v.length<=max
const num=(v:unknown,min=0,max=900000000000)=>Number.isSafeInteger(v)&&Number(v)>=min&&Number(v)<=max
const hash=(v:unknown)=>typeof v==='string'&&/^[a-f0-9]{64}$/.test(v)
const nullableId=(v:unknown)=>v===null||validSupplyId(v)
const nullableText=(v:unknown)=>v===null||str(v)
export const iso=(v:unknown):v is string=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(v)&&Number.isFinite(Date.parse(v))&&new Date(v).toISOString()===v
const ids=(v:unknown,max=30)=>Array.isArray(v)&&v.length<=max&&v.every(validSupplyId)
export const isScope=(v:unknown):v is Scope=>exact(v,['purpose','territory','language','valid_until'])&&['PUBLIC_SHARE','RELEASE'].includes(String(v.purpose))&&typeof v.territory==='string'&&/^[A-Z]{2}$/.test(v.territory)&&typeof v.language==='string'&&/^[a-z]{2}$/.test(v.language)&&iso(v.valid_until)
const right=(v:unknown)=>exact(v,['layer','holder_party_id','evidence_asset_id','purpose','territory','valid_until','terms'])&&Object.hasOwn(layers,String(v.layer))&&validSupplyId(v.holder_party_id)&&validSupplyId(v.evidence_asset_id)&&['PUBLIC_SHARE','RELEASE'].includes(String(v.purpose))&&typeof v.territory==='string'&&/^[A-Z]{2}$/.test(v.territory)&&iso(v.valid_until)&&str(v.terms)
const confirmer=(v:unknown)=>exact(v,['party_id','responsibility','after_party_ids'])&&validSupplyId(v.party_id)&&str(v.responsibility,1000)&&ids(v.after_party_ids,50)&&new Set(v.after_party_ids as string[]).size===(v.after_party_ids as string[]).length
const funding=(v:unknown)=>exact(v,['candidate_id','order_id','line_id'])&&validSupplyId(v.candidate_id)&&validSupplyId(v.order_id)&&str(v.line_id,128)
function review(v:unknown,kind:keyof typeof reviewFields){return v===null||exact(v,['decision','reason','verification','reviewer_account_id','method'])&&['APPROVED','CHANGES_REQUESTED','REJECTED'].includes(String(v.decision))&&str(v.reason,4000)&&obj(v.verification)&&Object.entries(v.verification).every(([k,x])=>(reviewFields[kind] as readonly string[]).includes(k)&&typeof x==='boolean')&&(v.decision!=='APPROVED'||reviewFields[kind].every(k=>(v.verification as Record<string,unknown>)[k]===true))&&validSupplyId(v.reviewer_account_id)&&v.method==='MANUAL_EVIDENCE_REVIEW'}
export function isProjectRecord(v:unknown):v is ProjectRecord {
 if(!exact(v,['id','kind','project_id','owner_party_id','created_by','current_status','object_version','content_sha256','data'])||![v.id,v.owner_party_id,v.created_by].every(validSupplyId)||!num(v.object_version,1)||!hash(v.content_sha256)||!obj(v.data))return false
 const d=v.data,s=String(v.current_status),child=validSupplyId(v.project_id),reviewStatus=['IN_REVIEW','APPROVED','CHANGES_REQUESTED','REJECTED'].includes(s)
 const signers=(x:unknown)=>Array.isArray(x)&&x.length>0&&x.length<=50&&x.every(confirmer)
 switch(v.kind){
 case 'PROJECT':return v.project_id===null&&['PREPARING','STARTED','CANCELLED'].includes(s)&&exact(d,['title','scope','current_plan_id','current_edition_id','cancel_reason'])&&str(d.title)&&isScope(d.scope)&&nullableId(d.current_plan_id)&&nullableId(d.current_edition_id)&&nullableText(d.cancel_reason)
 case 'ROLE':return child&&s==='OPEN'&&exact(d,['title','capacity','pricing','amount_minor','terms'])&&str(d.title)&&num(d.capacity,1,100)&&['FIXED','QUOTE'].includes(String(d.pricing))&&(d.pricing==='FIXED'?num(d.amount_minor):d.amount_minor===null)&&str(d.terms)
 case 'CANDIDATE':return child&&['INVITED','APPLIED','DECLINED','SELECTED','CONFIRMED','REJECTED','WITHDRAWN'].includes(s)&&exact(d,['role_id','avatar_id','consent_id','amount_minor','note','terms','final_confirmed_by'])&&validSupplyId(d.role_id)&&nullableId(d.avatar_id)&&nullableId(d.consent_id)&&(d.amount_minor===null||num(d.amount_minor))&&nullableText(d.note)&&str(d.terms)&&nullableId(d.final_confirmed_by)
 case 'PLAN':return child&&reviewStatus&&exact(d,['production_project_id','rights','confirmers','funding','terms','roster_sha256','review'])&&validSupplyId(d.production_project_id)&&Array.isArray(d.rights)&&d.rights.length===6&&d.rights.every(right)&&new Set(d.rights.map(x=>x.layer)).size===6&&signers(d.confirmers)&&Array.isArray(d.funding)&&d.funding.length<=100&&d.funding.every(funding)&&str(d.terms)&&hash(d.roster_sha256)&&review(d.review,'PLAN')
 case 'EDITION':return child&&reviewStatus&&exact(d,['plan_id','final_version_id','final_content_sha256','material_asset_ids','confirmers','note','review'])&&validSupplyId(d.plan_id)&&validSupplyId(d.final_version_id)&&hash(d.final_content_sha256)&&ids(d.material_asset_ids)&&(d.material_asset_ids as unknown[]).length>0&&signers(d.confirmers)&&str(d.note)&&review(d.review,'EDITION')
 case 'CHANNEL':return v.project_id===null&&reviewStatus&&exact(d,['name','channel_reference','submission_requirements','evidence_asset_id','review'])&&str(d.name)&&str(d.channel_reference)&&str(d.submission_requirements)&&validSupplyId(d.evidence_asset_id)&&review(d.review,'CHANNEL')
 case 'RELEASE':return child&&['INTERNAL_PENDING','READY_TO_SUBMIT','CHANGES_REQUESTED','REJECTED','EXTERNAL_SUBMITTED','EXTERNAL_CHANGES_REQUESTED','EXTERNAL_REJECTED','EXTERNAL_PUBLISHED','EXTERNAL_WITHDRAWN'].includes(s)&&exact(d,['edition_id','channel_id','prior_release_id','material_asset_ids','note','review','last_external_event_id'])&&validSupplyId(d.edition_id)&&validSupplyId(d.channel_id)&&nullableId(d.prior_release_id)&&ids(d.material_asset_ids)&&(d.material_asset_ids as unknown[]).length>0&&str(d.note)&&review(d.review,'RELEASE')&&nullableId(d.last_external_event_id)
 case 'EXTERNAL_EVENT':return child&&reviewStatus&&exact(d,['release_id','outcome','external_reference','occurred_at','evidence_asset_id','note','review','provenance'])&&validSupplyId(d.release_id)&&['SUBMITTED','CHANGES_REQUESTED','REJECTED','PUBLISHED','WITHDRAWN'].includes(String(d.outcome))&&str(d.external_reference)&&iso(d.occurred_at)&&validSupplyId(d.evidence_asset_id)&&str(d.note)&&review(d.review,'EXTERNAL_EVENT')&&d.provenance==='EXTERNAL_MANUAL_EVIDENCE'
 default:return false
 }
}
export function isCatalogue(v:unknown):v is {items:CatalogueItem[]}{return exact(v,['items'])&&Array.isArray(v.items)&&v.items.length<=100&&v.items.every(x=>exact(x,['id','kind','title','scope','channel_reference','roles'])&&validSupplyId(x.id)&&str(x.title)&&['PROJECT','CHANNEL'].includes(String(x.kind))&&(x.kind==='PROJECT'?isScope(x.scope)&&x.channel_reference===null:x.scope===null&&str(x.channel_reference))&&Array.isArray(x.roles)&&x.roles.every(r=>exact(r,['id','object_version','title','capacity','pricing','amount_minor','terms'])&&validSupplyId(r.id)&&num(r.object_version,1)&&str(r.title)&&num(r.capacity,1,100)&&['FIXED','QUOTE'].includes(String(r.pricing))&&(r.pricing==='FIXED'?num(r.amount_minor):r.amount_minor===null)&&str(r.terms)))}
const options=(i:SupplyIdentity,signal?:AbortSignal)=>({token:i.token,actingParty:i.partyId,cache:'no-store' as const,signal})
function checked<T>(r:ApiResult<unknown>,i:SupplyIdentity,guard:(v:unknown)=>v is T):T {if(!guard(r.data)||!r.meta?.request_id||r.meta.actor?.account_id!==i.accountId||r.meta.acting_party!==i.partyId)throw new ApiError({status:200,code:'UNEXPECTED_RESPONSE_SHAPE',message:'项目回复的身份或内容不符合契约，请核对原操作。',requestId:r.requestId});return r.data}
export async function getProject(i:SupplyIdentity,id:string,kind?:ProjectKind,signal?:AbortSignal){return checked(await request(`/projects/records/${id}`,options(i,signal)),i,(v):v is ProjectRecord=>isProjectRecord(v)&&v.id===id&&(!kind||v.kind===kind))}
export async function listProjects(i:SupplyIdentity,projectId?:string,kind?:ChildKind,cursor:string|null=null,signal?:AbortSignal){const q=new URLSearchParams({limit:'20'});if(kind)q.set('kind',kind);if(cursor)q.set('cursor',cursor);return checked(await request(projectId?`/projects/projects/${projectId}/records?${q}`:`/projects/projects?${q}`,options(i,signal)),i,(v):v is ProjectPage=>exact(v,['items','next_cursor'])&&Array.isArray(v.items)&&v.items.length<=100&&v.items.every(r=>isProjectRecord(r)&&(projectId?r.project_id===projectId&&r.kind===kind:r.kind==='PROJECT'))&&nullableId(v.next_cursor))}
export async function projectCatalogue(i:SupplyIdentity,signal?:AbortSignal){const publicIdentity={...i,partyId:null};return checked(await request('/projects/catalogue',options(publicIdentity,signal)),publicIdentity,isCatalogue)}
export async function projectConfirmations(i:SupplyIdentity,id:string,signal?:AbortSignal){return checked(await request(`/projects/records/${id}/confirmations`,options(i,signal)),i,(v):v is {items:Confirmation[]}=>exact(v,['items'])&&Array.isArray(v.items)&&v.items.every(x=>exact(x,['party_id','account_id','content_sha256','decision','reason'])&&validSupplyId(x.party_id)&&validSupplyId(x.account_id)&&hash(x.content_sha256)&&['APPROVED','REJECTED'].includes(String(x.decision))&&str(x.reason)))}
export async function projectReadiness(i:SupplyIdentity,id:string,signal?:AbortSignal){return checked(await request(`/projects/projects/${id}/readiness`,options(i,signal)),i,(v):v is ProjectReadiness=>exact(v,['current_status','reason_code'])&&(v.current_status==='AVAILABLE'?v.reason_code===null:v.current_status==='BLOCKED'&&str(v.reason_code,128)))}
export async function postProject(i:SupplyIdentity,c:ProjectWrite,key:string,signal?:AbortSignal):Promise<ProjectResult>{if(c.supply)return postSupply(i,c.supply,key,signal) as Promise<SupplyAsset>;return checked(await request(c.path,{...options(i,signal),method:'POST',body:c.body,idempotencyKey:key,ifMatch:c.version}),i,(v):v is ProjectRecord=>isProjectRecord(v)&&v.kind===c.resultKind&&(!c.projectId||v.project_id===c.projectId||v.kind==='PROJECT'&&v.id===c.projectId)&&(!c.targetId||v.id===c.targetId||v.project_id===c.targetId||v.kind==='CANDIDATE'&&v.data.role_id===c.targetId||v.kind==='EXTERNAL_EVENT'&&v.data.release_id===c.targetId))}
export const getProjectResult=(i:SupplyIdentity,id:string,kind:ProjectWrite['resultKind'],signal?:AbortSignal):Promise<ProjectResult>=>kind==='ASSET'?getSupplyAsset(i,id,signal):getProject(i,id,kind,signal)
export const projectEvidence=(i:SupplyIdentity,id:string,asset:string,signal?:AbortSignal)=>requestBytes(`/projects/records/${id}/evidence/${asset}`,options(i,signal))
export function confirmationGate(r:ProjectRecord,party:string,items:Confirmation[]){if(r.kind!=='PLAN'&&r.kind!=='EDITION')return {can:false,message:'本记录不支持会签。'};const own=r.data.confirmers.find(x=>x.party_id===party);if(!own)return {can:false,message:'当前身份不是本版指定确认方。'};if(r.current_status!=='APPROVED')return {can:false,message:'本版尚未通过独立核验。'};if(items.some(x=>x.party_id===party))return {can:false,message:'本方已对这份记录作出决定；新版本须重新确认。'};const waiting=own.after_party_ids.filter(p=>!items.some(x=>x.party_id===p&&x.decision==='APPROVED'&&x.content_sha256===r.content_sha256));return {can:!waiting.length,message:waiting.length?`等待前置确认方：${waiting.join('、')}`:'前置确认已齐，可以核对本方决定。'}}
export const kindLabels:Record<ProjectKind,string>={PROJECT:'项目',ROLE:'招募角色',CANDIDATE:'候选',PLAN:'项目方案',EDITION:'成片材料版本',CHANNEL:'渠道档案',RELEASE:'发行申请',EXTERNAL_EVENT:'外部结果报告'}
export const statusLabels:Record<string,string>={PREPARING:'准备与招募中',STARTED:'项目已启动',CANCELLED:'项目已取消',OPEN:'角色开放',INVITED:'等待本人回应',APPLIED:'已申请，待筛选',DECLINED:'已谢绝邀请',SELECTED:'获选，待本人确认',CONFIRMED:'已由本人确认入选',WITHDRAWN:'已退出',IN_REVIEW:'待独立核验',APPROVED:'独立核验已通过',CHANGES_REQUESTED:'需补充材料，另提新版本',REJECTED:'已拒绝，保留原记录',INTERNAL_PENDING:'内部发行审核中',READY_TO_SUBMIT:'内部通过，可向外部送出',EXTERNAL_SUBMITTED:'已核实外部提交',EXTERNAL_CHANGES_REQUESTED:'已核实外部补件要求',EXTERNAL_REJECTED:'已核实外部拒绝',EXTERNAL_PUBLISHED:'已核实外部发行',EXTERNAL_WITHDRAWN:'已核实外部撤下'}
export const projectStatus=(r:Pick<ProjectRecord,'kind'|'current_status'>)=>statusLabels[r.current_status]||r.current_status
export const evidenceIds=(r:ProjectRecord)=>r.kind==='PLAN'?r.data.rights.map(x=>x.evidence_asset_id):r.kind==='EDITION'||r.kind==='RELEASE'?r.data.material_asset_ids:r.kind==='CHANNEL'||r.kind==='EXTERNAL_EVENT'?[r.data.evidence_asset_id]:[]

/** Parse explicitly entered yuan without floating point rounding; blank is unknown. */
export function parseMoney(v:string){if(!/^(0|[1-9][0-9]*)(\.[0-9]{1,2})?$/.test(v))return null;const [whole,frac='']=v.split('.');const minor=BigInt(whole!)*100n+BigInt(frac.padEnd(2,'0'));return minor<=900000000000n?Number(minor):null}
