import { ApiError, request, requestBytes, type ApiResult } from '../client'
import { snapshotContent, type SnapshotContent } from './contracts'
import { validSupplyId, type SupplyIdentity } from './supply'
import { instant, minorInteger } from './licensing'
import { isCommercialSnapshot, type CommercialSnapshot } from './gigs'

export const tradeKinds = ['SPEC','QUOTE','ORDER','PAYMENT','REFUND','LEGACY'] as const
/** Known trade snapshot labels only; arbitrary rule content and stored values remain intact. */
export const tradeContractLabels: Readonly<Record<string,string>> = {
 quote_id:'报价编号',quote_sha256:'报价内容指纹',quote:'原成交报价',lines:'服务明细',installments:'付款节点',total_minor:'总金额（人民币分）',currency:'币种',channel:'支付渠道',transaction_model:'交易责任方式',rule_id:'采用规则编号',expires_at:'报价截止时间',payment_window_minutes:'付款窗口（分钟）',license_reservation_id:'关联许可预留',review:'已保存审核意见',order_id:'订单编号',line_id:'明细编号',spec_id:'规格编号',spec_version:'规格记录版本',quantity:'数量',unit_minor:'单价（人民币分）',provider_party_id:'实际提供方主体',line_kind:'服务类型',specification:'原服务规格',title:'服务名称',version:'规格版本',service_tier:'服务档位',sample_seconds:'样片时长（秒）',final_seconds:'成片时长（秒）',revision_limit:'可修改次数',deliverables:'约定交付内容',terms:'原条款',decision:'审核结论',reason:'审核理由',account_id:'审核账号',key:'付款节点名称',trigger:'付款触发条件',allocations:'逐项分摊',amount_minor:'金额（人民币分）',apple_product_id:'Apple商品编号',
}
export type TradeKind = typeof tradeKinds[number]
export const lineKinds = { LICENSE:'许可', PRODUCTION:'制作', OTHER:'其他明确服务' } as const
export const triggers = { ORDER_ACCEPTED:'确认订单', SAMPLE_ACCEPTED:'当前样片版本验收', FINAL_ACCEPTED:'当前成片版本验收' } as const
export interface Specification { version:string; service_tier:string; sample_seconds:number; final_seconds:number; revision_limit:number; deliverables:string[]; terms:string }
export interface Review { decision:'APPROVED'|'REJECTED'; reason:string; account_id:string }
export interface SpecData { title:string; provider_party_id:string; line_kind:keyof typeof lineKinds; unit_minor:number; currency:'CNY'; specification:Specification; review:Review|null }
export interface QuoteLine extends SpecData { line_id:string; spec_id:string; spec_version:number; quantity:number; total_minor:number }
export interface Allocation { line_id:string; amount_minor:number }
export interface Installment { key:string; trigger:keyof typeof triggers; allocations:Allocation[]; apple_product_id:string|null }
export interface QuoteData { commercial?:CommercialSnapshot; lines:QuoteLine[]; installments:Installment[]; total_minor:number; currency:'CNY'; channel:'ALIPAY'|'APPLE'; transaction_model:'DIRECT_SUPPLIER'|'PLATFORM_PRINCIPAL'; rule_id:string; expires_at:string; payment_window_minutes:number; license_reservation_id:string|null; review:Review|null; order_id?:string }
export interface OrderData { quote:QuoteData; contract:SnapshotContent; buyer_acknowledged_by:string; financial:{received_minor:number;refunded_minor:number;net_minor:number}; cancel_reason?:string }
export interface Proof { provider:'ALIPAY'|'APPLE'; environment:'SANDBOX'|'PRODUCTION'; app_id:string; merchant_id:string; currency:'CNY'; amount_minor:number; payment_id:string; transaction_id:string|null; status:string; product_id?:string|null; app_account_token?:string|null; refund_id?:string }
export interface PaymentData { provider:'ALIPAY'|'APPLE'; environment:'SANDBOX'|'PRODUCTION'; app_id:string; merchant_id:string; currency:'CNY'; amount_minor:number; config_revision:string; allocations:Allocation[]; installment_key:string; apple_product_id:string|null; title:string; payment_window_minutes:number; expires_at:string; checkout: {kind:'ALIPAY_APP';order_string:string}|{kind:'APPLE_STOREKIT2';product_id:string;app_account_token:string}|null; transaction_id:string|null; proof:Proof|null }
export interface RefundData { provider:'ALIPAY'|'APPLE'; environment:'SANDBOX'|'PRODUCTION'; app_id:string; merchant_id:string; currency:'CNY'; amount_minor:number; payment_id:string; allocations:Allocation[]; transaction_id:string; apple_product_id:string|null; reason:string; review:Review|null; proof?:Proof }
export interface LegacyData { source_system:string; source_order_id:string; original_lines:{line_id:string;amount_minor:number;reported_status:'REPORTED_PAID'|'REPORTED_UNPAID'|'UNKNOWN'}[]; original_terms:string; evidence_asset_id:string; currency:'CNY'; payment_verified:false; review:Review|null }
interface Base { id:string; buyer_party_id:string|null; merchant_party_id:string; parent_id:string|null; order_id:string|null; created_by:string|null; current_status:string; object_version:number; content_sha256:string }
export type TradeRecord = Base & ({kind:'SPEC';data:SpecData}|{kind:'QUOTE';data:QuoteData}|{kind:'ORDER';data:OrderData}|{kind:'PAYMENT';data:PaymentData}|{kind:'REFUND';data:RefundData}|{kind:'LEGACY';data:LegacyData})
export interface TradePage { items:TradeRecord[]; next_cursor:string|null }
export interface TradeWrite { path:string; body:unknown; version?:number; targetId?:string; resultKind:TradeKind; label:string }
export const statuses:Record<string,string> = {IN_REVIEW:'待独立审核',PUBLISHED:'已发布规格',REJECTED:'已拒绝',ACCEPTED:'已确认报价',OPEN:'待付款',PARTIALLY_PAID:'已收到部分款',PAID:'约定款项已收齐',PARTIALLY_REFUNDED:'已核实部分退款',REFUNDED:'已核实全部退款',PAYMENT_REVIEW_REQUIRED:'款项异常待人工核对',CANCELLED:'已取消',CREATED:'已建立付款记录',SUBMITTING:'正在提交或核实',PENDING:'等待渠道结果',UNKNOWN:'结果待核实',CLOSED:'付款已关闭',REQUESTED:'退款待独立复核',AWAITING_APPLE_REQUEST:'等待用户在 Apple 流程申请退款',SUCCEEDED:'已核实成功',FAILED:'已核实失败',NEEDS_REVIEW:'历史材料待独立核对',VERIFIED_REFERENCE_ONLY:'已核对历史材料，未追认渠道到账'}
export function tradeStatus(r:Pick<TradeRecord,'kind'|'current_status'>) { if(r.current_status==='APPROVED')return r.kind==='REFUND'?'退款已批准，尚未退款':'报价已审，等待买方确认';if(r.current_status==='SUCCEEDED')return r.kind==='REFUND'?'退款已核实':'付款已核实到账';return statuses[r.current_status]||r.current_status }
export const money = (minor:number) => { const n=BigInt(minor);return `¥${(n/100n).toLocaleString('zh-CN')}.${String(n%100n).padStart(2,'0')}` }
export const amountInput = (v:string,min=1,max=900000000000) => {const n=minorInteger(v);return n!==null && n>=min && n<=max?n:null}
const obj=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==='object'&&!Array.isArray(v)
const text=(v:unknown,max=2000):v is string=>typeof v==='string'&&v.trim().length>0&&v.length<=max
const integer=(v:unknown,min=1,max=900000000000)=>Number.isSafeInteger(v)&&Number(v)>=min&&Number(v)<=max
const nullableId=(v:unknown)=>v===null||validSupplyId(v)
const nullableText=(v:unknown)=>v===null||text(v,128)
const hash=(v:unknown)=>typeof v==='string'&&/^[a-f0-9]{64}$/.test(v)
const rows=(v:unknown,guard:(x:unknown)=>boolean,max=30)=>Array.isArray(v)&&v.length>0&&v.length<=max&&v.every(guard)
const unique=(v:unknown[],key:(x:unknown)=>unknown)=>new Set(v.map(key)).size===v.length
const review=(v:unknown)=>v===null||obj(v)&&['APPROVED','REJECTED'].includes(String(v.decision))&&text(v.reason)&&validSupplyId(v.account_id)
export function isSpecification(v:unknown):v is Specification{return obj(v)&&text(v.version,128)&&text(v.service_tier,100)&&integer(v.sample_seconds,0,100000)&&integer(v.final_seconds,0,100000)&&integer(v.revision_limit,0,100000)&&rows(v.deliverables,x=>text(x,500))&&unique(v.deliverables as unknown[],x=>x)&&text(v.terms,8000)}
const spec=(v:unknown):v is SpecData=>obj(v)&&text(v.title,200)&&validSupplyId(v.provider_party_id)&&Object.hasOwn(lineKinds,String(v.line_kind))&&integer(v.unit_minor)&&v.currency==='CNY'&&isSpecification(v.specification)&&review(v.review)
const allocation=(v:unknown):v is Allocation=>obj(v)&&text(v.line_id,128)&&integer(v.amount_minor)
const allocations=(v:unknown):v is Allocation[]=>rows(v,allocation)&&unique(v as unknown[],x=>(x as Allocation).line_id)
const line=(v:unknown):v is QuoteLine=>spec(v)&&obj(v)&&text(v.line_id,128)&&validSupplyId(v.spec_id)&&integer(v.spec_version,1,100000)&&integer(v.quantity,1,10000)&&integer(v.total_minor)&&v.total_minor===v.unit_minor*Number(v.quantity)
const installment=(v:unknown):v is Installment=>obj(v)&&text(v.key,128)&&Object.hasOwn(triggers,String(v.trigger))&&allocations(v.allocations)&&nullableText(v.apple_product_id)
const quote=(v:unknown):v is QuoteData=>{if(!obj(v)||!rows(v.lines,line)||!rows(v.installments,installment,20)||!integer(v.total_minor)||v.currency!=='CNY'||!['ALIPAY','APPLE'].includes(String(v.channel))||!['DIRECT_SUPPLIER','PLATFORM_PRINCIPAL'].includes(String(v.transaction_model))||!validSupplyId(v.rule_id)||!instant(v.expires_at)||!integer(v.payment_window_minutes,1,10080)||!nullableId(v.license_reservation_id)||!review(v.review)||v.order_id!==undefined&&!validSupplyId(v.order_id)||v.commercial!==undefined&&!isCommercialSnapshot(v.commercial))return false;const ls=v.lines as QuoteLine[],ins=v.installments as Installment[];return unique(ls,x=>(x as QuoteLine).line_id)&&unique(ins,x=>(x as Installment).key)&&ls.reduce((s,l)=>s+l.total_minor,0)===v.total_minor&&ls.every(l=>ins.flatMap(i=>i.allocations).filter(a=>a.line_id===l.line_id).reduce((s,a)=>s+a.amount_minor,0)===l.total_minor)&&ins.every(i=>i.allocations.every(a=>ls.some(l=>l.line_id===a.line_id)))}
const channel=(v:Record<string,unknown>)=>['ALIPAY','APPLE'].includes(String(v.provider))&&['SANDBOX','PRODUCTION'].includes(String(v.environment))&&text(v.app_id,200)&&text(v.merchant_id,200)&&v.currency==='CNY'&&integer(v.amount_minor)
const proof=(v:unknown)=>obj(v)&&channel(v)&&validSupplyId(v.payment_id)&&nullableText(v.transaction_id)&&['PENDING','SUCCEEDED','CLOSED','REFUNDED','REVIEW_REQUIRED'].includes(String(v.status))&&(v.refund_id===undefined||validSupplyId(v.refund_id))&&(v.app_account_token===undefined||nullableId(v.app_account_token))
const checkout=(v:unknown)=>v===null||obj(v)&&(v.kind==='ALIPAY_APP'&&text(v.order_string,16000)||v.kind==='APPLE_STOREKIT2'&&text(v.product_id,128)&&validSupplyId(v.app_account_token))
export function isTradeRecord(v:unknown):v is TradeRecord{
 if(!obj(v)||!validSupplyId(v.id)||!validSupplyId(v.merchant_party_id)||![v.buyer_party_id,v.parent_id,v.order_id,v.created_by].every(nullableId)||!integer(v.object_version,1,100000)||!hash(v.content_sha256)||!obj(v.data))return false
 const d=v.data,s=String(v.current_status)
 switch(v.kind){
 case 'SPEC':return ['IN_REVIEW','PUBLISHED','REJECTED'].includes(s)&&spec(d)
 case 'QUOTE':return ['IN_REVIEW','APPROVED','REJECTED','ACCEPTED'].includes(s)&&quote(d)
 case 'ORDER':return ['OPEN','PARTIALLY_PAID','PAID','PARTIALLY_REFUNDED','REFUNDED','PAYMENT_REVIEW_REQUIRED','CANCELLED'].includes(s)&&quote(d.quote)&&snapshotContent(d.contract)&&validSupplyId(d.buyer_acknowledged_by)&&obj(d.financial)&&['received_minor','refunded_minor','net_minor'].every(k=>integer((d.financial as Record<string,unknown>)[k],0))&&Number(d.financial.net_minor)===Number(d.financial.received_minor)-Number(d.financial.refunded_minor)&&(d.cancel_reason===undefined||text(d.cancel_reason))
 case 'PAYMENT':return ['CREATED','SUBMITTING','PENDING','UNKNOWN','CLOSED','SUCCEEDED','REFUNDED','REVIEW_REQUIRED'].includes(s)&&channel(d)&&text(d.config_revision,128)&&allocations(d.allocations)&&text(d.installment_key,128)&&nullableText(d.apple_product_id)&&text(d.title,200)&&integer(d.payment_window_minutes,1,10080)&&instant(d.expires_at)&&checkout(d.checkout)&&nullableText(d.transaction_id)&&(d.proof===null||proof(d.proof))&&(d.allocations as Allocation[]).reduce((sum,a)=>sum+a.amount_minor,0)===d.amount_minor
 case 'REFUND':return ['REQUESTED','APPROVED','REJECTED','SUBMITTING','PENDING','UNKNOWN','AWAITING_APPLE_REQUEST','SUCCEEDED','FAILED'].includes(s)&&channel(d)&&validSupplyId(d.payment_id)&&allocations(d.allocations)&&text(d.transaction_id,128)&&nullableText(d.apple_product_id)&&text(d.reason)&&review(d.review)&&(d.proof===undefined||proof(d.proof))&&(d.allocations as Allocation[]).reduce((sum,a)=>sum+a.amount_minor,0)===d.amount_minor
 case 'LEGACY':return ['NEEDS_REVIEW','VERIFIED_REFERENCE_ONLY','REJECTED'].includes(s)&&text(d.source_system,128)&&text(d.source_order_id,128)&&rows(d.original_lines,x=>obj(x)&&text(x.line_id,128)&&integer(x.amount_minor,0)&&['REPORTED_PAID','REPORTED_UNPAID','UNKNOWN'].includes(String(x.reported_status)))&&unique(d.original_lines as unknown[],x=>(x as {line_id:string}).line_id)&&text(d.original_terms,8000)&&validSupplyId(d.evidence_asset_id)&&d.currency==='CNY'&&d.payment_verified===false&&review(d.review)
 default:return false
 }
}
const options=(i:SupplyIdentity,signal?:AbortSignal)=>({token:i.token,actingParty:i.partyId,cache:'no-store' as const,signal})
const visible=(r:TradeRecord,i:SupplyIdentity)=>!i.partyId||r.merchant_party_id===i.partyId||r.buyer_party_id===i.partyId
function checked<T>(r:ApiResult<unknown>,i:SupplyIdentity,guard:(v:unknown)=>v is T):T{if(!guard(r.data)||!r.meta?.request_id||r.meta.actor?.account_id!==i.accountId||r.meta.acting_party!==i.partyId)throw new ApiError({status:200,code:'UNEXPECTED_RESPONSE_SHAPE',message:'无法确认交易记录，请重新读取。',requestId:r.requestId});return r.data}
export async function listTrade(i:SupplyIdentity,kind:TradeKind,cursor:string|null=null,signal?:AbortSignal){const q=new URLSearchParams({kind,limit:'20'});if(cursor)q.set('cursor',cursor);return checked(await request(`/trade/records?${q}`,options(i,signal)),i,(v):v is TradePage=>obj(v)&&Array.isArray(v.items)&&v.items.length<=100&&v.items.every(r=>isTradeRecord(r)&&r.kind===kind&&visible(r,i))&&nullableId(v.next_cursor))}
export async function getTrade(i:SupplyIdentity,id:string,kind?:TradeKind,signal?:AbortSignal){return checked(await request(`/trade/records/${encodeURIComponent(id)}`,options(i,signal)),i,(v):v is TradeRecord=>isTradeRecord(v)&&v.id===id&&(!kind||v.kind===kind)&&visible(v,i))}
export async function postTrade(i:SupplyIdentity,c:TradeWrite,key:string,signal?:AbortSignal){return checked(await request(c.path,{...options(i,signal),method:'POST',body:c.body,idempotencyKey:key,ifMatch:c.version}),i,(v):v is TradeRecord=>isTradeRecord(v)&&v.kind===c.resultKind&&visible(v,i)&&(!c.targetId||v.id===c.targetId||c.resultKind==='ORDER'&&v.parent_id===c.targetId))}
export const legacyBytes=(i:SupplyIdentity,recordId:string,assetId:string,signal?:AbortSignal)=>requestBytes(`/trade/legacy-orders/${encodeURIComponent(recordId)}/evidence/${encodeURIComponent(assetId)}/content`,options(i,signal))
export const tradeTitle=(r:TradeRecord)=>r.kind==='SPEC'||r.kind==='PAYMENT'?r.data.title:r.kind==='LEGACY'?`${r.data.source_system} · ${r.data.source_order_id}`:r.kind==='ORDER'?'保存的订单与合同':r.kind==='REFUND'?'逐付款明细退款':`报价 · ${money(r.data.total_minor)}`
/** Remaining amounts subtract requested and in-flight refunds too, preventing misleading availability. */
export function refundable(payment:TradeRecord,refunds:TradeRecord[]):Allocation[]{if(payment.kind!=='PAYMENT'||payment.current_status!=='SUCCEEDED')return [];return payment.data.allocations.map(a=>({...a,amount_minor:Math.max(0,a.amount_minor-refunds.filter(r=>r.kind==='REFUND'&&r.data.payment_id===payment.id&&!['REJECTED','FAILED'].includes(r.current_status)).reduce((sum,r)=>sum+(r.kind==='REFUND'?r.data.allocations.filter(x=>x.line_id===a.line_id).reduce((s,x)=>s+x.amount_minor,0):0),0))}))}
export function validRefund(payment:TradeRecord,refunds:TradeRecord[],allocs:Allocation[]):boolean{if(payment.kind!=='PAYMENT'||payment.current_status!=='SUCCEEDED'||!allocations(allocs))return false;const remaining=refundable(payment,refunds);if(!allocs.every(a=>a.amount_minor<=(remaining.find(x=>x.line_id===a.line_id)?.amount_minor||0)))return false;return payment.data.provider!=='APPLE'||allocs.length===payment.data.allocations.length&&allocs.every(a=>a.amount_minor===payment.data.allocations.find(x=>x.line_id===a.line_id)?.amount_minor)}
