import {computed,onScopeDispose,ref,shallowRef,watch} from 'vue'
import {ApiError,asApiError,newIdempotencyKey,outcomeUnknown} from '@/api/client'
import {getNotifications,getComments,getReport,postOperations,verifyRecoveryIdentity,commentWriteMatches,type Target,type Notification,type Comment,type Report,type OperationsWrite,type WriteResult} from '@/api/modules/operations'
import type {SupplyIdentity} from '@/api/modules/supply'
import type {SupplyContext} from './useSupply'
interface Pending {command:OperationsWrite;key:string;state:'sending'|'unknown'|'refresh';checked:boolean;resultId?:string|number;done:(r:WriteResult)=>void}
export function useOperations(context:()=>SupplyContext){
 const notifications=ref<Notification[]>([]),comments=ref<Comment[]>([]),report=ref<Report|null>(null),notificationCursor=ref<number|null>(null),commentCursor=ref<string|null>(null),error=ref<ApiError|null>(null),notice=ref(''),pending=shallowRef<Pending|null>(null),writing=ref(false),reading=ref<Record<string,boolean>>({}),securityRevision=ref(0),conflictRevision=ref(0),retryAt=ref(0)
 let epoch=0,disposed=false;const tickets=new Map<string,number>(),aborts=new Map<string,AbortController>(),urls=new Set<string>()
 const busy=computed(()=>writing.value||Object.values(reading.value).some(Boolean))
 function revoke(){for(const u of urls)URL.revokeObjectURL(u);urls.clear()}
 function clear(){epoch++;for(const a of aborts.values())a.abort();aborts.clear();notifications.value=[];comments.value=[];report.value=null;notificationCursor.value=commentCursor.value=null;error.value=null;notice.value='';pending.value=null;writing.value=false;reading.value={};retryAt.value=0;revoke();securityRevision.value++}
 watch(()=>[context().token,context().accountId,context().partyId,context().revision,context().scope],clear,{flush:'sync'})
 onScopeDispose(()=>{disposed=true;clear()})
 function identity():SupplyIdentity{const c=context();if(!c.token||!c.accountId||c.partyId==='')throw new ApiError({status:400,code:'CLIENT_IDENTITY_REQUIRED',message:'请读取当前账号并选择实际办理身份。'});return {token:c.token,accountId:c.accountId,partyId:c.partyId}}
 function failure(cause:unknown){const e=asApiError(cause);if([401,403,404].includes(e.status))clear();else if(['UNEXPECTED_RESPONSE_SHAPE','PRIVATE_CONTENT_MISMATCH'].includes(e.code)){notifications.value=[];comments.value=[];report.value=null;revoke();securityRevision.value++}error.value=e;retryAt.value=e.retryAfterAt||0}
 async function read<T>(name:string,task:(i:SupplyIdentity,s:AbortSignal)=>Promise<T>,apply?:(r:T)=>void):Promise<T|null>{if(retryAt.value>Date.now())return null;const ticket=(tickets.get(name)||0)+1;tickets.set(name,ticket);aborts.get(name)?.abort();const a=new AbortController(),generation=epoch;aborts.set(name,a);const current=()=>!disposed&&generation===epoch&&tickets.get(name)===ticket;reading.value={...reading.value,[name]:true};error.value=null;try{const value=await task(identity(),a.signal);if(!current())return null;apply?.(value);return value}catch(e){if(current())failure(e);return null}finally{if(current()){reading.value={...reading.value,[name]:false};aborts.delete(name)}}}
 async function loadNotifications(unread=false,more=false){const cursor=more?notificationCursor.value:null;if(more&&cursor===null)return;return read('notifications',(i,s)=>getNotifications(i,cursor,unread,s),r=>{if(r.next_cursor!==null&&r.next_cursor===cursor)throw new ApiError({status:200,code:'UNEXPECTED_RESPONSE_SHAPE',message:'通知分页位置未更新。'});notifications.value=more?[...new Map([...notifications.value,...r.items].map(r=>[r.id,r])).values()]:r.items;notificationCursor.value=r.next_cursor})}
 async function allNotifications(i:SupplyIdentity,s:AbortSignal){const all:Notification[]=[],seen=new Set<number>();let cursor:number|null=null;do{const page=await getNotifications(i,cursor,false,s);all.push(...page.items);cursor=page.next_cursor;if(cursor!==null&&seen.has(cursor))throw new ApiError({status:200,code:'UNEXPECTED_RESPONSE_SHAPE',message:'通知分页位置重复。'});if(cursor!==null)seen.add(cursor)}while(cursor!==null);return [...new Map(all.map(r=>[r.id,r])).values()]}
 async function loadEvent(id:number){return read('event',async(i,s)=>(await allNotifications(i,s)).find(r=>r.id===id)||null,r=>{if(!r)throw new ApiError({status:404,code:'CLIENT_EVENT_NOT_AVAILABLE',message:'当前身份的通知记录中没有此事件，或原业务权限已经变化。'});notifications.value=[r]})}
 async function loadComments(t:Target,more=false){const cursor=more?commentCursor.value:null;if(more&&!cursor)return;return read('comments',(i,s)=>getComments(i,t,cursor,s),r=>{if(r.next_cursor&&r.next_cursor===cursor)throw new ApiError({status:200,code:'UNEXPECTED_RESPONSE_SHAPE',message:'留言分页位置未更新。'});comments.value=more?[...new Map([...comments.value,...r.items].map(r=>[r.id,r])).values()]:r.items;commentCursor.value=r.next_cursor})}
 async function allComments(i:SupplyIdentity,t:Target,s:AbortSignal){const all:Comment[]=[],seen=new Set<string>();let cursor:string|null=null;do{const page=await getComments(i,t,cursor,s);all.push(...page.items);cursor=page.next_cursor;if(cursor&&seen.has(cursor))throw new ApiError({status:200,code:'UNEXPECTED_RESPONSE_SHAPE',message:'留言分页位置重复。'});if(cursor)seen.add(cursor)}while(cursor);return [...new Map(all.map(r=>[r.id,r])).values()]}
 const loadReport=(id:string)=>{report.value=null;revoke();return read('report',(i,s)=>getReport(i,id,s),r=>report.value=r)}
 function apply(r:WriteResult){if('request' in r)report.value=r;else if('domain' in r)comments.value=comments.value.map(c=>c.id===r.id?r:c);else notifications.value=notifications.value.map(n=>n.id===r.id?{...n,read:true}:n)}
 function finish(p:Pending,r:WriteResult){pending.value=null;apply(r);notice.value=`${p.command.label}已保存，已核对当前服务器状态。`;p.done(r)}
 async function knownResult(p:Pending,i:SupplyIdentity,s:AbortSignal):Promise<WriteResult>{if(p.command.resultKind==='REPORT')return getReport(i,String(p.resultId),s);if(p.command.resultKind==='COMMENT'&&p.command.target){const all=await allComments(i,p.command.target,s),r=all.find(r=>r.id===p.resultId);if(r&&commentWriteMatches(r,p.command,i))return r}else if(p.command.resultKind==='READ'){const r=(await allNotifications(i,s)).find(r=>r.id===p.resultId);if(r?.read)return {id:r.id,read:true}}throw new ApiError({status:200,code:'UNEXPECTED_RESPONSE_SHAPE',message:'尚未在当前获准的实际记录中核实原操作结果，请继续读取。'})}
 async function checkPending(){const p=pending.value;if(!p||busy.value)return;const generation=epoch;if(p.resultId){const r=await read('recovery',(i,s)=>knownResult(p,i,s));if(r&&generation===epoch&&pending.value===p)finish(p,r);return}
 if(p.command.recovery==='COMMENTS'&&p.command.target){const all=await read('recovery',(i,s)=>allComments(i,p.command.target!,s));if(all&&generation===epoch&&pending.value===p){comments.value=all;p.checked=true}}
 else if(p.command.recovery==='NOTIFICATIONS'){const all=await read('recovery',(i,s)=>allNotifications(i,s));if(all&&generation===epoch&&pending.value===p){notifications.value=all;const n=all.find(r=>r.id===p.command.resultId);if(n?.read){finish(p,{id:n.id,read:true});return}p.checked=true}}
 else if(p.command.recovery==='REPORT'&&p.command.resultId){const r=await read('recovery',(i,s)=>getReport(i,String(p.command.resultId),s));if(r&&generation===epoch&&pending.value===p){report.value=r;p.checked=true}}
 else {const r=await read('recovery',(i,s)=>verifyRecoveryIdentity(i,s));if(r&&generation===epoch&&pending.value===p)p.checked=true}
 if(generation===epoch&&pending.value===p&&p.checked)notice.value=p.command.recovery==='CREATE_REPORT'?'已核对当前账号。接口没有按原请求查找新报表的目录；请使用原编号和原参数恢复以取得原任务，不能另建申请。':'已核对获准原记录；当前记录不能证明原请求未执行。请只使用原请求编号、内容及版本恢复。'}
 async function runPending(first=false){const p=pending.value;if(!p||writing.value||retryAt.value>Date.now())return;if(p.resultId){await checkPending();return}if(!first&&!p.checked)return;const generation=epoch,a=new AbortController();aborts.set('write',a);const current=()=>!disposed&&generation===epoch&&pending.value===p;writing.value=true;error.value=null;p.state='sending';p.checked=false;try{const i=identity(),r=await postOperations(i,p.command,p.key,a.signal);if(!current())return;p.resultId=r.id;p.state='refresh';const fresh=await knownResult(p,i,a.signal);if(current())finish(p,fresh)}catch(cause){if(!current())return;const e=asApiError(cause);if([401,403,404].includes(e.status)){failure(e);return}if('resultId' in e&&(typeof e.resultId==='string'||typeof e.resultId==='number'))p.resultId=e.resultId;if(e.status===412){pending.value=null;notice.value='原留言版本已变化，请读取最新记录后重新选择并确认。';if(p.command.target){const all=await allComments(identity(),p.command.target,a.signal).catch(c=>{if(generation===epoch&&!disposed)failure(c);return null});if(generation===epoch&&!disposed&&all)comments.value=all}if(generation===epoch&&!disposed)conflictRevision.value++}else if(p.resultId)p.state='refresh';else if(outcomeUnknown(e)||e.code==='IDEMPOTENCY_IN_PROGRESS')p.state='unknown';else pending.value=null;if(generation===epoch&&!disposed){error.value=e;retryAt.value=e.retryAfterAt||0}}finally{if(generation===epoch&&!disposed){writing.value=false;aborts.delete('write')}}}
 async function write(command:OperationsWrite,done:Pending['done']=()=>{}){if(pending.value||busy.value||retryAt.value>Date.now())return;pending.value={command:{...command,body:JSON.parse(JSON.stringify(command.body)),target:command.target?{...command.target}:undefined,request:command.request?{...command.request}:undefined},key:newIdempotencyKey(),state:'sending',checked:false,done};await runPending(true)}
 function objectUrl(blob:Blob){revoke();const url=URL.createObjectURL(blob);urls.add(url);return url}
 return {notifications,comments,report,notificationCursor,commentCursor,error,notice,pending,busy,writing,reading,securityRevision,conflictRevision,retryAt,read,clear,loadNotifications,loadEvent,loadComments,loadReport,allComments,write,checkPending,retry:()=>runPending(),revoke,objectUrl,canNavigate:()=>!pending.value}
}
