import { computed, onScopeDispose, ref, shallowRef, watch } from 'vue'
import { ApiError, asApiError, newIdempotencyKey, outcomeUnknown } from '@/api/client'
import { getProduction, getProductionResult, listProduction, postProduction, type ProductionKind, type ProductionRecord, type ProductionResult, type ProductionWrite } from '@/api/modules/production'
import type { SupplyContext } from './useSupply'
import type { SupplyIdentity } from '@/api/modules/supply'
interface Pending { command:ProductionWrite; key:string; state:'sending'|'unknown'|'refresh'|'blocked'; checked:boolean; resultId?:string; done:(r:ProductionResult)=>void }
export function useProduction(context:()=>SupplyContext){
 const rows=ref<ProductionRecord[]>([]),detail=ref<ProductionRecord|null>(null),nextCursor=ref<string|null>(null),error=ref<ApiError|null>(null),notice=ref(''),pending=shallowRef<Pending|null>(null),writing=ref(false),reading=ref<Record<string,boolean>>({}),securityRevision=ref(0),conflictRevision=ref(0),retryAt=ref(0)
 let epoch=0,disposed=false;const tickets=new Map<string,number>(),aborts=new Map<string,AbortController>(),urls=new Set<string>()
 const busy=computed(()=>writing.value||Object.values(reading.value).some(Boolean))
 function revoke(){for(const u of urls)URL.revokeObjectURL(u);urls.clear()}
 function clear(){epoch++;for(const a of aborts.values())a.abort();aborts.clear();rows.value=[];detail.value=null;nextCursor.value=null;pending.value=null;writing.value=false;reading.value={};error.value=null;notice.value='';retryAt.value=0;revoke();securityRevision.value++}
 watch(()=>[context().token,context().accountId,context().partyId,context().revision,context().scope],clear,{flush:'sync'})
 onScopeDispose(()=>{disposed=true;clear()})
 function identity():SupplyIdentity{const c=context();if(!c.token||!c.accountId||c.partyId==='')throw new ApiError({status:400,code:'CLIENT_IDENTITY_REQUIRED',message:'请读取账号并选择实际办理身份。'});return {token:c.token,accountId:c.accountId,partyId:c.partyId}}
 function failure(cause:unknown){const e=asApiError(cause);if([401,403,404].includes(e.status))clear();error.value=e;retryAt.value=e.retryAfterAt||0}
 function apply(r:ProductionRecord){if(detail.value?.id===r.id)detail.value=r;rows.value=rows.value.map(x=>x.id===r.id?r:x)}
 async function read<T>(name:string,task:(i:SupplyIdentity,s:AbortSignal)=>Promise<T>,applyValue?:(v:T)=>void):Promise<T|null>{if(retryAt.value>Date.now())return null;const ticket=(tickets.get(name)||0)+1;tickets.set(name,ticket);aborts.get(name)?.abort();const a=new AbortController(),generation=epoch;aborts.set(name,a);const current=()=>!disposed&&generation===epoch&&tickets.get(name)===ticket;reading.value={...reading.value,[name]:true};error.value=null;try{const value=await task(identity(),a.signal);if(!current())return null;applyValue?.(value);return value}catch(e){if(current())failure(e);return null}finally{if(current()){reading.value={...reading.value,[name]:false};aborts.delete(name)}}}
 async function loadList(projectId?:string,kind?:Exclude<ProductionKind,'PROJECT'>,more=false){const cursor=more?nextCursor.value:null;if(more&&!cursor)return;if(!more){rows.value=[];nextCursor.value=null}return read('list',(i,s)=>listProduction(i,projectId,kind,cursor,s),page=>{if(page.next_cursor&&page.next_cursor===cursor)throw new ApiError({status:200,code:'UNEXPECTED_RESPONSE_SHAPE',message:'分页位置未更新，请重新读取。'});rows.value=more?[...new Map([...rows.value,...page.items].map(x=>[x.id,x])).values()]:page.items;nextCursor.value=page.next_cursor})}
 const loadRecord=(id:string,kind?:ProductionKind)=>read('detail',(i,s)=>getProduction(i,id,kind,s),r=>detail.value=r)
 async function loadAll(projectId:string,kind:Exclude<ProductionKind,'PROJECT'>){return read(`all-${kind}`,async(i,s)=>{const all:ProductionRecord[]=[],seen=new Set<string>();let cursor:string|null=null;do{const page=await listProduction(i,projectId,kind,cursor,s);all.push(...page.items);cursor=page.next_cursor;if(cursor&&seen.has(cursor))throw new ApiError({status:200,code:'UNEXPECTED_RESPONSE_SHAPE',message:'分页位置重复，请重新读取。'});if(cursor)seen.add(cursor)}while(cursor);return [...new Map(all.map(r=>[r.id,r])).values()]})}
 function finish(p:Pending,r:ProductionResult){pending.value=null;if('kind' in r)apply(r);notice.value=`${p.command.label}已保存，已核对当前服务器状态。`;p.done(r)}
 async function checkPending(){const p=pending.value;if(!p||busy.value)return;const generation=epoch;if(p.resultId){const r=await read('recovery',(i,s)=>getProductionResult(i,p.resultId!,p.command.resultKind,s));if(r&&epoch===generation&&pending.value===p)finish(p,r);return}if(p.command.targetId){const r=await read('recovery',(i,s)=>getProduction(i,p.command.targetId!,undefined,s));if(r&&epoch===generation&&pending.value===p){apply(r);p.checked=true}}else if(p.command.resultKind!=='ASSET'){const page=await read('recovery',(i,s)=>listProduction(i,p.command.projectId,p.command.projectId?p.command.resultKind as Exclude<ProductionKind,'PROJECT'>:undefined,null,s));if(page&&epoch===generation&&pending.value===p){p.checked=true}}else{const page=await read('recovery',(i,s)=>listProduction(i));if(page&&epoch===generation&&pending.value===p)p.checked=true}if(epoch===generation&&pending.value===p&&p.checked)notice.value='已核对现有记录；列表不能证明原请求未执行。若仍未确认，请使用原编号和原内容重试。'}
 async function runPending(first=false){const p=pending.value;if(!p||writing.value||p.state==='blocked'||retryAt.value>Date.now())return;if(p.resultId){await checkPending();return}if(!first&&!p.checked)return;const generation=epoch,a=new AbortController();aborts.set('write',a);const current=()=>!disposed&&generation===epoch&&pending.value===p;writing.value=true;error.value=null;p.state='sending';p.checked=false;try{const i=identity(),r=await postProduction(i,p.command,p.key,a.signal);if(!current())return;p.resultId=r.id;p.state='refresh';const fresh=await getProductionResult(i,r.id,p.command.resultKind,a.signal);if(current())finish(p,fresh)}catch(cause){if(!current())return;const e=asApiError(cause);if([401,403,404].includes(e.status)){failure(e);return}if(e.status===412){pending.value=null;notice.value='记录已经变化，请核对最新内容后重新选择和确认。';if(p.command.targetId){const fresh=await getProduction(identity(),p.command.targetId,undefined,a.signal).catch(c=>{if(generation===epoch&&!disposed)failure(c);return null});if(generation===epoch&&!disposed)detail.value=fresh}if(generation===epoch&&!disposed)conflictRevision.value++}else if(p.resultId)p.state='refresh';else if(e.code==='UPLOAD_RECONCILIATION_REQUIRED')p.state='blocked';else if(outcomeUnknown(e))p.state='unknown';else pending.value=null;if(generation===epoch&&!disposed){error.value=e;retryAt.value=e.retryAfterAt||0}}finally{if(generation===epoch&&!disposed){writing.value=false;aborts.delete('write')}}}
 async function write(command:ProductionWrite,done:Pending['done']=()=>{}){if(pending.value||busy.value||retryAt.value>Date.now())return;pending.value={command:{...command,body:command.body===undefined?undefined:JSON.parse(JSON.stringify(command.body)),supply:command.supply?{...command.supply,body:command.supply.body?JSON.parse(JSON.stringify(command.supply.body)):undefined}:undefined},key:newIdempotencyKey(),state:'sending',checked:false,done};await runPending(true)}
 function endBlocked(){if(pending.value?.state==='blocked'&&pending.value.checked){pending.value=null;conflictRevision.value++;notice.value='原上传已由服务器拒绝继续重放，请先核对文件记录及存储结果，再决定后续处理。'}}
 function objectUrl(blob:Blob){revoke();const url=URL.createObjectURL(blob);urls.add(url);return url}
 return {rows,detail,nextCursor,error,notice,pending,writing,reading,busy,securityRevision,conflictRevision,retryAt,clear,read,loadList,loadRecord,loadAll,write,retry:()=>runPending(),checkPending,endBlocked,objectUrl,revoke,canNavigate:()=>!pending.value}
}
