import { computed, onScopeDispose, ref, shallowRef, watch } from 'vue'
import { ApiError, asApiError, newIdempotencyKey, outcomeUnknown } from '@/api/client'
import { getTrade, legacyBytes, listTrade, postTrade, type TradeKind, type TradeRecord, type TradeWrite } from '@/api/modules/trade'
import type { SupplyContext } from './useSupply'
import type { SupplyIdentity } from '@/api/modules/supply'
interface Pending { command:TradeWrite; key:string; state:'sending'|'unknown'|'refresh'; checked:boolean; resultId?:string; done:(r:TradeRecord)=>void }
export function useTrade(context:()=>SupplyContext){
 const rows=ref<TradeRecord[]>([]),detail=ref<TradeRecord|null>(null),related=ref<TradeRecord[]>([]),nextCursor=ref<string|null>(null),error=ref<ApiError|null>(null),notice=ref(''),pending=shallowRef<Pending|null>(null),writing=ref(false),reading=ref<Record<string,boolean>>({}),securityRevision=ref(0),conflictRevision=ref(0),retryAt=ref(0)
 let epoch=0,disposed=false;const tickets=new Map<string,number>(),aborts=new Map<string,AbortController>(),urls=new Set<string>()
 const busy=computed(()=>writing.value||Object.values(reading.value).some(Boolean))
 function clear(){epoch++;for(const a of aborts.values())a.abort();aborts.clear();rows.value=[];detail.value=null;related.value=[];nextCursor.value=null;pending.value=null;writing.value=false;reading.value={};error.value=null;notice.value='';retryAt.value=0;for(const u of urls)URL.revokeObjectURL(u);urls.clear();securityRevision.value++}
 watch(()=>[context().token,context().accountId,context().partyId,context().revision,context().scope],clear,{flush:'sync'})
 onScopeDispose(()=>{disposed=true;clear()})
 function identity():SupplyIdentity{const c=context();if(!c.token||!c.accountId||c.partyId==='')throw new ApiError({status:400,code:'CLIENT_IDENTITY_REQUIRED',message:'请先读取账号并选择办理身份。'});return {token:c.token,accountId:c.accountId,partyId:c.partyId}}
 function failure(cause:unknown){const e=asApiError(cause);if([401,403,404].includes(e.status))clear();error.value=e;retryAt.value=e.retryAfterAt||0}
 function apply(r:TradeRecord){detail.value=r;rows.value=rows.value.map(x=>x.id===r.id?r:x);related.value=related.value.map(x=>x.id===r.id?r:x)}
 async function read<T>(name:string,task:(i:SupplyIdentity,s:AbortSignal)=>Promise<T>,applyValue?:(v:T)=>void):Promise<T|null>{if(retryAt.value>Date.now())return null;const ticket=(tickets.get(name)||0)+1;tickets.set(name,ticket);aborts.get(name)?.abort();const a=new AbortController(),generation=epoch;aborts.set(name,a);const current=()=>!disposed&&generation===epoch&&tickets.get(name)===ticket;reading.value={...reading.value,[name]:true};error.value=null;try{const value=await task(identity(),a.signal);if(!current())return null;applyValue?.(value);return value}catch(e){if(current())failure(e);return null}finally{if(current()){reading.value={...reading.value,[name]:false};aborts.delete(name)}}}
 async function loadList(kind:TradeKind,more=false){const cursor=more?nextCursor.value:null;if(more&&!cursor)return;if(!more){rows.value=[];nextCursor.value=null}return read('list',(i,s)=>listTrade(i,kind,cursor,s),page=>{if(page.next_cursor&&page.next_cursor===cursor)throw new ApiError({status:200,code:'UNEXPECTED_RESPONSE_SHAPE',message:'分页位置未更新，请重新读取。'});rows.value=more?[...new Map([...rows.value,...page.items].map(r=>[r.id,r])).values()]:page.items;nextCursor.value=page.next_cursor})}
 function loadRecord(id:string,kind?:TradeKind){detail.value=null;return read('detail',(i,s)=>getTrade(i,id,kind,s),apply)}
 function loadAll(kind:TradeKind){return read('all-'+kind,async(i,s)=>{const items:TradeRecord[]=[],seen=new Set<string>();let cursor:string|null=null;do{const page=await listTrade(i,kind,cursor,s);items.push(...page.items);cursor=page.next_cursor;if(cursor&&seen.has(cursor))throw new ApiError({status:200,code:'UNEXPECTED_RESPONSE_SHAPE',message:'列表没有前进，请重新读取。'});if(cursor)seen.add(cursor)}while(cursor);return [...new Map(items.map(r=>[r.id,r])).values()]})}
 function finish(p:Pending,r:TradeRecord){pending.value=null;apply(r);notice.value=`${p.command.label}已处理，当前状态已重新读取。`;p.done(r)}
 /** An uncertain POST is never replaced. GET first, then a deliberate replay of the identical request. */
 async function checkPending(){const p=pending.value;if(!p||busy.value)return;const generation=epoch;let r:TradeRecord|null=null;if(p.resultId){r=await read('recovery',(i,s)=>getTrade(i,p.resultId!,p.command.resultKind,s));if(r&&epoch===generation&&pending.value===p)finish(p,r);return}if(p.command.targetId){r=await read('recovery',(i,s)=>getTrade(i,p.command.targetId!,undefined,s));if(r&&epoch===generation&&pending.value===p){apply(r);if(p.command.resultKind==='ORDER'&&r.kind==='QUOTE'&&r.data.order_id){p.resultId=r.data.order_id;await checkPending();return}p.checked=true}}else{const page=await read('recovery',(i,s)=>listTrade(i,p.command.resultKind,null,s));if(page&&epoch===generation&&pending.value===p){rows.value=page.items;nextCursor.value=page.next_cursor;p.checked=true}}if(epoch===generation&&pending.value===p&&p.checked)notice.value='已核对当前记录。仍无法确认原提交时，请使用原请求编号重试；不会另建相同请求。'}
 async function runPending(first=false){const p=pending.value;if(!p||writing.value||retryAt.value>Date.now()||!first&&!p.checked)return;if(p.resultId){await checkPending();return}const generation=epoch,a=new AbortController();aborts.set('write',a);const current=()=>!disposed&&generation===epoch&&pending.value===p;writing.value=true;error.value=null;p.state='sending';p.checked=false;try{const i=identity(),r=await postTrade(i,p.command,p.key,a.signal);if(!current())return;p.resultId=r.id;p.state='refresh';const fresh=await getTrade(i,r.id,p.command.resultKind,a.signal);if(!current())return;finish(p,fresh)}catch(cause){if(!current())return;const e=asApiError(cause);if([401,403,404].includes(e.status)){failure(e);return}if(e.status===412){pending.value=null;conflictRevision.value++;notice.value='记录已变化，请核对最新内容后重新确认。';if(p.command.targetId){const fresh=await getTrade(identity(),p.command.targetId,undefined,a.signal).catch(c=>{if(generation===epoch&&!disposed)failure(c);return null});if(generation===epoch&&!disposed){if(fresh)apply(fresh);else detail.value=null}}}else if(p.resultId)p.state='refresh';else if(outcomeUnknown(e))p.state='unknown';else pending.value=null;if(generation===epoch&&!disposed){error.value=e;retryAt.value=e.retryAfterAt||0}}finally{if(generation===epoch&&!disposed){writing.value=false;aborts.delete('write')}}}
 async function write(command:TradeWrite,done:Pending['done']=()=>{}){if(pending.value||busy.value||retryAt.value>Date.now())return;pending.value={command:{...command,body:JSON.parse(JSON.stringify(command.body))},key:newIdempotencyKey(),state:'sending',checked:false,done};await runPending(true)}
 async function downloadLegacy(recordId:string,assetId:string){await read('download',(i,s)=>legacyBytes(i,recordId,assetId,s),bytes=>{const u=URL.createObjectURL(bytes);urls.add(u);const a=document.createElement('a');a.href=u;a.download=`历史材料-${assetId}.bin`;a.click();window.setTimeout(()=>{URL.revokeObjectURL(u);urls.delete(u)},0)})}
 return {rows,detail,related,nextCursor,error,notice,pending,writing,reading,busy,securityRevision,conflictRevision,retryAt,clear,read,loadList,loadRecord,loadAll,write,retry:()=>runPending(),checkPending,downloadLegacy,canNavigate:()=>!pending.value}
}
