 'use strict';
const {id,error}=require('../party/policy'),{digest}=require('../governance/content');
const {coversConsent}=require('../works/consent-policy');
const one=async(tx,sql,args=[])=>(await tx.execute(sql,args))[0][0];
const parsed=x=>typeof x==='string'?JSON.parse(x):x;
function checked(row){if(!row)throw error('GIG_NOT_FOUND',404);const data=parsed(row.data_json);if(digest(data)!==row.data_sha256)throw error('STORED_CONTENT_MISMATCH',503);return {...row,data};}
function dto(row){const r=checked(row);return {id:r.id,kind:r.kind,owner_party_id:r.owner_party_id,counterparty_id:r.counterparty_id,parent_id:r.parent_id,created_by:r.created_by,current_status:r.current_status,object_version:r.object_version,content_sha256:r.data_sha256,data:r.data};}
async function load(tx,key,kind,lock='FOR UPDATE'){const r=dto(await one(tx,'SELECT * FROM gig_records WHERE id=? '+lock,[id(key)]));if(kind&&r.kind!==kind)throw error('GIG_NOT_FOUND',404);return r;}
async function supply(tx,key,kind,party){const r=checked(await one(tx,'SELECT * FROM supply_records WHERE id=? FOR SHARE',[id(key)]));if(r.kind!==kind||party&&r.owner_party_id!==party)throw error('SUPPLY_EVIDENCE_MISMATCH',409);return r;}
async function activeParty(tx,party){const r=await one(tx,'SELECT * FROM parties WHERE id=? FOR SHARE',[id(party)]);if(!r||['CLOSED','SUSPENDED'].includes(r.current_status))throw error('PARTY_NOT_ACTIVE',409);return r;}
async function liveRule(tx,key){const r=await load(tx,key,'RULE','FOR SHARE');if(r.current_status!=='EFFECTIVE')throw error('GIG_RULE_NOT_EFFECTIVE',409);return r;}
async function eligible(tx,g,o,{newContract=true}={}){if(g.current_status!=='PUBLISHED')throw error('GIG_NOT_PUBLISHED',409);await activeParty(tx,g.owner_party_id);await activeParty(tx,o.owner_party_id);if(newContract&&o.data.relation){const rel=await load(tx,o.data.relation.id,'RELATION','FOR SHARE'),now=new Date().toISOString();if(rel.current_status!=='ACTIVE'||rel.object_version!==o.data.relation.version||rel.data.valid_from>now||rel.data.valid_until<=now)throw error('RELATION_NOT_APPLICABLE',409);await activeParty(tx,rel.owner_party_id);if(!await one(tx,"SELECT party_id FROM party_capabilities WHERE party_id=? AND code='MCN' AND current_status='ACTIVE' FOR SHARE",[rel.owner_party_id]))throw error('MCN_CAPABILITY_REQUIRED',409);}if(newContract)await liveRule(tx,g.data.rule_id);const now=new Date().toISOString();if(g.data.scope.valid_until<=now)throw error('GIG_EXPIRED',409);const avatar=await supply(tx,o.data.avatar_id,'AVATAR',o.owner_party_id);if(avatar.current_status!=='RECORDED')throw error('AVATAR_NOT_ACTIVE',409);const consent=await supply(tx,o.data.consent_id,'CONSENT');if(consent.data.consent.avatar_id!==avatar.id||!consent.data.consent.features.every(feature=>coversConsent(consent,{feature,purpose:'COMMERCIAL',territory:g.data.scope.territory},now))||consent.data.consent.valid_until<g.data.scope.valid_until)throw error('COMMERCIAL_CONSENT_REQUIRED',409);}
async function quoteContext(tx,{offer_id,buyer,merchant,lines}){const hint=await load(tx,offer_id,'OFFER','');const g=await load(tx,hint.parent_id,'GIG');const o=await load(tx,offer_id,'OFFER');if(o.current_status!=='ACCEPTED'||o.owner_party_id!==merchant||g.owner_party_id!==buyer)throw error('COMMERCIAL_AGREEMENT_MISMATCH',409);await eligible(tx,g,o);if(lines.length!==1||lines[0].spec_id!==o.data.spec_id||lines[0].quantity!==1||lines[0].provider_party_id!==merchant)throw error('COMMERCIAL_LINES_MISMATCH',409);return {ranking_opt_in:o.data.ranking_opt_in,offer_id:o.id,offer_sha256:o.content_sha256,gig_id:g.id,scope:g.data.scope,category:g.data.category,terms:o.data.terms,commission:o.data.commission,relation:o.data.relation,avatar_id:o.data.avatar_id,consent_id:o.data.consent_id,rule_id:g.data.rule_id};}
async function bindOrder(tx,order){const c=order.data.quote.commercial;if(!c)return;const actual=await quoteContext(tx,{offer_id:c.offer_id,buyer:order.buyer_party_id,merchant:order.merchant_party_id,lines:order.data.quote.lines});if(digest(c)!==digest(actual))throw error('COMMERCIAL_AGREEMENT_CHANGED',409);try{await tx.execute('INSERT INTO gig_orders(order_id,offer_id) VALUES (?,?)',[order.id,c.offer_id]);}catch(e){if(e.code==='ER_DUP_ENTRY')throw error('COMMERCIAL_ORDER_EXISTS',409);throw e;}}
async function checkOrder(tx,order){const c=order.data.quote.commercial;if(!c)return;const g=await load(tx,c.gig_id,'GIG','FOR SHARE');await eligible(tx,g,{owner_party_id:order.merchant_party_id,data:c},{newContract:false});}
module.exports={checkOrder,one,parsed,checked,dto,load,supply,activeParty,liveRule,eligible,quoteContext,bindOrder};
