 'use strict';
const {shape,id,label,ref,error}=require('../party/policy');
const {copy,amount,instant}=require('../trade/policy');
function commission(v){shape(v,['platform_bps','mcn_bps']);for(const n of Object.values(v))if(!Number.isInteger(n)||n<0||n>10000)throw error('INVALID_COMMISSION',400);if(v.mcn_bps>v.platform_bps)throw error('MCN_EXCEEDS_PLATFORM',400);return copy(v);}
function split(net,v){amount(net,true);commission(v);const fee=Number(BigInt(net)*BigInt(v.platform_bps)/10000n),mcn=Number(BigInt(net)*BigInt(v.mcn_bps)/10000n);return {net_minor:net,supplier_minor:net-fee,platform_minor:fee-mcn,mcn_minor:mcn};}
function rules(v){shape(v,['version','categories','ranking','terms']);ref(v.version);label(v.terms,8000);if(!Array.isArray(v.categories)||!v.categories.length||v.categories.length>100)throw error('INVALID_CATEGORIES',400);const seen=new Set();for(const c of v.categories){shape(c,['code','allowed','required_proofs']);ref(c.code);if(seen.has(c.code)||typeof c.allowed!=='boolean'||!Array.isArray(c.required_proofs)||c.required_proofs.length>20)throw error('INVALID_CATEGORIES',400);seen.add(c.code);c.required_proofs.forEach(x=>ref(x));}shape(v.ranking,['window_days','newcomer_days','minimum_orders','order_weight','net_minor_weight','newcomer_bonus']);for(const x of Object.values(v.ranking))if(!Number.isSafeInteger(x)||x<0||x>100000)throw error('INVALID_RANKING_RULE',400);if(v.ranking.window_days<1||v.ranking.window_days>366||v.ranking.minimum_orders<1)throw error('INVALID_RANKING_RULE',400);return copy(v);}
function scope(v){shape(v,['purpose','territory','valid_until']);if(v.purpose!=='COMMERCIAL')throw error('COMMERCIAL_SCOPE_REQUIRED',400);ref(v.territory);instant(v.valid_until);return copy(v);}
function rank(facts,config,asOf){const end=Date.parse(asOf),start=end-config.window_days*86400000,previous=start-config.window_days*86400000,map=new Map();for(const f of facts){if(f.environment!=='PRODUCTION'||f.net_minor<=0||f.at>=end||f.at<previous)continue;const k=f.party_id+'|'+f.territory;let x=map.get(k);if(!x){x={party_id:f.party_id,territory:f.territory,current:0,previous:0,net:0,first:f.first_at};map.set(k,x);}if(f.at>=start){x.current++;x.net+=f.net_minor;}else x.previous++;}const result=[];for(const x of map.values()){if(x.current<config.minimum_orders)continue;const heat=BigInt(x.current)*BigInt(config.order_weight)+BigInt(x.net)*BigInt(config.net_minor_weight);const emerging=BigInt(x.current-x.previous)*BigInt(config.order_weight)+(x.first>=end-config.newcomer_days*86400000?BigInt(config.newcomer_bonus):0n);result.push({...x,heat:heat.toString(),emerging:emerging.toString()});}const sort=field=>(a,b)=>BigInt(a[field])===BigInt(b[field])?(a.party_id+'|'+a.territory).localeCompare(b.party_id+'|'+b.territory):BigInt(a[field])>BigInt(b[field])?-1:1;return {hot:[...result].sort(sort('heat')),emerging:[...result].sort(sort('emerging')),regional:[...result].sort((a,b)=>a.territory.localeCompare(b.territory)||sort('heat')(a,b))};}
module.exports={copy,commission,split,rules,scope,rank};
