'use strict';
const {randomUUID}=require('node:crypto');
const {shape,id,ref,label,version,error}=require('../party/policy');
const {digest}=require('../governance/content');
const {authorizeOperator}=require('../governance/operator-access');
const policy=require('./policy'),{one,parsed,checked,dto,load,supply,activeParty,liveRule,eligible}=require('./context');
function createGigsRepository(db,{resolvePrincipal=async()=>null}={}){
 async function actor(tx,ctx){const p=await resolvePrincipal(ctx);if(!p)throw error('AUTHENTICATION_REQUIRED',401);const a=await one(tx,'SELECT * FROM identity_accounts WHERE subject_ref=? FOR SHARE',[ref(p.subject_ref)]);if(!a||a.current_status!=='ACTIVE')throw error('ACCOUNT_NOT_ACTIVE');return {...a,request_id:ref(p.request_id||randomUUID())};}
 async function owner(tx,a,party){await activeParty(tx,party);const m=await one(tx,'SELECT * FROM party_memberships WHERE party_id=? AND account_id=? FOR SHARE',[id(party),a.id]);if(!m||m.current_status!=='ACTIVE'||m.role_code!=='OWNER')throw error('GIG_PARTY_FORBIDDEN');}
 async function operator(tx,a,r,independent=false){if(!await authorizeOperator(tx,{account_id:a.id,action:'GIG_REVIEW'}))throw error('GIG_REVIEW_FORBIDDEN');if(independent&&r&&(r.created_by===a.id||await one(tx,"SELECT id FROM party_memberships WHERE account_id=? AND current_status='ACTIVE' AND party_id IN (?,?,?)",[a.id,r.owner_party_id,r.counterparty_id,r.data.relation?.mcn_party_id||null])))throw error('SELF_REVIEW_FORBIDDEN');}
 async function access(tx,a,r,party){if(!party){await operator(tx,a,r);return;}await owner(tx,a,party);if(![r.owner_party_id,r.counterparty_id,r.data.relation?.mcn_party_id].includes(party))throw error('GIG_NOT_FOUND',404);}
 async function audit(tx,a,r,event){const eventId=randomUUID();await tx.execute('INSERT INTO gig_audit(id,record_id,actor_account_id,event_code,object_version,data_sha256,request_id) VALUES (?,?,?,?,?,?,?)',[eventId,r.id,a.id,event,r.object_version,digest(r.data),a.request_id]);await require('../operations/events').publishEvent(tx,{domain:'GIGS',record_id:r.id,event_id:eventId,event_code:event,object_version:r.object_version,actor_account_id:a.id});}
 async function insert(tx,a,kind,ownerId,counter,parent,status,data){const r={id:randomUUID(),kind,owner_party_id:ownerId,counterparty_id:counter,parent_id:parent,created_by:a.id,current_status:status,object_version:1,content_sha256:digest(data),data};await tx.execute('INSERT INTO gig_records(id,kind,owner_party_id,counterparty_id,parent_id,created_by,current_status,data_json,data_sha256) VALUES (?,?,?,?,?,?,?,?,?)',[r.id,kind,ownerId,counter,parent,a.id,status,JSON.stringify(data),r.content_sha256]);await audit(tx,a,r,kind+'_CREATED');return r;}
 async function save(tx,a,r,status,data,event){const n={...r,current_status:status,object_version:r.object_version+1,content_sha256:digest(data),data};await tx.execute('UPDATE gig_records SET current_status=?,object_version=?,data_json=?,data_sha256=? WHERE id=?',[status,n.object_version,JSON.stringify(data),n.content_sha256,r.id]);await audit(tx,a,n,event);return n;}
 async function notice(tx,r,event,parties){for(const p of new Set(parties.filter(Boolean)))await tx.execute('INSERT IGNORE INTO gig_notifications(id,party_id,record_id,event_code) VALUES (?,?,?,?)',[randomUUID(),p,r.id,event]);}
 async function command(tx,a,op,i,fn){const k=digest([a.id,op,ref(i.operation_key)]),hash=digest(i);try{await tx.execute('INSERT INTO gig_commands(id,fingerprint) VALUES (?,?)',[k,hash]);}catch(e){if(e.code!=='ER_DUP_ENTRY')throw e;const old=await one(tx,'SELECT * FROM gig_commands WHERE id=?',[k]);if(old.fingerprint!==hash)throw error('IDEMPOTENCY_CONFLICT',409);if(!old.result_id)throw error('IDEMPOTENCY_IN_PROGRESS',409);return load(tx,old.result_id,null,'FOR SHARE');}const r=await fn();await tx.execute('UPDATE gig_commands SET result_id=? WHERE id=?',[r.id,k]);return r;}
 const match=(r,v)=>{if(r.object_version!==version(v))throw error('VERSION_CONFLICT',412);};
 async function evidence(tx,ids,party){if(!Array.isArray(ids)||!ids.length||ids.length>30)throw error('EVIDENCE_REQUIRED',400);for(const key of ids){const r=await one(tx,'SELECT * FROM supply_assets WHERE id=? AND owner_party_id=? FOR SHARE',[id(key),party]);if(!r||r.current_status!=='READY'||!['RIGHTS_EVIDENCE','REVIEW_EVIDENCE','CONSENT_EVIDENCE'].includes(r.purpose))throw error('EVIDENCE_NOT_READY',409);}}
 async function mutate(ctx,input,op,auth,fn){const i=policy.copy(input);return db.withTransaction(async tx=>{const a=await actor(tx,ctx),hint=await load(tx,i.record_id,null,'');if(hint.kind==='OFFER')await load(tx,hint.parent_id,'GIG');if(hint.kind==='RELATION')await one(tx,'SELECT id FROM parties WHERE id=? FOR UPDATE',[hint.counterparty_id]);const r=await load(tx,i.record_id);await auth(tx,a,r,i);return command(tx,a,op,i,async()=>{match(r,i.expected_version);return fn(tx,a,r,i);});});}
 const self=async(tx,a,r,i)=>{await owner(tx,a,i.party_id);if(r.owner_party_id!==i.party_id)throw error('GIG_PARTY_FORBIDDEN');};
 const api={
 async relationParties(ctx,{record_id,party_id}){return db.withTransaction(async tx=>{
  if(!party_id)throw error('ACTING_PARTY_REQUIRED',400);
  const a=await actor(tx,ctx),r=await load(tx,record_id,'RELATION','FOR SHARE');
  await access(tx,a,r,party_id);
  const parties=[];
  for(const party of [r.owner_party_id,r.counterparty_id]){
   const row=await one(tx,'SELECT id,display_name FROM parties WHERE id=? FOR SHARE',[party]);
   parties.push({party_id:party,display_name:row?.display_name||null});
  }
  return {record_id:r.id,source:'CURRENT_DISPLAY_NAME',parties};
 });},
 async read(ctx,{record_id,party_id}){return db.withTransaction(async tx=>{const a=await actor(tx,ctx),r=await load(tx,record_id,null,'FOR SHARE');await access(tx,a,r,party_id);return r;});},
 async list(ctx,{party_id,kind,after='',limit=20}){if(!['RULE','RELATION','GIG','OFFER','COMMISSION','RANKING'].includes(kind)||!Number.isInteger(limit)||limit<1||limit>100)throw error('INVALID_LIST',400);if(after)id(after);return db.withTransaction(async tx=>{const a=await actor(tx,ctx);if(party_id)await owner(tx,a,party_id);else await operator(tx,a);const [rows]=await tx.execute('SELECT * FROM gig_records WHERE kind=? AND id>? '+(party_id?"AND (owner_party_id=? OR counterparty_id=? OR JSON_UNQUOTE(JSON_EXTRACT(data_json,'$.relation.mcn_party_id'))=?) ":'')+'ORDER BY id LIMIT ?',[kind,after,...(party_id?[party_id,party_id,party_id]:[]),limit+1]);return {items:rows.slice(0,limit).map(dto),next_cursor:rows.length>limit?rows[limit-1].id:null};});},
 async createRule(ctx,i){shape(i,['rule','operation_key']);const rule=policy.rules(i.rule);return db.withTransaction(async tx=>{const a=await actor(tx,ctx);await operator(tx,a);return command(tx,a,'RULE',i,()=>insert(tx,a,'RULE',null,null,null,'IN_REVIEW',{rule,review:null}));});},
 async review(ctx,i){shape(i,['record_id','expected_version','decision','reason','checks','operation_key']);if(!['APPROVED','REJECTED'].includes(i.decision))throw error('INVALID_REVIEW',400);label(i.reason,2000);return mutate(ctx,i,'REVIEW',(tx,a,r)=>operator(tx,a,r,true),async(tx,a,r)=>{if(!['RULE','GIG','OFFER'].includes(r.kind)||r.current_status!=='IN_REVIEW')throw error('REVIEW_NOT_PENDING',409);if(i.decision==='APPROVED'&&r.kind!=='RULE'){shape(i.checks,['identity_verified','authority_verified','materials_reviewed','content_reviewed','marking_reviewed']);if(Object.values(i.checks).length!==5||Object.values(i.checks).some(v=>v!==true))throw error('MANUAL_REVIEW_REQUIRED',400);if(r.kind==='GIG')await liveRule(tx,r.data.rule_id);else await eligible(tx,await load(tx,r.parent_id,'GIG'),r);}else if(i.checks!==null)throw error('INVALID_REVIEW',400);return save(tx,a,r,i.decision==='REJECTED'?'REJECTED':{RULE:'EFFECTIVE',GIG:'PUBLISHED',OFFER:'APPROVED'}[r.kind],{...r.data,review:{decision:i.decision,reason:i.reason,checks:i.checks,account_id:a.id,method:'EXTERNAL_MANUAL_REVIEW'}},'INDEPENDENT_REVIEW');});},
 async retireRule(ctx,i){shape(i,['record_id','expected_version','reason','operation_key']);label(i.reason,2000);return mutate(ctx,i,'RETIRE_RULE',(tx,a,r)=>operator(tx,a,r,true),async(tx,a,r)=>{if(r.kind!=='RULE'||r.current_status!=='EFFECTIVE')throw error('GIG_RULE_NOT_EFFECTIVE',409);return save(tx,a,r,'RETIRED',{...r.data,retirement:{reason:i.reason,account_id:a.id}},'RULE_RETIRED');});},
 async relation(ctx,i){shape(i,['party_id','artist_party_id','scope','valid_from','valid_until','exclusive','terms','commission','evidence_asset_ids','operation_key']);id(i.artist_party_id);if(i.artist_party_id===i.party_id||typeof i.exclusive!=='boolean'||i.scope!=='COMMERCIAL')throw error('INVALID_RELATION',400);require('../trade/policy').instant(i.valid_from);require('../trade/policy').instant(i.valid_until);if(i.valid_from>=i.valid_until)throw error('INVALID_RELATION_PERIOD',400);label(i.terms,8000);const commission=policy.commission(i.commission);return db.withTransaction(async tx=>{const a=await actor(tx,ctx);await owner(tx,a,i.party_id);await activeParty(tx,i.artist_party_id);const cap=await one(tx,"SELECT * FROM party_capabilities WHERE party_id=? AND code='MCN' AND current_status='ACTIVE'",[i.party_id]);if(!cap)throw error('MCN_CAPABILITY_REQUIRED',409);await evidence(tx,i.evidence_asset_ids,i.party_id);return command(tx,a,'RELATION',i,()=>insert(tx,a,'RELATION',i.party_id,i.artist_party_id,null,'INVITED',{scope:i.scope,valid_from:i.valid_from,valid_until:i.valid_until,exclusive:i.exclusive,terms:i.terms,commission,evidence_asset_ids:i.evidence_asset_ids,accepted_by:null,ended_reason:null}));});},
 async relationDecision(ctx,i){shape(i,['record_id','party_id','expected_version','decision','reason','operation_key']);label(i.reason,2000);return mutate(ctx,i,'RELATION_DECISION',async(tx,a,r)=>{if(r.kind!=='RELATION')throw error('GIG_NOT_FOUND',404);await access(tx,a,r,i.party_id);},async(tx,a,r)=>{if(i.decision==='END'){if(!['ACTIVE','INVITED'].includes(r.current_status))throw error('RELATION_NOT_ACTIVE',409);const n=await save(tx,a,r,'ENDED',{...r.data,ended_reason:i.reason},'RELATION_ENDED');await notice(tx,n,'RELATION_ENDED',[r.owner_party_id,r.counterparty_id]);return n;}if(!['ACCEPT','REJECT'].includes(i.decision)||i.party_id!==r.counterparty_id||r.current_status!=='INVITED')throw error('RELATION_ACCEPTANCE_REQUIRED',409);if(i.decision==='REJECT')return save(tx,a,r,'REJECTED',r.data,'RELATION_REJECTED');if(r.data.valid_until<=new Date().toISOString())throw error('RELATION_EXPIRED',409);const [others]=await tx.execute("SELECT * FROM gig_records WHERE kind='RELATION' AND counterparty_id=? AND current_status='ACTIVE' FOR UPDATE",[r.counterparty_id]);for(const x of others.map(dto))if(x.data.scope===r.data.scope&&x.data.valid_from<r.data.valid_until&&r.data.valid_from<x.data.valid_until&&(x.data.exclusive||r.data.exclusive))throw error('EXCLUSIVE_RELATION_CONFLICT',409);return save(tx,a,r,'ACTIVE',{...r.data,accepted_by:a.id},'RELATION_ACCEPTED');});},
 async createGig(ctx,i){shape(i,['party_id','title','brief','category','scope','rule_id','proofs','operation_key']);label(i.title,200);label(i.brief,8000);ref(i.category);const scope=policy.scope(i.scope);if(scope.valid_until<=new Date().toISOString())throw error('GIG_EXPIRED',400);return db.withTransaction(async tx=>{const a=await actor(tx,ctx);await owner(tx,a,i.party_id);const rule=await liveRule(tx,i.rule_id),category=rule.data.rule.categories.find(c=>c.code===i.category);if(!category?.allowed)throw error('GIG_CATEGORY_FORBIDDEN',409);if(!Array.isArray(i.proofs)||i.proofs.length>30)throw error('EVIDENCE_REQUIRED',400);for(const p of i.proofs){shape(p,['code','asset_id']);ref(p.code);await evidence(tx,[p.asset_id],i.party_id);}if(category.required_proofs.some(code=>!i.proofs.some(p=>p.code===code)))throw error('REQUIRED_PROOF_MISSING',409);return command(tx,a,'GIG',i,()=>insert(tx,a,'GIG',i.party_id,null,null,'IN_REVIEW',{title:i.title,brief:i.brief,category:i.category,scope,rule_id:rule.id,rule_sha256:rule.content_sha256,proofs:i.proofs,review:null,suspension:null}));});},
 async suspend(ctx,i){shape(i,['record_id','expected_version','reason','operation_key']);label(i.reason,2000);return mutate(ctx,i,'SUSPEND',(tx,a,r)=>operator(tx,a,r,true),async(tx,a,r)=>{if(r.kind!=='GIG'||r.current_status!=='PUBLISHED')throw error('GIG_NOT_PUBLISHED',409);const n=await save(tx,a,r,'SUSPENDED',{...r.data,suspension:{reason:i.reason,account_id:a.id}},'GIG_SUSPENDED');const [offers]=await tx.execute("SELECT owner_party_id FROM gig_records WHERE parent_id=? AND kind='OFFER'",[r.id]);await notice(tx,n,'GIG_SUSPENDED',[r.owner_party_id,...offers.map(x=>x.owner_party_id)]);return n;});},
 async offer(ctx,i){shape(i,['party_id','gig_id','spec_id','avatar_id','consent_id','relation_id','commission','terms','ranking_opt_in','evidence_asset_ids','operation_key']);if(typeof i.ranking_opt_in!=='boolean')throw error('INVALID_RANKING_CONSENT',400);label(i.terms,8000);const commission=policy.commission(i.commission);return db.withTransaction(async tx=>{const a=await actor(tx,ctx);await owner(tx,a,i.party_id);const g=await load(tx,i.gig_id,'GIG');if(g.owner_party_id===i.party_id)throw error('SELF_DEAL_FORBIDDEN',409);await evidence(tx,i.evidence_asset_ids,i.party_id);const spec=checked(await one(tx,"SELECT * FROM trade_records WHERE id=? AND kind='SPEC' FOR SHARE",[id(i.spec_id)]));if(spec.current_status!=='PUBLISHED'||spec.merchant_party_id!==i.party_id||spec.data.provider_party_id!==i.party_id||spec.data.line_kind==='LICENSE')throw error('COMMERCIAL_SPEC_REQUIRED',409);let relation=null;if(i.relation_id!==null){const r=await load(tx,i.relation_id,'RELATION','FOR SHARE'),now=new Date().toISOString();if(r.current_status!=='ACTIVE'||r.counterparty_id!==i.party_id||r.data.scope!=='COMMERCIAL'||r.data.valid_from>now||r.data.valid_until<=now||digest(r.data.commission)!==digest(commission))throw error('RELATION_NOT_APPLICABLE',409);relation={id:r.id,version:r.object_version,sha256:r.content_sha256,mcn_party_id:r.owner_party_id,terms:r.data.terms,valid_from:r.data.valid_from,valid_until:r.data.valid_until};}else if(commission.mcn_bps!==0)throw error('DIRECT_RELATION_REQUIRED',400);const data={ranking_opt_in:i.ranking_opt_in,spec_id:spec.id,avatar_id:id(i.avatar_id),consent_id:id(i.consent_id),relation,commission,terms:i.terms,evidence_asset_ids:i.evidence_asset_ids,review:null,buyer_accepted_by:null};await eligible(tx,g,{owner_party_id:i.party_id,data});return command(tx,a,'OFFER',i,()=>insert(tx,a,'OFFER',i.party_id,g.owner_party_id,g.id,'IN_REVIEW',data));});},
 async acceptOffer(ctx,i){shape(i,['record_id','party_id','expected_version','offer_sha256','operation_key']);return mutate(ctx,i,'ACCEPT_OFFER',async(tx,a,r)=>{await owner(tx,a,i.party_id);if(r.kind!=='OFFER'||r.counterparty_id!==i.party_id)throw error('GIG_PARTY_FORBIDDEN');},async(tx,a,r)=>{if(r.current_status!=='APPROVED'||r.content_sha256!==i.offer_sha256)throw error('OFFER_NOT_ACCEPTABLE',409);await eligible(tx,await load(tx,r.parent_id,'GIG'),r);return save(tx,a,r,'ACCEPTED',{...r.data,buyer_accepted_by:a.id},'OFFER_ACCEPTED');});},
 async notifications(ctx,{party_id}){return db.withTransaction(async tx=>{const a=await actor(tx,ctx);await owner(tx,a,party_id);const [rows]=await tx.execute('SELECT id,record_id,event_code FROM gig_notifications WHERE party_id=? ORDER BY created_at DESC,id DESC LIMIT 100',[party_id]);return {items:rows};});},
 async catalogue(ctx){return db.withTransaction(async tx=>{await actor(tx,ctx);const [rows]=await tx.execute("SELECT * FROM gig_records WHERE kind='GIG' AND current_status='PUBLISHED' ORDER BY created_at DESC,id DESC LIMIT 100");const [rules]=await tx.execute("SELECT * FROM gig_records WHERE kind='RULE' AND current_status='EFFECTIVE' ORDER BY id");return {rules:rules.map(dto).map(r=>({id:r.id,rule:r.data.rule})),items:rows.map(dto).filter(r=>r.data.scope.valid_until>new Date().toISOString()).map(r=>({id:r.id,title:r.data.title,brief:r.data.brief,category:r.data.category,scope:r.data.scope,buyer_party_id:r.owner_party_id}))};});},
 };
 return Object.assign(api,require('./settlement').methods({db,actor,owner,operator,access,insert,save,command}));
}
module.exports={createGigsRepository};
