(() => {
'use strict';
const data=window.PROJECT_DATA;
const page=document.getElementById('page');
const dialog=document.getElementById('detail-dialog');
const titles={overview:'业务全景',flows:'流程与界面',gaps:'新旧差距',roadmap:'需求与分期',decisions:'讨论与待决策'};
let view='overview',stage='custom',flow='custom',gapFilter='全部',decisionFilter='全部';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const badge=(s,c='target')=>`<span class="pill ${c}">${esc(s)}</span>`;
const head=(eye,title,sub)=>`<div class="page-head"><div><span class="eyebrow">${eye}</span><h1>${title}</h1><p>${sub}</p></div>${badge('V0.4 · 评审稿','pending')}</div>`;
const section=(title,body,extra='')=>`<section class="panel spaced"><div class="section-top"><h2>${title}</h2>${extra}</div>${body}</section>`;
function showDialog(label,title,html){document.getElementById('dialog-label').textContent=label;document.getElementById('dialog-content').innerHTML=`<h2 id="dialog-title">${esc(title)}</h2>${html}`;dialog.showModal();}
function refsHTML(refs){return refs.map(([title,path])=>`<div class="evidence-item">${esc(title)}<code>${esc(path)}</code></div>`).join('');}
function overview(){const s=data.stages.find(x=>x.id===stage);return head('PROJECT ATLAS / 01','从现有 App，看清下一版主线','同一个数字人，连接自娱消费、商业接单与公开发行。')+`<section class="panel"><div class="section-top"><h2>四个板块，一条用户旅程</h2><small>选择板块，查看现状与目标</small></div><div class="world">${data.stages.map(x=>`<button class="stage ${x.id===stage?'active':''}" data-stage="${x.id}" aria-pressed="${x.id===stage}"><span class="stage-num">0${data.stages.indexOf(x)+1} / ${x.phase}</span><h3>${x.name}</h3><p>${x.subtitle}</p><span class="stage-link">查看现状与差距 ↗</span></button>`).join('')}</div><div class="selected-detail" aria-live="polite"><div><span class="muted-label">现有实现 / ${s.name}</span><p>${s.current}</p></div><div><span class="muted-label">最新讨论 / ${s.phase}</span><p>${s.target}</p><button class="text-btn" data-stage-detail="${s.id}">差距与依据 ↗</button></div></div><div class="line-diagram"><div class="business-line"><div class="line-title"><h3>自娱线 · 做自己的主角</h3>${badge('P0 主闭环','exists')}</div><div class="mini-flow"><span>我的数字人</span><span class="arrow">→</span><span>定制与样片</span><span class="arrow">→</span><span>私人收藏</span></div><p class="line-caption">用户主导 · 允许理想化形象 · 基础内容审核</p></div><div class="business-line issue"><div class="line-title"><h3>发行线 · 成角出品</h3>${badge('正式能力 P2','defer')}</div><div class="mini-flow"><span>项目与阵容</span><span class="arrow">→</span><span>授权及严审</span><span class="arrow">→</span><span>公开发行</span></div><p class="line-caption">自娱转发行需补条件 · P0 预留入口与字段</p></div></div></section><div class="below-grid"><section class="panel"><div class="section-top"><h2>现有工程可以继续承接什么</h2></div><div class="stack-layer"><strong>用户入口</strong><span>Flutter 12.3.1+22 · 40 个页面 · 在线 / 演示模式</span></div><div class="stack-layer"><strong>业务服务</strong><span>Node / Express · 25 个路由模块 · SQLite</span></div><div class="stack-layer"><strong>能力基础</strong><span>账号、数字人、剧本、生成任务、上传、审核记录、订单</span></div><div class="stack-layer"><strong>外部服务</strong><span>火山 AI、核身审核、支付宝已有接入代码；运行可用性需独立验收</span></div></section><section class="panel"><div class="section-top"><h2>最影响下一版的三个变化</h2></div><div class="key-find"><span class="number">01</span><div><h3>尾款从剧本确认移到样片确认</h3><p>改变支付时点、修改规则和制作责任。</p></div></div><div class="key-find"><span class="number">02</span><div><h3>自娱与发行成为独立业务线</h3><p>同一作品不能沿用自娱审核直接发行。</p></div></div><div class="key-find"><span class="number">03</span><div><h3>先收紧 P0，再铺开变现与发行</h3><p>已有高端、机构、席位功能需要重新归位。</p></div></div></section></div>`;}
function render(){document.querySelectorAll('[data-view]').forEach(b=>{if(b.dataset.view===view)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});document.getElementById('breadcrumb').textContent='项目 / '+titles[view];page.innerHTML=view==='overview'?overview():view==='flows'?flows():view==='gaps'?gaps():view==='roadmap'?roadmap():decisions();}
function setView(v){view=titles[v]?v:'overview';if(location.hash!=='#'+view)history.replaceState(null,'','#'+view);render();}
document.addEventListener('click',e=>{const el=e.target.closest('button,a');if(!el)return;if(el.dataset.view){setView(el.dataset.view);window.scrollTo({top:0});}if(el.dataset.stage){stage=el.dataset.stage;render();}if(el.dataset.stageDetail){const s=data.stages.find(x=>x.id===el.dataset.stageDetail);showDialog('板块 / '+s.phase,s.name,`<p class="dialog-copy">${s.gap}</p>${refsHTML(s.refs)}`);}if(el.dataset.action==='sources')showSources();});
document.getElementById('close-dialog').addEventListener('click',()=>dialog.close());
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
function showSources(){showDialog('资料与判断口径','方向、建议、实现，分开阅读',`<ul class="source-list"><li><strong>最新会议.docx</strong><p>V0.4 评审稿，源于 9 月 12 日战略沟通。包含业务线、页面、流程、状态机与授权专章。</p></li><li><strong>晶选片场_业务架构融合与待处理问题清单_20260915.md</strong><p>新架构与旧问题的映射，补充制作侧、资金、支付和分期缺口。</p></li><li><strong>晶选片场_业务决策工作底稿_20260915.xlsx</strong><p>32 项待决策。I2:L33 会议结论、补充约定、负责人、截止日期均为空。推荐数值不能视为决议。</p></li><li><strong>现有前后端源码</strong><p>晶晶日上工程交接包 / 01_源码 / frontend_jingjingshangri_app 与 backend_server。页面中的“前端”“后端”路径均相对于这两个目录。</p></li><li><strong>旧设计与交接档案</strong><p>产品与价格单一事实源记录旧规则；暖墨 HTML 是旧业务的视觉提案；Gate0 包是性能实验增量，并非新业务 App。</p></li></ul><p class="small-note">“已有”指在本地代码中找到实现，不代表真实支付、生成、授权或发行已通过线上验收。本页不修改原始决策记录。</p>`);}
function flows(){const f=data.flows[flow];const steps=(list,old)=>`<ol class="flow-steps">${list.map((x,i)=>`<li class="flow-step ${x[2]==='focus'?'highlight':x[2]==='pay'?'legacy-pay':''}"><span class="step-count">${String(i+1).padStart(2,'0')}</span><div>${x[0]}<small>${x[1]}</small></div></li>`).join('')}</ol>`;return head('JOURNEY / 02','流程与界面对照','核心变化：用户确认什么、何时付款、作品最终去哪里。')+`<div class="segment" aria-label="选择流程">${[['custom','定制剧交易'],['avatar','数字人创建'],['review','授权与审核']].map(([id,label])=>`<button data-flow="${id}" aria-pressed="${flow===id}">${label}</button>`).join('')}</div><h2 style="margin-bottom:18px">${f.title}</h2><div class="flow-columns"><section class="flow-column">${badge('旧版 · 实际代码','defer')}<h2>现有流程</h2><p>${f.oldIntro}</p>${steps(f.old,true)}</section><section class="flow-column">${badge('新版 · 目标流程','exists')}<h2>最新讨论</h2><p>${f.newIntro}</p>${steps(f.next,false)}</section></div><div class="change-note">${f.note}</div><div class="flow-source">${f.source}</div>`+section('从旧界面看见旧业务',`<div class="screens">${data.screens.map((s,i)=>`<figure class="screen-card"><button data-screen="${i}" aria-label="放大${s.title}"><img src="${s.src}" alt="${s.title}：${s.caption}" loading="lazy"></button><figcaption>${s.title}<span>${s.caption}</span></figcaption></figure>`).join('')}</div><p class="small-note">来源：App 图文对照审阅包中的旧版实机渲染截图；用于解释旧设计，不作为当前线上运行证据。</p>`)+`<div class="design-comparison"><section class="design-block"><div class="section-top"><h3>现有信息架构</h3>${badge('源码现状','defer')}</div><div class="nav-preview"><span>首页</span><span>圆梦</span><span>＋创作</span><span>消息</span><span>我的</span></div><p>创作中心并列 AI 生成、祝福、定制、数字人和角色席位。已有暖墨提案保留这套业务结构。</p><button class="text-btn" data-action="prototype">查看暖墨视觉提案 ↗</button></section><section class="design-block"><div class="section-top"><h3>新讨论的信息架构</h3>${badge('推荐 · 未决议','pending')}</div><div class="nav-preview new"><span>首页</span><span>入戏</span><span>培育</span><span>成角</span><span>我的</span></div><p>首页承载数字人与分发，入戏承载消费，培育承载经营，成角承载发行。消息、认证和机构入口收进“我的”。</p></section></div>`;}
function gaps(){const filtered=data.gaps.filter(g=>gapFilter==='全部'||g.category===gapFilter);const cats=['全部','重构','贯通','补齐','重组','后置'];return head('GAP MAP / 03','哪些要重做，哪些能接着用','14 个关键差距，区分业务变化与已有能力未贯通。')+`<div class="legend"><b>判断口径</b><span>重构：业务规则变化</span><span>贯通：已有能力未形成闭环</span><span>补齐：缺必要能力</span><span>重组 / 后置：范围调整</span></div><div class="segment" aria-label="差距类型">${cats.map(c=>`<button data-gap-filter="${c}" aria-pressed="${gapFilter===c}">${c}</button>`).join('')}<span class="count-label" role="status">显示 ${filtered.length} / ${data.gaps.length} 项</span></div><div class="gap-grid">${filtered.map(g=>`<article class="gap-card"><div class="meta">${badge(g.category,g.category==='重构'?'rework':g.category==='后置'?'defer':g.category==='贯通'?'pending':'target')}<span class="group">${g.phase}</span></div><h2>${g.title}</h2><div class="comparison-row"><span>现状</span><p>${g.old}</p></div><div class="comparison-row new"><span>目标</span><p>${g.next}</p></div><div class="gap-action"><p>${g.action}</p><button class="text-btn" data-gap="${g.id}">查看依据 ↗</button></div></article>`).join('')}</div>`+section('不是所有内容都被推翻',`<div class="selected-detail" style="border:0;margin:0;padding:0"><div><h3>保留能力基础</h3><p>账号、数字人资料、剧本库、生成任务、上传、审核记录、订单和支付宝基础可以复用。修改重点是它们如何围绕新业务连接。</p></div><div><h3>校正“从无到有”的说法</h3><p>旧版已有四步理念、禁用众筹与收益承诺、授权和撮合分账设计。新版更系统，但这些并非全部首次提出。</p></div></div>`);}
function roadmap(){return head('SCOPE / 04','先完成自娱定制，再展开经营与发行','P0 / P1 / P2 表示范围顺序，不代表工期或完成率。')+`<div class="roadmap-columns">${data.roadmap.map(p=>`<section class="roadmap-phase"><span class="phase-label">${p.phase} / ${p.phase==='P0'?'最小闭环':p.phase==='P1'?'变现分发':'发行与高端'}</span><h2>${p.title}</h2><p>${p.desc}</p>${p.items.map(([title,desc])=>`<div class="requirement"><h3>${title}</h3><p>${desc}</p></div>`).join('')}</section>`).join('')}</div>`+section('P0 的依赖顺序',`<ol class="priority-list"><li><span>01</span><div><h3>先锁定订单和生产规则</h3><p>六步与状态对应、首款、样片规格、修改、退款、供给模式、谁确认与谁交付。</p></div></li><li><span>02</span><div><h3>定义资产、授权与费用对象</h3><p>数字人类型与权利人、授权触发、陪演来源、费用构成、收款及供给结算。</p></div></li><li><span>03</span><div><h3>连通一笔真实定制订单</h3><p>从配置到首款、样片、尾款、最终交付与收藏，同时覆盖失败和退款。</p></div></li><li><span>04</span><div><h3>再对齐前端入口与后台操作</h3><p>同一套状态驱动用户按钮、制作工作台、消息通知、审核与客服处置。</p></div></li></ol>`)+`<div class="change-note">首期收缩并不等于删掉所有旧功能。高端、MCN、角色和发行相关能力应按新分期归位，历史订单也不能被新流程直接改写。</div><p class="flow-source">来源：最新会议 §8；融合清单 §1.6、A3、A4、D1。具体排期未在材料中确定。</p>`;}
function decisions(){const labels={全部:'全部 32 项',A:'A · 主闭环 9',B:'B · 合规 8',C:'C · 变现 7',D:'D · 发行 8'};const list=data.decisions.filter(d=>decisionFilter==='全部'||d.id.startsWith(decisionFilter));return head('DECISION LOG / 05','新方向已经清晰，参数尚待拍板','下方推荐内容来自工作底稿 G 列；未将建议改写成正式需求。')+`<div class="decision-summary"><div class="summary-block"><strong>32</strong><div><p>待决策问题</p><small>A9 / B8 / C7 / D8，共四组</small></div></div><div class="summary-block"><strong>0</strong><div><p>已填写会议结论</p><small>I2:L33 结论、约定、负责人、期限均为空</small></div></div></div><div class="segment" aria-label="决策分组">${Object.entries(labels).map(([key,label])=>`<button data-decision-filter="${key}" aria-pressed="${decisionFilter===key}">${label}</button>`).join('')}</div><div class="decision-list">${list.map(d=>`<details class="decision"><summary><span class="decision-id">${d.id}</span><span class="decision-title">${esc(d.title)}</span>${badge(d.phase+' · 未决议','pending')}</summary><div class="decision-body"><span class="field">为什么要定</span><p>${esc(d.why)}</p><span class="field">工作底稿的推荐方案 · 尚未确认</span><p>${esc(d.recommendation)}</p><span class="field">备选</span><p>${esc(d.options)}</p><div class="decision-foot">影响：${esc(d.affected)}<br>来源：决策总表第 ${d.row} 行，推荐 G${d.row}；会议结论 I${d.row} 为空。涉及法规、费率与资质的表述按原讨论保留，未在本页独立核验。</div></div></details>`).join('')}</div>`+section('进入开发前，需要统一的几处口径',`<div class="inconsistency"><h3>六步不全是付款前的配置步骤</h3><p>图2的第五步是样片、第六步是交付，表4-1却写“六步填完待下单”。应拆开需求配置与订单履约状态。</p></div><div class="inconsistency"><h3>11 态主线尚未覆盖交易异常</h3><p>定制状态表未完整列取消、超时、退款和争议；修改用尽、不付尾款也需要可执行出口。</p></div><div class="inconsistency"><h3>轻量自娱与商用授权触发需统一</h3><p>A6 建议把重确权后移，但授权专章要求先授权后建模；纯虚拟开放矩阵与统一 EVIDENCED 闸门也要对齐。</p></div><div class="inconsistency"><h3>P0 陪演来源与 P1 市场需要衔接</h3><p>P0 定制包含选陪演，而完整广场、服务市场与提现后置。首期可选资源、定价和结算由谁维护，需要明确。</p></div><div class="inconsistency"><h3>制作模式会改变合同与收款关系</h3><p>旧规则强调外部承制方交付，新建议偏向平台自营或签约班底。这项决定同时影响责任、成本与费用分配。</p></div>`);}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.flow){flow=b.dataset.flow;render();}if(b.dataset.gapFilter){gapFilter=b.dataset.gapFilter;render();}if(b.dataset.decisionFilter){decisionFilter=b.dataset.decisionFilter;render();}if(b.dataset.gap){const g=data.gaps.find(x=>x.id===b.dataset.gap);showDialog(g.category+' / '+g.phase,g.title,`<p class="dialog-copy">${g.action}</p>${refsHTML(g.refs)}`);}if(b.dataset.screen!==undefined){const s=data.screens[Number(b.dataset.screen)];showDialog('旧版界面 / 历史截图',s.title,`<p class="dialog-copy">${s.caption}</p><img class="image-full" src="${s.src}" alt="${s.title}">`);}if(b.dataset.action==='prototype')showDialog('视觉提案 / 不代表新版业务已实现','暖墨 HTML 视觉原型',`<p class="dialog-copy">已有暖墨方案与旧 12.3.1+22 逐页对齐，保留原导航与七步定制。视觉语言可参考，业务结构仍需调整。</p><img class="image-full" src="assets/warm-prototype.png" alt="暖墨视觉原型及页面设计说明"><p class="flow-source">来源：晶晶日上_UI设计方案 / 质感层v2对比 / home_v2_全屏.png</p>`);});
window.addEventListener('hashchange',()=>{const next=location.hash.slice(1);if(titles[next])setView(next);});setView(location.hash.slice(1)||'overview');
})();
