 'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');
const {randomUUID:key,randomBytes,createHash}=require('node:crypto'),mysql=require('mysql2/promise');
const {openDatabase}=require('../src/infrastructure/database'),{migrate}=require('../src/infrastructure/database/migrator');
const {createPartyRepository}=require('../src/modules/party/repository'),{createAuthRepository}=require('../src/modules/auth/repository');
const {maintainOperatorGrant}=require('../src/modules/governance/operator-access'),{createAccountApi}=require('../src/http/account-api');
const {createTradeRepository}=require('../src/modules/trade/repository'),{createRuleContent}=require('../src/modules/governance/content');
const {createSupplyRepository}=require('../src/modules/works/repository'),{createSupplyAssets}=require('../src/modules/works/assets');
test('gigs isolated MySQL and real HTTP cooperation, commissions and rankings',{skip:!process.env.JX_MYSQL_TEST_ENV_FILE},async t=>{
 const env=JSON.parse(await fs.readFile(process.env.JX_MYSQL_TEST_ENV_FILE,'utf8'));assert.equal(env.NODE_ENV,'test');assert.equal(env.MYSQL_HOST,'127.0.0.1');assert.equal(env.MYSQL_DATABASE,'jx_dev');
 const name=`jx_test_${process.pid}_${randomBytes(6).toString('hex')}`,control=await mysql.createConnection({host:env.MYSQL_HOST,port:Number(env.MYSQL_PORT),user:env.MYSQL_USER,password:env.MYSQL_PASSWORD,database:env.MYSQL_DATABASE});let db,server;
 try{
 await control.query('CREATE DATABASE '+mysql.escapeId(name)+' CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin');db=await openDatabase({...env,MYSQL_DATABASE:name});const migrationDirectory=path.resolve(__dirname,'../migrations/mysql-runtime'),baseDirectory=await fs.mkdtemp(path.resolve(__dirname,'../../../..','.local/gigs-upgrade-'));try{for(const file of await fs.readdir(migrationDirectory))if(file.endsWith('.sql')&&file.slice(0,4)<='0049')await fs.copyFile(path.join(migrationDirectory,file),path.join(baseDirectory,file));await migrate(db,{directory:baseDirectory});await migrate(db);await migrate(db);}finally{await fs.rm(baseDirectory,{recursive:true});}
 const principals=new Map(),resolvePrincipal=async ctx=>principals.get(ctx),parties=createPartyRepository(db,{resolvePrincipal}),secret=randomBytes(32).toString('base64'),auth=createAuthRepository(db,{secret}),trade=createTradeRepository(db,{resolvePrincipal}),supply=createSupplyRepository(db,{resolvePrincipal});
 const people=[];for(const label of ['supplier','buyer','mcn','reviewer','rule-author','outsider']){const ctx={};principals.set(ctx,{subject_ref:'synthetic:'+key()});const p={ctx,...await parties.registerAccount(ctx,{display_name:label}),token:randomBytes(32).toString('base64url')};people.push(p);await db.execute('INSERT INTO auth_sessions(token_hash,account_id,expires_ms) VALUES (?,?,ROUND(UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000)+3600000)',[auth.secure.digest('token',p.token),p.account_id]);}
 const [seller,buyer,mcn,reviewer,author,outsider]=people;for(const p of [reviewer,author,seller,mcn])for(const action of ['GIG_REVIEW','TRADE_REVIEW','TRADE_REFUND','SUPPLY_REVIEW_CONSENT'])await maintainOperatorGrant(db,{account_id:p.account_id,action,enabled:true,expires_at:null,expected_version:0,authority_ref:'synthetic:test',reason:'isolated test'});
 await db.execute("INSERT INTO party_capabilities(party_id,code,current_status) VALUES (?,'MCN','ACTIVE')",[mcn.personal_party_id]);
 const files=new Map(),storageFactory=()=>({async put({key,body}){files.set(key,Buffer.from(body));return {key,size:body.length,sha256:createHash('sha256').update(body).digest('hex')};},async getBuffer(key){return files.get(key);}}),assets=createSupplyAssets({db,repository:supply,storageFactory});
 const upload=(p,purpose)=>assets.upload(p.ctx,{party_id:p.personal_party_id,purpose,media_type:'text/plain',body:Buffer.from('synthetic '+purpose+key()),operation_key:key()});
 const evidence=await upload(seller,'RIGHTS_EVIDENCE'),buyerEvidence=await upload(buyer,'RIGHTS_EVIDENCE'),mcnEvidence=await upload(mcn,'RIGHTS_EVIDENCE'),material=await upload(seller,'AVATAR_MATERIAL'),consentEvidence=await upload(seller,'CONSENT_EVIDENCE');
 const avatar=await supply.createAvatar(seller.ctx,{party_id:seller.personal_party_id,display_name:'synthetic',material_asset_ids:[material.id],operation_key:key()});
 async function consentFor(purposes){let r=await supply.createConsent(seller.ctx,{consent:{avatar_id:avatar.id,subject_party_id:seller.personal_party_id,features:['FACE'],purposes,territories:['CN'],valid_from:'2020-01-01T00:00:00.000Z',valid_until:'2099-01-01T00:00:00.000Z',terms:'synthetic only',evidence_asset_ids:[consentEvidence.id]},operation_key:key()});return supply.reviewConsent(reviewer.ctx,{record_id:r.id,expected_version:r.object_version,decision:'APPROVED',reason:'synthetic',operation_key:key()});}
 const consent=await consentFor(['COMMERCIAL']),privateConsent=await consentFor(['PRIVATE']);
 const ruleId=key(),content=createRuleContent({id:ruleId,rule_key:'gigs.test',version:'1',terms:{synthetic:'not commercial approval'}});await db.execute('INSERT INTO governance_rules(id,rule_key,version_label,content_json,effective_at,created_by,current_status) VALUES (?,?,?,?,?,?,?)',[ruleId,'gigs.test','1',JSON.stringify(content),'2020-01-01 00:00:00',author.account_id,'EFFECTIVE']);
 const reviewTrade=r=>trade.review(reviewer.ctx,{record_id:r.id,expected_version:r.object_version,decision:'APPROVED',reason:'synthetic',operation_key:key()});
 const spec=await reviewTrade(await trade.createSpec(seller.ctx,{party_id:seller.personal_party_id,previous_spec_id:null,title:'Synthetic commercial delivery',provider_party_id:seller.personal_party_id,line_kind:'OTHER',unit_minor:10001,currency:'CNY',specification:{version:'1',service_tier:'test',sample_seconds:0,final_seconds:0,revision_limit:1,deliverables:['synthetic commercial material'],terms:'synthetic terms'},operation_key:key()}));
 server=createAccountApi({db,secret,supplyStorageFactory:storageFactory}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const host='http://127.0.0.1:'+server.address().port,fixtures=[];
 async function api(method,url,p=seller,body,party=p?.personal_party_id,headers={}){const r=await fetch(host+'/api/v1/gigs'+url,{method,headers:{...(p?{Authorization:'Bearer '+p.token}:{}),...(party?{'X-Acting-Party':party}:{}),...(method==='POST'?{'Content-Type':'application/json','Idempotency-Key':key()}:{}),...headers},...(body===undefined?{}:{body:JSON.stringify(body)})});const out={status:r.status,body:(r.headers.get('content-type')||'').includes('application/json')?await r.json():Buffer.from(await r.arrayBuffer())};return out;}
 const take=(r,schema='GigRecordResponse')=>{assert.equal(r.status,200,JSON.stringify(r.body));fixtures.push({schema,value:r.body});return r.body.data;};
 const checks={identity_verified:true,authority_verified:true,materials_reviewed:true,content_reviewed:true,marking_reviewed:true};
 const review=(r,p=reviewer)=>api('POST','/records/'+r.id+'/reviews',p,{decision:'APPROVED',reason:'synthetic independent review',checks:r.kind==='RULE'?null:checks},null,{'If-Match':'"'+r.object_version+'"'}).then(take);
 const ruleInput={version:'test1',categories:[{code:'TEST',allowed:true,required_proofs:['AUTHORITY']},{code:'BANNED_TEST',allowed:false,required_proofs:[]}],ranking:{window_days:7,newcomer_days:30,minimum_orders:1,order_weight:10,net_minor_weight:0,newcomer_bonus:2},terms:'synthetic only, not production policy'};
 let rule,relation,gig,offer,order,payment,commission;
 await t.test('no login, no operator and no self-review',async()=>{assert.equal((await api('GET','/catalogue',null)).status,401);assert.equal((await api('POST','/rules',buyer,{rule:ruleInput},null)).status,403);rule=take(await api('POST','/rules',author,{rule:ruleInput},null));assert.equal((await api('POST','/records/'+rule.id+'/reviews',author,{decision:'APPROVED',reason:'self',checks:null},null,{'If-Match':'"1"'})).status,403);rule=await review(rule);});
 const relationInput={artist_party_id:seller.personal_party_id,scope:'COMMERCIAL',valid_from:'2020-01-01T00:00:00.000Z',valid_until:'2099-01-01T00:00:00.000Z',exclusive:true,terms:'synthetic direct-only agreement',commission:{platform_bps:2000,mcn_bps:500},evidence_asset_ids:[mcnEvidence.id]};
 await t.test('MCN cannot silently add artist; artist acceptance is required',async()=>{relation=take(await api('POST','/relations',mcn,relationInput));assert.equal(relation.current_status,'INVITED');assert.equal((await api('POST','/relations/'+relation.id+'/decision',mcn,{decision:'ACCEPT',reason:'self'},mcn.personal_party_id,{'If-Match':'"1"'})).status,409);relation=take(await api('POST','/relations/'+relation.id+'/decision',seller,{decision:'ACCEPT',reason:'agree'},seller.personal_party_id,{'If-Match':'"1"'}));assert.equal(relation.current_status,'ACTIVE');});
 await t.test('overlapping exclusive relation rejected and outsiders cannot read',async()=>{const other=take(await api('POST','/relations',mcn,relationInput));assert.equal((await api('POST','/relations/'+other.id+'/decision',seller,{decision:'ACCEPT',reason:'duplicate'},seller.personal_party_id,{'If-Match':'"1"'})).status,409);assert.equal((await api('GET','/records/'+relation.id,outsider)).status,404);});
 const gigInput={title:'Synthetic brand task',brief:'Explicit commercial use',category:'TEST',scope:{purpose:'COMMERCIAL',territory:'CN',valid_until:'2098-01-01T00:00:00.000Z'},proofs:[{code:'AUTHORITY',asset_id:buyerEvidence.id}]};
 await t.test('missing proofs, forbidden category and unreviewed publication blocked',async()=>{assert.equal((await api('POST','/requests',buyer,{...gigInput,rule_id:rule.id,proofs:[]})).status,409);assert.equal((await api('POST','/requests',buyer,{...gigInput,rule_id:rule.id,category:'BANNED_TEST'})).status,409);gig=take(await api('POST','/requests',buyer,{...gigInput,rule_id:rule.id}));assert.equal(take(await api('GET','/catalogue',buyer),'GigCatalogueResponse').items.length,0);gig=await review(gig);assert.equal(take(await api('GET','/catalogue',buyer),'GigCatalogueResponse').items.length,1);});
 const offerInput=()=>({gig_id:gig.id,spec_id:spec.id,avatar_id:avatar.id,consent_id:consent.id,relation_id:relation.id,commission:relationInput.commission,terms:'synthetic receipt-based commission, MCN funded from platform',ranking_opt_in:true,evidence_asset_ids:[evidence.id]});
 await t.test('private-only consent does not authorize commercial offer',async()=>{assert.equal((await api('POST','/offers',seller,{...offerInput(),consent_id:privateConsent.id})).status,409);offer=take(await api('POST','/offers',seller,offerInput()));assert.equal((await api('POST','/records/'+offer.id+'/reviews',seller,{decision:'APPROVED',reason:'self',checks},null,{'If-Match':'"1"'})).status,403);assert.equal((await api('POST','/records/'+offer.id+'/reviews',mcn,{decision:'APPROVED',reason:'beneficiary self review',checks},null,{'If-Match':'"1"'})).status,403);offer=await review(offer);});
 await t.test('buyer accepts exact reviewed version and concurrent acceptance cannot overwrite',async()=>{const body={offer_sha256:offer.content_sha256},headers={'If-Match':'"'+offer.object_version+'"'};const replies=await Promise.all([api('POST','/offers/'+offer.id+'/acceptance',buyer,body,buyer.personal_party_id,headers),api('POST','/offers/'+offer.id+'/acceptance',buyer,body,buyer.personal_party_id,headers)]);assert.deepEqual(replies.map(x=>x.status).sort(),[200,412]);offer=take(replies.find(x=>x.status===200));});
 async function httpQuote({party_id,operation_key,...body}){const response=await fetch(host+'/api/v1/trade/quotes',{method:'POST',headers:{Authorization:'Bearer '+seller.token,'X-Acting-Party':party_id,'Idempotency-Key':operation_key,'Content-Type':'application/json'},body:JSON.stringify(body)});return take({status:response.status,body:await response.json()},'TradeRecordResponse');}
 async function quoteFor(o){return reviewTrade(await httpQuote({party_id:seller.personal_party_id,buyer_party_id:buyer.personal_party_id,lines:[{line_id:'commercial',spec_id:spec.id,quantity:1}],installments:[{key:'full',trigger:'ORDER_ACCEPTED',allocations:[{line_id:'commercial',amount_minor:10001}],apple_product_id:null}],channel:'ALIPAY',transaction_model:'DIRECT_SUPPLIER',rule_id:ruleId,expires_at:'2098-01-01T00:00:00.000Z',payment_window_minutes:30,license_reservation_id:null,commercial_offer_id:o.id,operation_key:key()}));}
 await t.test('commercial commitments are included before quote and sealed in order',async()=>{const q=await quoteFor(offer);assert.equal(q.data.commercial.offer_id,offer.id);order=await trade.accept(buyer.ctx,{record_id:q.id,party_id:buyer.personal_party_id,expected_version:q.object_version,quote_sha256:q.content_sha256,operation_key:key()});assert.deepEqual(order.data.quote.commercial.commission,relationInput.commission);const q2=await quoteFor(offer);await assert.rejects(trade.accept(buyer.ctx,{record_id:q2.id,party_id:buyer.personal_party_id,expected_version:q2.object_version,quote_sha256:q2.content_sha256,operation_key:key()}),e=>e.code==='COMMERCIAL_ORDER_EXISTS');});
 const config={provider:'ALIPAY',environment:'PRODUCTION',app_id:'synthetic.app',merchant_id:'synthetic.merchant',merchant_party_id:seller.personal_party_id,config_revision:'synthetic'};
 await t.test('no verified receipt means zero commission; verified receipt creates conserved accrual',async()=>{commission=take(await api('POST','/commissions',seller,{order_id:order.id}));assert.equal(commission.data.amounts.net_minor,0);payment=await trade.preparePayment(buyer.ctx,{party_id:buyer.personal_party_id,order_id:order.id,installment_key:'full',operation_key:key()},config);await trade.applyPayment({...config,payment_id:payment.id,currency:'CNY',amount_minor:10001,transaction_id:'synthetic.'+payment.id,status:'SUCCEEDED',product_id:null,app_account_token:null});await db.execute("UPDATE trade_journal SET created_at=CURRENT_TIMESTAMP(3)-INTERVAL 1 DAY WHERE order_id=?",[order.id]);commission=take(await api('POST','/commissions',mcn,{order_id:order.id}));assert.deepEqual(commission.data.amounts,{net_minor:10001,supplier_minor:8001,platform_minor:1500,mcn_minor:500});assert.equal(commission.data.paid_out_minor,0);});
 await t.test('repeated reconciliation and command replay do not create duplicate entries',async()=>{const headers={'Idempotency-Key':key()},body={order_id:order.id};const a=take(await api('POST','/commissions',seller,body,seller.personal_party_id,headers)),b=take(await api('POST','/commissions',seller,body,seller.personal_party_id,headers));assert.equal(a.object_version,b.object_version);const entries=take(await api('GET','/commissions/'+a.id+'/entries',seller),'GigEntriesResponse');assert.equal(entries.items.length,2);assert.equal((await api('GET','/commissions/'+a.id+'/entries',outsider)).status,404);});
 await t.test('daily ranking snapshot is deterministic and exposes no order IDs or receipt amounts',async()=>{const as_of=new Date().toISOString().slice(0,10)+'T00:00:00.000Z';const r=take(await api('POST','/rankings',reviewer,{rule_id:rule.id,as_of},null));const again=take(await api('POST','/rankings',author,{rule_id:rule.id,as_of},null));assert.equal(r.id,again.id);const pub=take(await api('GET','/rankings/'+r.id,outsider),'GigRankingResponse');assert.equal(pub.boards.hot.length,1);assert.equal(pub.boards.hot[0].orders,1);assert.ok(!JSON.stringify(pub).includes(order.id));assert.equal(pub.boards.hot[0].net,undefined);});
 await t.test('revoked MCN capability blocks new quotes',async()=>{await db.execute("UPDATE party_capabilities SET current_status='SUSPENDED' WHERE party_id=? AND code='MCN'",[mcn.personal_party_id]);await assert.rejects(quoteFor(offer),/MCN_CAPABILITY_REQUIRED/);await db.execute("UPDATE party_capabilities SET current_status='ACTIVE' WHERE party_id=? AND code='MCN'",[mcn.personal_party_id]);});
 await t.test('real consent withdrawal blocks further commercial quotes without rewriting financial facts',async()=>{await supply.withdrawConsent(seller.ctx,{record_id:consent.id,expected_version:consent.object_version,reason:'withdraw future use',operation_key:key()});await assert.rejects(quoteFor(offer),/COMMERCIAL_CONSENT_REQUIRED/);assert.equal(take(await api('POST','/commissions',mcn,{order_id:order.id})).data.amounts.mcn_minor,500);});
 await t.test('ending relation blocks new offers but preserves existing order commission',async()=>{relation=take(await api('POST','/relations/'+relation.id+'/decision',seller,{decision:'END',reason:'end future cooperation'},seller.personal_party_id,{'If-Match':'"'+relation.object_version+'"'}));assert.equal((await api('POST','/offers',seller,offerInput())).status,409);const r=take(await api('POST','/commissions',mcn,{order_id:order.id}));assert.equal(r.data.amounts.mcn_minor,500);assert.equal(r.data.relation.version,2);});
 await t.test('verified partial refund reverses commission once with exact rounding',async()=>{let r=await trade.requestRefund(buyer.ctx,{party_id:buyer.personal_party_id,payment_id:payment.id,allocations:[{line_id:'commercial',amount_minor:5000}],reason:'synthetic refund',operation_key:key()});r=await reviewTrade(r);await trade.claim(reviewer.ctx,r.id,null,'REFUND');await trade.applyRefund(r.id,{...config,payment_id:payment.id,refund_id:r.id,transaction_id:r.data.transaction_id,amount_minor:5000,currency:'CNY',status:'SUCCEEDED'});const c=take(await api('POST','/commissions',seller,{order_id:order.id}));assert.deepEqual(c.data.amounts,{net_minor:5001,supplier_minor:4001,platform_minor:750,mcn_minor:250});const entries=take(await api('GET','/commissions/'+c.id+'/entries',mcn),'GigEntriesResponse');assert.equal(entries.items.at(-1).data.delta.mcn_minor,-250);take(await api('POST','/commissions',mcn,{order_id:order.id}));assert.equal(take(await api('GET','/commissions/'+c.id+'/entries',mcn),'GigEntriesResponse').items.length,3);});
 await t.test('suspension removes discovery and notifies buyer and suppliers',async()=>{gig=take(await api('POST','/requests/'+gig.id+'/suspension',reviewer,{reason:'synthetic policy violation'},null,{'If-Match':'"'+gig.object_version+'"'}));assert.equal(take(await api('GET','/catalogue',buyer),'GigCatalogueResponse').items.length,0);assert.ok(take(await api('GET','/notifications',seller),'GigNotificationsResponse').items.some(n=>n.event_code==='GIG_SUSPENDED'));});
 await t.test('evidence downloads are private and linked to exact record',async()=>{assert.equal((await api('GET','/records/'+gig.id+'/evidence/'+buyerEvidence.id,reviewer,undefined,null)).status,200);assert.equal((await api('GET','/records/'+gig.id+'/evidence/'+evidence.id,reviewer,undefined,null)).status,404);assert.equal((await api('GET','/records/'+gig.id+'/evidence/'+buyerEvidence.id,outsider)).status,404);});
 await t.test('audit failure rolls back records and command reservations',async()=>{await db.withConnection(c=>c.query("CREATE TRIGGER gig_audit_fail BEFORE INSERT ON gig_audit FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='synthetic audit failure'"));try{const [[before]]=await db.execute('SELECT COUNT(*) n FROM gig_records');assert.equal((await api('POST','/rules',author,{rule:ruleInput},null)).status,503);const [[after]]=await db.execute('SELECT COUNT(*) n FROM gig_records');assert.equal(before.n,after.n);}finally{await db.withConnection(c=>c.query('DROP TRIGGER gig_audit_fail'));}});

 await t.test('membership revocation immediately removes historic commission access',async()=>{await db.execute("UPDATE party_memberships SET current_status='REVOKED' WHERE party_id=? AND account_id=?",[mcn.personal_party_id,mcn.account_id]);assert.equal((await api('GET','/records/'+commission.id,mcn)).status,403);await db.execute("UPDATE party_memberships SET current_status='ACTIVE' WHERE party_id=? AND account_id=?",[mcn.personal_party_id,mcn.account_id]);});
 await t.test('retired rule cannot publish new gigs but historical accrual remains readable',async()=>{rule=take(await api('POST','/rules/'+rule.id+'/retirement',reviewer,{reason:'replaced for future work'},null,{'If-Match':'"'+rule.object_version+'"'}));assert.equal((await api('POST','/requests',buyer,{...gigInput,rule_id:rule.id})).status,409);assert.equal(take(await api('POST','/commissions',mcn,{order_id:order.id})).data.amounts.mcn_minor,250);});
 take(await api('GET','/records?kind=OFFER&limit=1',seller),'GigListResponse');
 const out=path.resolve(__dirname,'../../../..','.local/gigs-http-fixtures.json');await fs.mkdir(path.dirname(out),{recursive:true});await fs.writeFile(out,JSON.stringify({synthetic_only:true,cases:fixtures},null,2));
 }finally{if(server)await new Promise(r=>{server.close(r);server.closeAllConnections();});if(db)await db.close();await control.query('DROP DATABASE '+mysql.escapeId(name));await control.end();}
});
