 'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');
const {randomUUID:key,randomBytes,createHash}=require('node:crypto'),mysql=require('mysql2/promise');
const {openDatabase}=require('../src/infrastructure/database'),{migrate}=require('../src/infrastructure/database/migrator');
const {createPartyRepository}=require('../src/modules/party/repository'),{createAuthRepository}=require('../src/modules/auth/repository');
const {createSupplyRepository}=require('../src/modules/works/repository'),{createSupplyAssets}=require('../src/modules/works/assets');
const {maintainOperatorGrant}=require('../src/modules/governance/operator-access'),{createAccountApi}=require('../src/http/account-api');
test('licensing HTTP, conflict protection, conditions, binding and controlled reading with isolated MySQL',{skip:!process.env.JX_MYSQL_TEST_ENV_FILE},async t=>{
 const env=JSON.parse(await fs.readFile(process.env.JX_MYSQL_TEST_ENV_FILE,'utf8'));
 assert.equal(env.NODE_ENV,'test');assert.equal(env.DB_CLIENT,'mysql');assert.equal(env.MYSQL_HOST,'127.0.0.1');assert.equal(env.MYSQL_PORT,'33316');assert.equal(env.MYSQL_USER,'jx_local');assert.equal(env.MYSQL_DATABASE,'jx_dev');
 const name=`jx_test_${process.pid}_${randomBytes(6).toString('hex')}`,control=await mysql.createConnection({host:env.MYSQL_HOST,port:Number(env.MYSQL_PORT),user:env.MYSQL_USER,password:env.MYSQL_PASSWORD,database:env.MYSQL_DATABASE});let db,server;
 try{
  await control.query('CREATE DATABASE '+mysql.escapeId(name)+' CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin');db=await openDatabase({...env,MYSQL_DATABASE:name});await migrate(db);
  const principals=new Map(),resolvePrincipal=async ctx=>principals.get(ctx),parties=createPartyRepository(db,{resolvePrincipal}),secret=randomBytes(32).toString('base64'),auth=createAuthRepository(db,{secret}),repo=createSupplyRepository(db,{resolvePrincipal});
  const people=[];
  for(const label of ['author','rights','content','outsider','subject']){const ctx={};principals.set(ctx,{subject_ref:'synthetic:'+key()});const p={ctx,...await parties.registerAccount(ctx,{display_name:label}),token:randomBytes(32).toString('base64url')};people.push(p);await db.execute('INSERT INTO auth_sessions(token_hash,account_id,expires_ms) VALUES (?,?,ROUND(UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000)+3600000)',[auth.secure.digest('token',p.token),p.account_id]);}
  const [author,rights,content,outsider,subject]=people;
  for(const [person,actions] of [[rights,['SUPPLY_REVIEW_PROFILE','SUPPLY_REVIEW_RIGHTS','SUPPLY_REVIEW_CONSENT','LICENSE_REVIEW']],[content,['SUPPLY_REVIEW_CONTENT']],[author,['SUPPLY_REVIEW_PROFILE','SUPPLY_REVIEW_RIGHTS','SUPPLY_REVIEW_CONSENT','LICENSE_REVIEW']]])for(const action of actions)await maintainOperatorGrant(db,{account_id:person.account_id,action,enabled:true,expires_at:null,expected_version:0,authority_ref:'synthetic:test',reason:'isolated tests only'});
  const files=new Map();let puts=0;
  const storageFactory=()=>({async put({key,body}){puts++;files.set(key,Buffer.from(body));return {key,size:body.length,sha256:createHash('sha256').update(body).digest('hex')};},async getBuffer(key){return files.get(key);}});
  const assets=createSupplyAssets({db,repository:repo,storageFactory});
  server=createAccountApi({db,secret,supplyStorageFactory:storageFactory}).listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));
  const base='http://127.0.0.1:'+server.address().port+'/api/v1/supply',fixtures=[];
  async function request(method,url,person=author,body,partyId=person?.personal_party_id,headers={}){
   const h={...(person?{Authorization:'Bearer '+person.token}:{}),...(partyId?{'X-Acting-Party':partyId}:{}),...headers};
   if(body!==undefined)h['Content-Type']=Buffer.isBuffer(body)?'application/octet-stream':'application/json';
   const r=await fetch(base+url,{method,headers:h,...(body===undefined?{}:{body:Buffer.isBuffer(body)?body:JSON.stringify(body)})});
   const raw=await r.arrayBuffer(),isJson=(r.headers.get('content-type')||'').includes('application/json');return {status:r.status,headers:r.headers,body:isJson?JSON.parse(Buffer.from(raw).toString()):Buffer.from(raw)};
  }
  const capture=(r,schema)=>{assert.equal(r.status,200,JSON.stringify(r.body));fixtures.push({schema,value:r.body});return r.body.data;};
  async function upload(purpose,person=author,text='synthetic private bytes '+key(),op=key()){
   return capture(await request('POST','/assets?purpose='+purpose+'&media_type=text%2Fplain',person,Buffer.from(text),person.personal_party_id,{'Idempotency-Key':op}),'SupplyAssetResponse');
  }
  const {createRuleContent,digest}=require('../src/modules/governance/content');
  const proof=await upload('RIGHTS_EVIDENCE'),script=await upload('WORK_CONTENT',author,'Synthetic script line one\nSecond script line'),otherProof=await upload('RIGHTS_EVIDENCE',outsider);
  let profile=await repo.createProfile(author.ctx,{party_id:author.personal_party_id,display_name:'author',description:'synthetic',evidence_asset_ids:[proof.id],previous_profile_id:null,operation_key:key()});
  await repo.reviewProfile(rights.ctx,{record_id:profile.id,expected_version:1,decision:'APPROVED',reason:'synthetic',operation_key:key()});
  const workInput={party_id:author.personal_party_id,work_id:null,previous_version_id:null,title:'synthetic work',kind:'ORIGINAL',source_version_id:null,project_id:null,content_asset_id:script.id,evidence_ids:[proof.id],credits:[{party_id:author.personal_party_id,role:'RIGHTS_HOLDER',evidence_asset_ids:[proof.id]}]};
  async function approvedWork(input=workInput){let w=await repo.createVersion(author.ctx,{...input,operation_key:key()});w=await repo.changeVersion(author.ctx,{party_id:author.personal_party_id,record_id:w.id,expected_version:1,action:'SUBMIT',reason:null,operation_key:key()});for(const [channel,person] of [['RIGHTS',rights],['CONTENT',content]])w=await repo.reviewVersion(person.ctx,{record_id:w.id,expected_version:w.object_version,channel,decision:'APPROVED',reason:'synthetic',operation_key:key()});return w;}
  const w=await approvedWork(),ruleId=key(),rule=createRuleContent({id:ruleId,rule_key:'license.synthetic',version:'1',terms:{explicit:'test-only terms'}});
  await db.execute("INSERT INTO governance_rules(id,rule_key,version_label,content_json,effective_at,created_by,current_status) VALUES (?,?,?,?,?,?,?)",[ruleId,'license.synthetic','1',JSON.stringify(rule),'2020-01-01 00:00:00',author.account_id,'EFFECTIVE']);
  const terms=()=>({exclusive:false,rights:['ADAPT','PRODUCE'],purposes:['PRIVATE'],territories:['CN'],languages:['zh'],valid_from:'2020-01-01T00:00:00.000Z',valid_until:'2099-01-01T00:00:00.000Z',development_until:'2098-01-01T00:00:00.000Z',project_limit:1,episode_limit:2,terms_text:'Synthetic exact rights; no distribution or AI training.'});
  const productInput=()=>({work_version_id:w.id,previous_product_id:null,title:'synthetic license',preview_text:'Approved short preview',terms:terms(),price:{currency:'CNY',amount_minor:12345},payment_due_minor:12345,reservation_minutes:30,rule_id:ruleId});
  async function api(method,url,person=outsider,body,partyId=person?.personal_party_id,headers={}){const h={...(person?{Authorization:'Bearer '+person.token}:{}),...(partyId?{'X-Acting-Party':partyId}:{}),...(method==='POST'?{'Content-Type':'application/json','Idempotency-Key':key()}:{}),...headers};const r=await fetch(base.replace('/supply','/licensing')+url,{method,headers:h,...(body===undefined?{}:{body:JSON.stringify(body)})});const isJson=(r.headers.get('content-type')||'').includes('application/json');return {status:r.status,headers:r.headers,body:isJson?await r.json():Buffer.from(await r.arrayBuffer())};}
  const take=r=>capture(r,'LicenseRecordResponse');
  const review=async row=>take(await api('POST','/records/'+row.id+'/reviews',rights,{decision:'APPROVED',reason:'Verified exact scope, parties, signatures, identity and agreed receipt where applicable',...(row.kind==='EVIDENCE'?{verification:{signed_contract_sha256:row.data.contract_sha256,identity_verified:true,seller_signature_verified:true,buyer_signature_verified:true,currency:'CNY',received_minor:12345,payee_party_id:author.personal_party_id,receipt_ref:'synthetic.receipt.'+row.id}}:{})},null,{'If-Match':'"'+row.object_version+'"'}));
  const product=async(input=productInput())=>review(take(await api('POST','/products',author,input)));
  let listed,reservation,evidence,grant,project,reading;
  await t.test('product requires approved source, explicit conditions and an independent reviewer',async()=>{
   const draft=take(await api('POST','/products',author,productInput()));assert.equal(draft.current_status,'IN_REVIEW');assert.equal((await api('POST','/records/'+draft.id+'/reviews',author,{decision:'APPROVED',reason:'self'},null,{'If-Match':'"1"'})).status,403);listed=await review(draft);assert.equal(listed.current_status,'LISTED');
   assert.equal((await api('POST','/products',outsider,productInput())).status,403);assert.equal((await api('POST','/products',author,{...productInput(),payment_due_minor:999999})).status,400);
  });
  await t.test('catalog is paged and never exposes the private original script',async()=>{const r=await api('GET','/records?kind=PRODUCT&catalog=true&limit=1');capture(r,'LicenseListResponse');assert.equal(r.body.data.items.length,1);assert.ok(!JSON.stringify(r.body).includes('Synthetic script line'));assert.equal((await api('GET','/records?kind=PRODUCT',null)).status,401);});
  await t.test('reservation snapshots exact terms and price with safe repeat requests',async()=>{const op=key();reservation=take(await api('POST','/reservations',outsider,{product_id:listed.id},outsider.personal_party_id,{'Idempotency-Key':op}));const again=take(await api('POST','/reservations',outsider,{product_id:listed.id},outsider.personal_party_id,{'Idempotency-Key':op}));assert.deepEqual(again,reservation);assert.equal(reservation.data.contract.signing_method,'NOT_SIGNED');assert.equal(reservation.data.contract.commitments.price.amount_minor,12345);assert.equal((await api('GET','/records/'+reservation.id,subject)).status,404);});
  const evidenceInput=r=>({reservation_id:r.id,contract_sha256:r.data.contract.content_sha256,seller_signature_asset_id:proof.id,buyer_signature_asset_id:otherProof.id,identity_asset_id:otherProof.id,payment_asset_id:otherProof.id,external_reference:'synthetic.external.receipt'});
  await t.test('uploading evidence never activates a license; foreign or mismatched evidence rejected',async()=>{assert.equal((await api('POST','/evidence',outsider,{...evidenceInput(reservation),contract_sha256:'0'.repeat(64)})).status,409);evidence=take(await api('POST','/evidence',outsider,evidenceInput(reservation)));assert.equal(evidence.current_status,'IN_REVIEW');assert.equal((await api('POST','/reservations/'+reservation.id+'/activation',rights,{evidence_id:evidence.id,reason:'unreviewed'},null,{'If-Match':'"1"'})).status,409);});
  await t.test('reviewer can fetch the linked private evidence, outsiders cannot',async()=>{const url='/evidence/'+evidence.id+'/assets/'+otherProof.id+'/content';assert.equal((await api('GET',url,rights,undefined,null)).status,200);assert.equal((await api('GET',url,subject,undefined,null)).status,403);assert.equal((await api('GET','/evidence/'+evidence.id+'/assets/'+script.id+'/content',rights,undefined,null)).status,404);});
  await t.test('approval requires explicit matching signature identity amount and recipient verification',async()=>{
   const verification={signed_contract_sha256:evidence.data.contract_sha256,identity_verified:true,seller_signature_verified:true,buyer_signature_verified:true,currency:'CNY',received_minor:12345,payee_party_id:author.personal_party_id,receipt_ref:'synthetic.receipt.'+evidence.id};
   for(const change of [{identity_verified:false},{buyer_signature_verified:false},{currency:'USD'},{received_minor:1},{payee_party_id:outsider.personal_party_id},{signed_contract_sha256:'0'.repeat(64)}])assert.equal((await api('POST','/records/'+evidence.id+'/reviews',rights,{decision:'APPROVED',reason:'invalid checks',verification:{...verification,...change}},null,{'If-Match':'"1"'})).status,409);
   assert.equal((await api('POST','/records/'+evidence.id+'/reviews',rights,{decision:'APPROVED',reason:'missing checks'},null,{'If-Match':'"1"'})).status,400);
  });
  let tradePayment,tradeRepo;
  await t.test('linked license order must actually receive its license fee before issuing the grant',async()=>{
   for(const action of ['TRADE_REVIEW','TRADE_REFUND'])await maintainOperatorGrant(db,{account_id:rights.account_id,action,enabled:true,expires_at:null,expected_version:0,authority_ref:'synthetic:test',reason:'isolated trade integration'});
   tradeRepo=require('../src/modules/trade/repository').createTradeRepository(db,{resolvePrincipal});
   const input={party_id:author.personal_party_id,previous_spec_id:null,title:'License fee',provider_party_id:author.personal_party_id,line_kind:'LICENSE',unit_minor:12345,currency:'CNY',specification:{version:'1',service_tier:'License only',sample_seconds:0,final_seconds:0,revision_limit:0,deliverables:['License'],terms:'Synthetic'},operation_key:key()};
   let s=await tradeRepo.createSpec(author.ctx,input);s=await tradeRepo.review(rights.ctx,{record_id:s.id,expected_version:1,decision:'APPROVED',reason:'synthetic',operation_key:key()});
   let q=await tradeRepo.quote(author.ctx,{party_id:author.personal_party_id,buyer_party_id:outsider.personal_party_id,lines:[{line_id:'license',spec_id:s.id,quantity:1}],installments:[{key:'fee',trigger:'ORDER_ACCEPTED',allocations:[{line_id:'license',amount_minor:12345}],apple_product_id:null}],channel:'ALIPAY',transaction_model:'DIRECT_SUPPLIER',rule_id:ruleId,expires_at:'2099-01-01T00:00:00.000Z',payment_window_minutes:30,license_reservation_id:reservation.id,operation_key:key()});
   q=await tradeRepo.review(rights.ctx,{record_id:q.id,expected_version:1,decision:'APPROVED',reason:'synthetic',operation_key:key()});
   const order=await tradeRepo.accept(outsider.ctx,{record_id:q.id,party_id:outsider.personal_party_id,expected_version:q.object_version,quote_sha256:q.content_sha256,operation_key:key()});
   assert.equal((await api('POST','/reservations/'+reservation.id+'/activation',rights,{evidence_id:evidence.id,reason:'no payment'},null,{'If-Match':'"1"'})).body.error.code,'LICENSE_PAYMENT_NOT_READY');
   tradePayment=await tradeRepo.preparePayment(outsider.ctx,{party_id:outsider.personal_party_id,order_id:order.id,installment_key:'fee',operation_key:key()},{provider:'ALIPAY',environment:'SANDBOX',app_id:'synthetic.app',merchant_id:'synthetic.seller',merchant_party_id:author.personal_party_id,config_revision:'test'});
   await tradeRepo.applyPayment({...tradePayment.data,payment_id:tradePayment.id,transaction_id:'synthetic.license.tx',status:'SUCCEEDED',product_id:null,app_account_token:null});
  });
  await t.test('independent evidence approval permits one grant, not a fabricated payment transaction',async()=>{evidence=await review(evidence);const op=key();grant=take(await api('POST','/reservations/'+reservation.id+'/activation',rights,{evidence_id:evidence.id,reason:'verified external conditions'},null,{'If-Match':'"1"','Idempotency-Key':op}));assert.equal(grant.current_status,'ACTIVE');assert.equal(evidence.data.payment_channel_result,'NOT_REPORTED');assert.deepEqual(take(await api('POST','/reservations/'+reservation.id+'/activation',rights,{evidence_id:evidence.id,reason:'verified external conditions'},null,{'If-Match':'"1"','Idempotency-Key':op})),grant);});
  await t.test('the same external receipt cannot issue another license',async()=>{
   const r=take(await api('POST','/reservations',outsider,{product_id:listed.id})),e=take(await api('POST','/evidence',outsider,evidenceInput(r)));
   take(await api('POST','/records/'+e.id+'/reviews',rights,{decision:'APPROVED',reason:'synthetic reused receipt',verification:{...evidence.data.review.verification,signed_contract_sha256:r.data.contract.content_sha256}},null,{'If-Match':'"1"'}));
   const failed=await api('POST','/reservations/'+r.id+'/activation',rights,{evidence_id:e.id,reason:'receipt duplicate'},null,{'If-Match':'"1"'});assert.equal(failed.status,409);assert.equal(failed.body.error.code,'RECEIPT_ALREADY_USED');
  });
  await t.test('unlisting and later prices do not rewrite an acquired license',async()=>{const replacement=await product({...productInput(),previous_product_id:listed.id,price:{currency:'CNY',amount_minor:22222}});assert.equal(replacement.data.price.amount_minor,22222);take(await api('POST','/records/'+listed.id+'/closures',author,{reason:'retired price'},author.personal_party_id,{'If-Match':'"2"'}));assert.equal((await api('POST','/reservations',subject,{product_id:listed.id})).status,409);assert.deepEqual(take(await api('GET','/records/'+grant.id)),grant);});
  await t.test('real project binding enforces purpose and quota under concurrent requests',async()=>{const projectInput={title:'Synthetic project',purpose:'PRIVATE',territory:'CN',language:'zh',episodes:1};project=take(await api('POST','/projects',outsider,{project:projectInput}));const second=take(await api('POST','/projects',outsider,{project:{...projectInput,title:'other'}}));const bad=take(await api('POST','/projects',outsider,{project:{...projectInput,purpose:'RELEASE'}}));assert.equal((await api('POST','/grants/'+grant.id+'/bindings',outsider,{project_id:bad.id},outsider.personal_party_id,{'If-Match':'"1"'})).status,409);const results=await Promise.all([project,second].map(p=>api('POST','/grants/'+grant.id+'/bindings',outsider,{project_id:p.id},outsider.personal_party_id,{'If-Match':'"1"'})));assert.deepEqual(results.map(r=>r.status).sort(),[200,409]);project=results[0].status===200?project:second;take(results.find(r=>r.status===200));});
  await t.test('project adaptation is enabled only for the bound recipient and approved source',async()=>{const buyerRepo=createSupplyRepository(db,{resolvePrincipal,verifyProjectSource:require('../src/modules/licensing/repository').validBinding});let p=await buyerRepo.createProfile(outsider.ctx,{party_id:outsider.personal_party_id,display_name:'buyer',description:'synthetic',evidence_asset_ids:[otherProof.id],previous_profile_id:null,operation_key:key()});await buyerRepo.reviewProfile(rights.ctx,{record_id:p.id,expected_version:1,decision:'APPROVED',reason:'synthetic',operation_key:key()});const buyerScript=await upload('WORK_CONTENT',outsider,'synthetic adaptation');const input={...workInput,party_id:outsider.personal_party_id,kind:'PROJECT_ADAPTATION',project_id:project.id,source_version_id:w.id,content_asset_id:buyerScript.id,evidence_ids:[otherProof.id],credits:[{party_id:outsider.personal_party_id,role:'RIGHTS_HOLDER',evidence_asset_ids:[otherProof.id]}],operation_key:key()};const {party_id,operation_key,...httpBody}=input;const response=await request('POST','/work-versions',outsider,httpBody,party_id,{'Idempotency-Key':operation_key});const r=capture(response,'SupplyRecordResponse');assert.equal(r.data.version.content.source_version_id,w.id);await assert.rejects(()=>buyerRepo.createVersion(outsider.ctx,{...input,project_id:key(),operation_key:key()}),e=>e.code==='PROJECT_LICENSE_NOT_READY');});
  await t.test('verified license fee refund immediately prevents further project adaptations',async()=>{
   let r=await tradeRepo.requestRefund(outsider.ctx,{party_id:outsider.personal_party_id,payment_id:tradePayment.id,allocations:[{line_id:'license',amount_minor:12345}],reason:'synthetic',operation_key:key()});
   r=await tradeRepo.review(rights.ctx,{record_id:r.id,expected_version:1,decision:'APPROVED',reason:'synthetic',operation_key:key()});await tradeRepo.claim(rights.ctx,r.id,null,'REFUND');
   await tradeRepo.applyRefund(r.id,{...r.data,refund_id:r.id,status:'SUCCEEDED'});
   assert.equal(await db.withTransaction(tx=>require('../src/modules/licensing/repository').validBinding(tx,{party_id:outsider.personal_party_id,source:w,project_id:project.id})),false);
  });
  await t.test('same original across different versions prevents concurrent exclusive sales',async()=>{const other=await approvedWork({...workInput,title:'Different original'}),next=await approvedWork({...workInput,work_id:other.stream_ref,previous_version_id:other.id,title:'Different original revised'});const a=await product({...productInput(),work_version_id:other.id,terms:{...terms(),exclusive:true}}),b=await product({...productInput(),work_version_id:next.id,terms:{...terms(),exclusive:true}});const rows=await Promise.all([a,b].map(p=>api('POST','/reservations',outsider,{product_id:p.id})));assert.deepEqual(rows.map(r=>r.status).sort(),[200,409]);});
  await t.test('active nonexclusive grant blocks a later exclusive sale in the same scope',async()=>{const exclusive=await product({...productInput(),terms:{...terms(),exclusive:true}});assert.equal((await api('POST','/reservations',subject,{product_id:exclusive.id})).status,409);});
  await t.test('late evidence cannot reactivate an expired hold',async()=>{const p=await product(),r=take(await api('POST','/reservations',outsider,{product_id:p.id}));const changed={...r.data,expires_at:'2020-01-01T00:00:00.000Z'};await db.execute('UPDATE license_records SET data_json=?,data_sha256=? WHERE id=?',[JSON.stringify(changed),digest(changed),r.id]);const result=take(await api('POST','/reservations/'+r.id+'/activation',rights,{evidence_id:key(),reason:'late receipt needs separate remediation'},null,{'If-Match':'"1"'}));assert.equal(result.current_status,'REVIEW_REQUIRED');});
  await t.test('controlled reading requires named account, independent approval and watermark on actual text',async()=>{reading=take(await api('POST','/readings',author,{work_version_id:w.id,reader_account_id:outsider.account_id,reader_party_id:outsider.personal_party_id,valid_until:'2099-01-01T00:00:00.000Z',basis_type:'NDA',basis_asset_id:proof.id}));assert.equal((await api('GET','/readings/'+reading.id+'/content')).status,403);reading=await review(reading);const r=await api('GET','/readings/'+reading.id+'/content');capture(r,'LicenseReadingResponse');assert.ok(r.body.data.watermarked_text.includes(outsider.account_id));assert.ok(r.body.data.watermarked_text.includes('Synthetic script line'));assert.equal(r.body.data.allows_generation,false);assert.equal((await api('GET','/readings/'+reading.id+'/content',subject)).status,403);const [[audit]]=await db.execute("SELECT COUNT(*) n FROM license_audit WHERE record_id=? AND event_code='CONTROLLED_READING_DELIVERED'",[reading.id]);assert.equal(Number(audit.n),1);});
  await t.test('expired or corrupt reading never delivers private text',async()=>{
   const old=reading.data,expired={...old,valid_until:'2020-01-01T00:00:00.000Z'};await db.execute('UPDATE license_records SET data_json=?,data_sha256=? WHERE id=?',[JSON.stringify(expired),digest(expired),reading.id]);assert.equal((await api('GET','/readings/'+reading.id+'/content')).status,403);await db.execute('UPDATE license_records SET data_json=?,data_sha256=? WHERE id=?',[JSON.stringify(old),digest(old),reading.id]);
   const [[asset]]=await db.execute('SELECT object_key FROM supply_assets WHERE id=?',[script.id]),bytes=files.get(asset.object_key);files.set(asset.object_key,Buffer.from('wrong content'));assert.equal((await api('GET','/readings/'+reading.id+'/content')).status,503);files.set(asset.object_key,bytes);
  });
  await t.test('reading expiry and revocation take effect without exposing original file URLs',async()=>{take(await api('POST','/records/'+reading.id+'/closures',author,{reason:'evaluation ended'},author.personal_party_id,{'If-Match':'"2"'}));assert.equal((await api('GET','/readings/'+reading.id+'/content')).status,403);});
  await t.test('suspension preserves contract and prevents subsequent adaptation',async()=>{grant=take(await api('POST','/grants/'+grant.id+'/suspensions',rights,{reason:'rights dispute'},null,{'If-Match':'"1"'}));assert.equal(grant.current_status,'SUSPENDED');assert.equal(grant.data.contract.commitments.price.amount_minor,12345);const ok=await db.withTransaction(tx=>require('../src/modules/licensing/repository').validBinding(tx,{party_id:outsider.personal_party_id,source:w,project_id:project.id}));assert.equal(ok,false);});
  await t.test('audit failure rolls back commands and catalog writes',async()=>{await db.withConnection(c=>c.query("CREATE TRIGGER license_audit_fail BEFORE INSERT ON license_audit FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='synthetic audit failure'"));try{const [[before]]=await db.execute('SELECT COUNT(*) n FROM license_records');assert.equal((await api('POST','/products',author,productInput())).status,503);const [[after]]=await db.execute('SELECT COUNT(*) n FROM license_records');assert.equal(after.n,before.n);}finally{await db.withConnection(c=>c.query('DROP TRIGGER license_audit_fail'));}});
  await t.test('revoked operator cannot reuse prior authorization',async()=>{await maintainOperatorGrant(db,{account_id:rights.account_id,action:'LICENSE_REVIEW',enabled:false,expires_at:null,expected_version:1,authority_ref:'synthetic:test',reason:'revoked'});assert.equal((await api('GET','/records/'+grant.id,rights,undefined,null)).status,403);});
  const out=path.resolve(__dirname,'../../../..','.local/licensing-http-fixtures.json');await fs.mkdir(path.dirname(out),{recursive:true});await fs.writeFile(out,JSON.stringify({synthetic_only:true,cases:fixtures},null,2));
 }finally{if(server)await new Promise(resolve=>{server.close(resolve);server.closeAllConnections();});if(db)await db.close();await control.query('DROP DATABASE '+mysql.escapeId(name));await control.end();}
});
