 'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');
const {randomUUID:key,randomBytes,createHash}=require('node:crypto'),mysql=require('mysql2/promise');
const {openDatabase}=require('../src/infrastructure/database'),{migrate}=require('../src/infrastructure/database/migrator');
const {createPartyRepository}=require('../src/modules/party/repository'),{createAuthRepository}=require('../src/modules/auth/repository');
const {createSupplyRepository}=require('../src/modules/works/repository'),{createSupplyAssets}=require('../src/modules/works/assets');
const {maintainOperatorGrant}=require('../src/modules/governance/operator-access'),{createAccountApi}=require('../src/http/account-api');
const {createTradeRepository}=require('../src/modules/trade/repository'),{createRuleContent,digest}=require('../src/modules/governance/content');
const {productionPaymentGate}=require('../src/modules/production/payment-gate');
test('production actual HTTP: private versions, explicit acceptance and payment gates',{skip:!process.env.JX_MYSQL_TEST_ENV_FILE},async t=>{
 const env=JSON.parse(await fs.readFile(process.env.JX_MYSQL_TEST_ENV_FILE,'utf8'));assert.equal(env.NODE_ENV,'test');assert.equal(env.MYSQL_HOST,'127.0.0.1');assert.equal(env.MYSQL_DATABASE,'jx_dev');
 const name=`jx_test_${process.pid}_${randomBytes(6).toString('hex')}`,control=await mysql.createConnection({host:env.MYSQL_HOST,port:Number(env.MYSQL_PORT),user:env.MYSQL_USER,password:env.MYSQL_PASSWORD,database:env.MYSQL_DATABASE});let db,server;
 try{
 await control.query('CREATE DATABASE '+mysql.escapeId(name)+' CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin');db=await openDatabase({...env,MYSQL_DATABASE:name});await migrate(db);
 const principals=new Map(),resolvePrincipal=async ctx=>principals.get(ctx),parties=createPartyRepository(db,{resolvePrincipal}),secret=randomBytes(32).toString('base64'),auth=createAuthRepository(db,{secret}),supply=createSupplyRepository(db,{resolvePrincipal}),trade=createTradeRepository(db,{resolvePrincipal,fulfillmentGate:productionPaymentGate});
 const people=[];for(const label of ['producer','buyer','reviewer','outsider']){const ctx={};principals.set(ctx,{subject_ref:'synthetic:'+key()});const p={ctx,...await parties.registerAccount(ctx,{display_name:label}),token:randomBytes(32).toString('base64url')};people.push(p);await db.execute('INSERT INTO auth_sessions(token_hash,account_id,expires_ms) VALUES (?,?,ROUND(UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000)+3600000)',[auth.secure.digest('token',p.token),p.account_id]);}
 const [producer,buyer,reviewer,outsider]=people;for(const person of [reviewer,producer])for(const action of ['TRADE_REVIEW','PRODUCTION_REVIEW','SUPPLY_REVIEW_PROFILE','SUPPLY_REVIEW_RIGHTS','SUPPLY_REVIEW_CONTENT','SUPPLY_REVIEW_CONSENT'])await maintainOperatorGrant(db,{account_id:person.account_id,action,enabled:true,expires_at:null,expected_version:0,authority_ref:'synthetic:test',reason:'isolated test'});
 let holdUpload=null;const files=new Map(),storageFactory=()=>({async put({key,body}){if(holdUpload)await holdUpload();files.set(key,Buffer.from(body));return {key,size:body.length,sha256:createHash('sha256').update(body).digest('hex')};},async getBuffer(key){return files.get(key);}}),assets=createSupplyAssets({db,repository:supply,storageFactory});
 const upload=purpose=>assets.upload(producer.ctx,{party_id:producer.personal_party_id,purpose,media_type:'text/plain',body:Buffer.from('synthetic '+purpose),operation_key:key()});
 const proof=await upload('RIGHTS_EVIDENCE'),script=await upload('WORK_CONTENT'),avatarMaterial=await upload('AVATAR_MATERIAL'),consentEvidence=await upload('CONSENT_EVIDENCE');const avatar=await supply.createAvatar(producer.ctx,{party_id:producer.personal_party_id,display_name:'synthetic',material_asset_ids:[avatarMaterial.id],operation_key:key()});let consent=await supply.createConsent(producer.ctx,{consent:{avatar_id:avatar.id,subject_party_id:producer.personal_party_id,features:['FACE'],purposes:['PRIVATE','AI_TRAIN'],territories:['CN'],valid_from:'2020-01-01T00:00:00.000Z',valid_until:'2099-01-01T00:00:00.000Z',terms:'Synthetic consent',evidence_asset_ids:[consentEvidence.id]},operation_key:key()});consent=await supply.reviewConsent(reviewer.ctx,{record_id:consent.id,expected_version:1,decision:'APPROVED',reason:'synthetic',operation_key:key()});let profile=await supply.createProfile(producer.ctx,{party_id:producer.personal_party_id,display_name:'synthetic',description:'synthetic',evidence_asset_ids:[proof.id],previous_profile_id:null,operation_key:key()});await supply.reviewProfile(reviewer.ctx,{record_id:profile.id,expected_version:1,decision:'APPROVED',reason:'synthetic',operation_key:key()});
 let work=await supply.createVersion(producer.ctx,{party_id:producer.personal_party_id,work_id:null,previous_version_id:null,title:'Synthetic original',kind:'ORIGINAL',source_version_id:null,project_id:null,content_asset_id:script.id,evidence_ids:[proof.id],credits:[{party_id:producer.personal_party_id,role:'RIGHTS_HOLDER',evidence_asset_ids:[proof.id]}],operation_key:key()});work=await supply.changeVersion(producer.ctx,{party_id:producer.personal_party_id,record_id:work.id,expected_version:1,action:'SUBMIT',reason:null,operation_key:key()});for(const channel of ['RIGHTS','CONTENT'])work=await supply.reviewVersion(reviewer.ctx,{record_id:work.id,expected_version:work.object_version,channel,decision:'APPROVED',reason:'synthetic',operation_key:key()});
 const ruleId=key(),rule=createRuleContent({id:ruleId,rule_key:'production.test',version:'1',terms:{explicit:'synthetic only'}});await db.execute('INSERT INTO governance_rules(id,rule_key,version_label,content_json,effective_at,created_by,current_status) VALUES (?,?,?,?,?,?,?)',[ruleId,'production.test','1',JSON.stringify(rule),'2020-01-01 00:00:00',producer.account_id,'EFFECTIVE']);
 const reviewTrade=r=>trade.review(reviewer.ctx,{record_id:r.id,expected_version:r.object_version,decision:'APPROVED',reason:'synthetic',operation_key:key()});
 const spec=await reviewTrade(await trade.createSpec(producer.ctx,{party_id:producer.personal_party_id,previous_spec_id:null,title:'Synthetic production',provider_party_id:producer.personal_party_id,line_kind:'PRODUCTION',unit_minor:10000,currency:'CNY',specification:{version:'1',service_tier:'test',sample_seconds:20,final_seconds:90,revision_limit:2,deliverables:['Synthetic film with reviewed script audio and marks'],terms:'synthetic terms'},operation_key:key()}));
 const quote=await reviewTrade(await trade.quote(producer.ctx,{party_id:producer.personal_party_id,buyer_party_id:buyer.personal_party_id,lines:[{line_id:'film',spec_id:spec.id,quantity:1}],installments:[{key:'first',trigger:'ORDER_ACCEPTED',allocations:[{line_id:'film',amount_minor:4000}],apple_product_id:null},{key:'last',trigger:'FINAL_ACCEPTED',allocations:[{line_id:'film',amount_minor:6000}],apple_product_id:null}],channel:'ALIPAY',transaction_model:'DIRECT_SUPPLIER',rule_id:ruleId,expires_at:'2099-01-01T00:00:00.000Z',payment_window_minutes:30,license_reservation_id:null,operation_key:key()}));
 const order=await trade.accept(buyer.ctx,{record_id:quote.id,party_id:buyer.personal_party_id,expected_version:quote.object_version,quote_sha256:quote.content_sha256,operation_key:key()}),config={provider:'ALIPAY',environment:'SANDBOX',app_id:'test.app',merchant_id:'test.merchant',merchant_party_id:producer.personal_party_id,config_revision:'test'};
 async function pay(step){const p=await trade.preparePayment(buyer.ctx,{party_id:buyer.personal_party_id,order_id:order.id,installment_key:step,operation_key:key()},config);await trade.applyPayment({...config,payment_id:p.id,currency:'CNY',amount_minor:p.data.amount_minor,transaction_id:'test.'+p.id,status:'SUCCEEDED',product_id:null,app_account_token:null});return p;}
 let enabled=false,submits=0,queries=0;const upstream=new Map(),provider={async descriptor(){return {provider_code:'synthetic.long-lived',environment:'SANDBOX',config_revision:'test'};},async assertReady(){if(!enabled)throw Error('not configured');},async readiness(){return {current_status:enabled?'SERVICE_READY':'NOT_ENABLED',reason_code:enabled?null:'PROVIDER_NOT_IMPLEMENTED',...await this.descriptor()};},async submit(input){submits++;upstream.set(input.request_key,input);return {request_key:input.request_key,status:'PENDING',task_id:'task.'+input.request_key};},async query(input){queries++;assert.ok(upstream.has(input.request_key));return {request_key:input.request_key,status:'SUCCEEDED',asset_type:'LONG_LIVED_AVATAR',asset_ref:'synthetic.asset',result_ref:'synthetic.result',deleted:true};}};
 server=createAccountApi({db,secret,supplyStorageFactory:storageFactory,productionProviderFactory:()=>provider}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port+'/api/v1/production',fixtures=[];
 async function api(method,url,person=producer,body,party=person?.personal_party_id,headers={}){const r=await fetch(base+url,{method,headers:{...(person?{Authorization:'Bearer '+person.token}:{}),...(party?{'X-Acting-Party':party}:{}),...(method==='POST'?{'Content-Type':Buffer.isBuffer(body)?'application/octet-stream':'application/json','Idempotency-Key':key()}:{}),...headers},...(body===undefined?{}:{body:Buffer.isBuffer(body)?body:JSON.stringify(body)})});return {status:r.status,body:(r.headers.get('content-type')||'').includes('application/json')?await r.json():Buffer.from(await r.arrayBuffer())};}
 const take=(r,schema='ProductionRecordResponse')=>{assert.equal(r.status,200,JSON.stringify(r.body));fixtures.push({schema,value:r.body});return r.body.data;};
 const get=id=>api('GET','/records/'+id).then(take);
 const checks=stage=>stage==='SCRIPT'?{script_reviewed:true}:{script_reviewed:true,specification_reviewed:true,audio_reviewed:true,branding_reviewed:true};
 let project,scriptV,sample,final,first;
 const projectInput={order_id:order.id,line_id:'film',script_version_id:work.id,license_project_id:null,assignee_account_id:producer.account_id,purpose:'PRIVATE',territory:'CN',consent_ids:[consent.id],evidence_asset_id:proof.id};
 async function review(row){return take(await api('POST','/records/'+row.id+'/reviews',reviewer,{decision:'APPROVED',reason:'synthetic manual review',verification:row.kind==='PROJECT'?{contract_sha256:row.data.contract_sha256,identity_verified:true,signatures_verified:true,rights_verified:true}:checks(row.data.stage)},null,{'If-Match':'"'+row.object_version+'"'}));}
 async function uploadFile(stage,text){return take(await api('POST','/projects/'+project.id+'/files?media_type='+encodeURIComponent(stage==='SCRIPT'?'text/plain':'video/mp4'),producer,Buffer.from(text)));}
 async function deliver(stage){const f=await uploadFile(stage,'synthetic unverified media '+key()),preview=stage==='FINAL'?await uploadFile(stage,'synthetic preview '+key()):f,p=await get(project.id);return review(take(await api('POST','/projects/'+p.id+'/versions',producer,{stage,file_id:f.id,preview_file_id:preview.id,note:'synthetic delivery'},producer.personal_party_id,{'If-Match':'"'+p.object_version+'"'})));}
 async function accept(v,decision='ACCEPT'){return take(await api('POST','/versions/'+v.id+'/feedback',buyer,{decision,note:'synthetic review',checklist:decision==='ACCEPT'?checks(v.data.stage):null},buyer.personal_party_id,{'If-Match':'"'+v.object_version+'"'}));}
 await t.test('one project per order line; project approval is independent and requires evidence',async()=>{project=take(await api('POST','/projects',producer,projectInput));assert.equal(project.current_status,'IN_REVIEW');assert.equal((await api('POST','/projects',producer,projectInput)).status,409);assert.equal((await api('GET','/records/'+project.id,outsider)).status,404);assert.equal((await api('POST','/records/'+project.id+'/reviews',producer,{decision:'APPROVED',reason:'self',verification:{}},null,{'If-Match':'"1"'})).status,403);assert.equal((await api('GET','/projects/'+project.id+'/evidence',reviewer,undefined,null)).status,200);project=await review(project);});
 await t.test('no production before agreed first payment; final payment stays closed',async()=>{assert.equal((await api('POST','/projects/'+project.id+'/files?media_type=text%2Fplain',producer,Buffer.from('unpaid'))).status,409);await assert.rejects(()=>pay('last'),e=>e.code==='PAYMENT_MILESTONE_NOT_MET');first=await pay('first');});
 await t.test('private upload retries return same file; outsiders and unassigned buyer cannot upload',async()=>{const bytes=Buffer.from('synthetic'),op=key(),url='/projects/'+project.id+'/files?media_type=text%2Fplain';const a=take(await api('POST',url,producer,bytes,producer.personal_party_id,{'Idempotency-Key':op}));assert.equal(take(await api('POST',url,producer,bytes,producer.personal_party_id,{'Idempotency-Key':op})).id,a.id);assert.equal((await api('POST',url,buyer,bytes)).status,403);});
 await t.test('simultaneous upload retries do not write the same private object twice',async()=>{let entered,release;const started=new Promise(r=>entered=r),wait=new Promise(r=>release=r);holdUpload=async()=>{entered();await wait;};const op=key(),url='/projects/'+project.id+'/files?media_type=text%2Fplain',body=Buffer.from('synthetic concurrent upload'),h={'Idempotency-Key':op};const firstRequest=api('POST',url,producer,body,producer.personal_party_id,h);try{await started;assert.equal((await api('POST',url,producer,body,producer.personal_party_id,h)).status,409);}finally{release();holdUpload=null;}take(await firstRequest);});
 await t.test('script acceptance precedes sample; customer cannot accept unpublished or old version',async()=>{scriptV=await deliver('SCRIPT');const p=await get(project.id),f=await uploadFile('SAMPLE','synthetic');assert.equal((await api('POST','/projects/'+p.id+'/versions',producer,{stage:'SAMPLE',file_id:f.id,preview_file_id:f.id,note:'too early'},producer.personal_party_id,{'If-Match':'"'+p.object_version+'"'})).status,409);await accept(scriptV);sample=await deliver('SAMPLE');await accept(sample);});
 await t.test('unconfigured long-lived provider stays visibly disabled and queues no fake success',async()=>{const p=await get(project.id);take(await api('GET','/projects/'+p.id+'/generation-readiness'),'ProductionReadinessResponse');assert.equal((await api('POST','/projects/'+p.id+'/generation',producer,{operation:'CREATE_LONG_LIVED',avatar_id:avatar.id,asset_id:null,consent_id:consent.id},producer.personal_party_id,{'If-Match':'"'+p.object_version+'"'})).status,503);assert.equal(submits,0);});
 await t.test('durable generation recovers by original key after lost worker lease without resubmission',async()=>{
  enabled=true;const p=await get(project.id);const reduced={...consent.data,consent:{...consent.data.consent,purposes:['PRIVATE']}};await db.execute('UPDATE supply_records SET data_json=?,data_sha256=? WHERE id=?',[JSON.stringify(reduced),digest(reduced),consent.id]);assert.equal((await api('POST','/projects/'+p.id+'/generation',producer,{operation:'CREATE_LONG_LIVED',avatar_id:avatar.id,asset_id:null,consent_id:consent.id},producer.personal_party_id,{'If-Match':'"'+p.object_version+'"'})).body.error.code,'AI_TRAIN_CONSENT_REQUIRED');await db.execute('UPDATE supply_records SET data_json=?,data_sha256=? WHERE id=?',[JSON.stringify(consent.data),digest(consent.data),consent.id]);const request=take(await api('POST','/projects/'+p.id+'/generation',producer,{operation:'CREATE_LONG_LIVED',avatar_id:avatar.id,asset_id:null,consent_id:consent.id},producer.personal_party_id,{'If-Match':'"'+p.object_version+'"'}));
  const jobs=require('../src/infrastructure/jobs/repository').createJobRepository(db),handlers=require('../src/modules/production/handlers').createProductionHandlers(db,{provider}),first=await jobs.claim('synthetic.first',1000),handler=handlers.get(first.task_type);assert.equal(first.id,request.data.job_id);
  assert.equal((await handler.execute(first,{saveProviderTask:id=>jobs.saveProviderTask(first,id)})).status,'RETRY');assert.equal(submits,1);
  await db.execute('UPDATE platform_jobs SET lease_until=TIMESTAMPADD(SECOND,-1,CURRENT_TIMESTAMP(6)) WHERE id=?',[first.id]);const worker=require('../src/worker/runner').createWorker({repository:jobs,handlers});await worker.tick();assert.equal(submits,1);assert.equal(queries,1);
  const completed=await get(request.id);assert.equal(completed.current_status,'SUCCEEDED');const mapped=await get(completed.data.result.asset_id);assert.equal(mapped.current_status,'READY');assert.equal(mapped.data.asset_type,'LONG_LIVED_AVATAR');
  take(await api('GET','/generations/'+request.id+'/job'),'ProductionJobResponse');
  const repo=require('../src/modules/production/repository').createProductionRepository(db);await assert.rejects(()=>repo.saveJobObservation(first,{status:'SUCCEEDED',asset_type:'LONG_LIVED_AVATAR',asset_ref:'stale'}),e=>e.code==='LEASE_LOST');
  const render=take(await api('POST','/projects/'+p.id+'/generation',producer,{operation:'RENDER',avatar_id:avatar.id,asset_id:mapped.id,consent_id:consent.id},producer.personal_party_id,{'If-Match':'"'+p.object_version+'"'}));
  await worker.tick();await db.execute("UPDATE supply_records SET current_status='WITHDRAWN' WHERE id=?",[consent.id]);await db.execute('UPDATE platform_jobs SET next_run_at=CURRENT_TIMESTAMP(6) WHERE id=?',[render.data.job_id]);await worker.tick();assert.equal((await jobs.get(render.data.job_id)).status,'BLOCKED');assert.equal(queries,1);
  await repo.markConsentWithdrawal(consent.id);assert.equal((await get(mapped.id)).current_status,'DELETE_REQUIRED');
  // Restore only this synthetic fixture so later independent delivery tests remain meaningful.
  await db.execute("UPDATE supply_records SET current_status='APPROVED' WHERE id=?",[consent.id]);
  const deletion=take(await api('POST','/projects/'+p.id+'/generation',producer,{operation:'DELETE_LONG_LIVED',avatar_id:avatar.id,asset_id:mapped.id,consent_id:consent.id},producer.personal_party_id,{'If-Match':'"'+p.object_version+'"'}));await worker.tick();await db.execute('UPDATE platform_jobs SET next_run_at=CURRENT_TIMESTAMP(6) WHERE id=?',[deletion.data.job_id]);await worker.tick();assert.equal((await get(mapped.id)).current_status,'DELETED');
  const retryOp=key();const retried=take(await api('POST','/generations/'+render.id+'/retry',reviewer,{reason_ref:'synthetic.audit'},null,{'Idempotency-Key':retryOp}));assert.equal(retried.current_status,'QUEUED');take(await api('POST','/generations/'+render.id+'/retry',reviewer,{reason_ref:'synthetic.audit'},null,{'Idempotency-Key':retryOp}));await worker.tick();assert.equal((await jobs.get(render.data.job_id)).status,'BLOCKED');assert.equal(submits,3);
  enabled=false;
 });
 await t.test('new sample invalidates previous confirmation; feedback versions are not overwritten',async()=>{const old=sample;await accept(await get(sample.id),'REQUEST_CHANGES');assert.equal((await get(project.id)).data.change_requests,1);sample=await deliver('SAMPLE');assert.equal((await get(project.id)).data.accepted.SAMPLE,undefined);assert.equal((await api('POST','/versions/'+old.id+'/feedback',buyer,{decision:'ACCEPT',note:'old',checklist:checks('SAMPLE')},buyer.personal_party_id,{'If-Match':'"'+(await get(old.id)).object_version+'"'})).status,409);await accept(sample);});
 await t.test('concurrent decisions use version check; only buyer can accept',async()=>{const rough=await deliver('ROUGH_CUT'),body={decision:'ACCEPT',note:'concurrent',checklist:checks('ROUGH_CUT')},headers={'If-Match':'"'+rough.object_version+'"'};assert.equal((await api('POST','/versions/'+rough.id+'/feedback',producer,body,producer.personal_party_id,headers)).status,403);const results=await Promise.all([1,2].map(()=>api('POST','/versions/'+rough.id+'/feedback',buyer,body,buyer.personal_party_id,headers)));assert.deepEqual(results.map(x=>x.status).sort(),[200,412]);take(results.find(x=>x.status===200));});
 await t.test('final acceptance and final delivery are separate; tail cannot unlock itself',async()=>{final=await deliver('FINAL');assert.equal((await api('GET','/versions/'+final.id+'/content?variant=preview',buyer)).status,200);assert.equal((await api('GET','/versions/'+final.id+'/content?variant=final',buyer)).status,409);await assert.rejects(()=>pay('last'),e=>e.code==='PAYMENT_MILESTONE_NOT_MET');await accept(final);assert.equal((await get(project.id)).current_status,'ACCEPTED');await pay('last');assert.equal((await api('GET','/versions/'+final.id+'/content?variant=final',buyer)).status,200);});
 await t.test('completed delivery cannot be silently replaced by producer',async()=>{const f=await uploadFile('FINAL','synthetic new final'),p=await get(project.id);assert.equal((await api('POST','/projects/'+p.id+'/versions',producer,{stage:'FINAL',file_id:f.id,preview_file_id:f.id,note:'replace'},producer.personal_party_id,{'If-Match':'"'+p.object_version+'"'})).status,409);});
 await t.test('private bytes verified and permission rechecked before download',async()=>{const v=await get(final.data.preview_file_id),old=files.get(v.data.object_key);files.set(v.data.object_key,Buffer.from('tampered'));assert.equal((await api('GET','/versions/'+final.id+'/content?variant=preview',buyer)).status,503);files.set(v.data.object_key,old);assert.equal((await api('GET','/versions/'+final.id+'/content?variant=preview',outsider)).status,404);});
 await t.test('reassigning a producer requires current membership and project version',async()=>{const p=await get(project.id);assert.equal((await api('POST','/projects/'+p.id+'/assignment',producer,{assignee_account_id:outsider.account_id,reason:'wrong organization'},producer.personal_party_id,{'If-Match':'"'+p.object_version+'"'})).status,409);take(await api('POST','/projects/'+p.id+'/assignment',producer,{assignee_account_id:producer.account_id,reason:'keep current assignee'},producer.personal_party_id,{'If-Match':'"'+p.object_version+'"'}));});
 await t.test('audit failure rolls back a production mutation and idempotency key',async()=>{await db.withConnection(c=>c.query("CREATE TRIGGER production_audit_fail BEFORE INSERT ON production_audit FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='synthetic'"));try{const p=await get(project.id);assert.equal((await api('POST','/projects/'+p.id+'/assignment',producer,{assignee_account_id:producer.account_id,reason:'must rollback'},producer.personal_party_id,{'If-Match':'"'+p.object_version+'"'})).status,503);assert.equal((await get(project.id)).object_version,p.object_version);}finally{await db.withConnection(c=>c.query('DROP TRIGGER production_audit_fail'));}});
 await t.test('refund blocks further delivery even though historical acceptance is retained',async()=>{let r=await trade.requestRefund(buyer.ctx,{party_id:buyer.personal_party_id,payment_id:first.id,allocations:[{line_id:'film',amount_minor:1}],reason:'test',operation_key:key()});await maintainOperatorGrant(db,{account_id:reviewer.account_id,action:'TRADE_REFUND',enabled:true,expires_at:null,expected_version:0,authority_ref:'synthetic:test',reason:'isolated'});r=await reviewTrade(r);await trade.claim(reviewer.ctx,r.id,null,'REFUND');await trade.applyRefund(r.id,{...r.data,refund_id:r.id,status:'SUCCEEDED'});assert.equal((await api('GET','/versions/'+final.id+'/content?variant=final',buyer)).status,409);assert.equal((await get(project.id)).data.accepted.FINAL,final.id);});
 take(await api('GET','/projects/'+project.id+'/records?kind=VERSION&limit=1'),'ProductionListResponse');take(await api('GET','/projects?limit=1'),'ProductionListResponse');
 const out=path.resolve(__dirname,'../../../..','.local/production-http-fixtures.json');await fs.mkdir(path.dirname(out),{recursive:true});await fs.writeFile(out,JSON.stringify({synthetic_only:true,cases:fixtures},null,2));
 }finally{if(server)await new Promise(r=>{server.close(r);server.closeAllConnections();});if(db)await db.close();await control.query('DROP DATABASE '+mysql.escapeId(name));await control.end();}
});
