 'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');
const {randomUUID:key,randomBytes,createHash}=require('node:crypto'),mysql=require('mysql2/promise');
const {openDatabase}=require('../src/infrastructure/database'),{migrate}=require('../src/infrastructure/database/migrator');
const {createPartyRepository}=require('../src/modules/party/repository'),{createAuthRepository}=require('../src/modules/auth/repository');
const {createSupplyRepository}=require('../src/modules/works/repository'),{createSupplyAssets}=require('../src/modules/works/assets');
const {maintainOperatorGrant}=require('../src/modules/governance/operator-access'),{createAccountApi}=require('../src/http/account-api');
const {createTradeRepository}=require('../src/modules/trade/repository'),{createRuleContent,digest}=require('../src/modules/governance/content');
const {productionPaymentGate}=require('../src/modules/production/payment-gate');
test('projects actual HTTP: cast, version approval and external release evidence',{skip:!process.env.JX_MYSQL_TEST_ENV_FILE},async t=>{
 const env=JSON.parse(await fs.readFile(process.env.JX_MYSQL_TEST_ENV_FILE,'utf8'));assert.equal(env.NODE_ENV,'test');assert.equal(env.MYSQL_HOST,'127.0.0.1');assert.equal(env.MYSQL_DATABASE,'jx_dev');
 const name=`jx_test_${process.pid}_${randomBytes(6).toString('hex')}`,control=await mysql.createConnection({host:env.MYSQL_HOST,port:Number(env.MYSQL_PORT),user:env.MYSQL_USER,password:env.MYSQL_PASSWORD,database:env.MYSQL_DATABASE});let db,server;
 try{
 await control.query('CREATE DATABASE '+mysql.escapeId(name)+' CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin');db=await openDatabase({...env,MYSQL_DATABASE:name});await t.test('existing stage 7 and stage 8 schemas upgrade in order without rewriting applied migrations',async()=>{
 const source=path.resolve(__dirname,'../migrations/mysql-runtime'),root=path.resolve(__dirname,'../../../..','.local'),directory=await fs.mkdtemp(path.join(root,'project-upgrade-'));const copied=[];
 try{const names=(await fs.readdir(source)).filter(x=>x.endsWith('.sql')).sort();for(const boundary of ['0054','0062']){for(const name of names.filter(n=>n.slice(0,4)<=boundary&&!copied.includes(n))){await fs.copyFile(path.join(source,name),path.join(directory,name));copied.push(name);}await migrate(db,{directory});const [rows]=await db.execute("SELECT MAX(version) AS version FROM platform_schema_migrations WHERE status='APPLIED'");assert.equal(rows[0].version,boundary);}await migrate(db);const [rows]=await db.execute("SELECT MAX(version) AS version FROM platform_schema_migrations WHERE status='APPLIED'");assert.equal(rows[0].version,'0068');await migrate(db);
 }finally{for(const name of copied)await fs.unlink(path.join(directory,name));await fs.rmdir(directory);}
 });
 const principals=new Map(),resolvePrincipal=async ctx=>principals.get(ctx),parties=createPartyRepository(db,{resolvePrincipal}),secret=randomBytes(32).toString('base64'),auth=createAuthRepository(db,{secret}),supply=createSupplyRepository(db,{resolvePrincipal,verifyProjectSource:require('../src/modules/licensing/repository').validBinding}),trade=createTradeRepository(db,{resolvePrincipal,fulfillmentGate:productionPaymentGate});
 const people=[];for(const label of ['producer','buyer','reviewer','outsider']){const ctx={};principals.set(ctx,{subject_ref:'synthetic:'+key()});const p={ctx,...await parties.registerAccount(ctx,{display_name:label}),token:randomBytes(32).toString('base64url')};people.push(p);await db.execute('INSERT INTO auth_sessions(token_hash,account_id,expires_ms) VALUES (?,?,ROUND(UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000)+3600000)',[auth.secure.digest('token',p.token),p.account_id]);}
 const [producer,buyer,reviewer,outsider]=people;for(const person of [reviewer,producer])for(const action of ['PROJECT_REVIEW','TRADE_REVIEW','PRODUCTION_REVIEW','SUPPLY_REVIEW_PROFILE','SUPPLY_REVIEW_RIGHTS','SUPPLY_REVIEW_CONTENT','SUPPLY_REVIEW_CONSENT'])await maintainOperatorGrant(db,{account_id:person.account_id,action,enabled:true,expires_at:null,expected_version:0,authority_ref:'synthetic:test',reason:'isolated test'});
 let holdUpload=null;const files=new Map(),storageFactory=()=>({async put({key,body}){if(holdUpload)await holdUpload();files.set(key,Buffer.from(body));return {key,size:body.length,sha256:createHash('sha256').update(body).digest('hex')};},async getBuffer(key){return files.get(key);}}),assets=createSupplyAssets({db,repository:supply,storageFactory});
 const upload=purpose=>assets.upload(producer.ctx,{party_id:producer.personal_party_id,purpose,media_type:'text/plain',body:Buffer.from('synthetic '+purpose),operation_key:key()});
 const proof=await upload('RIGHTS_EVIDENCE'),script=await upload('WORK_CONTENT'),avatarMaterial=await upload('AVATAR_MATERIAL'),consentEvidence=await upload('CONSENT_EVIDENCE');const avatar=await supply.createAvatar(producer.ctx,{party_id:producer.personal_party_id,display_name:'synthetic',material_asset_ids:[avatarMaterial.id],operation_key:key()});let consent=await supply.createConsent(producer.ctx,{consent:{avatar_id:avatar.id,subject_party_id:producer.personal_party_id,features:['FACE'],purposes:['PRIVATE','AI_TRAIN','PUBLIC_SHARE','RELEASE'],territories:['CN'],valid_from:'2020-01-01T00:00:00.000Z',valid_until:'2099-01-01T00:00:00.000Z',terms:'Synthetic consent',evidence_asset_ids:[consentEvidence.id]},operation_key:key()});consent=await supply.reviewConsent(reviewer.ctx,{record_id:consent.id,expected_version:1,decision:'APPROVED',reason:'synthetic',operation_key:key()});let profile=await supply.createProfile(producer.ctx,{party_id:producer.personal_party_id,display_name:'synthetic',description:'synthetic',evidence_asset_ids:[proof.id],previous_profile_id:null,operation_key:key()});await supply.reviewProfile(reviewer.ctx,{record_id:profile.id,expected_version:1,decision:'APPROVED',reason:'synthetic',operation_key:key()});
 let work=await supply.createVersion(producer.ctx,{party_id:producer.personal_party_id,work_id:null,previous_version_id:null,title:'Synthetic original',kind:'ORIGINAL',source_version_id:null,project_id:null,content_asset_id:script.id,evidence_ids:[proof.id],credits:[{party_id:producer.personal_party_id,role:'RIGHTS_HOLDER',evidence_asset_ids:[proof.id]}],operation_key:key()});work=await supply.changeVersion(producer.ctx,{party_id:producer.personal_party_id,record_id:work.id,expected_version:1,action:'SUBMIT',reason:null,operation_key:key()});for(const channel of ['RIGHTS','CONTENT'])work=await supply.reviewVersion(reviewer.ctx,{record_id:work.id,expected_version:work.object_version,channel,decision:'APPROVED',reason:'synthetic',operation_key:key()});
 const ruleId=key(),rule=createRuleContent({id:ruleId,rule_key:'production.test',version:'1',terms:{explicit:'synthetic only'}});await db.execute('INSERT INTO governance_rules(id,rule_key,version_label,content_json,effective_at,created_by,current_status) VALUES (?,?,?,?,?,?,?)',[ruleId,'production.test','1',JSON.stringify(rule),'2020-01-01 00:00:00',producer.account_id,'EFFECTIVE']);
 const reviewTrade=r=>trade.review(reviewer.ctx,{record_id:r.id,expected_version:r.object_version,decision:'APPROVED',reason:'synthetic',operation_key:key()});
 const spec=await reviewTrade(await trade.createSpec(producer.ctx,{party_id:producer.personal_party_id,previous_spec_id:null,title:'Synthetic production',provider_party_id:producer.personal_party_id,line_kind:'PRODUCTION',unit_minor:10000,currency:'CNY',specification:{version:'1',service_tier:'test',sample_seconds:20,final_seconds:90,revision_limit:2,deliverables:['Synthetic film with reviewed script audio and marks'],terms:'synthetic terms'},operation_key:key()}));
 const quote=await reviewTrade(await trade.quote(producer.ctx,{party_id:producer.personal_party_id,buyer_party_id:buyer.personal_party_id,lines:[{line_id:'film',spec_id:spec.id,quantity:1}],installments:[{key:'first',trigger:'ORDER_ACCEPTED',allocations:[{line_id:'film',amount_minor:4000}],apple_product_id:null},{key:'last',trigger:'FINAL_ACCEPTED',allocations:[{line_id:'film',amount_minor:6000}],apple_product_id:null}],channel:'ALIPAY',transaction_model:'DIRECT_SUPPLIER',rule_id:ruleId,expires_at:'2099-01-01T00:00:00.000Z',payment_window_minutes:30,license_reservation_id:null,operation_key:key()}));
 const order=await trade.accept(buyer.ctx,{record_id:quote.id,party_id:buyer.personal_party_id,expected_version:quote.object_version,quote_sha256:quote.content_sha256,operation_key:key()}),config={provider:'ALIPAY',environment:'SANDBOX',app_id:'test.app',merchant_id:'test.merchant',merchant_party_id:producer.personal_party_id,config_revision:'test'};
 async function pay(step){const p=await trade.preparePayment(buyer.ctx,{party_id:buyer.personal_party_id,order_id:order.id,installment_key:step,operation_key:key()},config);await trade.applyPayment({...config,payment_id:p.id,currency:'CNY',amount_minor:p.data.amount_minor,transaction_id:'test.'+p.id,status:'SUCCEEDED',product_id:null,app_account_token:null});return p;}
 let enabled=false,submits=0,queries=0;const upstream=new Map(),provider={async descriptor(){return {provider_code:'synthetic.long-lived',environment:'SANDBOX',config_revision:'test'};},async assertReady(){if(!enabled)throw Error('not configured');},async readiness(){return {current_status:enabled?'SERVICE_READY':'NOT_ENABLED',reason_code:enabled?null:'PROVIDER_NOT_IMPLEMENTED',...await this.descriptor()};},async submit(input){submits++;upstream.set(input.request_key,input);return {request_key:input.request_key,status:'PENDING',task_id:'task.'+input.request_key};},async query(input){queries++;assert.ok(upstream.has(input.request_key));return {request_key:input.request_key,status:'SUCCEEDED',asset_type:'LONG_LIVED_AVATAR',asset_ref:'synthetic.asset',result_ref:'synthetic.result',deleted:true};}};
 let privateConsent=await supply.createConsent(producer.ctx,{consent:{...consent.data.consent,purposes:['PRIVATE']},operation_key:key()});privateConsent=await supply.reviewConsent(reviewer.ctx,{record_id:privateConsent.id,expected_version:1,decision:'APPROVED',reason:'synthetic private production only',operation_key:key()});
 server=createAccountApi({db,secret,supplyStorageFactory:storageFactory,productionProviderFactory:()=>provider}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port+'/api/v1/production',fixtures=[];
 async function api(method,url,person=producer,body,party=person?.personal_party_id,headers={}){const r=await fetch(base+url,{method,headers:{...(person?{Authorization:'Bearer '+person.token}:{}),...(party?{'X-Acting-Party':party}:{}),...(method==='POST'?{'Content-Type':Buffer.isBuffer(body)?'application/octet-stream':'application/json','Idempotency-Key':key()}:{}),...headers},...(body===undefined?{}:{body:Buffer.isBuffer(body)?body:JSON.stringify(body)})});return {status:r.status,body:(r.headers.get('content-type')||'').includes('application/json')?await r.json():Buffer.from(await r.arrayBuffer())};}
 const productionTake=(r,schema='ProductionRecordResponse')=>{assert.equal(r.status,200,JSON.stringify(r.body));return r.body.data;};
 const get=id=>api('GET','/records/'+id).then(productionTake);
 const checks=stage=>stage==='SCRIPT'?{script_reviewed:true}:{script_reviewed:true,specification_reviewed:true,audio_reviewed:true,branding_reviewed:true};
 let project,scriptV,sample,final,first;
 const projectInput={order_id:order.id,line_id:'film',script_version_id:work.id,license_project_id:null,assignee_account_id:producer.account_id,purpose:'PRIVATE',territory:'CN',consent_ids:[privateConsent.id],evidence_asset_id:proof.id};
 async function review(row){return productionTake(await api('POST','/records/'+row.id+'/reviews',reviewer,{decision:'APPROVED',reason:'synthetic manual review',verification:row.kind==='PROJECT'?{contract_sha256:row.data.contract_sha256,identity_verified:true,signatures_verified:true,rights_verified:true}:checks(row.data.stage)},null,{'If-Match':'"'+row.object_version+'"'}));}
 async function uploadFile(stage,text){return productionTake(await api('POST','/projects/'+project.id+'/files?media_type='+encodeURIComponent(stage==='SCRIPT'?'text/plain':'video/mp4'),producer,Buffer.from(text)));}
 async function deliver(stage){const f=await uploadFile(stage,'synthetic unverified media '+key()),preview=stage==='FINAL'?await uploadFile(stage,'synthetic preview '+key()):f,p=await get(project.id);return review(productionTake(await api('POST','/projects/'+p.id+'/versions',producer,{stage,file_id:f.id,preview_file_id:preview.id,note:'synthetic delivery'},producer.personal_party_id,{'If-Match':'"'+p.object_version+'"'})));}
 async function accept(v,decision='ACCEPT'){return productionTake(await api('POST','/versions/'+v.id+'/feedback',buyer,{decision,note:'synthetic review',checklist:decision==='ACCEPT'?checks(v.data.stage):null},buyer.personal_party_id,{'If-Match':'"'+v.object_version+'"'}));}

 // Build a real paid production through public HTTP; upstream media/payments remain synthetic.
 project=productionTake(await api('POST','/projects',producer,projectInput));project=await review(project);await pay('first');scriptV=await deliver('SCRIPT');await accept(scriptV);sample=await deliver('SAMPLE');await accept(sample);await accept(await deliver('ROUGH_CUT'));final=await deliver('FINAL');await accept(final);await pay('last');
 const buyerProof=await assets.upload(buyer.ctx,{party_id:buyer.personal_party_id,purpose:'RIGHTS_EVIDENCE',media_type:'text/plain',body:Buffer.from('synthetic release rights'),operation_key:key()});
 const root=base.replace('/production','/projects');
 async function call(method,url,person=buyer,body,party=person?.personal_party_id,headers={}){const r=await fetch(root+url,{method,headers:{...(person?{Authorization:'Bearer '+person.token}:{}),...(party?{'X-Acting-Party':party}:{}),...(method==='POST'?{'Content-Type':'application/json','Idempotency-Key':key()}:{}),...headers},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:r.status,body:(r.headers.get('content-type')||'').includes('application/json')?await r.json():Buffer.from(await r.arrayBuffer())};}
 const take=(r,schema='ProjectRecordResponse')=>{assert.equal(r.status,200,JSON.stringify(r.body));fixtures.push({schema,value:r.body});return r.body.data;};
 const read=(r,person=buyer,party=person.personal_party_id)=>call('GET','/records/'+(r.id||r),person,undefined,party).then(take);
 const post=(url,row,body,person=buyer,party=person.personal_party_id,headers={})=>call('POST',url,person,body,party,{'If-Match':'"'+row.object_version+'"',...headers});
 const decision=(row,act,person=buyer)=>post('/candidates/'+row.id+'/decisions',row,{decision:act,content_sha256:row.content_sha256,reason:'synthetic explicit decision'},person);
 const verification=kind=>Object.fromEntries(require('../src/modules/projects/release').APPROVAL_CHECKS[kind].map(k=>[k,true]));
 const rev=(row,decision='APPROVED',person=reviewer)=>post('/records/'+row.id+'/reviews',row,{decision,reason:'synthetic independent evidence review',verification:verification(row.kind)},person,null);
 const confirm=(row,person)=>post('/records/'+row.id+'/confirmations',row,{content_sha256:row.content_sha256,decision:'APPROVED',reason:'synthetic version confirmation'},person);
 const target={purpose:'RELEASE',territory:'CN',language:'zh',valid_until:'2090-01-01T00:00:00.000Z'};
 let film,role,candidate,plan,edition,channel,release;
 await t.test('authenticated catalogue and explicit public scope; private purpose does not imply release',async()=>{assert.equal((await call('GET','/catalogue',null)).status,401);assert.equal((await call('POST','/projects',buyer,{title:'Invalid',scope:{...target,purpose:'PRIVATE'}})).status,400);film=take(await call('POST','/projects',buyer,{title:'Synthetic public project',scope:target}));role=take(await post('/projects/'+film.id+'/roles',film,{title:'Lead',capacity:1,pricing:'FIXED',amount_minor:0,terms:'explicit zero fee fixture'}));const list=take(await call('GET','/catalogue',outsider),'ProjectCatalogueResponse');assert.ok(list.items.find(x=>x.id===film.id).roles.some(x=>x.id===role.id));assert.equal((await call('GET','/records/'+film.id,outsider)).status,404);});
 await t.test('inviting someone does not enlist them; only their current owner can accept',async()=>{candidate=take(await post('/roles/'+role.id+'/invitations',role,{invitee_party_id:producer.personal_party_id}));assert.equal(candidate.current_status,'INVITED');const input={decision:'ACCEPT',avatar_id:avatar.id,consent_id:consent.id,amount_minor:0,note:'explicit invitation acceptance'};assert.equal((await post('/candidates/'+candidate.id+'/responses',candidate,input,outsider)).status,403);candidate=take(await post('/candidates/'+candidate.id+'/responses',candidate,input,producer));assert.equal(candidate.current_status,'APPLIED');assert.equal((await post('/roles/'+role.id+'/applications',role,{avatar_id:avatar.id,consent_id:consent.id,amount_minor:0,note:'duplicate'},producer)).status,409);});
 await t.test('selection and final confirmation are separate; self-selection is forbidden',async()=>{assert.equal((await decision(candidate,'SELECT',producer)).status,403);candidate=take(await decision(candidate,'SELECT'));assert.equal(candidate.current_status,'SELECTED');assert.equal((await decision(candidate,'CONFIRM',buyer)).status,403);candidate=take(await decision(candidate,'CONFIRM',producer));assert.equal(candidate.current_status,'CONFIRMED');});
 const planInput=()=>({production_project_id:project.id,rights:require('../src/modules/projects/policy').LAYERS.map(layer=>({layer,holder_party_id:producer.personal_party_id,evidence_asset_id:buyerProof.id,purpose:target.purpose,territory:target.territory,valid_until:target.valid_until,terms:'synthetic explicit '+layer+' terms'})),confirmers:[{party_id:producer.personal_party_id,responsibility:'all six explicit rights',after_party_ids:[]},{party_id:buyer.personal_party_id,responsibility:'project sponsor',after_party_ids:[producer.personal_party_id]}],funding:[],terms:'synthetic versioned project agreement'});

 await t.test('parallel selection reserves only one role slot and outsiders never see another application',async()=>{
  const material=await assets.upload(outsider.ctx,{party_id:outsider.personal_party_id,purpose:'AVATAR_MATERIAL',media_type:'text/plain',body:Buffer.from('synthetic second face'),operation_key:key()}),ev=await assets.upload(outsider.ctx,{party_id:outsider.personal_party_id,purpose:'CONSENT_EVIDENCE',media_type:'text/plain',body:Buffer.from('synthetic consent'),operation_key:key()});
  const av=await supply.createAvatar(outsider.ctx,{party_id:outsider.personal_party_id,display_name:'other fixture',material_asset_ids:[material.id],operation_key:key()});let co=await supply.createConsent(outsider.ctx,{consent:{...consent.data.consent,avatar_id:av.id,subject_party_id:outsider.personal_party_id,evidence_asset_ids:[ev.id]},operation_key:key()});co=await supply.reviewConsent(reviewer.ctx,{record_id:co.id,expected_version:1,decision:'APPROVED',reason:'synthetic',operation_key:key()});
  const p=take(await call('POST','/projects',buyer,{title:'Concurrent casting',scope:target})),r=take(await post('/projects/'+p.id+'/roles',p,{title:'Only one place',capacity:1,pricing:'QUOTE',amount_minor:null,terms:'quoted terms'}));
  const c1=take(await post('/roles/'+r.id+'/applications',r,{avatar_id:avatar.id,consent_id:consent.id,amount_minor:0,note:'first'},producer)),c2=take(await post('/roles/'+r.id+'/applications',r,{avatar_id:av.id,consent_id:co.id,amount_minor:0,note:'second'},outsider));
  const results=await Promise.all([c1,c2].map(x=>decision(x,'SELECT')));assert.deepEqual(results.map(x=>x.status).sort(),[200,409]);take(results.find(x=>x.status===200));assert.equal((await call('GET','/records/'+c1.id,outsider)).status,404);assert.equal(take(await call('GET','/projects/'+p.id+'/records?kind=CANDIDATE',outsider),'ProjectListResponse').items.length,1);
 });
 await t.test('expired or private-only consent blocks public use without changing historical terms',async()=>{
  for(const patch of [{purposes:['PRIVATE']},{valid_until:'2021-01-01T00:00:00.000Z'}]){const changed={...consent.data,consent:{...consent.data.consent,...patch}};await db.execute('UPDATE supply_records SET data_json=?,data_sha256=? WHERE id=?',[JSON.stringify(changed),digest(changed),consent.id]);try{assert.equal(take(await call('GET','/projects/'+film.id+'/readiness'),'ProjectReadinessResponse').current_status,'BLOCKED');film=await read(film);assert.equal((await post('/projects/'+film.id+'/plans',film,planInput())).status,409);}finally{await db.execute('UPDATE supply_records SET data_json=?,data_sha256=? WHERE id=?',[JSON.stringify(consent.data),digest(consent.data),consent.id]);}}
 });
 await t.test('private exclusive script license remains non-distributable through the real license and production gates',async()=>{
  for(const action of ['LICENSE_REVIEW'])await maintainOperatorGrant(db,{account_id:reviewer.account_id,action,enabled:true,expires_at:null,expected_version:0,authority_ref:'synthetic:test',reason:'isolated'});
  const license=require('../src/modules/licensing/repository').createLicensingRepository(db,{resolvePrincipal}),lr=async(r,verification=null)=>license.review(reviewer.ctx,{record_id:r.id,expected_version:r.object_version,decision:'APPROVED',reason:'synthetic',verification,operation_key:key()});
  const terms={exclusive:true,rights:['ADAPT','PRODUCE'],purposes:['PRIVATE'],territories:['CN'],languages:['zh'],valid_from:'2020-01-01T00:00:00.000Z',valid_until:'2099-01-01T00:00:00.000Z',development_until:'2098-01-01T00:00:00.000Z',project_limit:1,episode_limit:1,terms_text:'Exclusive PRIVATE only, no distribution'};
  const prod=await lr(await license.createProduct(producer.ctx,{party_id:producer.personal_party_id,work_version_id:work.id,previous_product_id:null,title:'Synthetic exclusive private',preview_text:'short',terms,price:{currency:'CNY',amount_minor:1},payment_due_minor:1,reservation_minutes:30,rule_id:ruleId,operation_key:key()})),res=await license.reserve(buyer.ctx,{party_id:buyer.personal_party_id,product_id:prod.id,operation_key:key()});
  let ev=await license.submitEvidence(buyer.ctx,{party_id:buyer.personal_party_id,reservation_id:res.id,contract_sha256:res.data.contract.content_sha256,seller_signature_asset_id:proof.id,buyer_signature_asset_id:buyerProof.id,identity_asset_id:buyerProof.id,payment_asset_id:buyerProof.id,external_reference:'synthetic.exclusive.receipt',operation_key:key()});ev=await lr(ev,{signed_contract_sha256:res.data.contract.content_sha256,identity_verified:true,seller_signature_verified:true,buyer_signature_verified:true,currency:'CNY',received_minor:1,payee_party_id:producer.personal_party_id,receipt_ref:'synthetic:'+key()});
  const grant=await license.activate(reviewer.ctx,{record_id:res.id,expected_version:res.object_version,evidence_id:ev.id,reason:'synthetic manual external receipt',operation_key:key()}),lp=await license.createProject(buyer.ctx,{party_id:buyer.personal_party_id,project:{title:'Private licensed project',purpose:'PRIVATE',territory:'CN',language:'zh',episodes:1},operation_key:key()});await license.bind(buyer.ctx,{party_id:buyer.personal_party_id,record_id:grant.id,expected_version:grant.object_version,project_id:lp.id,operation_key:key()});
  const bp=await supply.createProfile(buyer.ctx,{party_id:buyer.personal_party_id,display_name:'synthetic adapter',description:'synthetic',evidence_asset_ids:[buyerProof.id],previous_profile_id:null,operation_key:key()});await supply.reviewProfile(reviewer.ctx,{record_id:bp.id,expected_version:1,decision:'APPROVED',reason:'synthetic',operation_key:key()});
  const cp=await assets.upload(buyer.ctx,{party_id:buyer.personal_party_id,purpose:'WORK_CONTENT',media_type:'text/plain',body:Buffer.from('synthetic adapted script'),operation_key:key()});let adapted=await supply.createVersion(buyer.ctx,{party_id:buyer.personal_party_id,work_id:null,previous_version_id:null,title:'Licensed adaptation',kind:'PROJECT_ADAPTATION',source_version_id:work.id,project_id:lp.id,content_asset_id:cp.id,evidence_ids:[buyerProof.id],credits:[{party_id:buyer.personal_party_id,role:'RIGHTS_HOLDER',evidence_asset_ids:[buyerProof.id]}],operation_key:key()});adapted=await supply.changeVersion(buyer.ctx,{party_id:buyer.personal_party_id,record_id:adapted.id,expected_version:1,action:'SUBMIT',reason:null,operation_key:key()});for(const channel of ['RIGHTS','CONTENT'])adapted=await supply.reviewVersion(reviewer.ctx,{record_id:adapted.id,expected_version:adapted.object_version,channel,decision:'APPROVED',reason:'synthetic',operation_key:key()});
  // Temporarily attach the fully paid synthetic production to this genuine reviewed private license.
  // This isolates the distribution check; the prior production contract is restored in finally.
  const savedOrder=(await db.execute('SELECT data_json FROM trade_records WHERE id=?',[order.id]))[0][0].data_json,savedProduction=(await db.execute('SELECT data_json FROM production_records WHERE id=?',[project.id]))[0][0].data_json;
  const parse=x=>typeof x==='string'?JSON.parse(x):x,od={...parse(savedOrder),quote:{...parse(savedOrder).quote,license_reservation_id:res.id}},pd={...parse(savedProduction),script_version_id:adapted.id,license_project_id:lp.id};
  await db.execute('UPDATE trade_records SET data_json=?,data_sha256=? WHERE id=?',[JSON.stringify(od),digest(od),order.id]);await db.execute('UPDATE production_records SET data_json=?,data_sha256=? WHERE id=?',[JSON.stringify(pd),digest(pd),project.id]);try{film=await read(film);const denied=await post('/projects/'+film.id+'/plans',film,planInput());assert.equal(denied.body.error.code,'DISTRIBUTION_LICENSE_REQUIRED');}finally{for(const [table,record,data] of [['trade_records',order.id,parse(savedOrder)],['production_records',project.id,parse(savedProduction)]])await db.execute('UPDATE '+table+' SET data_json=?,data_sha256=? WHERE id=?',[JSON.stringify(data),digest(data),record]);}
 });

 await t.test('paid roles need a separate paid order line; production fees cannot be counted twice',async()=>{
  let p=take(await call('POST','/projects',buyer,{title:'Paid cast project',scope:target}));const r=take(await post('/projects/'+p.id+'/roles',p,{title:'Paid role',capacity:1,pricing:'FIXED',amount_minor:10000,terms:'explicit paid role'}));let c=take(await post('/roles/'+r.id+'/applications',r,{avatar_id:avatar.id,consent_id:consent.id,amount_minor:10000,note:'paid application'},producer));c=take(await decision(c,'SELECT'));c=take(await decision(c,'CONFIRM',producer));p=await read(p);
  assert.equal((await post('/projects/'+p.id+'/plans',p,planInput())).body.error.code,'CAST_FUNDING_REQUIRED');assert.equal((await post('/projects/'+p.id+'/plans',p,{...planInput(),funding:[{candidate_id:c.id,order_id:order.id,line_id:'film'}]})).body.error.code,'CAST_FUNDING_NOT_VERIFIED');
  const sp=await reviewTrade(await trade.createSpec(producer.ctx,{party_id:producer.personal_party_id,previous_spec_id:null,title:'Cast fee',provider_party_id:producer.personal_party_id,line_kind:'OTHER',unit_minor:10000,currency:'CNY',specification:spec.data.specification,operation_key:key()})),q=await reviewTrade(await trade.quote(producer.ctx,{party_id:producer.personal_party_id,buyer_party_id:buyer.personal_party_id,lines:[{line_id:'cast',spec_id:sp.id,quantity:1}],installments:[{key:'fee',trigger:'ORDER_ACCEPTED',allocations:[{line_id:'cast',amount_minor:10000}],apple_product_id:null}],channel:'ALIPAY',transaction_model:'DIRECT_SUPPLIER',rule_id:ruleId,expires_at:'2099-01-01T00:00:00.000Z',payment_window_minutes:30,license_reservation_id:null,operation_key:key()})),o=await trade.accept(buyer.ctx,{party_id:buyer.personal_party_id,record_id:q.id,expected_version:q.object_version,quote_sha256:q.content_sha256,operation_key:key()});const funded={...planInput(),funding:[{candidate_id:c.id,order_id:o.id,line_id:'cast'}]};assert.equal((await post('/projects/'+p.id+'/plans',p,funded)).body.error.code,'CAST_FUNDING_NOT_VERIFIED');
  const payment=await trade.preparePayment(buyer.ctx,{party_id:buyer.personal_party_id,order_id:o.id,installment_key:'fee',operation_key:key()},config);await trade.applyPayment({...config,payment_id:payment.id,currency:'CNY',amount_minor:10000,transaction_id:'synthetic:'+payment.id,status:'SUCCEEDED',product_id:null,app_account_token:null});let pl=take(await post('/projects/'+p.id+'/plans',p,funded));pl=take(await rev(pl));take(await confirm(pl,producer));take(await confirm(pl,buyer));p=await read(p);take(await post('/projects/'+p.id+'/start',p,{}));
  const used=(await db.execute('SELECT candidate_id FROM project_funding WHERE order_id=? AND line_id=?',[o.id,'cast']))[0][0];assert.equal(used.candidate_id,c.id);
 });
 await t.test('rights layers, real funding references and all signers are required',async()=>{film=await read(film);for(const change of [{rights:planInput().rights.slice(1)},{confirmers:planInput().confirmers.slice(1)},{confirmers:[...planInput().confirmers,{party_id:outsider.personal_party_id,responsibility:'unrelated veto',after_party_ids:[]}]},{funding:[{candidate_id:key(),order_id:order.id,line_id:'film'}]}])assert.ok([400,409].includes((await post('/projects/'+film.id+'/plans',film,{...planInput(),...change})).status));plan=take(await post('/projects/'+film.id+'/plans',film,planInput()));assert.equal((await rev(plan,'APPROVED',producer)).status,403);plan=take(await rev(plan));});
 await t.test('confirmation order and content hash prevent consenting to another version',async()=>{assert.equal((await confirm(plan,buyer)).status,409);const bad=await post('/records/'+plan.id+'/confirmations',plan,{content_sha256:'0'.repeat(64),decision:'APPROVED',reason:'wrong version'},producer);assert.equal(bad.status,409);take(await confirm(plan,producer));take(await confirm(plan,buyer));take(await call('GET','/records/'+plan.id+'/confirmations'),'ProjectConfirmationsResponse');film=await read(film);film=take(await post('/projects/'+film.id+'/start',film,{}));assert.equal(film.current_status,'STARTED');take(await call('GET','/projects/'+film.id+'/readiness'),'ProjectReadinessResponse');});
 await t.test('edition needs accepted paid final, independent review, and fresh multi-party agreement',async()=>{assert.equal((await post('/projects/'+film.id+'/editions',film,{final_version_id:sample.id,material_asset_ids:[buyerProof.id],note:'sample is not final'})).status,409);edition=take(await post('/projects/'+film.id+'/editions',film,{final_version_id:final.id,material_asset_ids:[buyerProof.id],note:'synthetic release edition'}));edition=take(await rev(edition));assert.equal((await confirm(edition,buyer)).status,409);take(await confirm(edition,producer));take(await confirm(edition,buyer));});
 await t.test('channel evidence is reviewed independently; no external API is silently enabled',async()=>{channel=take(await call('POST','/channels',producer,{name:'Synthetic channel',channel_reference:'synthetic:channel',submission_requirements:'synthetic materials only',evidence_asset_id:proof.id}));assert.equal((await rev(channel,'APPROVED',producer)).status,403);channel=take(await rev(channel));take(await call('GET','/catalogue'),'ProjectCatalogueResponse');});
 const releaseInput=prior=>({channel_id:channel.id,prior_release_id:prior?.id||null,material_asset_ids:[buyerProof.id],note:'synthetic submission'});
 await t.test('internal corrections and rejection preserve attempts; resubmission links predecessor',async()=>{film=await read(film);release=take(await post('/projects/'+film.id+'/releases',film,releaseInput()));release=take(await rev(release,'CHANGES_REQUESTED'));film=await read(film);const second=take(await post('/projects/'+film.id+'/releases',film,releaseInput(release)));release=take(await rev(second,'REJECTED'));film=await read(film);release=take(await post('/projects/'+film.id+'/releases',film,releaseInput(release)));release=take(await rev(release));assert.equal(release.current_status,'READY_TO_SUBMIT');film=await read(film);assert.equal((await post('/projects/'+film.id+'/releases',film,releaseInput())).status,409);});
 const external=async(outcome)=>take(await post('/releases/'+release.id+'/external-events',release,{outcome,external_reference:'synthetic:'+key(),occurred_at:'2020-01-01T00:00:00.000Z',evidence_asset_id:buyerProof.id,note:'synthetic evidence, no actual publishing'}));
 await t.test('claimed external success is pending until independent proof review and valid transition',async()=>{let event=await external('PUBLISHED');assert.equal((await read(release)).current_status,'READY_TO_SUBMIT');assert.equal((await rev(event)).status,409);event=await external('SUBMITTED');assert.equal((await rev(event,'APPROVED',producer)).status,403);take(await rev(event));release=await read(release);assert.equal(release.current_status,'EXTERNAL_SUBMITTED');});
 await t.test('external corrections and rejection each allow a new traceable attempt',async()=>{for(const outcome of ['CHANGES_REQUESTED','REJECTED']){take(await rev(await external(outcome)));release=await read(release);assert.equal(release.current_status,'EXTERNAL_'+outcome);film=await read(film);release=take(await post('/projects/'+film.id+'/releases',film,releaseInput(release)));release=take(await rev(release));take(await rev(await external('SUBMITTED')));release=await read(release);}});
 await t.test('external publication is evidence-based; revoked consent blocks new distribution but allows withdrawal proof',async()=>{take(await rev(await external('PUBLISHED')));release=await read(release);assert.equal(release.current_status,'EXTERNAL_PUBLISHED');await db.execute("UPDATE supply_records SET current_status='WITHDRAWN' WHERE id=?",[consent.id]);const state=take(await call('GET','/projects/'+film.id+'/readiness'),'ProjectReadinessResponse');assert.equal(state.current_status,'BLOCKED');take(await rev(await external('WITHDRAWN')));release=await read(release);assert.equal(release.current_status,'EXTERNAL_WITHDRAWN');await db.execute("UPDATE supply_records SET current_status='APPROVED' WHERE id=?",[consent.id]);});
 await t.test('new edition never inherits old agreements; old edition cannot be confirmed',async()=>{const old=edition;film=await read(film);edition=take(await post('/projects/'+film.id+'/editions',film,{final_version_id:final.id,material_asset_ids:[buyerProof.id],note:'revised materials'}));assert.equal((await confirm(old,buyer)).status,409);edition=take(await rev(edition));film=await read(film);assert.equal((await post('/projects/'+film.id+'/releases',film,releaseInput(release))).status,409);take(await confirm(edition,producer));take(await confirm(edition,buyer));});
 await t.test('private evidence never has a public fallback; outsider and other signer cannot download',async()=>{const url='/records/'+plan.id+'/evidence/'+buyerProof.id;assert.equal((await call('GET',url,outsider)).status,403);assert.equal((await call('GET',url,producer)).status,403);assert.equal((await call('GET',url,reviewer,undefined,null)).status,200);const row=(await db.execute('SELECT * FROM supply_assets WHERE id=?',[buyerProof.id]))[0][0],saved=files.get(row.object_key);files.set(row.object_key,Buffer.from('corrupt'));assert.equal((await call('GET',url)).status,503);files.set(row.object_key,saved);});
 await t.test('audit failure rolls back edits; repeated operations are idempotent and stale versions fail',async()=>{film=await read(film);const op=key(),url='/projects/'+film.id+'/editions',input={final_version_id:final.id,material_asset_ids:[buyerProof.id],note:'repeat'};const one=take(await post(url,film,input,buyer,buyer.personal_party_id,{'Idempotency-Key':op}));assert.equal(take(await post(url,film,input,buyer,buyer.personal_party_id,{'Idempotency-Key':op})).id,one.id);assert.equal((await post(url,film,input)).status,412);film=await read(film);await db.withConnection(c=>c.query("CREATE TRIGGER project_audit_fail BEFORE INSERT ON project_audit FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='synthetic'"));try{assert.equal((await post('/projects/'+film.id+'/cancellation',film,{reason:'rollback'})).status,503);assert.equal((await read(film)).object_version,film.object_version);}finally{await db.withConnection(c=>c.query('DROP TRIGGER project_audit_fail'));}});
 await t.test('membership is checked again after login; a removed owner cannot act using an old token',async()=>{await db.execute("UPDATE party_memberships SET current_status='REVOKED' WHERE party_id=? AND account_id=?",[buyer.personal_party_id,buyer.account_id]);try{assert.equal((await call('GET','/records/'+film.id)).status,403);}finally{await db.execute("UPDATE party_memberships SET current_status='ACTIVE' WHERE party_id=? AND account_id=?",[buyer.personal_party_id,buyer.account_id]);}});
 await t.test('withdrawal preserves history and blocks reuse; cancellation does not pretend to refund',async()=>{candidate=take(await decision(candidate,'WITHDRAW',producer));assert.equal(candidate.current_status,'WITHDRAWN');assert.equal(take(await call('GET','/projects/'+film.id+'/readiness'),'ProjectReadinessResponse').current_status,'BLOCKED');film=await read(film);film=take(await post('/projects/'+film.id+'/cancellation',film,{reason:'synthetic cancelled'}));assert.equal(film.current_status,'CANCELLED');assert.equal((await trade.read(buyer.ctx,{record_id:order.id,party_id:buyer.personal_party_id})).current_status,'PAID');});
 take(await call('GET','/projects/'+film.id+'/records?kind=RELEASE&limit=1'),'ProjectListResponse');take(await call('GET','/projects?limit=1'),'ProjectListResponse');
 const out=path.resolve(__dirname,'../../../..','.local/projects-http-fixtures.json');await fs.mkdir(path.dirname(out),{recursive:true});await fs.writeFile(out,JSON.stringify({synthetic_only:true,cases:fixtures},null,2));
 }finally{if(server)await new Promise(r=>{server.close(r);server.closeAllConnections();});if(db)await db.close();await control.query('DROP DATABASE '+mysql.escapeId(name));await control.end();}
});
