 'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');
const {randomUUID:key,randomBytes}=require('node:crypto'),mysql=require('mysql2/promise');
const {openDatabase}=require('../src/infrastructure/database'),{migrate}=require('../src/infrastructure/database/migrator');
const {createPartyRepository}=require('../src/modules/party/repository'),{createAuthRepository}=require('../src/modules/auth/repository');
const {maintainOperatorGrant}=require('../src/modules/governance/operator-access'),{createAccountApi}=require('../src/http/account-api');
const {createTradeRepository}=require('../src/modules/trade/repository'),{createRuleContent,digest}=require('../src/modules/governance/content');
test('release rehearsal with isolated MySQL, encrypted restore and bounded real HTTP load',{skip:!process.env.JX_MYSQL_TEST_ENV_FILE},async t=>{
 const env=JSON.parse(await fs.readFile(process.env.JX_MYSQL_TEST_ENV_FILE,'utf8'));assert.equal(env.NODE_ENV,'test');assert.equal(env.MYSQL_HOST,'127.0.0.1');assert.equal(env.MYSQL_DATABASE,'jx_dev');
 const name=`jx_test_${process.pid}_${randomBytes(6).toString('hex')}`,control=await mysql.createConnection({host:env.MYSQL_HOST,port:Number(env.MYSQL_PORT),user:env.MYSQL_USER,password:env.MYSQL_PASSWORD,database:env.MYSQL_DATABASE});let db,server;const extraDatabases=[],extraPools=[];
 try{
 await control.query('CREATE DATABASE '+mysql.escapeId(name)+' CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin');db=await openDatabase({...env,MYSQL_DATABASE:name});await migrate(db);
 const principals=new Map(),resolvePrincipal=async ctx=>principals.get(ctx),parties=createPartyRepository(db,{resolvePrincipal}),secret=randomBytes(32).toString('base64'),auth=createAuthRepository(db,{secret}),repo=createTradeRepository(db,{resolvePrincipal});
 const people=[];for(const label of ['seller','buyer','reviewer','stranger']){const ctx={};principals.set(ctx,{subject_ref:'synthetic:'+key()});const p={ctx,...await parties.registerAccount(ctx,{display_name:label}),token:randomBytes(32).toString('base64url')};people.push(p);await db.execute('INSERT INTO auth_sessions(token_hash,account_id,expires_ms) VALUES (?,?,ROUND(UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000)+3600000)',[auth.secure.digest('token',p.token),p.account_id]);}
 const [seller,buyer,reviewer,stranger]=people;for(const person of [reviewer,seller])for(const action of ['TRADE_REVIEW','TRADE_REFUND'])await maintainOperatorGrant(db,{account_id:person.account_id,action,enabled:true,expires_at:null,expected_version:0,authority_ref:'synthetic:test',reason:'isolated test'});
 const ruleId=key(),rule=createRuleContent({id:ruleId,rule_key:'trade.test',version:'1',terms:{explicit:'synthetic only'}});await db.execute('INSERT INTO governance_rules(id,rule_key,version_label,content_json,effective_at,created_by,current_status) VALUES (?,?,?,?,?,?,?)',[ruleId,'trade.test','1',JSON.stringify(rule),'2020-01-01 00:00:00',seller.account_id,'EFFECTIVE']);
 let calls=0,fail=false,ready=true;const proofs=new Map();const config=code=>({provider:code,environment:'SANDBOX',app_id:'synthetic.app',merchant_id:'synthetic.merchant',merchant_party_id:seller.personal_party_id,config_revision:'test'});
 const providersFactory=()=>({get(code){return {config:config(code),async assertReady(){if(!ready)throw Error('not configured');},async call(method,p){if(method==='create'){calls++;if(fail)throw Error('unknown');return code==='ALIPAY'?{kind:'ALIPAY_APP',order_string:'synthetic-only'}:{kind:'APPLE_STOREKIT2',product_id:p.apple_product_id,app_account_token:p.id};}if(method==='refund')return {status:code==='APPLE'?'AWAITING_APPLE_REQUEST':'PENDING'};return proofs.get(p.id);},async refundQuery(r){return {...r,refund_id:r.id,status:'SUCCEEDED'};},async notification(body){if(body.signedPayload!=='synthetic-verified-token'||!proofs.has('notification'))throw Error('unsigned');return proofs.get('notification');}};}});
 const files=new Map(),storageFactory=()=>({async put({key,body}){files.set(key,body);return {key,size:body.length,sha256:require('node:crypto').createHash('sha256').update(body).digest('hex')};},async getBuffer(key){return files.get(key);}});
 server=createAccountApi({db,secret,tradeProvidersFactory:providersFactory,supplyStorageFactory:storageFactory}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port+'/api/v1/trade',fixtures=[];
 async function api(method,url,person=buyer,body,party=person?.personal_party_id,headers={}){const r=await fetch(base+url,{method,headers:{...(person?{Authorization:'Bearer '+person.token}:{}),...(party?{'X-Acting-Party':party}:{}),...(method==='POST'?{'Content-Type':'application/json','Idempotency-Key':key()}:{}),...headers},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:r.status,body:(r.headers.get('content-type')||'').includes('application/json')?await r.json():await r.text()};}
 const take=(r,schema='TradeRecordResponse')=>{assert.equal(r.status,200,JSON.stringify(r.body));fixtures.push({schema,value:r.body});return r.body.data;};
 const review=async r=>take(await api('POST','/records/'+r.id+'/reviews',reviewer,{decision:'APPROVED',reason:'synthetic verified'},null,{'If-Match':'"'+r.object_version+'"'}));
 const specification={version:'1',service_tier:'Explicit synthetic tier',sample_seconds:23,final_seconds:119,revision_limit:2,deliverables:['test artifact'],terms:'No real product terms'};
 let spec,order,payment;
 async function newOrder(channel='ALIPAY',trigger='ORDER_ACCEPTED'){const q=await review(take(await api('POST','/quotes',seller,{buyer_party_id:buyer.personal_party_id,lines:[{line_id:'production',spec_id:spec.id,quantity:1}],installments:[{key:'first',trigger,allocations:[{line_id:'production',amount_minor:500000}],apple_product_id:channel==='APPLE'?'synthetic.product':null}],channel,transaction_model:'DIRECT_SUPPLIER',rule_id:ruleId,expires_at:'2099-01-01T00:00:00.000Z',payment_window_minutes:30,license_reservation_id:null})));return take(await api('POST','/quotes/'+q.id+'/acceptance',buyer,{quote_sha256:q.content_sha256},buyer.personal_party_id,{'If-Match':'"'+q.object_version+'"'}));}
 const start=(o,op=key())=>api('POST','/payments',buyer,{order_id:o.id,installment_key:'first'},buyer.personal_party_id,{'Idempotency-Key':op});
 const proof=p=>({...config(p.data.provider),payment_id:p.id,currency:'CNY',amount_minor:p.data.amount_minor,status:'SUCCEEDED',transaction_id:'synthetic.'+p.id,product_id:p.data.apple_product_id,app_account_token:p.data.provider==='APPLE'?p.id:null});

 spec=await review(take(await api('POST','/specifications',seller,{previous_spec_id:null,title:'Synthetic production',provider_party_id:seller.personal_party_id,line_kind:'PRODUCTION',unit_minor:500000,currency:'CNY',specification})));order=await newOrder();payment=take(await start(order));await repo.applyPayment(proof(payment));

 const B=require('../src/operations/backup'),L=require('../src/operations/legacy'),F=require('../src/operations/data-format'),R=require('../src/operations/release-check');
 const {mysqlReady}=require('../src/http/operations'),{createJobRepository}=require('../src/infrastructure/jobs/repository');
 const fixtureDir=path.resolve(__dirname,'../../../..','.local/release-fixtures',key());await fs.mkdir(fixtureDir,{recursive:true});
 const sqlite=path.join(fixtureDir,'legacy.db'),Database=require('better-sqlite3'),old=new Database(sqlite);
 old.exec("CREATE TABLE original_orders(id INTEGER PRIMARY KEY,intent_amount REAL,production_amount REAL,reported_status TEXT,terms TEXT,proof BLOB); CREATE TABLE old_messages(id INTEGER PRIMARY KEY,body TEXT); INSERT INTO original_orders VALUES(9007199254740993,99,4901,'paid','Original promise 🎬',X'00FF0102'); INSERT INTO old_messages VALUES(1,'retained only');");old.close();
 const startHash=F.hash(await fs.readFile(sqlite));let legacy,saved,back,restored;const encryptionKey=randomBytes(32),evidence={format:'JX_RELEASE_REHEARSAL_V1',synthetic_only:true,production_access:false,paid_services:false,checks:[],metrics:null};
 async function newDatabase(){const n=`jx_test_${process.pid}_${randomBytes(6).toString('hex')}`;await control.query('CREATE DATABASE '+mysql.escapeId(n)+' CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin');extraDatabases.push(n);const x=await openDatabase({...env,MYSQL_DATABASE:n});extraPools.push(x);return x;}
 await t.test('legacy inspection is read-only and retains unsafe-size integers, raw money and binary',async()=>{legacy=L.inspect(sqlite,{source_ref:'synthetic.stage12',source_kind:'SYNTHETIC'});assert.equal(F.hash(await fs.readFile(sqlite)),startHash);const row=legacy.payload.tables.find(t=>t.name==='original_orders').rows[0];assert.equal(row[0].v,'9007199254740993');assert.equal(row[1].v,99);assert.equal(row[2].v,4901);assert.equal(row[3].v,'paid');assert.deepEqual(F.decode(row[5]),Buffer.from([0,255,1,2]));assert.equal(legacy.manifest.verified_payments,0);});
 await t.test('source declaration and active WAL reject before unsafe copy',async()=>{assert.throws(()=>L.inspect(sqlite,{}),{code:'LEGACY_SOURCE_DECLARATION_REQUIRED'});await fs.writeFile(sqlite+'-wal','pending');try{assert.throws(()=>L.inspect(sqlite,{source_ref:'x',source_kind:'SYNTHETIC'}),{code:'LEGACY_WAL_REQUIRES_CLOSED_COPY'});}finally{await fs.unlink(sqlite+'-wal');}});
 await t.test('archiving twice preserves old facts without creating active identities, payment receipts or licenses',async()=>{const [[before]]=await db.execute('SELECT COUNT(*) n FROM trade_journal');saved=await L.retain(db,legacy.payload);assert.equal(saved.current_status,'RETAINED_REVIEW_REQUIRED');assert.equal((await L.retain(db,legacy.payload)).replay,true);const checked=await L.reconcile(db,saved.id);assert.equal(checked.rows,2);assert.equal(checked.verified_payments,0);assert.equal((await db.execute('SELECT COUNT(*) n FROM trade_journal'))[0][0].n,before.n);evidence.checks.push({name:'legacy-retention',...checked});});
 await t.test('concurrent archives converge and manifest tampering is detected',async()=>{const payload={...legacy.payload,source_ref:'synthetic.concurrent'};const copies=await Promise.all([L.retain(db,payload),L.retain(db,payload)]);assert.equal(copies[0].id,copies[1].id);assert.equal(copies.filter(x=>!x.replay).length,1);await db.execute("UPDATE legacy_imports SET manifest_json=JSON_SET(manifest_json,'$.schema',JSON_ARRAY()) WHERE id=?",[copies[0].id]);await assert.rejects(L.reconcile(db,copies[0].id),{code:'LEGACY_MANIFEST_MISMATCH'});await db.execute('UPDATE legacy_imports SET manifest_json=? WHERE id=?',[JSON.stringify(L.manifest(payload)),copies[0].id]);});
 await t.test('modified archive payload fails without partial writes',async()=>{const corrupt=JSON.parse(JSON.stringify(legacy.payload));corrupt.tables[0].rows[0][0].v='2';await assert.rejects(L.retain(db,corrupt),{code:'LEGACY_CHECKSUM_MISMATCH'});});
 await t.test('backup includes immutable payment and pending-job facts',async()=>{await createJobRepository(db).enqueue({task_type:'SYNTHETIC_RECOVERY_TASK',business_key:key(),payload_ref:'synthetic:only',max_attempts:1});await db.execute("INSERT INTO party_invitations(id,party_id,inviter_account_id,invitee_account_id,expires_at) VALUES (?,?,?,?,?)",[key(),seller.personal_party_id,seller.account_id,buyer.account_id,'2030-01-02 03:04:05.123456']);await db.withConnection(c=>c.query('ALTER TABLE ops_audit AUTO_INCREMENT=5000'));await db.execute("UPDATE legacy_imports SET manifest_json=JSON_SET(manifest_json,'$.exact_integer',CAST('9007199254740993' AS JSON)) WHERE id=?",[saved.id]);back=await B.backup(db,{source_ref:'synthetic.stage12'});assert.ok(back.payload.tables.some(t=>t.name==='trade_journal'&&t.row_count===1));assert.ok(back.payload.tables.some(t=>t.name==='legacy_rows'&&t.row_count===4));assert.ok(back.payload.tables.some(t=>t.name==='platform_jobs'&&t.row_count===1));assert.equal(back.manifest.external_object_bytes_included,false);});
 await t.test('encrypted file has no visible business body, rejects wrong key/tamper/truncation and overwrite',async()=>{const file=path.join(fixtureDir,'backup.jxb');await B.writeEncrypted(file,back.payload,encryptionKey);const text=await fs.readFile(file,'utf8');assert.ok(!text.includes('Original promise'));const read=await B.readEncrypted(file,encryptionKey);assert.equal(F.hash(read),back.manifest.payload_sha256);await assert.rejects(B.writeEncrypted(file,back.payload,encryptionKey),{code:'EEXIST'});await assert.rejects(B.readEncrypted(file,randomBytes(32)),{code:'BACKUP_AUTHENTICATION_FAILED'});const blob=JSON.parse(text);blob.tag=Buffer.alloc(16).toString('base64');assert.throws(()=>B.unseal(blob,encryptionKey),{code:'BACKUP_AUTHENTICATION_FAILED'});blob.tag=JSON.parse(text).tag;blob.data=blob.data.slice(0,-8);assert.throws(()=>B.unseal(blob,encryptionKey),{code:'BACKUP_AUTHENTICATION_FAILED'});});
 await t.test('restore to a fresh database matches every row while leaving runtime quarantined',async()=>{restored=await newDatabase();const started=performance.now();const keyFile=path.join(fixtureDir,'restore-key.json');await fs.writeFile(keyFile,JSON.stringify({key_base64:encryptionKey.toString('base64')}),{flag:'wx'});const result=await require('../scripts/release-tools.cjs').main(['restore','--env-file',process.env.JX_MYSQL_TEST_ENV_FILE,'--database',restored.database,'--file',path.join(fixtureDir,'backup.jxb'),'--key-file',keyFile,'--sha256',back.manifest.payload_sha256]);assert.equal(result.result,'MATCHED');assert.equal(result.runtime_status,'QUARANTINED');assert.equal(await mysqlReady(restored)(),false);await assert.rejects(require('../src/http/main').main({...env,MYSQL_DATABASE:restored.database,PORT:'0'}),/MYSQL_MIGRATIONS_REQUIRED/);const child=require('node:child_process').spawnSync(process.execPath,[path.resolve(__dirname,'../src/worker/main.js')],{env:{...process.env,...env,MYSQL_DATABASE:restored.database,OPERATIONS_WORKER_ENABLED:'true'},encoding:'utf8',timeout:10000,windowsHide:true});assert.equal(child.status,1);assert.match(child.stderr,/RESTORE_REVIEW_REQUIRED/);const [[invite]]=await restored.execute('SELECT pending_invitee,expires_at FROM party_invitations');assert.equal((await restored.execute("SELECT AUTO_INCREMENT n FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='ops_audit'"))[0][0].n,'5000');assert.equal(invite.pending_invitee,buyer.account_id);assert.equal(invite.expires_at,'2030-01-02 03:04:05.123456');const [[paid]]=await restored.execute('SELECT amount_minor FROM trade_journal WHERE order_id=?',[order.id]);assert.equal(paid.amount_minor,'500000');assert.equal((await L.reconcile(restored,saved.id)).rows,2);assert.equal((await restored.execute("SELECT JSON_UNQUOTE(JSON_EXTRACT(manifest_json,'$.exact_integer')) v FROM legacy_imports WHERE id=?",[saved.id]))[0][0].v,'9007199254740993');assert.equal((await createJobRepository(restored).get(back.payload.tables.find(t=>t.name==='platform_jobs').rows[0][0].v))!==null,true);evidence.checks.push({name:'database-restore',...result,duration_ms:Math.round(performance.now()-started)});});
 await t.test('restore never overwrites an existing database or accepts the wrong source checksum',async()=>{await assert.rejects(B.restore(db,back.payload,{expected_sha256:back.manifest.payload_sha256}),{code:'RESTORE_TARGET_NOT_EMPTY'});const fresh=await newDatabase();await assert.rejects(B.restore(fresh,back.payload,{expected_sha256:'0'.repeat(64)}),{code:'BACKUP_CHECKSUM_MISMATCH'});assert.equal((await fresh.execute('SELECT COUNT(*) n FROM information_schema.tables WHERE table_schema=DATABASE()'))[0][0].n,'0');});
 await t.test('invalid foreign key rolls back all imported rows and preserves quarantine',async()=>{const p=JSON.parse(JSON.stringify(back.payload)),table=p.tables.find(x=>x.name==='auth_sessions');table.rows[0][table.columns.indexOf('account_id')]={t:'text',v:key()};table.data_sha256=F.tableHash(table.rows);const fresh=await newDatabase();await assert.rejects(B.restore(fresh,p,{expected_sha256:F.hash(p)}),{code:'RESTORE_FOREIGN_KEY_MISMATCH'});assert.equal(await mysqlReady(fresh)(),false);assert.equal((await fresh.execute('SELECT COUNT(*) n FROM identity_accounts'))[0][0].n,'0');});
 await t.test('schema injection or renamed column is rejected without executing backup SQL',async()=>{const p=JSON.parse(JSON.stringify(back.payload));p.tables[0].columns[0]='id`); DROP DATABASE live; --';assert.throws(()=>B.verify(p),{code:'UNSUPPORTED_IDENTIFIER'});const altered=JSON.parse(JSON.stringify(back.payload));altered.tables[0].ddl_sha256='0'.repeat(64);const fresh=await newDatabase();await assert.rejects(B.restore(fresh,altered,{expected_sha256:F.hash(altered)}),{code:'RESTORE_SCHEMA_MISMATCH'});assert.equal(await mysqlReady(fresh)(),false);});
 await t.test('release checks do not confuse filled forms, sandbox providers or running process with launch approval',async()=>{const m={format:'JX_RELEASE_REVIEW_V1',commit:'a'.repeat(40),checks:[],providers:[{provider_kind:'SmsProvider',provider_code:'volcengine',capability_code:'login_sms',config_revision:'synthetic'}]};const r=await R.inspect(db,m,env);assert.equal(r.production_release,'NOT_APPROVED');assert.ok(r.checks.every(c=>c.current_status==='MISSING_OR_OUTDATED'));assert.equal(r.providers[0].current_status,'NOT_VERIFIED');assert.equal(r.schema_ready,true);assert.equal(r.configuration.find(c=>c.name==='production_mode').result,'BLOCKED');evidence.checks.push({name:'release-check',result:'BLOCKS_UNVERIFIED',production_release:r.production_release});});
 await t.test('registered provider evidence remains version-bound and never substitutes for a live check',async()=>{const d={provider_kind:'PaymentProvider',provider_code:'SYNTHETIC_STAGE12',capability_code:'payment',environment:'PRODUCTION'},repository=require('../src/modules/providers/readiness').createReadinessRepository(db,{authorizeChange:async()=>true,verifyEvidence:async()=>true});await repository.record({...d,current_status:'PRODUCTION_VERIFIED',config_revision:'synthetic-r1',expected_version:0,evidence_ref:'synthetic:only'},{actor_ref:'synthetic:reviewer'});const manifest={format:'JX_RELEASE_REVIEW_V1',commit:'a'.repeat(40),checks:[],providers:[{...d,config_revision:'synthetic-r1'}]};const r=await R.inspect(db,manifest,env);assert.equal(r.providers[0].current_status,'RECORDED_REQUIRES_LIVE_RECHECK');assert.equal(r.providers[0].transport_checked,false);assert.equal(r.production_release,'NOT_APPROVED');manifest.providers[0].config_revision='synthetic-r2';assert.equal((await R.inspect(db,manifest,env)).providers[0].current_status,'NOT_VERIFIED');});
 await t.test('sustained bounded HTTP reads isolate identities and measure latency without claiming production capacity',async()=>{const total=160,concurrency=8,results=[],started=performance.now();let cursor=0;await Promise.all(Array.from({length:concurrency},async()=>{while(cursor<total){const n=cursor++,begin=performance.now(),r=await api('GET','/records/'+order.id,n%2?buyer:stranger);assert.equal(r.status,n%2?200:404);results.push(performance.now()-begin);}}));results.sort((a,b)=>a-b);evidence.metrics={requests:total,concurrency,duration_ms:Math.round(performance.now()-started),p50_ms:Math.round(results[Math.floor(results.length*.5)]),p95_ms:Math.round(results[Math.floor(results.length*.95)]),max_ms:Math.round(results.at(-1)),unexpected_responses:0,meaning:'隔离环境有限并发观测，不是生产容量承诺'};});
 await t.test('concurrent duplicate writes preserve one business object and one set of receipts',async()=>{const root=base.replace(/\/trade$/,''),op=key();const rows=await Promise.all(Array.from({length:8},async()=>{const r=await fetch(root+'/organizations',{method:'POST',headers:{Authorization:'Bearer '+buyer.token,'Content-Type':'application/json','Idempotency-Key':op},body:JSON.stringify({display_name:'Synthetic parallel organization'})});assert.equal(r.status,200);return (await r.json()).data;}));assert.equal(new Set(rows.map(x=>x.party_id)).size,1);const [[r]]=await db.execute("SELECT COUNT(*) n FROM parties WHERE display_name='Synthetic parallel organization'");assert.equal(Number(r.n),1);assert.equal((await db.execute('SELECT COUNT(*) n FROM trade_journal WHERE order_id=?',[order.id]))[0][0].n,'1');});
 await t.test('HTTP security failures never expose SQL, credentials or accept forged payment flags',async()=>{const unauth=await api('GET','/records/'+order.id,null);assert.equal(unauth.status,401);const invalid=await api('POST','/payments',buyer,{order_id:order.id,installment_key:'first',paid:true});assert.equal(invalid.status,400);assert.equal((await api('GET',"/records/'%20OR%201=1")).status,400);assert.ok(!JSON.stringify(unauth.body).includes(env.MYSQL_PASSWORD));assert.ok(!JSON.stringify(invalid.body).includes('INSERT INTO'));});
 assert.equal(F.hash(await fs.readFile(sqlite)),startHash);
 const evidenceFile=path.resolve(__dirname,'../../../..','.local/ci-evidence/release-rehearsal.json');await fs.mkdir(path.dirname(evidenceFile),{recursive:true});await fs.writeFile(evidenceFile,JSON.stringify(evidence,null,2));
 }finally{if(server)await new Promise(r=>{server.close(r);server.closeAllConnections();});for(const p of extraPools)await p.close();if(db)await db.close();for(const n of extraDatabases)await control.query('DROP DATABASE '+mysql.escapeId(n));await control.query('DROP DATABASE '+mysql.escapeId(name));await control.end();}
});
