 'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');
const {randomUUID:key,randomBytes}=require('node:crypto'),mysql=require('mysql2/promise');
const {openDatabase}=require('../src/infrastructure/database'),{migrate}=require('../src/infrastructure/database/migrator');
const {createPartyRepository}=require('../src/modules/party/repository'),{createAuthRepository}=require('../src/modules/auth/repository');
const {maintainOperatorGrant}=require('../src/modules/governance/operator-access'),{createAccountApi}=require('../src/http/account-api');
const {createTradeRepository}=require('../src/modules/trade/repository'),{createRuleContent,digest}=require('../src/modules/governance/content');
test('trade actual HTTP and isolated MySQL money, ownership and concurrency',{skip:!process.env.JX_MYSQL_TEST_ENV_FILE},async t=>{
 const env=JSON.parse(await fs.readFile(process.env.JX_MYSQL_TEST_ENV_FILE,'utf8'));assert.equal(env.NODE_ENV,'test');assert.equal(env.MYSQL_HOST,'127.0.0.1');assert.equal(env.MYSQL_DATABASE,'jx_dev');
 const name=`jx_test_${process.pid}_${randomBytes(6).toString('hex')}`,control=await mysql.createConnection({host:env.MYSQL_HOST,port:Number(env.MYSQL_PORT),user:env.MYSQL_USER,password:env.MYSQL_PASSWORD,database:env.MYSQL_DATABASE});let db,server;
 try{
 await control.query('CREATE DATABASE '+mysql.escapeId(name)+' CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin');db=await openDatabase({...env,MYSQL_DATABASE:name});await migrate(db);
 const principals=new Map(),resolvePrincipal=async ctx=>principals.get(ctx),parties=createPartyRepository(db,{resolvePrincipal}),secret=randomBytes(32).toString('base64'),auth=createAuthRepository(db,{secret}),repo=createTradeRepository(db,{resolvePrincipal});
 const people=[];for(const label of ['seller','buyer','reviewer','stranger']){const ctx={};principals.set(ctx,{subject_ref:'synthetic:'+key()});const p={ctx,...await parties.registerAccount(ctx,{display_name:label}),token:randomBytes(32).toString('base64url')};people.push(p);await db.execute('INSERT INTO auth_sessions(token_hash,account_id,expires_ms) VALUES (?,?,ROUND(UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000)+3600000)',[auth.secure.digest('token',p.token),p.account_id]);}
 const [seller,buyer,reviewer,stranger]=people;for(const person of [reviewer,seller])for(const action of ['TRADE_REVIEW','TRADE_REFUND'])await maintainOperatorGrant(db,{account_id:person.account_id,action,enabled:true,expires_at:null,expected_version:0,authority_ref:'synthetic:test',reason:'isolated test'});
 const ruleId=key(),rule=createRuleContent({id:ruleId,rule_key:'trade.test',version:'1',terms:{explicit:'synthetic only'}});await db.execute('INSERT INTO governance_rules(id,rule_key,version_label,content_json,effective_at,created_by,current_status) VALUES (?,?,?,?,?,?,?)',[ruleId,'trade.test','1',JSON.stringify(rule),'2020-01-01 00:00:00',seller.account_id,'EFFECTIVE']);
 let calls=0,fail=false,ready=true;const proofs=new Map();const config=code=>({provider:code,environment:'SANDBOX',app_id:'synthetic.app',merchant_id:'synthetic.merchant',merchant_party_id:seller.personal_party_id,config_revision:'test'});
 const providersFactory=()=>({get(code){return {config:config(code),async assertReady(){if(!ready)throw Error('not configured');},async call(method,p){if(method==='create'){calls++;if(fail)throw Error('unknown');return code==='ALIPAY'?{kind:'ALIPAY_APP',order_string:'synthetic-only'}:{kind:'APPLE_STOREKIT2',product_id:p.apple_product_id,app_account_token:p.id};}if(method==='refund')return {status:code==='APPLE'?'AWAITING_APPLE_REQUEST':'PENDING'};return proofs.get(p.id);},async refundQuery(r){return {...r,refund_id:r.id,status:'SUCCEEDED'};},async notification(body){if(body.signedPayload!=='synthetic-verified-token'||!proofs.has('notification'))throw Error('unsigned');return proofs.get('notification');}};}});
 const files=new Map(),storageFactory=()=>({async put({key,body}){files.set(key,body);return {key,size:body.length,sha256:require('node:crypto').createHash('sha256').update(body).digest('hex')};},async getBuffer(key){return files.get(key);}});
 server=createAccountApi({db,secret,tradeProvidersFactory:providersFactory,supplyStorageFactory:storageFactory}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port+'/api/v1/trade',fixtures=[];
 async function api(method,url,person=buyer,body,party=person?.personal_party_id,headers={}){const r=await fetch(base+url,{method,headers:{...(person?{Authorization:'Bearer '+person.token}:{}),...(party?{'X-Acting-Party':party}:{}),...(method==='POST'?{'Content-Type':'application/json','Idempotency-Key':key()}:{}),...headers},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:r.status,body:(r.headers.get('content-type')||'').includes('application/json')?await r.json():await r.text()};}
 const take=(r,schema='TradeRecordResponse')=>{assert.equal(r.status,200,JSON.stringify(r.body));fixtures.push({schema,value:r.body});return r.body.data;};
 const review=async r=>take(await api('POST','/records/'+r.id+'/reviews',reviewer,{decision:'APPROVED',reason:'synthetic verified'},null,{'If-Match':'"'+r.object_version+'"'}));
 const specification={version:'1',service_tier:'Explicit synthetic tier',sample_seconds:23,final_seconds:119,revision_limit:2,deliverables:['test artifact'],terms:'No real product terms'};
 let spec,order,payment;
 async function newOrder(channel='ALIPAY',trigger='ORDER_ACCEPTED'){const q=await review(take(await api('POST','/quotes',seller,{buyer_party_id:buyer.personal_party_id,lines:[{line_id:'production',spec_id:spec.id,quantity:1}],installments:[{key:'first',trigger,allocations:[{line_id:'production',amount_minor:500000}],apple_product_id:channel==='APPLE'?'synthetic.product':null}],channel,transaction_model:'DIRECT_SUPPLIER',rule_id:ruleId,expires_at:'2099-01-01T00:00:00.000Z',payment_window_minutes:30,license_reservation_id:null})));return take(await api('POST','/quotes/'+q.id+'/acceptance',buyer,{quote_sha256:q.content_sha256},buyer.personal_party_id,{'If-Match':'"'+q.object_version+'"'}));}
 const start=(o,op=key())=>api('POST','/payments',buyer,{order_id:o.id,installment_key:'first'},buyer.personal_party_id,{'Idempotency-Key':op});
 const proof=p=>({...config(p.data.provider),payment_id:p.id,currency:'CNY',amount_minor:p.data.amount_minor,status:'SUCCEEDED',transaction_id:'synthetic.'+p.id,product_id:p.data.apple_product_id,app_account_token:p.data.provider==='APPLE'?p.id:null});
 await t.test('independent review and immutable explicitly priced specification',async()=>{const draft=take(await api('POST','/specifications',seller,{previous_spec_id:null,title:'Synthetic production',provider_party_id:seller.personal_party_id,line_kind:'PRODUCTION',unit_minor:500000,currency:'CNY',specification}));assert.equal((await api('POST','/records/'+draft.id+'/reviews',seller,{decision:'APPROVED',reason:'self'},null,{'If-Match':'"1"'})).status,403);spec=await review(draft);order=await newOrder();assert.equal(order.data.contract.signing_method,'NOT_SIGNED');assert.equal(order.data.quote.total_minor,500000);});
 await t.test('unconfigured provider makes no payment attempt and cannot report success',async()=>{ready=false;assert.equal((await start(order)).status,503);ready=true;const [[r]]=await db.execute("SELECT COUNT(*) n FROM trade_records WHERE kind='PAYMENT'");assert.equal(Number(r.n),0);});
 await t.test('payment creation is idempotent and ownership enforced',async()=>{const op=key();payment=take(await start(order,op));assert.equal(payment.current_status,'PENDING');assert.equal(take(await start(order,op)).id,payment.id);assert.equal(calls,1);assert.equal((await api('GET','/records/'+payment.id,stranger)).status,404);assert.equal((await api('POST','/payments/'+payment.id+'/reconciliation',stranger,{transaction_id:null})).status,404);});
 await t.test('unsigned notifications and client paid fields never mark paid',async()=>{assert.equal((await api('POST','/notifications/apple',null,{signedPayload:'fake'},null)).status,400);assert.equal((await api('POST','/payments/'+payment.id+'/reconciliation',buyer,{transaction_id:null,paid:true})).status,400);assert.equal((await repo.read(buyer.ctx,{record_id:order.id,party_id:buyer.personal_party_id})).current_status,'OPEN');});
 await t.test('wrong amount currency merchant or environment rejected before receipt',async()=>{for(const change of [{amount_minor:1},{currency:'USD'},{merchant_id:'wrong'},{environment:'PRODUCTION'}]){proofs.set(payment.id,{...proof(payment),...change});assert.equal((await api('POST','/payments/'+payment.id+'/reconciliation',buyer,{transaction_id:null})).status,409);}});
 await t.test('concurrent verified observations credit once; out of order pending cannot erase receipt',async()=>{proofs.set(payment.id,proof(payment));for(const r of await Promise.all([1,2,3].map(()=>api('POST','/payments/'+payment.id+'/reconciliation',buyer,{transaction_id:null}))))take(r);await repo.applyPayment({...proof(payment),status:'PENDING',transaction_id:null});const [[r]]=await db.execute("SELECT COUNT(*) n FROM trade_journal WHERE direction='RECEIPT' AND order_id=?",[order.id]);assert.equal(Number(r.n),1);assert.equal(take(await api('GET','/records/'+order.id)).current_status,'PAID');});
 await t.test('refund reservations prevent concurrent excessive refunds and require separate review',async()=>{const body={payment_id:payment.id,allocations:[{line_id:'production',amount_minor:300000}],reason:'synthetic refund'};const rr=await Promise.all([1,2].map(()=>api('POST','/refunds',buyer,body)));assert.deepEqual(rr.map(r=>r.status).sort(),[200,409]);let r=take(rr.find(r=>r.status===200));assert.equal((await api('POST','/refunds/'+r.id+'/execution',buyer,{},null)).status,403);r=await review(r);r=take(await api('POST','/refunds/'+r.id+'/execution',reviewer,{},null));assert.equal(r.current_status,'PENDING');r=take(await api('POST','/refunds/'+r.id+'/reconciliation',buyer,{}));assert.equal(r.current_status,'SUCCEEDED');take(await api('POST','/refunds/'+r.id+'/reconciliation',buyer,{}));assert.equal(take(await api('GET','/records/'+order.id)).data.financial.refunded_minor,300000);});
 await t.test('unknown dispatch cannot be blindly submitted again',async()=>{const o=await newOrder(),op=key();fail=true;assert.equal((await start(o,op)).status,503);const n=calls;fail=false;const r=take(await start(o,op));assert.equal(r.current_status,'UNKNOWN');assert.equal(calls,n);assert.equal((await api('POST','/orders/'+o.id+'/cancellation',buyer,{reason:'uncertain'},buyer.personal_party_id,{'If-Match':'"1"'})).status,409);});
 await t.test('production acceptance cannot be claimed by client to unlock final payment',async()=>{const o=await newOrder('ALIPAY','FINAL_ACCEPTED');assert.equal((await start(o)).status,409);});
 await t.test('verified late payments are retained for manual review',async()=>{const o=await newOrder(),p=take(await start(o)),data={...p.data,expires_at:'2020-01-01T00:00:00.000Z'};await db.execute('UPDATE trade_records SET data_json=?,data_sha256=? WHERE id=?',[JSON.stringify(data),digest(data),p.id]);await repo.applyPayment(proof(p));assert.equal(take(await api('GET','/records/'+o.id)).current_status,'PAYMENT_REVIEW_REQUIRED');});
 await t.test('Apple purchase and full refund retain gross receipt and refund facts separately',async()=>{const o=await newOrder('APPLE'),p=take(await start(o));assert.equal(p.data.checkout.app_account_token,p.id);await repo.applyPayment(proof(p));assert.equal((await api('POST','/refunds',buyer,{payment_id:p.id,allocations:[{line_id:'production',amount_minor:1}],reason:'partial'})).status,409);proofs.set('notification',{...proof(p),status:'REFUNDED'});const notified=await api('POST','/notifications/apple',null,{signedPayload:'synthetic-verified-token'},null);assert.equal(notified.status,200);fixtures.push({schema:'TradeNotificationResponse',value:notified.body});await repo.applyPayment({...proof(p),status:'REFUNDED'});const out=take(await api('GET','/records/'+o.id));assert.equal(out.current_status,'REFUNDED');assert.deepEqual(out.data.financial,{received_minor:500000,refunded_minor:500000,net_minor:0});});
 await t.test('cancelled order preserves later verified cash and requires review',async()=>{const o=await newOrder();let p=await repo.preparePayment(buyer.ctx,{party_id:buyer.personal_party_id,order_id:o.id,installment_key:'first',operation_key:key()},config('ALIPAY'));take(await api('POST','/orders/'+o.id+'/cancellation',buyer,{reason:'before dispatch'},buyer.personal_party_id,{'If-Match':'"1"'}));await repo.applyPayment(proof(p));assert.equal(take(await api('GET','/records/'+o.id)).current_status,'PAYMENT_REVIEW_REQUIRED');});
 await t.test('two actual charges on one installment are retained without pretending order is normally paid',async()=>{const o=await newOrder(),p=take(await start(o));await repo.applyPayment({...proof(p),status:'CLOSED'});const p2=take(await start(o));await repo.applyPayment(proof(p2));await repo.applyPayment(proof(p));const r=take(await api('GET','/records/'+o.id));assert.equal(r.current_status,'PAYMENT_REVIEW_REQUIRED');assert.equal(r.data.financial.received_minor,1000000);});
 await t.test('legacy 99 and 4901 amounts and reported status are preserved as reference only',async()=>{const supply=require('../src/modules/works/repository').createSupplyRepository(db,{resolvePrincipal}),assets=require('../src/modules/works/assets').createSupplyAssets({db,repository:supply,storageFactory});const uploaded=await assets.upload(seller.ctx,{party_id:seller.personal_party_id,purpose:'RIGHTS_EVIDENCE',media_type:'text/plain',body:Buffer.from('synthetic old receipt'),operation_key:key()});const body={buyer_party_id:buyer.personal_party_id,merchant_party_id:seller.personal_party_id,source_system:'old.sqlite',source_order_id:'old.99.4901',original_lines:[{line_id:'sample',amount_minor:9900,reported_status:'REPORTED_PAID'},{line_id:'final',amount_minor:490100,reported_status:'REPORTED_UNPAID'}],original_terms:'Synthetic historical commitments',evidence_asset_id:uploaded.id};const imported=take(await api('POST','/legacy-orders',reviewer,body,null));assert.deepEqual(imported.data.original_lines,body.original_lines);assert.equal(imported.data.payment_verified,false);assert.equal((await api('POST','/records/'+imported.id+'/reviews',reviewer,{decision:'APPROVED',reason:'self'},null,{'If-Match':'"1"'})).status,403);const url='/legacy-orders/'+imported.id+'/evidence/'+uploaded.id+'/content';assert.equal((await api('GET',url,reviewer,undefined,null)).status,200);assert.equal((await api('GET',url,stranger,undefined,null)).status,403);assert.equal((await api('POST','/legacy-orders',reviewer,body,null)).status,409);});
 await t.test('audit failure rolls back order mutation and request key',async()=>{await db.withConnection(c=>c.query("CREATE TRIGGER trade_audit_fail BEFORE INSERT ON trade_audit FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='synthetic audit failure'"));try{const [[before]]=await db.execute('SELECT COUNT(*) n FROM trade_records');assert.equal((await api('POST','/specifications',seller,{previous_spec_id:null,title:'fail',provider_party_id:seller.personal_party_id,line_kind:'OTHER',unit_minor:1,currency:'CNY',specification})).status,503);const [[after]]=await db.execute('SELECT COUNT(*) n FROM trade_records');assert.equal(after.n,before.n);}finally{await db.withConnection(c=>c.query('DROP TRIGGER trade_audit_fail'));}});
 take(await api('GET','/records?kind=ORDER&limit=1'),'TradeListResponse');
 const out=path.resolve(__dirname,'../../../..','.local/trade-http-fixtures.json');await fs.mkdir(path.dirname(out),{recursive:true});await fs.writeFile(out,JSON.stringify({synthetic_only:true,cases:fixtures},null,2));
 }finally{if(server)await new Promise(r=>{server.close(r);server.closeAllConnections();});if(db)await db.close();await control.query('DROP DATABASE '+mysql.escapeId(name));await control.end();}
});
