 'use strict';
const {randomUUID,createHash}=require('node:crypto');
const {id,ref,label,shape,version,error}=require('../party/policy');
const {digest}=require('../governance/content');
const {authorizeOperator}=require('../governance/operator-access');
const {coversConsent}=require('../works/consent-policy');
const policy=require('./policy');
const one=async(tx,sql,args=[])=>(await tx.execute(sql,args))[0][0];
const parsed=x=>typeof x==='string'?JSON.parse(x):x;
function checked(row){if(!row)throw error('PRODUCTION_NOT_FOUND',404);const data=parsed(row.data_json);if(digest(data)!==row.data_sha256)throw error('STORED_CONTENT_MISMATCH',503);return {...row,data};}
function dto(row){const r=checked(row);return {id:r.id,kind:r.kind,project_id:r.project_id,order_id:r.order_id,created_by:r.created_by,current_status:r.current_status,object_version:r.object_version,content_sha256:r.data_sha256,data:r.data};}
function createProductionRepository(db,{resolvePrincipal=async()=>null}={}){
 async function actor(tx,ctx){const p=await resolvePrincipal(ctx);if(!p)throw error('AUTHENTICATION_REQUIRED',401);const a=await one(tx,'SELECT * FROM identity_accounts WHERE subject_ref=? FOR SHARE',[ref(p.subject_ref)]);if(!a||a.current_status!=='ACTIVE')throw error('ACCOUNT_NOT_ACTIVE');return {...a,request_id:ref(p.request_id||randomUUID())};}
 async function member(tx,a,party,owner=true){const p=await one(tx,'SELECT * FROM parties WHERE id=? FOR SHARE',[id(party)]),m=await one(tx,'SELECT * FROM party_memberships WHERE party_id=? AND account_id=? FOR SHARE',[party,a.id]);if(!p||['CLOSED','SUSPENDED'].includes(p.current_status)||!m||m.current_status!=='ACTIVE'||owner&&m.role_code!=='OWNER')throw error('PRODUCTION_PARTY_FORBIDDEN');return m;}
 async function reviewer(tx,a,p){if(!await authorizeOperator(tx,{account_id:a.id,action:'PRODUCTION_REVIEW'}))throw error('PRODUCTION_REVIEW_FORBIDDEN');if(p&&(p.created_by===a.id||await one(tx,"SELECT id FROM party_memberships WHERE account_id=? AND current_status='ACTIVE' AND party_id IN (?,?,?)",[a.id,p.data.buyer_party_id,p.data.merchant_party_id,p.data.producer_party_id])))throw error('SELF_REVIEW_FORBIDDEN');}
 async function load(tx,key,kind,lock='FOR UPDATE'){const r=dto(await one(tx,'SELECT * FROM production_records WHERE id=? '+lock,[id(key)]));if(kind&&r.kind!==kind)throw error('PRODUCTION_NOT_FOUND',404);return r;}
 async function locked(tx,key,kind){const hint=await load(tx,key,kind,'');await one(tx,'SELECT id FROM trade_records WHERE id=? FOR UPDATE',[hint.order_id]);if(hint.project_id)await load(tx,hint.project_id,'PROJECT');return load(tx,key,kind);}
 async function project(tx,r){return r.kind==='PROJECT'?r:load(tx,r.project_id,'PROJECT');}
 async function access(tx,a,p,party,role='read'){
  if(!party){await reviewer(tx,a,null);return;}
  const m=await member(tx,a,party,false);
  if(![p.data.buyer_party_id,p.data.merchant_party_id,p.data.producer_party_id].includes(party))throw error('PRODUCTION_NOT_FOUND',404);
  if(role==='buyer'&&(party!==p.data.buyer_party_id||m.role_code!=='OWNER'))throw error('PRODUCTION_BUYER_REQUIRED');
  if(role==='merchant'&&(party!==p.data.merchant_party_id||m.role_code!=='OWNER'))throw error('PRODUCTION_MERCHANT_REQUIRED');
  if(role==='producer'&&(party!==p.data.producer_party_id||a.id!==p.data.assignee_account_id))throw error('PRODUCTION_ASSIGNEE_REQUIRED');
  if(role==='read'&&m.role_code!=='OWNER'&&a.id!==p.data.assignee_account_id)throw error('PRODUCTION_PARTY_FORBIDDEN');
 }
 async function audit(tx,a,r,event){await tx.execute('INSERT INTO production_audit(id,record_id,actor_account_id,event_code,object_version,data_sha256,request_id) VALUES (?,?,?,?,?,?,?)',[randomUUID(),r.id,a.id,event,r.object_version,digest(r.data),a.request_id]);}
 async function insert(tx,a,kind,p,order,status,data){const r={id:randomUUID(),kind,project_id:p,order_id:order,created_by:a.id,current_status:status,object_version:1,content_sha256:digest(data),data};await tx.execute('INSERT INTO production_records(id,kind,project_id,order_id,created_by,current_status,data_json,data_sha256) VALUES (?,?,?,?,?,?,?,?)',[r.id,kind,p,order,a.id,status,JSON.stringify(data),r.content_sha256]);await audit(tx,a,r,kind+'_CREATED');return r;}
 async function save(tx,a,r,status,data,event){const next={...r,current_status:status,object_version:r.object_version+1,content_sha256:digest(data),data};await tx.execute('UPDATE production_records SET current_status=?,object_version=?,data_json=?,data_sha256=? WHERE id=?',[status,next.object_version,JSON.stringify(data),next.content_sha256,r.id]);await audit(tx,a,next,event);return next;}
 async function command(tx,a,op,input,fn){const key=digest([a.id,op,ref(input.operation_key)]),hash=digest(input);try{await tx.execute('INSERT INTO production_commands(id,fingerprint) VALUES (?,?)',[key,hash]);}catch(e){if(e.code!=='ER_DUP_ENTRY')throw e;const old=await one(tx,'SELECT * FROM production_commands WHERE id=?',[key]);if(old.fingerprint!==hash)throw error('IDEMPOTENCY_CONFLICT',409);if(!old.result_id)throw error('IDEMPOTENCY_IN_PROGRESS',409);return load(tx,old.result_id,null,'FOR SHARE');}const r=await fn();await tx.execute('UPDATE production_commands SET result_id=? WHERE id=?',[r.id,key]);return r;}
 const match=(r,v)=>{if(r.object_version!==version(v))throw error('VERSION_CONFLICT',412);};
 const usable=require('./eligibility').productionUsable;
 async function mutate(ctx,input,op,role,fn){input=policy.copy(input);return db.withTransaction(async tx=>{const a=await actor(tx,ctx),r=await locked(tx,input.record_id),p=await project(tx,r);if(role==='reviewer')await reviewer(tx,a,p);else await access(tx,a,p,input.party_id,role);return command(tx,a,op,input,async()=>{match(r,input.expected_version);return fn(tx,a,r,p,input);});});}
 const api={
 async create(ctx,input){shape(input,['party_id','order_id','line_id','script_version_id','license_project_id','assignee_account_id','purpose','territory','consent_ids','evidence_asset_id','operation_key']);input=policy.copy(input);id(input.assignee_account_id);ref(input.line_id);label(input.purpose,100);label(input.territory,100);if(!Array.isArray(input.consent_ids)||input.consent_ids.length>20||new Set(input.consent_ids).size!==input.consent_ids.length)throw error('INVALID_CONSENTS',400);input.consent_ids.forEach(id);
  return db.withTransaction(async tx=>{const a=await actor(tx,ctx);await member(tx,a,input.party_id);const order=checked(await one(tx,"SELECT * FROM trade_records WHERE id=? AND kind='ORDER' FOR UPDATE",[id(input.order_id)]));if(order.merchant_party_id!==input.party_id)throw error('PRODUCTION_MERCHANT_REQUIRED');return command(tx,a,'PROJECT',input,async()=>{
   const line=order.data.quote.lines.find(x=>x.line_id===input.line_id&&x.line_kind==='PRODUCTION');if(!line)throw error('PRODUCTION_LINE_NOT_FOUND',404);
   if(!await one(tx,"SELECT id FROM party_memberships WHERE party_id=? AND account_id=? AND current_status='ACTIVE'",[line.provider_party_id,input.assignee_account_id]))throw error('ASSIGNEE_NOT_MEMBER',409);
   const source=checked(await one(tx,"SELECT * FROM supply_records WHERE id=? AND kind='WORK_VERSION' FOR SHARE",[id(input.script_version_id)]));if(source.current_status!=='REVIEWS_COMPLETE'||![order.buyer_party_id,line.provider_party_id].includes(source.owner_party_id))throw error('PRODUCTION_SCRIPT_NOT_APPROVED',409);
   if(input.license_project_id!==null)id(input.license_project_id);if(Boolean(order.data.quote.license_reservation_id)!==Boolean(input.license_project_id))throw error('PRODUCTION_LICENSE_PROJECT_MISMATCH',409);
   const evidence=await one(tx,"SELECT * FROM supply_assets WHERE id=? AND current_status='READY' FOR SHARE",[id(input.evidence_asset_id)]);if(!evidence||!['RIGHTS_EVIDENCE','REVIEW_EVIDENCE'].includes(evidence.purpose)||![order.buyer_party_id,order.merchant_party_id].includes(evidence.owner_party_id))throw error('EVIDENCE_NOT_READY',409);
   const p=await insert(tx,a,'PROJECT',null,order.id,'IN_REVIEW',{line_id:input.line_id,buyer_party_id:order.buyer_party_id,merchant_party_id:order.merchant_party_id,producer_party_id:line.provider_party_id,script_version_id:input.script_version_id,license_project_id:input.license_project_id,assignee_account_id:input.assignee_account_id,purpose:input.purpose,territory:input.territory,consent_ids:input.consent_ids,evidence_asset_id:input.evidence_asset_id,specification:line.specification,quantity:line.quantity,contract_sha256:order.data.contract.content_sha256,current:{},accepted:{},revisions:{},change_requests:0,review:null});
   try{await tx.execute('INSERT INTO production_order_lines(order_id,line_id,project_id) VALUES (?,?,?)',[order.id,input.line_id,p.id]);}catch(e){if(e.code==='ER_DUP_ENTRY')throw error('PRODUCTION_ALREADY_EXISTS',409);throw e;}return p;
  });});
 },
 async listProjects(ctx,{party_id,after='',limit=20}){if(!Number.isInteger(limit)||limit<1||limit>100)throw error('INVALID_LIST',400);if(after)id(after);return db.withTransaction(async tx=>{const a=await actor(tx,ctx),m=await member(tx,a,party_id,false);const [rows]=await tx.execute("SELECT * FROM production_records WHERE kind='PROJECT' AND id>? AND (JSON_UNQUOTE(JSON_EXTRACT(data_json,'$.buyer_party_id'))=? OR JSON_UNQUOTE(JSON_EXTRACT(data_json,'$.merchant_party_id'))=? OR JSON_UNQUOTE(JSON_EXTRACT(data_json,'$.producer_party_id'))=?) "+(m.role_code==='OWNER'?'':"AND JSON_UNQUOTE(JSON_EXTRACT(data_json,'$.assignee_account_id'))=? ")+"ORDER BY id LIMIT ?",[after,party_id,party_id,party_id,...(m.role_code==='OWNER'?[]:[a.id]),limit+1]);return {items:rows.slice(0,limit).map(dto),next_cursor:rows.length>limit?rows[limit-1].id:null};});},
 async read(ctx,{record_id,party_id}){return db.withTransaction(async tx=>{const a=await actor(tx,ctx),r=await locked(tx,record_id),p=await project(tx,r);await access(tx,a,p,party_id);return r;});},
 async list(ctx,{project_id,party_id,kind,after='',limit=20}){if(!['FILE','VERSION','FEEDBACK','GENERATION','DIGITAL_ASSET'].includes(kind)||!Number.isInteger(limit)||limit<1||limit>100)throw error('INVALID_LIST',400);if(after)id(after);return db.withTransaction(async tx=>{const a=await actor(tx,ctx),p=await locked(tx,project_id,'PROJECT');await access(tx,a,p,party_id);const [rows]=await tx.execute('SELECT * FROM production_records WHERE project_id=? AND kind=? AND id>? ORDER BY id LIMIT ?',[p.id,kind,after,limit+1]);return {items:rows.slice(0,limit).map(dto),next_cursor:rows.length>limit?rows[limit-1].id:null};});},
 async review(ctx,input){shape(input,['record_id','expected_version','decision','reason','verification','operation_key']);if(!Object.hasOwn(input,'verification'))throw error('INVALID_INPUT',400);if(!['APPROVED','REJECTED'].includes(input.decision))throw error('INVALID_REVIEW',400);label(input.reason,2000);return mutate(ctx,input,'REVIEW','reviewer',async(tx,a,r,p,i)=>{
  if(!['PROJECT','VERSION'].includes(r.kind)||r.current_status!=='IN_REVIEW')throw error('REVIEW_NOT_PENDING',409);
  if(i.decision==='APPROVED'){if(r.kind==='PROJECT'){shape(i.verification,['contract_sha256','identity_verified','signatures_verified','rights_verified']);if(i.verification.contract_sha256!==p.data.contract_sha256||['identity_verified','signatures_verified','rights_verified'].some(k=>i.verification[k]!==true))throw error('PRODUCTION_CONDITIONS_NOT_VERIFIED',409);await usable(tx,{...p,current_status:'READY'},{paid:false});}else{await usable(tx,p);policy.checklist(i.verification,r.data.stage);}}
  const review={decision:i.decision,reason:i.reason,verification:i.verification,account_id:a.id,method:'EXTERNAL_MANUAL_REVIEW'};return save(tx,a,r,i.decision==='REJECTED'?'REJECTED':r.kind==='PROJECT'?'READY':'APPROVED',{...r.data,review},'INDEPENDENT_REVIEW');
 });},
 async assign(ctx,input){shape(input,['party_id','record_id','expected_version','assignee_account_id','reason','operation_key']);label(input.reason,2000);return mutate(ctx,input,'ASSIGN','merchant',async(tx,a,r,p,i)=>{if(r.kind!=='PROJECT')throw error('PRODUCTION_NOT_FOUND',404);if(!await one(tx,"SELECT id FROM party_memberships WHERE party_id=? AND account_id=? AND current_status='ACTIVE'",[p.data.producer_party_id,id(i.assignee_account_id)]))throw error('ASSIGNEE_NOT_MEMBER',409);return save(tx,a,p,p.current_status,{...p.data,assignee_account_id:i.assignee_account_id,assignment_reason:i.reason},'ASSIGNEE_CHANGED');});},
 async reserveFile(ctx,input){const {body,...meta}=input;shape(meta,['party_id','project_id','media_type','operation_key']);if(!Buffer.isBuffer(body)||!body.length||body.length>50*1024*1024||!['text/plain','video/mp4','audio/mpeg','image/png','application/pdf'].includes(meta.media_type))throw error('INVALID_PRODUCTION_FILE',400);const hash=createHash('sha256').update(body).digest('hex');return db.withTransaction(async tx=>{const a=await actor(tx,ctx),p=await locked(tx,input.project_id,'PROJECT');await access(tx,a,p,input.party_id,'producer');await usable(tx,p);let fresh=false;const record=await command(tx,a,'FILE',{...meta,content_sha256:hash,byte_size:body.length},()=>{fresh=true;return insert(tx,a,'FILE',p.id,p.order_id,'UPLOADING',{object_key:'private/production/'+p.id+'/'+randomUUID(),media_type:meta.media_type,byte_size:body.length,content_sha256:hash});});return {record,fresh};});},
 async finishFile(ctx,input){return db.withTransaction(async tx=>{const a=await actor(tx,ctx),r=await locked(tx,input.record_id,'FILE'),p=await project(tx,r);await access(tx,a,p,input.party_id,'producer');await usable(tx,p);if(r.current_status!=='UPLOADING')throw error('UPLOAD_RECONCILIATION_REQUIRED',409);return save(tx,a,r,input.success?'READY':'FAILED',r.data,'FILE_UPLOAD_RESULT');});},
 async submitVersion(ctx,input){shape(input,['record_id','party_id','expected_version','stage','file_id','preview_file_id','note','operation_key']);policy.stage(input.stage);label(input.note,2000);return mutate(ctx,input,'VERSION','producer',async(tx,a,r,p,i)=>{
  if(r.kind!=='PROJECT')throw error('PRODUCTION_NOT_FOUND',404);await usable(tx,p);const basis=policy.predecessor(p.data.current,p.data.accepted,i.stage),files=[];
  for(const fileId of [i.file_id,i.preview_file_id]){const f=await load(tx,fileId,'FILE','FOR SHARE');if(f.project_id!==p.id||f.current_status!=='READY'||f.data.media_type!==(i.stage==='SCRIPT'?'text/plain':'video/mp4'))throw error('PRODUCTION_FILE_NOT_READY',409);files.push(f);}
  if(i.stage==='FINAL'&&files[0].data.content_sha256===files[1].data.content_sha256)throw error('DISTINCT_PREVIEW_REQUIRED',409);
  if(p.current_status==='ACCEPTED')throw error('FINAL_ALREADY_ACCEPTED',409);const revision=(p.data.revisions[i.stage]||0)+1;
  const v=await insert(tx,a,'VERSION',p.id,p.order_id,'IN_REVIEW',{stage:i.stage,revision,file_id:i.file_id,preview_file_id:i.preview_file_id,basis_version_id:basis,note:i.note,review:null});
  const reset=policy.reset(p.data.current,p.data.accepted,i.stage);reset.current[i.stage]=v.id;await save(tx,a,p,'IN_PROGRESS',{...p.data,...reset,revisions:{...p.data.revisions,[i.stage]:revision}},'CURRENT_VERSION_CHANGED');return v;
 });},
 async feedback(ctx,input){shape(input,['record_id','party_id','expected_version','decision','note','checklist','operation_key']);if(!['ACCEPT','REQUEST_CHANGES'].includes(input.decision))throw error('INVALID_FEEDBACK',400);label(input.note,4000);return mutate(ctx,input,'FEEDBACK','buyer',async(tx,a,r,p,i)=>{
  if(r.kind!=='VERSION'||p.data.current[r.data.stage]!==r.id||r.current_status!=='APPROVED')throw error('CURRENT_APPROVED_VERSION_REQUIRED',409);await usable(tx,p);policy.predecessor(p.data.current,p.data.accepted,r.data.stage);
  if(i.decision==='REQUEST_CHANGES'&&p.data.change_requests>=p.data.specification.revision_limit)throw error('REVISION_LIMIT_REACHED',409);if(i.decision==='ACCEPT')policy.checklist(i.checklist,r.data.stage);else if(i.checklist!==null)throw error('INVALID_FEEDBACK',400);
  const f=await insert(tx,a,'FEEDBACK',p.id,p.order_id,'RECORDED',{version_id:r.id,stage:r.data.stage,decision:i.decision,note:i.note,checklist:i.checklist});
  const accepted={...p.data.accepted};if(i.decision==='ACCEPT')accepted[r.data.stage]=r.id;else for(const stage of policy.stages.slice(policy.stages.indexOf(r.data.stage)))delete accepted[stage];
  await save(tx,a,r,r.current_status,{...r.data,last_feedback_id:f.id},'BUYER_FEEDBACK');await save(tx,a,p,accepted.FINAL?'ACCEPTED':'IN_PROGRESS',{...p.data,accepted,change_requests:p.data.change_requests+(i.decision==='REQUEST_CHANGES'?1:0)},'BUYER_DECISION');return f;
 });},
 async content(ctx,{record_id,party_id,variant}){if(!['preview','final'].includes(variant))throw error('INVALID_VARIANT',400);return db.withTransaction(async tx=>{const a=await actor(tx,ctx),r=await locked(tx,record_id,'VERSION'),p=await project(tx,r);await access(tx,a,p,party_id);const order=await usable(tx,p);const buyer=party_id===p.data.buyer_party_id;if(buyer&&(r.current_status!=='APPROVED'||p.data.current[r.data.stage]!==r.id))throw error('CURRENT_APPROVED_VERSION_REQUIRED',409);if(buyer&&variant==='final'&&r.data.stage==='FINAL'&&(p.data.accepted.FINAL!==r.id||order.current_status!=='PAID'))throw error('FINAL_DELIVERY_NOT_READY',409);return load(tx,variant==='preview'?r.data.preview_file_id:r.data.file_id,'FILE','FOR SHARE');});},
 async requestGeneration(ctx,input,provider){shape(input,['party_id','record_id','expected_version','operation','avatar_id','asset_id','consent_id','operation_key']);if(!['CREATE_LONG_LIVED','RENDER','DELETE_LONG_LIVED'].includes(input.operation))throw error('INVALID_GENERATION_OPERATION',400);id(input.avatar_id);id(input.consent_id);return mutate(ctx,input,'GENERATION','producer',async(tx,a,r,p,i)=>{
  if(r.kind!=='PROJECT')throw error('PRODUCTION_NOT_FOUND',404);
  if(i.operation!=='DELETE_LONG_LIVED')await usable(tx,p);
  if(!p.data.consent_ids.includes(i.consent_id))throw error('PRODUCTION_CONSENT_NOT_AVAILABLE',409);
  const consent=checked(await one(tx,"SELECT * FROM supply_records WHERE id=? AND kind='CONSENT' FOR SHARE",[i.consent_id]));if(consent.data.consent.avatar_id!==i.avatar_id)throw error('AVATAR_CONSENT_MISMATCH',409);
  if(i.operation==='CREATE_LONG_LIVED')for(const feature of consent.data.consent.features)if(!coversConsent(consent,{feature,purpose:'AI_TRAIN',territory:p.data.territory},new Date().toISOString()))throw error('AI_TRAIN_CONSENT_REQUIRED',409);
  if(i.operation==='RENDER'){const order=checked(await one(tx,'SELECT * FROM trade_records WHERE id=?',[p.order_id]));if(order.data.quote.license_reservation_id){const license=checked(await one(tx,'SELECT * FROM license_records WHERE id=? FOR SHARE',[order.data.quote.license_reservation_id]));if(!license.data.terms.rights.includes('AI_PROCESS'))throw error('AI_PROCESS_LICENSE_REQUIRED',409);}}
  let asset=null;if(i.operation!=='CREATE_LONG_LIVED'){asset=await load(tx,i.asset_id,'DIGITAL_ASSET');if(asset.project_id!==p.id||asset.data.avatar_id!==i.avatar_id||asset.data.consent_id!==i.consent_id||asset.data.provider_code!==provider.provider_code||asset.data.environment!==provider.environment||asset.data.config_revision!==provider.config_revision)throw error('DIGITAL_ASSET_MISMATCH',409);if(i.operation==='RENDER'&&asset.current_status!=='READY')throw error('DIGITAL_ASSET_NOT_READY',409);if(i.operation==='DELETE_LONG_LIVED'&&!['READY','DELETE_REQUIRED'].includes(asset.current_status))throw error('DIGITAL_ASSET_NOT_DELETABLE',409);}else if(i.asset_id!==null)throw error('INVALID_DIGITAL_ASSET',400);
  if(i.operation==='CREATE_LONG_LIVED'){const existing=await one(tx,"SELECT id FROM production_records WHERE project_id=? AND ((kind='DIGITAL_ASSET' AND current_status<>'DELETED') OR (kind='GENERATION' AND current_status<>'SUCCEEDED' AND JSON_UNQUOTE(JSON_EXTRACT(data_json,'$.operation'))='CREATE_LONG_LIVED')) AND JSON_UNQUOTE(JSON_EXTRACT(data_json,'$.avatar_id'))=?",[p.id,i.avatar_id]);if(existing)throw error('DIGITAL_ASSET_ALREADY_REQUESTED',409);}
  if(i.operation==='RENDER'&&!p.data.accepted.SCRIPT)throw error('SCRIPT_NOT_ACCEPTED',409);
  const request=await insert(tx,a,'GENERATION',p.id,p.order_id,'QUEUED',{operation:i.operation,avatar_id:i.avatar_id,asset_id:i.asset_id,consent_id:i.consent_id,provider_code:provider.provider_code,environment:provider.environment,config_revision:provider.config_revision,script_version_id:i.operation==='RENDER'?p.data.current.SCRIPT:null,upstream_task_id:null,job_id:null,result:null});
  const jobs=require('../../infrastructure/jobs/repository').createJobRepository(db),job=await jobs.enqueue({task_type:'PRODUCTION_DIGITAL_HUMAN',business_key:request.id,provider:provider.provider_code,payload_ref:request.id,max_attempts:20},tx);
  if(asset&&i.operation==='DELETE_LONG_LIVED')await save(tx,a,asset,'DELETING',asset.data,'DIGITAL_ASSET_DELETE_REQUESTED');
  return save(tx,a,request,'QUEUED',{...request.data,job_id:job.id},'GENERATION_QUEUED');
 });},
 async markConsentWithdrawal(consentId){id(consentId);const [rows]=await db.execute("SELECT id FROM production_records WHERE kind='DIGITAL_ASSET' AND current_status='READY' AND JSON_UNQUOTE(JSON_EXTRACT(data_json,'$.consent_id'))=?",[consentId]);for(const row of rows)await db.withTransaction(async tx=>{const r=await locked(tx,row.id,'DIGITAL_ASSET'),c=await one(tx,"SELECT current_status FROM supply_records WHERE id=? AND kind='CONSENT' FOR SHARE",[consentId]);if(c?.current_status==='WITHDRAWN'&&r.current_status==='READY')await save(tx,{id:null,request_id:randomUUID()},r,'DELETE_REQUIRED',r.data,'CONSENT_WITHDRAWN_DELETE_REQUIRED');});},
 async generationJob(ctx,{record_id,party_id}){const r=await api.read(ctx,{record_id,party_id});if(r.kind!=='GENERATION')throw error('PRODUCTION_NOT_FOUND',404);const jobs=require('../../infrastructure/jobs/repository').createJobRepository(db),job=await jobs.get(r.data.job_id);if(!job)throw error('GENERATION_JOB_NOT_FOUND',503);return {record_id:r.id,job_id:job.id,current_status:job.status,attempts:job.attempts,last_error:job.last_error};},
 async retryGeneration(ctx,input){shape(input,['record_id','reason_ref','operation_key']);ref(input.reason_ref);return db.withTransaction(async tx=>{const a=await actor(tx,ctx),r=await locked(tx,input.record_id,'GENERATION'),p=await project(tx,r);await reviewer(tx,a,p);return command(tx,a,'RETRY_GENERATION',input,async()=>{await require('../../infrastructure/jobs/repository').createJobRepository(db).manualRetry(r.data.job_id,{actor_ref:a.id,reason_ref:input.reason_ref,additional_attempts:20},tx);return save(tx,a,r,'QUEUED',r.data,'GENERATION_RETRY_REQUESTED');});});},
 async jobContext(job){return db.withTransaction(async tx=>{const r=await locked(tx,job.payload_ref,'GENERATION'),p=await project(tx,r);if(r.data.job_id!==job.id)throw error('GENERATION_JOB_MISMATCH',409);if(r.data.operation!=='DELETE_LONG_LIVED'){await usable(tx,p);if(r.data.operation==='RENDER'&&(p.data.current.SCRIPT!==r.data.script_version_id||p.data.accepted.SCRIPT!==r.data.script_version_id))throw error('SCRIPT_VERSION_CHANGED',409);}const asset=r.data.asset_id?await load(tx,r.data.asset_id,'DIGITAL_ASSET','FOR SHARE'):null;if(r.data.operation==='RENDER'&&asset?.current_status!=='READY')throw error('DIGITAL_ASSET_NOT_READY',409);return {request:r,project:p,asset};});},
 async saveJobObservation(job,result){return db.withTransaction(async tx=>{const r=await locked(tx,job.payload_ref,'GENERATION'),p=await project(tx,r);const lease=await one(tx,"SELECT id FROM platform_jobs WHERE id=? AND status='RUNNING' AND lease_owner=? AND lease_token=? AND lease_until>CURRENT_TIMESTAMP(6) FOR SHARE",[job.id,job.lease_owner,job.lease_token]);if(!lease)throw error('LEASE_LOST',409);if(r.current_status==='SUCCEEDED')return r;
  const a={id:null,request_id:randomUUID()};if(r.data.operation!=='DELETE_LONG_LIVED'){await usable(tx,p);if(r.data.operation==='RENDER'&&(p.data.current.SCRIPT!==r.data.script_version_id||p.data.accepted.SCRIPT!==r.data.script_version_id))throw error('SCRIPT_VERSION_CHANGED',409);}
  if(result.status==='PENDING')return save(tx,a,r,'PENDING',{...r.data,upstream_task_id:ref(result.task_id)},'PROVIDER_PENDING');
  if(result.status!=='SUCCEEDED')throw error('UNVERIFIED_GENERATION_RESULT',503);
  let saved=result;if(r.data.operation==='CREATE_LONG_LIVED'){if(result.asset_type!=='LONG_LIVED_AVATAR')throw error('LONG_LIVED_ASSET_REQUIRED',409);ref(result.asset_ref);const asset=await insert(tx,a,'DIGITAL_ASSET',p.id,p.order_id,'READY',{avatar_id:r.data.avatar_id,consent_id:r.data.consent_id,provider_code:r.data.provider_code,environment:r.data.environment,config_revision:r.data.config_revision,upstream_asset_ref:result.asset_ref,asset_type:'LONG_LIVED_AVATAR'});saved={asset_id:asset.id,asset_type:'LONG_LIVED_AVATAR'};}
  if(r.data.operation==='DELETE_LONG_LIVED'){if(result.deleted!==true)throw error('DELETION_NOT_CONFIRMED',409);const asset=await load(tx,r.data.asset_id,'DIGITAL_ASSET');await save(tx,a,asset,'DELETED',asset.data,'UPSTREAM_DELETION_CONFIRMED');saved={deleted:true};}
  if(r.data.operation==='RENDER'){ref(result.result_ref);saved={result_ref:result.result_ref,delivery_state:'AWAITING_PRIVATE_IMPORT_AND_REVIEW'};}
  return save(tx,a,r,'SUCCEEDED',{...r.data,result:saved},'PROVIDER_RESULT_VERIFIED');
 });},
 async evidence(ctx,{record_id}){return db.withTransaction(async tx=>{const a=await actor(tx,ctx);await reviewer(tx,a,null);const p=await locked(tx,record_id,'PROJECT'),row=await one(tx,"SELECT * FROM supply_assets WHERE id=? AND current_status='READY' FOR SHARE",[p.data.evidence_asset_id]);if(!row)throw error('EVIDENCE_NOT_READY',409);return row;});},
 };
 return Object.freeze(api);
}
module.exports={createProductionRepository};
