 'use strict';
const {sqlUtcInstant}=require('./time');
const {randomUUID}=require('node:crypto'),{id,ref,label,version,error}=require('../party/policy');
const {digest}=require('../governance/content'),{authorizeOperator}=require('../governance/operator-access');
const {readSource}=require('./sources'),{publishEvent}=require('./events'),P=require('./policy');
const one=async(tx,q,a=[])=>(await tx.execute(q,a))[0][0];
function createOperationsRepository(db,{resolvePrincipal=async()=>null}={}){
 async function actor(tx,ctx){const p=await resolvePrincipal(ctx);if(!p)throw error('AUTHENTICATION_REQUIRED',401);const a=await one(tx,'SELECT * FROM identity_accounts WHERE subject_ref=? FOR SHARE',[ref(p.subject_ref)]);if(!a||a.current_status!=='ACTIVE')throw error('ACCOUNT_NOT_ACTIVE');return {...a,principal:p,request_id:ref(p.request_id||randomUUID())};}
 async function member(tx,a,party){id(party);const p=await one(tx,'SELECT current_status FROM parties WHERE id=? FOR SHARE',[party]);const m=await one(tx,"SELECT * FROM party_memberships WHERE party_id=? AND account_id=? AND current_status='ACTIVE' FOR SHARE",[party,a.id]);if(!p||['CLOSED','SUSPENDED'].includes(p.current_status)||!m)throw error('PARTY_ACTION_FORBIDDEN');return m;}
 async function operator(tx,a,action){if(!await authorizeOperator(tx,{account_id:a.id,action}))throw error('OPERATIONS_FORBIDDEN');}
 async function source(tx,a,i){P.target(i.domain,i.record_id);if(i.party_id)await member(tx,a,i.party_id);return readSource(tx,a.principal,i.domain,i.record_id,i.party_id||null);}
 async function audit(tx,a,object_id,event_code,object_version,reason=''){await tx.execute('INSERT INTO ops_audit(object_id,actor_account_id,event_code,object_version,reason,request_id) VALUES (?,?,?,?,?,?)',[object_id,a.id,event_code,object_version,reason,a.request_id]);}
 async function command(tx,a,op,i,fn,read){const key=digest([a.id,op,ref(i.operation_key)]),hash=digest(i);try{await tx.execute('INSERT INTO ops_commands(id,fingerprint) VALUES (?,?)',[key,hash]);}catch(e){if(e.code!=='ER_DUP_ENTRY')throw e;const r=await one(tx,'SELECT * FROM ops_commands WHERE id=?',[key]);if(r.fingerprint!==hash)throw error('IDEMPOTENCY_CONFLICT',409);if(!r.result_id)throw error('IDEMPOTENCY_IN_PROGRESS',409);return read(r.result_id);}const r=await fn();await tx.execute('UPDATE ops_commands SET result_id=? WHERE id=?',[r.id,key]);return r;}
 const commentDto=r=>({id:r.id,domain:r.domain,record_id:r.record_id,author_account_id:r.author_account_id,party_id:r.party_id,reply_to:r.reply_to,body:r.current_status==='VISIBLE'?r.body:null,current_status:r.current_status,object_version:r.object_version,created_at:sqlUtcInstant(r.created_at)});
 const comment=async(tx,key)=>{const r=await one(tx,'SELECT * FROM ops_comments WHERE id=? FOR UPDATE',[id(key)]);if(!r)throw error('COMMENT_NOT_FOUND',404);return r;};
 async function commentTarget(tx,a,i){const r=await source(tx,a,i);if(!({TRADE:['ORDER'],PRODUCTION:['PROJECT','VERSION'],PROJECTS:['PROJECT']}[i.domain]||[]).includes(r.kind))throw error('COMMENT_TARGET_NOT_SUPPORTED',400);return r;}
 async function reportAccess(tx,a,r){if(r.created_by!==a.id)throw error('REPORT_NOT_FOUND',404);if(r.party_id){const m=await member(tx,a,r.party_id);if(m.role_code!=='OWNER')throw error('OPERATIONS_FORBIDDEN');}else await operator(tx,a,'OPERATIONS_REPORT');}
 const reportDto=async(tx,r)=>{const job=r.job_id?await one(tx,'SELECT status,last_error FROM platform_jobs WHERE id=?',[r.job_id]):null;const request=typeof r.request_json==='string'?JSON.parse(r.request_json):r.request_json;if(digest(request)!==r.request_sha256)throw error('STORED_CONTENT_MISMATCH',503);const result=r.result_json?(typeof r.result_json==='string'?JSON.parse(r.result_json):r.result_json):null;if(result&&digest(result)!==r.result_sha256)throw error('STORED_CONTENT_MISMATCH',503);return {id:r.id,party_id:r.party_id,request,current_status:result?'SUCCEEDED':job?.status||'PENDING',error_code:result?null:job?.last_error||null,content_sha256:r.result_sha256,result};};
 async function loadReport(tx,key){const r=await one(tx,'SELECT * FROM ops_reports WHERE id=?',[id(key)]);if(!r)throw error('REPORT_NOT_FOUND',404);return r;}
 async function reportContents(tx,a,r){await reportAccess(tx,a,r);const dto=await reportDto(tx,r);if(dto.result)for(const target of dto.result.sources)await source(tx,a,{...target,party_id:r.party_id});return dto;}
 return {
 async inbox(ctx,i){P.page(i.before??0,i.limit??30);return db.withTransaction(async tx=>{const a=await actor(tx,ctx);await member(tx,a,i.party_id);const [rows]=await tx.execute(`SELECT e.*,rd.read_at FROM ops_recipients nr JOIN ops_events e ON e.id=nr.event_id LEFT JOIN ops_reads rd ON rd.event_id=e.id AND rd.account_id=? AND rd.party_id=nr.party_id WHERE nr.party_id=? ${i.before?'AND e.id<?':''} ORDER BY e.id DESC LIMIT ?`,[a.id,i.party_id,...(i.before?[i.before]:[]),i.limit??30]);const items=[];for(const r of rows){try{await source(tx,a,{...r,party_id:i.party_id});}catch(e){if([403,404].includes(e.status))continue;throw e;}if(i.unread_only&&r.read_at)continue;items.push({id:Number(r.id),domain:r.domain,record_id:r.record_id,event_code:r.event_code,object_version:r.object_version,read:!!r.read_at,created_at:sqlUtcInstant(r.created_at)});}return {items,next_cursor:rows.length===(i.limit??30)?Number(rows.at(-1).id):null};});},
 async markRead(ctx,i){P.page(i.event_id,1);if(!i.event_id)throw error('INVALID_EVENT',400);return db.withTransaction(async tx=>{const a=await actor(tx,ctx);await member(tx,a,i.party_id);const r=await one(tx,'SELECT e.* FROM ops_events e JOIN ops_recipients nr ON nr.event_id=e.id WHERE e.id=? AND nr.party_id=?',[i.event_id,i.party_id]);if(!r)throw error('NOTIFICATION_NOT_FOUND',404);await source(tx,a,{...r,party_id:i.party_id});await tx.execute('INSERT INTO ops_reads(event_id,account_id,party_id) VALUES (?,?,?) ON DUPLICATE KEY UPDATE event_id=event_id',[i.event_id,a.id,i.party_id]);return {id:Number(r.id),read:true};});},
 async addComment(ctx,i){label(i.body,4000);if(i.reply_to!==null)id(i.reply_to);return db.withTransaction(async tx=>{const a=await actor(tx,ctx),target=await commentTarget(tx,a,i);return command(tx,a,'COMMENT',i,async()=>{if(i.reply_to){const parent=await comment(tx,i.reply_to);if(parent.domain!==i.domain||parent.record_id!==i.record_id||parent.current_status!=='VISIBLE')throw error('COMMENT_REPLY_MISMATCH',409);}const cid=randomUUID();await tx.execute('INSERT INTO ops_comments(id,domain,record_id,author_account_id,party_id,reply_to,body) VALUES (?,?,?,?,?,?,?)',[cid,i.domain,i.record_id,a.id,i.party_id||null,i.reply_to,i.body]);await audit(tx,a,cid,'COMMENT_CREATED',1);await publishEvent(tx,{domain:i.domain,record_id:i.record_id,event_id:cid,event_code:'COMMENT_CREATED',object_version:target.object_version,actor_account_id:a.id});return commentDto(await comment(tx,cid));},async cid=>commentDto(await comment(tx,cid)));});},
 async comments(ctx,i){if(i.after)id(i.after);P.page(0,i.limit??30);return db.withTransaction(async tx=>{const a=await actor(tx,ctx);await commentTarget(tx,a,i);const [rows]=await tx.execute('SELECT * FROM ops_comments WHERE domain=? AND record_id=? AND id>? ORDER BY id LIMIT ?',[i.domain,i.record_id,i.after||'',(i.limit??30)+1]);return {items:rows.slice(0,i.limit??30).map(commentDto),next_cursor:rows.length>(i.limit??30)?rows[(i.limit??30)-1].id:null};});},
 async changeComment(ctx,i){label(i.reason,1000);if(!['WITHDRAW','HIDE'].includes(i.action))throw error('INVALID_COMMENT_ACTION',400);return db.withTransaction(async tx=>{const a=await actor(tx,ctx),hint=await one(tx,'SELECT domain,record_id FROM ops_comments WHERE id=?',[id(i.comment_id)]);if(!hint)throw error('COMMENT_NOT_FOUND',404);await commentTarget(tx,a,{...hint,party_id:i.party_id});const r=await comment(tx,i.comment_id);if(i.action==='WITHDRAW'){if(r.author_account_id!==a.id||r.party_id!==(i.party_id||null))throw error('COMMENT_AUTHOR_REQUIRED');}else {await operator(tx,a,'COMMENT_MODERATE');if(r.author_account_id===a.id)throw error('SELF_REVIEW_FORBIDDEN');}return command(tx,a,'COMMENT_CHANGE',i,async()=>{if(r.object_version!==version(i.expected_version))throw error('VERSION_CONFLICT',412);if(r.current_status!=='VISIBLE')throw error('COMMENT_ALREADY_HIDDEN',409);await tx.execute('UPDATE ops_comments SET current_status=?,object_version=object_version+1 WHERE id=?',[i.action==='HIDE'?'HIDDEN':'WITHDRAWN',r.id]);await audit(tx,a,r.id,'COMMENT_'+i.action,r.object_version+1,i.reason);return commentDto(await comment(tx,r.id));},async cid=>commentDto(await comment(tx,cid)));});},
 async audit(ctx,i){P.page(i.before??0,i.limit??30);return db.withTransaction(async tx=>{const a=await actor(tx,ctx);await operator(tx,a,'OPERATIONS_AUDIT');if(i.object_id)id(i.object_id);const [rows]=await tx.execute(`SELECT * FROM ops_audit WHERE 1=1 ${i.object_id?'AND object_id=?':''} ${i.before?'AND id<?':''} ORDER BY id DESC LIMIT ?`,[...(i.object_id?[i.object_id]:[]),...(i.before?[i.before]:[]),(i.limit??30)+1]);return {items:rows.slice(0,i.limit??30).map(r=>({...r,id:Number(r.id),created_at:sqlUtcInstant(r.created_at)})),next_cursor:rows.length>(i.limit??30)?Number(rows[(i.limit??30)-1].id):null};});},
 async businessAudit(ctx,i){P.target(i.domain,i.record_id);P.page(0,i.limit??30);if(i.after)id(i.after);return db.withTransaction(async tx=>{const a=await actor(tx,ctx);await operator(tx,a,'OPERATIONS_AUDIT');await source(tx,a,i);const table={TRADE:'trade_audit',PRODUCTION:'production_audit',PROJECTS:'project_audit',FINANCE:'finance_audit',SUPPLY:'supply_audit',LICENSE:'license_audit',GIGS:'gig_audit'}[i.domain];const [rows]=await tx.execute('SELECT id,record_id,actor_account_id,event_code,'+(i.domain==='SUPPLY'?'to_version':'object_version')+' AS object_version,request_id,created_at FROM '+table+' WHERE record_id=? AND id>? ORDER BY id LIMIT ?',[i.record_id,i.after||'',(i.limit??30)+1]);return {items:rows.slice(0,i.limit??30).map(r=>({...r,created_at:sqlUtcInstant(r.created_at)})),next_cursor:rows.length>(i.limit??30)?rows[(i.limit??30)-1].id:null};});},
 async requestReport(ctx,i){const request=P.request(i);return db.withTransaction(async tx=>{const a=await actor(tx,ctx);await reportAccess(tx,a,{created_by:a.id,party_id:i.party_id});return command(tx,a,'REPORT',i,async()=>{const rid=randomUUID();await tx.execute('INSERT INTO ops_reports(id,created_by,party_id,request_json,request_sha256) VALUES (?,?,?,?,?)',[rid,a.id,i.party_id||null,JSON.stringify(request),digest(request)]);const job=await require('../../infrastructure/jobs/repository').createJobRepository(db).enqueue({task_type:'OPERATIONS_REPORT',business_key:rid,payload_ref:rid,provider:null,max_attempts:3},tx);await tx.execute('UPDATE ops_reports SET job_id=? WHERE id=?',[job.id,rid]);await audit(tx,a,rid,'REPORT_REQUESTED',1);return reportDto(tx,await loadReport(tx,rid));},async rid=>reportContents(tx,a,await loadReport(tx,rid)));});},
 async report(ctx,i){return db.withTransaction(async tx=>{const a=await actor(tx,ctx),r=await loadReport(tx,i.report_id);if((i.party_id||null)!==r.party_id)throw error('REPORT_NOT_FOUND',404);return reportContents(tx,a,r);});},
 async retryReport(ctx,i){label(i.reason,1000);return db.withTransaction(async tx=>{const a=await actor(tx,ctx),r=await loadReport(tx,i.report_id);if((i.party_id||null)!==r.party_id)throw error('REPORT_NOT_FOUND',404);await reportAccess(tx,a,r);return command(tx,a,'REPORT_RETRY',i,async()=>{if(r.result_json)throw error('REPORT_ALREADY_COMPLETE',409);try{await require('../../infrastructure/jobs/repository').createJobRepository(db).manualRetry(r.job_id,{actor_ref:a.id,reason_ref:'ops:'+r.id,additional_attempts:1},tx);}catch(e){if(e.code==='JOB_NOT_RETRYABLE')throw error(e.code,409);throw e;}await audit(tx,a,r.id,'REPORT_RETRY',1,i.reason);return reportDto(tx,r);},async rid=>reportContents(tx,a,await loadReport(tx,rid)));});},
 _internal:{actor,member,operator,source,audit,loadReport,reportAccess,reportDto}
 };
}
module.exports={createOperationsRepository};
