'use strict';
const {error}=require('../party/policy');
const factories={TRADE:['../trade/repository','createTradeRepository'],PRODUCTION:['../production/repository','createProductionRepository'],PROJECTS:['../projects/repository','createProjectsRepository'],FINANCE:['../settlement/repository','createSettlementRepository'],SUPPLY:['../works/repository','createSupplyRepository'],LICENSE:['../licensing/repository','createLicensingRepository'],GIGS:['../gigs/repository','createGigsRepository']};
// Delegate current permissions to each business module; never expose its storage row to a page.
async function readSource(tx,principal,domain,record_id,party_id){const f=factories[domain];if(!f)throw error('INVALID_BUSINESS_DOMAIN',400);const repo=require(f[0])[f[1]]({withTransaction:fn=>fn(tx),execute:(...args)=>tx.execute(...args)},{resolvePrincipal:async()=>principal});return repo.read({}, {record_id,party_id});}
const tables={TRADE:'trade_records',PRODUCTION:'production_records',PROJECTS:'project_records',FINANCE:'finance_records',SUPPLY:'supply_records',LICENSE:'license_records',GIGS:'gig_records'};
const data=r=>typeof r.data_json==='string'?JSON.parse(r.data_json):r.data_json;
async function audience(tx,domain,record_id){const table=tables[domain];if(!table)throw error('INVALID_BUSINESS_DOMAIN',400);const [[r]]=await tx.execute('SELECT * FROM '+table+' WHERE id=?',[record_id]);if(!r)throw error('BUSINESS_OBJECT_NOT_FOUND',404);let ids=[r.owner_party_id,r.counterparty_id,r.buyer_party_id,r.merchant_party_id];if(domain==='PRODUCTION'){const [[o]]=await tx.execute('SELECT buyer_party_id,merchant_party_id FROM trade_records WHERE id=?',[r.order_id]);ids.push(o?.buyer_party_id,o?.merchant_party_id);const [[p]]=await tx.execute('SELECT data_json FROM production_records WHERE id=?',[r.project_id||r.id]);ids.push(data(p)?.producer_party_id);}
 if(domain==='FINANCE'){const [[g]]=await tx.execute('SELECT data_json FROM finance_records WHERE id=?',[r.agreement_id||r.id]);ids.push(...(data(g)?.parties||[]));}
 if(domain==='PROJECTS'){ids.push(...(data(r)?.confirmers||[]).map(x=>x.party_id));const [[p]]=await tx.execute('SELECT owner_party_id,data_json FROM project_records WHERE id=?',[r.project_id||r.id]);ids.push(p?.owner_party_id);if(['PROJECT','ROLE'].includes(r.kind)){const planId=data(p)?.current_plan_id;if(planId){const [[plan]]=await tx.execute('SELECT data_json FROM project_records WHERE id=?',[planId]);ids.push(...(data(plan)?.confirmers||[]).map(x=>x.party_id));}const [candidates]=await tx.execute("SELECT owner_party_id FROM project_records WHERE project_id=? AND kind='CANDIDATE' AND current_status IN ('INVITED','APPLIED','SELECTED','CONFIRMED')",[r.project_id||r.id]);ids.push(...candidates.map(x=>x.owner_party_id));}}
 return [...new Set(ids.filter(x=>typeof x==='string'))];}
module.exports={readSource,audience,tables};
