<script setup lang="ts">
import {kindLabels,financeStatus,type FinanceRecord} from '@/api/modules/finance'
import {money} from '@/api/modules/trade'
import {shortSupplyId} from '@/api/modules/supply'
import ContractText from './ContractText.vue'
import type {TextValue} from '@/api/modules/contracts'
defineProps<{record:FinanceRecord}>()
const text=(value:unknown):TextValue=>JSON.parse(JSON.stringify(value))
const outcome={PAID:'已实际付出',FAILED:'实际付款失败',RETURNED:'原款已全额退回'}
</script>
<template><section class="supply-card finance-record"><div class="section-heading"><h2>{{kindLabels[record.kind]}}</h2><span class="status-chip">{{financeStatus(record)}}</span></div><p v-if="record.kind==='PAYOUT'||record.kind==='PAYOUT_EVIDENCE'||record.kind==='RECEIPT'" class="finance-amount">{{money(record.data.amount_minor)}}</p>
<template v-if="record.kind==='AGREEMENT'"><dl class="supply-facts"><div><dt>来源</dt><dd>{{record.data.source_type==='ORDER'?'服务订单':'实际发行'}} · {{shortSupplyId(record.data.source_id)}}</dd></div><div><dt>执行环境</dt><dd>{{record.data.environment==='SANDBOX'?'沙盒':'正式'}}</dd></div><div><dt>可结算时间</dt><dd>{{record.data.rules.settlement_at}}</dd></div><div><dt>释放条件</dt><dd>{{record.data.rules.release_condition==='RECEIVED'?'真实收到款项':'真实收款及交付验收'}}</dd></div></dl><h3>本版完整条款</h3><p class="long-text">{{record.data.rules.terms}}</p><div v-for="line in record.data.rules.lines" :key="line.line_id" class="finance-rule-line"><h3>明细 {{line.line_id}}</h3><div class="table-wrap"><table><thead><tr><th>分配主体</th><th>角色</th><th>比例</th></tr></thead><tbody><tr v-for="s in line.shares" :key="s.party_id"><td :title="s.party_id">{{shortSupplyId(s.party_id)}}</td><td>{{s.role}}</td><td>{{(s.bps/100).toFixed(2)}}%</td></tr></tbody></table></div><p v-for="(d,n) in line.deductions" :key="n" class="long-text">{{d.category}} · {{shortSupplyId(d.party_id)}} · {{money(d.amount_minor)}} · {{d.basis}} · {{d.refund_behavior==='RETAIN'?'退款保留':'退款按比例调整'}}</p></div><details class="trade-rules"><summary>采用的治理规则原条款</summary><ContractText :value="record.data.rule_snapshot.terms"/></details></template>
<template v-if="record.kind==='SETTLEMENT'"><dl class="supply-facts"><div><dt>期间标签</dt><dd>{{record.data.period_reference}}</dd></div><div><dt>冻结实收</dt><dd>{{money(record.data.received_minor)}}</dd></div><div><dt>冻结应收</dt><dd>{{money(record.data.receivable_minor)}}</dd></div><div><dt>事实引用数</dt><dd>{{record.data.source_references.length}}</dd></div></dl><p class="long-text">{{record.data.note}}</p><h3>本次获准读取的冻结余额</h3><div class="table-wrap"><table><thead><tr><th>主体</th><th>计提</th><th>调整</th><th>已实付</th><th>余额</th></tr></thead><tbody><tr v-for="b in record.data.balances" :key="b.party_id"><td :title="b.party_id">{{shortSupplyId(b.party_id)}}</td><td>{{money(b.accrued_minor)}}</td><td>{{money(b.adjustment_minor)}}</td><td>{{money(b.paid_minor)}}</td><td>{{money(b.balance_minor)}}</td></tr></tbody></table></div><p class="muted">普通参与方仅看到本方余额。原指纹仍绑定保存的全体快照；历史结算单不随新收款、退款或调整变化。</p></template>
<template v-if="record.kind==='PAYOUT'"><p>收款方：{{shortSupplyId(record.data.recipient_party_id)}}</p><p class="long-text">{{record.data.note}}</p><p class="muted">申请和批准均占用可申请额度；尚未记为实际付款。真实人工支付完成后须另登记凭据并独立核实。</p><p v-if="record.data.cancel_reason">取消原因：{{record.data.cancel_reason}}</p></template>
<template v-if="record.kind==='PAYOUT_EVIDENCE'"><dl class="supply-facts"><div><dt>外部报告</dt><dd>{{outcome[record.data.outcome]}}</dd></div><div><dt>实际发生时间</dt><dd>{{record.data.occurred_at}}</dd></div></dl><p>外部参考：{{record.data.external_reference}}</p><p class="long-text">{{record.data.note}}</p><p class="muted">报告保留原付款全额；独立核实后才改变付款事实。</p></template>
<template v-if="record.kind==='STATEMENT'"><dl class="supply-facts"><div><dt>应收净额</dt><dd>{{money(record.data.net_minor)}}</dd></div><div><dt>账单性质</dt><dd>{{record.data.direction==='CREDIT'?'原应收账单':'冲减原账单'}}</dd></div><div><dt>账单期间</dt><dd>{{record.data.period_start}} — {{record.data.period_end}}</dd></div><div><dt>外部参考</dt><dd>{{record.data.external_reference}}</dd></div><div><dt>收入 / 退款</dt><dd>{{money(record.data.gross_minor)}} / {{money(record.data.refund_minor)}}</dd></div><div><dt>渠道费 / 税费</dt><dd>{{money(record.data.channel_fee_minor)}} / {{money(record.data.tax_minor)}}</dd></div></dl><p v-if="record.data.original_statement_id">冲减原记录：{{shortSupplyId(record.data.original_statement_id)}}</p><p class="long-text">{{record.data.note}}</p><p class="muted">账单核验形成应收事实；实际到账须单独登记。</p></template>
<template v-if="record.kind==='RECEIPT'"><p>对应账单：{{shortSupplyId(record.data.statement_id)}}</p><p>外部参考：{{record.data.external_reference}} · {{record.data.occurred_at}}</p><p class="long-text">{{record.data.note}}</p><p class="muted">登记的是实际到账报告；独立核验通过才记实收。</p></template>
<template v-if="record.kind==='ADJUSTMENT'"><div class="table-wrap"><table><thead><tr><th>主体</th><th>调整金额</th></tr></thead><tbody><tr v-for="e in record.data.entries" :key="e.party_id"><td>{{shortSupplyId(e.party_id)}}</td><td>{{money(e.amount_minor)}}</td></tr></tbody></table></div><p class="long-text">{{record.data.reason}}</p><p class="muted">同一约定内的零和调整；不凭空增加实收，不覆盖历史合同和付款。</p></template>
<template v-if="record.kind==='RECONCILIATION'"><p>{{record.data.provider}} · {{record.data.environment==='SANDBOX'?'沙盒':'正式'}} · {{record.data.external_reference}}</p><p>外部明细 {{record.data.items.length}} 条，差异 {{record.data.differences.length}} 条。</p><div class="table-wrap"><table><thead><tr><th>事实记录</th><th>差异</th></tr></thead><tbody><tr v-for="(d,n) in record.data.differences" :key="n"><td>{{shortSupplyId(d.record_id)}}</td><td>{{{MISSING_IN_EXTERNAL_STATEMENT:'外部账单缺少平台事实',FACT_MISMATCH:'金额或参考不符',UNKNOWN_PLATFORM_FACT:'未找到已核实平台事实'}[d.reason]}}</td></tr></tbody></table></div><p class="muted">只比较已核实收款退款；不会新增付款、补造实收或代替人工审批。</p></template>
<template v-if="record.kind==='DISPUTE'"><p>涉及记录：{{shortSupplyId(record.data.about_record_id)}} · {{record.data.category}}</p><p class="long-text">{{record.data.reason}}</p><div v-for="(d,n) in record.data.decision_history" :key="n" class="finance-rule-line"><p>{{d.decision}} · {{d.reason}}</p><p v-if="d.action_record_id">补救事实：{{shortSupplyId(d.action_record_id)}}</p></div><p class="muted">异议处理不会自动退款、改变许可或新增调账；补救须引用另行核实的真实业务事实。</p></template>
<p v-if="record.kind==='RESPONSE'" class="long-text">{{record.data.message}}</p><template v-if="'review' in record.data&&record.data.review"><h3>独立核验结论</h3><p>{{record.data.review.decision==='APPROVED'?'已通过':'已拒绝'}} · {{record.data.review.reason}}</p></template><details class="trade-rules"><summary>编号、版本、原指纹与冻结事实</summary><p class="identifier">{{record.id}} · 版本 {{record.object_version}}<br>{{record.content_sha256}}</p><ContractText :value="text(record.data)"/></details></section></template>
