<script setup lang="ts">
import { computed, reactive } from 'vue'
import { isGigRule } from '@/api/modules/gigs'
defineProps<{disabled:boolean}>();const emit=defineEmits<{submit:[body:unknown]}>()
const fields={window_days:'观察窗口（天）',newcomer_days:'新人观察期（天）',minimum_orders:'最低有效订单数',order_weight:'订单权重',net_minor_weight:'净实收权重（分）',newcomer_bonus:'新人加权'}
const f=reactive({version:'',terms:'',categories:[{code:'',allowed:'',proofs:''}],ranking:{window_days:'',newcomer_days:'',minimum_orders:'',order_weight:'',net_minor_weight:'',newcomer_bonus:''}})
const payload=computed(()=>{const rule={version:f.version.trim(),terms:f.terms.trim(),categories:f.categories.map(c=>({code:c.code.trim(),allowed:c.allowed==='true',required_proofs:c.proofs.split('\n').map(s=>s.trim()).filter(Boolean)})),ranking:Object.fromEntries(Object.entries(f.ranking).map(([k,v])=>[k,/^\d+$/.test(v)?Number(v):NaN]))};return f.categories.every(c=>['true','false'].includes(c.allowed))&&isGigRule(rule)?{rule}:null})
</script>
<template><form class="trade-form" @submit.prevent="payload&&emit('submit',payload)"><fieldset :disabled="disabled"><section class="supply-card"><h2>版本与完整条款</h2><label>规则版本 *<input v-model="f.version" data-testid="gigs-rule-version" maxlength="128" required></label><label>规则条款 *<textarea v-model="f.terms" data-testid="gigs-rule-terms" maxlength="8000" required></textarea></label></section><section class="supply-card"><div class="section-heading"><h2>类别、禁品与证明要求</h2><button class="outline" type="button" :disabled="f.categories.length>=100" @click="f.categories.push({code:'',allowed:'',proofs:''})">添加类别</button></div><div v-for="(c,n) in f.categories" :key="n" class="trade-row trade-fields three"><label>类别代码 *<input v-model="c.code" :data-testid="`gigs-category-code-${n}`" maxlength="128" required></label><label>是否允许商单 *<select v-model="c.allowed" :data-testid="`gigs-category-allowed-${n}`" required><option value="">明确选择</option><option value="true">允许</option><option value="false">禁止</option></select></label><label>所需证明代码（每行一个，最多20）<textarea v-model="c.proofs" :data-testid="`gigs-category-proofs-${n}`" placeholder="无要求可明确留空"></textarea></label><button v-if="f.categories.length>1" type="button" class="danger" @click="f.categories.splice(n,1)">移除类别</button></div></section><section class="supply-card"><h2>榜单参数</h2><div class="trade-fields three"><label v-for="(label,k) in fields" :key="k">{{label}} *<input v-model="f.ranking[k]" :data-testid="`gigs-ranking-${k}`" inputmode="numeric" required placeholder="显式整数，允许的零也须填写"></label></div><p class="muted">只计算已核实正式商业交易。版本生效后已有快照保留当时规则；没有正式数据时不生成演示排名。</p></section><section class="supply-card"><h2>登记与独立审核</h2><p>提交后待独立审核，由服务器核验 GIG_REVIEW。创建者不可自审。</p><button class="primary" data-testid="gigs-submit" :disabled="disabled||!payload">登记规则版本</button></section></fieldset></form></template>
