<script setup lang="ts">
import { gigTitle, gigStatuses, type GigRecord, type RelationParties } from '@/api/modules/gigs'
import { money } from '@/api/modules/trade'
import ContractText from './ContractText.vue'
import type { TextValue } from '@/api/modules/contracts'
const savedText=(v:unknown)=>v as TextValue
const props=defineProps<{record:GigRecord;relationParties?:RelationParties|null}>()
const displayName=(id:string|null)=>props.relationParties?.record_id===props.record.id?props.relationParties.parties.find(p=>p.party_id===id)?.display_name||'名称暂未提供，请结合编号核对':'名称暂未提供，请结合编号核对'
const rankingLabels={window_days:'观察窗口（天）',newcomer_days:'新人观察期（天）',minimum_orders:'最低有效订单数',order_weight:'订单权重',net_minor_weight:'净实收权重',newcomer_bonus:'新人加权'}
</script>
<template><section class="supply-card"><div class="section-heading"><h2>{{gigTitle(record)}}</h2><span class="supply-badge">{{gigStatuses[record.current_status]||record.current_status}}</span></div><dl v-if="record.kind==='RELATION'" class="supply-facts"><div><dt>MCN 显示名称</dt><dd>{{displayName(record.owner_party_id)}}</dd></div><div><dt>合作本人显示名称</dt><dd>{{displayName(record.counterparty_id)}}</dd></div></dl><p v-if="record.kind==='RELATION'" class="muted">显示名称可能变更，不代表已核实的法定名称；请结合编号核对。</p><dl class="supply-facts"><div><dt>登记主体 / 供给方</dt><dd class="identifier">{{record.owner_party_id||'独立规则与榜单记录'}}</dd></div><div><dt>相对方 / 客户</dt><dd class="identifier">{{record.counterparty_id||'此记录没有相对方'}}</dd></div></dl><details class="trade-rules"><summary>编号、原版本与完整内容指纹</summary><p class="identifier">{{record.id}} · 记录版本 {{record.object_version}}</p><p class="identifier">{{record.content_sha256}}</p><p class="identifier">原关联：{{record.parent_id||'无'}}</p></details></section>
<section v-if="record.kind==='RULE'" class="supply-card"><h2>规则 {{record.data.rule.version}}</h2><p class="long-text">{{record.data.rule.terms}}</p><div class="table-wrap"><table><thead><tr><th>类别代码</th><th>允许商业用途</th><th>必需证明</th></tr></thead><tbody><tr v-for="c in record.data.rule.categories" :key="c.code"><td>{{c.code}}</td><td>{{c.allowed?'允许':'禁止'}}</td><td>{{c.required_proofs.join('、')||'无必需证明'}}</td></tr></tbody></table></div><h3>榜单参数</h3><ContractText :value="savedText(record.data.rule.ranking)" :field-labels="rankingLabels"/></section>
<section v-if="record.kind==='GIG'" class="supply-card"><h2>需求与商业范围</h2><p class="long-text">{{record.data.brief}}</p><dl class="supply-facts"><div><dt>类别与用途</dt><dd>{{record.data.category}} · 商业用途</dd></div><div><dt>地域</dt><dd>{{record.data.scope.territory}}</dd></div><div><dt>有效截止</dt><dd>{{record.data.scope.valid_until}}</dd></div><div><dt>采用的规则版本</dt><dd class="identifier">{{record.data.rule_id}}</dd></div></dl><details class="trade-rules"><summary>保存的规则内容指纹</summary><p class="identifier">{{record.data.rule_sha256}}</p></details><p v-if="record.data.suspension" class="long-text">暂停原因：{{record.data.suspension.reason}}</p></section>
<section v-if="record.kind==='RELATION'||record.kind==='OFFER'" class="supply-card"><h2>{{record.kind==='RELATION'?'直接合作范围与原条款':'服务提案与佣金约定'}}</h2><dl class="supply-facts"><template v-if="record.kind==='RELATION'"><div><dt>范围</dt><dd>商业用途</dd></div><div><dt>期限</dt><dd>{{record.data.valid_from}} 至 {{record.data.valid_until}}</dd></div><div><dt>排他安排</dt><dd>{{record.data.exclusive?'排他':'非排他'}}</dd></div></template><template v-else><div><dt>已审服务规格</dt><dd class="identifier">{{record.data.spec_id}}</dd></div><div><dt>本人数字人 / 脸声同意</dt><dd class="identifier">{{record.data.avatar_id}}<br>{{record.data.consent_id}}</dd></div><div><dt>榜单参加</dt><dd>{{record.data.ranking_opt_in?'明确参加':'不参加'}}</dd></div></template><div><dt>平台费率</dt><dd>{{record.data.commission.platform_bps}} bps / {{record.data.commission.platform_bps/100}}%</dd></div><div><dt>MCN 费率（从平台费用中划分）</dt><dd>{{record.data.commission.mcn_bps}} bps / {{record.data.commission.mcn_bps/100}}%</dd></div></dl><p class="long-text">{{record.data.terms}}</p><template v-if="record.kind==='OFFER'"><h3>采用的直接 MCN 合作</h3><template v-if="record.data.relation"><p class="identifier">{{record.data.relation.id}} · 原版本 {{record.data.relation.version}} · MCN {{record.data.relation.mcn_party_id}}</p><p>{{record.data.relation.valid_from}} 至 {{record.data.relation.valid_until}}</p><p class="long-text">{{record.data.relation.terms}}</p><details class="trade-rules"><summary>原合作内容指纹</summary><p class="identifier">{{record.data.relation.sha256}}</p></details></template><p v-else class="muted">未关联 MCN；MCN 费率须明确为零。</p><p class="supply-warning">数字人登记、同意记录及保存的审核意见不等于系统自动完成实名或水印核验。</p></template><p v-else-if="record.data.ended_reason">结束或拒绝原因：{{record.data.ended_reason}}</p></section>
<section v-if="record.kind==='COMMISSION'" class="supply-card"><h2>已核实财务事实与计提</h2><div class="gigs-metrics"><div><span>已收款</span><strong>{{money(record.data.facts.received_minor)}}</strong></div><div><span>已退款</span><strong>{{money(record.data.facts.refunded_minor)}}</strong></div><div><span>净实收</span><strong>{{money(record.data.facts.net_minor)}}</strong></div></div><div class="table-wrap"><table><thead><tr><th>供应方</th><th>平台</th><th>MCN</th></tr></thead><tbody><tr><td>{{money(record.data.amounts.supplier_minor)}}</td><td>{{money(record.data.amounts.platform_minor)}}</td><td>{{money(record.data.amounts.mcn_minor)}}</td></tr></tbody></table></div><p class="muted">{{record.data.facts.environment==='PRODUCTION'?'正式渠道核实事实':record.data.facts.environment==='SANDBOX'?'测试环境事实，不能用于正式排行榜':'尚无渠道收款'}}。按整数分向下取整，再用累计退款重算差额。</p><p class="supply-warning">已计提，未出款。出款、提现与税务接口尚未开放；此记录不会触发转账。</p><details class="trade-rules"><summary>原订单、合同与商业协议</summary><p class="identifier">订单 {{record.data.order_id}} · 合同 {{record.data.contract_sha256}}</p><ContractText :value="savedText(record.data.agreement)" :field-labels="{terms:'原条款',commission:'原佣金比例',platform_bps:'平台费率（bps）',mcn_bps:'MCN费率（bps）',relation:'原直接MCN关系',ranking_opt_in:'参加榜单',offer_id:'原服务提案',offer_sha256:'原提案指纹',gig_id:'原商单',scope:'原范围',purpose:'用途',territory:'地域',valid_until:'截止时间',category:'类别',avatar_id:'数字人',consent_id:'同意记录',rule_id:'原规则'}"/></details></section>
<section v-if="'review' in record.data&&record.data.review" class="supply-card"><h2>保存的独立审核意见</h2><p>{{record.data.review.decision==='APPROVED'?'已批准':'已拒绝'}} · 外部人工核验</p><p class="long-text">{{record.data.review.reason}}</p><p class="identifier">审核账号：{{record.data.review.account_id}}</p></section>
</template>
