<script setup lang="ts">
import { computed, reactive } from 'vue'
import { isTerms, minorInteger, rights, purposes, type LicenseRecord, type ProductData } from '@/api/modules/licensing'
import { validSupplyId, shortSupplyId, type WorkRecord } from '@/api/modules/supply'
const props = defineProps<{ works: WorkRecord[]; products: LicenseRecord[]; disabled: boolean }>()
const emit = defineEmits<{ submit: [input: Omit<ProductData,'review'> & { previous_product_id: string | null }] }>()
const f = reactive({work:'',previous:'',title:'',preview:'',exclusive:'',rights:[] as (keyof typeof rights)[],purposes:[] as (keyof typeof purposes)[],territories:'',languages:'',start:'',development:'',until:'',projects:'',episodes:'',terms:'',currency:'',amount:'',due:'',minutes:'',rule:''})
const split = (s: string) => s.split(/[\s,，、]+/).filter(Boolean)
const iso = (s: string) => s && Number.isFinite(Date.parse(s)) ? new Date(s).toISOString() : ''
const payload = computed(() => ({work_version_id:f.work,previous_product_id:f.previous || null,title:f.title.trim(),preview_text:f.preview.trim(),terms:{exclusive:f.exclusive === 'yes',rights:[...f.rights],purposes:[...f.purposes],territories:split(f.territories),languages:split(f.languages),valid_from:iso(f.start),development_until:iso(f.development),valid_until:iso(f.until),project_limit:minorInteger(f.projects) ?? 0,episode_limit:minorInteger(f.episodes) ?? 0,terms_text:f.terms.trim()},price:{currency:f.currency.trim(),amount_minor:minorInteger(f.amount) ?? -1},payment_due_minor:minorInteger(f.due) ?? -1,reservation_minutes:minorInteger(f.minutes) ?? 0,rule_id:f.rule.trim()}))
const previousOptions = computed(() => props.products.filter(p => p.kind === 'PRODUCT' && p.work_id === props.works.find(w => w.id === f.work)?.stream_ref))
const valid = computed(() => validSupplyId(f.work) && (!f.previous || previousOptions.value.some(p => p.id === f.previous)) && f.title.trim().length > 0 && f.preview.trim().length > 0 && !!f.exclusive && isTerms(payload.value.terms) && /^[A-Z]{3}$/.test(payload.value.price.currency) && payload.value.price.amount_minor >= 0 && payload.value.payment_due_minor >= 0 && payload.value.payment_due_minor <= payload.value.price.amount_minor && payload.value.reservation_minutes > 0 && payload.value.reservation_minutes <= 10080 && validSupplyId(payload.value.rule_id))
const issues = computed(() => {
  const errors:string[]=[]
  if(f.previous && !previousOptions.value.some(p=>p.id===f.previous))errors.push('上一商品必须与当前原作属于同一作品，请重新选择。')
  if(f.currency && !/^[A-Z]{3}$/.test(f.currency.trim()))errors.push('币种须使用大写三位代码。')
  if([f.amount,f.due,f.projects,f.episodes,f.minutes].some(v=>v && minorInteger(v)===null))errors.push('金额、项目、集数与分钟须是安全范围内的整数；不填写小数、负数或前导零。')
  if(f.amount && f.due && payload.value.payment_due_minor > payload.value.price.amount_minor)errors.push('生效前应付金额不能超过总价。')
  if([f.projects,f.episodes].some(v=>v && (minorInteger(v)===0 || Number(v)>100000)))errors.push('项目与集数额度须在 1 至 100000 之间。')
  if(f.minutes && (Number(f.minutes)<1 || Number(f.minutes)>10080))errors.push('预留时长须在 1 至 10080 分钟之间。')
  if(f.start && f.development && f.until && !(Date.parse(f.start)<Date.parse(f.development) && Date.parse(f.development)<=Date.parse(f.until)))errors.push('许可开始须早于开发截止；开发截止不能晚于有效截止。')
  if(f.territories && split(f.territories).some(v=>!/^(WORLD|[A-Z]{2})$/.test(v)))errors.push('地域须是双方核验的两位大写国家代码或 WORLD。')
  if(f.languages && split(f.languages).some(v=>!/^(ALL|[a-z]{2})$/.test(v)))errors.push('语言须是两位小写代码或 ALL。')
  if([f.territories,f.languages].some(v=>v && new Set(split(v)).size!==split(v).length))errors.push('地域和语言代码不能重复填写。')
  if(f.rule && !validSupplyId(f.rule.trim()))errors.push('请填写准确的规则版本编号（小写 UUID）。')
  return errors
})
</script>
<template>
  <form class="license-form" @submit.prevent="valid && emit('submit',payload)"><fieldset :disabled="disabled">
    <section class="supply-card"><h2>一、已双审原作与商品版本</h2><div class="supply-fields"><label class="supply-field"><span class="field-label">已完成双审的原作版本 *</span><select v-model="f.work" required><option value="">请选择明确版本</option><option v-for="w in works" :key="w.id" :value="w.id">{{ w.data.version.content.title }} · 第 {{ w.revision }} 版 · {{ shortSupplyId(w.id) }}</option></select></label><label class="supply-field"><span class="field-label">上一许可商品（首次留空）</span><select v-model="f.previous"><option value="">首次创建</option><option v-for="p in previousOptions" :key="p.id" :value="p.id">{{ p.kind === 'PRODUCT' ? p.data.title : '' }} · {{ shortSupplyId(p.id) }}</option></select></label></div><p v-if="!works.length" class="supply-warning">当前没有可选的双审原作。请先完成供给申请与作品权属、内容审核。</p></section>
    <section class="supply-card"><h2>二、商品标题与短试读</h2><label class="supply-field"><span class="field-label">商品标题 *</span><input v-model="f.title" maxlength="200" required placeholder="填写本次许可商品名称"></label><label class="full-field"><span class="field-label">经人工核验的短试读 *</span><textarea v-model="f.preview" maxlength="2000" required placeholder="仅填写已获准展示的短试读，不复制全文" /></label></section>
    <section class="supply-card"><h2>三、许可范围、期限与额度</h2><div class="supply-fields"><label class="supply-field"><span class="field-label">是否独家 *</span><select v-model="f.exclusive" required><option value="">请主动选择</option><option value="yes">独家（仅限约定范围）</option><option value="no">非独家</option></select></label><div class="supply-field"><p class="field-label">获准权利 *</p><div class="license-checks"><label v-for="(label,key) in rights" :key="key"><input v-model="f.rights" type="checkbox" :value="key">{{ label }}</label></div></div><div class="supply-field"><p class="field-label">允许用途 *</p><div class="license-checks"><label v-for="(label,key) in purposes" :key="key"><input v-model="f.purposes" type="checkbox" :value="key">{{ label }}</label></div></div><label class="supply-field"><span class="field-label">地域代码 *</span><input v-model="f.territories" required placeholder="双方核验的两位国家代码或 WORLD，逗号分隔"></label><label class="supply-field"><span class="field-label">语言代码 *</span><input v-model="f.languages" required placeholder="两位小写语言代码或 ALL，逗号分隔"></label><label class="supply-field"><span class="field-label">许可开始（本地时间） *</span><input v-model="f.start" type="datetime-local" required></label><label class="supply-field"><span class="field-label">开发截止（本地时间） *</span><input v-model="f.development" type="datetime-local" required></label><label class="supply-field"><span class="field-label">有效截止（本地时间） *</span><input v-model="f.until" type="datetime-local" required></label><label class="supply-field"><span class="field-label">项目数量上限 *</span><input v-model="f.projects" inputmode="numeric" pattern="[0-9]+" required></label><label class="supply-field"><span class="field-label">每项目集数上限 *</span><input v-model="f.episodes" inputmode="numeric" pattern="[0-9]+" required></label></div><p class="muted">独家不自动包含发行权。复杂地域或语言条件须先人工整理成有依据、可表达的条款。</p></section>
    <section class="supply-card"><h2>四、金额与预留条件</h2><div class="supply-fields"><label class="supply-field"><span class="field-label">币种（大写三位代码） *</span><input v-model="f.currency" maxlength="3" pattern="[A-Z]{3}" required></label><label class="supply-field"><span class="field-label">总价（{{ f.currency === 'CNY' ? '整数分' : '整数最小币种单位' }}） *</span><input v-model="f.amount" inputmode="numeric" pattern="[0-9]+" required></label><label class="supply-field"><span class="field-label">生效前应付（{{ f.currency === 'CNY' ? '整数分' : '整数最小币种单位' }}） *</span><input v-model="f.due" inputmode="numeric" pattern="[0-9]+" required></label><label class="supply-field"><span class="field-label">预留时长（分钟） *</span><input v-model="f.minutes" inputmode="numeric" pattern="[0-9]+" required></label></div><p class="muted">CNY 的最小单位为分，例如 100 分＝1 元。其他币种按双方已核验的最小单位填写。金额、期限、额度及首款比例均须明确约定，不自动补值。</p></section>
    <section class="supply-card"><h2>五、完整条款、规则依据与提交</h2><label class="supply-field"><span class="field-label">完整约定条款 *</span><textarea v-model="f.terms" maxlength="8000" required /></label><label class="supply-field"><span class="field-label">已核验生效的规则版本编号 *</span><input v-model.trim="f.rule" required placeholder="准确的规则版本编号"></label><p class="muted">当前没有公共有效规则目录。请向规则维护人员核对版本编号及适用内容；服务器提交时再次检查。</p><ul v-if="issues.length" class="form-error" role="alert"><li v-for="issue in issues" :key="issue">{{ issue }}</li></ul><div class="license-form-footer"><p class="muted">提交后等待独立核验。改价或改条款须创建新商品版本；历史约定保留。</p><button class="primary" :disabled="disabled || !valid">提交许可商品审核</button></div></section>
  </fieldset></form>
</template>
