<script setup lang="ts">
import { productionStatus, stages, operations, type ProductionRecord } from '@/api/modules/production'
import ContractText from './ContractText.vue'
defineProps<{record:ProductionRecord;compact?:boolean}>()
</script>
<template>
 <section class="supply-card production-summary"><div class="section-heading"><h2>{{record.kind==='PROJECT'?'当前制作项目':record.kind==='VERSION'?`${stages[record.data.stage]} · 第 ${record.data.revision} 版`:record.kind==='GENERATION'?operations[record.data.operation]:'当前制作记录'}}</h2><span class="supply-badge">{{productionStatus(record)}}</span></div><template v-if="record.kind==='PROJECT'"><dl class="supply-facts"><div><dt>原订单制作明细</dt><dd>{{record.data.line_id}}</dd></div><div><dt>负责人账号</dt><dd class="identifier">{{record.data.assignee_account_id}}</dd></div><div><dt>用途与地域</dt><dd>{{record.data.purpose}} · {{record.data.territory}}</dd></div><div><dt>客户已提修改</dt><dd>{{record.data.change_requests}} 次 / 原约定 {{record.data.specification.revision_limit}} 次</dd></div></dl><p class="muted">内部通过与客户验收分别记录；新版本会重新核对本阶段及后续阶段。</p></template><p v-if="record.kind==='VERSION'" class="long-text">{{record.data.note}}</p><p v-if="record.kind==='GENERATION'" class="muted">请求记录不等于实际任务已完成；视频结果仍需导入私有文件、独立审片与客户验收。</p><details class="trade-rules"><summary>记录编号与原始依据</summary><dl class="supply-facts"><div><dt>记录编号</dt><dd class="identifier">{{record.id}}</dd></div><div><dt>原订单编号</dt><dd class="identifier">{{record.order_id}}</dd></div><div><dt>记录版本</dt><dd>{{record.object_version}}</dd></div><div><dt>保存内容指纹</dt><dd class="identifier">{{record.content_sha256}}</dd></div><template v-if="record.kind==='PROJECT'"><div><dt>买方 / 商家 / 制作方</dt><dd class="identifier">{{record.data.buyer_party_id}}<br>{{record.data.merchant_party_id}}<br>{{record.data.producer_party_id}}</dd></div><div><dt>已审剧本 / 许可项目</dt><dd class="identifier">{{record.data.script_version_id}}<br>{{record.data.license_project_id||'原订单无许可项目'}}</dd></div><div><dt>开工依据 / 合同指纹</dt><dd class="identifier">{{record.data.evidence_asset_id}}<br>{{record.data.contract_sha256}}</dd></div><div><dt>同意记录</dt><dd class="identifier">{{record.data.consent_ids.join('、')||'未引用同意记录'}}</dd></div></template><template v-if="record.kind==='VERSION'"><div><dt>原文件 / 预览文件</dt><dd class="identifier">{{record.data.file_id}}<br>{{record.data.preview_file_id}}</dd></div><div><dt>前阶段验收版本</dt><dd class="identifier">{{record.data.basis_version_id||'剧本阶段无前阶段'}}</dd></div></template></dl></details></section>
 <section v-if="record.kind==='PROJECT'" class="supply-card"><h2>原订单规格与阶段</h2><dl class="trade-snapshot"><div><dt>服务档位与规格版本</dt><dd>{{record.data.specification.service_tier}} · {{record.data.specification.version}}</dd></div><div><dt>样片 / 成片时长</dt><dd>{{record.data.specification.sample_seconds}} 秒 / {{record.data.specification.final_seconds}} 秒 · 数量 {{record.data.quantity}}</dd></div><div><dt>约定交付</dt><dd><ul><li v-for="text in record.data.specification.deliverables" :key="text">{{text}}</li></ul></dd></div></dl><div class="table-wrap"><table><thead><tr><th>阶段</th><th>当前版本</th><th>客户验收</th></tr></thead><tbody><tr v-for="(label,stage) in stages" :key="stage"><td>{{label}}</td><td>{{record.data.current[stage]?'第 '+(record.data.revisions[stage]||'')+' 版':'尚未提交'}}</td><td>{{record.data.current[stage]&&record.data.accepted[stage]===record.data.current[stage]?'当前版已验收':'未验收当前版'}}</td></tr></tbody></table></div><details class="trade-rules"><summary>原服务条款及具体阶段编号</summary><p class="long-text">{{record.data.specification.terms}}</p><ContractText :value="record.data.current"/><ContractText :value="record.data.accepted"/></details></section>
 <section v-if="'review' in record.data&&record.data.review" class="supply-card"><h2>已保存独立核验</h2><p>{{record.data.review.decision==='APPROVED'?'独立核验通过':'独立核验拒绝'}} · {{record.data.review.reason}}</p><details class="trade-rules"><summary>核验账号与具体检查</summary><p class="identifier">{{record.data.review.account_id}}</p><ContractText :value="record.data.review.verification"/></details><p class="muted">此处是实际外部材料的人工核验记录，不代表平台完成签署、实名验证或自动音画检查。</p></section>
 <slot/>
</template>
