<script setup lang="ts">
import { layers,type Layer,type ProjectRecord } from '@/api/modules/projects'
import type { ProductionRecord } from '@/api/modules/production'
import type { TradeRecord } from '@/api/modules/trade'
import { money } from '@/api/modules/trade'
import SupplyUpload from './SupplyUpload.vue'
import type { MediaType } from '@/api/modules/supply'
export interface RightDraft {layer:Layer;holder:string;purpose:string;territory:string;until:string;terms:string;asset:string}
export interface SignerDraft {party:string;responsibility:string;after:string}
export interface FundingDraft {candidate:string;order:string;line:string}
const props=defineProps<{rights:RightDraft[];signers:SignerDraft[];funding:FundingDraft[];production:string;terms:string;productions:ProductionRecord[];orders:TradeRecord[];candidates:ProjectRecord[];assets:string[];disabled:boolean}>()
const emit=defineEmits<{ 'update:production':[value:string];'update:terms':[value:string];upload:[file:File,media:MediaType];remove:[id:string];'check-production':[];'add-signer':[];'add-funding':[]}>()
const lines=(id:string)=>{const r=props.orders.find(x=>x.id===id);return r?.kind==='ORDER'?r.data.quote.lines.filter(x=>x.line_kind==='OTHER'):[]}
</script>
<template><section class="supply-card"><h2>制作项目关联</h2><label>实际制作项目 *<input :value="production" @input="emit('update:production',($event.target as HTMLInputElement).value)" list="project-productions" data-testid="plan-production" required placeholder="选择本人可读制作项目或输入真实编号"><datalist id="project-productions"><option v-for="p in productions" :key="p.id" :value="p.id">{{p.current_status}}</option></datalist></label><button type="button" class="outline" :disabled="disabled" @click="emit('check-production')">读取制作项目依据</button><p class="muted">发行仍需原制作有效、真实权利与付款；新授权不能覆盖原私人制作历史。</p></section>
<section class="supply-card"><h2>六层权利依据</h2><SupplyUpload label="项目权利证明" :ids="assets" :disabled="disabled" @upload="(f,m)=>emit('upload',f,m)" @remove="id=>emit('remove',id)"/><div class="project-right-grid"><article v-for="r in rights" :key="r.layer" class="project-right-row"><h3>{{layers[r.layer]}}</h3><div class="trade-fields two"><label>权利主体 *<input v-model="r.holder" :data-testid="`right-${r.layer}-holder`" required placeholder="真实权利主体编号"></label><label>私有依据 *<input v-model="r.asset" list="project-proof-assets" :data-testid="`right-${r.layer}-asset`" required placeholder="已上传的本方证明编号"></label><label>用途 *<select v-model="r.purpose" :data-testid="`right-${r.layer}-purpose`" required><option value="">待明确选择</option><option value="PUBLIC_SHARE">公开分享</option><option value="RELEASE">发行</option></select></label><label>地域 *<input v-model="r.territory" :data-testid="`right-${r.layer}-territory`" maxlength="2" required placeholder="两位地域代码"></label><label>有效至 *<input type="datetime-local" v-model="r.until" :data-testid="`right-${r.layer}-until`" required></label><label>实际条款 *<textarea v-model="r.terms" :data-testid="`right-${r.layer}-terms`" required maxlength="8000"></textarea></label></div></article></div><datalist id="project-proof-assets"><option v-for="id in assets" :key="id" :value="id"/></datalist></section>
<div class="project-columns"><section class="supply-card"><h2>确认人与前置顺序</h2><article v-for="(s,index) in signers" :key="index" class="project-form-row"><label>确认主体 *<input v-model="s.party" :data-testid="`confirmer-${index}-party`" required></label><label>责任说明 *<textarea v-model="s.responsibility" :data-testid="`confirmer-${index}-responsibility`" required maxlength="1000"></textarea></label><label>前置主体编号（无前置方则留空）<input v-model="s.after" :data-testid="`confirmer-${index}-after`" placeholder="多个编号用逗号分隔"></label><button type="button" class="text-button" @click="signers.splice(index,1)">移除确认方</button></article><button type="button" class="outline" :disabled="signers.length>=50" @click="emit('add-signer')">添加确认方</button><p class="muted">确认方来自发起方、入选方、权利持有人、脸声本人及制作方；明确填写前置顺序，不自行加入无关方。</p></section>
<section class="supply-card"><h2>角色费用的真实订单来源</h2><article v-for="(f,index) in funding" :key="index" class="project-form-row"><label>已确认候选 *<select v-model="f.candidate" :data-testid="`funding-${index}-candidate`" required><option value="">待选择</option><option v-for="c in candidates.filter(c=>c.kind==='CANDIDATE'&&c.current_status==='CONFIRMED'&&Number(c.data.amount_minor)>0)" :key="c.id" :value="c.id">{{c.owner_party_id}} · {{c.kind==='CANDIDATE'&&c.data.amount_minor!==null?money(c.data.amount_minor):''}}</option></select></label><label>已付款角色订单 *<select v-model="f.order" :data-testid="`funding-${index}-order`" @change="f.line=''" required><option value="">待选择本人可读原订单</option><option v-for="o in orders" :key="o.id" :value="o.id">{{o.id}} · {{o.current_status}}</option></select></label><label>OTHER 角色明细 *<select v-model="f.line" :data-testid="`funding-${index}-line`" required><option value="">待选择</option><option v-for="l in lines(f.order)" :key="l.line_id" :value="l.line_id">{{l.title}} · {{money(l.total_minor)}}</option></select></label><button type="button" class="text-button" @click="funding.splice(index,1)">移除付款关联</button></article><button type="button" class="outline" :disabled="funding.length>=100" @click="emit('add-funding')">添加角色付款关联</button><p class="muted">明确约定零元的候选不填付款关联；制作费和许可费不能充当角色费。</p></section></div>
<section class="supply-card"><h2>完整方案条款</h2><label>方案条款 *<textarea :value="terms" @input="emit('update:terms',($event.target as HTMLTextAreaElement).value)" data-testid="plan-terms" required maxlength="8000"></textarea></label></section></template>
