<script setup lang="ts">
import { layers,kindLabels,projectStatus,type ProjectRecord } from '@/api/modules/projects'
import { money } from '@/api/modules/trade'
import { shortSupplyId } from '@/api/modules/supply'
import ContractText from './ContractText.vue'
import type { TextValue } from '@/api/modules/contracts'
const textValue=(value:unknown):TextValue=>JSON.parse(JSON.stringify(value))
defineProps<{record:ProjectRecord}>()
</script>
<template><section class="supply-card project-record"><div class="project-record-title"><h2>{{record.kind==='PROJECT'?record.data.title:record.kind==='ROLE'?record.data.title:record.kind==='CHANNEL'?record.data.name:kindLabels[record.kind]}}</h2><span class="status-chip">{{projectStatus(record)}}</span></div>
<dl v-if="record.kind==='PROJECT'" class="supply-facts"><div><dt>用途</dt><dd>{{record.data.scope.purpose==='RELEASE'?'发行':'公开分享'}}</dd></div><div><dt>地域 / 语言</dt><dd>{{record.data.scope.territory}} / {{record.data.scope.language}}</dd></div><div><dt>有效期</dt><dd>{{record.data.scope.valid_until}}</dd></div><div><dt>当前方案</dt><dd>{{record.data.current_plan_id?shortSupplyId(record.data.current_plan_id):'尚未提交'}}</dd></div></dl>
<template v-if="record.kind==='ROLE'||record.kind==='CANDIDATE'"><dl class="supply-facts"><div><dt>金额</dt><dd>{{record.data.amount_minor===null?'待明确报价':money(record.data.amount_minor)}}</dd></div><div><dt>所属主体</dt><dd>{{shortSupplyId(record.owner_party_id)}}</dd></div><template v-if="record.kind==='CANDIDATE'"><div><dt>数字人</dt><dd>{{record.data.avatar_id?shortSupplyId(record.data.avatar_id):'尚未提供'}}</dd></div><div><dt>本人同意</dt><dd>{{record.data.consent_id?shortSupplyId(record.data.consent_id):'尚未提供'}}</dd></div></template></dl><p class="long-text">{{record.data.terms}}</p><p v-if="record.kind==='CANDIDATE'&&record.data.note" class="long-text">{{record.data.note}}</p></template>
<template v-if="record.kind==='PLAN'"><h3>六层权利依据</h3><div class="table-wrap"><table><thead><tr><th>权利层</th><th>持有人</th><th>范围与期限</th><th>实际条款</th></tr></thead><tbody><tr v-for="right in record.data.rights" :key="right.layer"><td>{{layers[right.layer]}}</td><td :title="right.holder_party_id">{{shortSupplyId(right.holder_party_id)}}</td><td>{{right.purpose==='RELEASE'?'发行':'公开分享'}} · {{right.territory}}<br>{{right.valid_until}}</td><td class="long-text">{{right.terms}}</td></tr></tbody></table></div><h3>方案条款</h3><p class="long-text">{{record.data.terms}}</p><details class="trade-rules"><summary>角色付款来源与制作编号</summary><p class="identifier">{{record.data.production_project_id}}</p><ContractText :value="textValue(record.data.funding)"/></details></template>
<template v-if="record.kind==='PLAN'||record.kind==='EDITION'"><h3>确认方与前置顺序</h3><div class="table-wrap"><table><thead><tr><th>主体</th><th>责任</th><th>前置主体</th></tr></thead><tbody><tr v-for="signer in record.data.confirmers" :key="signer.party_id"><td :title="signer.party_id">{{shortSupplyId(signer.party_id)}}</td><td class="long-text">{{signer.responsibility}}</td><td>{{signer.after_party_ids.map(shortSupplyId).join('、')||'无前置方'}}</td></tr></tbody></table></div></template>
<template v-if="record.kind==='EDITION'"><dl class="supply-facts"><div><dt>实际成片版本</dt><dd :title="record.data.final_version_id">{{shortSupplyId(record.data.final_version_id)}}</dd></div><div><dt>关联材料</dt><dd>{{record.data.material_asset_ids.length}} 份私有材料</dd></div></dl><p class="long-text">{{record.data.note}}</p></template>
<template v-if="record.kind==='CHANNEL'"><p>外部参考：{{record.data.channel_reference}}</p><h3>渠道提交要求</h3><p class="long-text">{{record.data.submission_requirements}}</p></template>
<template v-if="record.kind==='RELEASE'"><dl class="supply-facts"><div><dt>成片材料版</dt><dd>{{shortSupplyId(record.data.edition_id)}}</dd></div><div><dt>实际渠道</dt><dd>{{shortSupplyId(record.data.channel_id)}}</dd></div><div><dt>前次申请</dt><dd>{{record.data.prior_release_id?shortSupplyId(record.data.prior_release_id):'首次申请'}}</dd></div></dl><p class="long-text">{{record.data.note}}</p><p class="muted">内部审核通过只表示可向外部送出；外部发行和撤下均须另存实际凭据并独立核实。</p></template>
<template v-if="record.kind==='EXTERNAL_EVENT'"><dl class="supply-facts"><div><dt>报告结果</dt><dd>{{record.data.outcome}}</dd></div><div><dt>实际发生时间</dt><dd>{{record.data.occurred_at}}</dd></div></dl><p>外部参考：{{record.data.external_reference}}</p><p class="long-text">{{record.data.note}}</p><p class="muted">当前是人工外部报告；独立核实通过后才改变发行事实。</p></template>
<template v-if="'review' in record.data&&record.data.review"><h3>历史核验结论</h3><p>{{record.data.review.decision}} · {{record.data.review.reason}}</p></template>
<details class="trade-rules"><summary>记录编号、内容版本与原始事实</summary><p class="identifier">{{record.id}} · 版本 {{record.object_version}}<br>{{record.content_sha256}}</p><ContractText :value="textValue(record.data)"/></details></section></template>
