<script setup lang="ts">
import { creditRoles, recordTitle, shortSupplyId, supplyStatus, type SupplyAsset, type SupplyRecord } from '@/api/modules/supply'
defineProps<{ record: SupplyRecord; assets: Record<string, SupplyAsset>; busy?: boolean; contentFirst?: boolean }>()
const emit = defineEmits<{ info: [id: string]; download: [id: string] }>()
const time = (v: string) => new Date(v).toLocaleString('zh-CN', { hour12: false })
</script>
<template>
  <section class="supply-card"><div class="section-heading"><h2>{{ recordTitle(record) }}</h2><span class="supply-badge">{{ supplyStatus[record.current_status] }}</span></div><dl class="supply-facts"><div><dt>记录编号</dt><dd :title="record.id" :aria-label="record.id">{{ shortSupplyId(record.id) }}</dd></div><div><dt>修订</dt><dd>第 {{ record.revision }} 版</dd></div><div><dt>{{ record.kind === 'WORK_VERSION' ? '作品编号' : '主体编号' }}</dt><dd :title="record.stream_ref" :aria-label="record.stream_ref">{{ shortSupplyId(record.stream_ref) }}</dd></div><div><dt>提交账号</dt><dd :title="record.created_by" :aria-label="record.created_by">{{ shortSupplyId(record.created_by) }}</dd></div></dl>
    <p v-if="record.kind === 'PROFILE'" class="long-text">{{ record.data.description }}</p>
    <p v-else-if="record.current_status === 'REVIEWS_COMPLETE'" class="muted">双审结论已记录；作品上架、签约、许可和发行分别办理。</p>
    <details class="supply-identifiers"><summary>查看完整记录与身份编号</summary><dl class="supply-facts"><div><dt>记录编号</dt><dd>{{ record.id }}</dd></div><div><dt>{{ record.kind === 'WORK_VERSION' ? '作品编号' : '主体编号' }}</dt><dd>{{ record.stream_ref }}</dd></div><div><dt>提交账号</dt><dd>{{ record.created_by }}</dd></div><div><dt>供给身份</dt><dd>{{ record.owner_party_id }}</dd></div></dl></details>
  </section>
  <template v-if="record.kind === 'WORK_VERSION'">
    <template v-for="section in (contentFirst ? ['content', 'credits'] : ['credits', 'content'])" :key="section">
      <section v-if="section === 'credits'" class="supply-card"><h2>作者、权利人和代理</h2><div class="table-wrap"><table><thead><tr><th>主体编号</th><th>权利角色</th><th>私有证明</th></tr></thead><tbody><tr v-for="c in record.data.credits" :key="`${c.party_id}:${c.role}`"><td class="identifier" :title="c.party_id" :aria-label="c.party_id">{{ shortSupplyId(c.party_id) }}</td><td>{{ creditRoles[c.role] }}</td><td><div v-for="id in c.evidence_asset_ids" :key="id" class="material-line"><span :title="id" :aria-label="id">{{ shortSupplyId(id) }}</span><button type="button" :disabled="busy" @click="emit('download', id)">获准下载</button></div></td></tr></tbody></table></div></section>
      <section v-else class="supply-card"><h2>当前版本正文</h2><p class="muted">{{ record.data.version.content.kind === 'ORIGINAL' ? '原作' : '项目改稿' }}</p><div class="material-line"><span :title="record.data.version.content.content_asset_id" :aria-label="record.data.version.content.content_asset_id">{{ shortSupplyId(record.data.version.content.content_asset_id) }}</span><button class="outline" type="button" :disabled="busy" @click="emit('info', record.data.version.content.content_asset_id)">查看材料信息</button><button class="primary" type="button" :disabled="busy" @click="emit('download', record.data.version.content.content_asset_id)">下载当前正文</button></div><dl v-if="assets[record.data.version.content.content_asset_id]" class="supply-facts asset-facts"><div><dt>大小</dt><dd>{{ assets[record.data.version.content.content_asset_id]!.byte_size }} 字节</dd></div><div><dt>内容指纹</dt><dd>{{ assets[record.data.version.content.content_asset_id]!.content_sha256 }}</dd></div></dl></section>
    </template>
  </template>
  <section class="supply-card"><h2>{{ record.kind === 'PROFILE' ? '申请权利材料' : '作品证明材料' }}</h2><div v-for="id in (record.kind === 'PROFILE' ? record.data.evidence_asset_ids : record.data.version.content.evidence_ids)" :key="id" class="material-row"><div class="material-line"><span :title="id" :aria-label="id">{{ shortSupplyId(id) }}</span><button type="button" :disabled="busy" @click="emit('info', id)">查看信息</button><button class="outline" type="button" :disabled="busy" @click="emit('download', id)">获准下载</button></div><p v-if="assets[id]" class="muted">{{ assets[id]!.byte_size }} 字节 · 内容指纹 {{ assets[id]!.content_sha256 }}</p></div></section>
  <section class="supply-card"><h2>已记录的审核意见</h2>
    <template v-if="record.kind === 'PROFILE'"><div v-if="record.data.review" class="review-note"><strong>{{ supplyStatus[record.data.review.decision] }}</strong><p class="long-text">{{ record.data.review.reason }}</p><p class="muted">审核账号 <span :title="record.data.review.reviewer_account_id" :aria-label="record.data.review.reviewer_account_id">{{ shortSupplyId(record.data.review.reviewer_account_id) }}</span> · {{ time(record.data.review.recorded_at) }}</p></div><p v-else class="muted">本修订尚无审核结论。</p></template>
    <template v-else><div v-for="channel in (['RIGHTS','CONTENT'] as const)" :key="channel" class="review-note"><strong>{{ channel === 'RIGHTS' ? '权属审核' : '内容审核' }}</strong><template v-for="r in record.data.version.reviews.filter(r => r.channel === channel)" :key="r.channel"><span class="supply-badge">{{ supplyStatus[r.decision] }}</span><p class="long-text">{{ r.reason }}</p><p class="muted">审核账号 <span :title="r.reviewer_account_id" :aria-label="r.reviewer_account_id">{{ shortSupplyId(r.reviewer_account_id) }}</span> · {{ time(r.recorded_at) }}</p></template><p v-if="!record.data.version.reviews.some(r => r.channel === channel)" class="muted">{{ record.data.version.current_status === 'DRAFT' ? '尚未提交审核' : '尚无该轨结论' }}</p></div><div v-if="record.data.version.withdrawal" class="review-note"><strong>撤回说明</strong><p class="long-text">{{ record.data.version.withdrawal.reason }}</p><p class="muted">{{ time(record.data.version.withdrawal.recorded_at) }}</p></div></template>
  </section>
</template>

<style scoped>.supply-identifiers{margin-top:16px;font-size:14px}.supply-identifiers summary{cursor:pointer;color:var(--ops-ink);padding:6px 0;line-height:1.8}.supply-identifiers .supply-facts{margin-top:16px}</style>
