<script setup lang="ts">
import { computed } from 'vue'
import { lineKinds, money, tradeContractLabels, tradeStatus, triggers, type TradeRecord } from '@/api/modules/trade'
import ContractText from './ContractText.vue'
const props=defineProps<{record:TradeRecord;compact?:boolean}>()
const quote=computed(()=>props.record.kind==='QUOTE'?props.record.data:props.record.kind==='ORDER'?props.record.data.quote:null)
</script>
<template>
 <section class="supply-card"><h2>{{record.kind==='SPEC'?'规格快照':record.kind==='REFUND'?'本次退款申请':record.kind==='PAYMENT'?'支付尝试和真实状态':record.kind==='LEGACY'?'保存的历史原始依据':'买卖主体与记录'}}</h2><div class="section-heading"><strong v-if="record.kind==='SPEC'">{{record.data.title}}</strong><strong v-else-if="quote" class="trade-amount">{{money(quote.total_minor)}}</strong><strong v-else-if="record.kind==='PAYMENT'||record.kind==='REFUND'" class="trade-amount">{{money(record.data.amount_minor)}}</strong><span class="supply-badge">{{tradeStatus(record)}}</span></div><dl class="supply-facts"><div><dt>买方主体</dt><dd class="identifier">{{record.buyer_party_id||'此规格尚未关联买方'}}</dd></div><div><dt>商家主体</dt><dd class="identifier">{{record.merchant_party_id}}</dd></div></dl><details class="trade-rules"><summary>记录编号、版本与内容指纹</summary><dl class="supply-facts"><div><dt>记录编号</dt><dd class="identifier">{{record.id}}</dd></div><div><dt>记录版本</dt><dd>{{record.object_version}}</dd></div><div><dt>内容指纹</dt><dd class="identifier">{{record.content_sha256}}</dd></div></dl></details></section>
 <section v-if="record.kind==='SPEC'" class="supply-card"><h2>具体规格与交付约定</h2><dl class="trade-snapshot"><div><dt>商品名称</dt><dd>{{record.data.title}}</dd></div><div><dt>实际提供方</dt><dd class="identifier">{{record.data.provider_party_id}}</dd></div><div><dt>明细类型与单价</dt><dd>{{lineKinds[record.data.line_kind]}} · {{money(record.data.unit_minor)}} / CNY</dd></div><div><dt>规格版本与档位</dt><dd>{{record.data.specification.version}} · {{record.data.specification.service_tier}}</dd></div><div><dt>样片与成片时长</dt><dd>{{record.data.specification.sample_seconds}} 秒 / {{record.data.specification.final_seconds}} 秒</dd></div><div><dt>可修改次数</dt><dd>{{record.data.specification.revision_limit}}</dd></div><div><dt>交付内容</dt><dd><ul><li v-for="d in record.data.specification.deliverables" :key="d">{{d}}</li></ul></dd></div><div><dt>完整条款</dt><dd class="long-text">{{record.data.specification.terms}}</dd></div><div><dt>上一版本</dt><dd class="identifier">{{record.parent_id||'首次版本'}}</dd></div></dl></section>
 <slot/><template v-if="quote"><section class="supply-card"><h2>服务规格快照与总额</h2><p class="trade-amount">{{money(quote.total_minor)}} <span class="muted">/ CNY</span></p><article v-for="l in quote.lines" :key="l.line_id" class="trade-row"><h3>{{l.title}} · {{money(l.total_minor)}}</h3><p class="muted">{{money(l.unit_minor)}} × {{l.quantity}} · {{l.specification.service_tier}}</p><details class="trade-rules"><summary>查看本项完整规格与条款</summary><dl class="supply-facts"><div><dt>明细 / 规格 / 版本</dt><dd class="identifier">{{l.line_id}} · {{l.spec_id}} · {{l.spec_version}}</dd></div><div><dt>单价与数量</dt><dd>{{money(l.unit_minor)}} × {{l.quantity}}</dd></div><div><dt>实际提供方</dt><dd class="identifier">{{l.provider_party_id}}</dd></div><div><dt>服务档位与规格版本</dt><dd>{{l.specification.service_tier}} · {{l.specification.version}}</dd></div><div><dt>样片 / 成片 / 修改</dt><dd>{{l.specification.sample_seconds}} 秒 / {{l.specification.final_seconds}} 秒 / {{l.specification.revision_limit}} 次</dd></div><div><dt>明细类型</dt><dd>{{lineKinds[l.line_kind]}}</dd></div></dl><h4>交付内容</h4><ul><li v-for="d in l.specification.deliverables" :key="d">{{d}}</li></ul><h4>本项条款</h4><p class="long-text">{{l.specification.terms}}</p></details></article></section>
 <section class="supply-card"><h2>分期金额与触发条件</h2><article v-for="i in quote.installments" :key="i.key" class="trade-row"><h3>{{i.key}} · {{triggers[i.trigger]}}</h3><div class="table-wrap"><table><thead><tr><th>服务明细</th><th>本期金额</th></tr></thead><tbody><tr v-for="a in i.allocations" :key="a.line_id"><td>{{a.line_id}}</td><td>{{money(a.amount_minor)}}</td></tr></tbody></table></div><p v-if="i.apple_product_id" class="muted">Apple 商品编号：{{i.apple_product_id}}</p></article><p class="muted">付款状态不会自动证明制作完成。样片和成片付款须由服务器核验原制作明细的当前版本验收。</p></section>
 <section class="supply-card"><h2>期限、渠道与依据</h2><dl class="supply-facts"><div><dt>报价截止</dt><dd>{{quote.expires_at}}</dd></div><div><dt>支付窗口</dt><dd>{{quote.payment_window_minutes}} 分钟</dd></div><div><dt>支付渠道</dt><dd>{{quote.channel==='ALIPAY'?'支付宝':'Apple'}}</dd></div><div><dt>交易责任方式</dt><dd>{{quote.transaction_model==='DIRECT_SUPPLIER'?'商家本人供给':'平台作为交易主体'}}</dd></div><div><dt>采用规则</dt><dd class="identifier">{{quote.rule_id}}</dd></div><div><dt>许可预留</dt><dd class="identifier">{{quote.license_reservation_id||'未关联'}}</dd></div></dl></section></template>
 <section v-if="record.kind==='ORDER'" class="supply-card"><h2>订单条款与保存合同</h2><p class="supply-warning">合同内容已保存，尚未签署。付款不替代签署、身份、权属及独立许可核验。</p><p class="identifier">合同内容指纹：{{record.data.contract.content_sha256}}</p><details class="trade-rules"><summary>查看本订单保存的完整合同内容</summary><ContractText :value="record.data.contract.commitments" :field-labels="tradeContractLabels" label="本订单保存的合同内容" /></details><details class="trade-rules"><summary>查看本订单采用的原规则</summary><article v-for="r in record.data.contract.rule_contents" :key="r.id"><h3>{{r.rule_key}} · {{r.version}}</h3><p class="identifier">{{r.content_sha256}}</p><ContractText :value="r.terms" /></article></details><h3>已核实财务事实</h3><dl class="supply-facts"><div><dt>已收款</dt><dd>{{money(record.data.financial.received_minor)}}</dd></div><div><dt>已退款 / 净收款</dt><dd>{{money(record.data.financial.refunded_minor)}} / {{money(record.data.financial.net_minor)}}</dd></div></dl><p v-if="record.data.cancel_reason" class="long-text">取消理由：{{record.data.cancel_reason}}</p></section>
 <section v-if="record.kind==='PAYMENT' || record.kind==='REFUND'" class="supply-card"><h2>{{record.kind==='PAYMENT'?'付款依据与逐项金额':'原付款和退款明细'}}</h2><dl class="supply-facts"><div><dt>金额</dt><dd class="trade-amount">{{money(record.data.amount_minor)}} / CNY</dd></div><div><dt>支付渠道与环境</dt><dd>{{record.data.provider==='ALIPAY'?'支付宝':'Apple'}} · {{record.data.environment==='PRODUCTION'?'正式渠道记录':'测试渠道记录'}}</dd></div><div><dt>订单编号</dt><dd class="identifier">{{record.order_id}}</dd></div><div><dt>{{record.kind==='PAYMENT'?'付款分期':'原付款记录'}}</dt><dd class="identifier">{{record.kind==='PAYMENT'?record.data.installment_key:record.data.payment_id}}</dd></div><div><dt>渠道交易编号</dt><dd class="identifier">{{record.data.transaction_id||'渠道尚未确认'}}</dd></div><div><dt>核实返回状态</dt><dd>{{record.data.proof ? tradeStatus({kind:record.kind,current_status:record.data.proof.status}) : '尚无已核实依据'}}</dd></div></dl><div class="table-wrap"><table><thead><tr><th>明细编号</th><th>金额</th></tr></thead><tbody><tr v-for="a in record.data.allocations" :key="a.line_id"><td>{{a.line_id}}</td><td>{{money(a.amount_minor)}}</td></tr></tbody></table></div><p v-if="record.kind==='REFUND'" class="long-text">申请原因：{{record.data.reason}}</p><p v-if="record.kind==='PAYMENT'" class="supply-warning">浏览器支付客户端尚未开放。建立付款记录不表示已扣款，支付返回也须经服务器核实。</p><p v-else class="supply-warning">批准退款不表示已经退款。Apple 执行仅进入等待用户申请流程；以核实结果为准。</p></section>
 <section v-if="record.kind==='LEGACY'" class="supply-card"><h2>历史原明细与原条款</h2><p>{{record.data.source_system}} · {{record.data.source_order_id}}</p><div class="table-wrap"><table><thead><tr><th>原明细编号</th><th>原金额</th><th>原系统申报状态</th></tr></thead><tbody><tr v-for="l in record.data.original_lines" :key="l.line_id"><td>{{l.line_id}}</td><td>{{money(l.amount_minor)}}</td><td>{{l.reported_status==='REPORTED_PAID'?'原系统申报已付':l.reported_status==='REPORTED_UNPAID'?'原系统申报未付':'原系统未知'}}</td></tr></tbody></table></div><p class="long-text">{{record.data.original_terms}}</p><p class="identifier">私有附件：{{record.data.evidence_asset_id}}</p><p class="supply-warning">仅保留并核对历史材料；不追认为支付渠道确认到账。</p></section>
 <section v-if="'review' in record.data && record.data.review" class="supply-card"><h2>保存的审核结论</h2><p>{{record.data.review.decision==='APPROVED'?'已批准':'已拒绝'}}</p><p class="long-text">{{record.data.review.reason}}</p><p class="identifier">审核账号：{{record.data.review.account_id}}</p></section>
</template>
