<script setup lang="ts">
import { computed, reactive, watch } from 'vue'
import { amountInput, triggers, money, type TradeRecord, type Installment } from '@/api/modules/trade'
import { type GigRecord } from '@/api/modules/gigs'
import { validSupplyId } from '@/api/modules/supply'
const props=defineProps<{disabled:boolean;specs:TradeRecord[];offers?:GigRecord[];offerId?:string}>(),emit=defineEmits<{submit:[body:unknown]}>()
const blankLine=()=>({line:'',spec:'',qty:''}),blankAllocation=()=>({line:'',amount:''}),blankInstallment=()=>({key:'',trigger:'',apple:'',allocations:[blankAllocation()]})
const offer=reactive({id:''})
const selectedOffer=computed(()=>props.offers?.find(r=>r.id===offer.id&&r.kind==='OFFER'&&r.current_status==='ACCEPTED'))
const f=reactive({buyer:'',rule:'',expires:'',window:'',reservation:'',channel:'',model:'',lines:[blankLine()],installments:[blankInstallment()]})
watch(()=>props.offerId,v=>{if(v)offer.id=v},{immediate:true})
watch(selectedOffer,r=>{if(r?.kind==='OFFER'){f.buyer=r.counterparty_id||'';f.lines=[{line:'',spec:r.data.spec_id,qty:''}]}},{immediate:true})
const lineTotal=(l:ReturnType<typeof blankLine>)=>{const s=props.specs.find(s=>s.kind==='SPEC'&&s.id===l.spec),q=amountInput(l.qty,1,10000);return s?.kind==='SPEC'&&q!==null?s.data.unit_minor*q:null}
const payload=computed(()=>{if(!validSupplyId(f.buyer)||!validSupplyId(f.rule)||!f.expires||!Number.isFinite(Date.parse(f.expires))||Date.parse(f.expires)<=Date.now()||amountInput(f.window,1,10080)===null||f.reservation&&!validSupplyId(f.reservation)||!['ALIPAY','APPLE'].includes(f.channel)||!['DIRECT_SUPPLIER','PLATFORM_PRINCIPAL'].includes(f.model)||!f.lines.length||f.lines.length>30||!f.installments.length||f.installments.length>20)return null
 if(f.lines.some(l=>!l.line.trim()||l.line.length>128||!validSupplyId(l.spec)||lineTotal(l)===null||lineTotal(l)!>900000000000)||new Set(f.lines.map(l=>l.line)).size!==f.lines.length)return null
 const installments:Installment[]=[];for(const i of f.installments){if(!i.key.trim()||i.key.length>128||!Object.hasOwn(triggers,i.trigger)||!i.allocations.length||i.allocations.length>30||new Set(i.allocations.map(a=>a.line)).size!==i.allocations.length||i.allocations.some(a=>!f.lines.some(l=>l.line===a.line)||amountInput(a.amount)===null)||f.channel==='APPLE'&&!i.apple.trim())return null;installments.push({key:i.key.trim(),trigger:i.trigger as keyof typeof triggers,allocations:i.allocations.map(a=>({line_id:a.line,amount_minor:amountInput(a.amount)!})),apple_product_id:i.apple.trim()||null})}
 if(new Set(installments.map(i=>i.key)).size!==installments.length||f.lines.some(l=>installments.flatMap(i=>i.allocations).filter(a=>a.line_id===l.line).reduce((s,a)=>s+a.amount_minor,0)!==lineTotal(l)))return null
 if(props.offerId&&!selectedOffer.value||offer.id&&(!selectedOffer.value||selectedOffer.value.kind!=='OFFER'||f.buyer!==selectedOffer.value.counterparty_id||f.lines.length!==1||f.lines[0]?.spec!==selectedOffer.value.data.spec_id||amountInput(f.lines[0]?.qty||'',1,10000)!==1||f.model!=='DIRECT_SUPPLIER'))return null
 return {...(offer.id?{commercial_offer_id:offer.id}:{}),buyer_party_id:f.buyer,rule_id:f.rule,expires_at:new Date(f.expires).toISOString(),payment_window_minutes:amountInput(f.window,1,10080),license_reservation_id:f.reservation||null,channel:f.channel,transaction_model:f.model,lines:f.lines.map(l=>({line_id:l.line.trim(),spec_id:l.spec,quantity:amountInput(l.qty,1,10000)})),installments}
})
</script>
<template><form class="trade-form" @submit.prevent="payload && emit('submit',payload)"><fieldset :disabled="disabled">
 <section class="supply-card"><h2>关联已确认商单提案</h2><label>已确认的本人提案<select v-model="offer.id" data-testid="trade-commercial-offer" :disabled="!!offerId"><option value="">不关联商单提案</option><option v-for="r in offers" :key="r.id" :value="r.id">{{r.id}} · 客户 {{r.counterparty_id}}</option></select></label><template v-if="selectedOffer?.kind==='OFFER'"><p>原平台费率 {{selectedOffer.data.commission.platform_bps}} bps / 原 MCN 费率 {{selectedOffer.data.commission.mcn_bps}} bps。</p><p class="long-text">{{selectedOffer.data.terms}}</p><p class="muted">采用原提案、客户和规格，只可单行、数量明确填写1、商家本人供给。成交金额来自本人已发布规格，分期金额仍须明确填写。</p></template><p v-else-if="offerId" class="supply-warning">此提案当前不能用于本人创建商业报价，请返回核对状态与身份。</p></section><section class="supply-card"><h2>客户及规则依据</h2><div class="trade-fields two"><label>买方主体编号 *<input v-model="f.buyer" required placeholder="完整主体编号"></label><label>规则编号 *<input v-model="f.rule" required placeholder="已生效规则编号"></label></div><p class="muted">没有主体搜索入口，请使用双方明确提供的主体编号。商家以当前负责人身份提交报价。</p></section>
 <section class="supply-card"><div class="section-heading"><h2>逐项服务规格与数量</h2><button type="button" class="outline" :disabled="f.lines.length>=30" @click="f.lines.push(blankLine())">添加服务明细</button></div><div v-for="(l,n) in f.lines" :key="n" class="trade-row"><div class="trade-fields three"><label>明细编号 *<input v-model="l.line" maxlength="128" required placeholder="本报价内唯一"></label><label>已审服务规格 *<select v-model="l.spec" required><option value="">请选择本人已发布规格</option><option v-for="s in specs.filter(s=>s.kind==='SPEC' && s.current_status==='PUBLISHED')" :key="s.id" :value="s.id">{{s.kind==='SPEC'?`${s.data.title} · ${s.data.specification.version} · ${money(s.data.unit_minor)}`:s.id}}</option></select></label><label>数量 *<input v-model="l.qty" inputmode="numeric" required placeholder="待填写"></label></div><p class="muted">{{ lineTotal(l)===null?'填写规格和数量后显示本行金额':`本行金额 ${money(lineTotal(l)!)}` }}</p><button v-if="f.lines.length>1" type="button" class="danger" @click="f.lines.splice(n,1)">移除此行</button></div><p v-if="!specs.length" class="muted">尚无可选规格，请先提交服务规格并完成独立审核。</p></section>
 <section class="supply-card"><div class="section-heading"><h2>分期金额及触发条件</h2><button type="button" class="outline" :disabled="f.installments.length>=20" @click="f.installments.push(blankInstallment())">添加分期</button></div><div v-for="(i,n) in f.installments" :key="n" class="trade-row"><div class="trade-fields three"><label>分期名称 *<input v-model="i.key" maxlength="128" required placeholder="待填写"></label><label>付款触发条件 *<select v-model="i.trigger" required><option value="">待选择</option><option v-for="(name,key) in triggers" :key="key" :value="key">{{name}}</option></select></label><label>Apple 商品编号<input v-model="i.apple" maxlength="128" :required="f.channel==='APPLE'" placeholder="Apple 渠道必须明确填写"></label></div><div v-for="(a,k) in i.allocations" :key="k" class="trade-allocation"><label>关联明细编号 *<select v-model="a.line" required><option value="">待选择</option><option v-for="l in f.lines.filter(l=>l.line)" :key="l.line" :value="l.line">{{l.line}}</option></select></label><label>本期分摊金额（人民币分） *<input v-model="a.amount" required inputmode="numeric" placeholder="整数分"></label><button v-if="i.allocations.length>1" type="button" @click="i.allocations.splice(k,1)">移除分摊</button></div><div class="supply-actions"><button type="button" class="outline" :disabled="i.allocations.length>=30" @click="i.allocations.push(blankAllocation())">添加分摊</button><button v-if="f.installments.length>1" type="button" class="danger" @click="f.installments.splice(n,1)">移除此期</button></div></div><p class="muted">每项服务的各期分摊之和须等于该服务金额。样片及成片付款须在制作流程验收当前版本，由服务器核验原付款条件。</p></section>
 <section class="supply-card"><h2>支付渠道与有效期</h2><div class="trade-fields four"><label>交易责任方式 *<select v-model="f.model" required><option value="">待选择</option><option value="DIRECT_SUPPLIER">商家本人供给</option><option value="PLATFORM_PRINCIPAL">平台作为交易主体</option></select></label><label>支付渠道 *<select v-model="f.channel" required><option value="">待选择</option><option value="ALIPAY">支付宝</option><option value="APPLE">Apple</option></select></label><label>报价截止时间 *<input v-model="f.expires" type="datetime-local" required></label><label>支付窗口（分钟） *<input v-model="f.window" required inputmode="numeric" placeholder="待填写"></label></div></section>
 <section class="supply-card"><h2>其他关联信息</h2><label class="trade-inline">许可预留编号<input v-model="f.reservation" placeholder="有明确关联时填写，否则留空"></label><p class="muted">付款不能替代签署、身份与权属材料核验。关联商单只采用已确认原提案，不设置新的价格或分成。</p></section><div class="trade-footer"><RouterLink to="/trade/quotes" class="button-link outline">返回记录</RouterLink><button class="primary" :disabled="disabled || !payload">提交报价审核</button></div>
 </fieldset></form></template>
