<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, watch } from 'vue'
import { onBeforeRouteLeave, onBeforeRouteUpdate, useRoute, useRouter } from 'vue-router'
import { ElMessageBox } from 'element-plus'
import { useSessionStore } from '@/stores/session'
import { useLicensing } from '@/composables/useLicensing'
import { useSupply } from '@/composables/useSupply'
import { ApiError, asApiError } from '@/api/client'
import { canAdaptBinding, getLicense, grantUsable, licenseTitle, minorInteger, moneyText, projectFits, purposes, recordStatus, territoryText, languageText, type LicenseKind, type LicenseRecord, type ProductData, type ProjectData, type Verification } from '@/api/modules/licensing'
import { listSupply, shortSupplyId, validSupplyId, type MediaType, type SupplyAsset, type WorkRecord } from '@/api/modules/supply'
import WorkspaceNav from '@/components/WorkspaceNav.vue'
import ApiErrorAlert from '@/components/ApiErrorAlert.vue'
import SupplyUpload from '@/components/SupplyUpload.vue'
import LicenseRecordPanel from '@/components/LicenseRecordPanel.vue'
import LicenseProductForm from '@/components/LicenseProductForm.vue'
import '@/styles/supply.css'
import '@/styles/licensing.css'

const session = useSessionStore(), route = useRoute(), router = useRouter()
const reviewer = computed(() => route.name === 'license-review')
const section = computed(() => String(route.params.section || 'catalog'))
const kindMap: Record<string,LicenseKind> = { catalog:'PRODUCT',products:'PRODUCT',reservations:'RESERVATION',evidence:'EVIDENCE',grants:'GRANT',projects:'PROJECT',bindings:'BINDING',readings:'READING',activation:'RESERVATION' }
const titles: Record<string,string> = {catalog:'选剧本',products:'许可商品',reservations:'许可办理',evidence:'外部材料记录',grants:'我的许可',projects:'项目与许可绑定',bindings:'已分配项目额度',readings:'受控阅稿',activation:'许可发放'}
const kind = computed(() => kindMap[section.value] || 'PRODUCT'), catalog = computed(() => section.value === 'catalog')
const pageTitle = computed(() => formPage.value ? ({products:'新建剧本许可商品',projects:'登记项目用途',readings:'申请指定人员阅稿'}[section.value] || titles[section.value]) : detail.value ? ({GRANT:reviewer.value ? '许可暂停处理' : '许可凭证与使用范围',READING:reviewer.value ? '阅稿依据独立审核' : '受控剧本阅读',EVIDENCE:reviewer.value ? '许可证据核验' : '外部签署与付款依据',RESERVATION:reviewer.value ? '核对条件并发放许可' : '许可预留与合同',PROJECT:'项目用途与许可绑定',BINDING:'项目许可绑定',PRODUCT:reviewer.value ? '许可商品独立审核' : '剧本许可详情'}[detail.value.kind]) : titles[section.value])
const formPage = computed(() => route.name === 'license-new')
const targetId = computed(() => typeof route.params.recordId === 'string' ? route.params.recordId : '')
const canOwn = computed(() => !!session.selected && session.selected.membership.current_status === 'ACTIVE' && session.selected.membership.roles.includes('OWNER') && !['SUSPENDED','CLOSED'].includes(session.selected.party.current_status))
const context = () => ({token:session.token,accountId:session.account?.id || '',partyId:reviewer.value ? null : session.selectedId,revision:session.revision,scope:route.fullPath})
const ui = useLicensing(context), uploadUi = useSupply(context)
const {rows,detail,related,nextCursor,error,notice,content,pending,busy,securityRevision,conflictRevision,retryAt} = ui
const {pending:uploadPending,error:uploadError,busy:uploadBusy} = uploadUi
const initializing = ref(true), pageLoading = ref(false), now = ref(Date.now()), works = ref<WorkRecord[]>([]), products = ref<LicenseRecord[]>([]), projects = ref<LicenseRecord[]>([]), parentReservation = ref<LicenseRecord | null>(null)
const decision = ref(''), reason = ref(''), signedHash = ref(''), currency = ref(''), received = ref(''), payee = ref(''), receipt = ref(''), identityChecked = ref(false), sellerChecked = ref(false), buyerChecked = ref(false)
const closeReason = ref(''), showClose = ref(false), reserveConfirmed = ref(false), activationEvidence = ref(''), activationReason = ref(''), bindingProject = ref('')
const evidenceAssets = ref<Record<string,string[]>>({seller:[],buyer:[],identity:[],payment:[]}), externalRef = ref('')
const projectTitle = ref(''), projectPurpose = ref(''), projectTerritory = ref(''), projectLanguage = ref(''), projectEpisodes = ref('')
const readingWork = ref(''), readingAccount = ref(''), readingParty = ref(''), readingUntil = ref(''), readingBasis = ref(''), readingAsset = ref<string[]>([])
const conflicted = ref(false), confirmedNewDecision = ref(false)
const locked = computed(() => busy.value || uploadBusy.value || !!pending.value || !!uploadPending.value || now.value < Math.max(retryAt.value,uploadUi.retryAt.value) || conflicted.value && !confirmedNewDecision.value)
const ownRecord = computed(() => detail.value?.owner_party_id === session.selectedId)
const relevantEvidence = computed(() => related.value.filter(r => r.kind === 'EVIDENCE' && r.parent_id === (detail.value?.kind === 'RESERVATION' ? detail.value.id : parentReservation.value?.id)))
const bindings = computed(() => related.value.filter(r => r.kind === 'BINDING' && r.parent_id === detail.value?.id))
const chosenProject = computed(() => projects.value.find(r => r.id === bindingProject.value))
const canBind = computed(() => detail.value?.kind === 'GRANT' && ownRecord.value && grantUsable(detail.value,now.value) && chosenProject.value?.kind === 'PROJECT' && projectFits(detail.value.data.terms,chosenProject.value.data,now.value) && bindings.value.length < detail.value.data.terms.project_limit && !bindings.value.some(r => r.kind === 'BINDING' && r.data.project_id === bindingProject.value))
const canAdapt = computed(() => !reviewer.value && !!detail.value && related.value.some(grant=>related.value.some(project=>canAdaptBinding(detail.value!,grant,project,session.selectedId,now.value))))
const canRead = computed(() => detail.value?.kind === 'READING' && detail.value.current_status === 'APPROVED' && detail.value.data.reader_account_id === session.account?.id && detail.value.counterparty_id === session.selectedId && Date.parse(detail.value.data.valid_until) > now.value)
const reviewable = computed(() => reviewer.value && !!detail.value && ['PRODUCT','EVIDENCE','READING'].includes(detail.value.kind) && detail.value.current_status === 'IN_REVIEW')
const verificationValid = computed(() => parentReservation.value?.kind === 'RESERVATION' && signedHash.value === parentReservation.value.data.contract.content_sha256 && currency.value === parentReservation.value.data.price.currency && identityChecked.value && sellerChecked.value && buyerChecked.value && validSupplyId(payee.value) && payee.value === parentReservation.value.counterparty_id && minorInteger(received.value) !== null && minorInteger(received.value)! >= parentReservation.value.data.payment_due_minor && minorInteger(received.value)! <= parentReservation.value.data.price.amount_minor && (parentReservation.value.data.payment_due_minor === 0 || !!receipt.value.trim()))
const evidenceValid = computed(() => detail.value?.kind === 'RESERVATION' && ['seller','buyer','identity'].every(k => evidenceAssets.value[k]?.length === 1) && (detail.value.data.payment_due_minor === 0 || evidenceAssets.value.payment?.length === 1) && !!externalRef.value.trim())
const projectPayload = computed<ProjectData | null>(() => Object.hasOwn(purposes,projectPurpose.value) && /^[A-Z]{2}$/.test(projectTerritory.value) && /^[a-z]{2}$/.test(projectLanguage.value) && !!projectTitle.value.trim() && minorInteger(projectEpisodes.value) !== null && minorInteger(projectEpisodes.value)! >= 1 && minorInteger(projectEpisodes.value)! <= 100000 ? {title:projectTitle.value.trim(),purpose:projectPurpose.value as keyof typeof purposes,territory:projectTerritory.value,language:projectLanguage.value,episodes:minorInteger(projectEpisodes.value)!} : null)
const readingValid = computed(() => validSupplyId(readingWork.value) && validSupplyId(readingAccount.value) && validSupplyId(readingParty.value) && !!readingUntil.value && Number.isFinite(Date.parse(readingUntil.value)) && Date.parse(readingUntil.value) > now.value && !!readingBasis.value && readingAsset.value.length === 1)
let disposed = false, pageTicket = 0, timer = 0, validationTimer = 0
function resetForm() { works.value=[];products.value=[];projects.value=[];parentReservation.value=null;decision.value='';reason.value='';signedHash.value='';currency.value='';received.value='';payee.value='';receipt.value='';identityChecked.value=sellerChecked.value=buyerChecked.value=false;closeReason.value='';showClose.value=false;reserveConfirmed.value=false;activationEvidence.value=activationReason.value=bindingProject.value='';evidenceAssets.value={seller:[],buyer:[],identity:[],payment:[]};externalRef.value='';projectTitle.value=projectPurpose.value=projectTerritory.value=projectLanguage.value=projectEpisodes.value='';readingWork.value=readingAccount.value=readingParty.value=readingUntil.value=readingBasis.value='';readingAsset.value=[];conflicted.value=false;confirmedNewDecision.value=false }
watch(securityRevision,resetForm,{flush:'sync'})
watch(uploadError,e=>{if(e && [401,403,404].includes(e.status))ui.clear()},{flush:'sync'})
watch(error,e=>{if(e && [401,403,404].includes(e.status))uploadUi.clear()},{flush:'sync'})
watch(conflictRevision,()=>{decision.value='';reason.value='';identityChecked.value=sellerChecked.value=buyerChecked.value=false;reserveConfirmed.value=false;bindingProject.value='';activationEvidence.value=activationReason.value='';showClose.value=false;conflicted.value=true;confirmedNewDecision.value=false},{flush:'sync'})
watch(()=>[route.fullPath,session.selectedId,session.revision],()=>{if(!initializing.value)void loadPage()})
function pathFor(r: LicenseRecord) {const s = {PRODUCT:catalog.value?'catalog':'products',RESERVATION:reviewer.value?'activation':'reservations',EVIDENCE:'evidence',GRANT:'grants',PROJECT:'projects',BINDING:'bindings',READING:'readings'}[r.kind];return reviewer.value ? `/licensing/reviews/${s}/${r.id}` : `/licensing/${s}/${r.id}`}
async function gotoRecord(r: LicenseRecord) {await router.push(pathFor(r))}
async function loadWorks() { const all = await ui.read('works',async(i,s)=>{const out: WorkRecord[]=[];let cursor:string|null=null;const seen=new Set<string>();do{const page=await listSupply(i,'WORK_VERSION',cursor,s);out.push(...page.items.filter((r):r is WorkRecord=>r.kind==='WORK_VERSION'&&r.current_status==='REVIEWS_COMPLETE'&&r.data.version.content.kind==='ORIGINAL'&&r.data.version.reviews.every(x=>x.decision==='APPROVED')));cursor=page.next_cursor;if(cursor&&seen.has(cursor))throw new ApiError({status:200,code:'UNEXPECTED_RESPONSE_SHAPE',message:'作品分页未更新，请重新读取。'});if(cursor)seen.add(cursor)}while(cursor);return out});if(all)works.value=all }
async function loadPage() {
  const ticket=++pageTicket,current=()=>!disposed&&ticket===pageTicket
  pageLoading.value=true;ui.clearContent()
  try {
    if(!reviewer.value&&!canOwn.value){ui.clear();error.value=new ApiError({status:403,code:'LICENSE_PARTY_FORBIDDEN',message:'请使用有效负责人身份。'});return}
    if(targetId.value&&!validSupplyId(targetId.value)){error.value=new ApiError({status:400,code:'CLIENT_RECORD_INVALID',message:'请从列表进入完整的记录编号。'});return}
    if(formPage.value){if(section.value==='products'){await loadWorks();if(!current())return;const all=await ui.loadAll('PRODUCT');if(current()&&all)products.value=all}if(section.value==='readings')await loadWorks();return}
    if(!targetId.value){await ui.loadList(kind.value,catalog.value);return}
    const r=await ui.loadRecord(targetId.value,kind.value);if(!current()||!r)return
    if(r.kind==='RESERVATION'){const all=await ui.loadAll('EVIDENCE');if(current()&&all)related.value=all.filter(x=>x.parent_id===r.id)}
    if(r.kind==='EVIDENCE'&&r.parent_id){const parent=await ui.read('parent',(i,s)=>getLicense(i,r.parent_id!,'RESERVATION',s));if(current())parentReservation.value=parent}
    if(r.kind==='GRANT'){const all=await ui.loadAll('BINDING');if(!current()||!all)return;related.value=all.filter(x=>x.parent_id===r.id);if(!reviewer.value){const allProjects=await ui.loadAll('PROJECT');if(current()&&allProjects)projects.value=allProjects}}
    if(r.kind==='PRODUCT'&&!catalog.value){const all=await ui.loadAll('PRODUCT');if(current()&&all)related.value=all.filter(x=>x.work_id===r.work_id)}
    if(r.kind==='BINDING'&&r.parent_id){const grant=await ui.read('binding-grant',(i,s)=>getLicense(i,r.parent_id!,'GRANT',s)),project=await ui.read('binding-project',(i,s)=>getLicense(i,r.kind==='BINDING'?r.data.project_id:'','PROJECT',s));if(current())related.value=[grant,project].filter((x):x is LicenseRecord=>!!x)}
    if(r.kind==='PROJECT'){const all=await ui.loadAll('BINDING');if(current()&&all)related.value=all.filter(x=>x.kind==='BINDING'&&x.data.project_id===r.id)}
  } finally {if(current())pageLoading.value=false}
}
function leavePending(){if(ui.canNavigate()&&!uploadPending.value)return true;notice.value='原操作的结果还未核对，暂不能切换页面。请先重试原操作；明确冲突请先结束并刷新。';return false}
onBeforeRouteLeave(leavePending);onBeforeRouteUpdate(leavePending)
function hideReader(){ui.clearContent()}
onMounted(async()=>{timer=window.setInterval(()=>{now.value=Date.now();if(ui.readerDeadline.value&&ui.readerDeadline.value<=now.value)ui.clearContent()},1000);validationTimer=window.setInterval(()=>{if(content.value)void ui.verifyReader()},15000);window.addEventListener('blur',hideReader);document.addEventListener('visibilitychange',hideReader);const captured=session.capture();try{await Promise.all([session.loadAccount(),session.loadParties()]);if(!disposed&&session.current(captured)){initializing.value=false;await loadPage()}}catch(cause){if(!disposed&&session.current(captured)){ui.clear();error.value=asApiError(cause)}}finally{if(!disposed)initializing.value=false}})
onUnmounted(()=>{disposed=true;window.clearInterval(timer);window.clearInterval(validationTimer);window.removeEventListener('blur',hideReader);document.removeEventListener('visibilitychange',hideReader)})
async function saveProduct(body: Omit<ProductData,'review'> & {previous_product_id:string|null}){await ui.write({path:'/licensing/products',body,resultKind:'PRODUCT',label:'提交商品'},gotoRecord)}
async function reserve(){if(locked.value||!reserveConfirmed.value||detail.value?.kind!=='PRODUCT')return;await ui.write({path:'/licensing/reservations',body:{product_id:detail.value.id},resultKind:'RESERVATION',label:'预留权利'},gotoRecord)}
async function upload(file:File,mediaType:MediaType,destination:string){await uploadUi.write({path:`/supply/assets?${new URLSearchParams({purpose:'RIGHTS_EVIDENCE',media_type:mediaType})}`,blob:file,purpose:'RIGHTS_EVIDENCE',mediaType,kind:'ASSET',label:'上传依据'},r=>{const asset=r as SupplyAsset;if(destination==='basis')readingAsset.value=[asset.id];else evidenceAssets.value={...evidenceAssets.value,[destination]:[asset.id]}})}
async function submitEvidence(){const r=detail.value;if(locked.value||!evidenceValid.value||r?.kind!=='RESERVATION')return;await ui.write({path:'/licensing/evidence',body:{reservation_id:r.id,contract_sha256:r.data.contract.content_sha256,seller_signature_asset_id:evidenceAssets.value.seller![0],buyer_signature_asset_id:evidenceAssets.value.buyer![0],identity_asset_id:evidenceAssets.value.identity![0],payment_asset_id:evidenceAssets.value.payment?.[0]||null,external_reference:externalRef.value.trim()},resultKind:'EVIDENCE',label:'提交外部材料'},gotoRecord)}
async function review(){const r=detail.value;if(locked.value||!reviewable.value||!decision.value||!reason.value.trim()||!r)return;let verification:Verification|null=null;if(r.kind==='EVIDENCE'&&decision.value==='APPROVED'){if(!verificationValid.value)return;verification={signed_contract_sha256:signedHash.value,identity_verified:true,seller_signature_verified:true,buyer_signature_verified:true,currency:currency.value,received_minor:minorInteger(received.value)!,payee_party_id:payee.value,receipt_ref:receipt.value.trim()||null}}await ui.write({path:`/licensing/records/${r.id}/reviews`,body:{decision:decision.value,reason:reason.value.trim(),verification},version:r.object_version,targetId:r.id,resultKind:r.kind,label:'独立核验'},()=>{decision.value=reason.value='';identityChecked.value=sellerChecked.value=buyerChecked.value=false})}
async function activate(){const r=detail.value;if(locked.value||!reviewer.value||r?.kind!=='RESERVATION'||r.current_status!=='HELD'||!validSupplyId(activationEvidence.value)||!activationReason.value.trim())return;await ui.write({path:`/licensing/reservations/${r.id}/activation`,body:{evidence_id:activationEvidence.value,reason:activationReason.value.trim()},version:r.object_version,targetId:r.id,resultKind:'ACTIVATION',label:'发放许可核对'},gotoRecord)}
async function close(){const r=detail.value;if(locked.value||!r||!closeReason.value.trim())return;const suspend=reviewer.value&&r.kind==='GRANT', captured=session.capture();try{await ElMessageBox.confirm(suspend?'暂停后不可继续使用。确认按当前记录提交暂停？':'将关闭当前记录，理由及历史会保留。确认提交？',suspend?'暂停许可':'关闭当前记录',{confirmButtonText:'确认提交',cancelButtonText:'返回核对',type:'warning'})}catch{return}if(!session.current(captured,true)||detail.value?.id!==r.id||detail.value.object_version!==r.object_version)return;await ui.write({path:suspend?`/licensing/grants/${r.id}/suspensions`:`/licensing/records/${r.id}/closures`,body:{reason:closeReason.value.trim()},version:r.object_version,targetId:r.id,resultKind:r.kind,label:suspend?'暂停许可':'关闭记录'},()=>{showClose.value=false;closeReason.value=''})}
async function createProject(){if(locked.value||!projectPayload.value)return;await ui.write({path:'/licensing/projects',body:{project:projectPayload.value},resultKind:'PROJECT',label:'建立项目'},gotoRecord)}
async function bind(){const r=detail.value;if(locked.value||!canBind.value||r?.kind!=='GRANT')return;const captured=session.capture(),projectId=bindingProject.value;try{await ElMessageBox.confirm('将为此项目分配一个许可额度。本阶段不支持释放额度后重复使用。确认绑定？','分配项目额度',{confirmButtonText:'确认绑定',cancelButtonText:'返回核对'})}catch{return}if(!session.current(captured,true)||detail.value?.id!==r.id||detail.value.object_version!==r.object_version||!canBind.value||bindingProject.value!==projectId)return;await ui.write({path:`/licensing/grants/${r.id}/bindings`,body:{project_id:projectId},version:r.object_version,targetId:r.id,resultKind:'BINDING',label:'绑定项目'},gotoRecord)}
async function createReading(){if(locked.value||!readingValid.value)return;await ui.write({path:'/licensing/readings',body:{work_version_id:readingWork.value,reader_account_id:readingAccount.value,reader_party_id:readingParty.value,valid_until:new Date(readingUntil.value).toISOString(),basis_type:readingBasis.value,basis_asset_id:readingAsset.value[0]},resultKind:'READING',label:'提交阅稿申请'},gotoRecord)}
</script>

<template>
  <div class="supply-workspace licensing-workspace">
    <header class="supply-header"><RouterLink to="/workspace" class="supply-brand">晶晶日上</RouterLink><span>运营与合作方工作台</span><div class="account-actions"><span class="account-name">{{ session.account?.display_name || '当前账号' }}</span><button type="button" @click="session.logout().then(() => router.push('/login'))">退出</button></div></header>
    <div class="supply-layout"><aside class="supply-sidebar"><WorkspaceNav /><div class="supply-identity"><template v-if="reviewer"><p>独立许可核验</p><p class="muted">以当前账号审核；不代表任何业务身份。权限由服务器检查。</p></template><template v-else><label for="license-party">当前办理身份</label><select id="license-party" :value="session.selectedId" :disabled="busy || uploadBusy" @change="session.selectParty(($event.target as HTMLSelectElement).value)"><option v-for="p in session.parties" :key="p.party.id" :value="p.party.id">{{ p.party.display_name }}</option></select><button v-if="session.nextCursor" type="button" @click="session.loadMoreParties()">加载其他身份</button><p class="muted">{{ canOwn ? '以有效负责人身份办理' : '需有效负责人身份' }}</p></template></div></aside>
    <main class="supply-main">
      <div class="supply-heading"><div><h1>{{ pageTitle }}</h1><p>{{ catalog ? '先核对权利、用途和期限，再办理许可。' : reviewer ? '逐项核对真实材料与约定；审批不能绕过明确冲突。' : '按当前身份查看约定、办理进度及使用范围。' }}</p></div><div class="heading-actions"><button class="outline" :disabled="locked || pageLoading" @click="loadPage">刷新当前记录</button><RouterLink v-if="!reviewer && ['products','projects','readings'].includes(section) && !formPage" class="button-link primary" :to="`/licensing/${section}/new`">{{ section === 'products' ? '新建许可商品' : section === 'projects' ? '建立项目' : '申请指定人阅稿' }}</RouterLink></div></div>
      <div v-if="reviewer" class="loaded-tabs"><RouterLink v-for="s in ['products','evidence','readings','activation','grants']" :key="s" :to="`/licensing/reviews/${s}`" :class="{active:section === s}">{{ titles[s] }}</RouterLink></div>
      <div v-else-if="['reservations','evidence','grants'].includes(section)" class="loaded-tabs"><RouterLink v-for="s in ['reservations','evidence','grants']" :key="s" :to="`/licensing/${s}`" :class="{active:section === s}">{{ titles[s] }}</RouterLink></div>
      <ApiErrorAlert :error="error" /><ApiErrorAlert :error="uploadError" />
      <p v-if="notice" class="supply-notice" role="status">{{ notice }}</p>
      <div v-if="pending || uploadPending" class="supply-warning"><p>{{ (pending || uploadPending)?.command.label }}尚未完成核对。{{ (pending || uploadPending)?.state === 'blocked' ? '请先结束本次操作，再刷新并重新决定。' : '请保留原内容重试，不另建相同业务。' }}</p><button v-if="pending" class="outline" :disabled="busy || now < retryAt" @click="pending.state === 'blocked' ? ui.acknowledgeConflict() : ui.retry()">{{ pending.state === 'blocked' ? '结束本次操作' : pending.state === 'refresh' ? '重新读取操作结果' : '重试原操作' }}</button><button v-if="uploadPending" class="outline" :disabled="uploadBusy" @click="uploadPending.state === 'blocked' ? uploadUi.acknowledgeConflict() : uploadUi.retry()">{{ uploadPending.state === 'blocked' ? '结束本次上传' : '重试原上传' }}</button></div>
      <div v-if="conflicted" class="supply-warning"><label class="license-check"><input v-model="confirmedNewDecision" type="checkbox">我已核对刷新后的记录，将重新作出本次决定。</label></div>
      <p v-if="initializing || pageLoading" class="supply-empty" role="status">正在读取当前身份与记录…</p>
      <div v-else :key="route.fullPath + securityRevision">
      <template v-if="!targetId && !formPage">
        <section class="supply-card"><div class="section-heading"><h2>{{ catalog ? '已审核上架的许可商品' : reviewer ? '可获准核验的记录' : '当前身份的记录' }}</h2><span class="muted">{{ rows.length }} 条已加载记录</span></div>
          <div v-if="catalog && rows.length" class="catalog-grid"><article v-for="r in rows" :key="r.id" class="script-card"><template v-if="r.kind === 'PRODUCT'"><div class="section-heading"><span class="script-kicker">剧本许可</span><span class="supply-badge">{{ r.data.terms.exclusive ? '约定范围独家' : '非独家' }}</span></div><h3>{{ r.data.title }}</h3><p class="script-preview">{{ r.data.preview_text }}</p><p class="muted">{{ r.data.terms.rights.length }} 项权利 · {{ r.data.terms.project_limit }} 个项目额度</p><p class="script-price">{{ moneyText(r.data.price) }}</p><RouterLink :to="pathFor(r)" class="button-link outline">核对范围与短试读</RouterLink></template></article></div>
          <div v-else-if="rows.length" class="table-wrap"><table><thead><tr><th>记录</th><th>状态与期限</th><th>关联 / 版本</th><th>操作</th></tr></thead><tbody><tr v-for="r in rows" :key="r.id"><td><RouterLink :to="pathFor(r)" class="button-link table-link">{{ licenseTitle(r) }}</RouterLink><p class="muted" :title="r.id">{{ shortSupplyId(r.id) }}</p></td><td><span class="supply-badge">{{ recordStatus(r) }}</span><p v-if="r.kind === 'RESERVATION'" class="muted">预留截止 {{ new Date(r.data.expires_at).toLocaleString('zh-CN') }}<br>{{ now >= Date.parse(r.data.expires_at) && r.current_status === 'HELD' ? '预留已到期；实际使用需重新核验' : '' }}</p><p v-if="r.kind === 'GRANT'" class="muted">{{ grantUsable(r,now) ? '当前处于许可有效期间' : '当前不可继续使用' }}<br>开发截止 {{ new Date(r.data.terms.development_until).toLocaleString('zh-CN') }}</p><p v-if="r.kind === 'READING'" class="muted">阅读截止 {{ new Date(r.data.valid_until).toLocaleString('zh-CN') }}</p></td><td><span v-if="r.parent_id" :title="r.parent_id">{{ shortSupplyId(r.parent_id) }}</span><p class="muted">当前记录版本 {{ r.object_version }}</p></td><td><RouterLink class="button-link table-link" :to="pathFor(r)">查看与办理</RouterLink></td></tr></tbody></table></div>
          <p v-else class="supply-empty">{{ error ? '未取得可显示记录，请按错误说明处理。' : '当前没有可显示记录。' }}</p><button v-if="nextCursor" class="outline" :disabled="locked" @click="ui.loadList(kind,catalog,true)">继续加载</button><p v-if="reviewer" class="muted">列表不代表你可以审核每一条。本人及所属机构的材料仍禁止自行审批。</p></section>
      </template>
      <LicenseProductForm v-if="formPage && section === 'products' && canOwn" :key="route.fullPath + securityRevision" :works="works" :products="products" :disabled="locked" @submit="saveProduct" />
      <form v-if="formPage && section === 'projects' && canOwn" @submit.prevent="createProject"><section class="supply-card"><h2>建立项目用途记录</h2><fieldset :disabled="locked"><label class="supply-field"><span class="field-label">项目标题 *</span><input v-model="projectTitle" maxlength="200" required></label><div class="supply-fields"><label class="supply-field"><span class="field-label">实际用途 *</span><select v-model="projectPurpose" required><option value="">请选择</option><option v-for="(label,key) in purposes" :key="key" :value="key">{{ label }}</option></select></label><label class="supply-field"><span class="field-label">国家代码 *</span><input v-model="projectTerritory" maxlength="2" pattern="[A-Z]{2}" required></label><label class="supply-field"><span class="field-label">语言代码 *</span><input v-model="projectLanguage" maxlength="2" pattern="[a-z]{2}" required></label><label class="supply-field"><span class="field-label">项目集数 *</span><input v-model="projectEpisodes" inputmode="numeric" pattern="[0-9]+" required></label></div><p class="muted">用途不能原地改写。项目建立后，还需将有效许可绑定到此项目；建立项目本身不取得制作或改稿权。</p><button class="primary" :disabled="locked || !projectPayload">建立项目</button></fieldset></section></form>
      <form v-if="formPage && section === 'readings' && canOwn" @submit.prevent="createReading"><section class="supply-card"><h2>指定人、有期限的阅稿申请</h2><fieldset :disabled="locked"><label class="supply-field"><span class="field-label">已完成双审的原作 *</span><select v-model="readingWork" required><option value="">请选择明确版本</option><option v-for="w in works" :key="w.id" :value="w.id">{{ w.data.version.content.title }} · 第 {{ w.revision }} 版</option></select></label><div class="supply-fields"><label class="supply-field"><span class="field-label">指定阅读账号编号 *</span><input v-model.trim="readingAccount" required></label><label class="supply-field"><span class="field-label">该账号代表的身份编号 *</span><input v-model.trim="readingParty" required></label><label class="supply-field"><span class="field-label">阅读截止（本地时间） *</span><input v-model="readingUntil" type="datetime-local" required></label><label class="supply-field"><span class="field-label">依据类型 *</span><select v-model="readingBasis" required><option value="">请选择</option><option value="NDA">保密协议</option><option value="EVALUATION_PERMISSION">评估授权</option></select></label></div><SupplyUpload label="保密或评估授权依据" :ids="readingAsset" single :disabled="locked" @upload="(file,type) => upload(file,type,'basis')" @remove="readingAsset = []" /><p class="muted">指定账号须是该身份的有效负责人。独立核验批准后开放 UTF-8 纯文本受控阅读，不授予生成、训练或发行。</p><button class="primary" :disabled="locked || !readingValid">提交阅稿申请</button></fieldset></section></form>
      <template v-if="targetId && detail">
        <div class="license-detail-layout"><div><LicenseRecordPanel v-if="detail.kind !== 'READING' || reviewer" :record="detail" :reviewer="reviewer" :busy="locked" :binding-count="bindings.length" @material="ui.downloadEvidence" />
          <section v-if="catalog && detail.kind === 'PRODUCT'" class="supply-card"><h2>办理本商品的许可</h2><p class="supply-warning">预留后保存当时的价格、规则及合同。尚需外部签署、付款材料的独立核验与许可发放。独家冲突不能通过审批绕过。</p><label class="license-check"><input v-model="reserveConfirmed" type="checkbox" :disabled="locked">我已核对本商品全部权利、用途、地域、语言、期限和金额约定。</label><div class="supply-actions"><button class="primary" :disabled="locked || !reserveConfirmed || detail.owner_party_id === session.selectedId || now >= Date.parse(detail.data.terms.development_until)" @click="reserve">预留权利并保存本次合同</button></div><p v-if="detail.owner_party_id === session.selectedId" class="muted">不能购买当前身份自己供给的商品。</p></section>
          <section v-if="!reviewer && detail.kind === 'RESERVATION' && detail.current_status === 'HELD'" class="supply-card"><h2>提交真实外部签署与付款材料</h2><p class="muted">请引用与上方合同内容指纹一致的真实材料。上传仅归档依据，不能直接取得许可。</p><form @submit.prevent="submitEvidence"><fieldset :disabled="locked"><div class="uploads-grid"><SupplyUpload v-for="([key,label]) in [['seller','卖方签署材料'],['buyer','买方签署材料'],['identity','身份核验依据'],['payment', detail.data.payment_due_minor === 0 ? '付款材料（本约定可留空）' : '付款材料']]" :key="key || ''" :label="label || ''" :ids="evidenceAssets[key!] || []" single compact :disabled="locked" @upload="(file,type) => upload(file,type,key!)" @remove="evidenceAssets = {...evidenceAssets,[key!]:[]}" /></div><label class="supply-field" style="margin-top:24px"><span class="field-label">外部材料参考编号 *</span><input v-model="externalRef" maxlength="128" required></label><button class="primary" :disabled="locked || !evidenceValid">提交材料等待独立核验</button></fieldset></form></section>
          <section v-if="detail.kind === 'GRANT'" class="supply-card"><h2>项目额度与使用条件</h2><p class="supply-warning">{{ grantUsable(detail,now) ? '当前处于许可有效期间；项目绑定及改稿仍受开发截止、用途和额度限制。' : '本许可当前不可继续使用，请核对暂停状态或期限。' }}</p><p>本次已读取 {{ bindings.length }} 条项目绑定；本许可最多用于 {{ detail.data.terms.project_limit }} 个项目。</p><p class="muted">本阶段不支持释放额度后重复使用。是否实际可用由服务器每次重新核验。</p><form v-if="!reviewer && ownRecord" @submit.prevent="bind"><fieldset :disabled="locked"><label class="supply-field"><span class="field-label">将额度分配给哪个项目</span><select v-model="bindingProject" required><option value="">请选择当前身份的项目</option><option v-for="p in projects" :key="p.id" :value="p.id">{{ licenseTitle(p) }} · {{ shortSupplyId(p.id) }}</option></select></label><p v-if="chosenProject?.kind === 'PROJECT'" class="muted">{{ purposes[chosenProject.data.purpose] }} · {{ territoryText(chosenProject.data.territory) }} · {{ languageText(chosenProject.data.language) }} · {{ chosenProject.data.episodes }} 集</p><p v-if="bindingProject && !canBind" class="form-error">此项目的用途、范围、开发时间或剩余额度不符合当前许可，或已经绑定。</p><div class="supply-actions"><button class="primary" :disabled="locked || !canBind">确认分配一个项目额度</button><RouterLink to="/licensing/projects/new" class="button-link outline">先建立项目</RouterLink></div></fieldset></form></section>
          <section v-if="detail.kind === 'BINDING' && !reviewer" class="supply-card"><h2>按此项目许可提交改稿</h2><p class="muted">仅当前身份有效的改稿权及开发期允许进入。还需供给申请获批，并上传本次新稿与主动填写的作者、权利人证明。</p><RouterLink v-if="canAdapt" :to="`/supply/adaptations/${detail.id}/new`" class="button-link primary">按此绑定提交项目改稿</RouterLink><p v-else class="supply-warning">此绑定的许可当前不能用于项目改稿，请核对许可暂停、开发期限及改稿权。</p></section><section v-if="detail.kind === 'READING' && !reviewer" class="supply-card"><h2>阅读授权摘要</h2><dl class="supply-facts"><div><dt>阅读状态</dt><dd><span class="supply-badge">{{ recordStatus(detail) }}</span></dd></div><div><dt>截止时间（本地时间）</dt><dd class="license-deadline">{{ new Date(detail.data.valid_until).toLocaleString('zh-CN') }}</dd></div></dl><p class="muted">每次读取核验指定账号和身份；全文只在此页内存中显示。离开页面、切换身份、窗口失去焦点及期限到达时清除正文。</p><div class="supply-actions"><button class="primary" :disabled="locked || !canRead" @click="ui.readContent(detail.id)">重新核验并读取带水印正文</button><button v-if="content" class="outline" @click="ui.clearContent">收起并清除正文</button></div><p v-if="!canRead" class="supply-warning">当前身份不是获准指定读者，或授权未批准、已过期或已撤销。</p><pre v-if="content && canRead" class="controlled-reader" tabindex="0" aria-label="带水印受控阅稿正文">{{ content }}</pre><div class="reader-boundary"><h3>阅读边界提示</h3><p class="muted">仅供评估阅读，不授予生成、训练或发行。当前支持 UTF-8 纯文本及分段水印。</p></div></section><details v-if="detail.kind === 'READING' && !reviewer" class="supply-card reading-basis"><summary>查看指定人员、授权依据与核验记录</summary><LicenseRecordPanel :record="detail" :busy="locked" @material="ui.downloadEvidence" /></details>
        </div>
        <section v-if="reviewer && reviewable" class="supply-card review-form"><h2>独立核验结论</h2><p v-if="detail.kind === 'PRODUCT'" class="muted">商品审核意见可能随目录向买方显示，请只填写商品范围与上架依据，不填写私有证件或付款细节。</p><form @submit.prevent="review"><fieldset :disabled="locked"><template v-if="detail.kind === 'EVIDENCE'"><h3>合同与金额核对</h3><p class="supply-warning">先读取关联材料和预留合同，逐项核实实际事实。所有核验项初始为尚未核对。</p><RouterLink v-if="parentReservation" :to="pathFor(parentReservation)" class="button-link outline">查看预留的合同、金额与收款方</RouterLink><p v-if="parentReservation?.kind === 'RESERVATION'" class="identifier">应匹配合同指纹：{{ parentReservation.data.contract.content_sha256 }}<br>约定币种：{{ parentReservation.data.price.currency }}；最低生效实收：{{ moneyText({currency:parentReservation.data.price.currency,amount_minor:parentReservation.data.payment_due_minor}) }}；总价：{{ moneyText(parentReservation.data.price) }}<br>约定收款方：{{ parentReservation.counterparty_id }}</p><label class="supply-field"><span class="field-label">已签合同内容指纹 *</span><input v-model.trim="signedHash" maxlength="64"></label><h3 class="verification-heading">身份与双方签署核对</h3><div class="license-checks verification-checks"><label><input v-model="identityChecked" type="checkbox">已核实双方身份</label><label><input v-model="sellerChecked" type="checkbox">已核实卖方签署</label><label><input v-model="buyerChecked" type="checkbox">已核实买方签署</label></div><h3 class="verification-heading">实际收款核对</h3><div class="supply-fields"><label class="supply-field"><span class="field-label">实收币种</span><input v-model.trim="currency" maxlength="3"></label><label class="supply-field"><span class="field-label">实际收款（{{ currency === 'CNY' ? '整数分' : '整数最小币种单位' }}）</span><input v-model="received" inputmode="numeric" pattern="[0-9]+"></label><label class="supply-field"><span class="field-label">实际收款主体编号</span><input v-model.trim="payee"></label><label class="supply-field"><span class="field-label">收款凭证参考编号</span><input v-model="receipt" maxlength="128"></label></div><p class="muted">零应付也须明确核验实收、签署及身份。实际收款不能超过总价；不能更换凭证编号重复使用同一笔付款。</p></template><label class="supply-field"><span class="field-label">审核结论 *</span><select v-model="decision" required><option value="">请选择结论</option><option value="APPROVED">批准</option><option value="REJECTED">拒绝</option></select></label><label class="supply-field"><span class="field-label">核验理由 *</span><textarea v-model="reason" maxlength="2000" required /></label><button class="primary" :disabled="locked || !decision || !reason.trim() || detail.kind === 'EVIDENCE' && decision === 'APPROVED' && !verificationValid">提交独立核验结论</button></fieldset></form></section></div>
        <section v-if="reviewer && detail.kind === 'RESERVATION' && detail.current_status === 'HELD'" class="supply-card"><h2>{{ now >= Date.parse(detail.data.expires_at) ? '晚到条件转人工补救' : '条件齐备后发放许可' }}</h2><p v-if="now >= Date.parse(detail.data.expires_at)" class="supply-warning">预留已经到期。本次操作只记录需要人工补救，不会直接发放许可或重新占用权利范围。</p><form @submit.prevent="activate"><fieldset :disabled="locked"><label class="supply-field"><span class="field-label">本预留已批准的证据 *</span><select v-model="activationEvidence" required><option value="">请选择已独立核验的材料</option><option v-for="e in relevantEvidence.filter(e=>e.current_status === 'APPROVED')" :key="e.id" :value="e.id">{{ shortSupplyId(e.id) }}</option></select></label><label class="supply-field"><span class="field-label">{{ now >= Date.parse(detail.data.expires_at) ? '人工补救记录理由' : '发放理由' }} *</span><textarea v-model="activationReason" maxlength="2000" required /></label><button class="primary" :disabled="locked || !activationEvidence || !activationReason.trim()">{{ now >= Date.parse(detail.data.expires_at) ? '提交人工补救记录' : '核对并发放许可' }}</button></fieldset></form></section>
        <section v-if="!reviewer && ownRecord && ['PRODUCT','RESERVATION','READING'].includes(detail.kind) && !['UNLISTED','CANCELLED','REVOKED','COMMITTED'].includes(detail.current_status) || reviewer && detail.kind === 'GRANT' && detail.current_status === 'ACTIVE'" class="supply-card"><h2>{{ reviewer ? '争议处理：暂停许可' : detail.kind === 'PRODUCT' ? '下架商品' : detail.kind === 'READING' ? '撤销阅稿' : '取消预留' }}</h2><button class="outline danger" :disabled="locked" @click="showClose = !showClose">{{ showClose ? '收起' : '填写理由' }}</button><form v-if="showClose" @submit.prevent="close"><label class="supply-field"><span class="field-label">理由 *</span><textarea v-model="closeReason" maxlength="2000" required :disabled="locked" /></label><button class="outline danger" :disabled="locked || !closeReason.trim()">确认提交</button></form><p class="muted">历史合同与审核意见保留，不会改写已经取得的约定。</p></section>
        <section v-if="related.length" class="supply-card"><h2>{{ detail.kind === 'PRODUCT' ? '此作品的商品版本与历史关联' : detail.kind === 'RESERVATION' ? '本预留已提交的证据' : detail.kind === 'BINDING' ? '本绑定对应的许可与项目' : '已获准读取的项目绑定' }}</h2><div v-for="r in related" :key="r.id" class="history-item"><RouterLink :to="pathFor(r)" class="button-link table-link">{{ licenseTitle(r) }} · {{ shortSupplyId(r.id) }}</RouterLink><span class="supply-badge">{{ recordStatus(r) }}</span><p v-if="r.parent_id" class="muted">关联上一记录 <span :title="r.parent_id">{{ shortSupplyId(r.parent_id) }}</span></p></div></section>
        <section v-if="detail.kind === 'PROJECT' && !reviewer" class="supply-card"><h2>下一步分配许可</h2><p class="muted">请进入自己的有效许可，为此项目分配一个额度。只有具备改稿权且开发期有效的绑定，才可用于项目改稿。</p><RouterLink to="/licensing/grants" class="button-link primary">选择我的许可</RouterLink></section>
        <section class="supply-card"><RouterLink :to="reviewer ? `/licensing/reviews/${section}` : `/licensing/${section}`" class="button-link outline">返回当前列表</RouterLink></section>
      </template>
      </div>
    </main></div>
  </div>
</template>
