<script setup lang="ts">
import {computed,onMounted,onUnmounted,reactive,ref,watch} from 'vue'
import {onBeforeRouteLeave,onBeforeRouteUpdate,useRoute,useRouter} from 'vue-router'
import {useSessionStore} from '@/stores/session'
import {useOperations} from '@/composables/useOperations'
import {ApiError,asApiError} from '@/api/client'
import {domains,reportKinds,eventText,reportStatus,getBusiness,commentable,businessLink,getAudit,getBusinessAudit,getCsv,isReportRequest,utcInput,type Domain,type Target,type BusinessRecord,type Audit,type BusinessAudit,type ReportRequest,type Notification,type WriteResult} from '@/api/modules/operations'
import {validSupplyId,shortSupplyId} from '@/api/modules/supply'
import {listTrade} from '@/api/modules/trade'
import {listProduction} from '@/api/modules/production'
import {listProjects} from '@/api/modules/projects'
import WorkspaceNav from '@/components/WorkspaceNav.vue'
import ApiErrorAlert from '@/components/ApiErrorAlert.vue'
import OperationsCommentsPanel from '@/components/OperationsCommentsPanel.vue'
import OperationsReportPanel from '@/components/OperationsReportPanel.vue'
import '@/styles/supply.css'
import '@/styles/trade.css'
import '@/styles/operations.css'
const session=useSessionStore(),route=useRoute(),router=useRouter()
const mode=computed(()=>String(route.meta.operationsView||'notifications')),operator=computed(()=>route.meta.operationsOperator===true),recordId=computed(()=>String(route.params.recordId||'')),eventId=computed(()=>Number(route.params.eventId||0))
const context=()=>({token:session.token,accountId:session.account?.id||'',partyId:operator.value?null:session.selectedId,revision:session.revision,scope:route.fullPath})
const ui=useOperations(context),{notifications,comments,report,notificationCursor,commentCursor,error,notice,pending,busy,securityRevision,conflictRevision,retryAt}=ui
const initializing=ref(true),source=ref<BusinessRecord|null>(null),sourceTarget=ref<Target|null>(null),choices=ref<BusinessRecord[]>([]),selected=ref(''),reply=ref(''),body=ref(''),reason=ref(''),openId=ref(''),unread=ref(false),auditRows=ref<Audit[]>([]),businessAudit=ref<BusinessAudit[]>([]),auditCursor=ref<number|null>(null),businessCursor=ref<string|null>(null),filterId=ref(''),csvUrl=ref(''),conflicted=ref(false),reconfirm=ref(false),now=ref(Date.now())
const locator=reactive({domain:'',record:''}),requestDraft=reactive({kind:'',environment:'',start:'',end:''})
const canMember=computed(()=>!!session.selected&&session.selected.membership.current_status==='ACTIVE'&&!['CLOSED','SUSPENDED'].includes(session.selected.party.current_status)),canOwner=computed(()=>canMember.value&&!!session.selected?.membership.roles.includes('OWNER'))
const locked=computed(()=>busy.value||!!pending.value||now.value<retryAt.value||conflicted.value&&!reconfirm.value),chosen=computed(()=>comments.value.find(c=>c.id===selected.value)||null),ownsChosen=computed(()=>!!chosen.value&&chosen.value.author_account_id===session.account?.id&&chosen.value.party_id===context().partyId),canHide=computed(()=>operator.value&&chosen.value?.current_status==='VISIBLE'&&chosen.value.author_account_id!==session.account?.id),canWithdraw=computed(()=>chosen.value?.current_status==='VISIBLE'&&ownsChosen.value)
const title=computed(()=>({notifications:'我的业务通知',comments:'订单或项目纯文本留言',moderation:'业务留言独立管理',audit:'获授权操作历史','report-new':'申请可追溯报表',reports:'报表任务与可追溯结果'} as Record<string,string>)[mode.value]),gallery=computed(()=>({notifications:'WEB-32-01',comments:'WEB-32-02-v2',moderation:'WEB-32-03',audit:'WEB-32-04','report-new':'WEB-33-01',reports:'WEB-33-02'} as Record<string,string>)[mode.value]),reportBase=computed(()=>operator.value?'/operations/operator/reports':'/operations/reports')
const targetValid=computed(()=>Object.hasOwn(domains,locator.domain)&&validSupplyId(locator.record)),sourceReady=computed(()=>!!source.value&&!!sourceTarget.value&&commentable(sourceTarget.value,source.value)),requestPayload=computed(()=>{const value={kind:requestDraft.kind,environment:requestDraft.environment,period_start:utcInput(requestDraft.start),period_end:utcInput(requestDraft.end)};return isReportRequest(value)?value:null}),mayRequest=computed(()=>operator.value?!!session.account:canOwner.value)
let disposed=false,timer=0
function reset(){source.value=null;sourceTarget.value=null;choices.value=[];selected.value=reply.value=body.value=reason.value=openId.value=filterId.value=csvUrl.value='';auditRows.value=[];businessAudit.value=[];auditCursor.value=businessCursor.value=null;locator.domain=locator.record='';requestDraft.kind=requestDraft.environment=requestDraft.start=requestDraft.end='';conflicted.value=reconfirm.value=false}
watch(securityRevision,reset,{flush:'sync'})
watch(conflictRevision,()=>{selected.value=reply.value=reason.value='';conflicted.value=true;reconfirm.value=false},{flush:'sync'})
watch(()=>[route.fullPath,session.selectedId,session.revision],()=>{if(!initializing.value)void loadPage()})
watch(()=>locator.domain,()=>{choices.value=[];source.value=null;sourceTarget.value=null;locator.record='';comments.value=[];selected.value=reply.value=reason.value='';businessAudit.value=[]})
watch(()=>locator.record,()=>{source.value=null;sourceTarget.value=null;comments.value=[];selected.value=reply.value=reason.value='';businessAudit.value=[]})
watch(selected,()=>reason.value='')
function errorInput(message:string){error.value=new ApiError({status:400,code:'CLIENT_INPUT_REQUIRED',message})}
function routeTarget():Target|null{const domain=String(route.params.domain||'');return Object.hasOwn(domains,domain)&&validSupplyId(recordId.value)?{domain:domain as Domain,record_id:recordId.value}:null}
async function sourceRead(t:Target){source.value=null;sourceTarget.value=null;return ui.read('source',(i,s)=>getBusiness(i,t,s),r=>{source.value=r;sourceTarget.value={...t}})}
async function loadChoices(){if(!['TRADE','PRODUCTION','PROJECTS'].includes(locator.domain)||locked.value)return;const domain=locator.domain;await ui.read('choices',async(i,s)=>{const all:BusinessRecord[]=[],seen=new Set<string>();let cursor:string|null=null;do{const page:{items:BusinessRecord[];next_cursor:string|null}=domain==='TRADE'?await listTrade(i,'ORDER',cursor,s):domain==='PRODUCTION'?await listProduction(i,undefined,undefined,cursor,s):await listProjects(i,undefined,undefined,cursor,s);all.push(...page.items);cursor=page.next_cursor;if(cursor&&seen.has(cursor))throw new ApiError({status:200,code:'UNEXPECTED_RESPONSE_SHAPE',message:'原业务分页位置未更新。'});if(cursor)seen.add(cursor)}while(cursor);return all},r=>{if(locator.domain===domain)choices.value=r})}
async function openTarget(){if(!targetValid.value||locked.value)return;const t={domain:locator.domain as Domain,record_id:locator.record},r=await sourceRead(t);if(!r)return;if(['comments','moderation'].includes(mode.value)){if(!commentable(t,r)){errorInput('留言仅支持订单、制作项目、制作版本或项目发行项目。');return}await router.push((mode.value==='moderation'?'/operations/moderation/':operator.value?'/operations/operator/objects/':'/operations/objects/')+t.domain+'/'+t.record_id+(mode.value==='moderation'?'':'/comments'))}else if(mode.value==='audit')await loadObjectAudit(false,t)}
async function loadGlobalAudit(more=false){if(filterId.value&&!validSupplyId(filterId.value)){errorInput('筛选对象须为完整实际编号。');return}if(more&&auditCursor.value===null)return;const cursor=more?auditCursor.value:null;await ui.read('audit',(i,s)=>getAudit(i,filterId.value,cursor,s),r=>{if(r.next_cursor!==null&&r.next_cursor===cursor)throw new ApiError({status:200,code:'UNEXPECTED_RESPONSE_SHAPE',message:'操作历史分页未更新。'});auditRows.value=more?[...new Map([...auditRows.value,...r.items].map(x=>[x.id,x])).values()]:r.items;auditCursor.value=r.next_cursor})}
async function loadObjectAudit(more=false,t:Target|null=sourceTarget.value){if(!t||more&&!businessCursor.value)return;const cursor=more?businessCursor.value:null;await ui.read('business-audit',(i,s)=>getBusinessAudit(i,t,cursor,s),r=>{if(r.next_cursor&&r.next_cursor===cursor)throw new ApiError({status:200,code:'UNEXPECTED_RESPONSE_SHAPE',message:'原业务历史分页未更新。'});businessAudit.value=more?[...new Map([...businessAudit.value,...r.items].map(x=>[x.id,x])).values()]:r.items;businessCursor.value=r.next_cursor})}
async function loadPage(){if(!session.account||(!operator.value&&!canMember.value))return;const t=routeTarget();if(mode.value==='notifications'){if(eventId.value>0)await ui.loadEvent(eventId.value);else await ui.loadNotifications(unread.value)}else if(['comments','moderation'].includes(mode.value)&&t){const r=await sourceRead(t);if(r&&commentable(t,r)){await ui.loadComments(t);if(route.params.commentId)selected.value=comments.value.find(c=>c.id===route.params.commentId)?.id||''}else if(r)errorInput('当前实际记录不支持留言。')}else if(mode.value==='audit'){await loadGlobalAudit();if(t&&await sourceRead(t))await loadObjectAudit(false,t)}else if(mode.value==='reports'&&validSupplyId(recordId.value)){csvUrl.value='';await ui.loadReport(recordId.value)}}
async function markRead(n:Notification){if(locked.value||n.read)return;await ui.write({path:`/operations/notifications/${n.id}/read`,body:{},resultKind:'READ',resultId:n.id,recovery:'NOTIFICATIONS',label:'此条通知已读'},()=>{if(!eventId.value)void ui.loadNotifications(unread.value)})}
async function openBusiness(n:Notification){if(locked.value)return;const t={domain:n.domain,record_id:n.record_id};const r=await sourceRead(t);if(r)await router.push(businessLink(t,r))}
async function addComment(){const t=sourceTarget.value;if(locked.value||!t||!sourceReady.value||!body.value.trim()||body.value.length>4000||reply.value&&!comments.value.some(c=>c.id===reply.value&&c.current_status==='VISIBLE'))return;await ui.write({path:`/operations/objects/${t.domain}/${t.record_id}/comments`,body:{body:body.value,reply_to:reply.value||null},resultKind:'COMMENT',target:t,recovery:'COMMENTS',label:'纯文本留言'},()=>{body.value=reply.value='';void ui.loadComments(t)})}
async function actComment(action:'WITHDRAW'|'HIDE'){const c=chosen.value,t=sourceTarget.value;if(locked.value||!c||!t||!reason.value.trim()||reason.value.length>1000||(action==='WITHDRAW'?!canWithdraw.value:!canHide.value))return;await ui.write({path:`/operations/comments/${c.id}/actions`,body:{action,reason:reason.value},version:c.object_version,resultId:c.id,resultKind:'COMMENT',target:t,recovery:'COMMENTS',label:action==='HIDE'?'独立隐藏留言':'撤回本人留言'},()=>{selected.value=reason.value='';void ui.loadComments(t)})}
async function requestReport(){const value=requestPayload.value;if(locked.value||!mayRequest.value||!value)return;await ui.write({path:'/operations/reports',body:value,resultKind:'REPORT',recovery:'CREATE_REPORT',request:{...value},label:'报表申请'},(r:WriteResult)=>router.push(reportBase.value+'/'+r.id))}
async function openReport(){if(validSupplyId(openId.value)&&!locked.value)await router.push(reportBase.value+'/'+openId.value)}
async function refreshReport(){if(locked.value||!validSupplyId(recordId.value))return;csvUrl.value='';await ui.loadReport(recordId.value)}
async function retryReport(){const r=report.value;if(!r||locked.value||!['FAILED','BLOCKED'].includes(r.current_status)||!reason.value.trim()||reason.value.length>1000)return;await ui.write({path:`/operations/reports/${r.id}/retries`,body:{reason:reason.value},resultId:r.id,resultKind:'REPORT',recovery:'REPORT',label:'原报表任务重试'},()=>reason.value='')}
async function downloadCsv(){const r=report.value;if(locked.value||!r?.result||r.current_status!=='SUCCEEDED')return;csvUrl.value='';ui.revoke();await ui.read('csv',(i,s)=>getCsv(i,r.id,s),blob=>{csvUrl.value=ui.objectUrl(blob);const anchor=document.createElement('a');anchor.href=csvUrl.value;anchor.download='report-'+r.id+'.csv';anchor.click()})}
function leavePending(){if(ui.canNavigate())return true;notice.value='原请求结果尚未核实，请先核对并恢复原操作后再离开。';return false}
function beforeUnload(e:BeforeUnloadEvent){if(pending.value){e.preventDefault();e.returnValue=''}}
onBeforeRouteLeave(leavePending);onBeforeRouteUpdate(leavePending)
onMounted(async()=>{timer=window.setInterval(()=>now.value=Date.now(),1000);window.addEventListener('beforeunload',beforeUnload);const c=session.capture();try{await Promise.all([session.loadAccount(),session.loadParties()]);if(!disposed&&session.current(c)){initializing.value=false;await loadPage()}}catch(e){if(!disposed&&session.current(c)){ui.clear();error.value=asApiError(e)}}finally{if(!disposed)initializing.value=false}})
onUnmounted(()=>{disposed=true;window.clearInterval(timer);window.removeEventListener('beforeunload',beforeUnload)})
</script>

<template><div class="supply-workspace trade-workspace operations-workspace" :data-gallery="gallery"><header class="supply-header"><RouterLink to="/workspace" class="supply-brand">晶晶日上</RouterLink><span>运营与合作方工作台</span><div class="account-actions"><span class="account-name">{{session.account?.display_name||'当前账号'}}</span><button @click="session.logout().then(()=>router.push('/login'))">退出</button></div></header>
<div class="supply-layout"><aside class="supply-sidebar"><WorkspaceNav/><div class="supply-identity"><template v-if="operator"><p>独立运营操作者</p><p class="muted">以当前账号办理，不携带主体身份。实际运营权限及原业务访问权由服务器核验。</p></template><template v-else><label for="ops-party">当前办理身份</label><select id="ops-party" data-testid="ops-party" :value="session.selectedId" :disabled="!!pending||busy" @change="session.selectParty(($event.target as HTMLSelectElement).value)"><option v-for="a in session.parties" :key="a.party.id" :value="a.party.id">{{a.party.display_name}}</option></select><p class="muted">{{canOwner?'当前有效负责人':'当前成员；办理范围以原业务权限为准'}}</p></template></div></aside>
<main class="supply-main"><div class="supply-heading"><div><p class="eyebrow">{{operator?'运营独立管理':'业务协作与可追溯记录'}}</p><h1>{{title}}</h1><p class="muted">{{mode==='notifications'?'只显示当前身份获准的业务事件；打开原业务时重新核验访问权。':mode==='audit'?'只读历史保留实际账号、版本和请求痕迹，不提供授权授予接口。':mode==='reports'||mode==='report-new'?'按实际环境、UTC 期间与原业务权限生成；申请保存尚不代表生成成功。':'只在当前获准的原业务对象内协作，留言不改变审核、付款或交付状态。'}}</p></div><button class="outline" data-testid="ops-refresh" :disabled="locked" @click="loadPage">刷新当前记录</button></div>
<div class="loaded-tabs"><RouterLink to="/operations/notifications">我的通知</RouterLink><RouterLink to="/operations/reports">本方报表</RouterLink><RouterLink to="/operations/moderation">留言独立管理</RouterLink><RouterLink to="/operations/audit">只读操作历史</RouterLink><RouterLink to="/operations/operator/reports">独立报表入口</RouterLink></div>
<ApiErrorAlert :error="error" testid="ops-error"/><p v-if="notice" class="supply-notice" role="status">{{notice}}</p><p v-if="initializing||busy" class="muted" role="status">正在读取实际记录…</p>
<section v-if="pending" class="supply-card ops-awaiting" data-testid="ops-pending"><h2>{{pending.resultId?'已取得原结果编号，等待核实':'原请求结果尚未确认'}}</h2><p>已保留原请求编号、内容和版本。先核对原记录；恢复会使用同一请求，当前不能另建操作或换页。</p><p v-if="pending.command.recovery==='CREATE_REPORT'&&!pending.resultId" class="muted">接口没有新报表任务目录，无法按请求编号查询。核对当前账号后，用原请求取回原任务。</p><details class="ops-technical"><summary>原请求与已知结果编号</summary><p>{{pending.key}}</p><p v-if="pending.resultId">{{pending.resultId}}</p></details><div class="ops-controls"><button class="outline" data-testid="ops-check-pending" :disabled="busy||now<retryAt" @click="ui.checkPending">先核对原记录</button><button class="primary" data-testid="ops-retry-pending" :disabled="busy||now<retryAt||!pending.resultId&&!pending.checked" @click="ui.retry">{{pending.resultId?'仅重新读取原结果':'恢复同一原请求'}}</button></div></section>
<section v-if="conflicted" class="supply-card"><h2>原留言版本已变化</h2><p>已读取当前原记录。请重新选择留言并填写理由，旧确认不会重放。</p><label class="ops-check"><input v-model="reconfirm" data-testid="ops-reconfirm" type="checkbox" :disabled="busy||!!pending">我已核对最新版本，重新开始本次决定。</label></section>
<p v-if="!initializing&&!operator&&!canMember" class="supply-empty">请先在账号与机构中选择有效办理主体。服务器会核验当前成员和原业务权限。</p>

<template v-if="mode==='notifications'"><section class="supply-card"><div class="ops-toolbar"><h2>{{eventId?'这条实际业务事件':'当前身份业务事件'}}</h2><label v-if="!eventId"><input v-model="unread" data-testid="ops-unread-only" type="checkbox" :disabled="locked" @change="ui.loadNotifications(unread)">只看未读</label></div><p class="muted">列表可能因原业务权限变化而为空。事件版本记录当时发生的事实，不代表现在的业务状态；本页不推导全站未读总数。</p><div class="table-wrap"><table><thead><tr><th>事件</th><th>原业务对象</th><th>发生时间（UTC）</th><th>已读状态</th><th>操作</th></tr></thead><tbody><tr v-for="n in notifications" :key="n.id" :class="{'ops-notification-unread':!n.read}"><td><RouterLink :to="`/operations/notifications/${n.id}`">{{eventText(n.event_code)}}</RouterLink><p class="muted">事件时版本 {{n.object_version}}</p></td><td>{{domains[n.domain]}} · {{shortSupplyId(n.record_id)}}</td><td><time>{{n.created_at}}</time></td><td>{{n.read?'已读':'未读'}}</td><td><div class="ops-controls"><button :data-testid="`ops-open-event-${n.id}`" class="outline" :disabled="locked" @click="openBusiness(n)">读取并打开原业务</button><button v-if="!n.read" :data-testid="`ops-read-event-${n.id}`" class="outline" :disabled="locked" @click="markRead(n)">标记此条已读</button></div></td></tr></tbody></table></div><p v-if="!notifications.length" class="supply-empty">当前范围没有获准可见的通知。</p><div class="ops-controls"><button v-if="notificationCursor!==null&&!eventId" class="outline" :disabled="locked" @click="ui.loadNotifications(unread,true)">继续读取更早事件</button><RouterLink v-if="eventId" to="/operations/notifications" class="button-link outline">返回业务通知</RouterLink></div></section></template>

<template v-if="mode==='comments'||mode==='moderation'||mode==='audit'"><section v-if="!routeTarget()||mode==='audit'" class="supply-card"><h2>{{mode==='audit'?'原业务历史定位':'定位真实留言对象'}}</h2><p class="muted">{{mode==='audit'?'原业务历史须另有该对象访问权。':'仅支持订单、制作项目或版本、项目发行项目；没有全站留言目录。'}}</p><form class="ops-locator" @submit.prevent="openTarget"><label>原业务域 *<select v-model="locator.domain" data-testid="ops-object-domain" :disabled="locked" required><option value="">明确选择</option><option v-for="(name,key) in domains" v-show="mode==='audit'||['TRADE','PRODUCTION','PROJECTS'].includes(key)" :key="key" :value="key">{{name}}</option></select></label><label>真实对象完整编号 *<input v-model.trim="locator.record" data-testid="ops-object-id" list="ops-known-objects" :disabled="locked" required maxlength="36" placeholder="已有对象编号；也可读取当前业务列表"><datalist id="ops-known-objects"><option v-for="r in choices" :key="r.id" :value="r.id">{{r.kind}} · {{shortSupplyId(r.id)}}</option></datalist></label><button class="primary" data-testid="ops-object-open" :disabled="locked||!targetValid">{{mode==='audit'?'读取原业务历史':'读取该对象留言'}}</button></form><button v-if="['TRADE','PRODUCTION','PROJECTS'].includes(locator.domain)" class="outline" data-testid="ops-object-choices" :disabled="locked" @click="loadChoices">读取当前获准业务列表</button></section>
<section v-if="source&&sourceTarget" class="supply-card"><div class="supply-section-heading"><h2>已读取的实际原业务</h2><RouterLink :to="businessLink(sourceTarget,source)" class="button-link outline">返回原业务对象</RouterLink></div><p>{{domains[sourceTarget.domain]}} · {{source.kind}} · 当前版本 {{source.object_version}} · {{source.current_status}}</p><details class="ops-technical"><summary>实际原对象完整编号</summary><p>{{source.id}}</p></details></section></template>

<template v-if="(mode==='comments'||mode==='moderation')&&sourceReady"><div class="ops-columns"><div><OperationsCommentsPanel :comments="comments" :selected="selected" :disabled="locked" @select="id=>selected=id"><div class="ops-controls"><button v-if="commentCursor" class="outline" :disabled="locked" @click="sourceTarget&&ui.loadComments(sourceTarget,true)">继续读取留言</button><button class="outline" :disabled="locked" @click="sourceTarget&&ui.loadComments(sourceTarget)">重新读取留言</button></div></OperationsCommentsPanel>
<form v-if="mode==='comments'" @submit.prevent="addComment"><fieldset :disabled="locked"><section class="supply-card"><h2>在此对象下新增纯文本留言</h2><label>回复已读取的可见留言<select v-model="reply" data-testid="ops-reply-to"><option value="">直接留言，不回复其他留言</option><option v-for="c in comments.filter(c=>c.current_status==='VISIBLE')" :key="c.id" :value="c.id">{{shortSupplyId(c.id)}} · {{c.body?.slice(0,60)}}</option></select></label><label>留言正文 *<textarea v-model="body" data-testid="ops-comment-body" required maxlength="4000" rows="5" placeholder="只填写本对象的协作说明"></textarea></label><p class="muted">最多 4000 字，只保存纯文本。留言不会替代合同确认、独立审核或客户验收。</p><button class="primary" data-testid="ops-comment-submit" :disabled="locked||!body.trim()||body.length>4000">提交纯文本留言</button></section></fieldset></form></div>
<section class="supply-card ops-action"><h2>{{mode==='moderation'?'独立隐藏决定':'撤回本人留言'}}</h2><template v-if="chosen"><p>已选择 {{shortSupplyId(chosen.id)}} · 当前版本 {{chosen.object_version}}</p><p v-if="chosen.current_status==='VISIBLE'" class="ops-text">{{chosen.body}}</p><p v-else class="muted">原文已不可见，不能继续修改其状态。</p><form @submit.prevent="actComment(mode==='moderation'?'HIDE':'WITHDRAW')"><fieldset :disabled="locked||!(mode==='moderation'?canHide:canWithdraw)"><label>本次理由 *<textarea v-model="reason" data-testid="ops-comment-reason" required maxlength="1000" rows="4"></textarea></label><button :class="mode==='moderation'?'danger':'outline'" data-testid="ops-comment-action" :disabled="locked||!reason.trim()||!(mode==='moderation'?canHide:canWithdraw)">{{mode==='moderation'?'独立隐藏此留言':'撤回此条本人留言'}}</button></fieldset></form><p v-if="mode==='moderation'&&chosen.author_account_id===session.account?.id" class="muted">不能独立隐藏本人创建的留言。</p><p v-if="mode==='comments'&&!ownsChosen" class="muted">只能以原账号和原办理主体撤回本人留言。</p></template><p v-else class="supply-empty">先选择一条实际留言，再填写本次理由。</p><p class="muted">{{mode==='moderation'?'独立操作另需 COMMENT_MODERATE 和原对象访问权限；决定及理由保留审计。':'撤回后保留作者、版本和状态，原文不再显示。'}}</p></section></div></template>

<template v-if="mode==='audit'"><section class="supply-card"><h2>运营操作历史</h2><p class="muted">需 OPERATIONS_AUDIT；这里仅展示运营记录已有的历史，不创建或推导授权授予记录。</p><form class="ops-toolbar" @submit.prevent="loadGlobalAudit()"><label>按实际运营对象编号筛选<input v-model.trim="filterId" data-testid="ops-audit-object-id" :disabled="locked" placeholder="可留空读取获准历史"></label><button class="outline" data-testid="ops-audit-refresh" :disabled="locked">读取运营操作历史</button></form><div class="table-wrap"><table><thead><tr><th>操作</th><th>实际账号 / 对象</th><th>理由</th><th>版本</th><th>发生时间（UTC）</th><th>请求痕迹</th></tr></thead><tbody><tr v-for="a in auditRows" :key="a.id"><td>{{eventText(a.event_code)}}</td><td>{{shortSupplyId(a.actor_account_id)}} / {{shortSupplyId(a.object_id)}}</td><td class="ops-audit-reason">{{a.reason||'原记录未保存理由'}}</td><td>{{a.object_version}}</td><td><time>{{a.created_at}}</time></td><td class="ops-audit-reason">{{a.request_id}}</td></tr></tbody></table></div><p v-if="!auditRows.length" class="supply-empty">当前范围没有已读取的运营历史。</p><button v-if="auditCursor!==null" class="outline" :disabled="locked" @click="loadGlobalAudit(true)">继续读取运营历史</button></section>
<section class="supply-card"><h2>原业务状态与决定历史</h2><p class="muted">OPERATIONS_AUDIT 与原对象访问权限均须通过。这里的历史不会覆盖当前业务状态。</p><div class="table-wrap"><table><thead><tr><th>原业务事件</th><th>实际账号</th><th>版本</th><th>发生时间（UTC）</th><th>请求痕迹</th></tr></thead><tbody><tr v-for="a in businessAudit" :key="a.id"><td>{{eventText(a.event_code)}}</td><td>{{a.actor_account_id?shortSupplyId(a.actor_account_id):'原记录无账号字段'}}</td><td>{{a.object_version}}</td><td>{{a.created_at}}</td><td class="ops-audit-reason">{{a.request_id}}</td></tr></tbody></table></div><p v-if="!businessAudit.length" class="supply-empty">选择并读取实际原对象后显示获准历史。</p><button v-if="businessCursor" class="outline" :disabled="locked" @click="loadObjectAudit(true)">继续读取原业务历史</button></section></template>

<template v-if="mode==='report-new'"><form @submit.prevent="requestReport"><fieldset :disabled="locked||!mayRequest"><section class="supply-card"><h2>报表类别与真实环境</h2><div class="ops-kind-options"><label v-for="(name,key) in reportKinds" :key="key" :class="{selected:requestDraft.kind===key}"><input v-model="requestDraft.kind" :data-testid="`ops-report-kind-${key}`" type="radio" name="report-kind" :value="key" required>{{name}}</label></div><label>实际交易环境 *<select v-model="requestDraft.environment" data-testid="ops-report-environment" required><option value="">明确选择</option><option value="SANDBOX">沙盒</option><option value="PRODUCTION">正式</option></select></label></section><section class="supply-card"><h2>UTC 期间与结果边界</h2><div class="trade-fields two"><label>UTC 期间开始（含） *<input v-model="requestDraft.start" data-testid="ops-report-start" type="datetime-local" step="1" required></label><label>UTC 期间结束（不含） *<input v-model="requestDraft.end" data-testid="ops-report-end" type="datetime-local" step="1" required></label></div><p class="muted">输入值按 UTC 保存；开始须早于结束，区间最多 366 天。结果最多 2000 条明细，超出范围须缩小期间。</p><ul><li>收退款只计已核实的真实交易，不等于利润。</li><li>结算明细保留应计、调整及真实付出，不重复当作收入。</li><li>制作情况采用生成时项目状态，排除不符合付款或环境条件的项目。</li></ul><p v-if="!operator&&!canOwner" class="supply-warning">本方报表由有效负责人申请；独立报表另有授权入口。</p><button class="primary" data-testid="ops-report-submit" :disabled="locked||!mayRequest||!requestPayload">申请报表并等待生成</button></section></fieldset></form><RouterLink :to="reportBase" class="button-link outline">读取已有报表任务</RouterLink></template>

<template v-if="mode==='reports'"><section class="supply-card"><div class="supply-section-heading"><h2>{{recordId?'当前实际报表任务':'读取已有报表任务'}}</h2><RouterLink :to="reportBase+'/new'" class="button-link primary">申请可追溯报表</RouterLink></div><p class="muted">当前接口没有任务列表。请使用申请实际返回的报表编号读取；以原申请账号和原主体核验，不能读取他人任务。</p><form class="trade-fields two" @submit.prevent="openReport"><label>已取得的实际报表编号 *<input v-model.trim="openId" data-testid="ops-report-id" maxlength="36" :disabled="locked" required></label><button class="outline" data-testid="ops-report-open" :disabled="locked||!validSupplyId(openId)">读取原报表任务</button></form></section>
<template v-if="report"><div class="ops-columns"><OperationsReportPanel :report="report"/><section class="supply-card ops-action"><h2>任务操作与私有结果</h2><p>{{reportStatus[report.current_status]}}</p><button class="outline" data-testid="ops-report-refresh" :disabled="locked" @click="refreshReport">刷新原任务实际状态</button><template v-if="report.current_status==='SUCCEEDED'&&report.result"><p class="muted">下载时服务器再次核验全部来源权限；撤权后不提供旧内容或公开地址兜底。CSV 金额字段单位为整数分。</p><button class="primary" data-testid="ops-download-csv" :disabled="locked" @click="downloadCsv">核验权限并下载 CSV</button><p v-if="csvUrl" class="muted">本次获准 CSV 已下载；当前身份变化时会回收下载内容。</p></template><form v-if="['FAILED','BLOCKED'].includes(report.current_status)" @submit.prevent="retryReport"><label>已核对条件的重试理由 *<textarea v-model="reason" data-testid="ops-report-retry-reason" maxlength="1000" required rows="4" :disabled="locked"></textarea></label><button class="primary" data-testid="ops-report-retry" :disabled="locked||!reason.trim()">申请原任务重试</button><p class="muted">沿用原期间和原任务；不会重建报表或擦除历史。</p></form><p v-if="['PENDING','RUNNING','RETRY'].includes(report.current_status)" class="muted">尚未完成，CSV 不可用。后台生成未运行时保持等待；不能通过重复申请使其变成成功。</p></section></div></template><p v-else-if="recordId&&!busy" class="supply-empty">尚未取得可显示的实际任务，请核对当前账号、原申请身份和访问权。</p></template>
</main></div></div></template>
