<script setup lang="ts">
import { computed, onMounted, onUnmounted, reactive, ref, watch } from 'vue'
import { onBeforeRouteLeave, onBeforeRouteUpdate, useRoute, useRouter } from 'vue-router'
import { useSessionStore } from '@/stores/session'
import { useProduction } from '@/composables/useProduction'
import { ApiError, asApiError } from '@/api/client'
import { listMembers } from '@/api/modules/account'
import type { Member } from '@/api/types'
import { listTrade, getTrade, money, type TradeRecord } from '@/api/modules/trade'
import { getSupply, listSupply, validSupplyId, type SupplyRecord, type MediaType, type SupplyAsset } from '@/api/modules/supply'
import { listLicense, type LicenseRecord } from '@/api/modules/licensing'
import { canDisplay } from '@/config/actions'
import { canStage, checkedStage, currentApproved, getProduction, listDependencies, productionContent, productionEvidence, productionJob, productionReadiness, productionStatus, stages, operations, type Stage, type FileMedia, type ProductionRecord, type Job, type Readiness, type Dependency } from '@/api/modules/production'
import WorkspaceNav from '@/components/WorkspaceNav.vue'
import ApiErrorAlert from '@/components/ApiErrorAlert.vue'
import SupplyUpload from '@/components/SupplyUpload.vue'
import ProductionUpload from '@/components/ProductionUpload.vue'
import ProductionRecordPanel from '@/components/ProductionRecordPanel.vue'
import ContractText from '@/components/ContractText.vue'
import '@/styles/supply.css'
import '@/styles/trade.css'
import '@/styles/production.css'
const session=useSessionStore(),route=useRoute(),router=useRouter()
const reviewer=computed(()=>route.name==='production-review'),newProject=computed(()=>route.name==='production-new'||route.name==='production-new-order'),operation=computed(()=>String(route.params.operation||'')),reviewSection=computed(()=>String(route.params.section||'projects')),versionPage=computed(()=>route.name==='production-feedback'||reviewer.value&&reviewSection.value==='versions'),generationReview=computed(()=>reviewer.value&&reviewSection.value==='generations'),recordId=computed(()=>String(route.params.recordId||''))
const context=()=>({token:session.token,accountId:session.account?.id||'',partyId:reviewer.value?null:session.selectedId,revision:session.revision,scope:route.fullPath})
const ui=useProduction(context),{rows,detail,nextCursor,error,notice,pending,busy,securityRevision,conflictRevision,retryAt}=ui
const project=ref<ProductionRecord|null>(null),files=ref<ProductionRecord[]>([]),versions=ref<ProductionRecord[]>([]),feedbacks=ref<ProductionRecord[]>([]),generations=ref<ProductionRecord[]>([]),digitalAssets=ref<ProductionRecord[]>([]),orders=ref<TradeRecord[]>([]),sourceOrder=ref<TradeRecord|null>(null),scripts=ref<SupplyRecord[]>([]),licenseProjects=ref<LicenseRecord[]>([]),members=ref<Member[]>([]),consents=ref<Dependency[]>([]),avatars=ref<Dependency[]>([]),readiness=ref<Readiness|null>(null),job=ref<Job|null>(null)
const initializing=ref(true),pageLoading=ref(false),openId=ref(''),stage=ref<Stage|' '>(' '),fileId=ref(''),previewId=ref(''),versionNote=ref(''),decision=ref(''),reason=ref(''),contractHash=ref(''),feedbackDecision=ref(''),feedbackNote=ref(''),assignmentAccount=ref(''),assignmentReason=ref(''),reasonRef=ref(''),previewRead=ref(false),evidenceRead=ref(false),previewText=ref(''),previewUrl=ref(''),assets=ref<string[]>([]),newConfirmation=ref(false),conflicted=ref(false),now=ref(Date.now())
const form=reactive({order:'',line:'',script:'',license:'',assignee:'',purpose:'',territory:'',consents:'',evidence:''}),generation=reactive({operation:'',avatar:'',asset:'',consent:''})
const checks=reactive<Record<string,boolean>>({identity_verified:false,signatures_verified:false,rights_verified:false,script_reviewed:false,specification_reviewed:false,audio_reviewed:false,branding_reviewed:false})
const isOwner=computed(()=>!!session.selected&&session.selected.membership.current_status==='ACTIVE'&&session.selected.membership.roles.includes('OWNER')&&!['CLOSED','SUSPENDED'].includes(session.selected.party.current_status))
const p=computed(()=>project.value?.kind==='PROJECT'?project.value:null),v=computed(()=>detail.value?.kind==='VERSION'?detail.value:null),g=computed(()=>detail.value?.kind==='GENERATION'?detail.value:null)
const isMerchant=computed(()=>!!p.value&&isOwner.value&&p.value.data.merchant_party_id===session.selectedId),isBuyer=computed(()=>!!p.value&&isOwner.value&&p.value.data.buyer_party_id===session.selectedId),isAssignee=computed(()=>!!p.value&&p.value.data.producer_party_id===session.selectedId&&p.value.data.assignee_account_id===session.account?.id)
const locked=computed(()=>busy.value||!!pending.value||now.value<retryAt.value||conflicted.value&&!newConfirmation.value)
const validConsents=computed(()=>form.consents.trim()?form.consents.trim().split(/[\s,，]+/):[])
const productionLines=computed(()=>sourceOrder.value?.kind==='ORDER'?sourceOrder.value.data.quote.lines.filter(l=>l.line_kind==='PRODUCTION'):[])
const selectedLine=computed(()=>productionLines.value.find(l=>l.line_id===form.line))
const createValid=computed(()=>isOwner.value&&sourceOrder.value?.kind==='ORDER'&&sourceOrder.value.merchant_party_id===session.selectedId&&selectedLine.value&&['OPEN','PARTIALLY_PAID','PAID'].includes(sourceOrder.value.current_status)&&[form.script,form.assignee,form.evidence].every(validSupplyId)&&(!form.license||validSupplyId(form.license))&&!!form.license===!!sourceOrder.value.data.quote.license_reservation_id&&form.purpose.trim()&&form.territory.trim()&&validConsents.value.length<=20&&validConsents.value.every(validSupplyId)&&new Set(validConsents.value).size===validConsents.value.length)
const stageChecklist=computed(()=>v.value?checkedStage(v.value.data.stage,checks):null)
const reviewValid=computed(()=>detail.value&&['PROJECT','VERSION'].includes(detail.value.kind)&&detail.value.current_status==='IN_REVIEW'&&detail.value.created_by!==session.account?.id&&decision.value&&reason.value.trim()&&(decision.value==='REJECTED'||detail.value.kind==='PROJECT'?decision.value==='REJECTED'||evidenceRead.value&&contractHash.value===p.value?.data.contract_sha256&&checks.identity_verified&&checks.signatures_verified&&checks.rights_verified:previewRead.value&&stageChecklist.value))
const versionValid=computed(()=>p.value&&isAssignee.value&&stage.value!==' '&&canStage(p.value,stage.value)&&versionNote.value.trim()&&files.value.some(f=>f.kind==='FILE'&&f.id===fileId.value&&f.current_status==='READY'&&f.data.media_type===(stage.value==='SCRIPT'?'text/plain':'video/mp4'))&&files.value.some(f=>f.kind==='FILE'&&f.id===previewId.value&&f.current_status==='READY'&&f.data.media_type===(stage.value==='SCRIPT'?'text/plain':'video/mp4'))&&(stage.value!=='FINAL'||(files.value.find(f=>f.id===fileId.value) as Extract<ProductionRecord,{kind:'FILE'}>|undefined)?.data.content_sha256!==(files.value.find(f=>f.id===previewId.value) as Extract<ProductionRecord,{kind:'FILE'}>|undefined)?.data.content_sha256))
const feedbackValid=computed(()=>p.value&&v.value&&isBuyer.value&&currentApproved(p.value,v.value)&&previewRead.value&&feedbackNote.value.trim()&&(feedbackDecision.value==='ACCEPT'?!!stageChecklist.value:feedbackDecision.value==='REQUEST_CHANGES'&&p.value.data.change_requests<p.value.data.specification.revision_limit))
const generationValid=computed(()=>p.value&&isAssignee.value&&readiness.value?.current_status==='SERVICE_READY'&&Object.hasOwn(operations,generation.operation)&&validSupplyId(generation.avatar)&&validSupplyId(generation.consent)&&p.value.data.consent_ids.includes(generation.consent)&&(generation.operation==='CREATE_LONG_LIVED'?!generation.asset:validSupplyId(generation.asset)))
const title=computed(()=>newProject.value?'建立制作任务':reviewer.value?reviewSection.value==='projects'?'开工依据独立核验':reviewSection.value==='versions'?'版本独立审片':'实际生成任务独立恢复':versionPage.value?'客户审片与阶段验收':operation.value==='assignment'?'调整制作负责人':operation.value==='generation'?'生成服务状态与任务':operation.value==='versions'?'提交制作版本':recordId.value?'制作项目与私有素材':'我参与的制作项目')
const gallery=computed(()=>newProject.value?'WEB-16-02':reviewer.value?reviewSection.value==='projects'?'WEB-17-02':reviewSection.value==='versions'?'WEB-18-02':'WEB-17-03-v2':versionPage.value?'WEB-18-03-v2':operation.value==='assignment'?'WEB-16-03-v2':operation.value==='generation'?'WEB-17-03-v2':operation.value==='versions'?'WEB-18-01':recordId.value?'WEB-17-01-v2':'WEB-16-01-v2')
let disposed=false,pageTicket=0,timer=0
function resetChecks(){Object.keys(checks).forEach(k=>checks[k]=false);decision.value=reason.value=feedbackDecision.value=feedbackNote.value=contractHash.value='';previewRead.value=evidenceRead.value=false;previewText.value=previewUrl.value='';ui.revoke()}
function reset(){pageTicket++;pageLoading.value=false;project.value=null;files.value=[];versions.value=[];feedbacks.value=[];generations.value=[];digitalAssets.value=[];orders.value=[];sourceOrder.value=null;scripts.value=[];licenseProjects.value=[];members.value=[];consents.value=[];avatars.value=[];readiness.value=null;job.value=null;openId.value=fileId.value=previewId.value=versionNote.value=assignmentAccount.value=assignmentReason.value=reasonRef.value='';stage.value=' ';assets.value=[];Object.keys(form).forEach(k=>form[k as keyof typeof form]='');Object.keys(generation).forEach(k=>generation[k as keyof typeof generation]='');conflicted.value=false;newConfirmation.value=false;resetChecks()}
watch(securityRevision,reset,{flush:'sync'})
watch(conflictRevision,()=>{resetChecks();fileId.value=previewId.value=versionNote.value=assignmentAccount.value=assignmentReason.value='';stage.value=' ';conflicted.value=true;newConfirmation.value=false;if(detail.value?.kind==='PROJECT')project.value=detail.value;else if(detail.value?.project_id){const id=detail.value.project_id;project.value=null;void ui.read('conflict-project',(i,s)=>getProduction(i,id,'PROJECT',s),r=>project.value=r)}},{flush:'sync'})
watch(()=>[route.fullPath,session.selectedId,session.revision],()=>{if(!initializing.value)void loadPage()})
watch(()=>form.order,()=>{sourceOrder.value=null;form.line='';members.value=[];form.assignee=''})
watch(()=>form.line,()=>{members.value=[];form.assignee='';if(selectedLine.value?.provider_party_id===session.selectedId)void loadMembers()})
watch(stage,()=>{fileId.value=previewId.value='';versionNote.value='';resetChecks()})
watch(()=>generation.operation,()=>generation.asset='')
async function listOrders(){await ui.read('orders',async(i,s)=>{const all:TradeRecord[]=[],seen=new Set<string>();let cursor:string|null=null;do{const page=await listTrade(i,'ORDER',cursor,s);all.push(...page.items);cursor=page.next_cursor;if(cursor&&seen.has(cursor))throw new ApiError({status:200,code:'UNEXPECTED_RESPONSE_SHAPE',message:'订单分页重复，请重新读取。'});if(cursor)seen.add(cursor)}while(cursor);return all},r=>orders.value=r.filter(x=>x.merchant_party_id===session.selectedId&&x.kind==='ORDER'&&x.data.quote.lines.some(l=>l.line_kind==='PRODUCTION')))}
async function loadMembers(){if(!canDisplay(session.selected?.party.allowed_actions,'MANAGE_MEMBERS'))return;await ui.read('members',async(i)=>{const all:Member[]=[],seen=new Set<string>();let cursor:string|null=null;do{const res=await listMembers(i.token,i.partyId!,cursor);all.push(...res.data.items);cursor=res.data.next_cursor;if(cursor&&seen.has(cursor))throw new ApiError({status:200,code:'UNEXPECTED_RESPONSE_SHAPE',message:'成员分页重复，请重新读取。'});if(cursor)seen.add(cursor)}while(cursor);return all},r=>members.value=r.filter(m=>m.current_status==='ACTIVE'))}
async function loadDependencies(){if(!isOwner.value)return;const scriptResult=await ui.read('scripts',async(i,s)=>{const all:SupplyRecord[]=[],seen=new Set<string>();let cursor:string|null=null;do{const page=await listSupply(i,'WORK_VERSION',cursor,s);all.push(...page.items);cursor=page.next_cursor;if(cursor&&seen.has(cursor))throw new ApiError({status:200,code:'UNEXPECTED_RESPONSE_SHAPE',message:'剧本分页重复，请重新读取。'});if(cursor)seen.add(cursor)}while(cursor);return all},r=>scripts.value=r.filter(w=>w.current_status==='REVIEWS_COMPLETE'));if(!scriptResult)return;const consentResult=await ui.read('consents',(i,s)=>listDependencies(i,'CONSENT',s),r=>consents.value=r);if(!consentResult)return;const avatarResult=await ui.read('avatars',(i,s)=>listDependencies(i,'AVATAR',s),r=>avatars.value=r);if(!avatarResult)return;await ui.read('license-projects',async(i,s)=>{const all:LicenseRecord[]=[],seen=new Set<string>();let cursor:string|null=null;do{const page=await listLicense(i,'PROJECT',false,cursor,s);all.push(...page.items);cursor=page.next_cursor;if(cursor&&seen.has(cursor))throw new ApiError({status:200,code:'UNEXPECTED_RESPONSE_SHAPE',message:'许可项目分页重复，请重新读取。'});if(cursor)seen.add(cursor)}while(cursor);return all},r=>licenseProjects.value=r)}
async function readOrder(){if(!validSupplyId(form.order)||locked.value)return;await ui.read('source-order',(i,s)=>getTrade(i,form.order,'ORDER',s),r=>sourceOrder.value=r)}
async function checkScript(){if(!validSupplyId(form.script)||locked.value)return;const r=await ui.read('script-check',(i,s)=>getSupply(i,form.script,'WORK_VERSION',s));if(r)notice.value=r.current_status==='REVIEWS_COMPLETE'?'已读取当前剧本，权属与内容双审已完成。':'当前剧本尚未完成双审，不能作为开工剧本。'}
async function loadCollections(id:string){const ticket=pageTicket;for(const [kind,target] of [['FILE',files],['VERSION',versions],['FEEDBACK',feedbacks],['GENERATION',generations],['DIGITAL_ASSET',digitalAssets]] as const){const result=await ui.loadAll(id,kind);if(disposed||ticket!==pageTicket)return;if(result)target.value=result;else return}}
async function loadPage(){const ticket=++pageTicket,current=()=>!disposed&&ticket===pageTicket;pageLoading.value=true;resetChecks();try{if(newProject.value){await listOrders();if(!current())return;await loadDependencies();if(!current())return;const known=String(route.params.orderId||'');if(validSupplyId(known)){form.order=known;await readOrder()}return}if(!recordId.value){if(!reviewer.value&&!versionPage.value)await ui.loadList();return}if(!validSupplyId(recordId.value)){error.value=new ApiError({status:400,code:'CLIENT_RECORD_INVALID',message:'请使用完整的制作记录编号。'});return}const kind=versionPage.value?'VERSION':generationReview.value?'GENERATION':'PROJECT',r=await ui.loadRecord(recordId.value,kind);if(!current()||!r)return;if(r.kind==='PROJECT')project.value=r;else if(r.project_id)await ui.read('project',(i,s)=>getProduction(i,r.project_id!,'PROJECT',s),value=>project.value=value);if(!current()||!p.value)return;if(generationReview.value){await readJob();return}if(reviewer.value)return;await loadCollections(p.value.id);if(!current())return;if(operation.value==='assignment'&&p.value.data.producer_party_id===session.selectedId)await loadMembers();if(operation.value==='generation'){await refreshReadiness();if(!current())return;await loadDependencies()}}finally{if(current())pageLoading.value=false}}
function leavePending(){if(ui.canNavigate())return true;notice.value='原提交或上传结果尚未确认，请先核对，再使用原请求编号重试。';return false}
onBeforeRouteLeave(leavePending);onBeforeRouteUpdate(leavePending)
function beforeUnload(e:BeforeUnloadEvent){if(!ui.canNavigate()){e.preventDefault();e.returnValue=''}}
onMounted(async()=>{timer=window.setInterval(()=>now.value=Date.now(),1000);window.addEventListener('beforeunload',beforeUnload);const captured=session.capture();try{await Promise.all([session.loadAccount(),session.loadParties()]);if(!disposed&&session.current(captured)){initializing.value=false;await loadPage()}}catch(e){if(!disposed&&session.current(captured)){ui.clear();error.value=asApiError(e)}}finally{if(!disposed)initializing.value=false}})
onUnmounted(()=>{disposed=true;pageTicket++;window.clearInterval(timer);window.removeEventListener('beforeunload',beforeUnload)})
function openRecord(){if(!validSupplyId(openId.value)||locked.value)return;void router.push(reviewer.value?`/production/reviews/${reviewSection.value}/${openId.value}`:versionPage.value?`/production/versions/${openId.value}`:`/production/projects/${openId.value}`)}
async function createProject(){if(!createValid.value||locked.value)return;await ui.write({path:'/production/projects',resultKind:'PROJECT',label:'创建制作项目',body:{order_id:form.order,line_id:form.line,script_version_id:form.script,license_project_id:form.license||null,assignee_account_id:form.assignee,purpose:form.purpose.trim(),territory:form.territory.trim(),consent_ids:validConsents.value,evidence_asset_id:form.evidence}},r=>void router.push(`/production/projects/${r.id}`))}
async function uploadEvidence(file:File,media:MediaType){if(locked.value||!isOwner.value)return;const path=`/supply/assets?${new URLSearchParams({purpose:'RIGHTS_EVIDENCE',media_type:media})}`;await ui.write({path,resultKind:'ASSET',label:'上传私有开工依据',supply:{path,blob:file,mediaType:media,purpose:'RIGHTS_EVIDENCE',kind:'ASSET',label:'上传私有开工依据'}},r=>{const a=r as SupplyAsset;assets.value=[a.id];form.evidence=a.id})}
async function uploadFile(file:File,media:FileMedia){if(locked.value||!p.value||!isAssignee.value)return;await ui.write({path:`/production/projects/${p.value.id}/files?${new URLSearchParams({media_type:media})}`,blob:file,mediaType:media,projectId:p.value.id,resultKind:'FILE',label:'上传私有制作文件'},()=>{if(p.value)void loadCollections(p.value.id)})}
async function assign(){if(!p.value||locked.value||!isMerchant.value||!validSupplyId(assignmentAccount.value)||!assignmentReason.value.trim())return;await ui.write({path:`/production/projects/${p.value.id}/assignment`,targetId:p.value.id,resultKind:'PROJECT',version:p.value.object_version,label:'更换制作负责人',body:{assignee_account_id:assignmentAccount.value,reason:assignmentReason.value.trim()}},()=>void loadPage())}
async function submitVersion(){if(!p.value||!versionValid.value||locked.value)return;await ui.write({path:`/production/projects/${p.value.id}/versions`,targetId:p.value.id,projectId:p.value.id,resultKind:'VERSION',version:p.value.object_version,label:'提交当前阶段版本',body:{stage:stage.value,file_id:fileId.value,preview_file_id:previewId.value,note:versionNote.value.trim()}},()=>{fileId.value=previewId.value=versionNote.value='';stage.value=' ';void loadPage()})}
async function readEvidence(){if(!p.value||locked.value||!reviewer.value)return;await ui.read('evidence',(i,s)=>productionEvidence(i,p.value!.id,s),blob=>{evidenceRead.value=true;const url=ui.objectUrl(blob),a=document.createElement('a');a.href=url;a.download=`开工依据-${p.value!.id}.bin`;a.click();notice.value='已从本项目权限接口读取私有依据。请实际核对材料后填写检查结论。'})}
async function readPreview(variant:'preview'|'final'='preview'){if(!v.value||locked.value)return;const current=v.value;await ui.read('content',async(i,s)=>{const file=await getProduction(i,variant==='preview'?current.data.preview_file_id:current.data.file_id,'FILE',s);if(file.kind!=='FILE')throw new ApiError({status:200,code:'UNEXPECTED_RESPONSE_SHAPE',message:'无法核对版本文件。'});const blob=await productionContent(i,current.id,variant,s),hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await blob.arrayBuffer())),x=>x.toString(16).padStart(2,'0')).join('');if(blob.size!==file.data.byte_size||hash!==file.data.content_sha256)throw new ApiError({status:503,code:'PRIVATE_CONTENT_MISMATCH',message:'私有文件内容未能核对，请重新读取。'});return {blob:new Blob([blob],{type:file.data.media_type}),text:file.data.media_type==='text/plain'?await blob.text():null}},value=>{if(variant==='final'){previewUrl.value='';const url=ui.objectUrl(value.blob),a=document.createElement('a');a.href=url;a.download=`${stages[current.data.stage]}-${current.id}.${current.data.stage==='SCRIPT'?'txt':'mp4'}`;a.click();notice.value='已通过服务器当前权限及付款检查，发起本版文件下载。'}else{previewRead.value=true;previewText.value=value.text||'';previewUrl.value=value.text===null?ui.objectUrl(value.blob):'';notice.value='已实际读取本版受控预览，请核对内容后作出决定。'}})}
async function review(){if(!reviewValid.value||locked.value||!detail.value)return;const r=detail.value;const verification=decision.value==='REJECTED'?null:r.kind==='PROJECT'?{contract_sha256:contractHash.value,identity_verified:true,signatures_verified:true,rights_verified:true}:stageChecklist.value;await ui.write({path:`/production/records/${r.id}/reviews`,targetId:r.id,resultKind:r.kind,version:r.object_version,label:r.kind==='PROJECT'?'提交独立核验':'提交独立审片',body:{decision:decision.value,reason:reason.value.trim(),verification}},()=>void loadPage())}
async function submitFeedback(){if(!v.value||!feedbackValid.value||locked.value)return;const r=v.value;await ui.write({path:`/production/versions/${r.id}/feedback`,targetId:r.id,projectId:r.project_id!,resultKind:'FEEDBACK',version:r.object_version,label:'提交本版反馈',body:{decision:feedbackDecision.value,note:feedbackNote.value.trim(),checklist:feedbackDecision.value==='ACCEPT'?stageChecklist.value:null}},()=>void loadPage())}
async function refreshReadiness(){if(!p.value||reviewer.value)return;readiness.value=null;await ui.read('readiness',(i,s)=>productionReadiness(i,p.value!.id,s),r=>readiness.value=r)}
async function requestGeneration(){if(!p.value||!generationValid.value||locked.value)return;await ui.write({path:`/production/projects/${p.value.id}/generation`,targetId:p.value.id,projectId:p.value.id,resultKind:'GENERATION',version:p.value.object_version,label:'建立实际生成请求',body:{operation:generation.operation,avatar_id:generation.avatar,asset_id:generation.operation==='CREATE_LONG_LIVED'?null:generation.asset,consent_id:generation.consent}},()=>void loadPage())}
async function readJob(id=g.value?.id||''){if(!validSupplyId(id))return;job.value=null;await ui.read('job',(i,s)=>productionJob(i,id,s),r=>job.value=r)}
async function retryGeneration(){if(!g.value||locked.value||!reasonRef.value.trim()||!job.value||!['BLOCKED','FAILED'].includes(job.value.current_status))return;const r=g.value;await ui.write({path:`/production/generations/${r.id}/retry`,targetId:r.id,projectId:r.project_id!,resultKind:'GENERATION',label:'恢复原任务',body:{reason_ref:reasonRef.value.trim()}},()=>void loadPage())}
</script>
<template>
<div class="supply-workspace trade-workspace production-workspace" :data-gallery="gallery"><header class="supply-header"><RouterLink to="/workspace" class="supply-brand">晶晶日上</RouterLink><span>运营与合作方工作台</span><div class="account-actions"><span class="account-name">{{session.account?.display_name||'当前账号'}}</span><button @click="session.logout().then(()=>router.push('/login'))">退出</button></div></header><div class="supply-layout"><aside class="supply-sidebar"><WorkspaceNav/><div class="supply-identity"><template v-if="reviewer"><p>独立制作核验</p><p class="muted">以当前账号办理；制作核验权限由服务器核验，不能自行取得。</p></template><template v-else><label for="production-party">当前办理身份</label><select id="production-party" :value="session.selectedId" :disabled="locked" @change="session.selectParty(($event.target as HTMLSelectElement).value)"><option v-for="access in session.parties" :key="access.party.id" :value="access.party.id">{{access.party.display_name}}</option></select><p class="muted">{{isOwner?'有效负责人身份':'当前成员身份；仅本人获分配项目可办理'}}</p></template></div></aside><main class="supply-main">
<div class="supply-heading"><div><h1>{{title}}</h1><p>{{reviewer?'读取原始材料后，独立核验本次项目或指定版本。':'按照原订单约定完成制作、逐版反馈与验收。'}}</p></div><button class="outline" :disabled="locked||pageLoading" @click="loadPage">刷新当前记录</button></div>
<div class="loaded-tabs"><template v-if="reviewer"><RouterLink to="/production/reviews/projects" :class="{active:reviewSection==='projects'}">开工依据核验</RouterLink><RouterLink to="/production/reviews/versions" :class="{active:reviewSection==='versions'}">交付版本审片</RouterLink><RouterLink to="/production/reviews/generations" :class="{active:reviewSection==='generations'}">实际任务恢复</RouterLink></template><template v-else><RouterLink to="/production/projects" :class="{active:!versionPage}">参与制作项目</RouterLink><RouterLink to="/production/versions" :class="{active:versionPage}">版本反馈与验收</RouterLink></template></div>
<ApiErrorAlert :error="error"/><p v-if="notice" class="supply-notice" role="status">{{notice}}</p>
<div v-if="pending" class="supply-warning"><p>{{pending.command.label}}结果尚未确认。保留原请求、内容、文件及原版本；请先核对现有记录。{{pending.resultId?`已知结果记录：${pending.resultId}`:''}}</p><details><summary>原操作编号</summary><p class="identifier">{{pending.key}}</p></details><div class="supply-actions"><button class="outline" :disabled="busy||now<retryAt" @click="ui.checkPending()">{{pending.resultId?'重新读取已知结果':'先核对原记录'}}</button><button v-if="!pending.resultId&&pending.state!=='blocked'" class="primary" :disabled="busy||!pending.checked||now<retryAt" @click="ui.retry()">使用原编号重试</button><button v-if="pending.state==='blocked'" class="outline" :disabled="busy||!pending.checked" @click="ui.endBlocked()">结束已拒绝上传的核对</button></div></div>
<div v-if="conflicted" class="supply-warning"><label class="trade-check"><input v-model="newConfirmation" type="checkbox" data-testid="production-reconfirm">我已核对最新记录，将重新填写并作出决定。</label></div>
<p v-if="initializing||pageLoading" class="supply-empty" role="status">正在读取身份与制作记录…</p>
<div v-else :key="route.fullPath+securityRevision">
<form v-if="newProject" class="trade-form" @submit.prevent="createProject"><fieldset :disabled="locked||!isOwner">
<section class="supply-card"><h2>原订单与制作明细</h2><div class="trade-fields two"><label>原订单编号 *<input v-model="form.order" list="production-orders" data-testid="production-order-id" required placeholder="选择本人订单或填写完整编号"><datalist id="production-orders"><option v-for="order in orders" :key="order.id" :value="order.id">{{order.kind==='ORDER'?money(order.data.quote.total_minor):''}} · {{order.current_status}}</option></datalist></label><div class="production-field-action"><button type="button" class="outline" :disabled="!validSupplyId(form.order)" @click="readOrder">读取原订单</button></div><label>原订单制作明细 *<select v-model="form.line" data-testid="production-line-id" required><option value="">待选择已读取订单的制作明细</option><option v-for="line in productionLines" :key="line.line_id" :value="line.line_id">{{line.title}} · {{line.line_id}} · {{money(line.total_minor)}}</option></select></label><label>实际制作方<input :value="selectedLine?.provider_party_id||'选择原制作明细后显示'" readonly></label></div><p v-if="sourceOrder&&!productionLines.length" class="supply-warning">本单没有制作明细，不能建立制作项目。</p><p class="muted">制作方和规格取自原成交明细。此处不改价，也不改变原付款节点。</p></section>
<section class="supply-card"><h2>剧本、许可与负责账号</h2><div class="trade-fields two"><label>已审剧本版本编号 *<input v-model="form.script" list="production-scripts" data-testid="production-script-id" required placeholder="选择可读版本或填已获准使用的版本编号"><datalist id="production-scripts"><option v-for="script in scripts" :key="script.id" :value="script.id">{{script.kind==='WORK_VERSION'?script.data.version.content.title:''}}</option></datalist></label><label>关联许可项目编号<input v-model="form.license" list="production-license-projects" data-testid="production-license-id" :required="sourceOrder?.kind==='ORDER'&&!!sourceOrder.data.quote.license_reservation_id" placeholder="原订单有许可时须填当前绑定项目"><datalist id="production-license-projects"><option v-for="license in licenseProjects" :key="license.id" :value="license.id">{{license.kind==='PROJECT'?license.data.title:''}}</option></datalist></label></div><button type="button" class="outline production-secondary" :disabled="!validSupplyId(form.script)" @click="checkScript">读取已审剧本</button><label>负责账号编号 *<select v-if="members.length" v-model="form.assignee" data-testid="production-assignee" required><option value="">选择制作方当前成员</option><option v-for="member in members" :key="member.account_id" :value="member.account_id">{{member.account_id}} · {{member.role_code}}</option></select><input v-else v-model="form.assignee" data-testid="production-assignee" required placeholder="实际制作方当前成员的完整账号编号"></label><p class="muted">仅列出当前身份有权读取的剧本与成员。其他已知编号须来自实际当事方，服务器将核验归属及当前有效状态。</p></section>
<section class="supply-card"><h2>用途、地域与真实同意</h2><div class="trade-fields two"><label>本次用途 *<input v-model="form.purpose" maxlength="100" data-testid="production-purpose" required placeholder="待明确填写原约定用途"></label><label>本次地域 *<input v-model="form.territory" maxlength="100" data-testid="production-territory" required placeholder="待明确填写原约定地域"></label></div><label>同意记录编号<textarea v-model="form.consents" data-testid="production-consents" placeholder="最多20个；每行一个完整编号，未使用相关特征时按实际留空"></textarea></label><details v-if="consents.length" class="trade-rules"><summary>当前身份可读的同意记录</summary><div v-for="consent in consents" :key="consent.id" class="trade-row"><p class="identifier">{{consent.id}} · {{consent.current_status}}</p><p>{{consent.data.consent?.features.join('、')}} · {{consent.data.consent?.purposes.join('、')}} · {{consent.data.consent?.territories.join('、')}}</p></div></details><p class="muted">同意声明不等于实名核验。长期数字人另需明确 AI_TRAIN 同意；AI 处理仍受许可及同意范围限制。</p></section>
<section class="supply-card"><h2>真实外部开工依据</h2><label>已上传私有依据编号 *<input v-model="form.evidence" data-testid="production-evidence-id" required placeholder="本订单买方或商家归属的私有材料"></label><SupplyUpload :key="securityRevision" :disabled="locked||!isOwner" label="私有合同、签署、身份与权利证明" :ids="assets" single @upload="uploadEvidence" @remove="assets=[];form.evidence=''"/><p class="muted">已有外部材料可填写原编号；也可上传后引用。创建项目后独立核验真实签署、身份和权利，不自报审核成功。</p></section>
<div class="trade-footer"><RouterLink to="/production/projects" class="button-link outline">返回项目列表</RouterLink><button class="primary" :disabled="locked||!createValid" data-testid="production-create">创建制作项目</button></div>
</fieldset></form>
<template v-else-if="!recordId"><section class="supply-card"><h2>{{reviewer?'读取获准独立核验的记录':versionPage?'读取本次反馈的版本':'当前身份参与的制作项目'}}</h2><p class="muted">{{reviewer?'没有跨机构审核目录接口。使用实际项目、交付版本或生成记录编号读取。':versionPage?'从项目版本历史进入指定版本，或填写当事方提供的完整版本编号。':'仅加载本人机构或本人获分配的实际项目。'}}</p><div class="trade-list-actions"><RouterLink v-if="!reviewer&&!versionPage" to="/production/projects/new" class="button-link primary">新建制作项目</RouterLink><label>{{versionPage?'版本编号':generationReview?'生成记录编号':'项目编号'}}<input v-model="openId" data-testid="production-open-id" placeholder="完整记录编号"></label><button class="outline" :disabled="locked||!validSupplyId(openId)" @click="openRecord">打开制作记录</button></div><div v-if="rows.length" class="table-wrap"><table><thead><tr><th>项目编号</th><th>当前状态</th><th>原订单明细与负责人</th><th>操作</th></tr></thead><tbody><tr v-for="row in rows" :key="row.id"><td class="identifier">{{row.id}}</td><td>{{productionStatus(row)}}</td><td v-if="row.kind==='PROJECT'">{{row.data.line_id}}<div class="identifier">{{row.data.assignee_account_id}}</div></td><td><RouterLink :to="`/production/projects/${row.id}`" class="button-link table-link">查看项目素材</RouterLink></td></tr></tbody></table></div><p v-else-if="!reviewer&&!versionPage" class="supply-empty">当前没有可读取项目。可从含制作明细的原订单建立项目。</p><button v-if="nextCursor" class="outline" :disabled="locked" @click="ui.loadList(undefined,undefined,true)">加载下一页项目</button></section></template>
<template v-else-if="detail&&p">
<div v-if="!reviewer" class="loaded-tabs production-project-tabs"><RouterLink :to="`/production/projects/${p.id}`" :class="{active:!operation&&!versionPage}">项目素材</RouterLink><RouterLink :to="`/production/projects/${p.id}/assignment`" :class="{active:operation==='assignment'}">负责人</RouterLink><RouterLink :to="`/production/projects/${p.id}/generation`" :class="{active:operation==='generation'}">生成状态</RouterLink><RouterLink :to="`/production/projects/${p.id}/versions`" :class="{active:operation==='versions'}">交付版本</RouterLink><RouterLink :to="`/trade/orders/${p.order_id}`">原订单与付款</RouterLink><RouterLink to="/projects/projects/new">建立公开分享或发行项目</RouterLink><RouterLink to="/finance/agreements">读取本方结算约定与余额</RouterLink></div>
<div :class="reviewer||versionPage?'review-layout':''"><div><ProductionRecordPanel :record="versionPage||generationReview?detail:p" :compact="reviewer"/>
<section v-if="v" class="supply-card"><h2>本版受控预览</h2><p class="muted">内部批准不代表客户验收。预览需真实读取，核对本版剧本、规格、声音与品牌标识。</p><button class="outline" :disabled="locked" @click="readPreview('preview')" data-testid="production-read-preview">读取本版受控预览</button><pre v-if="previewText" class="production-text-preview">{{previewText}}</pre><video v-if="previewUrl" :src="previewUrl" controls preload="metadata" class="production-video" aria-label="本版私有视频预览"></video><p v-if="previewRead" class="supply-notice">已实际读取本版预览；请按看过的内容填写检查。</p></section>
<section v-if="reviewer&&reviewSection==='projects'" class="supply-card"><h2>开工私有依据</h2><p class="muted">实际阅读外部合同、签署、身份和权利材料后再作结论。拒绝后没有自动补件重新开工接口。</p><button class="outline" :disabled="locked" @click="readEvidence" data-testid="production-read-evidence">读取开工私有依据</button><p v-if="evidenceRead" class="supply-notice">已通过本项目权限接口读取私有依据。</p></section>
</div>
<section v-if="reviewer&&!generationReview" class="supply-card production-review-form"><h2>{{v?'本版独立审片':'独立开工核验'}}</h2><form @submit.prevent="review"><fieldset :disabled="locked||detail.current_status!=='IN_REVIEW'||detail.created_by===session.account?.id"><template v-if="reviewSection==='projects'"><label>实际核对的合同指纹 *<input v-model="contractHash" data-testid="production-contract-hash" maxlength="64" placeholder="原保存合同的完整SHA-256"></label><label class="trade-check"><input v-model="checks.identity_verified" type="checkbox" data-testid="production-check-identity">我已核对真实外部身份材料</label><label class="trade-check"><input v-model="checks.signatures_verified" type="checkbox" data-testid="production-check-signatures">我已核对当事方真实签署材料</label><label class="trade-check"><input v-model="checks.rights_verified" type="checkbox" data-testid="production-check-rights">我已核对本用途和地域的实际权利</label></template><template v-else><label class="trade-check"><input v-model="checks.script_reviewed" type="checkbox" data-testid="production-check-script">已实际核对剧本内容</label><template v-if="v?.data.stage!=='SCRIPT'"><label class="trade-check"><input v-model="checks.specification_reviewed" type="checkbox" data-testid="production-check-specification">已核对原成交时长及交付规格</label><label class="trade-check"><input v-model="checks.audio_reviewed" type="checkbox" data-testid="production-check-audio">已实际听审声音</label><label class="trade-check"><input v-model="checks.branding_reviewed" type="checkbox" data-testid="production-check-branding">已核对实际品牌与预览标识</label></template></template><label>本次决定 *<select v-model="decision" data-testid="production-review-decision" required><option value="">待选择</option><option value="APPROVED">批准</option><option value="REJECTED">拒绝</option></select></label><label>本次核验理由 *<textarea v-model="reason" data-testid="production-review-reason" maxlength="2000" required placeholder="填写本次实际核验依据"></textarea></label><button class="primary" :disabled="locked||!reviewValid" data-testid="production-review-submit">{{v?'提交独立审片':'提交独立核验'}}</button></fieldset></form><p class="muted">独立核验与客户决定分别保存；创建者及当事方不能独立审核自己参与的项目。</p></section>
<section v-if="versionPage&&!reviewer&&v" class="supply-card production-review-form"><h2>本版客户反馈与验收</h2><form @submit.prevent="submitFeedback"><fieldset :disabled="locked||!isBuyer||!currentApproved(p,v)"><p v-if="!currentApproved(p,v)" class="supply-warning">本记录不是当前内部已批准的版本，不能提交本次客户决定。</p><label class="trade-check"><input v-model="checks.script_reviewed" type="checkbox" data-testid="production-check-script">我已核对本版剧本</label><template v-if="v.data.stage!=='SCRIPT'"><label class="trade-check"><input v-model="checks.specification_reviewed" type="checkbox" data-testid="production-check-specification">我已核对原订单规格与时长</label><label class="trade-check"><input v-model="checks.audio_reviewed" type="checkbox" data-testid="production-check-audio">我已核对本版声音</label><label class="trade-check"><input v-model="checks.branding_reviewed" type="checkbox" data-testid="production-check-branding">我已核对本版品牌与标识</label></template><label>对本版的决定 *<select v-model="feedbackDecision" data-testid="production-feedback-decision" required><option value="">待选择</option><option value="ACCEPT">确认验收本版</option><option value="REQUEST_CHANGES" :disabled="p.data.change_requests>=p.data.specification.revision_limit">请求修改本版</option></select></label><label>本次说明 *<textarea v-model="feedbackNote" data-testid="production-feedback-note" maxlength="4000" required placeholder="明确逐版本反馈内容"></textarea></label><button class="primary" :disabled="locked||!feedbackValid" data-testid="production-feedback-submit">提交本版反馈</button></fieldset></form><p class="muted">客户修改已用 {{p.data.change_requests}} / 原约定 {{p.data.specification.revision_limit}} 次。内部修订不消耗客户次数；本页面不自动加价。</p><div v-if="v.data.stage==='FINAL'" class="production-delivery"><h3>最终受控交付</h3><p class="muted">当前成片已验收且原订单全部约定款项收齐后，由服务器允许最终下载。付款不代表验收，验收也不代表已收款。</p><button class="outline" :disabled="locked||!isBuyer||p.data.accepted.FINAL!==v.id||!currentApproved(p,v)" @click="readPreview('final')" data-testid="production-download-final">下载最终受控文件</button></div></section>
</div>
<template v-if="!reviewer&&!versionPage">
<form v-if="operation==='assignment'" @submit.prevent="assign"><fieldset :disabled="locked||!isMerchant"><section class="supply-card"><h2>新负责人及变更理由</h2><label>新负责账号 *<select v-if="members.length" v-model="assignmentAccount" data-testid="production-new-assignee" required><option value="">选择制作方当前成员</option><option v-for="member in members" :key="member.account_id" :value="member.account_id">{{member.account_id}} · {{member.role_code}}</option></select><input v-else v-model="assignmentAccount" data-testid="production-new-assignee" required placeholder="实际制作方当前成员的完整账号编号"></label><label>更换理由 *<textarea v-model="assignmentReason" data-testid="production-assignment-reason" maxlength="2000" required></textarea></label><p class="muted">只更换原制作方当前成员。被移除成员不能继续上传或提交，身份与权限由服务器再次核验。</p><button class="primary" :disabled="locked||!isMerchant||!validSupplyId(assignmentAccount)||!assignmentReason.trim()">保存负责人变更</button></section></fieldset></form>
<template v-else-if="operation==='generation'">
<section class="supply-card"><h2>实际服务可用状态</h2><dl class="supply-facts"><div><dt>生成服务</dt><dd>{{readiness?.current_status==='SERVICE_READY'?'服务器报告服务可用':readiness?'未启用（NOT_ENABLED）':'尚未确认可用，操作保持关闭'}}</dd></div><div><dt>当前原因</dt><dd>{{readiness?.reason_code||'尚未取得可用状态'}}</dd></div></dl><p v-if="readiness?.environment==='SANDBOX'" class="muted">当前为测试环境记录，不能据此认定正式生成服务已经开通。</p><p v-if="readiness?.current_status!=='SERVICE_READY'" class="supply-warning">实际生成服务尚未启用或可用状态未确认，当前不能发起生成。本页不会展示示例成片作为生成结果。</p><details v-if="readiness" class="trade-rules"><summary>当前服务配置事实</summary><p>{{readiness.provider_code}} · {{readiness.environment}} · {{readiness.config_revision}}</p></details><button class="outline" :disabled="locked" @click="refreshReadiness">查询服务可用状态</button></section>
<form @submit.prevent="requestGeneration"><fieldset :disabled="locked||!isAssignee||readiness?.current_status!=='SERVICE_READY'"><section class="supply-card"><h2>生成与资产操作</h2><div class="trade-fields two"><label>本次操作 *<select v-model="generation.operation" data-testid="production-generation-operation" required><option value="">待选择</option><option v-for="(label,key) in operations" :key="key" :value="key">{{label}}</option></select></label><label>实际数字人编号 *<input v-model="generation.avatar" list="production-avatars" data-testid="production-avatar-id" required placeholder="当前有效数字人记录编号"><datalist id="production-avatars"><option v-for="avatar in avatars" :key="avatar.id" :value="avatar.id">{{avatar.data.display_name}}</option></datalist></label><label>本项目实际同意记录 *<select v-model="generation.consent" data-testid="production-generation-consent" required><option value="">待选择项目引用的同意</option><option v-for="id in p.data.consent_ids" :key="id" :value="id">{{id}}</option></select></label><label v-if="generation.operation&&generation.operation!=='CREATE_LONG_LIVED'">长期资产编号 *<select v-model="generation.asset" data-testid="production-digital-asset" required><option value="">待选择本项目实际资产</option><option v-for="asset in digitalAssets" :key="asset.id" :value="asset.id" :disabled="generation.operation==='RENDER'?asset.current_status!=='READY':!['READY','DELETE_REQUIRED'].includes(asset.current_status)">{{asset.id}} · {{productionStatus(asset)}}</option></select></label></div><p class="muted">建立长期资产须真实 AI_TRAIN 同意；生成视频须已验收当前剧本及相应 AI_PROCESS 权利。删除请求受理不等于上游已删除。</p><button class="primary" :disabled="locked||!generationValid">建立实际生成请求</button></section></fieldset></form>
<section class="supply-card"><h2>实际任务与长期资产记录</h2><div v-for="record in generations" :key="record.id" class="trade-row"><p>{{record.kind==='GENERATION'?operations[record.data.operation]:''}} · {{productionStatus(record)}}</p><p class="identifier">{{record.id}}</p><button class="outline" :disabled="locked" @click="readJob(record.id)">读取实际任务</button><RouterLink :to="`/production/reviews/generations/${record.id}`" class="button-link outline">独立恢复原任务</RouterLink><details v-if="record.kind==='GENERATION'" class="trade-rules"><summary>服务已保存结果</summary><ContractText :value="record.data.result"/></details></div><p v-if="!generations.length" class="supply-empty">尚无已读取的生成任务。</p><div v-for="asset in digitalAssets" :key="asset.id" class="trade-row"><p>长期资产 · {{productionStatus(asset)}}</p><p class="identifier">{{asset.id}}</p></div></section>
</template>
<template v-else>
<section class="supply-card"><h2>{{operation==='versions'?'上传阶段交付与预览':'项目私有素材'}}</h2><ProductionUpload :key="securityRevision" :disabled="locked||!isAssignee||!['READY','IN_PROGRESS'].includes(p.current_status)" @upload="uploadFile"/><p v-if="!isAssignee" class="muted">只有原制作方当前获分配账号可以上传与提交；机构负责人仍可读取项目。</p><p class="muted">上传和生成仍须满足原订单首期实际到账条件；服务器再次核验，独立批准不代表已经到账。</p><p v-if="p.current_status==='IN_REVIEW'" class="supply-warning">项目尚待独立开工核验；上传还须满足原订单首期实际到账条件。</p><div v-if="files.length" class="table-wrap"><table><thead><tr><th>私有文件编号</th><th>类型</th><th>大小</th><th>实际状态</th></tr></thead><tbody><tr v-for="file in files" :key="file.id"><td class="identifier">{{file.id}}</td><template v-if="file.kind==='FILE'"><td>{{file.data.media_type}}</td><td>{{file.data.byte_size.toLocaleString('zh-CN')}} 字节</td></template><td>{{productionStatus(file)}}</td></tr></tbody></table></div><p v-else class="supply-empty">尚无已读取的私有制作文件。</p></section>
<form v-if="operation==='versions'" @submit.prevent="submitVersion"><fieldset :disabled="locked||!isAssignee"><section class="supply-card"><h2>提交当前阶段版本</h2><div class="trade-fields two"><label>当前提交阶段 *<select v-model="stage" data-testid="production-stage" required><option value=" ">待选择</option><option v-for="(label,key) in stages" :key="key" :value="key" :disabled="!canStage(p,key)">{{label}}</option></select></label><label>交付原文件 *<select v-model="fileId" data-testid="production-version-file" required><option value="">选择已上传可引用文件</option><option v-for="file in files.filter(f=>f.kind==='FILE'&&f.current_status==='READY'&&f.data.media_type===(stage==='SCRIPT'?'text/plain':'video/mp4'))" :key="file.id" :value="file.id">{{file.id}}</option></select></label><label>受控预览文件 *<select v-model="previewId" data-testid="production-version-preview" required><option value="">选择实际预览文件</option><option v-for="file in files.filter(f=>f.kind==='FILE'&&f.current_status==='READY'&&f.data.media_type===(stage==='SCRIPT'?'text/plain':'video/mp4'))" :key="file.id" :value="file.id">{{file.id}}</option></select></label></div><label>本次版本说明 *<textarea v-model="versionNote" data-testid="production-version-note" maxlength="2000" required placeholder="说明本次真实修改和交付"></textarea></label><p class="muted">每次提交生成不可覆盖的新版本。阶段顺序为剧本、样片、粗剪、成片；前阶段当前版须已获客户验收。成片原文件和预览内容必须不同，实际标识由审片人检查。</p><button class="primary" :disabled="locked||!versionValid" data-testid="production-version-submit">提交当前阶段版本</button></section></fieldset></form>
</template>
<section v-if="operation!=='assignment'" class="supply-card"><h2>历史版本与逐版反馈</h2><div class="table-wrap" v-if="versions.length"><table><thead><tr><th>阶段与修订</th><th>内部状态</th><th>当前版 / 客户验收</th><th>操作</th></tr></thead><tbody><tr v-for="version in versions" :key="version.id"><template v-if="version.kind==='VERSION'"><td>{{stages[version.data.stage]}} · 第 {{version.data.revision}} 版</td><td>{{productionStatus(version)}}</td><td>{{p.data.current[version.data.stage]===version.id?'当前版':'历史版'}} · {{p.data.accepted[version.data.stage]===version.id?'已验收':'未验收'}}</td><td><RouterLink :to="`/production/versions/${version.id}`" class="button-link table-link">本版反馈与验收</RouterLink><RouterLink :to="`/production/reviews/versions/${version.id}`" class="button-link table-link">独立审片</RouterLink></td></template></tr></tbody></table></div><p v-else class="supply-empty">尚无已读取的交付版本。</p><details v-if="feedbacks.length" class="trade-rules"><summary>客户历史反馈（{{feedbacks.length}}）</summary><article v-for="feedback in feedbacks" :key="feedback.id" class="trade-row"><template v-if="feedback.kind==='FEEDBACK'"><h3>{{stages[feedback.data.stage]}} · {{feedback.data.decision==='ACCEPT'?'验收':'请求修改'}}</h3><p class="long-text">{{feedback.data.note}}</p><p class="identifier">对应版本 {{feedback.data.version_id}}</p></template></article></details></section>
</template>
<section v-if="job" class="supply-card"><h2>实际任务状态</h2><dl class="supply-facts"><div><dt>当前状态</dt><dd>{{job.current_status}}</dd></div><div><dt>实际尝试次数</dt><dd>{{job.attempts}}</dd></div><div><dt>当前阻止原因</dt><dd>{{job.last_error||'未记录失败原因'}}</dd></div></dl><details class="trade-rules"><summary>任务与请求编号</summary><p class="identifier">{{job.job_id}}<br>{{job.record_id}}</p></details><p class="muted">BLOCKED、待核实和排队均不表示视频成功。长期资产的删除完成须由实际服务确认。</p></section>
<section v-if="generationReview&&g" class="supply-card"><h2>独立恢复原任务</h2><p class="muted">读取实际失败原因并填写真实处理依据。恢复只核对原外部请求，不重新发起付费创建。</p><button class="outline" :disabled="locked" @click="readJob()">读取实际任务</button><form @submit.prevent="retryGeneration"><label>真实恢复依据编号 *<input v-model="reasonRef" data-testid="production-retry-reason" maxlength="128" required placeholder="本次人工处理依据"></label><button class="primary" :disabled="locked||!reasonRef.trim()||!job||!['BLOCKED','FAILED'].includes(job.current_status)" data-testid="production-retry-submit">恢复原任务</button></form></section>
<div class="trade-footer"><RouterLink :to="reviewer?`/production/reviews/${reviewSection}`:'/production/projects'" class="button-link outline">返回{{reviewer?'核验入口':'项目列表'}}</RouterLink><RouterLink v-if="!reviewer&&!operation&&!versionPage" :to="`/production/projects/${p.id}/versions`" class="button-link primary">进入交付版本</RouterLink></div>
</template>
<p v-else class="supply-empty">未读取到可获准查看的制作记录，请核对编号与当前身份。</p>
</div></main></div></div>
</template>
