<script setup lang="ts">
import {computed,onMounted,onUnmounted,reactive,ref,watch} from 'vue'
import {onBeforeRouteLeave,onBeforeRouteUpdate,useRoute,useRouter} from 'vue-router'
import {useSessionStore} from '@/stores/session'
import {useProject} from '@/composables/useProjects'
import {ApiError,asApiError} from '@/api/client'
import {explainError} from '@/api/errors'
import {layers,reviewFields,verificationLabels,kindLabels,projectStatus,confirmationGate,evidenceIds,parseMoney,getProject,projectCatalogue,projectConfirmations,projectReadiness,projectEvidence,type ProjectRecord,type ProjectKind,type ChildKind,type CatalogueItem,type CatalogueRole,type Confirmation,type ProjectReadiness} from '@/api/modules/projects'
import {getProduction,listProduction,listDependencies,type ProductionRecord,type Dependency} from '@/api/modules/production'
import {listTrade,money,type TradeRecord} from '@/api/modules/trade'
import {validSupplyId,type MediaType,type SupplyAsset} from '@/api/modules/supply'
import WorkspaceNav from '@/components/WorkspaceNav.vue'
import ApiErrorAlert from '@/components/ApiErrorAlert.vue'
import SupplyUpload from '@/components/SupplyUpload.vue'
import ProjectRecordPanel from '@/components/ProjectRecordPanel.vue'
import ProjectPlanForm,{type RightDraft,type SignerDraft,type FundingDraft} from '@/components/ProjectPlanForm.vue'
import '@/styles/supply.css'
import '@/styles/trade.css'
import '@/styles/projects.css'
const session=useSessionStore(),route=useRoute(),router=useRouter()
const mode=computed(()=>String(route.meta.projectView||'list')),reviewer=computed(()=>mode.value==='review'),recordId=computed(()=>String(route.params.recordId||'')),section=computed(()=>String(route.params.section||'plans'))
const context=()=>({token:session.token,accountId:session.account?.id||'',partyId:reviewer.value?null:session.selectedId,revision:session.revision,scope:route.fullPath})
const ui=useProject(context),{rows,detail,nextCursor,error,notice,pending,busy,securityRevision,conflictRevision,retryAt}=ui
const related=ref<ProjectRecord[]>([]),invitedRole=ref<CatalogueRole|null>(null)
const project=ref<ProjectRecord|null>(null),records=ref<ProjectRecord[]>([]),catalogue=ref<CatalogueItem[]>([]),confirmations=ref<Confirmation[]>([]),readiness=ref<ProjectReadiness|null>(null),productions=ref<ProductionRecord[]>([]),sourceProduction=ref<ProductionRecord|null>(null),orders=ref<TradeRecord[]>([]),avatars=ref<Dependency[]>([]),consents=ref<Dependency[]>([]),assets=ref<string[]>([]),readAssets=ref<string[]>([])
const initializing=ref(true),pageLoading=ref(false),openId=ref(''),roleId=ref(''),inviteParty=ref(''),decision=ref(''),reason=ref(''),reconfirm=ref(false),conflicted=ref(false),now=ref(Date.now())
const create=reactive({title:'',purpose:'',territory:'',language:'',until:''}),role=reactive({title:'',capacity:'',pricing:'',amount:'',terms:''}),candidate=reactive({avatar:'',consent:'',amount:'',note:'',response:''}),plan=reactive({production:'',terms:''}),edition=reactive({final:'',note:''}),release=reactive({channel:'',prior:'',note:''}),channel=reactive({name:'',reference:'',requirements:''}),external=reactive({outcome:'',reference:'',time:'',note:''})
const rights=ref<RightDraft[]>(Object.keys(layers).map(layer=>({layer:layer as keyof typeof layers,holder:'',asset:'',purpose:'',territory:'',until:'',terms:''}))),signers=ref<SignerDraft[]>([{party:'',responsibility:'',after:''}]),funding=ref<FundingDraft[]>([]),checks=reactive<Record<string,boolean>>({})
const p=computed(()=>project.value?.kind==='PROJECT'?project.value:null),isOwner=computed(()=>!!session.selected&&session.selected.membership.current_status==='ACTIVE'&&session.selected.membership.roles.includes('OWNER')&&!['CLOSED','SUSPENDED'].includes(session.selected.party.current_status)),isSponsor=computed(()=>isOwner.value&&p.value?.owner_party_id===session.selectedId),locked=computed(()=>busy.value||!!pending.value||now.value<retryAt.value||conflicted.value&&!reconfirm.value)
const ownCandidate=computed(()=>detail.value?.kind==='CANDIDATE'&&isOwner.value&&detail.value.owner_party_id===session.selectedId),roles=computed(()=>records.value.filter(x=>x.kind==='ROLE')),candidates=computed(()=>records.value.filter(x=>x.kind==='CANDIDATE')),plans=computed(()=>records.value.filter(x=>x.kind==='PLAN')),editions=computed(()=>records.value.filter(x=>x.kind==='EDITION')),releases=computed(()=>records.value.filter(x=>x.kind==='RELEASE'))
const publicRole=computed(()=>mode.value==='respond'?invitedRole.value:catalogue.value.flatMap(x=>x.roles).find(x=>x.id===recordId.value)),publicProject=computed(()=>catalogue.value.find(x=>x.roles.some(r=>r.id===recordId.value))),selectedRole=computed(()=>roles.value.find(x=>x.id===roleId.value)),gate=computed(()=>detail.value?confirmationGate(detail.value,session.selectedId,confirmations.value):{can:false,message:'尚未读取本版确认记录。'})
const reviewKind=computed(()=>({plans:'PLAN',editions:'EDITION',channels:'CHANNEL',releases:'RELEASE','external-events':'EXTERNAL_EVENT'}[section.value] as keyof typeof reviewFields)),currentFields=computed(()=>detail.value&&Object.hasOwn(reviewFields,detail.value.kind)?reviewFields[detail.value.kind as keyof typeof reviewFields]:[])
const gallery=computed(()=>reviewer.value?section.value==='plans'?'WEB-24-02-v2':section.value==='editions'?'WEB-25-02-v2':'WEB-26-02-v2':({list:'WEB-23-01-v2',new:'WEB-23-02',roles:'WEB-23-02',catalogue:'WEB-23-01-v2',apply:'WEB-23-04-v3',select:'WEB-23-03-v2',respond:'WEB-23-04-v3',plan:'WEB-24-01','confirm-plan':'WEB-24-03-v2',readiness:'WEB-24-04-v2',edition:'WEB-25-01','confirm-edition':'WEB-25-03-v2',release:'WEB-25-04-v2',channel:'WEB-26-01','channel-detail':'WEB-26-01',external:'WEB-26-03-v2'} as Record<string,string>)[mode.value]||'WEB-23-01-v2')
const title=computed(()=>reviewer.value?section.value==='plans'?'项目方案独立核验':section.value==='editions'?'成片与材料独立核验':'发行事项独立审核':String(route.meta.title))
const until=(value:string)=>value?new Date(value).toISOString():''
const ids=(value:string)=>value.trim()?value.trim().split(/[\s,，]+/):[]
const validDate=(value:string)=>!!value&&Number.isFinite(Date.parse(value))
const createValid=computed(()=>isOwner.value&&create.title.trim()&&['PUBLIC_SHARE','RELEASE'].includes(create.purpose)&&/^[A-Z]{2}$/.test(create.territory)&&/^[a-z]{2}$/.test(create.language)&&validDate(create.until)&&Date.parse(create.until)>Date.now())
const roleValid=computed(()=>isSponsor.value&&p.value?.current_status==='PREPARING'&&!p.value.data.current_plan_id&&role.title.trim()&&/^\d+$/.test(role.capacity)&&Number(role.capacity)>=1&&Number(role.capacity)<=100&&['FIXED','QUOTE'].includes(role.pricing)&&(role.pricing==='QUOTE'||parseMoney(role.amount)!==null)&&role.terms.trim())
const candidateValid=computed(()=>isOwner.value&&validSupplyId(candidate.avatar)&&validSupplyId(candidate.consent)&&parseMoney(candidate.amount)!==null&&candidate.note.trim()&&(publicRole.value?.pricing!=='FIXED'||parseMoney(candidate.amount)===publicRole.value.amount_minor))
const planValid=computed(()=>isSponsor.value&&validSupplyId(plan.production)&&plan.terms.trim()&&rights.value.every(r=>validSupplyId(r.holder)&&validSupplyId(r.asset)&&r.purpose===p.value?.data.scope.purpose&&r.territory===p.value?.data.scope.territory&&validDate(r.until)&&until(r.until)>=p.value!.data.scope.valid_until&&r.terms.trim())&&signers.value.length>0&&signers.value.every(s=>validSupplyId(s.party)&&s.responsibility.trim()&&ids(s.after).every(validSupplyId))&&new Set(signers.value.map(s=>s.party)).size===signers.value.length&&funding.value.every(f=>[f.candidate,f.order].every(validSupplyId)&&f.line.trim()))
const reviewValid=computed(()=>reviewer.value&&detail.value&&['IN_REVIEW','INTERNAL_PENDING'].includes(detail.value.current_status)&&detail.value.created_by!==session.account?.id&&decision.value&&reason.value.trim()&&(decision.value!=='APPROVED'||currentFields.value.every(k=>checks[k])&&evidenceIds(detail.value).every(id=>readAssets.value.includes(id))))
const confirmValid=computed(()=>isOwner.value&&gate.value.can&&decision.value&&reason.value.trim())
const finalOptions=computed(()=>sourceProduction.value?.kind==='PROJECT'&&sourceProduction.value.data.current.FINAL===sourceProduction.value.data.accepted.FINAL&&sourceProduction.value.data.current.FINAL?[sourceProduction.value.data.current.FINAL]:[])
let disposed=false,pageTicket=0,timer=0
function resetDecision(){decision.value=reason.value='';readAssets.value=[];Object.keys(checks).forEach(k=>delete checks[k]);ui.revoke()}
function reset(){related.value=[];invitedRole.value=null;pageTicket++;pageLoading.value=false;project.value=null;records.value=[];catalogue.value=[];confirmations.value=[];readiness.value=null;productions.value=[];sourceProduction.value=null;orders.value=[];avatars.value=[];consents.value=[];assets.value=[];openId.value=roleId.value=inviteParty.value='';for(const form of [create,role,candidate,plan,edition,release,channel,external])Object.keys(form).forEach(k=>(form as Record<string,string>)[k]='');rights.value=Object.keys(layers).map(layer=>({layer:layer as keyof typeof layers,holder:'',asset:'',purpose:'',territory:'',until:'',terms:''}));signers.value=[{party:'',responsibility:'',after:''}];funding.value=[];conflicted.value=reconfirm.value=false;resetDecision()}
watch(securityRevision,reset,{flush:'sync'})
watch(conflictRevision,()=>{resetDecision();candidate.response='';edition.final='';external.outcome='';conflicted.value=true;reconfirm.value=false;confirmations.value=[];readiness.value=null;if(detail.value?.kind==='PROJECT')project.value=detail.value;if(detail.value)records.value=records.value.map(r=>r.id===detail.value!.id?detail.value!:r);void loadPage()},{flush:'sync'})
watch(()=>[route.fullPath,session.selectedId,session.revision],()=>{if(!initializing.value)void loadPage()})
watch(()=>plan.production,()=>{sourceProduction.value=null;edition.final=''})
async function loadCatalogue(){await ui.read('catalogue',(i,s)=>projectCatalogue(i,s),r=>catalogue.value=r.items)}
async function loadConfirmations(id:string){confirmations.value=[];await ui.read('confirmations',(i,s)=>projectConfirmations(i,id,s),r=>confirmations.value=r.items)}
async function loadCollections(id:string,kinds:ChildKind[]=['ROLE','CANDIDATE','PLAN','EDITION','RELEASE','EXTERNAL_EVENT']){const ticket=pageTicket;const all:ProjectRecord[]=[];for(const kind of kinds){const r=await ui.loadAll(id,kind);if(disposed||ticket!==pageTicket||!r)return;all.push(...r)}records.value=all}
async function loadDependencies(){const ticket=pageTicket;await ui.read('productions',async(i,s)=>{const result:ProductionRecord[]=[];let cursor:string|null=null;const seen=new Set<string>();do{const page=await listProduction(i,undefined,undefined,cursor,s);result.push(...page.items);cursor=page.next_cursor;if(cursor&&seen.has(cursor))throw new ApiError({status:200,code:'UNEXPECTED_RESPONSE_SHAPE',message:'制作项目分页未更新。'});if(cursor)seen.add(cursor)}while(cursor);return result.filter(p=>p.kind==='PROJECT'&&p.data.buyer_party_id===i.partyId)},r=>productions.value=r);if(ticket!==pageTicket)return;await ui.read('role-orders',async(i,s)=>{const result:TradeRecord[]=[];let cursor:string|null=null;const seen=new Set<string>();do{const page=await listTrade(i,'ORDER',cursor,s);result.push(...page.items);cursor=page.next_cursor;if(cursor&&seen.has(cursor))throw new ApiError({status:200,code:'UNEXPECTED_RESPONSE_SHAPE',message:'角色订单分页未更新。'});if(cursor)seen.add(cursor)}while(cursor);return result.filter(o=>o.kind==='ORDER'&&o.buyer_party_id===i.partyId&&o.current_status==='PAID'&&o.data.quote.lines.some(l=>l.line_kind==='OTHER'))},r=>orders.value=r)}
async function loadAvatarOptions(){await ui.read('avatars',(i,s)=>listDependencies(i,'AVATAR',s),r=>avatars.value=r);await ui.read('consents',(i,s)=>listDependencies(i,'CONSENT',s),r=>consents.value=r)}
async function checkProduction(id=plan.production){if(!validSupplyId(id))return;sourceProduction.value=null;await ui.read('source-production',(i,s)=>getProduction(i,id,'PROJECT',s),r=>sourceProduction.value=r)}
async function loadRelated(r:ProjectRecord){related.value=[];const queue=r.kind==='EDITION'?[r.data.plan_id]:r.kind==='RELEASE'?[r.data.edition_id,r.data.channel_id]:r.kind==='EXTERNAL_EVENT'?[r.data.release_id]:[];const ticket=pageTicket,seen=new Set<string>();while(queue.length){const id=queue.shift()!;if(seen.has(id))continue;seen.add(id);const record=await ui.read('related-'+id,(i,s)=>getProject(i,id,undefined,s));if(!record||ticket!==pageTicket||disposed)return;related.value.push(record);if(record.kind==='EDITION')queue.push(record.data.plan_id);if(record.kind==='RELEASE')queue.push(record.data.edition_id,record.data.channel_id)}}
async function loadPage(){const ticket=++pageTicket,current=()=>!disposed&&ticket===pageTicket;pageLoading.value=true;related.value=[];invitedRole.value=null;resetDecision();try{
 if(mode.value==='catalogue'||mode.value==='apply'||mode.value==='release'||mode.value==='channel-detail'&&!recordId.value){await loadCatalogue();if(!current())return}
 if(mode.value==='new'||mode.value==='channel')return
 if(mode.value==='apply'){if(!publicRole.value){error.value=new ApiError({status:404,code:'PROJECT_NOT_FOUND',message:'公开目录中没有此开放角色，请重新读取目录。'});return}await loadAvatarOptions();return}
 if(!recordId.value){if(!['catalogue','channel-detail'].includes(mode.value)){await ui.loadList();if(!current())return;if(mode.value==='plans'||mode.value==='releases'){const all:ProjectRecord[]=[];for(const r of rows.value){const child=await ui.loadAll(r.id,mode.value==='plans'?'PLAN':'RELEASE');if(!current()||!child)return;all.push(...child)}records.value=all}if(reviewer.value&&section.value!=='channels'){const all:ProjectRecord[]=[];for(const r of rows.value){const child=await ui.loadAll(r.id,reviewKind.value as ChildKind);if(!current()||!child)return;all.push(...child)}records.value=all}}return}
 if(!validSupplyId(recordId.value)){error.value=new ApiError({status:400,code:'CLIENT_RECORD_INVALID',message:'请填写完整的真实记录编号。'});return}
 const expected:ProjectKind|undefined=reviewer.value?reviewKind.value:['list','roles','plan','readiness','edition','release'].includes(mode.value)?'PROJECT':mode.value==='respond'||mode.value==='select'?'CANDIDATE':mode.value==='confirm-plan'?'PLAN':mode.value==='confirm-edition'?'EDITION':mode.value==='external'?'RELEASE':mode.value==='channel-detail'?'CHANNEL':undefined
 const r=await ui.loadRecord(recordId.value,expected);if(!current()||!r)return
 if(r.kind==='PROJECT')project.value=r;else if(r.project_id)await ui.read('project',(i,s)=>getProject(i,r.project_id!,'PROJECT',s),v=>project.value=v)
 if(!current())return
 if(r.kind==='PLAN'||r.kind==='EDITION'){await loadConfirmations(r.id);if(!current())return}
 if(reviewer.value){await loadRelated(r);return}
 if(mode.value==='respond'){if(r.kind==='CANDIDATE'&&r.current_status==='INVITED'){await ui.read('invited-role',(i,s)=>getProject(i,r.data.role_id,'ROLE',s),role=>{if(role.kind==='ROLE')invitedRole.value={id:role.id,object_version:role.object_version,...role.data}});if(!current())return;await loadAvatarOptions()}return}
 if(mode.value==='confirm-plan'||mode.value==='confirm-edition'||mode.value==='external'||mode.value==='record'||mode.value==='channel-detail'||mode.value==='select')return
 if(p.value){await loadCollections(p.value.id);if(!current())return}
 if(mode.value==='plan'){await loadDependencies();return}
 if(mode.value==='readiness'){await refreshReadiness();return}
 if(mode.value==='edition'&&p.value?.data.current_plan_id){const planRecord=records.value.find(x=>x.id===p.value!.data.current_plan_id);if(planRecord?.kind==='PLAN')await checkProduction(planRecord.data.production_project_id)}
 }finally{if(current())pageLoading.value=false}}
function leave(){if(ui.canNavigate())return true;notice.value='原操作结果尚未确认，请先核对并保留原请求重试。';return false}
onBeforeRouteLeave(leave);onBeforeRouteUpdate(leave)
function beforeUnload(e:BeforeUnloadEvent){if(!ui.canNavigate()){e.preventDefault();e.returnValue=''}}
onMounted(async()=>{timer=window.setInterval(()=>now.value=Date.now(),1000);window.addEventListener('beforeunload',beforeUnload);const c=session.capture();try{await Promise.all([session.loadAccount(),session.loadParties()]);if(!disposed&&session.current(c)){initializing.value=false;await loadPage()}}catch(e){if(!disposed&&session.current(c)){ui.clear();error.value=asApiError(e)}}finally{if(!disposed)initializing.value=false}})
onUnmounted(()=>{disposed=true;pageTicket++;window.clearInterval(timer);window.removeEventListener('beforeunload',beforeUnload)})
function openRecord(){if(!validSupplyId(openId.value)||locked.value)return;void router.push(reviewer.value?`/projects/reviews/${section.value}/${openId.value}`:mode.value==='channel-detail'?`/projects/channels/${openId.value}`:`/projects/records/${openId.value}`)}
async function upload(file:File,media:MediaType){if(locked.value||!isOwner.value)return;const path=`/supply/assets?${new URLSearchParams({purpose:'RIGHTS_EVIDENCE',media_type:media})}`;await ui.write({path,resultKind:'ASSET',label:'上传项目私有证明',supply:{path,blob:file,mediaType:media,purpose:'RIGHTS_EVIDENCE',kind:'ASSET',label:'上传项目私有证明'}},r=>{assets.value=[...assets.value,(r as SupplyAsset).id]})}
function removeAsset(id:string){assets.value=assets.value.filter(x=>x!==id)}
async function createProject(){if(!createValid.value||locked.value)return;await ui.write({path:'/projects/projects',resultKind:'PROJECT',label:'创建项目',body:{title:create.title.trim(),scope:{purpose:create.purpose,territory:create.territory,language:create.language,valid_until:until(create.until)}}},r=>void router.push(`/projects/projects/${r.id}/roles`))}
async function addRole(){if(!roleValid.value||!p.value||locked.value)return;const r=p.value;await ui.write({path:`/projects/projects/${r.id}/roles`,targetId:r.id,projectId:r.id,version:r.object_version,resultKind:'ROLE',label:'添加角色',body:{title:role.title.trim(),capacity:Number(role.capacity),pricing:role.pricing,amount_minor:role.pricing==='QUOTE'?null:parseMoney(role.amount),terms:role.terms.trim()}},()=>{Object.keys(role).forEach(k=>role[k as keyof typeof role]='');void loadPage()})}
async function invite(){const r=selectedRole.value;if(!r||locked.value||!isSponsor.value||!validSupplyId(inviteParty.value))return;await ui.write({path:`/projects/roles/${r.id}/invitations`,targetId:r.id,projectId:r.project_id!,version:r.object_version,resultKind:'CANDIDATE',label:'发送定向邀请',body:{invitee_party_id:inviteParty.value}},()=>{inviteParty.value='';void loadPage()})}
async function apply(){const r=publicRole.value;if(!r||locked.value||!candidateValid.value)return;await ui.write({path:`/projects/roles/${r.id}/applications`,targetId:r.id,projectId:publicProject.value!.id,version:r.object_version,resultKind:'CANDIDATE',catalogueRecovery:true,label:'申请开放角色',body:{avatar_id:candidate.avatar,consent_id:candidate.consent,amount_minor:parseMoney(candidate.amount),note:candidate.note.trim()}},r=>void router.push(`/projects/candidates/${r.id}/respond`))}
async function respond(){const r=detail.value;if(r?.kind!=='CANDIDATE'||!ownCandidate.value||r.current_status!=='INVITED'||locked.value||!candidate.response||!candidate.note.trim()||candidate.response==='ACCEPT'&&!candidateValid.value)return;const accept=candidate.response==='ACCEPT';await ui.write({path:`/projects/candidates/${r.id}/responses`,targetId:r.id,projectId:r.project_id!,version:r.object_version,resultKind:'CANDIDATE',label:'回应当前邀请',body:{decision:candidate.response,avatar_id:accept?candidate.avatar:null,consent_id:accept?candidate.consent:null,amount_minor:accept?parseMoney(candidate.amount):null,note:candidate.note.trim()}},()=>void loadPage())}
async function decide(){const r=detail.value;if(r?.kind!=='CANDIDATE'||locked.value||!reason.value.trim()||!decision.value)return;if(['SELECT','REJECT'].includes(decision.value)?!isSponsor.value:!ownCandidate.value)return;await ui.write({path:`/projects/candidates/${r.id}/decisions`,targetId:r.id,projectId:r.project_id!,version:r.object_version,resultKind:'CANDIDATE',label:'保存候选决定',body:{decision:decision.value,content_sha256:r.content_sha256,reason:reason.value.trim()}},()=>void loadPage())}
async function submitPlan(){if(!planValid.value||!p.value||locked.value)return;const r=p.value;await ui.write({path:`/projects/projects/${r.id}/plans`,targetId:r.id,projectId:r.id,version:r.object_version,resultKind:'PLAN',label:'提交项目方案',body:{production_project_id:plan.production,rights:rights.value.map(x=>({layer:x.layer,holder_party_id:x.holder,evidence_asset_id:x.asset,purpose:x.purpose,territory:x.territory,valid_until:until(x.until),terms:x.terms.trim()})),confirmers:signers.value.map(x=>({party_id:x.party,responsibility:x.responsibility.trim(),after_party_ids:ids(x.after)})),funding:funding.value.map(x=>({candidate_id:x.candidate,order_id:x.order,line_id:x.line})),terms:plan.terms.trim()}},r=>void router.push(`/projects/plans/${r.id}/confirm`))}
async function confirm(){const r=detail.value;if(!r||!confirmValid.value||locked.value)return;await ui.write({path:`/projects/records/${r.id}/confirmations`,targetId:r.id,projectId:r.project_id!,version:r.object_version,resultKind:r.kind,label:'提交本方准确版本确认',confirmation:true,body:{content_sha256:r.content_sha256,decision:decision.value,reason:reason.value.trim()}},()=>void loadPage())}
async function refreshReadiness(){if(!p.value)return;readiness.value=null;await ui.read('readiness',(i,s)=>projectReadiness(i,p.value!.id,s),r=>readiness.value=r)}
async function start(){if(!p.value||!isSponsor.value||readiness.value?.current_status!=='AVAILABLE'||locked.value)return;const r=p.value;await ui.write({path:`/projects/projects/${r.id}/start`,targetId:r.id,version:r.object_version,resultKind:'PROJECT',label:'启动项目',body:{}},()=>void loadPage())}
async function cancel(){if(!p.value||!isSponsor.value||!reason.value.trim()||locked.value)return;const r=p.value;await ui.write({path:`/projects/projects/${r.id}/cancellation`,targetId:r.id,version:r.object_version,resultKind:'PROJECT',label:'取消项目',body:{reason:reason.value.trim()}},()=>void loadPage())}
async function submitEdition(){if(!p.value||!isSponsor.value||locked.value||!finalOptions.value.includes(edition.final)||!assets.value.length||assets.value.length>30||!edition.note.trim())return;const r=p.value;await ui.write({path:`/projects/projects/${r.id}/editions`,targetId:r.id,projectId:r.id,version:r.object_version,resultKind:'EDITION',label:'提交成片材料新版本',body:{final_version_id:edition.final,material_asset_ids:[...assets.value],note:edition.note.trim()}},r=>void router.push(`/projects/editions/${r.id}/confirm`))}
async function submitRelease(){if(!p.value||!isSponsor.value||locked.value||!catalogue.value.some(c=>c.kind==='CHANNEL'&&c.id===release.channel)||release.prior&&!releases.value.some(r=>r.id===release.prior)||!assets.value.length||assets.value.length>30||!release.note.trim())return;const r=p.value;await ui.write({path:`/projects/projects/${r.id}/releases`,targetId:r.id,projectId:r.id,version:r.object_version,resultKind:'RELEASE',label:'提交新发行申请',body:{channel_id:release.channel,prior_release_id:release.prior||null,material_asset_ids:[...assets.value],note:release.note.trim()}},r=>void router.push(`/projects/releases/${r.id}/external`))}
async function registerChannel(){if(locked.value||!isOwner.value||!channel.name.trim()||!channel.reference.trim()||!channel.requirements.trim()||assets.value.length!==1)return;await ui.write({path:'/projects/channels',resultKind:'CHANNEL',label:'登记渠道档案待审核',body:{name:channel.name.trim(),channel_reference:channel.reference.trim(),submission_requirements:channel.requirements.trim(),evidence_asset_id:assets.value[0]}},r=>void router.push(`/projects/channels/${r.id}`))}
async function reportExternal(){const r=detail.value;if(r?.kind!=='RELEASE'||!isSponsor.value||locked.value||!external.outcome||!external.reference.trim()||!validDate(external.time)||Date.parse(external.time)>Date.now()||!external.note.trim()||assets.value.length!==1)return;await ui.write({path:`/projects/releases/${r.id}/external-events`,targetId:r.id,projectId:r.project_id!,version:r.object_version,resultKind:'EXTERNAL_EVENT',label:'登记真实外部报告待核实',body:{outcome:external.outcome,external_reference:external.reference.trim(),occurred_at:until(external.time),evidence_asset_id:assets.value[0],note:external.note.trim()}},r=>void router.push(`/projects/records/${r.id}`))}
async function readEvidence(id:string){const r=detail.value;if(!r||locked.value||!evidenceIds(r).includes(id))return;await ui.read('evidence',(i,s)=>projectEvidence(i,r.id,id,s),blob=>{const url=ui.objectUrl(blob),a=document.createElement('a');a.href=url;a.download=`项目私有证明-${id}.bin`;a.click();readAssets.value=[...new Set([...readAssets.value,id])];notice.value='已通过当前权限接口读取私有材料。请实际核对内容后填写结论。'})}
async function review(){const r=detail.value;if(!r||!reviewValid.value||locked.value)return;await ui.write({path:`/projects/records/${r.id}/reviews`,targetId:r.id,projectId:r.project_id||undefined,version:r.object_version,resultKind:r.kind,label:'提交独立核验',body:{decision:decision.value,reason:reason.value.trim(),verification:Object.fromEntries(currentFields.value.map(k=>[k,!!checks[k]]))}},()=>void loadPage())}
</script>
<template>
<div class="supply-workspace trade-workspace projects-workspace" :data-gallery="gallery"><header class="supply-header"><RouterLink to="/workspace" class="supply-brand">晶晶日上</RouterLink><span>运营与合作方工作台</span><div class="account-actions"><span class="account-name">{{session.account?.display_name||'当前账号'}}</span><button @click="session.logout().then(()=>router.push('/login'))">退出</button></div></header><div class="supply-layout"><aside class="supply-sidebar"><WorkspaceNav/><div class="supply-identity"><template v-if="reviewer"><p>独立项目核验</p><p class="muted">以当前账号办理；PROJECT_REVIEW 由服务器核验，参与方不能审核自己的业务。</p></template><template v-else><label for="project-party">当前办理身份</label><select id="project-party" :value="session.selectedId" :disabled="locked" @change="session.selectParty(($event.target as HTMLSelectElement).value)"><option v-for="access in session.parties" :key="access.party.id" :value="access.party.id">{{access.party.display_name}}</option></select><p class="muted">{{isOwner?'有效负责人身份':'当前不是负责人，业务写入不可用'}}</p></template></div></aside><main class="supply-main">
<div class="supply-heading"><div><h1>{{title}}</h1><p>{{reviewer?'实际读取材料，独立核验本次项目或发行事项。':'项目报名、本人入选、方案会签、成片与真实发行分别保存。'}}</p></div><button class="outline" :disabled="locked||pageLoading" @click="loadPage">刷新当前记录</button></div>
<div class="loaded-tabs"><template v-if="reviewer"><RouterLink v-for="(label,key) in {plans:'项目方案',editions:'成片材料',channels:'渠道档案',releases:'发行申请','external-events':'外部结果'}" :key="key" :to="`/projects/reviews/${key}`" :class="{active:section===key}">{{label}}</RouterLink></template><template v-else><RouterLink to="/projects/projects">参与项目</RouterLink><RouterLink to="/projects/catalogue">公开角色摘要</RouterLink><RouterLink to="/projects/plans">项目会签</RouterLink><RouterLink to="/projects/releases">项目发行</RouterLink><RouterLink to="/projects/channels">渠道摘要与档案</RouterLink></template></div>
<ApiErrorAlert :error="error"/><p v-if="notice" class="supply-notice" role="status">{{notice}}</p>
<div v-if="pending" class="supply-warning"><p>{{pending.command.label}}结果尚未确认。保留原请求、原内容、文件和版本。{{pending.resultId?`已知结果：${pending.resultId}`:''}}</p><details><summary>原操作编号</summary><p class="identifier">{{pending.key}}</p></details><div class="supply-actions"><button class="outline" :disabled="busy||now<retryAt" @click="ui.checkPending()" data-testid="project-recovery-check">核对原操作</button><button v-if="!pending.resultId&&pending.state!=='blocked'" class="primary" :disabled="busy||!pending.checked||now<retryAt" @click="ui.retry()" data-testid="project-recovery-retry">使用原请求重试</button><button v-if="pending.state==='blocked'" class="outline" :disabled="busy||!pending.checked" @click="ui.endBlocked()">结束已拒绝上传的核对</button></div></div>
<div v-if="conflicted" class="supply-warning"><label class="trade-check"><input v-model="reconfirm" type="checkbox" data-testid="project-reconfirm">我已核对最新记录，将重新填写并作出决定。</label></div>
<p v-if="initializing||pageLoading" class="supply-empty" role="status">正在读取身份与项目记录…</p>
<div v-else :key="route.fullPath+securityRevision">
<section v-if="!recordId&&mode!=='new'&&mode!=='channel'" class="supply-card"><div class="supply-section-heading"><h2>{{reviewer?'获准核验的项目':mode==='catalogue'?'开放角色摘要':mode==='channel-detail'?'已核验渠道摘要':'我参与的项目'}}</h2><RouterLink v-if="!reviewer" to="/projects/projects/new" class="button-link primary">建立项目与角色</RouterLink></div>
<div v-if="rows.length" class="table-wrap"><table><thead><tr><th>项目标题</th><th>状态</th><th>用途</th><th>操作</th></tr></thead><tbody><tr v-for="r in rows" :key="r.id"><template v-if="r.kind==='PROJECT'"><td>{{r.data.title}}</td><td>{{projectStatus(r)}}</td><td>{{r.data.scope.purpose==='RELEASE'?'发行':'公开分享'}}</td><td><RouterLink :to="`/projects/projects/${r.id}`" class="table-link">打开项目记录</RouterLink></td></template></tr></tbody></table></div><p v-if="!rows.length&&!['catalogue','channel-detail'].includes(mode)" class="supply-empty">尚无已读取的可见项目。</p><button v-if="nextCursor" class="outline" :disabled="locked" @click="ui.loadList(undefined,undefined,true)">继续加载项目</button>
<div v-if="mode==='catalogue'||mode==='channel-detail'"><article v-for="item in catalogue.filter(x=>mode==='catalogue'?x.kind==='PROJECT':x.kind==='CHANNEL')" :key="item.id" class="project-catalogue-row"><h3>{{item.title}}</h3><p v-if="item.scope">{{item.scope.purpose==='RELEASE'?'发行':'公开分享'}} · {{item.scope.territory}} / {{item.scope.language}} · {{item.scope.valid_until}}</p><p v-else>外部参考：{{item.channel_reference}}</p><div v-if="item.roles.length" class="table-wrap"><table><thead><tr><th>角色</th><th>人数</th><th>价格方式</th><th>原条款</th><th>操作</th></tr></thead><tbody><tr v-for="r in item.roles" :key="r.id"><td>{{r.title}}</td><td>{{r.capacity}}</td><td>{{r.pricing==='QUOTE'?'本人明确报价':money(r.amount_minor!)}}</td><td class="long-text">{{r.terms}}</td><td><RouterLink :to="`/projects/roles/${r.id}/apply`" class="table-link">向开放角色申请</RouterLink></td></tr></tbody></table></div><RouterLink v-if="item.kind==='CHANNEL'" :to="`/projects/channels/${item.id}`" class="table-link">读取获准渠道档案</RouterLink></article><p class="muted">目录只给开放角色及渠道摘要，不包含报名人资料、原始证据或未审核渠道。完整记录仍按当前身份授权。</p></div>
<div v-if="records.length" class="table-wrap"><table><thead><tr><th>事项</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="r in records" :key="r.id"><td>{{kindLabels[r.kind]}} · {{r.id.slice(0,8)}}</td><td>{{projectStatus(r)}}</td><td><RouterLink :to="reviewer?`/projects/reviews/${section}/${r.id}`:r.kind==='PLAN'?`/projects/plans/${r.id}/confirm`:`/projects/releases/${r.id}/external`" class="table-link">{{reviewer?'打开独立核验':r.kind==='PLAN'?'核对准确版本会签':'查看发行记录'}}</RouterLink></td></tr></tbody></table></div>
</section>
<section v-if="reviewer&&!recordId||mode==='channel-detail'&&!recordId||mode==='record'&&!recordId" class="supply-card"><h2>读取已知真实记录</h2><form @submit.prevent="openRecord"><label>记录编号 *<input v-model="openId" data-testid="project-open-id" required placeholder="当事方提供的完整UUID"></label><button class="outline" :disabled="locked||!validSupplyId(openId)" data-testid="project-open-submit">读取指定记录</button></form><p v-if="section==='channels'" class="muted">没有待审渠道全局目录，请使用实际登记后的记录编号。审核权限由服务器再次核验。</p></section>
<form v-if="mode==='new'" @submit.prevent="createProject"><fieldset :disabled="locked||!isOwner"><section class="supply-card"><h2>1　项目标题与使用范围</h2><label>项目标题 *<input v-model="create.title" data-testid="project-title" required maxlength="200" placeholder="待填写"></label><div class="trade-fields two"><label>项目用途 *<select v-model="create.purpose" data-testid="project-purpose" required><option value="">待明确选择</option><option value="PUBLIC_SHARE">公开分享</option><option value="RELEASE">发行</option></select></label><label>地域 *<input v-model="create.territory" data-testid="project-territory" required maxlength="2" placeholder="两位大写代码，如CN"></label><label>语言 *<input v-model="create.language" data-testid="project-language" required maxlength="2" placeholder="两位小写代码，如zh"></label><label>有效至 *<input v-model="create.until" type="datetime-local" data-testid="project-until" required></label></div><button class="primary" :disabled="locked||!createValid" data-testid="project-create">创建项目</button><p class="muted">创建后添加角色和定向邀请。独家许可不自动包含发行权。</p></section></fieldset></form>
<div v-if="p&&!reviewer" class="loaded-tabs project-context-tabs"><RouterLink :to="`/projects/projects/${p.id}`">项目与角色</RouterLink><RouterLink :to="`/projects/projects/${p.id}/roles`">角色与邀请</RouterLink><RouterLink :to="`/projects/projects/${p.id}/plans/new`">新方案</RouterLink><RouterLink :to="`/projects/projects/${p.id}/readiness`">开工条件</RouterLink><RouterLink :to="`/projects/projects/${p.id}/editions/new`">成片材料</RouterLink><RouterLink :to="`/projects/projects/${p.id}/releases/new`">新发行申请</RouterLink></div>
<ProjectRecordPanel v-if="p&&['list','roles','plan','readiness','edition','release'].includes(mode)" :record="p"/>
<template v-if="p&&mode==='list'"><section class="supply-card"><h2>角色与候选</h2><div class="table-wrap"><table><thead><tr><th>角色</th><th>名额</th><th>报价</th><th>条款</th></tr></thead><tbody><tr v-for="r in roles" :key="r.id"><template v-if="r.kind==='ROLE'"><td>{{r.data.title}}</td><td>{{r.data.capacity}}</td><td>{{r.data.amount_minor===null?'明确报名报价':money(r.data.amount_minor)}}</td><td class="long-text">{{r.data.terms}}</td></template></tr></tbody></table></div><article v-for="c in candidates" :key="c.id" class="trade-row"><p>{{c.owner_party_id.slice(0,8)}} · {{projectStatus(c)}}</p><RouterLink :to="`/projects/candidates/${c.id}/${isSponsor?'select':'respond'}`" class="table-link">{{isSponsor?'筛选当前候选':'回应与本人确认'}}</RouterLink></article><p v-if="!candidates.length" class="supply-empty">没有当前身份获准读取的候选记录。</p></section>
<section class="supply-card"><h2>方案、成片与发行历史</h2><article v-for="r in records.filter(r=>['PLAN','EDITION','RELEASE','EXTERNAL_EVENT'].includes(r.kind))" :key="r.id" class="trade-row"><p>{{kindLabels[r.kind]}} · {{projectStatus(r)}}</p><RouterLink :to="r.kind==='PLAN'?`/projects/plans/${r.id}/confirm`:r.kind==='EDITION'?`/projects/editions/${r.id}/confirm`:r.kind==='RELEASE'?`/projects/releases/${r.id}/external`:`/projects/records/${r.id}`" class="table-link">核对本记录</RouterLink></article></section><details v-if="isSponsor" class="supply-card"><summary>取消项目</summary><p class="muted">取消只保存项目状态，不代表已退款、撤回许可或完成外部下架。</p><label>实际取消理由 *<textarea v-model="reason" data-testid="project-cancel-reason" required></textarea></label><button class="outline" :disabled="locked||!reason.trim()||p.current_status==='CANCELLED'" @click="cancel" data-testid="project-cancel">取消本项目</button></details></template>
<template v-if="mode==='roles'&&p"><form @submit.prevent="addRole"><fieldset :disabled="locked||!isSponsor"><section class="supply-card"><h2>2　指定项目角色需求</h2><div class="trade-fields two"><label>角色名称 *<input v-model="role.title" data-testid="role-title" required maxlength="200"></label><label>人数 *<input v-model="role.capacity" data-testid="role-capacity" required inputmode="numeric" placeholder="待明确填写"></label><label>报价方式 *<select v-model="role.pricing" data-testid="role-pricing" required><option value="">待选择</option><option value="FIXED">明确固定价</option><option value="QUOTE">报名时明确报价</option></select></label><label v-if="role.pricing==='FIXED'">固定金额（元） *<input v-model="role.amount" data-testid="role-amount" required inputmode="decimal" placeholder="明确零元也须填写"></label></div><label>角色条款 *<textarea v-model="role.terms" data-testid="role-terms" required maxlength="4000"></textarea></label><button class="primary" :disabled="locked||!roleValid" data-testid="role-create">添加角色</button><p class="muted">方案建立后不再添加角色；报价模式金额提交 null，不用零元代替未知价格。</p></section></fieldset></form>
<section class="supply-card"><h2>3　定向邀请</h2><form @submit.prevent="invite"><fieldset :disabled="locked||!isSponsor||p.current_status!=='PREPARING'"><div class="trade-fields two"><label>实际招募角色 *<select v-model="roleId" data-testid="invite-role" required><option value="">待选择已建角色</option><option v-for="r in roles" :key="r.id" :value="r.id">{{r.kind==='ROLE'?r.data.title:''}} · {{r.id.slice(0,8)}}</option></select></label><label>受邀主体编号 *<input v-model="inviteParty" data-testid="invite-party" required placeholder="真实主体UUID，不是手机号"></label></div><button class="primary" :disabled="locked||!selectedRole||!validSupplyId(inviteParty)" data-testid="invite-submit">发送定向邀请</button></fieldset></form><p class="muted">没有全站主体搜索接口；邀请只创建待回应候选，对方回应后仍需筛选及本人最终确认。</p><article v-for="c in candidates" :key="c.id" class="trade-row"><p>{{c.owner_party_id.slice(0,8)}} · {{projectStatus(c)}}</p><RouterLink :to="`/projects/candidates/${c.id}/select`" class="table-link">筛选当前候选</RouterLink></article></section></template>
<template v-if="mode==='apply'||mode==='respond'||mode==='select'"><div class="project-columns"><div><ProjectRecordPanel v-if="detail?.kind==='CANDIDATE'" :record="detail"/><section v-if="publicRole" class="supply-card"><h2>角色需求与条款</h2><h3>{{publicRole.title}}</h3><p>{{publicRole.capacity}} 个名额 · {{publicRole.pricing==='QUOTE'?'报名时明确报价':money(publicRole.amount_minor!)}}</p><p class="long-text">{{publicRole.terms}}</p><p v-if="publicProject?.scope" class="muted">{{publicProject.scope.purpose}} · {{publicProject.scope.territory}} · {{publicProject.scope.valid_until}}</p></section>
<form v-if="mode==='apply'||mode==='respond'&&detail?.current_status==='INVITED'" @submit.prevent="mode==='apply'?apply():respond()"><fieldset :disabled="locked||!isOwner||mode==='respond'&&!ownCandidate"><section class="supply-card"><h2>数字人与本人同意</h2><div class="trade-fields two"><label>数字人编号 *<input v-model="candidate.avatar" list="project-avatars" data-testid="candidate-avatar" :required="candidate.response!=='DECLINE'"><datalist id="project-avatars"><option v-for="a in avatars" :key="a.id" :value="a.id">{{a.data.display_name}}</option></datalist></label><label>本人同意记录 *<input v-model="candidate.consent" list="project-consents" data-testid="candidate-consent" :required="candidate.response!=='DECLINE'"><datalist id="project-consents"><option v-for="c in consents" :key="c.id" :value="c.id">{{c.current_status}} · {{c.data.consent?.purposes.join('、')}}</option></datalist></label><label>明确金额（元） *<input v-model="candidate.amount" data-testid="candidate-amount" inputmode="decimal" :required="candidate.response!=='DECLINE'" placeholder="未知金额不填零"></label></div><label>本次说明 *<textarea v-model="candidate.note" data-testid="candidate-note" required maxlength="2000"></textarea></label><label v-if="mode==='respond'">邀请回应 *<select v-model="candidate.response" data-testid="candidate-response" required><option value="">待选择</option><option value="ACCEPT">接受邀请，提交本人报名资料</option><option value="DECLINE">谢绝本次邀请</option></select></label><button v-if="mode==='apply'" class="primary" :disabled="locked||!candidateValid||!publicRole" data-testid="candidate-apply">向开放角色申请</button><button v-else class="primary" :disabled="locked||!candidate.response||!candidate.note.trim()||candidate.response==='ACCEPT'&&!candidateValid" data-testid="candidate-respond">回应当前邀请</button></section></fieldset></form></div>
<section v-if="detail?.kind==='CANDIDATE'" class="supply-card project-action-panel"><h2>{{mode==='select'?'入选或拒绝决定':'入选后本人确认与退出'}}</h2><p class="muted">{{mode==='select'?'发起方筛选不等于本人确认入组。':'本人最终确认绑定当前候选金额、同意和原条款。'}}</p><form @submit.prevent="decide"><fieldset :disabled="locked||(mode==='select'?!isSponsor:!ownCandidate)"><label>当前候选决定 *<select v-model="decision" data-testid="candidate-decision" required><option value="">待选择</option><template v-if="mode==='select'"><option value="SELECT" :disabled="detail.current_status!=='APPLIED'">选中，等待本人确认</option><option value="REJECT" :disabled="detail.current_status!=='APPLIED'">拒绝</option></template><template v-else><option value="CONFIRM" :disabled="detail.current_status!=='SELECTED'">本人确认入选内容</option><option value="WITHDRAW" :disabled="!['INVITED','APPLIED','SELECTED','CONFIRMED'].includes(detail.current_status)">退出本角色</option></template></select></label><label>决定理由 *<textarea v-model="reason" data-testid="candidate-reason" required maxlength="2000"></textarea></label><button class="primary" :disabled="locked||!decision||!reason.trim()" data-testid="candidate-decide">{{mode==='select'?'提交筛选结果':'确认本人入选或退出'}}</button></fieldset></form></section></div></template>
<form v-if="mode==='plan'&&p" @submit.prevent="submitPlan"><fieldset :disabled="locked||!isSponsor"><ProjectPlanForm v-model:production="plan.production" v-model:terms="plan.terms" :rights="rights" :signers="signers" :funding="funding" :productions="productions" :orders="orders" :candidates="candidates" :assets="assets" :disabled="locked" @upload="upload" @remove="removeAsset" @check-production="checkProduction()" @add-signer="signers.push({party:'',responsibility:'',after:''})" @add-funding="funding.push({candidate:'',order:'',line:''})"/><section class="supply-card"><h2>提交新方案独立核验</h2><p class="muted">所有六层依据、确认职责与顺序须明确；新方案重新审核及会签，不继承旧决定。</p><button class="primary" :disabled="locked||!planValid" data-testid="plan-submit">提交方案审核</button></section></fieldset></form>
<template v-if="detail&&(mode==='confirm-plan'||mode==='confirm-edition')"><div class="project-columns"><ProjectRecordPanel :record="detail"/><section class="supply-card project-action-panel"><h2>本方责任与准确内容确认</h2><p v-if="detail.kind==='PLAN'||detail.kind==='EDITION'">{{detail.data.confirmers.find(x=>x.party_id===session.selectedId)?.responsibility||'当前身份不是本版指定确认方'}}</p><p class="supply-warning">{{gate.message}}</p><form @submit.prevent="confirm"><fieldset :disabled="locked||!gate.can||!isOwner"><label>本方决定 *<select v-model="decision" data-testid="project-confirm-decision" required><option value="">待选择</option><option value="APPROVED">批准本版内容</option><option value="REJECTED">拒绝本版内容</option></select></label><label>确认理由 *<textarea v-model="reason" data-testid="project-confirm-reason" required maxlength="2000"></textarea></label><button class="primary" :disabled="locked||!confirmValid" data-testid="project-confirm-submit">{{mode==='confirm-plan'?'提交本方确认':'提交本方成片确认'}}</button></fieldset></form><p class="muted">会签只保存本方对准确内容的决定，不等于平台电子签、付款或实际发行。</p></section></div><section class="supply-card"><h2>已读取的各方确认</h2><div class="table-wrap"><table><thead><tr><th>确认方</th><th>决定</th><th>理由</th><th>内容版本</th></tr></thead><tbody><tr v-for="c in confirmations" :key="c.party_id"><td>{{c.party_id.slice(0,8)}}</td><td>{{c.decision==='APPROVED'?'批准':'拒绝'}}</td><td class="long-text">{{c.reason}}</td><td>{{c.content_sha256===detail.content_sha256?'本版准确内容':'其他内容版本'}}</td></tr></tbody></table></div><p v-if="!confirmations.length" class="supply-empty">尚无已保存的确认。接口没有确认时间字段，本页不补造时间。</p><button class="outline" :disabled="locked" @click="loadConfirmations(detail.id)">刷新确认记录</button></section></template>
<template v-if="mode==='readiness'&&p"><section class="supply-card"><h2>最新开工可用状态</h2><p :class="readiness?.current_status==='AVAILABLE'?'supply-notice':'supply-warning'">{{readiness?.current_status==='AVAILABLE'?'当前开工条件齐全':readiness?'暂不满足开工条件':'尚未读取开工条件'}}</p><p v-if="readiness?.reason_code" data-testid="project-readiness-reason">当前阻止原因：{{explainError({status:409,code:readiness.reason_code,message:'',retryable:false})}}（{{readiness.reason_code}}）</p><p class="muted">此接口返回当前一个阻止原因，处理后继续读取；没有返回全量核验清单。AVAILABLE 不代表成片验收、实际送出或外部发行。</p><div class="supply-actions"><button class="outline" :disabled="locked" @click="refreshReadiness" data-testid="project-readiness-refresh">刷新开工条件</button><button class="primary" :disabled="locked||!isSponsor||readiness?.current_status!=='AVAILABLE'||p.current_status!=='PREPARING'" @click="start" data-testid="project-start">启动项目</button></div></section></template>
<form v-if="mode==='edition'&&p" @submit.prevent="submitEdition"><fieldset :disabled="locked||!isSponsor||p.current_status!=='STARTED'"><section class="supply-card"><h2>当前项目与制作成片</h2><label>制作域准确成片版本 *<select v-model="edition.final" data-testid="edition-final" required><option value="">待选择当前已验收成片</option><option v-for="id in finalOptions" :key="id" :value="id">{{id}}</option></select></label><p v-if="!finalOptions.length" class="supply-warning">尚未读取到制作项目当前已验收成片。原订单须实际付清，服务器将再次核验。</p><RouterLink v-if="sourceProduction" :to="`/production/projects/${sourceProduction.id}`" class="table-link">查看原制作项目与受控交付</RouterLink></section><section class="supply-card"><h2>发行材料与版本说明</h2><SupplyUpload :key="securityRevision" label="成片版本材料" :ids="assets" :disabled="locked||assets.length>=30" @upload="upload" @remove="removeAsset"/><label>本次版本说明 *<textarea v-model="edition.note" data-testid="edition-note" required maxlength="2000"></textarea></label><button class="primary" :disabled="locked||!finalOptions.includes(edition.final)||!assets.length||!edition.note.trim()" data-testid="edition-submit">提交项目成片</button></section></fieldset></form>
<form v-if="mode==='release'&&p" @submit.prevent="submitRelease"><fieldset :disabled="locked||!isSponsor||p.current_status!=='STARTED'"><section class="supply-card"><h2>确定成片及实际渠道</h2><p>本项目当前成片记录：{{p.data.current_edition_id||'尚未提交成片材料'}}</p><p class="muted">当前成片材料须通过独立核验及各方会签。本操作只提交内部发行申请。</p><label>已核验发行渠道 *<select v-model="release.channel" data-testid="release-channel" required><option value="">待选择真实渠道摘要</option><option v-for="c in catalogue.filter(c=>c.kind==='CHANNEL')" :key="c.id" :value="c.id">{{c.title}} · {{c.channel_reference}}</option></select></label><label>前次发行记录（首次留空）<select v-model="release.prior" data-testid="release-prior"><option value="">首次申请</option><option v-for="r in releases.filter(r=>r.kind==='RELEASE'&&r.data.channel_id===release.channel&&['CHANGES_REQUESTED','REJECTED','EXTERNAL_CHANGES_REQUESTED','EXTERNAL_REJECTED','EXTERNAL_WITHDRAWN'].includes(r.current_status))" :key="r.id" :value="r.id">{{r.id}} · {{projectStatus(r)}}</option></select></label></section><section class="supply-card"><h2>本次提交材料与说明</h2><SupplyUpload :key="securityRevision" label="发行申请材料" :ids="assets" :disabled="locked||assets.length>=30" @upload="upload" @remove="removeAsset"/><label>发行说明 *<textarea v-model="release.note" data-testid="release-note" required maxlength="2000"></textarea></label><button class="primary" :disabled="locked||!release.channel||!assets.length||!release.note.trim()" data-testid="release-submit">提交发行申请</button></section></fieldset></form>
<form v-if="mode==='channel'" @submit.prevent="registerChannel"><fieldset :disabled="locked||!isOwner"><section class="supply-card"><h2>渠道名称与外部参考</h2><div class="trade-fields two"><label>渠道名称 *<input v-model="channel.name" data-testid="channel-name" required maxlength="200"></label><label>实际外部参考 *<input v-model="channel.reference" data-testid="channel-reference" required maxlength="1000"></label></div><label>渠道提交要求 *<textarea v-model="channel.requirements" data-testid="channel-requirements" required maxlength="8000"></textarea></label></section><section class="supply-card"><h2>渠道私有证明</h2><SupplyUpload :key="securityRevision" label="渠道档案证明" :ids="assets" :disabled="locked" single @upload="upload" @remove="removeAsset"/><p class="muted">资料登记须负责人身份及 PROJECT_REVIEW；登记不代表已审核或已取得渠道资格。独立审核由无利益关联账号办理。</p><button class="primary" :disabled="locked||!channel.name.trim()||!channel.reference.trim()||!channel.requirements.trim()||assets.length!==1" data-testid="channel-submit">登记渠道待审核</button></section></fieldset></form>
<template v-if="detail&&(mode==='channel-detail'||mode==='record')"><ProjectRecordPanel :record="detail"/><section v-if="evidenceIds(detail).length" class="supply-card"><h2>关联私有证明</h2><button v-for="id in [...new Set(evidenceIds(detail))]" :key="id" class="outline" :disabled="locked" @click="readEvidence(id)">读取本事项证明 {{id.slice(0,8)}}</button><p class="muted">原始证明只限项目发起方或获授权审核账号；普通参与方不会获得全部材料下载权。</p></section></template>
<template v-if="mode==='external'&&detail?.kind==='RELEASE'"><div class="project-columns"><div><ProjectRecordPanel :record="detail"/><form @submit.prevent="reportExternal"><fieldset :disabled="locked||!isSponsor"><section class="supply-card"><h2>外部参考与实际发生时间</h2><div class="trade-fields two"><label>外部参考 *<input v-model="external.reference" data-testid="external-reference" required maxlength="1000"></label><label>实际发生日期时间 *<input v-model="external.time" type="datetime-local" data-testid="external-time" required></label></div><SupplyUpload :key="securityRevision" label="真实外部证明" :ids="assets" :disabled="locked" single @upload="upload" @remove="removeAsset"/><label>补充说明 *<textarea v-model="external.note" data-testid="external-note" required maxlength="4000"></textarea></label><RouterLink v-if="detail.owner_party_id===session.selectedId&&['EXTERNAL_PUBLISHED','EXTERNAL_WITHDRAWN'].includes(detail.current_status)" :to="`/finance/agreements/new?sourceType=RELEASE&sourceId=${detail.id}`" class="button-link outline" data-testid="project-finance-agreement">从实际发行建立结算约定</RouterLink><button class="primary" :disabled="locked||!external.outcome||!external.reference.trim()||!external.time||!external.note.trim()||assets.length!==1" data-testid="external-submit">登记外部事实待核验</button></section></fieldset></form></div><section class="supply-card project-action-panel"><h2>外部事实报告</h2><label>实际外部结果 *<select v-model="external.outcome" data-testid="external-outcome" :disabled="locked||!isSponsor" required><option value="">待选择</option><option value="SUBMITTED">已实际提交</option><option value="CHANGES_REQUESTED">外部要求补件</option><option value="REJECTED">外部拒绝</option><option value="PUBLISHED">外部已发行</option><option value="WITHDRAWN">外部已撤下</option></select></label><p class="muted">报告不会自动改变发行状态；凭据经独立核实后才记录外部事实。补件或拒绝须建立新申请关联旧记录，不覆盖历史。</p></section></div></template>
<template v-if="reviewer&&detail"><div class="project-columns"><div><section v-if="p" class="supply-card"><h2>{{p.data.title}}</h2><p>{{p.data.scope.purpose==='RELEASE'?'发行':'公开分享'}} · {{p.data.scope.territory}} / {{p.data.scope.language}} · {{p.data.scope.valid_until}}</p></section><ProjectRecordPanel :record="detail"/><details v-if="related.length" class="supply-card project-related"><summary>核对关联方案、成片及渠道的原始事实</summary><ProjectRecordPanel v-for="item in related" :key="item.id" :record="item"/></details><section class="supply-card"><h2>本事项的实际私有证据</h2><div v-for="id in [...new Set(evidenceIds(detail))]" :key="id" class="project-evidence-row"><span>{{id.slice(0,8)}} · {{readAssets.includes(id)?'本次已读取':'本次未读取'}}</span><button class="outline" :disabled="locked" @click="readEvidence(id)" :data-testid="`project-read-evidence-${id}`">读取本事项依据</button></div><p class="muted">实际查看原材料后逐项核验；接口读取成功本身不代表权利或外部事实已经真实核实。</p></section></div><section class="supply-card project-action-panel"><h2>独立核验项与结论</h2><form @submit.prevent="review"><fieldset :disabled="locked||!['IN_REVIEW','INTERNAL_PENDING'].includes(detail.current_status)||detail.created_by===session.account?.id"><label v-for="key in currentFields" :key="key" class="trade-check"><input v-model="checks[key]" type="checkbox" :data-testid="`review-${key}`">{{verificationLabels[key]}}</label><label>本次核验结论 *<select v-model="decision" data-testid="review-decision" required><option value="">待选择</option><option value="APPROVED">批准</option><option value="CHANGES_REQUESTED">要求补件，另建新申请</option><option value="REJECTED">拒绝</option></select></label><label>实际核验理由 *<textarea v-model="reason" data-testid="review-reason" required maxlength="4000"></textarea></label><button class="primary" :disabled="locked||!reviewValid" data-testid="project-review-submit">提交独立核验</button></fieldset></form><p class="muted">核验不得由创建者、发起方或其他参与方成员自行办理；权限及当前依赖由服务器再次核实。</p></section></div></template>
<div class="trade-footer"><RouterLink :to="reviewer?`/projects/reviews/${section}`:'/projects/projects'" class="button-link outline">返回{{reviewer?'核验入口':'项目列表'}}</RouterLink><RouterLink v-if="!reviewer" to="/projects/channels/new" class="button-link outline">登记渠道档案</RouterLink></div>
</div></main></div></div>
</template>
