<script setup lang="ts">
import { computed, onMounted, onUnmounted, reactive, ref, watch } from 'vue'
import { onBeforeRouteLeave, onBeforeRouteUpdate, useRoute, useRouter } from 'vue-router'
import { useSessionStore } from '@/stores/session'
import { useTrade } from '@/composables/useTrade'
import { getGig, listGigs, type GigRecord } from '@/api/modules/gigs'
import { useSupply } from '@/composables/useSupply'
import { ApiError, asApiError } from '@/api/client'
import { amountInput, getTrade, money, refundable, tradeStatus, tradeTitle, validRefund, type TradeKind, type TradeRecord, type TradeWrite } from '@/api/modules/trade'
import { validSupplyId, type MediaType, type SupplyAsset } from '@/api/modules/supply'
import WorkspaceNav from '@/components/WorkspaceNav.vue'
import ApiErrorAlert from '@/components/ApiErrorAlert.vue'
import SupplyUpload from '@/components/SupplyUpload.vue'
import TradeSpecForm from '@/components/TradeSpecForm.vue'
import TradeQuoteForm from '@/components/TradeQuoteForm.vue'
import TradeRecordPanel from '@/components/TradeRecordPanel.vue'
import '@/styles/supply.css'
import '@/styles/trade.css'

const session=useSessionStore(),route=useRoute(),router=useRouter()
const section=computed(()=>route.name==='trade-offer-new'?'quotes':route.name==='trade-version'?'specifications':String(route.params.section||'quotes')),reviewer=computed(()=>route.name==='trade-review'||section.value==='legacy'&&route.name==='trade-new')
const formPage=computed(()=>route.name==='trade-new'||route.name==='trade-version'||route.name==='trade-offer-new'),targetId=computed(()=>typeof route.params.recordId==='string'?route.params.recordId:'')
const kindMap:Record<string,TradeKind>={specifications:'SPEC',quotes:'QUOTE',orders:'ORDER',payments:'PAYMENT',refunds:'REFUND',legacy:'LEGACY'},kind=computed(()=>kindMap[section.value]||'QUOTE')
const titles:Record<string,string>={specifications:'商品规格',quotes:'报价与订单记录',orders:'订单记录',payments:'付款状态与到账核实',refunds:'退款申请与结果',legacy:'历史订单登记与核对'}
const pageTitle=computed(()=>formPage.value?{specifications:'新建服务规格版本',quotes:'创建明确报价',payments:'建立本期付款记录',refunds:'退款申请',legacy:'历史订单登记与核对'}[section.value]:targetId.value?reviewer.value?{specifications:'服务规格独立审核',quotes:'报价独立审核',refunds:'退款独立复核与执行',legacy:'历史订单依据独立核对'}[section.value]:{specifications:'服务规格详情',quotes:'客户确认报价',orders:'订单履约详情',payments:'付款状态与到账核实',refunds:'退款申请与结果',legacy:'历史订单登记与核对'}[section.value]:titles[section.value])
const canOwn=computed(()=>!!session.selected&&session.selected.membership.current_status==='ACTIVE'&&session.selected.membership.roles.includes('OWNER')&&!['SUSPENDED','CLOSED'].includes(session.selected.party.current_status))
const context=()=>({token:session.token,accountId:session.account?.id||'',partyId:reviewer.value?null:session.selectedId,revision:session.revision,scope:route.fullPath})
const ui=useTrade(context),uploadUi=useSupply(()=>({...context(),partyId:session.selectedId}))
const {rows,detail,related,nextCursor,error,notice,pending,busy,securityRevision,conflictRevision,retryAt}=ui
const offers=ref<GigRecord[]>([])
const initializing=ref(true),pageLoading=ref(false),now=ref(Date.now()),specs=ref<TradeRecord[]>([]),payments=ref<TradeRecord[]>([]),refunds=ref<TradeRecord[]>([]),sourceOrder=ref<TradeRecord|null>(null),sourcePayment=ref<TradeRecord|null>(null)
const decision=ref(''),reason=ref(''),acceptConfirmed=ref(false),executionConfirmed=ref(false),cancelReason=ref(''),appleTransaction=ref(''),orderInput=ref(''),installmentInput=ref(''),paymentInput=ref(''),refundReason=ref(''),refundAmounts=ref<Record<string,string>>({}),openId=ref('')
const legacy=reactive({system:'',order:'',buyer:'',merchant:'',terms:'',asset:'',lines:[{line:'',amount:'',status:''}]}),assets=ref<string[]>([])
const conflicted=ref(false),newDecision=ref(false),locked=computed(()=>busy.value||uploadUi.busy.value||!!pending.value||!!uploadUi.pending.value||now.value<Math.max(retryAt.value,uploadUi.retryAt.value)||conflicted.value&&!newDecision.value)
const isBuyer=computed(()=>detail.value?.buyer_party_id===session.selectedId),reviewable=computed(()=>reviewer.value&&detail.value&&detail.value.created_by!==session.account?.id&&({SPEC:'IN_REVIEW',QUOTE:'IN_REVIEW',REFUND:'REQUESTED',LEGACY:'NEEDS_REVIEW'} as Record<string,string>)[detail.value.kind]===detail.value.current_status)
const refundAllocations=computed(()=>Object.entries(refundAmounts.value).filter(([,value])=>value!=='').map(([line,value])=>({line_id:line,amount_minor:amountInput(value)||0})))
const refundValid=computed(()=>sourcePayment.value&&refundReason.value.trim()&&validRefund(sourcePayment.value,refunds.value,refundAllocations.value))
const selectedInstallment=computed(()=>sourceOrder.value?.kind==='ORDER'?sourceOrder.value.data.quote.installments.find(i=>i.key===installmentInput.value):null)
const paymentValid=computed(()=>sourceOrder.value?.kind==='ORDER'&&sourceOrder.value.buyer_party_id===session.selectedId&&['OPEN','PARTIALLY_PAID'].includes(sourceOrder.value.current_status)&&selectedInstallment.value?.trigger==='ORDER_ACCEPTED'&&!payments.value.some(p=>p.kind==='PAYMENT'&&p.order_id===sourceOrder.value?.id&&p.data.installment_key===installmentInput.value&&['CREATED','SUBMITTING','PENDING','UNKNOWN','SUCCEEDED','REVIEW_REQUIRED'].includes(p.current_status)))
const legacyPayload=computed(()=>{if(!validSupplyId(legacy.buyer)||!validSupplyId(legacy.merchant)||!legacy.system.trim()||!legacy.order.trim()||!legacy.terms.trim()||!validSupplyId(legacy.asset)||!legacy.lines.length||legacy.lines.length>30||new Set(legacy.lines.map(l=>l.line)).size!==legacy.lines.length||legacy.lines.some(l=>!l.line.trim()||amountInput(l.amount,0)===null||!['REPORTED_PAID','REPORTED_UNPAID','UNKNOWN'].includes(l.status)))return null;return {buyer_party_id:legacy.buyer,merchant_party_id:legacy.merchant,source_system:legacy.system.trim(),source_order_id:legacy.order.trim(),original_terms:legacy.terms.trim(),evidence_asset_id:legacy.asset,original_lines:legacy.lines.map(l=>({line_id:l.line.trim(),amount_minor:amountInput(l.amount,0),reported_status:l.status}))}})
let disposed=false,pageTicket=0,timer=0
function reset(){offers.value=[];specs.value=[];payments.value=[];refunds.value=[];sourceOrder.value=null;sourcePayment.value=null;decision.value=reason.value=cancelReason.value=appleTransaction.value=orderInput.value=installmentInput.value=paymentInput.value=refundReason.value=openId.value='';acceptConfirmed.value=executionConfirmed.value=false;refundAmounts.value={};assets.value=[];Object.assign(legacy,{system:'',order:'',buyer:'',merchant:'',terms:'',asset:'',lines:[{line:'',amount:'',status:''}]});conflicted.value=false;newDecision.value=false}
watch(securityRevision,reset,{flush:'sync'})
watch(conflictRevision,()=>{decision.value=reason.value=cancelReason.value='';acceptConfirmed.value=executionConfirmed.value=false;conflicted.value=true;newDecision.value=false},{flush:'sync'})
watch(uploadUi.error,e=>{if(e&&[401,403,404].includes(e.status))ui.clear()},{flush:'sync'});watch(error,e=>{if(e&&[401,403,404].includes(e.status))uploadUi.clear()},{flush:'sync'})
watch(()=>[route.fullPath,session.selectedId,session.revision],()=>{if(!initializing.value)void loadPage()})
function pathFor(r:TradeRecord){const s={SPEC:'specifications',QUOTE:'quotes',ORDER:'orders',PAYMENT:'payments',REFUND:'refunds',LEGACY:'legacy'}[r.kind];return `/trade/${reviewer.value&&['SPEC','QUOTE','REFUND','LEGACY'].includes(r.kind)?'reviews/':''}${s}/${r.id}`}
async function gotoRecord(r:TradeRecord){await router.push(pathFor(r))}
async function loadPage(){const ticket=++pageTicket,current=()=>!disposed&&ticket===pageTicket;pageLoading.value=true;try{if(!reviewer.value&&!canOwn.value){ui.clear();error.value=new ApiError({status:403,code:'TRADE_PARTY_FORBIDDEN',message:'请选择有效负责人身份办理。'});return}if(targetId.value&&!validSupplyId(targetId.value)){error.value=new ApiError({status:400,code:'CLIENT_RECORD_INVALID',message:'请使用完整的记录编号。'});return}if(formPage.value){if(section.value==='quotes'){const all=await ui.loadAll('SPEC');if(current()&&all)specs.value=all.filter(r=>r.merchant_party_id===session.selectedId);const found=await ui.read('commercial-offers',async(i,s)=>{if(typeof route.params.offerId==='string'){return [await getGig(i,route.params.offerId,'OFFER',s)]}const items:GigRecord[]=[],seen=new Set<string>();let cursor:string|null=null;do{const page=await listGigs(i,'OFFER',cursor,s);items.push(...page.items);cursor=page.next_cursor;if(cursor&&seen.has(cursor))throw new ApiError({status:200,code:'UNEXPECTED_RESPONSE_SHAPE',message:'提案列表没有前进。'});if(cursor)seen.add(cursor)}while(cursor);return items});if(current()&&found)offers.value=found.filter(r=>r.kind==='OFFER'&&r.owner_party_id===session.selectedId&&r.current_status==='ACCEPTED')}if(['payments','refunds'].includes(section.value)){const all=await ui.loadAll('PAYMENT');if(current()&&all)payments.value=all;if(section.value==='refunds'){const all=await ui.loadAll('REFUND');if(current()&&all)refunds.value=all}}return}if(!targetId.value){await ui.loadList(kind.value);return}const r=await ui.loadRecord(targetId.value,kind.value);if(!current()||!r)return;if(r.kind==='ORDER'){const all=await ui.loadAll('PAYMENT');if(current()&&all)related.value=all.filter(p=>p.order_id===r.id)}if(r.kind==='PAYMENT'){const all=await ui.loadAll('REFUND');if(current()&&all){refunds.value=all;related.value=all.filter(x=>x.kind==='REFUND'&&x.data.payment_id===r.id)}}}finally{if(current())pageLoading.value=false}}
function leavePending(){if(ui.canNavigate()&&!uploadUi.pending.value)return true;notice.value='原操作结果尚未核对，暂不能切换页面。请先核对，再使用原请求编号重试。';return false}
onBeforeRouteLeave(leavePending);onBeforeRouteUpdate(leavePending)
function beforeUnload(e:BeforeUnloadEvent){if(!ui.canNavigate()||uploadUi.pending.value){e.preventDefault();e.returnValue=''}}
onMounted(async()=>{timer=window.setInterval(()=>now.value=Date.now(),1000);window.addEventListener('beforeunload',beforeUnload);const captured=session.capture();try{await Promise.all([session.loadAccount(),session.loadParties()]);if(!disposed&&session.current(captured)){initializing.value=false;await loadPage()}}catch(e){if(!disposed&&session.current(captured)){ui.clear();error.value=asApiError(e)}}finally{if(!disposed)initializing.value=false}})
onUnmounted(()=>{disposed=true;pageTicket++;window.clearInterval(timer);window.removeEventListener('beforeunload',beforeUnload)})
async function create(path:string,body:unknown,resultKind:TradeKind,label:string){if(locked.value)return;await ui.write({path:'/trade/'+path,body,resultKind,label},gotoRecord)}
async function mutate(suffix:string,body:unknown,label:string,resultKind?:TradeKind,version=true){const r=detail.value;if(locked.value||!r)return;await ui.write({path:`/trade/${suffix}`,body,resultKind:resultKind||r.kind,targetId:r.id,version:version?r.object_version:undefined,label},gotoRecord)}
function review(){const r=detail.value;if(!r||!reviewable.value||!decision.value||!reason.value.trim())return;void mutate(`records/${r.id}/reviews`,{decision:decision.value,reason:reason.value.trim()},'提交独立审核')}
function accept(){const r=detail.value;if(r?.kind!=='QUOTE'||r.current_status!=='APPROVED'||!isBuyer.value||!acceptConfirmed.value||Date.parse(r.data.expires_at)<=now.value)return;void mutate(`quotes/${r.id}/acceptance`,{quote_sha256:r.content_sha256},'确认报价并建立订单','ORDER')}
function cancel(){const r=detail.value;if(r?.kind!=='ORDER'||r.current_status!=='OPEN'||!cancelReason.value.trim()||r.data.financial.received_minor!==0||related.value.some(p=>p.kind==='PAYMENT'&&['CREATED','SUBMITTING','PENDING','UNKNOWN','SUCCEEDED','REVIEW_REQUIRED'].includes(p.current_status)))return;void mutate(`orders/${r.id}/cancellation`,{reason:cancelReason.value.trim()},'取消未付款订单')}
function reconcilePayment(){const r=detail.value;if(r?.kind!=='PAYMENT'||!isBuyer.value||r.data.provider==='APPLE'&&!appleTransaction.value.trim())return;void mutate(`payments/${r.id}/reconciliation`,{transaction_id:r.data.provider==='ALIPAY'?null:appleTransaction.value.trim()},'核实支付结果',undefined,false)}
function executeRefund(){const r=detail.value;if(r?.kind!=='REFUND'||!reviewer.value||r.current_status!=='APPROVED'||!executionConfirmed.value)return;void mutate(`refunds/${r.id}/execution`,{},'执行已审退款',undefined,false)}
function reconcileRefund(){const r=detail.value;if(r?.kind!=='REFUND'||reviewer.value)return;void mutate(`refunds/${r.id}/reconciliation`,{},'核实原退款结果',undefined,false)}
async function readOrder(){if(locked.value||!validSupplyId(orderInput.value))return;sourceOrder.value=null;installmentInput.value='';const ticket=pageTicket,r=await ui.read('source-order',(i,s)=>getTrade(i,orderInput.value,'ORDER',s));if(ticket===pageTicket&&r)sourceOrder.value=r}
async function readPayment(){if(locked.value||!validSupplyId(paymentInput.value))return;sourcePayment.value=null;refundAmounts.value={};const ticket=pageTicket,r=await ui.read('source-payment',(i,s)=>getTrade(i,paymentInput.value,'PAYMENT',s));if(ticket===pageTicket&&r){sourcePayment.value=r;if(r.kind==='PAYMENT')refundAmounts.value=Object.fromEntries(r.data.allocations.map(a=>[a.line_id,'']))}}
async function upload(file:File,type:MediaType){if(locked.value||!canOwn.value)return;await uploadUi.write({path:`/supply/assets?${new URLSearchParams({purpose:'RIGHTS_EVIDENCE',media_type:type})}`,blob:file,purpose:'RIGHTS_EVIDENCE',mediaType:type,kind:'ASSET',label:'上传历史私有依据'},r=>{assets.value=[(r as SupplyAsset).id];legacy.asset=(r as SupplyAsset).id})}
function openRecord(){if(!validSupplyId(openId.value)||locked.value)return;void router.push(`/trade/${reviewer.value?'reviews/':''}${section.value}/${openId.value}`)}
const gallery=computed(()=>formPage.value?{specifications:'WEB-09-02',quotes:'WEB-13-02',payments:'WEB-15-01-v2',refunds:'WEB-15-02-v2',legacy:'WEB-15-04-v2'}[section.value]:targetId.value?reviewer.value?{specifications:'WEB-09-04-v2',quotes:'WEB-13-03',refunds:'WEB-15-03-v2',legacy:'WEB-15-04-v2'}[section.value]:{specifications:'WEB-09-02',quotes:'WEB-13-04',orders:'WEB-14-01',payments:'WEB-15-01-v2',refunds:'WEB-15-02-v2',legacy:'WEB-15-04-v2'}[section.value]:'WEB-13-01-v2')
</script>
<template>
 <div class="supply-workspace trade-workspace" :data-gallery="gallery"><header class="supply-header"><RouterLink to="/workspace" class="supply-brand">晶晶日上</RouterLink><span>运营与合作方工作台</span><div class="account-actions"><span class="account-name">{{session.account?.display_name||'当前账号'}}</span><button @click="session.logout().then(()=>router.push('/login'))">退出</button></div></header><div class="supply-layout"><aside class="supply-sidebar"><WorkspaceNav/><div class="supply-identity"><template v-if="reviewer"><p>独立交易审核</p><p class="muted">以当前账号办理。交易审核与退款权限由服务器核验，不能自行取得。</p></template><template v-else><label for="trade-party">当前办理身份</label><select id="trade-party" :value="session.selectedId" :disabled="locked" @change="session.selectParty(($event.target as HTMLSelectElement).value)"><option v-for="p in session.parties" :key="p.party.id" :value="p.party.id">{{p.party.display_name}}</option></select><p class="muted">{{canOwn?'有效负责人身份':'需有效负责人身份'}}</p></template></div></aside><main class="supply-main">
 <div class="supply-heading"><div><h1>{{pageTitle}}</h1><p>{{reviewer?'核对保存的规格、金额、条款和原始材料。':formPage?'明确填写本次商业约定，提交后按真实记录办理。':'按当前身份读取报价、付款及退款的真实记录。'}}</p></div><button class="outline" :disabled="locked||pageLoading" @click="loadPage">刷新当前记录</button></div>
 <div class="loaded-tabs"><RouterLink v-for="s in (reviewer?['specifications','quotes','refunds','legacy']:['specifications','quotes','orders','payments','refunds','legacy'])" :key="s" :to="`/trade/${reviewer?'reviews/':''}${s}`" :class="{active:section===s}">{{titles[s]}}</RouterLink></div>
 <ApiErrorAlert :error="error"/><ApiErrorAlert :error="uploadUi.error.value"/><p v-if="notice" class="supply-notice" role="status">{{notice}}</p>
 <div v-if="pending" class="supply-warning"><p>{{pending.command.label}}结果尚未确认。保留原请求编号、原内容及原版本，请先核对。{{pending.resultId?`已知结果记录：${pending.resultId}`:''}}</p><p class="identifier">原请求编号：{{pending.key}}</p><div class="supply-actions"><button class="outline" :disabled="busy||now<retryAt" @click="ui.checkPending()">{{pending.resultId?'重新读取已知结果':'先核对原记录'}}</button><button v-if="!pending.resultId" class="primary" :disabled="busy||!pending.checked||now<retryAt" @click="ui.retry()">使用原编号重试</button></div></div>
 <div v-if="uploadUi.pending.value" class="supply-warning"><p>原上传尚未确认，保留原文件及请求编号。</p><button :disabled="uploadUi.busy.value" class="outline" @click="uploadUi.retry()">重试原上传</button></div>
 <div v-if="conflicted" class="supply-warning"><label class="trade-check"><input v-model="newDecision" type="checkbox">我已核对最新记录，将重新作出决定。</label></div>
 <p v-if="initializing||pageLoading" class="supply-empty" role="status">正在读取身份与交易记录…</p>
 <div v-else :key="route.fullPath+securityRevision">
 <template v-if="formPage">
 <TradeSpecForm v-if="section==='specifications'" :disabled="locked" :previous="targetId" @submit="body=>create('specifications',body,'SPEC','提交规格审核')"/>
 <TradeQuoteForm v-else-if="section==='quotes'" :disabled="locked" :specs="specs" :offers="offers" :offer-id="typeof route.params.offerId==='string'?route.params.offerId:undefined" @submit="body=>create('quotes',body,'QUOTE','提交报价审核')"/>
 <form v-else-if="section==='payments'" class="trade-form" @submit.prevent="paymentValid && create('payments',{order_id:sourceOrder!.id,installment_key:installmentInput},'PAYMENT','建立本期付款记录')"><fieldset :disabled="locked"><section class="supply-card"><h2>订单及当前分期</h2><div class="trade-fields two"><label>订单编号 *<input v-model="orderInput" data-testid="trade-order-id" required placeholder="完整订单编号"></label><button type="button" class="outline" :disabled="!validSupplyId(orderInput)" @click="readOrder">读取原订单</button></div><template v-if="sourceOrder?.kind==='ORDER'"><p class="identifier">{{sourceOrder.id}} · {{tradeStatus(sourceOrder)}}</p><label>付款分期名称 *<select v-model="installmentInput" data-testid="trade-installment" required><option value="">请选择原订单分期</option><option v-for="i in sourceOrder.data.quote.installments" :key="i.key" :value="i.key" :disabled="i.trigger!=='ORDER_ACCEPTED'">{{i.key}} · {{money(i.allocations.reduce((s,a)=>s+a.amount_minor,0))}}{{i.trigger==='ORDER_ACCEPTED'?'':' · 验收条件尚未开放'}}</option></select></label></template></section><section class="supply-card"><h2>支付客户端状态</h2><p class="supply-warning">浏览器支付客户端尚未开放；本页只建立、读取和核对付款记录。正式支付服务未完成验证，不能据本页认定已收款。</p><p class="muted">已有待核实、处理中或成功付款的分期，请先打开原付款记录。结果未知不会自动另建付款。</p><button class="primary" :disabled="!paymentValid||locked">建立本期付款记录</button></section></fieldset></form>
 <form v-else-if="section==='refunds'" class="trade-form" @submit.prevent="refundValid && create('refunds',{payment_id:sourcePayment!.id,allocations:refundAllocations,reason:refundReason.trim()},'REFUND','提交退款申请')"><fieldset :disabled="locked"><section class="supply-card"><h2>原付款和可退明细</h2><div class="trade-fields two"><label>原付款编号 *<select v-model="paymentInput" data-testid="trade-refund-payment" required><option value="">选定已核实付款</option><option v-for="p in payments.filter(p=>p.kind==='PAYMENT'&&p.current_status==='SUCCEEDED')" :key="p.id" :value="p.id">{{p.id}} · {{p.kind==='PAYMENT'?money(p.data.amount_minor):''}}</option></select></label><button type="button" class="outline" :disabled="!validSupplyId(paymentInput)" @click="readPayment">读取原付款与明细</button></div><p v-if="sourcePayment" class="muted">{{tradeStatus(sourcePayment)}} · {{sourcePayment.kind==='PAYMENT'&&sourcePayment.data.provider==='APPLE'?'Apple 仅支持逐项全额退款；全部金额须等于原付款。':'每项不得超过本付款剩余可退金额。'}}</p></section><section v-if="sourcePayment" class="supply-card"><h2>逐项退款金额</h2><div v-for="a in refundable(sourcePayment,refunds)" :key="a.line_id" class="trade-allocation"><label>明细编号<input :value="a.line_id" disabled></label><label>退款金额（人民币分）<input v-model="refundAmounts[a.line_id]" inputmode="numeric" :placeholder="`可退 ${money(a.amount_minor)}；不申请可留空`"></label></div><p class="muted">已申请、处理中、待核实的退款也占用可退额度；提交仍由服务器再次核验。</p></section><section class="supply-card"><h2>申请原因</h2><label>本次退款原因 *<textarea v-model="refundReason" maxlength="2000" required placeholder="待填写"></textarea></label></section><section class="supply-card"><h2>申请提交</h2><button class="primary" :disabled="locked||!refundValid">提交退款申请</button><p class="muted">提交后等待独立复核。批准及发送请求均不代表已经退款。</p></section></fieldset></form>
 <form v-else-if="section==='legacy'" class="trade-form" @submit.prevent="legacyPayload && create('legacy-orders',legacyPayload,'LEGACY','登记历史订单')"><fieldset :disabled="locked"><section class="supply-card"><h2>原系统与原单编号</h2><div class="trade-fields two"><label>原系统名称 *<input v-model="legacy.system" maxlength="128" required></label><label>原订单编号 *<input v-model="legacy.order" maxlength="128" required></label></div></section><section class="supply-card"><h2>历史买卖主体</h2><div class="trade-fields two"><label>买方主体编号 *<input v-model="legacy.buyer" required></label><label>商家主体编号 *<input v-model="legacy.merchant" required></label></div></section><section class="supply-card"><div class="section-heading"><h2>原始明细与原条款</h2><button class="outline" type="button" :disabled="legacy.lines.length>=30" @click="legacy.lines.push({line:'',amount:'',status:''})">添加原明细</button></div><div v-for="(l,n) in legacy.lines" :key="n" class="trade-row"><div class="trade-fields three"><label>明细编号 *<input v-model="l.line" maxlength="128" required></label><label>原金额（人民币分） *<input v-model="l.amount" inputmode="numeric" required></label><label>原系统申报状态 *<select v-model="l.status" required><option value="">待选择</option><option value="REPORTED_PAID">原系统申报已付</option><option value="REPORTED_UNPAID">原系统申报未付</option><option value="UNKNOWN">原系统未知</option></select></label></div><button v-if="legacy.lines.length>1" class="danger" type="button" @click="legacy.lines.splice(n,1)">移除原明细</button></div><label>原条款 *<textarea v-model="legacy.terms" maxlength="8000" required></textarea></label></section><section class="supply-card"><h2>私有原单证明</h2><label>原始证明编号 *<input v-model="legacy.asset" required placeholder="原买卖方已上传的私有材料编号"></label><p class="muted">登记需交易审核权限；材料须归属原买卖方。原当事方可在下方上传后将编号提供给登记人员。</p><label>当前上传身份<select :value="session.selectedId" :disabled="locked" @change="session.selectParty(($event.target as HTMLSelectElement).value)"><option v-for="p in session.parties" :key="p.party.id" :value="p.party.id">{{p.party.display_name}}</option></select></label><SupplyUpload :key="securityRevision+uploadUi.securityRevision.value" label="私有原单证明" :ids="assets" single :disabled="locked||!canOwn" @upload="upload" @remove="assets=[];legacy.asset=''"/></section><section class="supply-card"><h2>登记及审核说明</h2><p class="supply-warning">保留原金额与原报告状态，核对历史材料不追认渠道入账。创建者不能审核自己登记的记录。</p></section><div class="trade-footer"><RouterLink to="/trade/legacy" class="button-link outline">返回历史记录</RouterLink><button class="primary" :disabled="locked||!legacyPayload">登记历史订单</button></div></fieldset></form>
 </template>
 <template v-else-if="!targetId"><section class="supply-card"><dl class="supply-facts"><div><dt>记录类别</dt><dd>{{titles[section]}}</dd></div><div><dt>本页内容</dt><dd>保存的约定、金额与实际状态</dd></div></dl></section><div class="trade-list-actions"><RouterLink v-if="!reviewer&&['specifications','quotes','payments','refunds','legacy'].includes(section)" :to="`/trade/${section}/new`" class="button-link primary">{{section==='specifications'?'新建服务规格':section==='quotes'?'新建报价':section==='payments'?'建立付款记录':section==='refunds'?'申请退款':'登记历史订单'}}</RouterLink><RouterLink v-if="section==='quotes'" class="button-link outline" to="/trade/orders">加载订单</RouterLink><label>记录编号<input v-model="openId" placeholder="打开已有记录"></label><button class="outline" :disabled="locked||!validSupplyId(openId)" @click="openRecord">打开记录</button></div><section class="supply-card"><h2>{{reviewer?'可获准独立审核的记录':'当前身份的交易记录'}}</h2><div v-if="rows.length" class="table-wrap"><table><thead><tr><th>记录类别与编号</th><th>当前状态</th><th>保存内容</th><th>操作</th></tr></thead><tbody><tr v-for="r in rows" :key="r.id"><td>{{r.kind}}<div class="identifier">{{r.id}}</div></td><td>{{tradeStatus(r)}}</td><td>{{tradeTitle(r)}}</td><td><RouterLink :to="pathFor(r)" class="button-link table-link">打开记录</RouterLink></td></tr></tbody></table></div><p v-else class="supply-empty">当前没有可读取记录。可用完整记录编号打开已获准查看的记录。</p><button v-if="nextCursor" class="outline" :disabled="locked" @click="ui.loadList(kind,true)">加载下一页</button></section></template>
 <template v-else-if="detail"><div :class="reviewer?'review-layout':''"><div><TradeRecordPanel :record="detail" :compact="reviewer">
 <section v-if="!reviewer&&detail.kind==='QUOTE'" class="supply-card"><h2>所确认内容</h2><p class="identifier">{{detail.content_sha256}}</p><label class="trade-check"><input v-model="acceptConfirmed" type="checkbox" :disabled="locked||detail.current_status!=='APPROVED'||!isBuyer">我已核对本报价的服务、分期、期限和条款。</label><div class="supply-actions"><button class="primary" :disabled="locked||!isBuyer||!acceptConfirmed||detail.current_status!=='APPROVED'||Date.parse(detail.data.expires_at)<=now" @click="accept">确认报价并建立订单</button><RouterLink v-if="detail.data.order_id" class="button-link outline" :to="`/trade/orders/${detail.data.order_id}`">查看已有订单</RouterLink><RouterLink class="button-link outline" to="/trade/quotes">返回记录</RouterLink></div><p class="muted">原样确认当前内容指纹。建立订单只保存合同，支付另行办理。</p></section>
 <section v-if="!reviewer&&detail.kind==='ORDER'" class="supply-card"><h2>订单后续办理</h2><div class="supply-actions"><RouterLink to="/trade/payments" class="button-link primary">查看付款与退款</RouterLink><RouterLink to="/trade/payments/new" class="button-link outline">建立本期付款记录</RouterLink><RouterLink to="/licensing/reservations" class="button-link outline">办理独立许可核验</RouterLink><RouterLink v-if="detail.data.quote.commercial" :to="`/gigs/offers/${detail.data.quote.commercial.offer_id}`" class="button-link outline">查看原商单与佣金约定</RouterLink><RouterLink v-if="detail.data.quote.commercial" to="/gigs/commissions" class="button-link outline">读取商业佣金计提</RouterLink><button disabled>制作交付尚未开放</button><button disabled>订单留言尚未开放</button></div><p class="muted">付款不会自动发放许可，签署、身份和权属核验仍单独办理。</p><h3>已关联付款记录</h3><p v-if="!related.length" class="muted">没有已加载的关联付款。</p><div v-for="p in related" :key="p.id" class="trade-row"><RouterLink :to="`/trade/payments/${p.id}`" class="button-link table-link">{{p.id}} · {{tradeStatus(p)}}</RouterLink></div><form @submit.prevent="cancel"><label>取消理由<textarea v-model="cancelReason" maxlength="2000" :disabled="locked||detail.current_status!=='OPEN'" placeholder="待填写"></textarea></label><button class="outline danger" :disabled="locked||detail.current_status!=='OPEN'||!cancelReason.trim()||detail.data.financial.received_minor!==0||related.some(p=>['CREATED','SUBMITTING','PENDING','UNKNOWN','SUCCEEDED','REVIEW_REQUIRED'].includes(p.current_status))">取消未付款订单</button><p class="muted">存在付款处理中、待核实或已收款时不能取消，服务器会再次检查。</p></form></section>
 <section v-if="!reviewer&&detail.kind==='PAYMENT'" class="supply-card"><h2>渠道返回入口与核实</h2><label v-if="detail.data.provider==='APPLE'">Apple 实际交易编号 *<input v-model="appleTransaction" maxlength="128" placeholder="使用实际交易编号核对"></label><p v-else class="muted">支付宝核实时交易编号按接口留空。</p><div class="supply-actions"><button class="primary" :disabled="locked||!isBuyer||detail.data.provider==='APPLE'&&!appleTransaction.trim()" @click="reconcilePayment">核实支付结果</button><RouterLink class="button-link outline" to="/trade/refunds/new">申请退款</RouterLink><RouterLink v-if="detail.order_id" class="button-link outline" :to="`/trade/orders/${detail.order_id}`">返回原订单</RouterLink></div><h3>本付款已有退款</h3><p v-if="!related.length" class="muted">尚无已加载的退款记录。</p><RouterLink v-for="r in related" :key="r.id" :to="`/trade/refunds/${r.id}`" class="button-link outline">{{r.id}} · {{tradeStatus(r)}}</RouterLink></section>
</TradeRecordPanel></div>
 <section v-if="reviewer&&['SPEC','QUOTE','REFUND','LEGACY'].includes(detail.kind)" class="supply-card trade-review-form"><h2>独立审核意见</h2><form @submit.prevent="review"><fieldset :disabled="locked||!reviewable"><div class="trade-fields two"><label>本次决定 *<select v-model="decision" data-testid="trade-review-decision" required><option value="">待选择</option><option value="APPROVED">批准</option><option value="REJECTED">拒绝</option></select></label><label>本次理由 *<textarea v-model="reason" data-testid="trade-review-reason" maxlength="2000" required placeholder="待填写"></textarea></label></div><button class="primary" :disabled="locked||!reviewable||!decision||!reason.trim()">提交独立审核</button></fieldset></form><p v-if="detail.created_by===session.account?.id" class="muted">创建者不可审核自己提交的记录。</p><p v-if="detail.kind==='REFUND'" class="muted">读取、审核与执行退款另需退款权限。批准尚不表示退款。</p></section></div>
 <section v-if="!reviewer&&detail.kind==='SPEC'" class="supply-card"><RouterLink :to="`/trade/specifications/${detail.id}/new`" class="button-link primary">创建新的规格版本</RouterLink></section>
 <section v-if="detail.kind==='REFUND'" class="supply-card"><h2>执行及即时返回</h2><template v-if="reviewer"><label class="trade-check"><input v-model="executionConfirmed" type="checkbox" :disabled="locked||detail.current_status!=='APPROVED'">我已核对已批准的原退款明细，确认执行。</label><button class="primary" :disabled="locked||detail.current_status!=='APPROVED'||!executionConfirmed" @click="executeRefund">执行已审退款</button></template><button v-else class="primary" :disabled="locked" @click="reconcileRefund">核实已有退款结果</button><p class="muted">等待 Apple 申请、提交中、待核实与实际退款分别展示。核实以服务器结果为准。</p></section>
 <section v-if="reviewer&&detail.kind==='LEGACY'" class="supply-card"><h2>私有原单材料</h2><button class="outline" :disabled="locked" @click="ui.downloadLegacy(detail.id,detail.data.evidence_asset_id)">下载本单私有原始材料</button></section>
 <div class="trade-footer"><RouterLink :to="`/trade/${reviewer?'reviews/':''}${section}`" class="button-link outline">返回记录列表</RouterLink></div>
 </template><p v-else class="supply-empty">未读取到当前记录，请核对权限与记录编号。</p>
 </div></main></div></div>
</template>
