 'use strict';
const {id,error}=require('../party/policy'),{digest}=require('../governance/content');
const {coversConsent}=require('../works/consent-policy');
const one=async(tx,sql,args=[])=>(await tx.execute(sql,args))[0][0];
function checked(row){if(!row)throw error('PROJECT_NOT_FOUND',404);const data=typeof row.data_json==='string'?JSON.parse(row.data_json):row.data_json;if(digest(data)!==row.data_sha256)throw error('STORED_CONTENT_MISMATCH',503);return {...row,data};}
function dto(row){const r=checked(row);return {id:r.id,kind:r.kind,project_id:r.project_id,owner_party_id:r.owner_party_id,created_by:r.created_by,current_status:r.current_status,object_version:r.object_version,content_sha256:r.data_sha256,data:r.data};}
async function load(tx,key,kind,lock='FOR UPDATE'){const r=dto(await one(tx,'SELECT * FROM project_records WHERE id=? '+lock,[id(key)]));if(kind&&r.kind!==kind)throw error('PROJECT_NOT_FOUND',404);return r;}
async function active(tx,party){const r=await one(tx,'SELECT * FROM parties WHERE id=? FOR SHARE',[id(party)]);if(!r||['CLOSED','SUSPENDED'].includes(r.current_status))throw error('PROJECT_PARTY_NOT_ACTIVE',409);return r;}
async function candidateScope(tx,c,p){await active(tx,c.owner_party_id);const avatar=checked(await one(tx,"SELECT * FROM supply_records WHERE id=? AND kind='AVATAR' FOR SHARE",[id(c.data.avatar_id)]));if(avatar.owner_party_id!==c.owner_party_id||avatar.current_status!=='RECORDED')throw error('CAST_AVATAR_MISMATCH',409);const consent=checked(await one(tx,"SELECT * FROM supply_records WHERE id=? AND kind='CONSENT' FOR SHARE",[id(c.data.consent_id)])),scope=p.data.scope,now=new Date().toISOString();if(consent.data.consent.avatar_id!==avatar.id||consent.data.consent.valid_until<scope.valid_until||!consent.data.consent.features.every(feature=>coversConsent(consent,{feature,purpose:scope.purpose,territory:scope.territory},now)))throw error('CAST_CONSENT_NOT_AVAILABLE',409);return consent.data.consent.subject_party_id;}
async function roster(tx,p){const [roles]=await tx.execute("SELECT * FROM project_records WHERE project_id=? AND kind='ROLE' ORDER BY id FOR SHARE",[p.id]);if(!roles.length)throw error('CAST_INCOMPLETE',409);const [rows]=await tx.execute("SELECT * FROM project_records WHERE project_id=? AND kind='CANDIDATE' AND current_status='CONFIRMED' ORDER BY id FOR SHARE",[p.id]);const candidates=rows.map(dto);for(const role of roles.map(dto))if(candidates.filter(c=>c.data.role_id===role.id).length!==role.data.capacity)throw error('CAST_INCOMPLETE',409);for(const c of candidates)await candidateScope(tx,c,p);return candidates;}
const rosterHash=rows=>digest(rows.map(r=>({id:r.id,object_version:r.object_version,content_sha256:r.content_sha256})));
async function evidence(tx,key,owner){const r=await one(tx,'SELECT * FROM supply_assets WHERE id=? FOR SHARE',[id(key)]);if(!r||r.owner_party_id!==owner||r.current_status!=='READY'||!['RIGHTS_EVIDENCE','REVIEW_EVIDENCE','CONSENT_EVIDENCE'].includes(r.purpose))throw error('PROJECT_EVIDENCE_REQUIRED',409);return r;}
async function source(tx,p,plan,{finalId=null}={}){
 const pr=checked(await one(tx,"SELECT * FROM production_records WHERE id=? AND kind='PROJECT' FOR SHARE",[plan.data.production_project_id]));if(pr.data.buyer_party_id!==p.owner_party_id)throw error('PRODUCTION_PROJECT_MISMATCH',409);
 const order=await require('../production/eligibility').productionUsable(tx,pr);

 // A new cast consent may grant release rights while the original private production consent stays unchanged.
 const [castRows]=await tx.execute("SELECT * FROM project_records WHERE project_id=? AND kind='CANDIDATE' AND current_status='CONFIRMED' FOR SHARE",[p.id]);
 for(const key of pr.data.consent_ids){const original=checked(await one(tx,"SELECT * FROM supply_records WHERE id=? AND kind='CONSENT' FOR SHARE",[key])),candidates=[original];for(const row of castRows.map(dto)){if(row.data.avatar_id===original.data.consent.avatar_id)candidates.push(checked(await one(tx,"SELECT * FROM supply_records WHERE id=? AND kind='CONSENT' FOR SHARE",[row.data.consent_id])));}if(!candidates.some(c=>c.data.consent.subject_party_id===original.data.consent.subject_party_id&&plan.data.confirmers.some(x=>x.party_id===c.data.consent.subject_party_id)&&c.data.consent.valid_until>=p.data.scope.valid_until&&original.data.consent.features.every(feature=>coversConsent(c,{feature,purpose:p.data.scope.purpose,territory:p.data.scope.territory},new Date().toISOString()))))throw error('SOURCE_RELEASE_CONSENT_REQUIRED',409);}

 const work=checked(await one(tx,"SELECT * FROM supply_records WHERE id=? AND kind='WORK_VERSION' FOR SHARE",[pr.data.script_version_id])),content=work.data.version.content;
 if(content.kind==='PROJECT_ADAPTATION'){
  const [rows]=await tx.execute("SELECT g.* FROM license_records b JOIN license_records g ON g.id=b.parent_id WHERE b.kind='BINDING' AND b.current_status='ACTIVE' AND b.counterparty_id=? AND JSON_UNQUOTE(JSON_EXTRACT(b.data_json,'$.project_id'))=? FOR SHARE",[p.owner_party_id,pr.data.license_project_id]);let usable=false;
  for(const row of rows){const g=checked(row),t=g.data.terms,now=new Date().toISOString();if(g.current_status==='ACTIVE'&&g.data.work_version_id===content.source_version_id&&t.rights.includes('DISTRIBUTE')&&t.purposes.includes(p.data.scope.purpose)&&(t.territories.includes('WORLD')||t.territories.includes(p.data.scope.territory))&&(t.languages.includes('ALL')||t.languages.includes(p.data.scope.language))&&t.valid_from<=now&&now<t.valid_until&&t.valid_until>=p.data.scope.valid_until&&await require('../trade/license-gate').licensePaymentUsable(tx,g.parent_id))usable=true;}
  if(!usable)throw error('DISTRIBUTION_LICENSE_REQUIRED',409);
 }
 if(finalId){const v=checked(await one(tx,"SELECT * FROM production_records WHERE id=? AND kind='VERSION' FOR SHARE",[id(finalId)]));if(v.project_id!==pr.id||v.data.stage!=='FINAL'||v.current_status!=='APPROVED'||pr.data.current.FINAL!==v.id||pr.data.accepted.FINAL!==v.id||pr.current_status!=='ACCEPTED'||order.current_status!=='PAID')throw error('FINAL_DELIVERY_NOT_ACCEPTED_PAID',409);return v;}
 return pr;
}
async function planUsable(tx,p,plan){if(p.current_status==='CANCELLED'||p.data.scope.valid_until<=new Date().toISOString())throw error('PROJECT_NOT_USABLE',409);await active(tx,p.owner_party_id);if(plan.kind!=='PLAN'||p.data.current_plan_id!==plan.id)throw error('PROJECT_VERSION_SUPERSEDED',409);const cast=await roster(tx,p);if(rosterHash(cast)!==plan.data.roster_sha256)throw error('CAST_CHANGED_RECONFIRM_REQUIRED',409);await source(tx,p,plan);for(const signer of plan.data.confirmers)await active(tx,signer.party_id);for(const r of plan.data.rights){await active(tx,r.holder_party_id);await evidence(tx,r.evidence_asset_id,p.owner_party_id);if(r.valid_until<=new Date().toISOString())throw error('PROJECT_RIGHTS_EXPIRED',409);}if(plan.data.funding.some(f=>!cast.some(c=>c.id===f.candidate_id&&c.data.amount_minor>0)))throw error('INVALID_CAST_FUNDING',409);for(const c of cast){if(c.data.amount_minor===0)continue;const f=plan.data.funding.find(x=>x.candidate_id===c.id);if(!f)throw error('CAST_FUNDING_REQUIRED',409);const order=checked(await one(tx,"SELECT * FROM trade_records WHERE id=? AND kind='ORDER' FOR SHARE",[id(f.order_id)])),line=order.data.quote.lines.find(x=>x.line_id===f.line_id);if(order.buyer_party_id!==p.owner_party_id||order.current_status!=='PAID'||order.data.financial.refunded_minor||!line||line.line_kind!=='OTHER'||line.provider_party_id!==c.owner_party_id||line.total_minor!==c.data.amount_minor)throw error('CAST_FUNDING_NOT_VERIFIED',409);const used=await one(tx,'SELECT candidate_id FROM project_funding WHERE order_id=? AND line_id=?',[f.order_id,f.line_id]);if(used&&used.candidate_id!==c.id)throw error('FUNDING_ALREADY_ASSIGNED',409);}
 return cast;
}
async function allConfirmed(tx,r){const rows=(await tx.execute('SELECT party_id,decision,content_sha256 FROM project_confirmations WHERE record_id=?',[r.id]))[0];for(const x of r.data.confirmers)if(!rows.some(c=>c.party_id===x.party_id&&c.decision==='APPROVED'&&c.content_sha256===r.content_sha256))throw error('PROJECT_CONFIRMATIONS_REQUIRED',409);}
async function editionUsable(tx,p,edition){if(edition.kind!=='EDITION'||edition.current_status!=='APPROVED'||p.data.current_edition_id!==edition.id)throw error('PROJECT_VERSION_SUPERSEDED',409);const plan=await load(tx,edition.data.plan_id,'PLAN','FOR SHARE');await planUsable(tx,p,plan);if(plan.current_status!=='APPROVED')throw error('PROJECT_PLAN_NOT_APPROVED',409);await allConfirmed(tx,plan);const final=await source(tx,p,plan,{finalId:edition.data.final_version_id});if(digest(final.data)!==edition.data.final_content_sha256)throw error('FINAL_VERSION_CHANGED',409);return plan;}
module.exports={one,checked,dto,load,active,candidateScope,roster,rosterHash,evidence,source,planUsable,allConfirmed,editionUsable};
