 'use strict';
const {id,label,shape,error}=require('../party/policy');
const {copy,amount,instant}=require('../trade/policy');
const LAYERS=['FACE_VOICE','ORIGINAL','SCRIPT','MUSIC','ADAPTATION','FINAL'];
function scope(v){shape(v,['purpose','territory','language','valid_until']);if(!['PUBLIC_SHARE','RELEASE'].includes(v.purpose)||! /^[A-Z]{2}$/.test(v.territory)||! /^[a-z]{2}$/.test(v.language))throw error('INVALID_RELEASE_SCOPE',400);instant(v.valid_until);if(Date.parse(v.valid_until)<=Date.now())throw error('RELEASE_SCOPE_EXPIRED',409);return copy(v);}
function signers(list){if(!Array.isArray(list)||!list.length||list.length>50)throw error('CONFIRMERS_REQUIRED',400);const keys=new Set();for(const x of list){shape(x,['party_id','responsibility','after_party_ids']);id(x.party_id);label(x.responsibility,1000);if(keys.has(x.party_id)||!Array.isArray(x.after_party_ids)||x.after_party_ids.length>50||new Set(x.after_party_ids).size!==x.after_party_ids.length)throw error('INVALID_CONFIRMERS',400);keys.add(x.party_id);}const done=new Set(),visiting=new Set();function visit(k){if(done.has(k))return;if(visiting.has(k))throw error('CONFIRMATION_CYCLE',400);const row=list.find(x=>x.party_id===k);if(!row)throw error('UNKNOWN_CONFIRMATION_DEPENDENCY',400);visiting.add(k);row.after_party_ids.forEach(visit);visiting.delete(k);done.add(k);}keys.forEach(visit);return copy(list);}
function rights(list,target){if(!Array.isArray(list)||list.length!==LAYERS.length||new Set(list.map(x=>x.layer)).size!==LAYERS.length)throw error('RIGHTS_LAYERS_REQUIRED',400);for(const x of list){shape(x,['layer','holder_party_id','evidence_asset_id','purpose','territory','valid_until','terms']);if(!LAYERS.includes(x.layer)||x.purpose!==target.purpose||x.territory!==target.territory)throw error('RIGHTS_SCOPE_MISMATCH',409);id(x.holder_party_id);id(x.evidence_asset_id);instant(x.valid_until);if(x.valid_until<target.valid_until)throw error('RIGHTS_PERIOD_TOO_SHORT',409);label(x.terms,8000);}return copy(list);}
function slotAvailable(candidates,capacity){return candidates.filter(x=>['SELECTED','CONFIRMED'].includes(x.current_status)).length<capacity;}
module.exports={copy,amount,instant,scope,signers,rights,slotAvailable,LAYERS};
