 'use strict';
const {id,label,shape,error}=require('../party/policy');
const P=require('./policy'),C=require('./checks'),{load,one}=C;
const APPROVAL_CHECKS={PLAN:['identity_verified','signatures_verified','rights_verified','production_verified'],EDITION:['rights_verified','content_verified','credits_verified','materials_verified'],CHANNEL:['channel_verified','requirements_verified'],RELEASE:['rights_verified','materials_verified','channel_verified'],EXTERNAL_EVENT:['source_verified','reference_verified','outcome_verified']};
function methods(H){const {db,actor,owner,operator,access,sponsor,insert,save,command,mutate,asSponsor}=H;
 async function releaseUsable(tx,p,r){if(r.kind!=='RELEASE')throw error('PROJECT_NOT_FOUND',404);const edition=await load(tx,r.data.edition_id,'EDITION','FOR SHARE');await C.editionUsable(tx,p,edition);await C.allConfirmed(tx,edition);const channel=await load(tx,r.data.channel_id,'CHANNEL','FOR SHARE');if(channel.current_status!=='APPROVED')throw error('CHANNEL_NOT_APPROVED',409);for(const key of r.data.material_asset_ids)await C.evidence(tx,key,p.owner_party_id);return edition;}
 return {
 async channel(ctx,i){shape(i,['party_id','name','channel_reference','submission_requirements','evidence_asset_id','operation_key']);label(i.name,200);label(i.channel_reference,1000);label(i.submission_requirements,8000);return db.withTransaction(async tx=>{const a=await actor(tx,ctx);await owner(tx,a,i.party_id);await operator(tx,a,null,null);await C.evidence(tx,i.evidence_asset_id,i.party_id);return command(tx,a,'CHANNEL',i,()=>insert(tx,a,'CHANNEL',null,i.party_id,'IN_REVIEW',{name:i.name,channel_reference:i.channel_reference,submission_requirements:i.submission_requirements,evidence_asset_id:id(i.evidence_asset_id),review:null}));});},
 async review(ctx,i){shape(i,['record_id','expected_version','decision','reason','verification','operation_key']);label(i.reason,4000);if(!['APPROVED','CHANGES_REQUESTED','REJECTED'].includes(i.decision))throw error('INVALID_REVIEW',400);return mutate(ctx,i,'REVIEW',(tx,a,p,r)=>operator(tx,a,p,r,true),async(tx,a,p,r)=>{const fields=APPROVAL_CHECKS[r.kind];if(!fields||!['IN_REVIEW','INTERNAL_PENDING'].includes(r.current_status))throw error('REVIEW_NOT_PENDING',409);shape(i.verification,fields);if(i.decision==='APPROVED'&&fields.some(k=>i.verification[k]!==true))throw error('MANUAL_VERIFICATION_REQUIRED',409);
 let status=i.decision;
 if(i.decision==='APPROVED'){
  if(r.kind==='PLAN')await C.planUsable(tx,p,r);
  if(r.kind==='EDITION'){if(p.data.current_edition_id!==r.id)throw error('PROJECT_VERSION_SUPERSEDED',409);await C.editionUsable(tx,p,{...r,current_status:'APPROVED'});}
  if(r.kind==='CHANNEL')await C.evidence(tx,r.data.evidence_asset_id,r.owner_party_id);
  if(r.kind==='RELEASE'){await releaseUsable(tx,p,r);status='READY_TO_SUBMIT';}
  if(r.kind==='EXTERNAL_EVENT'){const release=await load(tx,r.data.release_id,'RELEASE');const transitions={SUBMITTED:['READY_TO_SUBMIT','EXTERNAL_SUBMITTED'],CHANGES_REQUESTED:['EXTERNAL_SUBMITTED','EXTERNAL_CHANGES_REQUESTED'],REJECTED:['EXTERNAL_SUBMITTED','EXTERNAL_REJECTED'],PUBLISHED:['EXTERNAL_SUBMITTED','EXTERNAL_PUBLISHED'],WITHDRAWN:['EXTERNAL_PUBLISHED','EXTERNAL_WITHDRAWN']},pair=transitions[r.data.outcome];if(release.current_status!==pair[0])throw error('EXTERNAL_TRANSITION_INVALID',409);if(r.data.outcome!=='WITHDRAWN')await releaseUsable(tx,p,release);await C.evidence(tx,r.data.evidence_asset_id,p.owner_party_id);await save(tx,a,release,pair[1],{...release.data,last_external_event_id:r.id},'EXTERNAL_RESULT_VERIFIED');}
 }
 return save(tx,a,r,status,{...r.data,review:{decision:i.decision,reason:i.reason,verification:i.verification,reviewer_account_id:a.id,method:'MANUAL_EVIDENCE_REVIEW'}},'INDEPENDENT_REVIEW');});},
 async submitRelease(ctx,i){shape(i,['record_id','party_id','expected_version','channel_id','prior_release_id','material_asset_ids','note','operation_key']);label(i.note,2000);if(!Array.isArray(i.material_asset_ids)||!i.material_asset_ids.length||i.material_asset_ids.length>30)throw error('RELEASE_MATERIAL_REQUIRED',400);return mutate(ctx,i,'RELEASE',asSponsor,async(tx,a,p,r)=>{if(r.kind!=='PROJECT'||p.current_status!=='STARTED')throw error('PROJECT_NOT_STARTED',409);if(i.prior_release_id){const old=await load(tx,i.prior_release_id,'RELEASE');if(old.project_id!==p.id||old.data.channel_id!==i.channel_id||!['CHANGES_REQUESTED','REJECTED','EXTERNAL_CHANGES_REQUESTED','EXTERNAL_REJECTED','EXTERNAL_WITHDRAWN'].includes(old.current_status))throw error('INVALID_RELEASE_PREDECESSOR',409);}
 const [attempts]=await tx.execute("SELECT * FROM project_records WHERE project_id=? AND kind='RELEASE' AND JSON_UNQUOTE(JSON_EXTRACT(data_json,'$.channel_id'))=? FOR SHARE",[p.id,id(i.channel_id)]);if(attempts.some(x=>['INTERNAL_PENDING','READY_TO_SUBMIT','EXTERNAL_SUBMITTED','EXTERNAL_PUBLISHED'].includes(x.current_status)))throw error('RELEASE_ALREADY_PENDING',409);if(attempts.length&&!i.prior_release_id)throw error('RELEASE_PREDECESSOR_REQUIRED',409);if(i.prior_release_id&&attempts.some(x=>C.dto(x).data.prior_release_id===i.prior_release_id))throw error('RELEASE_PREDECESSOR_USED',409);
 const created=await insert(tx,a,'RELEASE',p.id,p.owner_party_id,'INTERNAL_PENDING',{edition_id:p.data.current_edition_id,channel_id:id(i.channel_id),prior_release_id:i.prior_release_id||null,material_asset_ids:i.material_asset_ids,note:i.note,review:null,last_external_event_id:null});await releaseUsable(tx,p,created);await save(tx,a,p,p.current_status,p.data,'RELEASE_SUBMITTED_FOR_REVIEW');return created;});},
 async reportExternal(ctx,i){shape(i,['record_id','party_id','expected_version','outcome','external_reference','occurred_at','evidence_asset_id','note','operation_key']);label(i.external_reference,1000);label(i.note,4000);if(!['SUBMITTED','CHANGES_REQUESTED','REJECTED','PUBLISHED','WITHDRAWN'].includes(i.outcome))throw error('INVALID_EXTERNAL_OUTCOME',400);P.instant(i.occurred_at);if(i.occurred_at>new Date().toISOString())throw error('EXTERNAL_EVENT_IN_FUTURE',400);return mutate(ctx,i,'EXTERNAL_EVENT',async(tx,a,p,r)=>{await owner(tx,a,i.party_id);if(!p||p.owner_party_id!==i.party_id)throw error('PROJECT_PARTY_FORBIDDEN');},async(tx,a,p,r)=>{if(r.kind!=='RELEASE')throw error('PROJECT_NOT_FOUND',404);await C.evidence(tx,i.evidence_asset_id,p.owner_party_id);return insert(tx,a,'EXTERNAL_EVENT',p.id,p.owner_party_id,'IN_REVIEW',{release_id:r.id,outcome:i.outcome,external_reference:i.external_reference,occurred_at:i.occurred_at,evidence_asset_id:id(i.evidence_asset_id),note:i.note,review:null,provenance:'EXTERNAL_MANUAL_EVIDENCE'});});},
 async evidence(ctx,{record_id,asset_id,party_id}){return db.withTransaction(async tx=>{const a=await actor(tx,ctx),r=await load(tx,record_id,null,'FOR SHARE'),p=r.project_id?await load(tx,r.project_id,'PROJECT','FOR SHARE'):null;if(party_id){await owner(tx,a,party_id);if(party_id!==(p?.owner_party_id||r.owner_party_id))throw error('PROJECT_EVIDENCE_FORBIDDEN');}else await operator(tx,a,p,r);const keys=[r.data.evidence_asset_id,...(r.data.material_asset_ids||[]),...(r.data.rights||[]).map(x=>x.evidence_asset_id)];if(!keys.includes(id(asset_id)))throw error('PROJECT_NOT_FOUND',404);return C.evidence(tx,asset_id,p?.owner_party_id||r.owner_party_id);});}
 };
}
module.exports={methods,APPROVAL_CHECKS};
