CREATE TABLE party_capabilities (
 party_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 code ENUM('AUTHOR','SCRIPT_SUPPLIER','PRODUCER','MCN','BRAND_CLIENT') NOT NULL,
 current_status ENUM('PENDING_REVIEW','ACTIVE','SUSPENDED') NOT NULL DEFAULT 'PENDING_REVIEW',
 object_version INT UNSIGNED NOT NULL DEFAULT 1,
 created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 PRIMARY KEY(party_id,code),
 FOREIGN KEY(party_id) REFERENCES parties(id),
 CONSTRAINT capability_version CHECK(object_version > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin
