CREATE TABLE supply_assets (
 id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,
 owner_party_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 created_by CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 operation_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL UNIQUE,
 object_key VARCHAR(512) CHARACTER SET ascii COLLATE ascii_bin NOT NULL UNIQUE,
 purpose ENUM('WORK_CONTENT','RIGHTS_EVIDENCE','CONSENT_EVIDENCE','REVIEW_EVIDENCE','AVATAR_MATERIAL') NOT NULL,
 media_type VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 byte_size INT UNSIGNED NOT NULL,
 content_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 current_status ENUM('UPLOADING','READY','FAILED') NOT NULL DEFAULT 'UPLOADING',
 created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 FOREIGN KEY(owner_party_id) REFERENCES parties(id),
 FOREIGN KEY(created_by) REFERENCES identity_accounts(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin
