CREATE TABLE ops_commands (
id CHAR(64) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,
fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, result_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin
