CREATE TABLE legacy_imports (
 id CHAR(64) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,
 source_ref VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 source_kind ENUM('SYNTHETIC','SANITIZED_COPY') NOT NULL,
 source_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 content_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 manifest_json JSON NOT NULL,
 current_status ENUM('RETAINED_REVIEW_REQUIRED') NOT NULL DEFAULT 'RETAINED_REVIEW_REQUIRED',
 created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 UNIQUE KEY legacy_source(source_ref,source_sha256)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin
