 'use strict';
const {randomUUID}=require('node:crypto');
const {id,ref,label,shape,version,error}=require('../party/policy');
const {canonical,digest,sealUnsignedContent,verifyUnsignedContent}=require('../governance/content');
const {authorizeOperator}=require('../governance/operator-access');
const policy=require('./policy');
const one=async(tx,sql,args=[]) => (await tx.execute(sql,args))[0][0];
const parsed=x=>typeof x==='string'?JSON.parse(x):x;
function record(row){if(!row)throw error('LICENSE_NOT_FOUND',404);const body=parsed(row.data_json);if(digest(body)!==row.data_sha256)throw error('STORED_CONTENT_MISMATCH',503);return {id:row.id,kind:row.kind,owner_party_id:row.owner_party_id,counterparty_id:row.counterparty_id,work_id:row.work_id,parent_id:row.parent_id,created_by:row.created_by,current_status:row.current_status,object_version:row.object_version,data:body};}
async function lockWork(tx,work){await tx.execute('INSERT INTO license_work_locks(work_id) VALUES (?) ON DUPLICATE KEY UPDATE work_id=VALUES(work_id)',[id(work)]);await one(tx,'SELECT work_id FROM license_work_locks WHERE work_id=? FOR UPDATE',[work]);}
async function clock(tx){const row=await one(tx,'SELECT ROUND(UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000) AS ms');return Number(row.ms);}
async function validBinding(tx,{party_id,source,project_id}){
 const now=await clock(tx);const project=await one(tx,"SELECT * FROM license_records WHERE id=? AND kind='PROJECT' FOR SHARE",[project_id]);if(!project||project.owner_party_id!==party_id||project.current_status!=='ACTIVE')return false;
 const [rows]=await tx.execute("SELECT g.* FROM license_records b JOIN license_records g ON g.id=b.parent_id WHERE b.kind='BINDING' AND b.counterparty_id=? AND b.current_status='ACTIVE' AND JSON_UNQUOTE(JSON_EXTRACT(b.data_json,'$.project_id'))=? FOR SHARE",[party_id,project_id]);
 return rows.some(raw=>{const g=record(raw);return g.current_status==='ACTIVE'&&g.data.work_version_id===source.id&&g.data.terms.rights.includes('ADAPT')&&policy.projectScope(g.data.terms,record(project).data,now);});
}
function createLicensingRepository(db,{resolvePrincipal=async()=>null}={}){
 async function actor(tx,ctx){const principal=await resolvePrincipal(ctx);if(!principal)throw error('AUTHENTICATION_REQUIRED',401);const a=await one(tx,'SELECT * FROM identity_accounts WHERE subject_ref=? FOR SHARE',[ref(principal.subject_ref)]);if(!a||a.current_status!=='ACTIVE')throw error('ACCOUNT_NOT_ACTIVE');return {...a,request_id:ref(principal.request_id||randomUUID())};}
 async function owner(tx,a,partyId){const p=await one(tx,'SELECT * FROM parties WHERE id=? FOR SHARE',[id(partyId)]),m=await one(tx,'SELECT * FROM party_memberships WHERE party_id=? AND account_id=? FOR SHARE',[partyId,a.id]);if(!p||['SUSPENDED','CLOSED'].includes(p.current_status)||!m||m.current_status!=='ACTIVE'||m.role_code!=='OWNER')throw error('LICENSE_PARTY_FORBIDDEN');}
 async function reviewer(tx,a,r){if(!await authorizeOperator(tx,{account_id:a.id,action:'LICENSE_REVIEW'}))throw error('LICENSE_REVIEW_FORBIDDEN');if(r&&(r.kind!=='GRANT'&&r.created_by===a.id||await one(tx,"SELECT id FROM party_memberships WHERE account_id=? AND current_status='ACTIVE' AND party_id IN (?,?)",[a.id,r.owner_party_id,r.counterparty_id])))throw error('SELF_REVIEW_FORBIDDEN');}
 async function load(tx,recordId,kind,lock='FOR UPDATE'){const r=record(await one(tx,'SELECT * FROM license_records WHERE id=? '+lock,[id(recordId)]));if(kind&&r.kind!==kind)throw error('LICENSE_NOT_FOUND',404);return r;}
 async function audit(tx,a,r,event){await tx.execute('INSERT INTO license_audit(id,record_id,actor_account_id,event_code,object_version,data_sha256,request_id) VALUES (?,?,?,?,?,?,?)',[randomUUID(),r.id,a.id,event,r.object_version,digest(r.data),a.request_id]);}
 async function insert(tx,a,kind,ownerParty,other,work,parent,status,data,recordId=randomUUID()){
 const r={id:recordId,kind,owner_party_id:ownerParty,counterparty_id:other,work_id:work,parent_id:parent,created_by:a.id,current_status:status,object_version:1,data};await tx.execute('INSERT INTO license_records(id,kind,owner_party_id,counterparty_id,work_id,parent_id,created_by,current_status,data_json,data_sha256) VALUES (?,?,?,?,?,?,?,?,?,?)',[r.id,kind,ownerParty,other,work,parent,a.id,status,JSON.stringify(data),digest(data)]);await audit(tx,a,r,kind+'_CREATED');return r;}
 async function save(tx,a,r,status,data,event){const next={...r,current_status:status,object_version:r.object_version+1,data};await tx.execute('UPDATE license_records SET current_status=?,object_version=?,data_json=?,data_sha256=? WHERE id=?',[status,next.object_version,JSON.stringify(data),digest(data),r.id]);await audit(tx,a,next,event);return next;}
 const match=(r,v)=>{if(r.object_version!==version(v))throw error('VERSION_CONFLICT',412);};
 async function command(tx,a,op,input,work){const key=digest([a.id,op,ref(input.operation_key)]),fingerprint=digest(input);try{await tx.execute('INSERT INTO license_commands(id,fingerprint) VALUES (?,?)',[key,fingerprint]);}catch(e){if(e.code!=='ER_DUP_ENTRY')throw e;const row=await one(tx,'SELECT * FROM license_commands WHERE id=?',[key]);if(row.fingerprint!==fingerprint)throw error('IDEMPOTENCY_CONFLICT',409);if(!row.result_json)throw error('IDEMPOTENCY_IN_PROGRESS',409);return parsed(row.result_json);}const result=await work();await tx.execute('UPDATE license_commands SET result_json=? WHERE id=?',[JSON.stringify(result),key]);return result;}
 async function work(tx,versionId){const r=await one(tx,"SELECT * FROM supply_records WHERE id=? AND kind='WORK_VERSION' FOR SHARE",[id(versionId)]);if(!r||r.current_status!=='REVIEWS_COMPLETE')throw error('WORK_NOT_APPROVED',409);const supplier=await one(tx,"SELECT p.current_status,(SELECT s.current_status FROM supply_records s WHERE s.kind='PROFILE' AND s.owner_party_id=p.id ORDER BY s.revision DESC LIMIT 1) supply_status FROM parties p WHERE p.id=? FOR SHARE",[r.owner_party_id]);if(!supplier||['SUSPENDED','CLOSED'].includes(supplier.current_status)||supplier.supply_status!=='APPROVED')throw error('SUPPLIER_NOT_APPROVED',409);const d=parsed(r.data_json);if(digest(d)!==r.data_sha256||d.version.content.id!==r.id||d.version.content.work_id!==r.stream_ref||d.version.content.kind!=='ORIGINAL')throw error('WORK_NOT_USABLE',409);return {...r,data:d};}
 async function asset(tx,assetId,parties){const r=await one(tx,'SELECT * FROM supply_assets WHERE id=? FOR SHARE',[id(assetId)]);if(!r||r.current_status!=='READY'||!parties.includes(r.owner_party_id)||!['RIGHTS_EVIDENCE','REVIEW_EVIDENCE'].includes(r.purpose))throw error('EVIDENCE_NOT_READY',409);return r;}
 async function overlap(tx,workId,terms,now,exclude){const [rows]=await tx.execute("SELECT * FROM license_records WHERE work_id=? AND kind IN ('RESERVATION','GRANT') AND current_status IN ('HELD','ACTIVE','SUSPENDED','REVIEW_REQUIRED')",[workId]);for(const raw of rows){const r=record(raw);if(r.id===exclude||r.parent_id===exclude)continue;if(r.kind==='RESERVATION'&&policy.instant(r.data.expires_at)<=now)continue;if(policy.conflict(terms,r.data.terms))throw error('LICENSE_SCOPE_CONFLICT',409);}}
 async function accessible(tx,a,r,partyId){if(partyId){await owner(tx,a,partyId);if([r.owner_party_id,r.counterparty_id].includes(partyId))return;if(r.kind==='PRODUCT'&&r.current_status==='LISTED')return;throw error('LICENSE_NOT_FOUND',404);}await reviewer(tx,a,null);}
 async function mutable(ctx,input,op,kind,auth,fn){input=JSON.parse(canonical(input));return db.withTransaction(async tx=>{const a=await actor(tx,ctx);const initial=await load(tx,input.record_id,kind,'');if(initial.work_id)await lockWork(tx,initial.work_id);const r=await load(tx,input.record_id,kind);await auth(tx,a,r,input);return command(tx,a,op,input,async()=>{match(r,input.expected_version);return fn(tx,a,r,input,await clock(tx));});});}
 const api={
 async read(ctx,{record_id,party_id}){return db.withTransaction(async tx=>{const a=await actor(tx,ctx),r=await load(tx,record_id,null,'FOR SHARE');await accessible(tx,a,r,party_id);return r;});},
 async list(ctx,{kind,party_id,after='',limit=20,catalog=false}){if(!['PRODUCT','RESERVATION','EVIDENCE','GRANT','PROJECT','BINDING','READING'].includes(kind)||!Number.isInteger(limit)||limit<1||limit>100||typeof catalog!=='boolean')throw error('INVALID_LIST',400);if(after)id(after);return db.withTransaction(async tx=>{const a=await actor(tx,ctx);if(party_id)await owner(tx,a,party_id);else await reviewer(tx,a,null);if(catalog&&kind!=='PRODUCT')throw error('INVALID_LIST',400);const [rows]=await tx.execute('SELECT * FROM license_records WHERE kind=? AND id>? '+(catalog?"AND current_status='LISTED' ":party_id?'AND (owner_party_id=? OR counterparty_id=?) ':'')+'ORDER BY id LIMIT ?',[kind,after,...(!catalog&&party_id?[party_id,party_id]:[]),limit+1]);return {items:rows.slice(0,limit).map(record),next_cursor:rows.length>limit?rows[limit-1].id:null};});},
 async createProduct(ctx,input){input=JSON.parse(canonical(input));shape(input,['party_id','work_version_id','previous_product_id','title','preview_text','terms','price','payment_due_minor','reservation_minutes','rule_id','operation_key']);const terms=policy.terms(input.terms),price=policy.price(input.price);label(input.title,200);label(input.preview_text,2000);if(!Number.isSafeInteger(input.payment_due_minor)||input.payment_due_minor<0||input.payment_due_minor>price.amount_minor||!Number.isInteger(input.reservation_minutes)||input.reservation_minutes<1||input.reservation_minutes>10080)throw error('INVALID_PRODUCT_CONDITIONS',400);
 return db.withTransaction(async tx=>{const a=await actor(tx,ctx);await owner(tx,a,input.party_id);const w=await work(tx,input.work_version_id);if(w.owner_party_id!==input.party_id)throw error('LICENSE_PARTY_FORBIDDEN');await lockWork(tx,w.stream_ref);return command(tx,a,'CREATE_PRODUCT',input,async()=>{if(input.previous_product_id!==null){const prev=await load(tx,input.previous_product_id,'PRODUCT');if(prev.owner_party_id!==input.party_id||prev.work_id!==w.stream_ref)throw error('LICENSE_PARTY_FORBIDDEN');}const rule=await one(tx,"SELECT id FROM governance_rules WHERE id=? AND current_status='EFFECTIVE' AND effective_at<=CURRENT_TIMESTAMP(3) FOR SHARE",[id(input.rule_id)]);if(!rule)throw error('RULE_NOT_EFFECTIVE',409);return insert(tx,a,'PRODUCT',input.party_id,null,w.stream_ref,input.previous_product_id,'IN_REVIEW',{work_version_id:w.id,title:input.title,preview_text:input.preview_text,terms,price,payment_due_minor:input.payment_due_minor,reservation_minutes:input.reservation_minutes,rule_id:input.rule_id,review:null});});});},
 async review(ctx,input){shape(input,['record_id','expected_version','decision','reason','verification','operation_key']);if(!['APPROVED','REJECTED'].includes(input.decision))throw error('INVALID_REVIEW',400);label(input.reason,2000);return mutable(ctx,input,'REVIEW',null,(tx,a,r)=>reviewer(tx,a,r),async(tx,a,r,i)=>{if(!['PRODUCT','EVIDENCE','READING'].includes(r.kind)||r.current_status!=='IN_REVIEW')throw error('REVIEW_NOT_PENDING',409);if(r.kind==='PRODUCT')await work(tx,r.data.work_version_id);let verification=null;if(r.kind==='EVIDENCE'&&i.decision==='APPROVED'){const reservation=await load(tx,r.parent_id,'RESERVATION','FOR SHARE'),v=i.verification;shape(v,['signed_contract_sha256','identity_verified','seller_signature_verified','buyer_signature_verified','currency','received_minor','payee_party_id','receipt_ref']);if(v.signed_contract_sha256!==reservation.data.contract.content_sha256||v.identity_verified!==true||v.seller_signature_verified!==true||v.buyer_signature_verified!==true||v.currency!==reservation.data.price.currency||v.payee_party_id!==reservation.counterparty_id||!Number.isSafeInteger(v.received_minor)||v.received_minor<reservation.data.payment_due_minor||v.received_minor>reservation.data.price.amount_minor)throw error('VERIFICATION_MISMATCH',409);if(reservation.data.payment_due_minor>0)ref(v.receipt_ref);else if(v.receipt_ref!==null)ref(v.receipt_ref);verification=v;}else if(i.verification!==undefined&&i.verification!==null)throw error('UNEXPECTED_VERIFICATION',400);const data={...r.data,review:{decision:i.decision,reason:i.reason,reviewer_account_id:a.id,verification}};return save(tx,a,r,i.decision==='REJECTED'?'REJECTED':r.kind==='PRODUCT'?'LISTED':'APPROVED',data,'INDEPENDENT_REVIEW');});},
 async close(ctx,input){shape(input,['record_id','party_id','expected_version','reason','operation_key']);label(input.reason,2000);return mutable(ctx,input,'CLOSE',null,async(tx,a,r,i)=>{await owner(tx,a,i.party_id);if(r.owner_party_id!==i.party_id)throw error('LICENSE_PARTY_FORBIDDEN');},async(tx,a,r,i)=>{if(!['PRODUCT','RESERVATION','READING'].includes(r.kind)||['UNLISTED','CANCELLED','REVOKED','COMMITTED'].includes(r.current_status))throw error('CLOSE_FORBIDDEN',409);return save(tx,a,r,{PRODUCT:'UNLISTED',RESERVATION:'CANCELLED',READING:'REVOKED'}[r.kind],{...r.data,close_reason:i.reason},'CLOSED');});},
 async reserve(ctx,input){input=JSON.parse(canonical(input));shape(input,['party_id','product_id','operation_key']);return db.withTransaction(async tx=>{const a=await actor(tx,ctx);await owner(tx,a,input.party_id);let product=await load(tx,input.product_id,'PRODUCT','');await lockWork(tx,product.work_id);product=await load(tx,input.product_id,'PRODUCT');if(product.owner_party_id===input.party_id)throw error('SELF_PURCHASE_FORBIDDEN',409);return command(tx,a,'RESERVE',input,async()=>{if(product.current_status!=='LISTED')throw error('PRODUCT_NOT_LISTED',409);await work(tx,product.data.work_version_id);const now=await clock(tx);if(now>=policy.instant(product.data.terms.development_until))throw error('LICENSE_PERIOD_ENDED',409);await overlap(tx,product.work_id,product.data.terms,now);const reservationId=randomUUID(),rule=await one(tx,'SELECT * FROM governance_rules WHERE id=? FOR SHARE',[product.data.rule_id]);if(!rule)throw error('RULE_NOT_EFFECTIVE',409);const contract=sealUnsignedContent({id:randomUUID(),contract_version_id:randomUUID(),party_ids:[product.owner_party_id,input.party_id],created_at:new Date(now).toISOString(),rules:[{content:parsed(rule.content_json),current_status:rule.current_status,effective_at:new Date(rule.effective_at.replace(' ','T')+'Z').toISOString()}],commitments:{reservation_id:reservationId,product_id:product.id,product_version:product.object_version,work_version_id:product.data.work_version_id,terms:product.data.terms,price:product.data.price,payment_due_minor:product.data.payment_due_minor}});
 return insert(tx,a,'RESERVATION',input.party_id,product.owner_party_id,product.work_id,product.id,'HELD',{...product.data,contract,expires_at:new Date(now+product.data.reservation_minutes*60000).toISOString()},reservationId);});});},
 async submitEvidence(ctx,input){input=JSON.parse(canonical(input));shape(input,['party_id','reservation_id','contract_sha256','seller_signature_asset_id','buyer_signature_asset_id','identity_asset_id','payment_asset_id','external_reference','operation_key']);ref(input.external_reference);
 return db.withTransaction(async tx=>{const a=await actor(tx,ctx);await owner(tx,a,input.party_id);const r=await load(tx,input.reservation_id,'RESERVATION');if(![r.owner_party_id,r.counterparty_id].includes(input.party_id))throw error('LICENSE_PARTY_FORBIDDEN');return command(tx,a,'EVIDENCE',input,async()=>{verifyUnsignedContent(r.data.contract);if(input.contract_sha256!==r.data.contract.content_sha256)throw error('CONTRACT_MISMATCH',409);for(const k of ['seller_signature_asset_id','buyer_signature_asset_id','identity_asset_id'])await asset(tx,input[k],[r.owner_party_id,r.counterparty_id]);if(r.data.payment_due_minor>0)await asset(tx,input.payment_asset_id,[r.owner_party_id,r.counterparty_id]);else if(input.payment_asset_id!==null)await asset(tx,input.payment_asset_id,[r.owner_party_id,r.counterparty_id]);return insert(tx,a,'EVIDENCE',r.owner_party_id,r.counterparty_id,r.work_id,r.id,'IN_REVIEW',{contract_sha256:input.contract_sha256,seller_signature_asset_id:input.seller_signature_asset_id,buyer_signature_asset_id:input.buyer_signature_asset_id,identity_asset_id:input.identity_asset_id,payment_asset_id:input.payment_asset_id,external_reference:input.external_reference,verification_method:'EXTERNAL_MANUAL_REVIEW',payment_channel_result:'NOT_REPORTED',review:null});});});},
 async activate(ctx,input){shape(input,['record_id','expected_version','evidence_id','reason','operation_key']);label(input.reason,2000);return mutable(ctx,input,'ACTIVATE','RESERVATION',(tx,a,r)=>reviewer(tx,a,r),async(tx,a,r,i,now)=>{if(r.current_status!=='HELD')throw error('RESERVATION_NOT_HELD',409);if(policy.instant(r.data.expires_at)<=now)return save(tx,a,r,'REVIEW_REQUIRED',{...r.data,late_reason:i.reason},'LATE_CONDITIONS');const e=await load(tx,i.evidence_id,'EVIDENCE','FOR SHARE');if(e.parent_id!==r.id||e.current_status!=='APPROVED'||e.data.contract_sha256!==r.data.contract.content_sha256)throw error('LICENSE_CONDITIONS_NOT_VERIFIED',409);verifyUnsignedContent(r.data.contract);await work(tx,r.data.work_version_id);if(now<policy.instant(r.data.terms.valid_from)||now>=policy.instant(r.data.terms.development_until))throw error('LICENSE_PERIOD_NOT_ACTIVE',409);await overlap(tx,r.work_id,r.data.terms,now,r.id);if(r.data.payment_due_minor>0){const v=e.data.review.verification;if(!v)throw error('LICENSE_CONDITIONS_NOT_VERIFIED',409);try{await tx.execute('INSERT INTO license_receipt_uses(payee_party_id,currency,receipt_ref,reservation_id) VALUES (?,?,?,?)',[r.counterparty_id,v.currency,v.receipt_ref,r.id]);}catch(err){if(err.code==='ER_DUP_ENTRY')throw error('RECEIPT_ALREADY_USED',409);throw err;}}const grant=await insert(tx,a,'GRANT',r.owner_party_id,r.counterparty_id,r.work_id,r.id,'ACTIVE',{work_version_id:r.data.work_version_id,terms:r.data.terms,price:r.data.price,contract:r.data.contract,evidence_id:e.id,activated_at:new Date(now).toISOString(),reason:i.reason});await save(tx,a,r,'COMMITTED',{...r.data,grant_id:grant.id},'LICENSE_GRANTED');return grant;});},
 async suspend(ctx,input){shape(input,['record_id','expected_version','reason','operation_key']);label(input.reason,2000);return mutable(ctx,input,'SUSPEND','GRANT',(tx,a,r)=>reviewer(tx,a,r),async(tx,a,r,i)=>{if(r.current_status!=='ACTIVE')throw error('LICENSE_NOT_ACTIVE',409);return save(tx,a,r,'SUSPENDED',{...r.data,suspension_reason:i.reason},'LICENSE_SUSPENDED');});},
 async createProject(ctx,input){input=JSON.parse(canonical(input));shape(input,['party_id','project','operation_key']);const dummy={exclusive:false,rights:['PRODUCE'],purposes:policy.PURPOSES,territories:['WORLD'],languages:['ALL'],valid_from:'2000-01-01T00:00:00.000Z',valid_until:'9999-01-01T00:00:00.000Z',development_until:'9999-01-01T00:00:00.000Z',project_limit:1,episode_limit:100000,terms_text:'validation only'};if(!policy.projectScope(dummy,input.project,Date.now()))throw error('INVALID_PROJECT',400);return db.withTransaction(async tx=>{const a=await actor(tx,ctx);await owner(tx,a,input.party_id);return command(tx,a,'PROJECT',input,()=>insert(tx,a,'PROJECT',input.party_id,null,null,null,'ACTIVE',input.project));});},
 async bind(ctx,input){shape(input,['party_id','record_id','expected_version','project_id','operation_key']);return mutable(ctx,input,'BIND','GRANT',async(tx,a,r,i)=>{await owner(tx,a,i.party_id);if(r.owner_party_id!==i.party_id)throw error('LICENSE_PARTY_FORBIDDEN');},async(tx,a,r,i,now)=>{await work(tx,r.data.work_version_id);const project=await load(tx,i.project_id,'PROJECT');if(project.owner_party_id!==i.party_id||project.current_status!=='ACTIVE'||r.current_status!=='ACTIVE'||!policy.projectScope(r.data.terms,project.data,now)||!r.data.terms.rights.some(x=>['ADAPT','PRODUCE'].includes(x)))throw error('PROJECT_LICENSE_NOT_READY',409);const [bindings]=await tx.execute("SELECT * FROM license_records WHERE kind='BINDING' AND parent_id=?",[r.id]);if(bindings.some(x=>record(x).data.project_id===project.id))throw error('PROJECT_ALREADY_BOUND',409);if(bindings.length>=r.data.terms.project_limit)throw error('LICENSE_QUOTA_EXHAUSTED',409);return insert(tx,a,'BINDING',i.party_id,i.party_id,r.work_id,r.id,'ACTIVE',{project_id:project.id,work_version_id:r.data.work_version_id,terms_sha256:digest(r.data.terms)});});},
 async createReading(ctx,input){input=JSON.parse(canonical(input));shape(input,['party_id','work_version_id','reader_account_id','reader_party_id','valid_until','basis_type','basis_asset_id','operation_key']);id(input.reader_account_id);if(!['NDA','EVALUATION_PERMISSION'].includes(input.basis_type))throw error('INVALID_READING_BASIS',400);policy.instant(input.valid_until);
 return db.withTransaction(async tx=>{const a=await actor(tx,ctx);await owner(tx,a,input.party_id);const w=await work(tx,input.work_version_id);if(w.owner_party_id!==input.party_id)throw error('LICENSE_PARTY_FORBIDDEN');await owner(tx,{id:input.reader_account_id},input.reader_party_id);return command(tx,a,'READING',input,async()=>{if(policy.instant(input.valid_until)<=await clock(tx))throw error('READING_EXPIRED',409);await asset(tx,input.basis_asset_id,[input.party_id]);return insert(tx,a,'READING',input.party_id,input.reader_party_id,w.stream_ref,null,'IN_REVIEW',{work_version_id:w.id,reader_account_id:input.reader_account_id,valid_until:input.valid_until,basis_type:input.basis_type,basis_asset_id:input.basis_asset_id,review:null,allows_generation:false});});});},
 async readingAsset(ctx,{record_id,party_id},log=false){return db.withTransaction(async tx=>{const a=await actor(tx,ctx);await owner(tx,a,party_id);const r=await load(tx,record_id,'READING','FOR SHARE');if(r.counterparty_id!==party_id||r.data.reader_account_id!==a.id||r.current_status!=='APPROVED'||policy.instant(r.data.valid_until)<=await clock(tx))throw error('READING_FORBIDDEN');const w=await work(tx,r.data.work_version_id);const file=await one(tx,"SELECT * FROM supply_assets WHERE id=? AND current_status='READY'",[w.data.version.content.content_asset_id]);if(!file||file.media_type!=='text/plain')throw error('READING_FORMAT_NOT_SUPPORTED',409);if(log)await audit(tx,a,r,'CONTROLLED_READING_DELIVERED');return {asset:file,watermark:'仅供受控评估阅读 | '+a.id+' | '+r.id+' | '+new Date(await clock(tx)).toISOString()};});},
 async evidenceAsset(ctx,{record_id,asset_id}){return db.withTransaction(async tx=>{const a=await actor(tx,ctx);await reviewer(tx,a,null);const r=await load(tx,record_id,null,'FOR SHARE');const allowed=r.kind==='EVIDENCE'?['seller_signature_asset_id','buyer_signature_asset_id','identity_asset_id','payment_asset_id']:r.kind==='READING'?['basis_asset_id']:[];if(!allowed.some(k=>r.data[k]===asset_id))throw error('LICENSE_NOT_FOUND',404);return asset(tx,asset_id,[r.owner_party_id,r.counterparty_id]);});},
 };
 return Object.freeze(api);
}
module.exports={createLicensingRepository,validBinding};
