'use strict';
const fs=require('node:fs/promises'),crypto=require('node:crypto');
const {status,migrate,lockName}=require('../infrastructure/database/migrator');
const F=require('./data-format');
const FORMAT='JX_MYSQL_BACKUP_V1';
const normalizeDDL=s=>s.replace(/ AUTO_INCREMENT=\d+/g,'').replace(/\r\n/g,'\n');
async function catalogue(c){const [rows]=await c.query("SELECT TABLE_NAME,ENGINE,TABLE_TYPE FROM information_schema.tables WHERE TABLE_SCHEMA=DATABASE() ORDER BY TABLE_NAME");if(rows.some(r=>r.ENGINE!=='InnoDB'||r.TABLE_TYPE!=='BASE TABLE'))throw F.fail('BACKUP_REQUIRES_INNODB_TABLES');return rows.map(r=>r.TABLE_NAME);}
async function capture(c,table){F.name(table);const [[ddl]]=await c.query('SHOW CREATE TABLE '+F.name(table));const [cols]=await c.execute('SELECT COLUMN_NAME,DATA_TYPE,EXTRA FROM information_schema.columns WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? ORDER BY ORDINAL_POSITION',[table]);const generated_columns=cols.filter(x=>/VIRTUAL GENERATED|STORED GENERATED/.test(x.EXTRA)).map(x=>x.COLUMN_NAME);const names=cols.map(x=>x.COLUMN_NAME),json_columns=cols.filter(x=>x.DATA_TYPE==='json').map(x=>x.COLUMN_NAME);const [data]=await c.execute('SELECT '+projection(names,json_columns)+' FROM '+F.name(table)+' LIMIT '+(F.MAX_ROWS+1));if(data.length>F.MAX_ROWS)throw F.fail('BACKUP_ROW_LIMIT');const rows=data.map(r=>names.map(n=>F.encode(r[n])));return {name:table,columns:names,generated_columns,json_columns,auto_increment:ddl['Create Table'].match(/ AUTO_INCREMENT=(\d+)/)?.[1]||(cols.some(c=>c.EXTRA==='auto_increment')?'1':null),ddl_sha256:F.hash(normalizeDDL(ddl['Create Table'])),rows,row_count:rows.length,data_sha256:F.tableHash(rows)};}
async function backup(db,{source_ref}={}){if(typeof source_ref!=='string'||!/^[A-Za-z0-9_.:-]{1,100}$/.test(source_ref))throw F.fail('BACKUP_SOURCE_REQUIRED');return db.withConnection(async c=>{const key=lockName(db.database);const [[locked]]=await c.execute('SELECT GET_LOCK(?,0) acquired',[key]);if(Number(locked.acquired)!==1)throw F.fail('MIGRATION_LOCK_BUSY');try{const schema=await status({withConnection:fn=>fn(c)});if(schema.migrations.some(x=>x.status!=='APPLIED'))throw F.fail('BACKUP_SCHEMA_NOT_READY');await c.query('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');await c.query('START TRANSACTION WITH CONSISTENT SNAPSHOT, READ ONLY');const names=await catalogue(c),tables=[];let size=0;for(const name of names){const t=await capture(c,name);size+=Buffer.byteLength(F.canonical(t));if(size>F.MAX_BYTES)throw F.fail('BACKUP_SIZE_LIMIT');tables.push(t);}if(F.canonical(names)!==F.canonical(await catalogue(c)))throw F.fail('BACKUP_SCHEMA_CHANGED');const payload={format:FORMAT,source_ref,created_at:new Date().toISOString(),migrations:schema.migrations.map(({version,name,checksum})=>({version,name,checksum})),tables};await c.commit();return {payload,manifest:manifest(payload)};}catch(e){await c.rollback();throw e;}finally{await c.execute('SELECT RELEASE_LOCK(?)',[key]);}});}
function projection(columns,json_columns){return columns.map(n=>json_columns.includes(n)?'CAST('+F.name(n)+' AS CHAR CHARACTER SET utf8mb4) AS '+F.name(n):F.name(n)).join(',');}
function manifest(p){return {format:FORMAT,source_ref:p.source_ref,created_at:p.created_at,payload_sha256:F.hash(p),tables:p.tables.map(({name,row_count,data_sha256,ddl_sha256})=>({name,row_count,data_sha256,ddl_sha256})),contains_private_data:true,external_object_bytes_included:false};}
function verify(p){if(!p||p.format!==FORMAT||!Array.isArray(p.tables)||!Array.isArray(p.migrations)||!p.tables.length||p.tables.length>500||Buffer.byteLength(F.canonical(p))>F.MAX_BYTES)throw F.fail('INVALID_BACKUP');if(new Set(p.tables.map(t=>t.name)).size!==p.tables.length)throw F.fail('INVALID_BACKUP');for(const t of p.tables){F.name(t.name);if(!Array.isArray(t.columns)||!t.columns.length||new Set(t.columns).size!==t.columns.length||!Array.isArray(t.rows)||t.rows.length>F.MAX_ROWS||t.rows.length!==t.row_count||F.tableHash(t.rows)!==t.data_sha256)throw F.fail('BACKUP_CHECKSUM_MISMATCH');if(!Array.isArray(t.json_columns)||t.json_columns.some(n=>!t.columns.includes(n)))throw F.fail('INVALID_BACKUP');if(!Array.isArray(t.generated_columns)||t.generated_columns.some(n=>!t.columns.includes(n)))throw F.fail('INVALID_BACKUP');if(t.auto_increment!==null&&(typeof t.auto_increment!=='string'||!/^[1-9][0-9]{0,19}$/.test(t.auto_increment)||BigInt(t.auto_increment)>18446744073709551615n))throw F.fail('INVALID_BACKUP');t.columns.forEach(F.name);for(const row of t.rows){if(!Array.isArray(row)||row.length!==t.columns.length)throw F.fail('INVALID_BACKUP');row.forEach(F.decode);}}return p;}
function secret(key){if(!Buffer.isBuffer(key)||key.length!==32)throw F.fail('BACKUP_KEY_REQUIRED');return key;}
function seal(payload,key){verify(payload);const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',secret(key),iv,{authTagLength:16});c.setAAD(Buffer.from(FORMAT));const data=Buffer.concat([c.update(Buffer.from(F.canonical(payload))),c.final()]);return {format:FORMAT,algorithm:'AES-256-GCM',iv:iv.toString('base64'),tag:c.getAuthTag().toString('base64'),data:data.toString('base64')};}
function unseal(blob,key){secret(key);try{if(blob.format!==FORMAT||blob.algorithm!=='AES-256-GCM'||typeof blob.data!=='string'||blob.data.length>Math.ceil(F.MAX_BYTES*4/3)+8)throw Error();const iv=Buffer.from(blob.iv,'base64'),tag=Buffer.from(blob.tag,'base64');if(iv.length!==12||tag.length!==16)throw Error();const c=crypto.createDecipheriv('aes-256-gcm',key,iv,{authTagLength:16});c.setAAD(Buffer.from(FORMAT));c.setAuthTag(tag);return verify(JSON.parse(Buffer.concat([c.update(Buffer.from(blob.data,'base64')),c.final()]).toString('utf8')));}catch{throw F.fail('BACKUP_AUTHENTICATION_FAILED');}}
async function writeEncrypted(file,payload,key){const bytes=Buffer.from(JSON.stringify(seal(payload,key)));const handle=await fs.open(file,'wx',0o600);try{await handle.writeFile(bytes);await handle.sync();}finally{await handle.close();}return {bytes:bytes.length,sha256:F.hash(bytes)};}
async function readEncrypted(file,key){const h=await fs.open(file,'r');try{const stat=await h.stat();if(!stat.isFile()||stat.size>F.MAX_BYTES*1.4)throw F.fail('BACKUP_SIZE_LIMIT');return unseal(JSON.parse(await h.readFile('utf8')),key);}finally{await h.close();}}
async function restore(db,payload,{expected_sha256}={}){verify(payload);if(F.hash(payload)!==expected_sha256)throw F.fail('BACKUP_CHECKSUM_MISMATCH');const tables=await db.withConnection(c=>catalogue(c));if(tables.length)throw F.fail('RESTORE_TARGET_NOT_EMPTY');const schema=await status(db);if(F.canonical(schema.migrations.map(({version,name,checksum})=>({version,name,checksum})))!==F.canonical(payload.migrations))throw F.fail('RESTORE_MIGRATIONS_MISMATCH');await migrate(db);
 // A marker is persisted before any data write; no failure may leave this restored database runnable.
 await db.execute("INSERT INTO platform_schema_metadata(schema_key,schema_value) VALUES ('recovery_status','QUARANTINED')");
  // Validate trusted schema before starting the row transaction; never reserve a second pool connection.
  await db.withConnection(async c=>{for(const t of payload.tables){const current=await capture(c,t.name);if((current.auto_increment===null)!==(t.auto_increment===null)||current.ddl_sha256!==t.ddl_sha256||F.canonical(current.json_columns)!==F.canonical(t.json_columns)||F.canonical(current.columns)!==F.canonical(t.columns)||F.canonical(current.generated_columns)!==F.canonical(t.generated_columns))throw F.fail('RESTORE_SCHEMA_MISMATCH');}});
 const result=await db.withTransaction(async tx=>{const names=(await tx.execute('SELECT TABLE_NAME FROM information_schema.tables WHERE TABLE_SCHEMA=DATABASE() ORDER BY TABLE_NAME'))[0].map(r=>r.TABLE_NAME);if(F.canonical(names)!==F.canonical(payload.tables.map(t=>t.name)))throw F.fail('RESTORE_TABLE_SET_MISMATCH');
  await tx.execute("DELETE FROM platform_schema_metadata WHERE schema_key<>'recovery_status'");await tx.execute('DELETE FROM platform_schema_migrations');
  let pending=[];for(const t of payload.tables)for(const row of t.rows){if(t.name==='platform_schema_metadata'&&row[t.columns.indexOf('schema_key')]?.v==='recovery_status')continue;pending.push({t,row});}
  // Keep foreign keys enabled. Deferred rows are retried only after referenced rows have been inserted.
  while(pending.length){const next=[];for(const entry of pending){const {t,row}=entry;try{const indices=t.columns.map((n,i)=>t.generated_columns.includes(n)?-1:i).filter(i=>i>=0);await tx.execute('INSERT INTO '+F.name(t.name)+' ('+indices.map(i=>F.name(t.columns[i])).join(',')+') VALUES ('+indices.map(()=>'?').join(',')+')',indices.map(i=>F.decode(row[i])));}catch(e){if(e.code==='ER_NO_REFERENCED_ROW_2')next.push(entry);else throw e;}}if(next.length===pending.length)throw F.fail('RESTORE_FOREIGN_KEY_MISMATCH');pending=next;}
  for(const t of payload.tables){const [data]=await tx.execute('SELECT '+projection(t.columns,t.json_columns)+' FROM '+F.name(t.name)+(t.name==='platform_schema_metadata'?" WHERE schema_key<>'recovery_status'":''));const rows=data.map(r=>t.columns.map(n=>F.encode(r[n]))),original=t.name==='platform_schema_metadata'?t.rows.filter(row=>row[t.columns.indexOf('schema_key')]?.v!=='recovery_status'):t.rows;if(F.tableHash(rows)!==F.tableHash(original))throw Object.assign(F.fail('RESTORE_DATA_MISMATCH'),{message:'RESTORE_DATA_MISMATCH: '+t.name+' '+t.columns.filter((n,i)=>F.tableHash(rows.map(r=>[r[i]]))!==F.tableHash(original.map(r=>[r[i]]))).join(',')});}
  return {result:'MATCHED',tables:payload.tables.length,rows:payload.tables.reduce((n,t)=>n+t.row_count,0),payload_sha256:F.hash(payload),runtime_status:'QUARANTINED',comparison_excludes:['platform_schema_metadata.recovery_status'],external_objects_restored:false};
 });
 // Restore deleted/reserved identifier high-water marks only after the row transaction commits.
 // The persistent quarantine remains in place if this final step fails.
 await db.withConnection(async c=>{for(const t of payload.tables)if(t.auto_increment!==null)await c.query('ALTER TABLE '+F.name(t.name)+' AUTO_INCREMENT='+t.auto_increment);});
 return result;}
module.exports={backup,manifest,verify,seal,unseal,writeEncrypted,readEncrypted,restore,capture};
