'use strict';
const fs=require('node:fs'),Database=require('better-sqlite3'),F=require('./data-format');
function inspect(file,{source_ref,source_kind}={}){
 if(!/^[A-Za-z0-9_.:-]{1,100}$/.test(source_ref||'')||!['SYNTHETIC','SANITIZED_COPY'].includes(source_kind))throw F.fail('LEGACY_SOURCE_DECLARATION_REQUIRED');
 const st=fs.lstatSync(file);if(!st.isFile()||st.isSymbolicLink()||st.size>F.MAX_BYTES)throw F.fail('LEGACY_FILE_NOT_SUPPORTED');
 if(fs.existsSync(file+'-wal')&&fs.statSync(file+'-wal').size)throw F.fail('LEGACY_WAL_REQUIRES_CLOSED_COPY');
 const original=F.hash(fs.readFileSync(file)),db=new Database(file,{readonly:true,fileMustExist:true});
 try{db.defaultSafeIntegers(true);db.pragma('query_only = ON');db.exec('BEGIN');const integrity=db.pragma('integrity_check');if(integrity.length!==1||integrity[0].integrity_check!=='ok')throw F.fail('LEGACY_INTEGRITY_FAILED');const schema=db.prepare("SELECT type,name,tbl_name,sql FROM sqlite_master WHERE name NOT LIKE 'sqlite_%' ORDER BY type,name").all();const tables=[];let bytes=0;
 for(const t of schema.filter(x=>x.type==='table')){F.name(t.name);const columns=db.prepare('PRAGMA table_info('+F.name(t.name)+')').all().map(x=>({name:x.name,type:x.type,notnull:String(x.notnull),default:x.dflt_value,pk:String(x.pk)}));const names=columns.map(c=>c.name);names.forEach(F.name);const data=db.prepare('SELECT '+names.map(F.name).join(',')+' FROM '+F.name(t.name)+' LIMIT '+(F.MAX_ROWS+1)).all();if(data.length>F.MAX_ROWS)throw F.fail('LEGACY_ROW_LIMIT');const rows=data.map(row=>names.map(n=>F.encode(row[n])));const item={name:t.name,columns,rows,row_count:rows.length,data_sha256:F.tableHash(rows)};bytes+=Buffer.byteLength(F.canonical(item));if(bytes>F.MAX_BYTES)throw F.fail('LEGACY_SIZE_LIMIT');tables.push(item);}
 db.exec('ROLLBACK');if(original!==F.hash(fs.readFileSync(file)))throw F.fail('LEGACY_SOURCE_CHANGED');const payload={format:'JX_LEGACY_RETAIN_V1',source_ref,source_kind,source_sha256:original,schema,tables};return {payload,manifest:manifest(payload)};
 }finally{db.close();}}
function manifest(p){return {format:p.format,source_ref:p.source_ref,source_kind:p.source_kind,source_sha256:p.source_sha256,schema:p.schema,content_sha256:F.hash(p),tables:p.tables.map(({name,columns,row_count,data_sha256})=>({name,columns,row_count,data_sha256})),current_status:'RETAINED_REVIEW_REQUIRED',converted_accounts:0,verified_payments:0,activated_licenses:0};}
function validate(p){if(!p||p.format!=='JX_LEGACY_RETAIN_V1'||!Array.isArray(p.tables)||!p.tables.length||!Array.isArray(p.schema)||!['SYNTHETIC','SANITIZED_COPY'].includes(p.source_kind)||!/^[A-Za-z0-9_.:-]{1,100}$/.test(p.source_ref||'')||!/^[a-f0-9]{64}$/.test(p.source_sha256||'')||Buffer.byteLength(F.canonical(p))>F.MAX_BYTES)throw F.fail('LEGACY_INVALID_PAYLOAD');if(new Set(p.tables.map(t=>t.name)).size!==p.tables.length)throw F.fail('LEGACY_INVALID_PAYLOAD');for(const t of p.tables){F.name(t.name);if(t.row_count!==t.rows.length||t.rows.length>F.MAX_ROWS||F.tableHash(t.rows)!==t.data_sha256)throw F.fail('LEGACY_CHECKSUM_MISMATCH');for(const row of t.rows){if(row.length!==t.columns.length)throw F.fail('LEGACY_INVALID_PAYLOAD');row.forEach(F.decode);}}}
async function retain(db,payload){validate(payload);const m=manifest(payload),id=F.hash([m.source_ref,m.source_sha256]);return db.withTransaction(async tx=>{const [[old]]=await tx.execute('SELECT content_sha256 FROM legacy_imports WHERE id=? FOR UPDATE',[id]);if(old){if(old.content_sha256!==m.content_sha256)throw F.fail('LEGACY_SOURCE_CONFLICT');return {id,replay:true,...m};}try{await tx.execute('INSERT INTO legacy_imports(id,source_ref,source_kind,source_sha256,content_sha256,manifest_json) VALUES (?,?,?,?,?,?)',[id,m.source_ref,m.source_kind,m.source_sha256,m.content_sha256,JSON.stringify(m)]);}catch(e){if(e.code!=='ER_DUP_ENTRY')throw e;const [[existing]]=await tx.execute('SELECT content_sha256 FROM legacy_imports WHERE id=? FOR UPDATE',[id]);if(existing?.content_sha256!==m.content_sha256)throw F.fail('LEGACY_SOURCE_CONFLICT');return {id,replay:true,...m};}for(const t of payload.tables)for(let n=0;n<t.rows.length;n++)await tx.execute('INSERT INTO legacy_rows(import_id,table_name,row_index,data_json,content_sha256) VALUES (?,?,?,?,?)',[id,t.name,n,JSON.stringify(t.rows[n]),F.hash(t.rows[n])]);return {id,replay:false,...m};});}
async function reconcile(db,id){if(!/^[a-f0-9]{64}$/.test(id||''))throw F.fail('INVALID_IMPORT_ID');return db.withTransaction(async tx=>{const [[r]]=await tx.execute('SELECT * FROM legacy_imports WHERE id=? FOR SHARE',[id]);if(!r)throw F.fail('LEGACY_IMPORT_NOT_FOUND');const m=typeof r.manifest_json==='string'?JSON.parse(r.manifest_json):r.manifest_json;const [rows]=await tx.execute('SELECT table_name,row_index,data_json,content_sha256 FROM legacy_rows WHERE import_id=? ORDER BY table_name,row_index',[id]);const grouped=new Map();for(const row of rows){const data=typeof row.data_json==='string'?JSON.parse(row.data_json):row.data_json;if(F.hash(data)!==row.content_sha256)throw F.fail('LEGACY_CHECKSUM_MISMATCH');if(!grouped.has(row.table_name))grouped.set(row.table_name,[]);grouped.get(row.table_name).push(data);}if(rows.length!==m.tables.reduce((n,t)=>n+t.row_count,0))throw F.fail('LEGACY_COUNT_MISMATCH');for(const t of m.tables)if(F.tableHash(grouped.get(t.name)||[])!==t.data_sha256)throw F.fail('LEGACY_CHECKSUM_MISMATCH');const payload={format:m.format,source_ref:m.source_ref,source_kind:m.source_kind,source_sha256:m.source_sha256,schema:m.schema,tables:m.tables.map(t=>({...t,rows:grouped.get(t.name)||[]}))};if(F.hash(payload)!==r.content_sha256||m.content_sha256!==r.content_sha256||m.source_ref!==r.source_ref||m.source_sha256!==r.source_sha256||m.source_kind!==r.source_kind)throw F.fail('LEGACY_MANIFEST_MISMATCH');return {id,result:'MATCHED',source_kind:r.source_kind,tables:m.tables.length,rows:rows.length,current_status:r.current_status,verified_payments:0,converted_accounts:0,activated_licenses:0};});}
module.exports={inspect,manifest,retain,reconcile,validate};
