'use strict';
const {status}=require('../infrastructure/database/migrator'),{recoveryAllowed}=require('../infrastructure/database/recovery-guard');
const {hash,fail}=require('./data-format');
const CHECKS=Object.freeze(['peer_review','frontend_journeys','real_devices','sanitized_legacy_rehearsal','database_restore','private_object_restore','security_review','target_load','incident_contacts','product_and_contracts']);
function validateManifest(m){if(!m||m.format!=='JX_RELEASE_REVIEW_V1'||!/^[a-f0-9]{40}$/.test(m.commit||'')||!Array.isArray(m.checks)||!Array.isArray(m.providers)||m.checks.length>30||m.providers.length>30)throw fail('INVALID_RELEASE_MANIFEST');const names=m.checks.map(x=>x.name);if(new Set(names).size!==names.length||names.some(x=>!CHECKS.includes(x)))throw fail('INVALID_RELEASE_MANIFEST');return m;}
function reviewChecks(m,now=Date.now()){validateManifest(m);return CHECKS.map(name=>{const r=m.checks.find(x=>x.name===name);const valid=!!r&&r.result==='VERIFIED'&&r.commit===m.commit&&r.environment==='PRODUCTION_CANDIDATE'&&typeof r.evidence_ref==='string'&&/^[A-Za-z0-9_.:/-]{1,200}$/.test(r.evidence_ref)&&typeof r.reviewed_by==='string'&&r.reviewed_by.trim()&&Number.isFinite(Date.parse(r.reviewed_at))&&Date.parse(r.reviewed_at)<=now&&Number.isFinite(Date.parse(r.expires_at))&&Date.parse(r.expires_at)>now;return {name,current_status:valid?'DECLARED_EVIDENCE_REQUIRES_REVIEW':'MISSING_OR_OUTDATED',reason:valid?'材料声明已填写，仍须独立核验其真实性':'缺少与本次版本匹配、未过期的验收材料'};});}
function configChecks(env){const rows=[];const check=(name,ok)=>rows.push({name,result:ok?'PASS':'BLOCKED'});check('explicit_mysql',env.DB_CLIENT==='mysql');check('production_mode',env.NODE_ENV==='production');check('verified_database_tls',env.MYSQL_SSL_MODE==='verify_identity'&&!!env.MYSQL_SSL_CA&&!!env.MYSQL_USER&&env.MYSQL_USER!=='root');const key=env.AUTH_SECRET_BASE64;check('auth_secret',typeof key==='string'&&/^[A-Za-z0-9+/]{43}=$/.test(key)&&Buffer.from(key,'base64').length===32);const origins=(env.API_ALLOWED_ORIGINS||'').split(',').filter(Boolean);check('https_browser_origins',origins.length>0&&origins.every(x=>{try{const u=new URL(x);return u.protocol==='https:'&&u.origin===x&&!u.username&&!u.password;}catch{return false;}}));check('no_debug_logging',!env.DEBUG);check('operations_worker_declared',env.OPERATIONS_WORKER_ENABLED==='true');return rows;}
async function inspect(db,manifest,env={}){const checks=reviewChecks(manifest),schema=await status(db),quarantine=!await recoveryAllowed(db);const [jobs]=await db.execute("SELECT status,COUNT(*) count FROM platform_jobs WHERE status IN ('RUNNING','BLOCKED','FAILED') GROUP BY status");const providers=[];for(const p of manifest.providers){const descriptor=require('../modules/providers/readiness').descriptor({...p,environment:'PRODUCTION'});const r=await require('../modules/providers/readiness').createReadinessRepository(db).read(descriptor);const matched=r?.current_status==='PRODUCTION_VERIFIED'&&r.config_revision===p.config_revision&&r.verification_history.some(h=>h.object_version===r.object_version&&h.environment==='PRODUCTION'&&h.verified_state==='PRODUCTION_VERIFIED'&&h.config_revision===p.config_revision&&h.evidence_ref);providers.push({provider_kind:descriptor.provider_kind,provider_code:descriptor.provider_code,capability_code:descriptor.capability_code,current_status:matched?'RECORDED_REQUIRES_LIVE_RECHECK':'NOT_VERIFIED',transport_checked:false});}
 return {format:'JX_RELEASE_REPORT_V1',commit:manifest.commit,manifest_sha256:hash(manifest),generated_at:new Date().toISOString(),schema_ready:schema.migrations.length>0&&schema.migrations.every(x=>x.status==='APPLIED'),restore_quarantined:quarantine,configuration:configChecks(env),checks,providers,pending_jobs:jobs.map(x=>({status:x.status,count:Number(x.count)})),production_release:'NOT_APPROVED',reason:'本工具只读检查配置和已登记证据；不调用真实供应商、不批准上线，也不自动放行恢复库。',external_credentials_printed:false};}
module.exports={CHECKS,validateManifest,reviewChecks,configChecks,inspect};
