 'use strict';
const {shape,ref,id,label,error}=require('../party/policy');
const {canonical}=require('../governance/content');
const {instant}=require('../licensing/policy');
const copy=x=>JSON.parse(canonical(x));
function amount(n,zero=false){if(!Number.isSafeInteger(n)||n<(zero?0:1)||n>900000000000)throw error('INVALID_MONEY',400);return n;}
function sum(values){return amount(values.reduce((a,b)=>a+amount(b,true),0),true);}
function allocations(list){if(!Array.isArray(list)||!list.length||list.length>30)throw error('INVALID_ALLOCATIONS',400);const seen=new Set();for(const x of list){shape(x,['line_id','amount_minor']);ref(x.line_id);amount(x.amount_minor);if(seen.has(x.line_id))throw error('DUPLICATE_LINE',400);seen.add(x.line_id);}return copy(list);}
function specification(v){v=copy(v);shape(v,['version','service_tier','sample_seconds','final_seconds','revision_limit','deliverables','terms']);ref(v.version);label(v.service_tier,100);label(v.terms,8000);for(const k of ['sample_seconds','final_seconds','revision_limit'])if(!Number.isInteger(v[k])||v[k]<0||v[k]>100000)throw error('INVALID_SPECIFICATION',400);if(!Array.isArray(v.deliverables)||!v.deliverables.length||v.deliverables.length>30)throw error('INVALID_SPECIFICATION',400);v.deliverables.forEach(x=>label(x,500));return v;}
function plan(lines,steps,channel){if(!Array.isArray(steps)||!steps.length||steps.length>20)throw error('INVALID_PAYMENT_PLAN',400);const keys=new Set(),totals=new Map(lines.map(x=>[x.line_id,0]));for(const step of steps){shape(step,['key','trigger','allocations','apple_product_id']);ref(step.key);if(keys.has(step.key)||!['ORDER_ACCEPTED','SAMPLE_ACCEPTED','FINAL_ACCEPTED'].includes(step.trigger))throw error('INVALID_PAYMENT_PLAN',400);keys.add(step.key);if(channel==='APPLE')ref(step.apple_product_id);else if(step.apple_product_id!==null)throw error('INVALID_PAYMENT_PLAN',400);for(const a of allocations(step.allocations)){if(!totals.has(a.line_id))throw error('UNKNOWN_LINE',400);totals.set(a.line_id,amount(totals.get(a.line_id)+a.amount_minor));}}for(const line of lines)if(totals.get(line.line_id)!==line.total_minor)throw error('PAYMENT_PLAN_TOTAL_MISMATCH',400);return copy(steps);}
function yuanToMinor(v){if(typeof v!=='string'||!/^\d+(?:\.\d{1,2})?$/.test(v))throw error('INVALID_PROVIDER_AMOUNT',409);const [a,b='']=v.split('.'),n=BigInt(a)*100n+BigInt(b.padEnd(2,'0'));return amount(Number(n),true);}
function minorToYuan(v){amount(v);return (BigInt(v)/100n).toString()+'.'+(BigInt(v)%100n).toString().padStart(2,'0');}
function refundWithin(paid,existing,wanted){const totals=new Map(paid.map(x=>[x.line_id,x.amount_minor]));for(const refund of existing)for(const a of refund)totals.set(a.line_id,(totals.get(a.line_id)||0)-a.amount_minor);for(const a of allocations(wanted))if(!totals.has(a.line_id)||a.amount_minor>totals.get(a.line_id))throw error('REFUND_EXCEEDS_REMAINING',409);return sum(wanted.map(x=>x.amount_minor));}
function paymentMatches(p,r){if(!r||r.provider!==p.provider||r.environment!==p.environment||r.app_id!==p.app_id||r.merchant_id!==p.merchant_id||r.payment_id!==p.id||r.currency!==p.currency||r.amount_minor!==p.amount_minor||!['PENDING','SUCCEEDED','CLOSED','REFUNDED','REVIEW_REQUIRED'].includes(r.status))throw error('PAYMENT_PROOF_MISMATCH',409);if(['SUCCEEDED','REFUNDED'].includes(r.status))ref(r.transaction_id);if(p.provider==='APPLE'&&(r.product_id!==p.apple_product_id||r.app_account_token!==p.id))throw error('PAYMENT_PROOF_MISMATCH',409);return r;}
module.exports={copy,amount,sum,allocations,specification,plan,yuanToMinor,minorToYuan,refundWithin,paymentMatches,instant};
