 'use strict';
const {randomUUID}=require('node:crypto');
const {id,ref,label,shape,version,error}=require('../party/policy');
const {digest,sealUnsignedContent}=require('../governance/content');
const {authorizeOperator}=require('../governance/operator-access');
const rules=require('./policy');
const one=async(tx,sql,args=[]) => (await tx.execute(sql,args))[0][0];
const parsed=x=>typeof x==='string'?JSON.parse(x):x;
function record(row){if(!row)throw error('TRADE_NOT_FOUND',404);const data=parsed(row.data_json);if(digest(data)!==row.data_sha256)throw error('STORED_CONTENT_MISMATCH',503);return {id:row.id,kind:row.kind,buyer_party_id:row.buyer_party_id,merchant_party_id:row.merchant_party_id,parent_id:row.parent_id,order_id:row.order_id,created_by:row.created_by,current_status:row.current_status,object_version:row.object_version,content_sha256:row.data_sha256,data};}
function createTradeRepository(db,{resolvePrincipal=async()=>null,fulfillmentGate=async()=>false}={}) {
 async function actor(tx,ctx){const p=await resolvePrincipal(ctx);if(!p)throw error('AUTHENTICATION_REQUIRED',401);const a=await one(tx,'SELECT * FROM identity_accounts WHERE subject_ref=? FOR SHARE',[ref(p.subject_ref)]);if(!a||a.current_status!=='ACTIVE')throw error('ACCOUNT_NOT_ACTIVE');return {id:a.id,kind:'ACCOUNT',request_id:ref(p.request_id||randomUUID())};}
 const providerActor=()=>({id:null,kind:'PROVIDER',request_id:randomUUID()});
 async function owner(tx,a,party){const p=await one(tx,'SELECT * FROM parties WHERE id=? FOR SHARE',[id(party)]),m=await one(tx,'SELECT * FROM party_memberships WHERE party_id=? AND account_id=? FOR SHARE',[party,a.id]);if(!p||['SUSPENDED','CLOSED'].includes(p.current_status)||!m||m.current_status!=='ACTIVE'||m.role_code!=='OWNER')throw error('TRADE_PARTY_FORBIDDEN');}
 async function reviewer(tx,a,r,action='TRADE_REVIEW'){if(!await authorizeOperator(tx,{account_id:a.id,action}))throw error('TRADE_REVIEW_FORBIDDEN');if(r&&(r.created_by===a.id||await one(tx,"SELECT id FROM party_memberships WHERE account_id=? AND current_status='ACTIVE' AND party_id IN (?,?)",[a.id,r.buyer_party_id,r.merchant_party_id])))throw error('SELF_REVIEW_FORBIDDEN');}
 async function access(tx,a,r,party){if(party){await owner(tx,a,party);if(![r.buyer_party_id,r.merchant_party_id].includes(party))throw error('TRADE_NOT_FOUND',404);}else await reviewer(tx,a,null,r.kind==='REFUND'?'TRADE_REFUND':'TRADE_REVIEW');}
 async function load(tx,key,kind,lock='FOR UPDATE'){const r=record(await one(tx,'SELECT * FROM trade_records WHERE id=? '+lock,[id(key)]));if(kind&&r.kind!==kind)throw error('TRADE_NOT_FOUND',404);return r;}
 async function locked(tx,key,kind){const hint=await load(tx,key,kind,'');if(hint.order_id)await load(tx,hint.order_id,'ORDER');return load(tx,key,kind);}
 async function now(tx){return Number((await one(tx,'SELECT ROUND(UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000) ms')).ms);}
 async function audit(tx,a,r,event){await tx.execute('INSERT INTO trade_audit(id,record_id,actor_account_id,actor_kind,event_code,object_version,data_sha256,request_id) VALUES (?,?,?,?,?,?,?,?)',[randomUUID(),r.id,a.id,a.kind,event,r.object_version,digest(r.data),a.request_id]);}
 async function insert(tx,a,kind,buyer,merchant,parent,order,status,data){const r={id:randomUUID(),kind,buyer_party_id:buyer,merchant_party_id:merchant,parent_id:parent,order_id:order,created_by:a.id,current_status:status,object_version:1,content_sha256:digest(data),data};await tx.execute('INSERT INTO trade_records(id,kind,buyer_party_id,merchant_party_id,parent_id,order_id,created_by,current_status,data_json,data_sha256) VALUES (?,?,?,?,?,?,?,?,?,?)',[r.id,kind,buyer,merchant,parent,order,a.id,status,JSON.stringify(data),digest(data)]);await audit(tx,a,r,kind+'_CREATED');return r;}
 async function save(tx,a,r,status,data,event){const next={...r,current_status:status,object_version:r.object_version+1,content_sha256:digest(data),data};await tx.execute('UPDATE trade_records SET current_status=?,object_version=?,data_json=?,data_sha256=? WHERE id=?',[status,next.object_version,JSON.stringify(data),digest(data),r.id]);await audit(tx,a,next,event);return next;}
 const match=(r,v)=>{if(r.object_version!==version(v))throw error('VERSION_CONFLICT',412);};
 async function command(tx,a,op,input,fn){const key=digest([a.id,op,ref(input.operation_key)]),hash=digest(input);try{await tx.execute('INSERT INTO trade_commands(id,fingerprint) VALUES (?,?)',[key,hash]);}catch(e){if(e.code!=='ER_DUP_ENTRY')throw e;const old=await one(tx,'SELECT * FROM trade_commands WHERE id=?',[key]);if(old.fingerprint!==hash)throw error('IDEMPOTENCY_CONFLICT',409);if(!old.result_id)throw error('IDEMPOTENCY_IN_PROGRESS',409);return load(tx,old.result_id,null,'FOR SHARE');}const result=await fn();await tx.execute('UPDATE trade_commands SET result_id=? WHERE id=?',[result.id,key]);return result;}
 async function change(ctx,input,op,auth,fn){input=rules.copy(input);return db.withTransaction(async tx=>{const a=await actor(tx,ctx),r=await locked(tx,input.record_id);await auth(tx,a,r,input);return command(tx,a,op,input,async()=>{match(r,input.expected_version);return fn(tx,a,r,input);});});}
 async function journal(tx,source,direction,proof){await tx.execute('INSERT INTO trade_journal(id,source_id,order_id,direction,currency,amount_minor,provider_reference) VALUES (?,?,?,?,?,?,?)',[randomUUID(),source.id,source.order_id,direction,source.data.currency,source.data.amount_minor,proof]);}
 async function summarize(tx,a,order,forceReview=false){const [rows]=await tx.execute('SELECT direction,amount_minor FROM trade_journal WHERE order_id=?',[order.id]);const received=rules.sum(rows.filter(x=>x.direction==='RECEIPT').map(x=>Number(x.amount_minor))),refunded=rules.sum(rows.filter(x=>x.direction==='REFUND').map(x=>Number(x.amount_minor)));if(refunded>received)throw error('FINANCIAL_INVARIANT_BROKEN',503);const status=forceReview||order.current_status==='PAYMENT_REVIEW_REQUIRED'?'PAYMENT_REVIEW_REQUIRED':refunded===received&&refunded>0?'REFUNDED':refunded>0?'PARTIALLY_REFUNDED':received===order.data.quote.total_minor?'PAID':received>0?'PARTIALLY_PAID':order.current_status;return save(tx,a,order,status,{...order.data,financial:{received_minor:received,refunded_minor:refunded,net_minor:received-refunded}},'FINANCIAL_FACT_UPDATED');}
 async function reservation(tx,key,buyer,merchant){const row=await one(tx,"SELECT * FROM license_records WHERE id=? AND kind='RESERVATION' FOR SHARE",[id(key)]);if(!row||row.owner_party_id!==buyer||row.counterparty_id!==merchant)throw error('LICENSE_RESERVATION_MISMATCH',409);const d=parsed(row.data_json);if(digest(d)!==row.data_sha256)throw error('STORED_CONTENT_MISMATCH',503);return {...row,data:d};}
 const api={
 async read(ctx,{record_id,party_id}){return db.withTransaction(async tx=>{const a=await actor(tx,ctx),r=await load(tx,record_id,null,'FOR SHARE');await access(tx,a,r,party_id);return r;});},
 async list(ctx,{kind,party_id,after='',limit=20}){if(!['SPEC','QUOTE','ORDER','PAYMENT','REFUND','LEGACY'].includes(kind)||!Number.isInteger(limit)||limit<1||limit>100)throw error('INVALID_LIST',400);if(after)id(after);return db.withTransaction(async tx=>{const a=await actor(tx,ctx);if(party_id)await owner(tx,a,party_id);else await reviewer(tx,a,null);const [rows]=await tx.execute('SELECT * FROM trade_records WHERE kind=? AND id>? '+(party_id?'AND (buyer_party_id=? OR merchant_party_id=?) ':'')+'ORDER BY id LIMIT ?',[kind,after,...(party_id?[party_id,party_id]:[]),limit+1]);return {items:rows.slice(0,limit).map(record),next_cursor:rows.length>limit?rows[limit-1].id:null};});},
 async createSpec(ctx,input){input=rules.copy(input);shape(input,['party_id','previous_spec_id','title','provider_party_id','line_kind','unit_minor','currency','specification','operation_key']);label(input.title,200);id(input.provider_party_id);if(!['LICENSE','PRODUCTION','OTHER'].includes(input.line_kind)||input.currency!=='CNY')throw error('UNSUPPORTED_SPECIFICATION',400);rules.amount(input.unit_minor);const spec=rules.specification(input.specification);return db.withTransaction(async tx=>{const a=await actor(tx,ctx);await owner(tx,a,input.party_id);if(!await one(tx,'SELECT id FROM parties WHERE id=?',[input.provider_party_id]))throw error('PARTY_NOT_FOUND',404);if(input.previous_spec_id!==null){const prev=await load(tx,input.previous_spec_id,'SPEC');if(prev.merchant_party_id!==input.party_id)throw error('TRADE_PARTY_FORBIDDEN');}return command(tx,a,'SPEC',input,()=>insert(tx,a,'SPEC',null,input.party_id,input.previous_spec_id,null,'IN_REVIEW',{title:input.title,provider_party_id:input.provider_party_id,line_kind:input.line_kind,unit_minor:input.unit_minor,currency:input.currency,specification:spec,review:null}));});},
 async review(ctx,input){shape(input,['record_id','expected_version','decision','reason','operation_key']);if(!['APPROVED','REJECTED'].includes(input.decision))throw error('INVALID_REVIEW',400);label(input.reason,2000);return change(ctx,input,'REVIEW',(tx,a,r)=>reviewer(tx,a,r,r.kind==='REFUND'?'TRADE_REFUND':'TRADE_REVIEW'),async(tx,a,r,i)=>{if(!['SPEC','QUOTE','REFUND','LEGACY'].includes(r.kind)||!['IN_REVIEW','REQUESTED','NEEDS_REVIEW'].includes(r.current_status))throw error('REVIEW_NOT_PENDING',409);const status=i.decision==='REJECTED'?'REJECTED':{SPEC:'PUBLISHED',QUOTE:'APPROVED',REFUND:'APPROVED',LEGACY:'VERIFIED_REFERENCE_ONLY'}[r.kind];return save(tx,a,r,status,{...r.data,review:{decision:i.decision,reason:i.reason,account_id:a.id}},'INDEPENDENT_REVIEW');});},
 async quote(ctx,input){input=rules.copy(input);shape(input,['party_id','buyer_party_id','lines','installments','channel','transaction_model','rule_id','expires_at','payment_window_minutes','license_reservation_id','operation_key']);id(input.buyer_party_id);if(input.buyer_party_id===input.party_id||!['ALIPAY','APPLE'].includes(input.channel)||!['DIRECT_SUPPLIER','PLATFORM_PRINCIPAL'].includes(input.transaction_model)||!Number.isInteger(input.payment_window_minutes)||input.payment_window_minutes<1||input.payment_window_minutes>10080)throw error('INVALID_QUOTE',400);rules.instant(input.expires_at);if(!Array.isArray(input.lines)||!input.lines.length||input.lines.length>30)throw error('INVALID_LINES',400);
 return db.withTransaction(async tx=>{const a=await actor(tx,ctx);await owner(tx,a,input.party_id);if(!await one(tx,'SELECT id FROM parties WHERE id=?',[input.buyer_party_id]))throw error('PARTY_NOT_FOUND',404);return command(tx,a,'QUOTE',input,async()=>{if(rules.instant(input.expires_at)<=await now(tx))throw error('QUOTE_EXPIRED',409);const seen=new Set(),lines=[];for(const l of input.lines){shape(l,['line_id','spec_id','quantity']);ref(l.line_id);if(seen.has(l.line_id)||!Number.isInteger(l.quantity)||l.quantity<1||l.quantity>10000)throw error('INVALID_LINES',400);seen.add(l.line_id);const s=await load(tx,l.spec_id,'SPEC','FOR SHARE');if(s.current_status!=='PUBLISHED'||s.merchant_party_id!==input.party_id)throw error('SPEC_NOT_PUBLISHED',409);lines.push({line_id:l.line_id,spec_id:s.id,spec_version:s.object_version,quantity:l.quantity,total_minor:rules.amount(s.data.unit_minor*l.quantity),...s.data});}if(input.transaction_model==='DIRECT_SUPPLIER'&&lines.some(x=>x.provider_party_id!==input.party_id))throw error('DIRECT_SUPPLIER_MISMATCH',409);const total_minor=rules.sum(lines.map(x=>x.total_minor)),installments=rules.plan(lines,input.installments,input.channel);if(input.license_reservation_id!==null){const r=await reservation(tx,input.license_reservation_id,input.buyer_party_id,input.party_id);const fees=lines.filter(x=>x.line_kind==='LICENSE');if(fees.length!==1||fees[0].total_minor!==r.data.price.amount_minor||fees[0].provider_party_id!==r.counterparty_id)throw error('LICENSE_PRICE_MISMATCH',409);}else if(lines.some(x=>x.line_kind==='LICENSE'))throw error('LICENSE_RESERVATION_REQUIRED',409);const rule=await one(tx,"SELECT id FROM governance_rules WHERE id=? AND current_status='EFFECTIVE' AND effective_at<=CURRENT_TIMESTAMP(3) FOR SHARE",[id(input.rule_id)]);if(!rule)throw error('RULE_NOT_EFFECTIVE',409);return insert(tx,a,'QUOTE',input.buyer_party_id,input.party_id,null,null,'IN_REVIEW',{lines,installments,total_minor,currency:'CNY',channel:input.channel,transaction_model:input.transaction_model,rule_id:input.rule_id,expires_at:input.expires_at,payment_window_minutes:input.payment_window_minutes,license_reservation_id:input.license_reservation_id,review:null});});});},
 async accept(ctx,input){shape(input,['record_id','party_id','expected_version','quote_sha256','operation_key']);return change(ctx,input,'ACCEPT',async(tx,a,r,i)=>{await owner(tx,a,i.party_id);if(r.kind!=='QUOTE'||r.buyer_party_id!==i.party_id)throw error('TRADE_PARTY_FORBIDDEN');},async(tx,a,q,i)=>{if(q.current_status!=='APPROVED'||q.data&&digest(q.data)!==i.quote_sha256||rules.instant(q.data.expires_at)<=await now(tx))throw error('QUOTE_NOT_ACCEPTABLE',409);if(q.data.license_reservation_id){const r=await reservation(tx,q.data.license_reservation_id,q.buyer_party_id,q.merchant_party_id);if(r.current_status!=='HELD'||rules.instant(r.data.expires_at)<=await now(tx))throw error('LICENSE_RESERVATION_EXPIRED',409);}const rule=await one(tx,'SELECT * FROM governance_rules WHERE id=? FOR SHARE',[q.data.rule_id]);if(!rule)throw error('RULE_NOT_EFFECTIVE',409);const snapshot=sealUnsignedContent({id:randomUUID(),contract_version_id:randomUUID(),party_ids:[q.buyer_party_id,q.merchant_party_id],created_at:new Date(await now(tx)).toISOString(),rules:[{content:parsed(rule.content_json),current_status:rule.current_status,effective_at:new Date(rule.effective_at.replace(' ','T')+'Z').toISOString()}],commitments:{quote_id:q.id,quote_sha256:i.quote_sha256,quote:q.data}});const order=await insert(tx,a,'ORDER',q.buyer_party_id,q.merchant_party_id,q.id,null,'OPEN',{quote:q.data,contract:snapshot,buyer_acknowledged_by:a.id,financial:{received_minor:0,refunded_minor:0,net_minor:0}});if(q.data.license_reservation_id){try{await tx.execute('INSERT INTO trade_license_orders(reservation_id,order_id) VALUES (?,?)',[q.data.license_reservation_id,order.id]);}catch(e){if(e.code==='ER_DUP_ENTRY')throw error('LICENSE_ORDER_ALREADY_EXISTS',409);throw e;}}await save(tx,a,q,'ACCEPTED',{...q.data,order_id:order.id},'QUOTE_ACCEPTED');return order;});},
 async preparePayment(ctx,input,config){shape(input,['party_id','order_id','installment_key','operation_key']);ref(input.installment_key);return db.withTransaction(async tx=>{const a=await actor(tx,ctx);await owner(tx,a,input.party_id);const order=await load(tx,input.order_id,'ORDER');if(order.buyer_party_id!==input.party_id)throw error('TRADE_PARTY_FORBIDDEN');return command(tx,a,'PAYMENT',input,async()=>{if(!['OPEN','PARTIALLY_PAID'].includes(order.current_status))throw error('ORDER_NOT_PAYABLE',409);if(config.provider!==order.data.quote.channel||config.merchant_party_id!==order.merchant_party_id)throw error('PAYMENT_MERCHANT_MISMATCH',409);const step=order.data.quote.installments.find(x=>x.key===input.installment_key);if(!step)throw error('INSTALLMENT_NOT_FOUND',404);if(step.trigger!=='ORDER_ACCEPTED'&&await fulfillmentGate(tx,{order,trigger:step.trigger})!==true)throw error('PAYMENT_MILESTONE_NOT_MET',409);const [payments]=await tx.execute("SELECT * FROM trade_records WHERE kind='PAYMENT' AND order_id=?",[order.id]);if(payments.map(record).some(p=>p.data.installment_key===step.key&&p.current_status!=='CLOSED'))throw error('PAYMENT_ALREADY_OPEN',409);return insert(tx,a,'PAYMENT',order.buyer_party_id,order.merchant_party_id,null,order.id,'CREATED',{provider:config.provider,environment:config.environment,app_id:config.app_id,merchant_id:config.merchant_id,config_revision:config.config_revision,currency:'CNY',amount_minor:rules.sum(step.allocations.map(x=>x.amount_minor)),allocations:step.allocations,installment_key:step.key,apple_product_id:step.apple_product_id,title:order.data.quote.lines[0].title,payment_window_minutes:order.data.quote.payment_window_minutes,expires_at:new Date(await now(tx)+order.data.quote.payment_window_minutes*60000).toISOString(),checkout:null,transaction_id:null,proof:null});});});},
 async paymentForActor(ctx,recordId,party){return db.withTransaction(async tx=>{const a=await actor(tx,ctx),r=await locked(tx,recordId,'PAYMENT');await owner(tx,a,party);if(r.buyer_party_id!==party)throw error('TRADE_NOT_FOUND',404);return r;});},
 async claim(ctx,recordId,party,kind){return db.withTransaction(async tx=>{const a=await actor(tx,ctx),r=await locked(tx,recordId,kind);if(kind==='PAYMENT'){await owner(tx,a,party);if(r.buyer_party_id!==party)throw error('TRADE_NOT_FOUND',404);const order=await load(tx,r.order_id,'ORDER');if(r.current_status==='CREATED'&&!['OPEN','PARTIALLY_PAID'].includes(order.current_status))throw error('ORDER_NOT_PAYABLE',409);}else await reviewer(tx,a,r,'TRADE_REFUND');if(r.current_status!==(kind==='PAYMENT'?'CREATED':'APPROVED'))return {dispatch:false,record:r};return {dispatch:true,record:await save(tx,a,r,'SUBMITTING',r.data,'PROVIDER_DISPATCH_CLAIMED')};});},
 async dispatchResult(recordId,result,unknown=false){return db.withTransaction(async tx=>{const r=await locked(tx,recordId),a=providerActor();if(r.current_status!=='SUBMITTING')return r;const data=r.kind==='PAYMENT'?{...r.data,checkout:unknown?null:result}:r.data;return save(tx,a,r,unknown?'UNKNOWN':r.kind==='REFUND'&&result.status==='AWAITING_APPLE_REQUEST'?'AWAITING_APPLE_REQUEST':'PENDING',data,unknown?'PROVIDER_RESULT_UNKNOWN':'PROVIDER_REQUEST_ACCEPTED');});},
 async applyPayment(proof){proof=Object.fromEntries(["provider","environment","app_id","merchant_id","payment_id","currency","amount_minor","transaction_id","status","product_id","app_account_token"].map(k=>[k,proof[k]]));return db.withTransaction(async tx=>{const r=await locked(tx,proof.payment_id,'PAYMENT'),a=providerActor(),order=await load(tx,r.order_id,'ORDER');rules.paymentMatches({...r.data,id:r.id},proof);if(r.data.transaction_id&&proof.transaction_id&&r.data.transaction_id!==proof.transaction_id)throw error('PAYMENT_TRANSACTION_MISMATCH',409);if(r.current_status==='REFUNDED'&&proof.status==='REVIEW_REQUIRED'){const next=await save(tx,a,r,'REVIEW_REQUIRED',{...r.data,proof},'REFUND_REVERSAL_REVIEW_REQUIRED');await summarize(tx,a,order,true);return next;}if(['REFUNDED','REVIEW_REQUIRED'].includes(r.current_status))return r;if(proof.status==='PENDING'||proof.status==='CLOSED'){if(r.current_status==='SUCCEEDED')return r;if(r.current_status===proof.status)return r;return save(tx,a,r,proof.status,{...r.data,proof},'PAYMENT_OBSERVED');}if(proof.status==='REVIEW_REQUIRED'){const next=await save(tx,a,r,'REVIEW_REQUIRED',{...r.data,proof},'PAYMENT_REVIEW_REQUIRED');await summarize(tx,a,order,true);return next;}
 if(!await one(tx,'SELECT payment_id FROM trade_transactions WHERE payment_id=?',[r.id])){try{await tx.execute('INSERT INTO trade_transactions(provider,environment,transaction_ref,payment_id) VALUES (?,?,?,?)',[proof.provider,proof.environment,proof.transaction_id,r.id]);}catch(e){if(e.code==='ER_DUP_ENTRY')throw error('PAYMENT_TRANSACTION_ALREADY_USED',409);throw e;}await journal(tx,r,'RECEIPT',proof.transaction_id);}
 let duplicateInstallment=false;const paidStep=await one(tx,'SELECT payment_id FROM trade_installments WHERE order_id=? AND installment_key=?',[r.order_id,r.data.installment_key]);if(paidStep)duplicateInstallment=paidStep.payment_id!==r.id;else await tx.execute('INSERT INTO trade_installments(order_id,installment_key,payment_id) VALUES (?,?,?)',[r.order_id,r.data.installment_key,r.id]);
 let next=r;if(r.current_status!=='SUCCEEDED')next=await save(tx,a,r,'SUCCEEDED',{...r.data,transaction_id:proof.transaction_id,proof},'PAYMENT_VERIFIED');if(proof.status==='REFUNDED'){const [old]=await tx.execute("SELECT * FROM trade_records WHERE kind='REFUND' AND parent_id=?",[r.id]);if(old.some(x=>record(x).data.amount_minor!==r.data.amount_minor||record(x).data.provider!=='APPLE'))throw error('APPLE_REFUND_REVIEW_REQUIRED',409);let refund=old.map(record).find(x=>x.current_status!=='REJECTED');if(!refund)refund=await insert(tx,a,'REFUND',r.buyer_party_id,r.merchant_party_id,r.id,r.order_id,'REQUESTED',{payment_id:r.id,provider:r.data.provider,environment:r.data.environment,app_id:r.data.app_id,merchant_id:r.data.merchant_id,currency:r.data.currency,amount_minor:r.data.amount_minor,allocations:r.data.allocations,transaction_id:proof.transaction_id,apple_product_id:r.data.apple_product_id,reason:'Verified full Apple refund',review:null});if(refund.current_status!=='SUCCEEDED'){refund=await save(tx,a,refund,'SUCCEEDED',{...refund.data,proof},'REFUND_VERIFIED');await journal(tx,refund,'REFUND',proof.transaction_id);}next=await save(tx,a,next,'REFUNDED',{...next.data,proof},'PAYMENT_REFUNDED');}
 let late=duplicateInstallment||order.current_status==='CANCELLED'||rules.instant(r.data.expires_at)<await now(tx);if(order.data.quote.license_reservation_id){const lic=await reservation(tx,order.data.quote.license_reservation_id,order.buyer_party_id,order.merchant_party_id);late=late||(lic.current_status!=='COMMITTED'&&(lic.current_status!=='HELD'||rules.instant(lic.data.expires_at)<=await now(tx)));}await summarize(tx,a,order,late);return next;});},
 async requestRefund(ctx,input){input=rules.copy(input);shape(input,['party_id','payment_id','allocations','reason','operation_key']);label(input.reason,2000);rules.allocations(input.allocations);return db.withTransaction(async tx=>{const a=await actor(tx,ctx),p=await locked(tx,input.payment_id,'PAYMENT');await access(tx,a,p,input.party_id);return command(tx,a,'REFUND',input,async()=>{if(p.current_status!=='SUCCEEDED')throw error('PAYMENT_NOT_REFUNDABLE',409);const [rows]=await tx.execute("SELECT * FROM trade_records WHERE kind='REFUND' AND parent_id=? AND current_status NOT IN ('REJECTED','FAILED')",[p.id]);const amount_minor=rules.refundWithin(p.data.allocations,rows.map(x=>record(x).data.allocations),input.allocations);if(p.data.provider==='APPLE'&&amount_minor!==p.data.amount_minor)throw error('APPLE_FULL_REFUND_REQUIRED',409);return insert(tx,a,'REFUND',p.buyer_party_id,p.merchant_party_id,p.id,p.order_id,'REQUESTED',{payment_id:p.id,provider:p.data.provider,environment:p.data.environment,app_id:p.data.app_id,merchant_id:p.data.merchant_id,currency:p.data.currency,amount_minor,allocations:input.allocations,transaction_id:p.data.transaction_id,apple_product_id:p.data.apple_product_id,reason:input.reason,review:null});});});},
 async refundForActor(ctx,recordId,party){return api.read(ctx,{record_id:recordId,party_id:party}).then(r=>{if(r.kind!=='REFUND')throw error('TRADE_NOT_FOUND',404);return r;});},
 async applyRefund(recordId,proof){proof=Object.fromEntries(["provider","environment","app_id","merchant_id","refund_id","payment_id","transaction_id","currency","amount_minor","status"].map(k=>[k,proof[k]]));return db.withTransaction(async tx=>{const r=await locked(tx,recordId,'REFUND'),a=providerActor();if(proof.provider!==r.data.provider||proof.environment!==r.data.environment||proof.app_id!==r.data.app_id||proof.merchant_id!==r.data.merchant_id||proof.refund_id!==r.id||proof.payment_id!==r.parent_id||proof.transaction_id!==r.data.transaction_id||proof.currency!==r.data.currency||proof.amount_minor!==r.data.amount_minor)throw error('REFUND_PROOF_MISMATCH',409);if(r.current_status==='SUCCEEDED')return r;if(!['SUBMITTING','PENDING','UNKNOWN'].includes(r.current_status))throw error('REFUND_NOT_SUBMITTED',409);if(proof.status!=='SUCCEEDED')return r;const next=await save(tx,a,r,'SUCCEEDED',{...r.data,proof},'REFUND_VERIFIED');await journal(tx,next,'REFUND',r.id);await summarize(tx,a,await load(tx,r.order_id,'ORDER'));return next;});},
 async evidenceAsset(ctx,{record_id,asset_id}){return db.withTransaction(async tx=>{const a=await actor(tx,ctx);await reviewer(tx,a,null);const r=await load(tx,record_id,'LEGACY','FOR SHARE');if(r.data.evidence_asset_id!==id(asset_id))throw error('TRADE_NOT_FOUND',404);const row=await one(tx,"SELECT * FROM supply_assets WHERE id=? AND current_status='READY' FOR SHARE",[asset_id]);if(!row||![r.buyer_party_id,r.merchant_party_id].includes(row.owner_party_id))throw error('EVIDENCE_NOT_READY',409);return row;});},
 async legacy(ctx,input){input=rules.copy(input);shape(input,['buyer_party_id','merchant_party_id','source_system','source_order_id','original_lines','original_terms','evidence_asset_id','operation_key']);ref(input.source_system);ref(input.source_order_id);id(input.buyer_party_id);id(input.merchant_party_id);label(input.original_terms,8000);if(!Array.isArray(input.original_lines)||!input.original_lines.length||input.original_lines.length>30)throw error('INVALID_LEGACY_LINES',400);for(const l of input.original_lines){shape(l,['line_id','amount_minor','reported_status']);ref(l.line_id);rules.amount(l.amount_minor,true);if(!['REPORTED_PAID','REPORTED_UNPAID','UNKNOWN'].includes(l.reported_status))throw error('INVALID_LEGACY_STATUS',400);}return db.withTransaction(async tx=>{const a=await actor(tx,ctx);await reviewer(tx,a,null);return command(tx,a,'LEGACY',input,async()=>{const evidence=await one(tx,"SELECT * FROM supply_assets WHERE id=? AND current_status='READY'",[id(input.evidence_asset_id)]);if(!evidence||!['RIGHTS_EVIDENCE','REVIEW_EVIDENCE'].includes(evidence.purpose)||![input.buyer_party_id,input.merchant_party_id].includes(evidence.owner_party_id))throw error('EVIDENCE_NOT_READY',409);const result=await insert(tx,a,'LEGACY',input.buyer_party_id,input.merchant_party_id,null,null,'NEEDS_REVIEW',{source_system:input.source_system,source_order_id:input.source_order_id,original_lines:input.original_lines,original_terms:input.original_terms,evidence_asset_id:input.evidence_asset_id,currency:'CNY',payment_verified:false,review:null});try{await tx.execute('INSERT INTO trade_legacy_keys(source_key,record_id) VALUES (?,?)',[digest([input.source_system,input.source_order_id]),result.id]);}catch(e){if(e.code==='ER_DUP_ENTRY')throw error('LEGACY_ALREADY_IMPORTED',409);throw e;}return result;});});},
 async cancel(ctx,input){shape(input,['record_id','party_id','expected_version','reason','operation_key']);label(input.reason,2000);return change(ctx,input,'CANCEL',async(tx,a,r,i)=>{await access(tx,a,r,i.party_id);},async(tx,a,r,i)=>{if(r.kind!=='ORDER'||r.current_status!=='OPEN')throw error('ORDER_CANNOT_CANCEL',409);const [rows]=await tx.execute("SELECT * FROM trade_records WHERE kind='PAYMENT' AND order_id=?",[r.id]);if(rows.some(x=>!['CREATED','CLOSED'].includes(x.current_status)))throw error('PAYMENT_RECONCILIATION_REQUIRED',409);for(const raw of rows)if(raw.current_status==='CREATED')await save(tx,a,record(raw),'CLOSED',record(raw).data,'UNSENT_PAYMENT_CANCELLED');return save(tx,a,r,'CANCELLED',{...r.data,cancel_reason:i.reason},'ORDER_CANCELLED');});},
 };
 return Object.freeze(api);
}
module.exports={createTradeRepository};
