import assert from 'node:assert/strict'
import {fileURLToPath} from 'node:url'
import {readFile} from 'node:fs/promises'
import {createServer} from 'vite'
import vue from '@vitejs/plugin-vue'
import {createSSRApp,effectScope,h,reactive} from 'vue'
import {renderToString} from '@vue/server-renderer'
import {createPinia} from 'pinia'
import {createRouter,createMemoryHistory,RouterView} from 'vue-router'
const root=fileURLToPath(new URL('..',import.meta.url)),server=await createServer({root,configFile:false,plugins:[vue()],resolve:{alias:{'@':root+'/src'}},server:{middlewareMode:true},appType:'custom'})
const originalFetch=globalThis.fetch,id=n=>String(n).padStart(8,'0')+'-0000-4000-8000-000000000001',hash='a'.repeat(64),who={token:'finance-private-test',accountId:id(1),partyId:id(2)},recipient={...who,partyId:id(3)},reviewer={...who,partyId:null},time='2026-10-01T00:00:00.000Z'
const rules=()=>({version:'explicit-v1',settlement_at:time,release_condition:'RECEIVED',terms:'准确原约定 <script>private</script>',lines:[{line_id:'original-line',shares:[{party_id:id(3),bps:7500,role:'SUPPLIER'},{party_id:id(2),bps:2500,role:'PLATFORM'}],deductions:[]}]})
const review=()=>({decision:'APPROVED',reason:'实际独立核实',verification:{parties_verified:true,contract_verified:true,amount_verified:true,evidence_verified:true},reviewer_account_id:id(8),method:'INDEPENDENT_MANUAL_EVIDENCE_REVIEW'})
const base=(kind,n,status,data)=>({id:id(n),kind,agreement_id:kind==='AGREEMENT'?null:id(10),owner_party_id:id(2),created_by:id(8),current_status:status,object_version:2,content_sha256:hash,data})
const b=(party=id(3))=>({party_id:party,accrued_minor:10005,adjustment_minor:-2,paid_minor:1000,balance_minor:9003})
const records={
 AGREEMENT:()=>base('AGREEMENT',10,'APPROVED',{previous_agreement_id:null,source_type:'ORDER',source_id:id(40),source_sha256:hash,environment:'SANDBOX',currency:'CNY',rule_id:id(30),rule_snapshot:{id:id(30),terms:{clause:'真实采用规则'},version:'v1',rule_key:'FINANCE',content_sha256:hash,format_version:'rule-content-v1'},rules:rules(),parties:[id(2),id(3)],evidence_asset_id:id(32),review:review()}),
 SETTLEMENT:()=>base('SETTLEMENT',11,'APPROVED',{period_reference:'明确期间标签',note:'冻结真实事实说明',facts_sha256:hash,source_references:[{id:id(41),record_id:id(42),direction:'RECEIPT',provider:'ALIPAY',environment:'SANDBOX',external_reference:'actual-ref',amount_minor:10005,sha256:hash}],received_minor:10005,receivable_minor:0,balances:[b()],rule_sha256:hash,review:review()}),
 PAYOUT:()=>base('PAYOUT',12,'REQUESTED',{recipient_party_id:id(3),amount_minor:10005,destination_asset_id:id(32),destination_owner_party_id:id(2),note:'真实付款用途',method:'EXTERNAL_MANUAL_PAYMENT',review:null}),
 PAYOUT_EVIDENCE:()=>base('PAYOUT_EVIDENCE',13,'IN_REVIEW',{payout_id:id(12),recipient_party_id:id(3),outcome:'PAID',amount_minor:10005,external_reference:'actual-bank-ref',occurred_at:time,evidence_asset_id:id(32),note:'实际全额付款凭据',review:null,method:'EXTERNAL_MANUAL_EVIDENCE'}),
 STATEMENT:()=>base('STATEMENT',14,'APPROVED',{external_reference:'actual-channel-statement',period_start:'2026-09-01T00:00:00.000Z',period_end:time,gross_minor:20005,refund_minor:500,channel_fee_minor:300,tax_minor:200,net_minor:19005,direction:'CREDIT',original_statement_id:null,evidence_asset_id:id(32),note:'原应收账单',environment:'SANDBOX',review:review()}),
 RECEIPT:()=>base('RECEIPT',15,'IN_REVIEW',{statement_id:id(14),amount_minor:19005,external_reference:'actual-receipt',occurred_at:time,evidence_asset_id:id(32),note:'实际到账报告',environment:'SANDBOX',review:null}),
 ADJUSTMENT:()=>base('ADJUSTMENT',16,'IN_REVIEW',{entries:[{party_id:id(2),amount_minor:-105},{party_id:id(3),amount_minor:105}],reason:'真实零和调整依据',evidence_asset_id:id(32),review:null}),
 RECONCILIATION:()=>base('RECONCILIATION',17,'DIFFERENCES',{provider:'ALIPAY',environment:'SANDBOX',external_reference:'actual-statement',items:[],facts_sha256:hash,differences:[{record_id:id(42),reason:'MISSING_IN_EXTERNAL_STATEMENT'}],evidence_asset_id:id(32),meaning:'COMPARISON_ONLY_NOT_A_PAYMENT_OR_MANUAL_APPROVAL'}),
 DISPUTE:()=>base('DISPUTE',18,'OPEN',{about_record_id:id(12),category:'SETTLEMENT',reason:'具体异议事实',evidence_asset_ids:[id(32)],decision_history:[]}),
 RESPONSE:()=>base('RESPONSE',19,'RECORDED',{dispute_id:id(18),message:'独立保留的补充说明',evidence_asset_ids:[]}),
}
const balances=()=>({agreement_id:id(10),currency:'CNY',environment:'SANDBOX',customer_payment_separate:true,received_minor:10005,receivable_minor:0,items:[{...b(),expected_accrued_minor:10005,available_minor:4003,recovery_due_minor:0,reason_code:null,meaning:'PAYABLE_NOT_YET_TRANSFERRED'}]})
const readiness=()=>({environment:'SANDBOX',automatic_payout:{current_status:'NOT_IMPLEMENTED',reason_code:'PAYOUT_PROVIDER_NOT_VERIFIED'},manual_payment:{current_status:'IMPLEMENTED',meaning:'records only; actual external payment and independent verification required'}})
const entry=()=>({id:'1',party_id:id(3),amount_minor:-1000,source_id:id(13),category:'PAYOUT',data:{payout_id:id(12),external_reference:'actual-bank-ref',evidence_asset_id:id(32),method:'EXTERNAL_MANUAL_PAYMENT'}})
const confirmation=()=>({party_id:id(3),content_sha256:hash,decision:'APPROVED',reason:'准确本人决定'})
const response=(data,i=who)=>new Response(JSON.stringify({meta:{request_id:'finance-test',actor:{account_id:i.accountId},acting_party:i.partyId},data}),{status:200,headers:{'Content-Type':'application/json'}})
const failure=(status,code)=>new Response(JSON.stringify({error:{code,message:'test',retryable:false,details:[]}}),{status,headers:{'Content-Type':'application/json'}})
const defer=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve}}
const tests=[],test=(name,run)=>tests.push({name,run})
try{
 const api=await server.ssrLoadModule('/src/api/modules/finance.ts'),{useFinance}=await server.ssrLoadModule('/src/composables/useFinance.ts'),{financeRoutes}=await server.ssrLoadModule('/src/router/financeRoutes.ts'),{loginRedirect}=await server.ssrLoadModule('/src/router/loginRedirect.ts')
 const state=(identity=who)=>{const context=reactive({...identity,revision:0,scope:'finance'}),scope=effectScope(),ui=scope.run(()=>useFinance(()=>context));return {ui,context,scope}}
 const command=()=>({path:`/finance/agreements/${id(10)}/payouts`,targetId:id(10),agreementId:id(10),version:2,resultKind:'PAYOUT',label:'原付款申请',body:{recipient_party_id:id(3),amount_minor:10005,destination_asset_id:id(32),note:'原请求用途'}})
 test('十类真实DTO严格kind/嵌套shape/人民币整数分/私有材料，不接受钱包或ready字段',()=>{for(const [kind,f] of Object.entries(records))assert.ok(api.isFinanceRecord(f()),kind);for(const kind of Object.keys(records)){const r=records[kind]();r.data.ready=true;assert.equal(api.isFinanceRecord(r),false,kind)}for(const mutate of [r=>r.content_sha256='fake',r=>r.object_version=0,r=>r.data.rules.lines[0].shares[0].bps=7501,r=>r.data.rule_snapshot.wallet_balance=999]){const r=records.AGREEMENT();mutate(r);assert.equal(api.isFinanceRecord(r),false)}assert.equal(api.isFinanceRecord({...records.PAYOUT(),data:{...records.PAYOUT().data,amount_minor:1.1}}),false);assert.equal(api.isReadiness({...readiness(),automatic_payout:{current_status:'READY'}}),false)})
 test('元/分和百分比精确解析，空白/隐式零/浮点/范围外拒绝；零和调整和扣除归属校验',()=>{for(const v of ['',' ','01','1e2','1.001','9000000000.01','-1','0.1x'])assert.equal(api.parseMoney(v),null);assert.equal(api.parseMoney('100.05'),10005);assert.equal(api.parseMoney('0'),0);assert.equal(api.parseSignedMoney('-1.05'),-105);assert.equal(api.parsePercent('12.50'),1250);assert.equal(api.parsePercent('100.01'),null);assert.equal(api.parsePercent(''),null);const r=records.ADJUSTMENT();r.data.entries[0].amount_minor=0;assert.equal(api.isFinanceRecord(r),false);const rule=rules();rule.lines[0].deductions=[{category:'OTHER',party_id:id(99),amount_minor:1,basis:'明确依据',refund_behavior:'RETAIN'}];assert.equal(api.isRules(rule),false)})
 test('全23真实端点与原body/key/If-Match、OWNER与独审头精确no-store',async()=>{const calls=[],posts=[
 ['agreements','AGREEMENT',null,{source_type:'ORDER',source_id:id(40),previous_agreement_id:null,environment:'SANDBOX',rule_id:id(30),rules:rules(),evidence_asset_id:id(32)},who],
 ['records/'+id(11)+'/confirmations','SETTLEMENT',id(11),{content_sha256:hash,decision:'APPROVED',reason:'准确本人决定'},recipient],
 ['agreements/'+id(10)+'/settlements','SETTLEMENT',id(10),{period_reference:'实际标签',note:'本次事实'},who],
 ['agreements/'+id(10)+'/statements','STATEMENT',id(10),{external_reference:'actual',period_start:'2026-09-01T00:00:00.000Z',period_end:time,gross_minor:10005,refund_minor:0,channel_fee_minor:0,tax_minor:0,direction:'CREDIT',original_statement_id:null,evidence_asset_id:id(32),note:'实际账单'},who],
 ['statements/'+id(14)+'/receipts','RECEIPT',id(14),{amount_minor:19005,external_reference:'actual',occurred_at:time,evidence_asset_id:id(32),note:'实际到账'},who],
 ['agreements/'+id(10)+'/adjustments','ADJUSTMENT',id(10),{entries:records.ADJUSTMENT().data.entries,reason:'真实调整',evidence_asset_id:id(32)},who],
 ['agreements/'+id(10)+'/payouts','PAYOUT',id(10),command().body,who],
 ['payouts/'+id(12)+'/evidence','PAYOUT_EVIDENCE',id(12),{outcome:'PAID',amount_minor:10005,external_reference:'actual',occurred_at:time,evidence_asset_id:id(32),note:'原全额'},who],
 ['payouts/'+id(12)+'/cancellation','PAYOUT',id(12),{reason:'取消尚未执行'},who],
 ['records/'+id(12)+'/disputes','DISPUTE',id(12),{category:'SETTLEMENT',reason:'真实异议',evidence_asset_ids:[id(32)]},who],
 ['disputes/'+id(18)+'/responses','RESPONSE',id(18),{message:'真实回复',evidence_asset_ids:[]},who],
 ['disputes/'+id(18)+'/decisions','DISPUTE',id(18),{decision:'ACTION_REQUIRED',reason:'实际调查',action_record_id:null},reviewer],
 ['records/'+id(14)+'/reviews','STATEMENT',id(14),{decision:'APPROVED',reason:'实际独立核验',verification:review().verification},reviewer],
 ['agreements/'+id(10)+'/reconciliations','RECONCILIATION',id(10),{provider:'ALIPAY',environment:'SANDBOX',external_reference:'actual',items:[],evidence_asset_id:id(32)},who]]
 for(const [path,kind,targetId,body,i] of posts){globalThis.fetch=async(url,o)=>{calls.push({url,o});return response(records[kind](),i)};await api.postFinance(i,{path:'/finance/'+path,resultKind:kind,targetId:targetId||undefined,version:targetId?2:undefined,body,label:'实际操作'},'original-key')}
 globalThis.fetch=async(url,o)=>{calls.push({url,o});return response(url.includes('/balances')?balances():url.includes('/readiness')?readiness():url.includes('/confirmations')?{items:[confirmation()]}:url.includes('/entries')?{items:[entry()],next_cursor:null}:url.includes('/notifications')?{items:[{id:'1',agreement_id:id(10),record_id:id(11),event_code:'FINANCE_CONFIRMATION'}],next_cursor:null}:url.includes('/records?')?{items:[records.SETTLEMENT()],next_cursor:null}:url.includes('/records/')?records.AGREEMENT():{items:[records.AGREEMENT()],next_cursor:null},who)}
 await api.listFinance(who);await api.listFinance(who,id(10),'SETTLEMENT',id(99));await api.getFinance(who,id(10),'AGREEMENT');await api.financeConfirmations(who,id(11));await api.financeReadiness(who,id(10));await api.financeBalances(who,id(10),id(2));await api.financeEntries(who,id(10),id(2),'9');await api.financeNotifications(who,'9');globalThis.fetch=async(url,o)=>{calls.push({url,o});return new Response('private-proof',{headers:{'Content-Type':'application/octet-stream'}})};await api.financeEvidence(reviewer,id(14),id(32));assert.equal(calls.length,23);assert.ok(calls.every(c=>c.o.cache==='no-store'));for(let n=0;n<posts.length;n++){const [, ,targetId,body,i]=posts[n];assert.deepEqual(JSON.parse(calls[n].o.body),body);assert.equal(calls[n].o.headers['If-Match'],targetId?'"2"':undefined);assert.equal(calls[n].o.headers['Idempotency-Key'],'original-key');assert.equal(calls[n].o.headers['X-Acting-Party'],i.partyId??undefined)}assert.equal(calls.at(-1).o.headers['X-Acting-Party'],undefined);assert.ok(calls[15].url.includes('kind=SETTLEMENT&cursor='+id(99)))})
 test('普通参与方SETTLEMENT保留原hash且仅本人余额，全量投影被客户端拒绝',async()=>{const r=records.SETTLEMENT();assert.equal(api.visibleRecord(recipient,r),true);r.data.balances.push(b(id(2)));assert.equal(api.visibleRecord(recipient,r),false);assert.equal(api.visibleRecord(who,r),true);assert.equal(api.visibleRecord(reviewer,r),true);globalThis.fetch=async()=>response(r,recipient);await assert.rejects(api.getFinance(recipient,id(11)),e=>e.code==='UNEXPECTED_RESPONSE_SHAPE');assert.equal(r.content_sha256,hash)})
 test('balances/entries本方隔离及身份echo；不能读取其他方available/账项',async()=>{const foreign=balances();foreign.items[0].party_id=id(2);globalThis.fetch=async()=>response(foreign,recipient);await assert.rejects(api.financeBalances(recipient,id(10),id(2)),e=>e.code==='UNEXPECTED_RESPONSE_SHAPE');globalThis.fetch=async()=>response({items:[{...entry(),party_id:id(2)}],next_cursor:null},recipient);await assert.rejects(api.financeEntries(recipient,id(10),id(2)),e=>e.code==='UNEXPECTED_RESPONSE_SHAPE');globalThis.fetch=async()=>response(records.AGREEMENT(),recipient);await assert.rejects(api.getFinance(who,id(10)),e=>e.code==='UNEXPECTED_RESPONSE_SHAPE')})
 test('列表分页空投影继续下一cursor、错kind/约定和重复cursor拒绝',async()=>{const {ui,scope}=state();let pages=0;globalThis.fetch=async()=>response(++pages===1?{items:[],next_cursor:id(99)}:{items:[records.SETTLEMENT()],next_cursor:null});const all=await ui.loadAll(id(10),'SETTLEMENT');assert.equal(pages,2);assert.equal(all.length,1);globalThis.fetch=async()=>response({items:[records.PAYOUT()],next_cursor:null});assert.equal(await ui.loadAll(id(10),'SETTLEMENT'),null);globalThis.fetch=async()=>response({items:[],next_cursor:id(99)});assert.equal(await ui.loadAll(id(10),'SETTLEMENT'),null);assert.equal(ui.error.value.code,'UNEXPECTED_RESPONSE_SHAPE');scope.stop()})
 test('503与网络断流先核对，同key/body/version恢复，未知阻止路由离开',async()=>{for(const network of [false,true]){const {ui,scope}=state(),calls=[];let posts=0;globalThis.fetch=async(url,o)=>{calls.push({url,o});if(o.method==='POST'&&++posts===1){if(network)throw new Error('network stream failure');return failure(503,'SERVICE_UNAVAILABLE')}return response(url.endsWith('/'+id(10))?records.AGREEMENT():records.PAYOUT())};const c=command();await ui.write(c);c.body.amount_minor=999;assert.equal(ui.pending.value.state,'unknown');assert.equal(ui.canNavigate(),false);await ui.retry();assert.equal(posts,1);await ui.checkPending();assert.equal(ui.pending.value.checked,true);await ui.retry();assert.equal(ui.pending.value,null);const writes=calls.filter(c=>c.o.method==='POST');assert.equal(writes.length,2);assert.equal(writes[0].o.body,writes[1].o.body);assert.equal(writes[0].o.headers['Idempotency-Key'],writes[1].o.headers['Idempotency-Key']);assert.equal(writes[1].o.headers['If-Match'],'"2"');scope.stop()}})
 test('POST已知ID刷新失败仅重新GET结果，不能另写或改金额',async()=>{const {ui,scope}=state();let posts=0;globalThis.fetch=async(url,o)=>o.method==='POST'?(posts++,response(records.PAYOUT())):failure(503,'SERVICE_UNAVAILABLE');await ui.write(command());assert.equal(ui.pending.value.resultId,id(12));globalThis.fetch=async()=>response(records.PAYOUT());await ui.retry();assert.equal(posts,1);assert.equal(ui.pending.value,null);scope.stop()})
 test('准确确认正常POST返回原记录必须GET confirmations，版本不变也能核实',async()=>{const {ui,scope}=state(recipient),calls=[];globalThis.fetch=async(url,o)=>{calls.push({url,o});return response(url.includes('/confirmations')&&o.method!=='POST'?{items:[confirmation()]}:records.SETTLEMENT(),recipient)};await ui.write({path:`/finance/records/${id(11)}/confirmations`,targetId:id(11),agreementId:id(10),version:2,resultKind:'SETTLEMENT',confirmation:true,label:'准确确认',body:{content_sha256:hash,decision:'APPROVED',reason:'准确本人决定'}});assert.equal(ui.pending.value,null);assert.equal(calls.length,3);assert.ok(calls[2].url.endsWith('/confirmations'));assert.equal(JSON.parse(calls[0].o.body).content_sha256,hash);scope.stop()})
 test('确认after-commit503核对四字段实际证据，无升版也不再POST',async()=>{const {ui,scope}=state(recipient);let posts=0;globalThis.fetch=async(url,o)=>o.method==='POST'?(posts++,failure(503,'SERVICE_UNAVAILABLE')):response(url.includes('/confirmations')?{items:[confirmation()]}:records.SETTLEMENT(),recipient);await ui.write({path:`/finance/records/${id(11)}/confirmations`,targetId:id(11),version:2,resultKind:'SETTLEMENT',confirmation:true,label:'准确确认',body:{content_sha256:hash,decision:'APPROVED',reason:'准确本人决定'}});await ui.checkPending();assert.equal(ui.pending.value,null);assert.equal(posts,1);scope.stop()})
 test('确认历史其它主体/旧hash/决定/理由不能假报本方成功',async()=>{for(const changes of [{party_id:id(2)},{content_sha256:'b'.repeat(64)},{decision:'REJECTED'},{reason:'其它理由'}]){const {ui,scope}=state(recipient);globalThis.fetch=async(url,o)=>o.method==='POST'?failure(503,'SERVICE_UNAVAILABLE'):response(url.includes('/confirmations')?{items:[{...confirmation(),...changes}]}:records.SETTLEMENT(),recipient);await ui.write({path:`/finance/records/${id(11)}/confirmations`,targetId:id(11),version:2,resultKind:'SETTLEMENT',confirmation:true,label:'本人确认',body:{content_sha256:hash,decision:'APPROVED',reason:'准确本人决定'}});await ui.checkPending();assert.ok(ui.pending.value);assert.equal(ui.pending.value.checked,true);scope.stop()}})
 test('确认gate为实际约定参与方/已独审且未历史决定；不要求客户端全量他人余额',()=>{assert.ok(api.confirmationGate(records.SETTLEMENT(),records.AGREEMENT(),id(3),[]).can);assert.equal(api.confirmationGate(records.SETTLEMENT(),records.AGREEMENT(),id(99),[]).can,false);assert.equal(api.confirmationGate({...records.SETTLEMENT(),current_status:'IN_REVIEW'},records.AGREEMENT(),id(3),[]).can,false);assert.equal(api.confirmationGate(records.SETTLEMENT(),records.AGREEMENT(),id(3),[confirmation()]).can,false)})
 test('412强制重新读取原记录并清原pending/确认，禁止自动重放',async()=>{const {ui,scope}=state();let posts=0;globalThis.fetch=async(url,o)=>o.method==='POST'?(posts++,failure(412,'VERSION_CONFLICT')):response({...records.AGREEMENT(),object_version:9});await ui.write(command());assert.equal(ui.pending.value,null);assert.equal(ui.conflictRevision.value,1);assert.equal(ui.detail.value.object_version,9);await ui.retry();assert.equal(posts,1);scope.stop()})
 test('401/403/404清私有记录与原File/Blob操作并回收下载URL',async()=>{const createURL=URL.createObjectURL,revokeURL=URL.revokeObjectURL;let revokes=0;URL.createObjectURL=()=> 'blob:finance-test';URL.revokeObjectURL=()=>revokes++;try{for(const status of [401,403,404]){const {ui,scope}=state();ui.detail.value=records.PAYOUT();ui.rows.value=[records.AGREEMENT()];ui.objectUrl(new Blob(['private']));globalThis.fetch=async()=>failure(status,'FINANCE_NOT_FOUND');await ui.write(command());assert.equal(ui.detail.value,null);assert.deepEqual(ui.rows.value,[]);assert.equal(ui.pending.value,null);scope.stop()}assert.equal(revokes,3)}finally{URL.createObjectURL=createURL;URL.revokeObjectURL=revokeURL}})
 test('身份A→B→A、路由、revision和logout忽略迟到读写',async()=>{for(const change of [c=>{c.partyId=id(99);c.partyId=id(2)},c=>c.revision++,c=>c.token=null,c=>c.scope='other']){const {ui,context,scope}=state(),late=defer();globalThis.fetch=()=>late.promise;const task=ui.loadRecord(id(10));change(context);late.resolve(response(records.AGREEMENT()));await task;assert.equal(ui.detail.value,null);scope.stop()}const {ui,context,scope}=state(),late=defer();globalThis.fetch=()=>late.promise;const task=ui.write(command(),()=>assert.fail('late callback'));context.partyId=id(99);late.resolve(response(records.PAYOUT()));await task;assert.equal(ui.pending.value,null);scope.stop()})
 test('上传503保留同Blob/key，实际SHA核对才完成，不接受错误SHA已知结果',async()=>{for(const wrong of [false,true]){const {ui,scope}=state(),blob=new Blob(['original-private-proof']),sha=Buffer.from(await crypto.subtle.digest('SHA-256',await blob.arrayBuffer())).toString('hex'),asset={id:id(32),owner_party_id:id(2),purpose:'RIGHTS_EVIDENCE',media_type:'text/plain',byte_size:blob.size,content_sha256:wrong?hash:sha,current_status:'READY'},calls=[];let posts=0;globalThis.fetch=async(url,o)=>{calls.push({url,o});if(o.method==='POST'&&++posts===1)return failure(503,'SERVICE_UNAVAILABLE');return response(url.includes('/finance/agreements?')?{items:[],next_cursor:null}:asset)};const path='/supply/assets?purpose=RIGHTS_EVIDENCE&media_type=text%2Fplain';await ui.write({path,resultKind:'ASSET',label:'上传',supply:{path,kind:'ASSET',blob,purpose:'RIGHTS_EVIDENCE',mediaType:'text/plain',label:'上传'}});assert.equal(ui.pending.value.command.supply.blob,blob);await ui.checkPending();await ui.retry();const writes=calls.filter(c=>c.o.method==='POST');assert.equal(writes[0].o.body,blob);assert.equal(writes[1].o.body,blob);assert.equal(writes[0].o.headers['Idempotency-Key'],writes[1].o.headers['Idempotency-Key']);if(wrong){assert.equal(ui.pending.value.resultId,id(32));assert.equal(ui.error.value.code,'PRIVATE_CONTENT_MISMATCH')}else assert.equal(ui.pending.value,null);scope.stop()}})
 test('私有证明拒绝HTML和JSON兜底，不产生公开URL',async()=>{globalThis.fetch=async()=>new Response('<html>private forbidden</html>',{headers:{'Content-Type':'text/html'}});await assert.rejects(api.financeEvidence(reviewer,id(14),id(32)));globalThis.fetch=async()=>new Response('verified bytes',{headers:{'Content-Type':'application/octet-stream'}});assert.equal((await api.financeEvidence(reviewer,id(14),id(32))).size,14)})
 test('20图册所有实际路由、safe来源deep link、40菜单与唯一高亮',async()=>{const {projectsRoutes}=await server.ssrLoadModule('/src/router/projectsRoutes.ts'),{productionRoutes}=await server.ssrLoadModule('/src/router/productionRoutes.ts'),{gigsRoutes}=await server.ssrLoadModule('/src/router/gigsRoutes.ts'),{tradeRoutes}=await server.ssrLoadModule('/src/router/tradeRoutes.ts');const paths=[['/finance/agreements','/finance/agreements'],['/finance/agreements/new','/finance/agreements'],[`/finance/agreements/new?sourceType=ORDER&sourceId=${id(40)}`,'/finance/agreements'],[`/finance/agreements/${id(10)}`,'/finance/agreements'],[`/finance/agreements/${id(10)}/confirm`,'/finance/agreements'],[`/finance/agreements/${id(10)}/settlements/new`,'/finance/agreements'],[`/finance/settlements/${id(11)}/confirm`,'/finance/agreements'],[`/finance/agreements/${id(10)}/payouts/new`,'/finance/payouts'],[`/finance/payouts/${id(12)}/evidence`,'/finance/payouts'],[`/finance/agreements/${id(10)}/statements/new`,'/finance/income'],[`/finance/statements/${id(14)}/receipts/new`,'/finance/income'],[`/finance/agreements/${id(10)}/reconciliations/new`,'/finance/income'],[`/finance/records/${id(12)}/disputes/new`,'/finance/disputes'],[`/finance/disputes/${id(18)}/respond`,'/finance/disputes'],[`/finance/agreements/${id(10)}/adjustments/new`,'/finance/disputes'],[`/finance/agreements/${id(10)}/readiness`,'/finance/payouts'],[`/finance/records/${id(19)}`,'/finance/agreements']];for(const section of Object.keys({agreements:1,settlements:1,payouts:1,'payout-evidence':1,revenue:1,adjustments:1,disputes:1}))paths.push([`/finance/reviews/${section}/${id(14)}`,'/finance/reviews/agreements']);for(const [path,current]of paths){assert.equal(loginRedirect(path),path);const router=createRouter({history:createMemoryHistory(),routes:[...financeRoutes,...projectsRoutes,...productionRoutes,...gigsRoutes,...tradeRoutes,{path:'/workspace',component:{render:()=>null}},{path:'/contracts',component:{render:()=>null}},{path:'/:pathMatch(.*)*',component:{render:()=>null}}]}),app=createSSRApp({render:()=>h(RouterView)}).use(createPinia()).use(router);await router.push(path);await router.isReady();assert.ok(router.currentRoute.value.name,path);const html=await renderToString(app),nav=html.match(/<nav\b[^>]*aria-label="工作区导航"[^>]*>([\s\S]*?)<\/nav>/)?.[1];assert.ok(nav);const links=[...nav.matchAll(/<a\b([^>]*)>/g)];assert.equal(links.length,40);assert.deepEqual(links.filter(([,a])=>a.includes('aria-current="page"')).map(([,a])=>a.match(/href="([^"]+)"/)[1]),[current],path)}for(const bad of ['/finance/admin','/finance/agreements/new?sourceType=ORDER&sourceId=bad',`/finance/agreements/new?sourceType=ORDER&sourceId=${id(40)}&grant=FINANCE_REVIEW`,'/finance/agreements?ready=true','//external/finance/agreements','/finance/reviews/receipts','/finance/agreements/bad'])assert.equal(loginRedirect(bad),'/workspace')})
 test('实际SSR规则表单显式无商业默认、原条款转义、金额与待核实文案',async()=>{const {default:Form}=await server.ssrLoadModule('/src/components/FinanceRulesForm.vue'),{default:Panel}=await server.ssrLoadModule('/src/components/FinanceRecordPanel.vue');const d={version:'',time:'',condition:'',terms:'',lines:[{id:'original-line',shares:[{party:'',role:'',percent:''}],fees:[]}]},html=await renderToString(createSSRApp({render:()=>h(Form,{draft:d,parties:[id(2),id(3)]})}));assert.ok(html.includes('finance-share-percent-0-0'));assert.equal(html.includes('value="100"'),false);assert.ok(html.includes('value=""'));for(const kind of Object.keys(records)){const panel=await renderToString(createSSRApp({render:()=>h(Panel,{record:records[kind]()})}));assert.ok(panel.includes(api.kindLabels[kind]));assert.ok(panel.includes('<details'));assert.equal(panel.includes('<script>private</script>'),false)}assert.ok(api.financeStatus({...records.PAYOUT(),current_status:'APPROVED'}).includes('尚未实际付款'));assert.ok(api.financeStatus(records.PAYOUT_EVIDENCE()).includes('尚未记实付'))})
 test('分配表单允许候选以外的明确参与主体，原候选保留，非法编号不可形成约定',async()=>{const {default:Form}=await server.ssrLoadModule('/src/components/FinanceRulesForm.vue');const d={version:'explicit-v1',time:'2026-10-01T00:00',condition:'RECEIVED',terms:'真实外部参与方',lines:[{id:'original-line',shares:[{party:id(2),role:'SUPPLIER',percent:'70'},{party:id(99),role:'PARTICIPANT',percent:'30'}],fees:[]}]};const html=await renderToString(createSSRApp({render:()=>h(Form,{draft:d,parties:[id(2),id(3)]})}));const field=html.match(/<input\b[^>]*data-testid="finance-share-party-0-1"[^>]*>/)?.[0];assert.ok(field,'external participant must be editable through actual form');assert.ok(field.includes('value="'+id(99)+'"'));assert.ok(field.includes('list="finance-source-parties-0-1"'));assert.ok(html.includes('<datalist'));assert.ok(html.includes('value="'+id(3)+'"'));const rule=rules();rule.lines[0].shares[0].party_id=id(99);assert.ok(api.isRules(rule));rule.lines[0].shares[0].party_id='not-a-party';assert.equal(api.isRules(rule),false)})
 test('实际FinanceView独审不依赖me.allowed_actions，参与方拒绝；付款全额/412/响应/来源约束',async()=>{const {useSessionStore}=await server.ssrLoadModule('/src/stores/session.ts'),pinia=createPinia(),session=useSessionStore(pinia);session.token=who.token;session.account={id:id(1),display_name:'有效负责人',current_status:'ACTIVE',object_version:1,allowed_actions:['READ_ACCOUNT']};session.parties=[{party:{id:id(2),display_name:'真实机构',kind:'ORGANIZATION',current_status:'ACTIVE',object_version:1,capabilities:[],allowed_actions:[]},membership:{id:id(70),account_id:id(1),party_id:id(2),roles:['OWNER'],current_status:'ACTIVE',object_version:1,allowed_actions:[]}}];session.selectParty(id(2));const router=createRouter({history:createMemoryHistory(),routes:[...financeRoutes,{path:'/:pathMatch(.*)*',component:{render:()=>null}}]}),app=createSSRApp({render:()=>h(RouterView)}).use(pinia).use(router);let vm;app.mixin({created(){if(this.$options.__name==='FinanceView')vm=this.$.setupState}});await router.push(`/finance/payouts/${id(12)}/evidence`);await router.isReady();await renderToString(app);globalThis.fetch=async(url)=>response(url.endsWith('/'+id(12))?{...records.PAYOUT(),current_status:'APPROVED'}:records.AGREEMENT());await vm.loadPage();vm.form.outcome='PAID';vm.form.amount='100.04';vm.form.reference='actual';vm.form.time='2026-10-01T08:00';vm.form.note='真实付款';vm.assets=[id(32)];let writes=0;globalThis.fetch=async()=>{writes++;return response(records.PAYOUT_EVIDENCE())};await vm.reportEvidence();assert.equal(writes,0);vm.form.amount='100.05';await vm.reportEvidence();assert.ok(writes>=1);session.parties=[];await router.push(`/finance/reviews/payout-evidence/${id(13)}`);await renderToString(app);globalThis.fetch=async(url,o)=>response(url.endsWith('/'+id(13))?records.PAYOUT_EVIDENCE():records.AGREEMENT(),reviewer);await vm.loadPage();assert.equal(vm.independent,true);vm.readAssets=[id(32)];for(const k of Object.keys(api.checks))vm.verification[k]=true;vm.decision='APPROVED';vm.reason='真实独立核实';assert.equal(!!vm.reviewValid,true);const calls=[];globalThis.fetch=async(url,o)=>{calls.push({url,o});return response(url.endsWith('/'+id(10))?records.AGREEMENT():records.PAYOUT_EVIDENCE(),reviewer)};await vm.review();assert.equal(calls.find(c=>c.o.method==='POST').o.headers['X-Acting-Party'],undefined);assert.equal(calls.find(c=>c.o.method==='POST').o.headers['If-Match'],'"2"');session.token=null})
 test('所有20图编号真实映射，桥接保留制作/商单/项目且隐含grant不误禁渠道登记',async()=>{const view=await readFile(root+'/src/views/FinanceView.vue','utf8'),trade=await readFile(root+'/src/views/TradeView.vue','utf8'),projects=await readFile(root+'/src/views/ProjectsView.vue','utf8');for(const picture of ['WEB-27-01','WEB-27-02-v2','WEB-27-03-v3','WEB-28-01-v4','WEB-28-02-v2','WEB-28-03-v2','WEB-28-04-v2','WEB-29-01-v2','WEB-29-02-v2','WEB-29-03-v2','WEB-29-04-v2','WEB-30-01-v2','WEB-30-02-v2','WEB-30-03','WEB-30-04-v2','WEB-31-01-v2','WEB-31-02-v2','WEB-31-03','WEB-31-04-v2','WEB-35-01-v2'])assert.ok(view.includes(picture),picture);assert.ok(trade.includes('trade-finance-agreement'));assert.ok(trade.includes('/production/orders/'));assert.ok(trade.includes('/gigs/commissions'));assert.ok(projects.includes('project-finance-agreement'));assert.equal(projects.includes("canDisplay(session.account?.allowed_actions,'PROJECT_REVIEW')"),false);assert.ok(view.includes("watch(securityRevision,reset,{flush:'sync'})"));assert.ok(view.includes('finance-reconfirm'));assert.ok(view.includes('form.amount)!==r.data.amount_minor'))})
 for(const {name,run} of tests){await run();console.log('✓ '+name)}console.log('\n'+tests.length+' finance checks passed.')
}finally{globalThis.fetch=originalFetch;await server.close()}
