import assert from 'node:assert/strict'
import { fileURLToPath } from 'node:url'
import { createServer } from 'vite'
import vue from '@vitejs/plugin-vue'
import { createSSRApp, effectScope, h, reactive, nextTick } from 'vue'
import { renderToString } from '@vue/server-renderer'
import { createPinia } from 'pinia'
import { createMemoryHistory, createRouter, RouterView } from 'vue-router'
const root=fileURLToPath(new URL('..',import.meta.url)),server=await createServer({root,configFile:false,plugins:[vue()],resolve:{alias:{'@':`${root}/src`}},server:{middlewareMode:true},appType:'custom'})
const originalFetch=globalThis.fetch,oldWindow=globalThis.window,oldDocument=globalThis.document,storageProperty=Object.getOwnPropertyDescriptor(globalThis,'sessionStorage'),store=new Map()
globalThis.window={setInterval:()=>0,clearInterval:()=>{},setTimeout:()=>0,addEventListener:()=>{},removeEventListener:()=>{}}
Object.defineProperty(globalThis,'sessionStorage',{configurable:true,value:{getItem:k=>store.get(k)??null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k)}})
const id=n=>`${String(n).padStart(8,'0')}-0000-4000-8000-000000000001`,hash='a'.repeat(64),until='2027-10-01T00:00:00.000Z',from='2026-09-01T00:00:00.000Z',who={token:'test-gigs',accountId:id(1),partyId:id(2)},admin={...who,partyId:null},mcn={...who,partyId:id(3)}
const rule=()=>({version:'explicit-v1',terms:'完整规则 <script>literal</script>',categories:[{code:'FOOD',allowed:true,required_proofs:['RIGHTS']},{code:'FORBIDDEN',allowed:false,required_proofs:[]}],ranking:{window_days:30,newcomer_days:60,minimum_orders:1,order_weight:20,net_minor_weight:2,newcomer_bonus:4}})
const scope=()=>({purpose:'COMMERCIAL',territory:'CN',valid_until:until}),commission=()=>({platform_bps:1234,mcn_bps:234}),rel=()=>({id:id(11),version:2,sha256:hash,mcn_party_id:id(3),terms:'旧MCN原条款',valid_from:from,valid_until:until})
const agreement=()=>({ranking_opt_in:true,offer_id:id(13),offer_sha256:hash,gig_id:id(12),scope:scope(),category:'FOOD',terms:'原完整提案条款',commission:commission(),relation:rel(),avatar_id:id(20),consent_id:id(21),rule_id:id(10)})
const facts=()=>({received_minor:10001,refunded_minor:100,net_minor:9901,environment:'PRODUCTION',first_at:100000,journal_ids:[id(22)]}),amounts=()=>({net_minor:9901,supplier_minor:8680,platform_minor:990,mcn_minor:231})
const review=()=>({decision:'APPROVED',reason:'实际人工依据',checks:{identity_verified:true,authority_verified:true,materials_reviewed:true,content_reviewed:true,marking_reviewed:true},account_id:id(5),method:'EXTERNAL_MANUAL_REVIEW'})
const base=(kind,n,status,data)=>({id:id(n),kind,owner_party_id:kind==='RULE'||kind==='RANKING'?null:id(2),counterparty_id:kind==='RELATION'||kind==='OFFER'||kind==='COMMISSION'?id(4):null,parent_id:kind==='OFFER'?id(12):kind==='COMMISSION'?id(13):kind==='RANKING'?id(10):null,created_by:id(6),current_status:status,object_version:2,content_sha256:hash,data})
const records={RULE:()=>base('RULE',10,'EFFECTIVE',{rule:rule(),review:{...review(),checks:null}}),RELATION:()=>({...base('RELATION',11,'ENDED',{scope:'COMMERCIAL',valid_from:from,valid_until:until,exclusive:false,terms:'旧直接合作',commission:commission(),evidence_asset_ids:[id(30)],accepted_by:id(4),ended_reason:'已结束'}),owner_party_id:id(3),counterparty_id:id(2)}),GIG:()=>base('GIG',12,'PUBLISHED',{title:'真实商业需求',brief:'完整需求',category:'FOOD',scope:scope(),rule_id:id(10),rule_sha256:hash,proofs:[{code:'RIGHTS',asset_id:id(30)}],review:review(),suspension:null}),OFFER:()=>base('OFFER',13,'APPROVED',{ranking_opt_in:true,spec_id:id(23),avatar_id:id(20),consent_id:id(21),relation:rel(),commission:commission(),terms:'保存的原提案 <script>literal</script>',evidence_asset_ids:[id(30)],review:review(),buyer_accepted_by:null}),COMMISSION:()=>base('COMMISSION',14,'CALCULATED',{order_id:id(24),contract_sha256:hash,agreement:agreement(),relation:rel(),facts:facts(),amounts:amounts(),currency:'CNY',paid_out_minor:0,meaning:'ACCRUAL_ONLY_NOT_TRANSFERRED'}),RANKING:()=>base('RANKING',15,'PUBLISHED',{as_of:'2026-10-01T00:00:00.000Z',rule_id:id(10),rule_sha256:hash,rule:rule().ranking,source:'VERIFIED_PRODUCTION_COMMERCIAL_RECEIPTS',facts:[],boards:{hot:[],emerging:[],regional:[]},data_status:'INSUFFICIENT_DATA'})}
const catalogue=()=>({rules:[{id:id(10),rule:rule()}],items:[{id:id(12),title:'真实商业需求',brief:'完整需求',category:'FOOD',scope:scope(),buyer_party_id:id(4)}]})
const publicRanking=()=>{const r=records.RANKING();return {id:r.id,as_of:r.data.as_of,rule_id:r.data.rule_id,rule:r.data.rule,source:r.data.source,data_status:r.data.data_status,boards:r.data.boards}}
const response=(data,i=who)=>new Response(JSON.stringify({meta:{request_id:'gigs-test',actor:{account_id:i.accountId},acting_party:i.partyId},data}),{headers:{'Content-Type':'application/json'}})
const failure=(status,code)=>new Response(JSON.stringify({error:{code,message:'test',retryable:false,details:[]}}),{status,headers:{'Content-Type':'application/json'}})
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve}}
const tests=[],test=(name,run)=>tests.push({name,run})
try{
 const api=await server.ssrLoadModule('/src/api/modules/gigs.ts'),trade=await server.ssrLoadModule('/src/api/modules/trade.ts'),{useGigs}=await server.ssrLoadModule('/src/composables/useGigs.ts'),{gigsRoutes}=await server.ssrLoadModule('/src/router/gigsRoutes.ts'),{tradeRoutes}=await server.ssrLoadModule('/src/router/tradeRoutes.ts'),{loginRedirect}=await server.ssrLoadModule('/src/router/loginRedirect.ts')
 const state=(i=who)=>{const context=reactive({...i,revision:0,scope:'gigs'}),s=effectScope(),ui=s.run(()=>useGigs(()=>context));return {ui,context,s}}
 const command=()=>({path:`/gigs/offers/${id(13)}/acceptance`,body:{offer_sha256:hash},version:2,targetId:id(13),resultKind:'OFFER',label:'确认提案'})
 test('合作名称限定双方、旧服务器404兼容，403/503不得假成功',async()=>{
 const r=records.RELATION(),names={record_id:r.id,source:'CURRENT_DISPLAY_NAME',parties:[{party_id:r.owner_party_id,display_name:'测试MCN <script>literal</script>'},{party_id:r.counterparty_id,display_name:'测试合作人'}]};
 globalThis.fetch=async()=>response(names);assert.deepEqual(await api.getRelationParties(who,r),names);
 for(const invalid of [{...names,record_id:id(99)},{...names,parties:[names.parties[0],names.parties[0]]},{...names,parties:[{...names.parties[0],phone:'private'},names.parties[1]]}]){globalThis.fetch=async()=>response(invalid);await assert.rejects(api.getRelationParties(who,r),e=>e.code==='UNEXPECTED_RESPONSE_SHAPE')}
 globalThis.fetch=async()=>failure(404,'NOT_FOUND');assert.equal(await api.getRelationParties(who,r),null);
 globalThis.fetch=async()=>failure(404,'GIG_NOT_FOUND');await assert.rejects(api.getRelationParties(who,r));
 for(const code of [403,503]){globalThis.fetch=async()=>failure(code,'SERVICE_UNAVAILABLE');await assert.rejects(api.getRelationParties(who,r))}
 const {default:Panel}=await server.ssrLoadModule('/src/components/GigRecordPanel.vue');
 const html=await renderToString(createSSRApp({render:()=>h(Panel,{record:r,relationParties:names})}));
 assert.ok(html.includes('测试合作人'));assert.ok(html.includes('&lt;script&gt;literal&lt;/script&gt;'));assert.ok(html.includes(r.owner_party_id));assert.ok(html.includes('不代表已核实的法定名称'));
 const fallback=await renderToString(createSSRApp({render:()=>h(Panel,{record:r,relationParties:{...names,record_id:id(99)}})}));assert.ok(fallback.includes('名称暂未提供'));assert.equal(fallback.includes('测试合作人'),false);
 })
 test('六类实际DTO逐种验证；拒绝伪公开地址、错误类型、金额和商业范围',async()=>{for(const make of Object.values(records))assert.ok(api.isGigRecord(make()));const changes=[['OFFER',r=>r.data.commission.mcn_bps=2000],['GIG',r=>r.data.scope.purpose='PRIVATE'],['RELATION',r=>r.data.exclusive='false'],['COMMISSION',r=>r.data.amounts.net_minor++],['COMMISSION',r=>r.data.paid_out_minor=1],['RULE',r=>r.data.rule.ranking.window_days=0],['RANKING',r=>r.data.boards.hot=[{public_url:'https://invalid'}]]];for(const [k,change]of changes){const r=records[k]();change(r);assert.equal(api.isGigRecord(r),false)}const many=records.RULE();many.data.rule.categories[0].required_proofs=Array.from({length:21},(_,n)=>`p${n}`);assert.equal(api.isGigRecord(many),false)})
 test('18个真实API：ordinary party、独立无party、If-Match与exact acceptance',async()=>{const calls=[];globalThis.fetch=async(url,o)=>{calls.push({url,o});const i=o.headers['X-Acting-Party']?who:admin;if(url.endsWith('/catalogue'))return response(catalogue(),admin);if(url.endsWith('/notifications'))return response({items:[]});if(url.includes('/entries'))return response({items:[]});if(url.includes('/evidence/'))return new Response('private',{headers:{'Content-Type':'application/octet-stream'}});if(url.includes('/rankings/')&&o.method!=='POST')return response(publicRanking(),admin);if(url.includes('/records?'))return response({items:[],next_cursor:null},i);const kind=url.endsWith('/retirement')||url.endsWith('/rules')?'RULE':url.includes('/relation')?'RELATION':url.includes('/request')?'GIG':url.includes('/commission')?'COMMISSION':url.endsWith('/rankings')?'RANKING':url.includes('/records/')&&url.endsWith('/reviews')?'GIG':'OFFER';return response(records[kind](),i)}
 const posts=[['rules','RULE',admin,{rule:rule()}],['rules/'+id(10)+'/retirement','RULE',admin,{reason:'退役'}],['records/'+id(12)+'/reviews','GIG',admin,{decision:'APPROVED',reason:'实际依据',checks:review().checks}],['relations','RELATION',who,{artist_party_id:id(4)}],['relations/'+id(11)+'/decision','RELATION',who,{decision:'ACCEPT',reason:'本人明确接受'}],['requests','GIG',who,{title:'明确需求'}],['requests/'+id(12)+'/suspension','GIG',admin,{reason:'暂停'}],['offers','OFFER',who,{gig_id:id(12)}],['offers/'+id(13)+'/acceptance','OFFER',who,{offer_sha256:hash}],['commissions','COMMISSION',who,{order_id:id(24)}],['rankings','RANKING',admin,{rule_id:id(10),as_of:'2026-10-01T00:00:00.000Z'}]]
 for(const [path,kind,i,body]of posts)await api.postGig(i,{path:'/gigs/'+path,body,resultKind:kind,version:path.includes(id(10))||path.includes(id(11))||path.includes(id(12))||path.includes(id(13))?2:undefined,label:'test'},'original-key')
 await api.listGigs(who,'OFFER',id(99));await api.getGig(who,id(13),'OFFER');await api.getCatalogue(who);await api.getNotifications(who);await api.getRanking(who,id(15));await api.getEntries(who,id(14));await api.gigEvidence(admin,id(12),id(30));assert.equal(calls.length,18);assert.ok(calls.every(c=>c.o.cache==='no-store'));for(let n=0;n<11;n++){assert.equal(calls[n].o.headers['X-Acting-Party'],posts[n][2].partyId??undefined);assert.equal(calls[n].o.headers['Idempotency-Key'],'original-key')}assert.deepEqual(JSON.parse(calls[8].o.body),{offer_sha256:hash});assert.equal(calls[8].o.headers['If-Match'],'"2"');assert.equal(calls[9].o.headers['If-Match'],undefined);assert.equal(calls[10].o.headers['If-Match'],undefined);assert.equal(calls[13].o.headers['X-Acting-Party'],undefined);assert.equal(calls[15].o.headers['X-Acting-Party'],undefined)})
 test('actor/party/kind/id/可见性不匹配拒绝；分页不能循环',async()=>{for(const bad of [()=>response(records.OFFER(),mcn),()=>response(records.GIG()),()=>response({...records.OFFER(),id:id(99)}),()=>response({...records.OFFER(),owner_party_id:id(99),counterparty_id:id(98),data:{...records.OFFER().data,relation:null}})]){globalThis.fetch=async()=>bad();await assert.rejects(api.getGig(who,id(13),'OFFER'),e=>e.code==='UNEXPECTED_RESPONSE_SHAPE')}const {ui,s}=state();globalThis.fetch=async()=>response({items:[records.OFFER()],next_cursor:id(99)});await ui.loadAll('OFFER');assert.equal(ui.error.value.code,'UNEXPECTED_RESPONSE_SHAPE');s.stop()})
 test('503/网络断流未知写入先核对原记录，同key/body/version且阻止导航',async()=>{for(const network of [false,true]){const {ui,s}=state(),calls=[];let posts=0;globalThis.fetch=async(url,o)=>{calls.push({url,o});if(o.method==='POST'&&++posts===1){if(network)throw new Error('network');return failure(503,'SERVICE_UNAVAILABLE')}return response({...records.OFFER(),current_status:'ACCEPTED',data:{...records.OFFER().data,buyer_accepted_by:id(1)}})};const c=command();await ui.write(c);c.body.offer_sha256='b'.repeat(64);assert.equal(ui.pending.value.state,'unknown');assert.equal(ui.canNavigate(),false);await ui.retry();assert.equal(posts,1);await ui.checkPending();assert.equal(ui.pending.value.checked,true);await ui.retry();assert.equal(ui.pending.value,null);const sent=calls.filter(x=>x.o.method==='POST');assert.equal(sent.length,2);assert.equal(sent[0].o.headers['Idempotency-Key'],sent[1].o.headers['Idempotency-Key']);assert.equal(sent[0].o.body,sent[1].o.body);assert.equal(sent[1].o.headers['If-Match'],'"2"');s.stop()}})
 test('已知POST结果刷新失败保留ID，只GET恢复，绝不再POST',async()=>{const {ui,s}=state();let posts=0,gets=0;globalThis.fetch=async(url,o)=>{if(o.method==='POST'){posts++;return response(records.OFFER())}if(++gets===1)return failure(503,'SERVICE_UNAVAILABLE');return response(records.OFFER())};await ui.write(command());assert.equal(ui.pending.value.resultId,id(13));await ui.retry();assert.equal(ui.pending.value,null);assert.equal(posts,1);assert.equal(gets,2);s.stop()})
 test('412先读最新版本再触发重新确认，旧动作不自动重放',async()=>{const {ui,s}=state();let posts=0;globalThis.fetch=async(url,o)=>o.method==='POST'?(posts++,failure(412,'VERSION_CONFLICT')):response({...records.OFFER(),object_version:5});await ui.write(command());assert.equal(ui.detail.value.object_version,5);assert.equal(ui.conflictRevision.value,1);assert.equal(ui.pending.value,null);await ui.retry();assert.equal(posts,1);s.stop()})
 test('上传503保留同一个原Blob，核对后同key重试；用原字节SHA核实result',async()=>{const {ui,s}=state(),blob=new Blob(['original-proof']),digest=await crypto.subtle.digest('SHA-256',await blob.arrayBuffer()),sha=Buffer.from(digest).toString('hex'),asset={id:id(30),owner_party_id:id(2),purpose:'RIGHTS_EVIDENCE',media_type:'text/plain',byte_size:blob.size,content_sha256:sha,current_status:'READY'},calls=[];let posts=0;globalThis.fetch=async(url,o)=>{calls.push({url,o});if(o.method==='POST'&&++posts===1)return failure(503,'SERVICE_UNAVAILABLE');return response(url.includes('/gigs/records?')?{items:[],next_cursor:null}:asset)};let done;await ui.write({path:'/supply/assets?purpose=RIGHTS_EVIDENCE&media_type=text%2Fplain',kind:'ASSET',resultKind:'ASSET',blob,purpose:'RIGHTS_EVIDENCE',mediaType:'text/plain',label:'上传'},r=>done=r);assert.equal(ui.pending.value.command.blob,blob);await ui.checkPending();await ui.retry();assert.equal(done.id,id(30));const p=calls.filter(c=>c.o.method==='POST');assert.equal(p[0].o.body,p[1].o.body);assert.equal(p[0].o.headers['Idempotency-Key'],p[1].o.headers['Idempotency-Key']);s.stop()})
 test('错误上传指纹保留已知resultId，不显示上传完成',async()=>{const {ui,s}=state(),blob=new Blob(['proof']),asset={id:id(30),owner_party_id:id(2),purpose:'RIGHTS_EVIDENCE',media_type:'text/plain',byte_size:5,content_sha256:hash,current_status:'READY'};globalThis.fetch=async()=>response(asset);await ui.write({path:'/supply/assets?purpose=RIGHTS_EVIDENCE&media_type=text%2Fplain',kind:'ASSET',resultKind:'ASSET',blob,purpose:'RIGHTS_EVIDENCE',mediaType:'text/plain',label:'上传'},()=>assert.fail('wrong bytes accepted'));assert.equal(ui.pending.value.resultId,id(30));assert.equal(ui.error.value.code,'PRIVATE_CONTENT_MISMATCH');s.stop()})
 test('401/403/404清空私有DTO与pending，身份/会话/路由变化忽略迟到响应',async()=>{for(const status of [401,403,404]){const {ui,s}=state();ui.rows.value=[records.OFFER()];ui.detail.value=records.OFFER();globalThis.fetch=async()=>failure(status,'GIG_PARTY_FORBIDDEN');await ui.write(command());assert.equal(ui.detail.value,null);assert.deepEqual(ui.rows.value,[]);assert.equal(ui.pending.value,null);s.stop()}for(const change of [c=>{c.partyId=id(99);c.partyId=id(2)},c=>c.revision++,c=>c.scope='other',c=>c.token=null]){const {ui,s,context}=state(),late=deferred();globalThis.fetch=()=>late.promise;const p=ui.write(command(),()=>assert.fail('late private result'));change(context);late.resolve(response(records.OFFER()));await p;assert.equal(ui.detail.value,null);assert.equal(ui.pending.value,null);s.stop()}})
 test('私有材料只走记录evidence字节接口；权限失败清理，对象URL身份变化回收',async()=>{const {ui,s,context}=state(),created=[],revoked=[],originalCreate=URL.createObjectURL,originalRevoke=URL.revokeObjectURL;URL.createObjectURL=()=>{created.push('blob:test');return 'blob:test'};URL.revokeObjectURL=u=>revoked.push(u);globalThis.document={createElement:()=>({click(){},href:'',download:''})};try{let call;globalThis.fetch=async(url,o)=>{call={url,o};return new Response('authorized-proof',{headers:{'Content-Type':'application/octet-stream'}})};await ui.downloadEvidence(id(12),id(30));assert.equal(call.url,`/api/v1/gigs/records/${id(12)}/evidence/${id(30)}`);assert.equal(call.o.cache,'no-store');context.revision++;assert.deepEqual(revoked,['blob:test']);globalThis.fetch=async()=>new Response('<html>public</html>',{headers:{'Content-Type':'text/html'}});await ui.downloadEvidence(id(12),id(30));assert.equal(created.length,1);globalThis.fetch=async()=>failure(403,'GIG_PARTY_FORBIDDEN');await ui.downloadEvidence(id(12),id(30));assert.equal(ui.detail.value,null)}finally{URL.createObjectURL=originalCreate;URL.revokeObjectURL=originalRevoke;s.stop()}})
 test('人民币整数分BigInt floor，MCN只分平台费；累计退款产生负delta而非支付',async()=>{assert.deepEqual(api.commissionSplit(9901,commission()),amounts());assert.deepEqual(api.commissionSplit(101,{platform_bps:1000,mcn_bps:333}),{net_minor:101,supplier_minor:91,platform_minor:7,mcn_minor:3});const before=api.commissionSplit(10001,commission()),after=api.commissionSplit(9901,commission());assert.equal(after.supplier_minor-before.supplier_minor,-87);assert.equal(after.platform_minor-before.platform_minor,-10);assert.equal(after.mcn_minor-before.mcn_minor,-3);for(const v of ['', '1.2','1e3','-1','10001'])assert.equal(api.basisInput(v),null);assert.equal(api.basisInput('0'),0);assert.throws(()=>api.commissionSplit(-1,commission()));assert.equal(api.isCommissionTerms({platform_bps:5,mcn_bps:6}),false)})
 test('榜单UTC完整历史日期、public summary拒绝私有fact/order/流水，不模拟INSUFFICIENT_DATA',async()=>{assert.ok(api.rankingDate('2026-10-01T00:00:00.000Z'));for(const v of ['2026-10-01','2026-10-01T12:00:00.000Z','2099-01-01T00:00:00.000Z','2026-02-30T00:00:00.000Z'])assert.equal(api.rankingDate(v),false);assert.ok(api.isPublicRanking(publicRanking()));assert.equal(api.isPublicRanking({...publicRanking(),facts:[]}),false);const pub=publicRanking();pub.boards.hot=[{party_id:id(2),territory:'CN',orders:1,heat:'999999999999999999999',emerging:'-2',order_id:id(24)}];assert.equal(api.isPublicRanking(pub),false)})
 test('重新下载失败不保留上次成功提示，恢复后可再次读取',async()=>{const {ui,s}=state();globalThis.document={createElement:()=>({click(){},href:'',download:''})};try{globalThis.fetch=async()=>new Response('authorized-proof',{headers:{'Content-Type':'application/octet-stream'}});await ui.downloadEvidence(id(12),id(30));assert.ok(ui.notice.value.includes('已按当前权限读取'));globalThis.fetch=async()=>failure(503,'GIG_EVIDENCE_UNAVAILABLE');await ui.downloadEvidence(id(12),id(30));assert.equal(ui.notice.value,'');assert.equal(ui.error.value.status,503);globalThis.fetch=async()=>new Response('authorized-proof',{headers:{'Content-Type':'application/octet-stream'}});await ui.downloadEvidence(id(12),id(30));assert.ok(ui.notice.value.includes('已按当前权限读取'));assert.equal(ui.error.value,null)}finally{s.stop()}})
 test('本人数字人/同意真实分页与scope，伪实名状态和错kind拒绝',async()=>{const avatar={id:id(20),kind:'AVATAR',stream_ref:id(20),revision:1,created_by:id(1),owner_party_id:id(2),current_status:'RECORDED',object_version:1,data:{display_name:'本人数字人',material_asset_ids:[id(30)],provider_asset_ref:null}},consent={...avatar,id:id(21),kind:'CONSENT',current_status:'APPROVED',data:{consent:{avatar_id:id(20),subject_party_id:id(2),features:['FACE','VOICE'],purposes:['COMMERCIAL'],territories:['CN'],valid_from:from,valid_until:until,terms:'本人明确商业条款',evidence_asset_ids:[id(30)]},review:null,withdrawal:null,signing_method:'IN_APP_DECLARATION',identity_verification:'NOT_VERIFIED'}};assert.ok(api.isCommercialSupply(avatar));assert.ok(api.isCommercialSupply(consent));assert.equal(api.isCommercialSupply({...consent,data:{...consent.data,identity_verification:'VERIFIED'}}),false);globalThis.fetch=async()=>response({items:[avatar],next_cursor:null});assert.equal((await api.listCommercialSupply(who,'AVATAR')).length,1);await assert.rejects(api.listCommercialSupply(who,'CONSENT'),e=>e.code==='UNEXPECTED_RESPONSE_SHAPE')})
 test('真实SSR条款转义、价格空白、人工五核验与出款边界',async()=>{const {default:Panel}=await server.ssrLoadModule('/src/components/GigRecordPanel.vue'),{default:RuleForm}=await server.ssrLoadModule('/src/components/GigRuleForm.vue');for(const r of [records.RULE(),records.OFFER(),records.COMMISSION()]){const html=await renderToString(createSSRApp({render:()=>h(Panel,{record:r})}));assert.equal(html.includes('<script>literal</script>'),false);if(r.kind==='OFFER')assert.ok(html.includes('&lt;script&gt;literal&lt;/script&gt;'));if(r.kind==='COMMISSION'){assert.ok(html.includes('未出款'));assert.ok(html.includes('税务接口尚未开放'));assert.ok(html.includes('¥99.01'))}}const html=await renderToString(createSSRApp({render:()=>h(RuleForm,{disabled:false})}));assert.ok(html.includes('类别、禁品与证明要求'));assert.ok(html.includes('最低有效订单数'));assert.equal(/value="(?:30|60|1000|1234)"/.test(html),false)})
 test('12真实页面路由/原trade桥接、单一菜单、safe deep link与全40入口共享',async()=>{for(const [path,current]of [['/gigs/catalogue','/gigs/catalogue'],['/gigs/requests/new','/gigs/catalogue'],[`/gigs/reviews/requests/${id(12)}`,'/gigs/reviews/requests'],['/gigs/offers/new','/gigs/catalogue'],[`/gigs/reviews/offers/${id(13)}`,'/gigs/reviews/requests'],[`/gigs/offers/${id(13)}`,'/gigs/catalogue'],['/gigs/relations/new','/gigs/relations'],[`/gigs/relations/${id(11)}`,'/gigs/relations'],[`/gigs/commissions/${id(14)}`,'/gigs/commissions'],['/gigs/rules/new','/gigs/reviews/rules'],[`/gigs/reviews/rules/${id(10)}`,'/gigs/reviews/rules'],[`/gigs/rankings/${id(15)}`,'/gigs/rankings'],[`/trade/offers/${id(13)}/quote`,'/trade/quotes'],[`/gigs/offers/new?gigId=${id(12)}`,'/gigs/catalogue']]){assert.equal(loginRedirect(path),path);const router=createRouter({history:createMemoryHistory(),routes:[...gigsRoutes,...tradeRoutes,{path:'/:pathMatch(.*)*',component:{render:()=>null}}]}),app=createSSRApp({render:()=>h(RouterView)}).use(createPinia()).use(router);await router.push(path);await router.isReady();assert.notEqual(router.currentRoute.value.name,undefined);const html=await renderToString(app),nav=html.match(/<nav\b[^>]*aria-label="工作区导航"[^>]*>([\s\S]*?)<\/nav>/)?.[1];assert.ok(nav);const links=[...nav.matchAll(/<a\b([^>]*)>/g)];assert.equal(links.length,40);assert.deepEqual(links.filter(([,a])=>a.includes('aria-current="page"')).map(([,a])=>a.match(/href="([^"]+)"/)[1]),[current])}for(const bad of ['/gigs/admin','/gigs/offers/new?gigId=bad',`/gigs/offers/new?gigId=${id(12)}&role=GIG_REVIEW`,'/gigs/rankings?permission=GIG_REVIEW','/gigs/offers/../../admin','//foreign/gigs/offers'])assert.equal(loginRedirect(bad),'/workspace')})
 test('真实GigsView MCN详情按钮可据原COMMISSION重算，无trade列表/未获准链接',async()=>{const {useSessionStore}=await server.ssrLoadModule('/src/stores/session.ts'),pinia=createPinia(),session=useSessionStore(pinia);session.token=mcn.token;session.account={id:id(1),display_name:'MCN测试',current_status:'ACTIVE',object_version:1,allowed_actions:[]};session.parties=[{party:{id:id(3),display_name:'实际MCN',kind:'ORGANIZATION',current_status:'ACTIVE',object_version:1,capabilities:[{code:'MCN',current_status:'ACTIVE',allowed_actions:[]}],allowed_actions:[]},membership:{id:id(40),account_id:id(1),party_id:id(3),roles:['OWNER'],current_status:'ACTIVE',object_version:1,allowed_actions:[]}}];session.selectParty(id(3));const router=createRouter({history:createMemoryHistory(),routes:[...gigsRoutes,...tradeRoutes,{path:'/:pathMatch(.*)*',component:{render:()=>null}}]}),app=createSSRApp({render:()=>h(RouterView)}).use(pinia).use(router);let vm;app.mixin({created(){if(this.$options.__name==='GigsView')vm=this.$.setupState}});await router.push(`/gigs/commissions/${id(14)}`);await router.isReady();await renderToString(app);assert.ok(vm?.calculate);const calls=[];globalThis.fetch=async(url,o)=>{calls.push({url,o});return response(url.includes('/entries')?{items:[]}:records.COMMISSION(),mcn)};await vm.loadPage();assert.equal(calls.some(c=>c.url.includes('/trade/records')),false);assert.equal(vm.detail.id,id(14));vm.orderId=vm.detail.data.order_id;vm.calculate();for(let n=0;n<10&&vm.pending;n++)await new Promise(r=>setTimeout(r,2));const post=calls.find(c=>c.o.method==='POST');assert.ok(post);assert.equal(post.url,'/api/v1/gigs/commissions');assert.deepEqual(JSON.parse(post.o.body),{order_id:id(24)});assert.equal(post.o.headers['X-Acting-Party'],id(3));assert.equal(post.o.headers['If-Match'],undefined);assert.equal(vm.pending,null);assert.ok(api.commissionOrderAllowed(id(24),[],records.COMMISSION()));assert.equal(api.commissionOrderAllowed(id(99),[],records.COMMISSION()),false);const {default:View}=await server.ssrLoadModule('/src/views/GigsView.vue');const loaded={...vm,initializing:false};const rendered=await renderToString(createSSRApp({...View,setup:()=>loaded}).use(pinia).use(router));assert.ok(rendered.includes('gigs-recalculate'));assert.ok(rendered.includes('MCN 可按历史协议读取与重算此计提'));assert.equal(rendered.includes('核对原订单与付款退款</a>'),false);session.token=null})
 test('真实商单报价表单保留原offer ID/terms，显式数量分期，拒绝错误双方规格或价格默认',async()=>{const {default:Form}=await server.ssrLoadModule('/src/components/TradeQuoteForm.vue'),offer={...records.OFFER(),current_status:'ACCEPTED',data:{...records.OFFER().data,buyer_accepted_by:id(4)}},spec={id:id(23),kind:'SPEC',merchant_party_id:id(2),current_status:'PUBLISHED',data:{title:'本人服务',provider_party_id:id(2),line_kind:'OTHER',unit_minor:999,currency:'CNY',specification:{version:'v1',service_tier:'完整服务',sample_seconds:0,final_seconds:0,revision_limit:0,deliverables:['明确交付'],terms:'原规格条款'},review:{decision:'APPROVED',reason:'实际审核',account_id:id(5)}}};const router=createRouter({history:createMemoryHistory(),routes:[{path:'/:pathMatch(.*)*',component:{render:()=>null}}]}),app=createSSRApp({render:()=>h(Form,{disabled:false,specs:[spec],offers:[offer],offerId:offer.id})}).use(router);let vm;app.mixin({created(){if(this.$options.__name==='TradeQuoteForm')vm=this.$.setupState}});const html=await renderToString(app);assert.ok(html.includes('原平台费率'));assert.ok(html.includes('保存的原提案'));assert.equal(vm.f.lines[0].qty,'');assert.equal(vm.f.model,'');assert.equal(vm.f.installments[0].allocations[0].amount,'');Object.assign(vm.f,{rule:id(10),expires:'2027-10-01T00:00',window:'60',channel:'ALIPAY',model:'DIRECT_SUPPLIER'});vm.f.lines=[{line:'service',spec:id(23),qty:'1'}];vm.f.installments=[{key:'first',trigger:'ORDER_ACCEPTED',apple:'',allocations:[{line:'service',amount:'999'}]}];assert.equal(vm.payload.commercial_offer_id,id(13));assert.equal(vm.payload.buyer_party_id,id(4));assert.equal(vm.payload.lines[0].quantity,1);vm.f.lines[0].qty='2';assert.equal(vm.payload,null);vm.f.lines[0].qty='1';vm.f.model='PLATFORM_PRINCIPAL';assert.equal(vm.payload,null);vm.f.model='DIRECT_SUPPLIER';vm.f.buyer=id(99);assert.equal(vm.payload,null)})
 for(const {name,run}of tests){await run();console.log(`✓ ${name}`)}console.log(`\n${tests.length} gigs checks passed.`)
}finally{globalThis.fetch=originalFetch;if(oldWindow===undefined)delete globalThis.window;else globalThis.window=oldWindow;if(oldDocument===undefined)delete globalThis.document;else globalThis.document=oldDocument;if(storageProperty)Object.defineProperty(globalThis,'sessionStorage',storageProperty);else delete globalThis.sessionStorage;await server.close()}
