import assert from 'node:assert/strict'
import { fileURLToPath } from 'node:url'
import { createServer } from 'vite'
import vue from '@vitejs/plugin-vue'
import { createSSRApp, effectScope, h, reactive } from 'vue'
import { renderToString } from '@vue/server-renderer'
import { createPinia } from 'pinia'
import { createMemoryHistory, createRouter, RouterView } from 'vue-router'
const root=fileURLToPath(new URL('..',import.meta.url)),server=await createServer({root,configFile:false,plugins:[vue()],resolve:{alias:{'@':`${root}/src`}},server:{middlewareMode:true},appType:'custom'})
const originalFetch=globalThis.fetch,id=n=>`${String(n).padStart(8,'0')}-0000-4000-8000-000000000001`,who={token:'trade-private',accountId:id(1),partyId:id(2)},reviewer={...who,partyId:null},hash='a'.repeat(64),stamp='2026-10-02T00:00:00.000Z',end='2027-10-02T00:00:00.000Z'
const review=()=>({decision:'APPROVED',reason:'明确审核依据',account_id:id(4)})
const specification=()=>({version:'原版本',service_tier:'明确档位',sample_seconds:30,final_seconds:120,revision_limit:2,deliverables:['已约定交付'],terms:'保存的旧条款 <script>literal</script>'})
const specData=()=>({title:'明确服务',provider_party_id:id(3),line_kind:'PRODUCTION',unit_minor:12345,currency:'CNY',specification:specification(),review:review()})
const quoteData=()=>({lines:[{...specData(),line_id:'production',spec_id:id(10),spec_version:1,quantity:2,total_minor:24690}],installments:[{key:'首期',trigger:'ORDER_ACCEPTED',allocations:[{line_id:'production',amount_minor:24690}],apple_product_id:null}],total_minor:24690,currency:'CNY',channel:'ALIPAY',transaction_model:'DIRECT_SUPPLIER',rule_id:id(7),expires_at:end,payment_window_minutes:60,license_reservation_id:null,review:review()})
const contract=()=>({format_version:'contract-content-v1',id:id(5),contract_version_id:id(6),party_ids:[id(2),id(3)],created_at:stamp,rule_contents:[{format_version:'rule-content-v1',id:id(7),rule_key:'trade',version:'1',terms:{text:'旧规则'},content_sha256:hash}],commitments:{text:'旧合同 <script>literal</script>'},object_version:1,current_status:'SEALED',signing_method:'NOT_SIGNED',content_sha256:hash})
const base=(kind,n,status,data)=>({id:id(n),kind,buyer_party_id:kind==='SPEC'?null:id(2),merchant_party_id:id(3),parent_id:null,order_id:null,created_by:id(1),current_status:status,object_version:1,content_sha256:hash,data})
const spec=()=>({...base('SPEC',10,'PUBLISHED',specData()),merchant_party_id:id(2)})
const quote=()=>base('QUOTE',11,'APPROVED',quoteData())
const order=()=>({...base('ORDER',12,'OPEN',{quote:quoteData(),contract:contract(),buyer_acknowledged_by:id(1),financial:{received_minor:0,refunded_minor:0,net_minor:0}}),parent_id:id(11)})
const payment=()=>({...base('PAYMENT',13,'SUCCEEDED',{provider:'ALIPAY',environment:'SANDBOX',app_id:'app',merchant_id:'merchant',currency:'CNY',amount_minor:24690,config_revision:'1',allocations:[{line_id:'production',amount_minor:24690}],installment_key:'首期',apple_product_id:null,title:'原付款',payment_window_minutes:60,expires_at:end,checkout:{kind:'ALIPAY_APP',order_string:'secret-checkout-never-render'},transaction_id:'real-transaction',proof:null}),order_id:id(12)})
const refund=()=>({...base('REFUND',14,'REQUESTED',{provider:'ALIPAY',environment:'SANDBOX',app_id:'app',merchant_id:'merchant',currency:'CNY',amount_minor:100,payment_id:id(13),allocations:[{line_id:'production',amount_minor:100}],transaction_id:'real-transaction',apple_product_id:null,reason:'明确原款退款依据',review:null}),order_id:id(12),parent_id:id(13)})
const legacy=()=>base('LEGACY',15,'NEEDS_REVIEW',{source_system:'旧系统',source_order_id:'旧编号',original_lines:[{line_id:'old',amount_minor:99,reported_status:'REPORTED_PAID'}],original_terms:'原条款',evidence_asset_id:id(16),currency:'CNY',payment_verified:false,review:null})
const response=(data,i=who)=>new Response(JSON.stringify({meta:{request_id:'trade-test',actor:{account_id:i.accountId},acting_party:i.partyId},data}),{status:200,headers:{'Content-Type':'application/json'}})
const failure=(status,code)=>new Response(JSON.stringify({error:{code,message:'test-only',retryable:false,details:[]}}),{status,headers:{'Content-Type':'application/json'}})
const defer=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve}}
const tests=[],test=(name,run)=>tests.push({name,run})
try{
 const api=await server.ssrLoadModule('/src/api/modules/trade.ts'),{useTrade}=await server.ssrLoadModule('/src/composables/useTrade.ts'),{loginRedirect}=await server.ssrLoadModule('/src/router/loginRedirect.ts'),{tradeRoutes}=await server.ssrLoadModule('/src/router/tradeRoutes.ts')
 const state=(admin=false)=>{const context=reactive({...admin?reviewer:who,revision:0,scope:'trade'}),scope=effectScope(),ui=scope.run(()=>useTrade(()=>context));return {ui,context,scope}}
 const command=()=>({path:'/trade/payments',body:{order_id:id(12),installment_key:'首期'},resultKind:'PAYMENT',label:'建立本期付款记录'})
 test('实DTO包含六类记录；拒绝错误金额、币种、规格和款项计算',async()=>{for(const f of [spec,quote,order,payment,refund,legacy])assert.ok(api.isTradeRecord(f()));for(const change of [r=>r.data.amount_minor=0.01,r=>r.data.currency='USD',r=>r.data.allocations[0].amount_minor=1,r=>r.data.checkout={kind:'WEB_READY'}]){const p=payment();change(p);assert.equal(api.isTradeRecord(p),false)}const q=quote();q.data.lines[0].specification.deliverables=Array.from({length:31},(_,n)=>`d${n}`);assert.equal(api.isTradeRecord(q),false);const o=order();o.data.financial.net_minor=1;assert.equal(api.isTradeRecord(o),false)})
 test('列表按kind和cursor分页，普通OWNER有身份，审核不传身份；私有读取no-store',async()=>{const calls=[];globalThis.fetch=async(url,o)=>{calls.push({url,o});return response({items:[],next_cursor:null},o.headers['X-Acting-Party']?who:reviewer)};await api.listTrade(who,'SPEC',id(99));await api.listTrade(reviewer,'REFUND');assert.equal(calls[0].url,`/api/v1/trade/records?kind=SPEC&limit=20&cursor=${id(99)}`);assert.equal(calls[0].o.headers['X-Acting-Party'],id(2));assert.equal(calls[1].o.headers['X-Acting-Party'],undefined);assert.ok(calls.every(c=>c.o.cache==='no-store'));globalThis.fetch=async()=>response(quote(),{...who,partyId:id(99)});await assert.rejects(api.getTrade(who,id(11)),e=>e.code==='UNEXPECTED_RESPONSE_SHAPE')})
 test('报价确认原样提交指纹，If-Match保留原版本；后台审核不传身份',async()=>{const calls=[];globalThis.fetch=async(url,o)=>{calls.push({url,o});return response(url.includes('acceptance')?order():spec(),url.includes('reviews')?reviewer:who)};await api.postTrade(who,{path:`/trade/quotes/${id(11)}/acceptance`,body:{quote_sha256:hash},version:4,targetId:id(11),resultKind:'ORDER',label:'确认'},'exact-key');await api.postTrade(reviewer,{path:`/trade/records/${id(10)}/reviews`,body:{decision:'APPROVED',reason:'依据'},version:2,targetId:id(10),resultKind:'SPEC',label:'审核'},'review-key');assert.equal(calls[0].o.headers['If-Match'],'"4"');assert.deepEqual(JSON.parse(calls[0].o.body),{quote_sha256:hash});assert.equal(calls[1].o.headers['X-Acting-Party'],undefined);assert.equal(calls[1].o.headers['If-Match'],'"2"')})
 test('所有503按结果未知保留原key/body/version；先核对再同key重放',async()=>{const {ui,scope}=state(),calls=[];let posts=0;globalThis.fetch=async(url,o)=>{calls.push({url,o});return o.method==='POST'?++posts===1?failure(503,'SERVICE_UNAVAILABLE'):response(payment()):response(url.includes('?')?{items:[payment()],next_cursor:null}:payment())};const c=command();await ui.write(c);assert.ok(ui.pending.value);assert.equal(ui.canNavigate(),false);assert.equal(ui.pending.value.state,'unknown');const key=ui.pending.value.key;c.body.installment_key='后改的值';await ui.retry();assert.equal(posts,1);await ui.checkPending();assert.ok(ui.pending.value.checked);await ui.retry();assert.equal(posts,2);const writes=calls.filter(c=>c.o.method==='POST');assert.equal(writes[0].o.headers['Idempotency-Key'],key);assert.equal(writes[1].o.headers['Idempotency-Key'],key);assert.equal(writes[0].o.body,writes[1].o.body);assert.equal(ui.pending.value,null);assert.equal(ui.detail.value.current_status,'SUCCEEDED');scope.stop()})
 test('断流和网络异常保留原请求，不自动另建付款或退款',async()=>{for(const broken of [async()=>{throw Error('network')},async()=>({ok:true,status:200,headers:new Headers(),text:async()=>{throw Error('stream')}})]){const {ui,scope}=state();globalThis.fetch=broken;await ui.write(command());assert.equal(ui.pending.value.state,'unknown');assert.equal(ui.canNavigate(),false);scope.stop()}})
 test('已知POST记录读取失败保留resultId，核对只GET不重POST',async()=>{const {ui,scope}=state();let posts=0;globalThis.fetch=async(url,o)=>o.method==='POST'?(posts++,response(payment())):failure(503,'SERVICE_UNAVAILABLE');await ui.write(command());assert.equal(ui.pending.value.resultId,id(13));assert.equal(ui.pending.value.state,'refresh');globalThis.fetch=async()=>response(payment());await ui.checkPending();assert.equal(posts,1);assert.equal(ui.pending.value,null);assert.equal(ui.detail.value.id,id(13));scope.stop()})
 test('412读取最新版本，清空旧操作并要求重新确认，不自动重放',async()=>{const {ui,scope}=state();const fresh={...quote(),object_version:5};let posts=0;globalThis.fetch=async(url,o)=>o.method==='POST'?(posts++,failure(412,'VERSION_MISMATCH')):response(fresh);await ui.write({path:`/trade/quotes/${id(11)}/acceptance`,body:{quote_sha256:hash},version:1,targetId:id(11),resultKind:'ORDER',label:'确认'});assert.equal(posts,1);assert.equal(ui.pending.value,null);assert.equal(ui.conflictRevision.value,1);assert.equal(ui.detail.value.object_version,5);await ui.retry();assert.equal(posts,1);scope.stop()})
 test('401/403/404清空私有内容、原操作和关联材料状态',async()=>{for(const status of [401,403,404]){const {ui,scope}=state();ui.rows.value=[quote()];ui.detail.value=order();ui.related.value=[payment()];globalThis.fetch=async()=>failure(status,'TRADE_PARTY_FORBIDDEN');await ui.write(command());assert.equal(ui.detail.value,null);assert.deepEqual(ui.rows.value,[]);assert.deepEqual(ui.related.value,[]);assert.equal(ui.pending.value,null);scope.stop()}})
 test('身份A→B→A、会话修订、退出和换页丢弃迟到请求',async()=>{for(const change of [c=>{c.partyId=id(99);c.partyId=id(2)},c=>c.token=null,c=>c.revision++,c=>c.scope='other']){const {ui,context,scope}=state(),late=defer();globalThis.fetch=()=>late.promise;const p=ui.loadRecord(id(11));change(context);late.resolve(response(quote()));await p;assert.equal(ui.detail.value,null);scope.stop()}const {ui,context,scope}=state(),late=defer();globalThis.fetch=()=>late.promise;const p=ui.write(command(),()=>assert.fail('late callback'));context.partyId=id(99);late.resolve(response(payment()));await p;assert.equal(ui.pending.value,null);assert.equal(ui.detail.value,null);scope.stop()})
 test('同身份换记录，旧403不清除新的有效详情；分页不能循环',async()=>{const {ui,scope}=state(),first=defer(),second=defer();let n=0;globalThis.fetch=()=>++n===1?first.promise:second.promise;const a=ui.loadRecord(id(11)),b=ui.loadRecord(id(12));first.resolve(failure(403,'TRADE_PARTY_FORBIDDEN'));await a;second.resolve(response(order()));await b;assert.equal(ui.detail.value.id,id(12));globalThis.fetch=async()=>response({items:[quote()],next_cursor:id(99)});await ui.loadAll('QUOTE');assert.equal(ui.error.value.code,'UNEXPECTED_RESPONSE_SHAPE');scope.stop()})
 test('金额整数分精确显示元，输入不接受小数/指数/隐含商业值',async()=>{assert.equal(api.money(99),'¥0.99');assert.equal(api.money(4901),'¥49.01');assert.equal(api.money(900000000000),'¥9,000,000,000.00');for(const v of ['', '1.23','1e3','-1','01','900000000001'])assert.equal(api.amountInput(v),null);assert.equal(api.amountInput('0',0),0)})
 test('退款逐付款明细扣除已有申请，Apple仅全额，待核实款不能申请',async()=>{const p=payment(),r=refund();assert.deepEqual(api.refundable(p,[r]),[{line_id:'production',amount_minor:24590}]);assert.ok(api.validRefund(p,[r],[{line_id:'production',amount_minor:100}]));assert.equal(api.validRefund(p,[r],[{line_id:'production',amount_minor:24690}]),false);assert.equal(api.validRefund({...p,current_status:'UNKNOWN'},[],p.data.allocations),false);p.data.provider='APPLE';assert.equal(api.validRefund(p,[],[{line_id:'production',amount_minor:100}]),false);assert.equal(api.validRefund(p,[],p.data.allocations),true);assert.equal(api.validRefund(p,[r],p.data.allocations),false);assert.match(api.tradeStatus({...r,current_status:'APPROVED'}),/尚未退款/);assert.match(api.tradeStatus({...r,current_status:'AWAITING_APPLE_REQUEST'}),/等待用户/)})
 test('付款核对不传If-Match，支付宝transaction_id必须null；退款执行空JSON',async()=>{const calls=[];globalThis.fetch=async(url,o)=>{calls.push({url,o});return response(url.includes('execution')?refund():payment(),url.includes('execution')?reviewer:who)};await api.postTrade(who,{path:`/trade/payments/${id(13)}/reconciliation`,body:{transaction_id:null},targetId:id(13),resultKind:'PAYMENT',label:'核实'},'reconcile-key');await api.postTrade(reviewer,{path:`/trade/refunds/${id(14)}/execution`,body:{},targetId:id(14),resultKind:'REFUND',label:'执行'},'execute-key');assert.equal(calls[0].o.headers['If-Match'],undefined);assert.deepEqual(JSON.parse(calls[0].o.body),{transaction_id:null});assert.deepEqual(JSON.parse(calls[1].o.body),{});assert.equal(calls[1].o.headers['X-Acting-Party'],undefined)})
 test('历史附件走本记录私有字节接口，保留原报告状态不伪造到账',async()=>{let call;globalThis.fetch=async(url,o)=>{call={url,o};return new Response('original-private',{headers:{'Content-Type':'application/octet-stream'}})};const blob=await api.legacyBytes(reviewer,id(15),id(16));assert.equal(await blob.text(),'original-private');assert.equal(call.url,`/api/v1/trade/legacy-orders/${id(15)}/evidence/${id(16)}/content`);assert.equal(call.o.headers['X-Acting-Party'],undefined);assert.equal(call.o.cache,'no-store');const l=legacy();l.data.payment_verified=true;assert.equal(api.isTradeRecord(l),false)})
 test('真实SSR记录组件转义合同和旧条款，支付字符串/令牌不展示',async()=>{const {default:Panel}=await server.ssrLoadModule('/src/components/TradeRecordPanel.vue');for(const r of [order(),payment(),refund(),legacy()]){const html=await renderToString(createSSRApp({render:()=>h(Panel,{record:r})}));assert.equal(html.includes('<script>literal</script>'),false);assert.equal(html.includes('secret-checkout-never-render'),false);if(r.kind==='ORDER'){assert.ok(html.includes('&lt;script&gt;literal&lt;/script&gt;'));assert.ok(html.includes('尚未签署'));assert.ok(html.includes('¥246.90'))}}})
 test('真实SSR规格/报价表单商业字段空白且存在多行、分期和30项约束',async()=>{const {default:Spec}=await server.ssrLoadModule('/src/components/TradeSpecForm.vue'),{default:Quote}=await server.ssrLoadModule('/src/components/TradeQuoteForm.vue');const formRouter=createRouter({history:createMemoryHistory(),routes:[{path:'/:pathMatch(.*)*',component:Spec}]}),s=await renderToString(createSSRApp({render:()=>h(Spec,{disabled:false})}).use(formRouter)),q=await renderToString(createSSRApp({render:()=>h(Quote,{disabled:false,specs:[]})}).use(formRouter));assert.ok(s.includes('整数分'));assert.ok(s.includes('最多 30 项'));assert.ok(q.includes('添加服务明细'));assert.ok(q.includes('添加分期'));assert.ok(q.includes('分摊之和'));assert.ok(q.includes('待选择'));assert.equal(/value="(?:60|99|4901)"/.test(s+q),false)})
 test('正式交易路由与安全登录返回一致，新版本/审核/详情都有唯一菜单高亮',async()=>{const oldWindow=globalThis.window,oldStorage=Object.getOwnPropertyDescriptor(globalThis,'sessionStorage'),storage=new Map();globalThis.window={setInterval:()=>0,clearInterval:()=>{},addEventListener:()=>{},removeEventListener:()=>{}};Object.defineProperty(globalThis,'sessionStorage',{configurable:true,value:{getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,String(v)),removeItem:k=>storage.delete(k)}});try{for(const [path,current] of [['/trade/quotes','/trade/quotes'],['/trade/specifications/new','/trade/specifications'],[`/trade/specifications/${id(10)}/new`,'/trade/specifications'],[`/trade/orders/${id(12)}`,'/trade/quotes'],['/trade/payments/new','/trade/payments'],[`/trade/refunds/${id(14)}`,'/trade/payments'],['/trade/legacy/new','/trade/payments'],[`/trade/reviews/specifications/${id(10)}`,'/trade/reviews/specifications'],[`/trade/reviews/quotes/${id(11)}`,'/trade/reviews/quotes'],[`/trade/reviews/legacy/${id(15)}`,'/trade/reviews/refunds']]){assert.equal(loginRedirect(path),path);const router=createRouter({history:createMemoryHistory(),routes:[...tradeRoutes,{path:'/:pathMatch(.*)*',component:{render:()=>null}}]}),app=createSSRApp({render:()=>h(RouterView)}).use(createPinia()).use(router);await router.push(path);await router.isReady();assert.notEqual(router.currentRoute.value.name,undefined);const html=await renderToString(app),nav=html.match(/<nav\b[^>]*aria-label="工作区导航"[^>]*>([\s\S]*?)<\/nav>/)?.[1];assert.ok(nav);const currentLinks=[...nav.matchAll(/<a\b([^>]*)>/g)].filter(([,attrs])=>attrs.includes('aria-current="page"')).map(([,attrs])=>attrs.match(/\bhref="([^"]+)"/)?.[1]);assert.deepEqual(currentLinks,[current]);for(const label of ['账号与机构','合同与规则','供给申请','我的作品','选剧本','许可商品','许可办理','项目与绑定','受控阅稿','商品规格','报价订单','付款退款','制作项目','供给审核','作品审核','许可核验','规格审核','报价审核','退款与旧单核对','制作独立核验','项目选角','项目会签','项目发行','渠道档案','项目独立核验'])assert.ok(nav.includes(label))}for(const bad of ['/trade/admin','/trade/quotes?role=TRADE_REVIEW','//foreign/trade/quotes','/trade/quotes/bad','/trade/orders/new','/trade/reviews/payments'])assert.equal(loginRedirect(bad),'/workspace')}finally{if(oldWindow===undefined)delete globalThis.window;else globalThis.window=oldWindow;if(oldStorage)Object.defineProperty(globalThis,'sessionStorage',oldStorage);else delete globalThis.sessionStorage}})
 for(const {name,run}of tests){await run();console.log(`✓ ${name}`)}console.log(`\n${tests.length} trade checks passed.`)
}finally{globalThis.fetch=originalFetch;await server.close()}
